### ISSUE TITLE
HorizontalCellStyleStrategy 策略设置单元格样式没有起作用

### ISSUE THREAD

**Issue by fengsmith** [alibaba/easyexcel#1000]
**触发场景描述**
在你们提供的 demo 
com.alibaba.easyexcel.test.demo.write.WriteTest.styleWrite() 方法中，如果把表头设置去掉的话，excel 的样式设置 HorizontalCellStyleStrategy 策略就不起作用了。

**触发Bug的代码**
```
       
        EasyExcel.write(fileName).registerWriteHandler(horizontalCellStyleStrategy).sheet("模板")
            .doWrite(data());

   
```
**提示的异常或者没有达到的效果**
HorizontalCellStyleStrategy 设置单元的策略没有生效，把 excel 表头设置加上就好了，去掉就不行。

加表头后导出的 excel 效果:
![image](https://user-images.githubusercontent.com/6457270/71239755-55a65800-2342-11ea-8662-48ad90848062.png)
去掉表头后导出的 excel 效果:

![image](https://user-images.githubusercontent.com/6457270/71239945-cf3e4600-2342-11ea-87a9-a52b7184f257.png)

**Comment by pdkst** [comment]
![image](https://user-images.githubusercontent.com/8915631/71266782-139e0600-2384-11ea-92a6-d9f9bfced2af.png)
未重现，尝试升级下版本看看

**Comment by zhuangjiaju** [comment]
请参照楼上升级到最新版本。如果还有问题，请重新打开issue

**Comment by fengsmith** [comment]
我是克隆的 easyexcel 的源码，不是依赖的 jar 包，分支是 master ，今天又 pull 了下最新的代码，pull 完之后还是有问题。

![image](https://user-images.githubusercontent.com/6457270/71332080-c54d5a80-256f-11ea-9dd0-310fa3ffadf0.png)
