### ISSUE TITLE
ExcelIgnore  和 ExcelProperty  混用 ，index失效

### ISSUE THREAD

**Issue by Hfate** [alibaba/easyexcel#1002]
例如
` 
   @ExcelIgnore
    private Long id;

    /**
     * 员工工号
     */
    @ExcelProperty(index = 1)
    @TableField("workerId")
    private Long workerId;

    @ExcelProperty(index = 3)
    private String workerName;

    @ExcelProperty(index = 2)
    private Long globalId;

    @ExcelIgnore
    private Long groupId;

    @ExcelProperty(index = 13)
    private String groupName;`

**Comment by pdkst** [comment]
![image](https://user-images.githubusercontent.com/8915631/71267420-72b04a80-2385-11ea-87d4-0202b1d446e3.png)
未重现，请尝试更新版本

**Comment by zhuangjiaju** [comment]
是否已经解决问题？如果未解决请重新打开问题。
