### ISSUE TITLE
前端调用导出接口没有出弹框下载，返回的是一堆乱码，如何解决？请赐教！

### ISSUE THREAD

**Issue by shuaizi777** [alibaba/easyexcel#1008]
前端调用导出接口没有出弹框下载，返回的是一堆乱码，如何解决？请赐教！

**Comment by zhuangjiaju** [comment]
请参照下载demo书写。

**Comment by frozenfires** [comment]
前台模拟点击链接
let blob = new Blob([response.data], {type: "application/vnd.ms-excel"});
let link = document.createElement('a');
link.href = window.URL.createObjectURL(blob);
link.download = response.config.fileName;
link.click();
