### ISSUE TITLE
我如何判断我读取的excel是我想处理的excel，我用invokeHeadMap判断完表头数据后，发现表头数据不对，发现抛出异常不能中断invoke的读取。

### ISSUE THREAD

**Issue by Drcary** [alibaba/easyexcel#1011]
我的意思是想在读取excel的时候，判断一下这个excel是不是我想要的那个excel，再进行导入，我发现我用一个相似的excel导入，也能导入，但是不是我想要的excel数据

**Comment by lxdnn** [comment]
onException中捕捉该异常并抛出异常可中断读取

**Comment by Drcary** [comment]
thanks!    I see！！！
