### ISSUE TITLE
请求下Excel导出行首怎么带空格进去

### ISSUE THREAD

**Issue by heyaping388** [alibaba/easyexcel#1016]
如图我合并单元格后，想最后一个起始位置想要带几个空格。
![image](https://user-images.githubusercontent.com/25815555/71400877-0e320b80-2663-11ea-882b-48d7e4e435f2.png)
实际导出效果
![image](https://user-images.githubusercontent.com/25815555/71400909-27d35300-2663-11ea-9a2a-e51dd1242526.png)
代码：
![image](https://user-images.githubusercontent.com/25815555/71400941-43d6f480-2663-11ea-9e89-6d417cb6aeff.png)
求助怎么导出到前面带空格的

**Comment by zhuangjiaju** [comment]
设置`autoTrim`=ture
