### ISSUE TITLE
考虑升级到POI 4.1版本吗？^_^

### ISSUE THREAD

**Issue by DerekHQ** [alibaba/easyexcel#1019]

**Comment by zhuangjiaju** [comment]
您本地项目直接升级即可，兼容4.1. 目前不考虑升级到4.1 升级到4.1需要将jdk由1.6升级到1.8.要照顾很多用jdk1.6的同学。

**Comment by Tango-Chen** [comment]
本地项目到4.1后，需要在pom中把easyexcel的poi排除
