### ISSUE TITLE
有java模型映射下读取多个sheet页，只会使用第一个sheet模型

### ISSUE THREAD

**Issue by haopangang** [alibaba/easyexcel#102]
如果多sheet页和有多个模型的话，导致后面的模型无法创建，一直用的是第一个模型。是以下代码的问题
`public void buildExcelHeadProperty(Class<? extends BaseRowModel> clazz, List<String> headOneRow) {
        if (this.excelHeadProperty == null && (clazz != null || headOneRow != null)) {
            this.excelHeadProperty = new ExcelHeadProperty(clazz, new ArrayList<List<String>>());
        }
        if (this.excelHeadProperty.getHead() == null && headOneRow != null) {
            this.excelHeadProperty.appendOneRow(headOneRow);
        }
    }`

**Comment by cc-cfg** [comment]
我这边也遇到这个问题了，准备自己更新包

**Comment by cc-cfg** [comment]
多sheet，对应对model，这个bug会导致最后数据都是第一个model类型的

**Comment by cc-cfg** [comment]
貌似要改动的代码不少，无果，只能换一种方法去读取解析，多读几次

**Comment by youlanqiang** [comment]
我们好像都是同一个问题

**Comment by youlanqiang** [comment]
我现在最快的解决方法就是不用head,直接当row插入进去。。

**Comment by cc-cfg** [comment]
> 我现在最快的解决方法就是不用head,直接当row插入进去。。

应该是差不多的问题，我这边是读取一个excel，该excel里面有多个sheet，需要一个sheet对应一个model，其实这个model就是对应一张数据表，这里的bug就是一直只会一第一个model作为后续数据的结构。
尝试修改重新编译源码无果，现在只能读多次该文件，读一次 对应一个sheet

**Comment by haopangang** [comment]
> 貌似要改动的代码不少，无果，只能换一种方法去读取解析，多读几次

改动的代码不多，只需每次赋值新的Sheet时。把之前的信息清空掉即可。

**Comment by cc-cfg** [comment]
> > 貌似要改动的代码不少，无果，只能换一种方法去读取解析，多读几次
> 
> 改动的代码不多，只需每次赋值新的Sheet时。把之前的信息清空掉即可。

能贴下代码不，或者直接来个重新打包后的jar   ，/手动微笑

**Comment by jipengfei-jpf** [comment]
1.1.2-beat1已经修复这个问题，谢谢你的问题
