### ISSUE TITLE
表头设置样式无效

### ISSUE THREAD

**Issue by QweikChris** [alibaba/easyexcel#1020]
![image](https://user-images.githubusercontent.com/13342522/71418929-195b5a80-26a8-11ea-974c-46cb18cbe55f.png)
![image](https://user-images.githubusercontent.com/13342522/71418951-33953880-26a8-11ea-9463-93a0ac745f47.png)

**Comment by QweikChris** [comment]
@Override
            public void afterSheetCreate(WriteWorkbookHolder writeWorkbookHolder, WriteSheetHolder writeSheetHolder) {
                // 内容的策略
                WriteCellStyle headtWriteCellStyle = new WriteCellStyle();
                // 这里需要指定 FillPatternType 为FillPatternType.SOLID_FOREGROUND 不然无法显示背景颜色.头默认了 FillPatternType所以可以不指定
                headtWriteCellStyle.setFillPatternType(FillPatternType.SOLID_FOREGROUND);
                // 背景绿色
                headtWriteCellStyle.setFillForegroundColor(IndexedColors.DARK_BLUE.getIndex());
                WriteFont contentWriteFont = new WriteFont();
                // 字体大小
                contentWriteFont.setFontHeightInPoints((short)20);
                headtWriteCellStyle.setWriteFont(contentWriteFont);

                headCellStyle = StyleUtil.buildHeadCellStyle(writeWorkbookHolder.getWorkbook(), headtWriteCellStyle);

                // 头的策略
                WriteCellStyle contentWriteCellStyle = new WriteCellStyle();
                // 背景设置为红色
                contentWriteCellStyle.setFillPatternType(FillPatternType.SOLID_FOREGROUND);
                contentWriteCellStyle.setFillForegroundColor(IndexedColors.LIGHT_BLUE.getIndex());
                WriteFont headWriteFont = new WriteFont();
                headWriteFont.setFontHeightInPoints((short)20);
                contentWriteCellStyle.setWriteFont(headWriteFont);

                contentCellStyle = StyleUtil.buildContentCellStyle(writeWorkbookHolder.getWorkbook(), contentWriteCellStyle);
            }

            @Override
            public void beforeCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Row row, Head head, Integer columnIndex, Integer relativeRowIndex, Boolean isHead) {

            }

            @Override
            public void afterCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {
                if (isHead) {
                    cell.setCellStyle(headCellStyle);
                } else {
                    cell.setCellStyle(contentCellStyle);
                }

            }

**Comment by zhuangjiaju** [comment]
参照自定义样式试试？

**Comment by zhuangjiaju** [comment]
是否已经解决？如果未解决 请重新打开问题。

**Comment by fygit01** [comment]
生成的样式内容单元格是有效的，表头单元格无效，请问什么问题？
String fileName = "D:\\test0202.xlsx";
        EasyExcel.write(fileName)
                .head(head())
                .sheet("模板")
                .useDefaultStyle(false)
                .registerWriteHandler(new MyStyleExcelHandler())
                .doWrite(data());


@Slf4j
public class MyStyleExcelHandler implements CellWriteHandler {
    @Override
    public void beforeCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Row row, Head head, Integer integer, Integer integer1, Boolean aBoolean) {

    }

    @Override
    public void afterCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Cell cell, Head head, Integer integer, Boolean aBoolean) {

    }

    @Override
    public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, List<CellData> list, Cell cell, Head head, Integer integer, Boolean aBoolean) {
        if (cell.getColumnIndex() == 1) {
            Workbook workbook = writeSheetHolder.getSheet().getWorkbook();
            CellStyle cellStyle = workbook.createCellStyle();
            cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            cellStyle.setFillForegroundColor(IndexedColors.BLUE.getIndex());
            `cell.setCellStyle(cellStyle);`
        }
    }
