### ISSUE TITLE
导出xlsx文件，打开提示“部分内容有问题，是否让我们尽量尝试恢复？”

### ISSUE THREAD

**Issue by soygrow** [alibaba/easyexcel#1025]
**触发场景描述**
![image](https://user-images.githubusercontent.com/19327340/71445647-38182a80-2756-11ea-8e3e-62195110d5fa.png)

下面是导出有问题的表格文件
[1577274701056.xlsx](https://github.com/alibaba/easyexcel/files/4000448/1577274701056.xlsx)

使用版本
```
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>2.1.3</version>
        </dependency>
```
**触发Bug的代码**
```java
List<NumberExportData> numberExportData = numberManagerService.numberExport(cloudAccountId, mode,
                        telX, areaCode, buyStartTime, buyEndTime);

LOGGER.info("numberExport controller result size: {}", numberExportData.size());
response.setContentType("application/vnd.ms-excel");
response.setCharacterEncoding("utf-8");
response.setHeader("Content-disposition",
                        "attachment;filename=" + System.currentTimeMillis() + ".xlsx");

EasyExcel.write(response.getOutputStream(), NumberExportData.class).excelType(ExcelTypeEnum.XLSX)
                        .sheet("号码列表").doWrite(numberExportData);
```
**提示的异常或者没有达到的效果**

**Comment by codefinally** [comment]
我在swagger里面下载也是同样的问题 直接浏览器地址上下载就没问题

**Comment by zhuangjiaju** [comment]
目前仅仅支持浏览器直接下载。其他任何框架需要自己对流做兼容处理。

**Comment by GavinAlison** [comment]
为何使用chrome下载，出现上述问题，使用的代码是源代码测试中的demo/web/WebTest. 
![image](https://user-images.githubusercontent.com/18605679/71763634-13237480-2f19-11ea-9911-a681cb81e083.png)

**Comment by GavinAlison** [comment]
版本v2.1.5

**Comment by soygrow** [comment]
> 目前仅仅支持浏览器直接下载。其他任何框架需要自己对流做兼容处理。

我是用浏览器下载的，仍然有这个问题。

**Comment by soygrow** [comment]
> 目前仅仅支持浏览器直接下载。其他任何框架需要自己对流做兼容处理。

是谷歌浏览器，怎么试都有这样的问题，不知道有没有解决方法。或者我可以尝试修改什么

**Comment by lIAn0110** [comment]
> > 目前仅仅支持浏览器直接下载。其他任何框架需要自己对流做兼容处理。
> 
> 是谷歌浏览器，怎么试都有这样的问题，不知道有没有解决方法。或者我可以尝试修改什么

解决了吗？偶然出现了一次 暂时不确定原因

**Comment by pianozcl** [comment]
3.0.1每次导出都有这个问题

**Comment by zzyymaggie** [comment]
将接口的返回类型设置为void,使用response导出数据 就可以避免这个问题了
参考[https://www.cnblogs.com/ziyue7575/p/12697648.html](url)

**Comment by amumus** [comment]
如果使用spring mvc，将接口的返回类型设置为void之后确实能解决，原因其实返回值后面拼接多了一部分字符，留意自己的接口返回
