### ISSUE TITLE
使用AnalysisEventListener如何返回异常信息

### ISSUE THREAD

**Issue by zhoujingtian4** [alibaba/easyexcel#1026]
在Listener里invoke方法处理数据，如果处理发现异常该用什么方式返回到页面？

**Comment by lxdnn** [comment]
同问

**Comment by zhuangjiaju** [comment]
直接抛出异常即可。目前版本可能要e.getCause才能获取到您自定义的异常。下个版本准备改成直接抛出就是自己的异常。
