### ISSUE TITLE
2.1.3版本autoCloseStream设置为false也会自动关闭流

### ISSUE THREAD

**Issue by magicCJ** [alibaba/easyexcel#1029]
**触发场景描述**
InputStream先用于读取excel，再用于上传到oss
**触发Bug的代码**
```java
   EasyExcel.read(is, Order.class, listener)
                .autoCloseStream(false)
                .sheet()
                .headRowNumber(3)
                .doReadSync();
```
**提示的异常或者没有达到的效果**
上传oss的时候出现
java.io.IOException: Stream closed

**Comment by zhuangjiaju** [comment]
贴全异常。然后流怎么可以读取2遍？

**Comment by zhuangjiaju** [comment]
是否已经解决了该问题？如果未解决 请重新打开

**Comment by ZanePoe** [comment]
遇到同样得问题，按道理设置自动关闭流为false,就是为了避免输出多个excel到同一输出流时流被自动关闭。但在debug时发现，在WriteContextImpl.java 339行代码写入流的时候输出流就被关闭了，而AutoCloseStream的判断在WriteContextImpl.java 356才执行，此时已经关闭了流。
![image](https://user-images.githubusercontent.com/16047426/122784442-0f3e0a80-d2e5-11eb-8d07-ee3a780eefe1.png)

**Comment by youmu1** [comment]
> 遇到同样得问题，按道理设置自动关闭流为false,就是为了避免输出多个excel到同一输出流时流被自动关闭。但在debug时发现，在WriteContextImpl.java 339行代码写入流的时候输出流就被关闭了，而AutoCloseStream的判断在WriteContextImpl.java 356才执行，此时已经关闭了流。
> ![image](https://user-images.githubusercontent.com/16047426/122784442-0f3e0a80-d2e5-11eb-8d07-ee3a780eefe1.png)

请问您问题解决了吗？

**Comment by qDonl** [comment]
> 遇到同样得问题，按道理设置自动关闭流为false,就是为了避免输出多个excel到同一输出流时流被自动关闭。但在debug时发现，在WriteContextImpl.java 339行代码写入流的时候输出流就被关闭了，而AutoCloseStream的判断在WriteContextImpl.java 356才执行，此时已经关闭了流。 ![image](https://user-images.githubusercontent.com/16047426/122784442-0f3e0a80-d2e5-11eb-8d07-ee3a780eefe1.png)

你好, 解决了吗
