### ISSUE TITLE
Formula records

### ISSUE THREAD

**Issue by busrauman** [alibaba/easyexcel#1031]
**异常代码**
```java
public class DataListener extends AnalysisEventListener<Data> {

   @Override
    public void invoke(Data data, AnalysisContext context) {
       // how to get current row is formula
    }
}
```
**异常提示**
How to understant the record is formula or not in my invoke method? 
**建议描述**

**Comment by zhuangjiaju** [comment]
Generics use `CellData` and then `celldata.formula`, It means whether it's a formula or not.
