### ISSUE TITLE
请教个关于easyexcel的问题

### ISSUE THREAD

**Issue by aiwthao** [alibaba/easyexcel#1034]
这里写你的代码
   {
    private String vin;
    private Long acquisitionTime;
    private String imsi;
    private BigDecimal speed;
    private BigDecimal direction;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private List<StatusInfo> statusInfos;
}

    public class StatusInfo {
    private String signalName;
    private String unit;
    private String code;
    private String name;
    private String id;
    private Object value;
    }

像这种数据结构的对象 想把StatusIndfo里面的数据也一并导出  请问可以做得到吗

**Comment by zhuangjiaju** [comment]
目前不支持，仅仅支持一级对象。
