### ISSUE TITLE
读取手机号时候变成科学计算法

### ISSUE THREAD

**Issue by HusenHuang** [alibaba/easyexcel#1038]
读取手机号时候变成科学计算法

**Comment by HusenHuang** [comment]
使用Map去接收

public class AbstractReadTaskMapListener extends AnalysisEventListener<Map<Integer, String>> {

}

**Comment by HusenHuang** [comment]
试了一下 最新版本的也有这个问题

**Comment by HusenHuang** [comment]
![image](https://user-images.githubusercontent.com/26651752/71567005-f3deae80-2af6-11ea-84e8-fa61403aad7c.png)

**Comment by zhuangjiaju** [comment]
用`@NumberFormat`注解来处理。这个会在下个大版本解决。

**Comment by HusenHuang** [comment]
没有用实体类去接受，这里使用的Map去接收数据，无法使用注解

**Comment by HusenHuang** [comment]
目前暂时使用new BigDecimal() 去处理这个问题
