### ISSUE TITLE
如何根据导出内容，设置Row的样式？比如背景之类的

### ISSUE THREAD

**Issue by baizhanshuang** [alibaba/easyexcel#1043]
**场景描述**
  现在有一份数据要导出，其中数据有A，B，C三种类型，现在希望A的数据背景是红色，B的背景是黄色，C的背景是蓝色。像这样的的根据内容设置导出样式的情况怎么处理？
   在RowWriteHandler类中，没有看到有原始数据传入，无法判断要设置什么样式，只能根据rowIndex这类的强制指定某行的样式效果。
请问有什么好的处理方法吗？在RowWriteHandler中的方法能否拿到原始数据

**Comment by zhuangjiaju** [comment]
自定义样式 可以根据第几列来判断。自定义样式可以 根据数据来判断。整个需要自己实现。
