### ISSUE TITLE
如何处理枚举或者字典类型的导出？

### ISSUE THREAD

**Issue by westflyer** [alibaba/easyexcel#1054]
在实体类中，某个类可能有一个字典或者是枚举类型作为属性。
例如常见的省市编码：private String provinceCode;
该code需要从数据库或是map中取出对应的value，实际导出时需要导出的也是描述
我目前想到的只有在实体类新建一个属性，命名为provinceName，然后循环遍历通过code填充Name，再进行导出，但是这样对实体类的破坏性很大，新建一个又不免觉得浪费。
这种需要查数据库字典的，循环填充还能接受，如果只是简单的已审核待审核状态呢，请问有什么更好的办法吗？

**Comment by zhuangjiaju** [comment]
建议自定义转换器，看demo有。

**Comment by caiqichang** [comment]
@zhuangjiaju  
在哪？ 没找着
