### ISSUE TITLE
@ExcelProperty 的value能否做成策略模式或者可扩展

### ISSUE THREAD

**Issue by ruibiaozhong** [alibaba/easyexcel#1060]
举个例子例子，目前公司需求是，导出的excel需要进行国际化处理，也就是说根据header的不同对导出的数据做对应的国际化处理，那么目前的value是固定的，按照目前的方式，表头是固定的，要么是中文，要么是英文，要么其他。能否都做成类似ExcelProperty 的converter()或者其他的方式，有一定的扩展性，实现的业务逻辑由使用者去实现？

**Comment by ruibiaozhong** [comment]
目前这个问题可以通过CellWriteHandler来解决，谢谢啦～

**Comment by zhuangjiaju** [comment]
新版本已经支持head 同事传入 class+ list ，取值用list, 注解读取class的。
