### ISSUE TITLE
如何获取同个表头下的不同数据

### ISSUE THREAD

**Issue by GitHubUDA** [alibaba/easyexcel#1063]
**异常代码**
```java

serviceImpl:
第一种：
   public void saveData(List<CPMXEntity> list) throws Exception {
        
        for (int i = 0; i < list.size(); i++) {
            List<String> pfbz = list.get(i).getPfbz();
            for (String s : pfbz) {
                System.out.println("pfbzA：" + s);
            }

第二种:
  for (int i = 0; i < list.size(); i++) {
            String pfbz = list.get(i).getPfbz();
            System.out.println(pfbz);
```
**异常提示**
第一种写法错误：
Caused by: com.alibaba.excel.exception.ExcelDataConvertException: Converter not found, convert STRING to java.util.List

第二种写法无报错，但只能获取一个数据
**建议描述**

评分标准
-------------
A | B | C
A1 | B1 | C1
A2 | B2 | C2

excel如上
“评分标准”这个表头下可以任填数据，如A、B、C 。每个数据下面可再填写数据如A1，B1,C1
按照普通的写法 只能获取到数据“A”，而获取不到“B”、“C”。
应如何编写才能获取到ABC全部数据

**Comment by zhuangjiaju** [comment]
定义对象头的时候 完全按照excel来，或者只定义头的最后一行，然后设置`headrownum`=头行的数量
