### ISSUE TITLE
关于写Excel，一个文件多个sheet，testdemo的一点建议

### ISSUE THREAD

**Issue by naihewuxiao** [alibaba/easyexcel#1071]
**建议描述**
package com.alibaba.easyexcel.test.demo.write下的WriteTest中的repeatedWrite()中的方法二，在运行时并不能安装描述生成多个sheet，在多次尝试后发现：
writeSheet = EasyExcel.writerSheet(i, "模板").build()  中不仅要指定sheetNo，如果sheetName已经存在，则不能产生新的sheet。因此注释容易造成误区，能否稍微修改一下代码或者注释

**Comment by zhuangjiaju** [comment]
ok  已经改了
