### ISSUE TITLE
excel读取时无法读到数据

### ISSUE THREAD

**Issue by zhangjingsen** [alibaba/easyexcel#1075]
**触发场景描述**
![图片](https://user-images.githubusercontent.com/18588851/72398047-a1e78b00-377c-11ea-8bc0-e094937d4608.png)
这个格式的数据，数据时间无法读取到
![图片](https://user-images.githubusercontent.com/18588851/72398092-c479a400-377c-11ea-9300-38160270b8dc.png)
这个是我的模板类，数据时间字段无法读取到

**Comment by NowFlying** [comment]
测试用例没有问题，能不能看一下代码

**Comment by zhangjingsen** [comment]
我是2.1.1版本的，跟这个有关系吗？需要看哪块的代码

**Comment by NowFlying** [comment]
我用的是2.1.4的，没有问题

**Comment by zhuangjiaju** [comment]
有2.1.6  修复过这个bug
