### ISSUE TITLE
读取存在列合并的excel时实体对象不支持单字母字段

### ISSUE THREAD

**Issue by javading** [alibaba/easyexcel#1078]
**触发场景描述**
easyexcel jar版本: 2.1.4

**触发Bug的代码**
```java
   //测试类
   String filePath1 = "C:\\Users\\Administrator\\Desktop\\work01\\题目导入模板测试1.xlsx";
   List<Test> list =
               EasyExcel.read(filePath1).head(Test.class).sheet("题目").doReadSync();
    System.out.println("数量:" + list.size());

    //实体类中部分代码如下
    @ExcelProperty(value = {"标题一"}, index = 0)
    private String test1;
   @ExcelProperty(value = {"答题二", "A"})
    private String A;
    @ExcelProperty(value = {"答题二", "B"})
    private String B;
    @ExcelProperty(value = {"答题二", "C"})
    private String C;
    @ExcelProperty(value = {"答题二", "D"})
    private String D;
    @ExcelProperty(value = {"标题三"}, index = 5)
    private String test3;
   
```
**提示的异常或者没有达到的效果**
A、B、C、D等字段无法取不到值。

**临时解决方法**
    //实体类中部分代码如下
    @ExcelProperty(value = {"标题一"}, index = 0)
    private String test1;
   @ExcelProperty(value = {"答题二", "A"})
    private String AA;
    @ExcelProperty(value = {"答题二", "B"})
    private String BB;
    @ExcelProperty(value = {"答题二", "C"})
    private String CC;
    @ExcelProperty(value = {"答题二", "D"})
    private String DD;
    @ExcelProperty(value = {"标题三"}, index = 5)
    private String test3;

**Comment by zhuangjiaju** [comment]
不建议同时使用index 和name 去匹配。建议全部name或者index。
