### ISSUE TITLE
https://github.com/alibaba/easyexcel/issues/807  所指的拦截器是什么？

### ISSUE THREAD

**Issue by gitzhangliang** [alibaba/easyexcel#1079]
[https://github.com/alibaba/easyexcel/issues/807  ](url)

目前不支持excel公式。如果想支持，建议使用拦截器，然后使用poi 的写法去处理
--
对于拦截器能简单说下吗

**Comment by gitzhangliang** [comment]
我看到写的时候可以自定义拦截器CellWriteHandler   读的时候怎么自定义拦截器？

**Comment by zhuangjiaju** [comment]
参照：https://www.yuque.com/easyexcel/doc/write#bbf8e817
