### ISSUE TITLE
增加按照相同内容进行合并单元格

### ISSUE THREAD

**Issue by andotorg** [alibaba/easyexcel#1082]
**建议描述**
增加按照相同内容进行合并单元格
例如  你好 你好 你好 这个三个自动合并单元格

**Comment by zhuangjiaju** [comment]
有些人不需要合并，这个需要自定义合并策略。看文档

**Comment by andotorg** [comment]
这个就是自定义的合并策略，提供合并策略备选项

**Comment by andotorg** [comment]
> 有些人不需要合并，这个需要自定义合并策略。看文档

需要怎么处理呢？

**Comment by zhuangjiaju** [comment]
暂时不考虑 后续需求的人多了考虑开发。这个感觉需求比较少。
