### ISSUE TITLE
当单元格是空值的时候，程序默认返回了空，并不会调用自定义converter

### ISSUE THREAD

**Issue by jinKnight** [alibaba/easyexcel#1084]
**建议描述**
建议对没有自定义converter的地方，可以直接返回空值。如果有自定义的Converter的列，应该让程序继续调用自定义converter。

因为自定义converter很大可能会对空值的处理有要求，所以，建议有自定义converter的地方，即使单元格取值是空值，也应该继续调用自定义的converter。

**Comment by jinKnight** [comment]
any update ?

**Comment by zhuangjiaju** [comment]
这个您的需求是啥？这个问题导致所有的转换器都需要非空判断。

**Comment by jinKnight** [comment]
> 这个您的需求是啥？这个问题导致所有的转换器都需要非空判断。

需求是：我想给一个单元格是空值的地方，依然进入我自定义的转换器，因为业务上，很多时候，会对空值有转换的需求，同时，按道理讲，我对该列使用了自定义转换器，那么该列无论什么值，都应该进入和使用我的转换器啊，由我自定义转换器控制写法和表现方法，**因为我自定义了**，你不能说空值就不进来啊。

举个例子，目前我们 商品库存状态编码，这个字段，可能的值是01（库存充足）、02（库存一般）、03（库存告警）和空值，导出excel的时候，业务要求，如果是空值，显示中文“库存异常”，结果现在的easyexcel版本，空值就直接不调用converter了。

我认为从设计上来讲，既然叫“自定义”，那么调用入口那里，空值的时候，就应该放行自定义转换器。

**Comment by jinKnight** [comment]
简单的说，就是空值的单元格，应该放行**自定义转换器**，默认转换器可以不用进入。

**Comment by zhuangjiaju** [comment]
这个可以考虑 新增的接口 `NullableObjectConvert` 空的也过来

**Comment by zhuangjiaju** [comment]
已经在2.2.1里面修复
