### ISSUE TITLE
使用map的方式与model方式读取数字的.0

### ISSUE THREAD

**Issue by PhilosophyBuns** [alibaba/easyexcel#1086]
**异常代码**
   这里写你的代码
![image](https://user-images.githubusercontent.com/28674017/72678423-b317fb00-3ae0-11ea-97ce-1a313c04b834.png)
![image](https://user-images.githubusercontent.com/28674017/72678470-39ccd800-3ae1-11ea-929c-15e166ff0139.png)
![image](https://user-images.githubusercontent.com/28674017/72678464-2b7ebc00-3ae1-11ea-83fc-57c3f068cc8d.png)

**异常提示**
**建议描述**
使用model方式读取数据时，如果是数字类型会自动截取.0
使用map方式读取数据时，如果是识字类型不会自动截取.0
如何让使用map的方式读取数据时也能够和model方式一样呢？

**Comment by zhuangjiaju** [comment]
这个在新版本已经修复。都用string接收即可。
