### ISSUE TITLE
关于向Excel插入图片的建议

### ISSUE THREAD

**Issue by vincentzip** [alibaba/easyexcel#1088]
使用easyexcel向excel插入图片, 使用URL对象进行包装, 插入后的数据回填充整个单元格, 但是, 如果单元格有边框线的话, 图片回覆盖调边框线, 导致excel不美观。因此， 建议能有一个操控图片摆放位置的功能，根据用户喜好自定义的去控制图片的大小和位置，谢谢。

**Comment by zhuangjiaju** [comment]
建议自定义拦截器去操作：https://www.yuque.com/easyexcel/faq/wpedtd

**Comment by Jin-93** [comment]
功能实现了  新的问题是
1. 一张sheet只能是同一种扩展名的图片    
2.图片会重复写入  两张图片呈现重叠状态

**Comment by Jin-93** [comment]
谢谢 辛苦了 功能实现了 新的问题是

1.一张sheet只能是同一种扩展名的图片
2.图片会重复写入 两张图片呈现重叠状态
