### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by chenshun00** [alibaba/easyexcel#109]
读取excel的时候发现读取到到数据是 0 ， 等我忙完再添重现步骤

**Comment by chenshun00** [comment]
读取一个普通的excel文件，发现 invoke 的对象设置的是 `0` , 具体怎么产生的还在看

**Comment by jipengfei-jpf** [comment]
没懂你说的什么意思

**Comment by chenshun00** [comment]
![image](https://user-images.githubusercontent.com/26037282/47983879-b4454e00-e10f-11e8-8648-2250439dcaf1.png)

**Comment by chenshun00** [comment]
刚刚有看了一下，发现整个Excel表格2600多行，除去第一行都有这个问题，可能是这个excel文件有问题，但是这个文件又没有什么特殊的地方，被我取消了合并单元格，前一列的型号我也取消了合并单元格却没有这个问题，奇怪啊

**Comment by jipengfei-jpf** [comment]
多少版本？

**Comment by jipengfei-jpf** [comment]
加我微信18042000709文件发我一下

**Comment by chenshun00** [comment]
@jipengfei-jpf  确实是这个文件有问题，刚刚重新搞了一次，发现是ok的，我有一个建议，我看反射部分使用的 Beanutils，我测试了一下，这里性能比较慢，你有时间可以改一下，具体的反射可以直接拿mybatis的反射包替换就可以了，这里我研究过了，替换是完全可行的。代码地址 [mybatis 反射](https://git.io/fxj6s)

**Comment by jipengfei-jpf** [comment]
这个我后面改用cglib，看来你对这块还是有研究。
