### ISSUE TITLE
读取多个Sheet时无法跳过表头

### ISSUE THREAD

**Issue by zsjSummer** [alibaba/easyexcel#1090]
**触发场景描述**
在读取多个 sheet 时不能自动跳过表头，会将表头的数据当作内容数据，导致converter失败出现异常
**触发Bug的代码**
我的实体如下：
![image](https://user-images.githubusercontent.com/45053977/72712888-f2a91a80-3ba6-11ea-9740-029cc2a1a654.png)
读取main方法如下：
```java
        File file = new File("C:\\Users\\admin\\Desktop\\测试_用户-20200120160005.xlsx");
        ExcelReader excelReader = EasyExcel.read(file).build();
        ReadSheet readSheet = EasyExcel.readSheet(0).head(TestDomain.class)
                .registerReadListener(new TestListener()).build();
        excelReader.read(readSheet);
        excelReader.finish();
```
**原因分析**
当进行读取的时候，在执行器中class为空：
![image](https://user-images.githubusercontent.com/45053977/72714573-e6728c80-3ba9-11ea-92bc-1f26a5bfd32e.png)
```java
// 采用如下的方式不会出现，readWorkbook对象中的clazz对象不为空
EasyExcel.read(file,Test.class,new TestListener()).build().readAll();
```
**提示的异常或者没有达到的效果**
出现的异常信息如下：
![image](https://user-images.githubusercontent.com/45053977/72713187-8d095e00-3ba7-11ea-8a21-d337feca8029.png)

**Comment by zsjSummer** [comment]
原因分析那块可能不正确，再次跟了一下断点，发现解析到的headRowNumber为1

**Comment by zhuangjiaju** [comment]
这个问题原因是 excel中存储的是中文 你却用int去接收了 有问题。

**Comment by zsjSummer** [comment]
使用到的是2.1.6的版本
main方法
![image](https://user-images.githubusercontent.com/45053977/80354908-f3d69b80-88a9-11ea-85b1-46a4741f3f8c.png)
实体类
![image](https://user-images.githubusercontent.com/45053977/80354960-03ee7b00-88aa-11ea-8669-6bb4dc8a412a.png)
监听器
![image](https://user-images.githubusercontent.com/45053977/80355010-1799e180-88aa-11ea-8c08-6bea7192de34.png)



> 这个问题原因是 excel中存储的是中文 你却用int去接收了 有问题。

**Comment by zsjSummer** [comment]
> 这个问题原因是 excel中存储的是中文 你却用int去接收了 有问题。

@zhuangjiaju 
主类
![image](https://user-images.githubusercontent.com/45053977/80355696-fab1de00-88aa-11ea-9e9a-20aaa26aec50.png)
实体类
![image](https://user-images.githubusercontent.com/45053977/80355727-02718280-88ab-11ea-8298-cacbb653e01e.png)
监听器
![image](https://user-images.githubusercontent.com/45053977/80355747-0d2c1780-88ab-11ea-8b8d-cef2c5219880.png)

**Comment by zsjSummer** [comment]
@zhuangjiaju 
仍然报错如下
![image](https://user-images.githubusercontent.com/45053977/80356038-7744bc80-88ab-11ea-9f90-67aa3c8a10cc.png)
