### ISSUE TITLE
HtmlToExcelService生成的内容，不管加任何style都会有边框，并且不识别a标签

### ISSUE THREAD

**Issue by tctxl** [alibaba/easyexcel#1093]
这个真的是html转excel的神器，太方便了，后台展示完还可以一键导出。
但是任意一个td或者tr加上style的时候（比如font-size这种），会默认给这个单元格生成一个边框，生成出来的东西就会略丑陋，建议即使不识别border也不要默认加上框框吧。
然后就是不识别a标签，比如表单里的图片链接，导出的时候我想作为超链接一起生成出来，就没有支持。
目前自己修改了下可以用了，希望后续版本可以加上，非常感谢有这么实用的功能！

**Comment by zhuangjiaju** [comment]
需要自定义拦截器。

**Comment by KevinPan1992** [comment]
html转excel怎么玩的?求指教
