### ISSUE TITLE
使用xls进入read的时候出现了这个异常，我看是因为枚举为空

### ISSUE THREAD

**Issue by sgerptangkang** [alibaba/easyexcel#1095]
com.alibaba.excel.exception.ExcelCommonException: Convert excel format exception.You can try specifying the 'excelType' yourself
at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:65)
使用版本是2.1.6
直接clone来代码吧xlsx改成xls文件，读取就报错

**Comment by zhuangjiaju** [comment]
嗯 乱改文件名需要自己指定类型
