### ISSUE TITLE
没有使用@ExcelProperty字段在解析时为字段赋值了

### ISSUE THREAD

**Issue by bigmzc** [alibaba/easyexcel#1098]
**建议描述**
读取时没有使用注解的字段也被赋值了，版本2.1.4

**Comment by Wsr-7** [comment]
请问后来解决了吗?我也碰到了.一个应该被跳过的列,被赋值到了一个没有@ExcelProperty的字段

**Comment by bigmzc** [comment]
> 请问后来解决了吗?我也碰到了.一个应该被跳过的列,被赋值到了一个没有@ExcelProperty的字段

加了@ExcelIgnore在不需要的字段上 解决
