### ISSUE TITLE
请问一下easyExcel是否提供获取excel总行数的接口？

### ISSUE THREAD

**Issue by ReignsZhang** [alibaba/easyexcel#1099]
请问一下easyExcel是否提供获取excel总行数的接口？

**Comment by zhuangjiaju** [comment]
`ReadSheetHolder.approximateTotalRowNumber` 但是不一定精确 要精确自己读完后统计。

**Comment by forlinran** [comment]
> `ReadSheetHolder.approximateTotalRowNumber` 但是不一定精确 要精确自己读完后统计。

我在listener里面拿到context后，获取ReadSheetHolder.approximateTotalRowNumber 进行调用发现值一直为1.

**Comment by sunchaohai** [comment]
同样遇到此问题，读取前需要校验下excel的总行数，ReadSheetHolder.approximateTotalRowNumber 进行调用发现值一直为1

**Comment by sunchaohai** [comment]
同样遇到此问题，读取前需要校验下excel的总行数，ReadSheetHolder.approximateTotalRowNumber 进行调用发现值一直为1

**Comment by Francyfx** [comment]
我自己在内存里统计的
