### ISSUE TITLE
使用了class上的注解通过InputStream导出图片，但是就不能动态定义表头了

### ISSUE THREAD

**Issue by wenlinguo** [alibaba/easyexcel#1110]
**异常代码**
在类里面定义了导出类的属性
```java
// DemoData.java
// ......
    @ExcelProperty(index = 3, value = "注册照", converter = InputStreamImageConverter.class)
    @ColumnWidth(value = 20)
    private InputStream faceImage;
```

然后，使用的时候
```java
EasyExcel.write(outputStream, DemoData.class).head(head())
```
**异常提示**
```com.alibaba.excel.exception.ExcelDataConvertException: Can not find 'Converter' support class FileInputStream.```
**建议描述**
看源码`EasyExcel.write`的第二个参数`DemoData.class` 其实就是在设置head， 然后因为有个动态生成head的需求，所以后面那个head替换了前面`DemoData.class`定义的head，造成找不到合适的`Converter`

如果遇到我这种，既要导出图片，又要动态生成head 应如何解决呢？
谢谢

**Comment by zhuangjiaju** [comment]
参照`InputStreamImageConverter` 吧里面的 `InputStream`改成 `FileInputStream`

**Comment by wenlinguo** [comment]
@zhuangjiaju  自定义了 converter， 如何注册到 WriteHolder 里面去呢 ？

**Comment by wenlinguo** [comment]
> 参照`InputStreamImageConverter` 吧里面的 `InputStream`改成 `FileInputStream`

谢谢。已经解决
