### ISSUE TITLE
图片跨行跨列的问题

### ISSUE THREAD

**Issue by laizuan** [alibaba/easyexcel#1113]
我有一个模板，其中有一个图片占位符是合并了单元格的，请问这时候我应该怎么做才能将图片铺满这个合并后的单元格呢？

**Comment by zhuangjiaju** [comment]
目前只能自己写。升级到`2.2.0` 然后 实现`CellWriteHandler`的 `afterCellDataConverted`返回一个empty类型的celldata,然后 实现 `afterCellDispose` 自己去写入数据
