### ISSUE TITLE
如何在自定义Convertor中获取目标type类型

### ISSUE THREAD

**Issue by YiuTerran** [alibaba/easyexcel#1114]
个人认为Converter的接口应该与mybatis的BaseTypeHandler类似，在构造函数中传入目标函数的真实type. 这样的话，否则的话，无法通过一个基类/接口的Converter来实现实际类型的实例化。

或者，提供类似Jackson的`@JsonCreator`的注解也可以，这样也能通过Excel中的基础数据构造复杂对象。

请教一下现在除了每个自定义类实现一个Convertor以外还有别的方式简化实现么？

**Comment by zhuangjiaju** [comment]
`supportJavaTypeKey` 就是目标的type类型

**Comment by YiuTerran** [comment]
> `supportJavaTypeKey` 就是目标的type类型

不是，supportJavaTypeKey只能拿到基类或者接口类型啊，如果我要构建子类，就必须知道对应的真实类型，才能通过构造函数进行实例化。
