### ISSUE TITLE
读取excel的bug-com.alibaba.excel.read.metadata.holder.AbstractReadHolder#buildHead

### ISSUE THREAD

**Issue by liuzou1991** [alibaba/easyexcel#1116]
例如要解析一个excel，excel有两列，A列head是H1，B列head是H2
定义实体类DataDemo来存数据，定义两个字段
```java
@ExcelProperty("h2")
private Integer h2;
private int rowIdx;
```
其中rowIdx是打算存行号的，在linstener的invoke方法里手动设置
A列数据压根没打算读
那么现在问题来了，com.alibaba.excel.read.metadata.holder.AbstractReadHolder#buildHead方法的206-210行有如下代码：
**触发Bug的代码**
```java
if (headData.getForceIndex() || !headData.getForceName()) {
                tmpHeadMap.put(entry.getKey(), headData);
                tmpContentPropertyMap.put(entry.getKey(), 
                contentPropertyMapData.get(entry.getKey()));
                continue;
            }
```
这地方会把字段h2的映射覆盖掉，导致B列的数据都读出来设置到了rowIdx字段上面

所以，是不是应该让读excel时也支持@ExcelIgnoreUnannotated和@ExcelIgnore这两个注解，来主动避免默认的按字段顺序读excel的这种行为

**Comment by zhuangjiaju** [comment]
读的时候也是支持的
