### ISSUE TITLE
如何在@ExcelProperty(value = "文本*5") value属性中的*5转成上角标或下角标?

### ISSUE THREAD

**Issue by SpencerReidFemale** [alibaba/easyexcel#1118]
@ExcelProperty(value = "文本*5") 
如何将value属性中的'*5'两个字符都转成上角标或下角标?
项目中的需求,需要将很多固定文本中含有上下角标的特殊字符部分显示出来,查了资料没有查到,望解答,谢谢

**Comment by zhuangjiaju** [comment]
参照 自定义拦截器 需要设置`inmomery`=true
