### ISSUE TITLE
怎么把下载的文件设置为xlsx后缀名

### ISSUE THREAD

**Issue by RoadSides** [alibaba/easyexcel#1119]
按照文档上面的写法
response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx");
EasyExcel.write(response.getOutputStream(), TraFreightInventoryResult.class).sheet("test单据").doWrite(collectList);

但是导出的文件都是xls的，而非xlsx，所以用office打开会报错，请问我要怎么设置才能把文件的后缀名改成xlsx呢

**Comment by tanpenggood** [comment]
```java
EasyExcel.write(response.getOutputStream(), TraFreightInventoryResult.class)
                .excelType(ExcelTypeEnum.XLSX)
                .sheet("test单据")
                .doWrite(collectList);
```

**Comment by RoadSides** [comment]
已解决，多谢
