### ISSUE TITLE
2.1.6使用模板方式写入时,单元格已经设置区中,但实际未居中.

### ISSUE THREAD

**Issue by namelessmyth** [alibaba/easyexcel#1125]
**触发场景描述**
使用的是模板方式写入(withTemplate),模板已经设置过居中,但实际生成的Excel未居中.
**触发Bug的代码**
File templateFile = PathUtils.getExcelTemplateFile("产线不良导出模板.xlsx");
File downloadFile = PathUtils.getExcelOutputFile(templateFile);
EasyExcel.write(downloadFile, ProdlineBugVO.class).withTemplate(templateFile).sheet(0).needHead(Boolean.FALSE).doWrite(list);
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
写入是不管任何格式的 。请使用填充或者写入后自定义样式。
