### ISSUE TITLE
是否有动态表头导出功能

### ISSUE THREAD

**Issue by wangyihuai1997** [alibaba/easyexcel#1126]
**建议描述**
表头数量类型都不确定，能否支持动态导出

**Comment by wangguanquan** [comment]
可以使用`EasyExcel.write("xx.xlsx", Data.class).sheet().doWrite(data);`方式解决吧，Data对象有什么字段就导什么字段。

你也可以看一下[EEC](https://github.com/wangguanquan/eec)工具，它支持List<Map>类型导出，同时对象数组也支持表头覆写功能

**Comment by zhuangjiaju** [comment]
参照无对象写
