### ISSUE TITLE
一列多值读取无法实现

### ISSUE THREAD

**Issue by heshouyou** [alibaba/easyexcel#1127]
**建议描述**
1、一列可能有多个值，实体模型现在只可以定义String类型字段，为什么不能定义List<String>去接收一列多值情况
2、或者是index可以指定范围，读取第几列到第几列到一个String字段，使用英文逗号做数据分隔

**Comment by zhuangjiaju** [comment]
很好的想法 短期内不会考虑。后续可能会加入
