### ISSUE TITLE
导出文件打开报错

### ISSUE THREAD

**Issue by Hnannan** [alibaba/easyexcel#1128]
**异常代码**
```java
    String fileName = "Withdrawals agency record " + model.getCreateTime().split(" ")[0]+ "_" + model.getReturnTime().split(" ")[0] + ".xlsx";
//            _response.setContentType("multipart/form-data");
            _response.setHeader("Content-Disposition", "attachment;fileName=" + fileName);
            _response.setContentType("application/vnd.ms-excel");
            _response.setCharacterEncoding("utf-8");
            ExcelWriter writer = new ExcelWriter(out, ExcelTypeEnum.XLSX);
            Sheet sheet = new Sheet(1, 1, AgencyWithdrawExport.class);
            sheet.setSheetName(fileName);
            //写出数据
            writer.write(createModelList(
                    model.getUuid(),
                    model.getAgencyId(),
                    model.getAuditStatus(),
                    model.getUid(),
                    model.getLevel(),
                    model.getCreateTime(),
                    model.getReturnTime()), sheet);
            writer.finish();
            out.close();
```
**异常提示**
PK  妟cP               _rels/.rels瓛羓?哶盆?韅孮窏2鑝岊4[ILb素跂烬?[K
?$}襳?嘔絈.灒乽觽蠃?x>=@凌p釮"脋穧?斄Б*"僅鹤贺?枂炮?擹鎊'?訾7m{O?昭菺?u萝??y|a泭瓖廌?瀹髺l_EY染?届铲vql3譓L榭eh妿??殊‐3篩0矞閛J讖?	:^槌貆PKz姐   I  PK  妟cP               [Content_Types].xml礢薾?鼤茸*6鬚U丆?\{揦?瘅]8擱?q騝fgfW鰀秖禯CB|闷|??h慊唥,^陒Va朸K<4?6汵?XQ┣嗸9?!P踵$??覇鋎闐攋);罚褲P羐鸸蜤僊'O惺曂浙罹H7L苃崚橰壍譍Ⅴ^??{駟瑉迱十B憠3?藱贽h.蒱鳺葱禙?j濞凜Q諣霕垬瞾}喂L鵘:D?妭%迖报愢,肂既瘿[?て ;吮?魗N魳~囏X駜p?ykOL?恔N€V瞍瘰芸BZ~啺紴q?? 奱r堘{O?PKz斒q;    PK  妟cP               docProps/app.xmlM幜
?D飩ro穤???{?橹歁HV殓洆z?骜T氟E?e〞缓?蓡蜒硶忹?蔔o7jH!bb嘫?錠翁?愴屴浜蘐?$o改魟0M吴9貤Gb??pe??~丷?婆Y肊B餮?nW絺焹?PK6n??  ?  PK  妟cP               docProps/core.xmlm愝J?F_%渚澊曅veAP\pE?$c[l~H咿串\a.捥櫭浍7=?鬭唉?A#?L仔驱6粻$Da??K7m-椫阄[?H覙昆khｃ A雳E?aR笳z-b胡湊o(;峇(搪汰FzT*?莼亽€#j41@?鹚F??皌V?啎殾)煪匥饇w,?fD谥G5?EDE拃荗?<UW-mKV矊U鞙?誎
鎔狩羸??佥咛茭\肐添PK?  ?  PK  妟cP               xl/sharedStrings.xml=孉
? 飩{穳D??則m?f7怏蜕?脤?m陜昪&橇€B騳壌Zx>顕逃~72嬺箲X鐸ｘnx鹲?["濯5麁神?R7痋摀巙誠*簠ⅳM煂9脘"仦~PKh巠   ?  PK  妟cP            
   xl/styles.xml漈K幵0?q藍&輽?#1R#钟Hl軮%逼?兕!?颁軃劾=(垸

癷梍辿U?桓?`转?%爅輕諘裘耩隁轙/_螐顉 OPI{锿?su捁m@釛V[?nm?c?.垽闰蓊u&W?訷ぶg錕海YU碯璈NP顟<0仴呞怴k?岐?殥^L1	塽??Y龢鋌Lp€X槟揬i?eI揩蠌療??Us?敹逓a婥.膔?殌?蘽瓣€2徘袬I昖揗?胣樈g嬴??o幋铞i涹亓l#\,銈G?i坂蛧郡3TZ弐嘶>琟浶H斫?4渦Z1虋u
$?涋泗鼛麶zF:Xx
B?智v﹡徴-Is	#J耞<噚?L6in蓒c??谂O挲塥骍M?b<鑀H?@?鄊OPU鄭陻迳'颂咵幭嗙u?5~KI??k6V{??D楮>逃r}唙闥lW?3誒PKE?i?  ?  PK  妟cP               xl/workbook.xml崘盢?唚$蘖航??N??C佡?壵貛桅伔荌`d:?z鏖vA?x	臯 C瘍本擆z|?庐菇┃@鏢g杫%??鏠麒T軉}薮仠J9R倾H↙??x)?w蕑?*鷱#喘崭W	釥Rn{;Fh~毥3*a??磈?缉缤浥)sdJ'{粒:I3?€K鐄2?Jx珐7う靍/鷅?恆??U諬爟??r,蹶鉱冩PK匃竜?  w  PK  妟cP               xl/_rels/workbook.xml.rels瓚Mk?@娧}q伊/c须铸 c+qh"K繜幻諤;?岎{崔~螕y?#搩甶??
^鱋7鱜D=E?1?b豱窒8y?$峐LE?H罿		g/
gず楣蘜氤6鹥?赨坜賠蝷%屿矉樈/?I綻|裄摔┼?f鼜桘~醡F?v粈兘?嬔銊庄魁?p9HB許y莸K~?桓鲦PK?;懺   3  PK  妟cP               xl/worksheets/sheet1.xml瓧賻?嗭?铦%?=秲6?iM梜峂跙l蓯槞<~┝X滑A}a??~だ披В鳏?梢鋥:載??簾I嬬,V?LH嫢0?胋s效?渤N敛蓑Sl`橈免滊x?潕!AH劎8Ib洔tj=z罐-齙??钆齖T鸀觖榚哽嚆v镃|&~弞c4孧圪ak鍙苒闿h炞:?どm瀼q?d?摥9,}俕兏峂紌啡砱/嚄}鑟l怍
?=&jr?焒跛蟿sNn燯h)釘?f娺,Bq趙猛猅黰Ta榠#鋽堡??oU&樸葄?r鑀緷\厛e[厔闞?UB含%f?披?睜畮L筕`N粩F?b═燱哦瀂?"枚e攙巧?髵瓾椻E蕏tsYⅷp署8闞?塡?+c塌?+僓﹢KE霩J貾a砡?筶y??啙?鈽q$?Q?/幺C飅?"(@嬸┖Q?豦?-?*嬐!p?鈯┤∑∮筓e芋]?D胀鱑3?胀u砢u髗 -茢[踨卙I潀讑 鳤)?}鹭爼聄酱謣-81樥翵E襥D鍨b椿8鞧垹??岀?倰^牑#P醾1"9敶J:
e焽湿鞫?:Le-鰛4┈檘罋X$6Kz?XR_単挎t<鸻I鍦?<?O6啩?q$黽嵘陎R章诚冄吜勨偬U@闰O:?矸u?-Ykp汝嬤腊jm吙?-?????a挎t麘〢(F蜨~亹C堗Ｍ?C
3?!叞厦4珇8iAX53?吋?i?猣?2x圏*<N﨔鱧M绡煐h硒紋b金^.帇s甲_鈢煠咓?摑嘹D郻梕F鐅囶.钳儯?鳀镥?挣Mv~檏痺鹫PK?Fp?  ?  PK   妟cPz姐   I                   _rels/.relsPK   妟cPz斒q;                   [Content_Types].xmlPK   妟cP6n??  ?               ?  docProps/app.xmlPK   妟cP?  ?               i  docProps/core.xmlPK   妟cPh巠   ?               ?  xl/sharedStrings.xmlPK   妟cPE?i?  ?  
             f  xl/styles.xmlPK   妟cP匃竜?  w               ?  xl/workbook.xmlPK   妟cP?;懺   3               ?  xl/_rels/workbook.xml.relsPK   妟cP?Fp?  ?               ?  xl/worksheets/sheet1.xmlPK    	 	 ?  ?    {"code":200,"type":0,"data":null,"msg":"OK","time":1583220020110}
**建议描述**
为什么在我生成的excel中会有个{"code":200,"type":0,"data":null,"msg":"OK","time":1583220020110}在内容中呢，这导致我打开就报个格式错误的问题

**Comment by hoshaoniurou** [comment]
有没有排除过 后台使用 .xlsx 导出，前端使用 .xls

**Comment by Hnannan** [comment]
这个是直接导出的，没有使用前端。后端直接_response这个连接下载到本地

**Comment by Hnannan** [comment]
> 有没有排除过 后台使用 .xlsx 导出，前端使用 .xls
这个是直接导出的，没有使用前端。后端直接_response这个连接下载到本地

**Comment by zhuangjiaju** [comment]
直接使用浏览器，且方法的返回设置void
