### ISSUE TITLE
调用代码时报NoSuchMethodError: com.alibaba.excel.ExcelWriter.<init>(Lcom/alibaba/excel/write/metadata/WriteWorkbook;)V

### ISSUE THREAD

**Issue by Mars-Shen** [alibaba/easyexcel#1129]
**异常代码**
```java
   EasyExcel.write(response.getOutputStream()).head(headList).sheet("模板").doWrite(new ArrayList());
```
**异常提示**
Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.alibaba.excel.ExcelWriter.<init>(Lcom/alibaba/excel/write/metadata/WriteWorkbook;)V
**建议描述**
用的最新2.1.6版本, poi版本冲突已经解决, 现在poi版本3.17, 调用代码就报上面的错误, 请问是什么原因

**Comment by zhuangjiaju** [comment]
尝试`clean`项目
