### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.alibaba.excel.read.listener.ReadListener

### ISSUE THREAD

**Issue by xyydcoo** [alibaba/easyexcel#1136]
**触发场景描述**
2.1.6版本
**触发Bug的代码**
```java
   EasyExcel.read(file.getInputStream(), Product.class, new ProductImportListener(productMapper)).sheet().doRead();
```
**提示的异常或者没有达到的效果**
Error creating bean with name 'productController': Failed to introspect bean class [com.qunar.market.prince.material.web.controller.ProductController] for lookup method metadata: could not find class that it depends on; nested exception is java.lang.NoClassDefFoundError: com/alibaba/excel/read/listener/ReadListener

**Comment by xyydcoo** [comment]
统一了poi没用

**Comment by zhuangjiaju** [comment]
重新导入包试试 就是包没导入。`mvn clean` 之类的

**Comment by qinyuqiong** [comment]
maven项目使用easyexcel时，如果使用maven将项目打包成jar包后，java -jar xxx.jar会报错 java.lang.NoClassDefFoundError: com/alibaba/excel/read/listener/ReadListener 。idea中运行正常 .MF文件中包含了easyexcel

**Comment by dsagsdfgfdh** [comment]
> maven项目使用easyexcel时，如果使用maven将项目打包成jar包后，java -jar xxx.jar会报错 java.lang.NoClassDefFoundError: com/alibaba/excel/read/listener/ReadListener 。idea中运行正常 .MF文件中包含了easyexcel

兄弟这个问题你解决了吗，我现在版本3.0.5，maven打包之后也是报错java.lang.ClassNotFoundException: com.alibaba.excel.read.listener.ReadListener

**Comment by qinyuqiong** [comment]
> > maven项目使用easyexcel时，如果使用maven将项目打包成jar包后，java -jar xxx.jar会报错java.lang.NoClassDefFoundError： com/alibaba/excel/read/listener/ReadListener 。idea中运行正常 .MF文件中包含了easyexcel
> 
> 兄弟这个问题你解决了吗，我现在版本3.0.5，maven打包之后也是报错java.lang.ClassNotFoundException： com.alibaba.excel.read.listener.ReadListener

没有，相关人员没有解答我的疑问。我后来没用它了。我都忘了这件事

**Comment by antield** [comment]
试了加依赖、Invalidate Caches..，都没用，后来把项目文件夹下.idea目录删除，再重新打开idea就好了

**Comment by finch04** [comment]
![微信图片_20241105145702](https://github.com/user-attachments/assets/196c551f-6d35-46b4-884d-e7deb139a0ed)
把这个给勾掉就好了
