### ISSUE TITLE
导出的excel 0字节

### ISSUE THREAD

**Issue by Dlarmor** [alibaba/easyexcel#1139]
**触发场景描述**
本地测试oraclejdk导出正常
服务器openjdk导出0字节

emmmmmm.

**Comment by Dlarmor** [comment]
easyexcel 版本 2.1.6

**Comment by tanpenggood** [comment]
注意数据处理结束，是否正常调用了`finish()`

**Comment by antz-H** [comment]
@Dlarmor 请问下，OpenJDK线上有问题，是如何解决掉的？除了安装fontconfig包，

**Comment by nasongyiqiu** [comment]
@antz-H 你最后如何解决的，我本地运行的都是好的，线上下载下来是0字节
