### ISSUE TITLE
07版本的xlsx获取不到sheet名称，代码如下所示

### ISSUE THREAD

**Issue by xiaomeng1994** [alibaba/easyexcel#114]
File file = new File("d:/testMy.xlsx");
        //写一个excel
        FileOutputStream fileOutputStream = new FileOutputStream(file);
        ExcelWriter excelWriter = new ExcelWriter(fileOutputStream, ExcelTypeEnum.XLSX);
        Sheet sheet = new Sheet(1);
        sheet.setSheetName("测试");
        excelWriter.write0(ImmutableList.of(ImmutableList.of("1","a","2","b")),sheet);
        excelWriter.finish();
        IOUtils.closeQuietly(fileOutputStream);
        //读这个excel
        FileInputStream fileInputStream = new FileInputStream(file);

        ExcelReader excelReader = new ExcelReader(fileInputStream, ExcelTypeEnum.XLSX, null, new AnalysisEventListener<List<String>>() {
            @Override
            public void invoke(List<String> list, AnalysisContext context) {
                System.out.println(context.getCurrentSheet());
                System.out.println(list);
            }
            @Override
            public void doAfterAllAnalysed(AnalysisContext context) {
            }
        });
        excelReader.read();
        IOUtils.closeQuietly(fileInputStream);

**Comment by jipengfei-jpf** [comment]
获取sheet名通过这种方式
ExcelReader excelReader = EasyExcelFactory.getReader(inputStream,excelListener);
 List<Sheet> sheets = excelReader.getSheets();
版本：1.1.2-beat1
