### ISSUE TITLE
文件上传不存数据库，直接返回数据给前端

### ISSUE THREAD

**Issue by LiZhongJun** [alibaba/easyexcel#1140]
**建议描述**
该如何去实现，求大神给点思路

**Comment by tanpenggood** [comment]
看数据量的大小

数据量特别小可直接读流返回给前端（数据量特别小还不如直接就在前端解析，还避免了网络交互）
数据量大可以用websocket，分段发送数据（一边解析一边响应数据，大部分场景下速度应该能接受）

**Comment by LiZhongJun** [comment]
> 看数据量的大小
> 
> 数据量特别小可直接读流返回给前端（数据量特别小还不如如直接就在前端解析，还避免了网络交互）
> 数据量大可以用websocket，分割发送数据（同时解析同时响应数据，大部分场景下速度应该能接受）

好的，数据量有点大。那我用 websocket试试
