### ISSUE TITLE
请问有大佬尝试过把导出创建实体和mybatis-plus的实体对象合并成一个嘛？

### ISSUE THREAD

**Issue by lgrknight** [alibaba/easyexcel#1149]
请问有大佬尝试过把导出对象实体和mybatis-plus的实体对象合并成一个嘛？

因为目前遇到需要把查询的list<bean>对象转换成另外的list<bean>对象才能导出。

**Comment by zhuangjiaju** [comment]
这个需要自己转换 或者在生成的实体类 注解加注解
