### ISSUE TITLE
如何读取同一列表头

### ISSUE THREAD

**Issue by LiZhongJun** [alibaba/easyexcel#1157]
![Capture](https://user-images.githubusercontent.com/38486787/76541665-e2366180-64be-11ea-8dc3-dab9335d6a9f.PNG)

**Comment by dota17** [comment]
你好，可以参考 https://alibaba-easyexcel.github.io/quickstart/read.html

获取到的对象里面，第一个string列表应该就是你要的 纵列表头。

**Comment by LiZhongJun** [comment]
好的，谢谢

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by kuanke** [comment]
> 你好，可以参考 https://alibaba-easyexcel.github.io/quickstart/read.html
> 
> 获取到的对象里面，第一个string列表应该就是你要的 纵列表头。
没听懂，请问是用哪个方法读取？

**Comment by kuanke** [comment]
没听懂，请问是用哪个方法读取？

**Comment by LiZhongJun** [comment]
该问题在几个月前已经得到了解决方案，谢谢你的回答！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: zhengll<mailto:notifications@github.com>
发送时间: 2020年9月2日 17:46
收件人: alibaba/easyexcel<mailto:easyexcel@noreply.github.com>
抄送: LiZhongJun<mailto:ZhongJun.Li@hotmail.com>; State change<mailto:state_change@noreply.github.com>
主题: Re: [alibaba/easyexcel] 如何读取同一列表头 (#1157)


你好，可以参考 https://alibaba-easyexcel.github.io/quickstart/read.html

获取到的对象里面，第一个string列表应该就是你要的 纵列表头。
没听懂，请问是用哪个方法读取？

―
