### ISSUE TITLE
建议开发一个多级表头解析并且能与数据结合，生成JSON的功能

### ISSUE THREAD

**Issue by gmysfjc** [alibaba/easyexcel#1163]
情景：上传一个成绩表(工资表)，表头的字段有部分不是固定的，而且表头的行数可能是一行，可能是两行，使用什么方法可以自动获取一级和二级表头，使得表头和每一行数据结合生成JSON写入数据库中保存，目前暂时没发现有这样的库，建议开发一个相应的功能。

**Comment by zhuangjiaju** [comment]
请实现`AnalysisEventListener` 的`invokeHeadMap`方法 可以读取到头信息。如果您的需求不确定几行头，建议统一安照2行处理。
