### ISSUE TITLE
如何自定义部分表头的样式？

### ISSUE THREAD

**Issue by l523402485** [alibaba/easyexcel#1166]
我已经按照（https://alibaba-easyexcel.github.io/quickstart/write.html）的示例自定义了表头样式
![1584503083(1)](https://user-images.githubusercontent.com/35321032/76923252-e377ec00-690d-11ea-9049-49ce2854a9e9.png)

` 

    private void dataExport(HttpServletResponse response, List<ReceiveDetail> receiveDetailList) throws Exception {
        String fileName = TestFileUtil.getPath() + "styleWrite" + System.currentTimeMillis() + ".xlsx";
        // 头的策略
        WriteCellStyle headWriteCellStyle = new WriteCellStyle();
        WriteFont headWriteFont = new WriteFont();
        headWriteFont.setColor(IndexedColors.RED.getIndex());
        headWriteCellStyle.setFillForegroundColor(IndexedColors.WHITE.getIndex());
        headWriteCellStyle.setWriteFont(headWriteFont);
        // 内容的策略
        WriteCellStyle contentWriteCellStyle = new WriteCellStyle();
        // 这个策略是 头是头的样式 内容是内容的样式 其他的策略可以自己实现
        HorizontalCellStyleStrategy horizontalCellStyleStrategy = new HorizontalCellStyleStrategy(headWriteCellStyle, contentWriteCellStyle);

        // 这里 需要指定写用哪个class去写，然后写到第一个sheet，名字为模板 然后文件流会自动关闭
        EasyExcel.write(fileName, DemoData.class).registerWriteHandler(horizontalCellStyleStrategy).sheet("模板").doWrite(data());
    }
`

但是后边几个表头的颜色我想设置黑色，该如何去做？

如果能在实体类里用注解的方式自定义样式是不是更方便？

**Comment by zhuangjiaju** [comment]
建议参照：https://www.yuque.com/easyexcel/doc/write#76fa967c-9
