### ISSUE TITLE
有没有办法在AnalysisEventListener上加个beforeRead接口

### ISSUE THREAD

**Issue by deemowww** [alibaba/easyexcel#1171]
假如我想在读取每个sheet之前做一些预先的处理，比如获取sheetName然后进行一些操作（这里的获取sheetName我好像也只能从deprecated的方法getCurrentSheet()里拿到，不知道是不是我操作的问题），可能需要这样一个beforeRead()方法来预处理一些数据。

**Comment by zhuangjiaju** [comment]
建议在`AnalysisEventListener`的构造方法和 `doAfterAllAnalysed`方法做文章，暂时不考虑before
