### ISSUE TITLE
图片重复写入的问题

### ISSUE THREAD

**Issue by Jin-93** [alibaba/easyexcel#1174]
您好： 根据所给文档  [https : //www.yuque.com/easyexcel/faq/wpedtd](url) 
 
在设置自定义图片属性以后  发现图片重复写入了 
 两张重叠图片  一张是自定义属性的图片  
                  一张是非自定义属性图片

**Comment by zhuangjiaju** [comment]
你有没有将单元格设置成`Empty`，有的话看下`AbstractExcelWriteExecutor` 49行 看下 是否为空。

**Comment by Jin-93** [comment]
谢谢  可以了  必须要2.2.0-beta1的   jar
还有一个问题请教一下  
int index = sheet.getWorkbook().addPicture(cellData.getImageValue(), HSSFWorkbook.PICTURE_TYPE_JPEG);
一个sheet 只能对一种格式的图片进行设置是吗？
