### ISSUE TITLE
请问{ }表示变量，{.}表示集合这个依据是？

### ISSUE THREAD

**Issue by Deeeeeeeeeeeeee** [alibaba/easyexcel#1176]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
请参照文档 书写
