### ISSUE TITLE
读入excel 列不满20时其余为null

### ISSUE THREAD

**Issue by minhao1995** [alibaba/easyexcel#118]
大概翻了一下项目的XlsxRowHandler类

初始化curRowContent默认为20
private String[] curRowContent = new String[20];

如果不够就扩
private void endCellValue(String name) throws SAXException {
        // ensure size
        if (curCol >= curRowContent.length) {
            curRowContent = Arrays.copyOf(curRowContent, (int)(curCol * 1.5));
 }

作者选择了动态扩的方式,是不是因为列的数量不方便获取???
能不能将这个参数变成可以开放出来,或者默认变的小一点

**Comment by minhao1995** [comment]
看上去这个参数变小一点,好像也没啥用,还是可能存在null

**Comment by jipengfei-jpf** [comment]
下个版本会升级

**Comment by minhao1995** [comment]
可以问一下准备怎么处理么，如果可以的话，想参与进来

**Comment by jipengfei-jpf** [comment]
1.1.2-beat1已发布修复了这个问题，参与的话欢迎加微信18042000709
