### ISSUE TITLE
使用动态表头的时候，设置的单元格高、宽格式失效

### ISSUE THREAD

**Issue by xuewuyang** [alibaba/easyexcel#1180]
EasyExcel.write(outputStream, DemoData.class)
       .registerWriteHandler(horizontalCellStyleStrategy)
       .head(head())
       .doWrite(data());

在实体类中设置了单元格的高宽格式，但是使用动态表头后，设置失效；不知道我的使用方式是否正确，但是我试了很多遍

**Comment by xuewuyang** [comment]
或者说在动态表头的时候，怎么去设置样式呢

**Comment by xuewuyang** [comment]
问题已解决，通过使用另外两个策略实现，谢谢

**Comment by devfat** [comment]
> 问题已解决，通过使用另外两个策略实现，谢谢

你好，我也遇到了同样的问题，请问你是怎么解决的

**Comment by xuewuyang** [comment]
> > 问题已解决，通过使用另外两个策略实现，谢谢
> 
> 你好，我也遇到了同样的问题，请问你是怎么解决的

SimpleColumnWidthStyleStrategy
SimpleRowHeightStyleStrategy

**Comment by devfat** [comment]
好的，了解了，感谢
