### ISSUE TITLE
vue post 请求不能正常下载

### ISSUE THREAD

**Issue by ncharming** [alibaba/easyexcel#1184]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
        //数据库中获取数据
        List<QryOrdListbyDayInfo> dataList = data(qryOrdListbyDayReq);
        response.setContentType("application/vnd.ms-excel");
        response.setCharacterEncoding("utf-8");
        //获取年月日作为文件名
        String dateName = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd"));
        String filename = URLEncoder.encode(dateName, "UTF-8");
        response.setHeader("Content-disposition", "attachment;filename=" + filename + ".xlsx");
        EasyExcel.write(response.getOutputStream(), QryOrdListbyDayInfo.class).sheet("sheet").doWrite(dataList);
```
**异常提示**
使用 postman 调用可以保存为正常的 .xlsx 文件，前台 vue post 调用返回乱码，且不能弹窗下载
![image](https://user-images.githubusercontent.com/37773337/77520526-4e03cb80-6ebc-11ea-8df1-6291eabb75f7.png)

**建议描述**

**Comment by pdkst** [comment]
不用post，重定向页面到这个地址试试

**Comment by zhuangjiaju** [comment]
这个需要您自己研究下，`vue`怎么可以做到下载一个普通文件。你这个放data肯定不行，需要序列化和发序列化。

**Comment by gaohanghang** [comment]
https://blog.csdn.net/qq_22871083/article/details/105378916

vue + easyexcel
