### ISSUE TITLE
字段全为大写，导出数据某个字段导出为空，

### ISSUE THREAD

**Issue by GuoXiangSheng** [alibaba/easyexcel#1188]
![image](https://user-images.githubusercontent.com/13583865/77605101-07ab7c80-6f4f-11ea-9096-2389f4092d85.png)
![image](https://user-images.githubusercontent.com/13583865/77605104-09754000-6f4f-11ea-8f39-e0c0faf1ef0d.png)
![image](https://user-images.githubusercontent.com/13583865/77605100-04b08c00-6f4f-11ea-9e90-339b48e22f9d.png)

**Comment by pdkst** [comment]
这个是beanMap的问题，你的属性命名需要符合java命名规范才可以被安全的映射

老问题了，经常有人疑惑为什么无法读取

**Comment by zhuangjiaju** [comment]
必须符合驼峰规范。
