### ISSUE TITLE
读取excel复杂表头问题

### ISSUE THREAD

**Issue by zmj-hub** [alibaba/easyexcel#1190]
读取Excel时 复杂表头 读取时出现读取不到的问题。
表头里有简单表头和复杂表头（如第一列表头是第一行和第二行的合并的单元格，第二列表头是第一行是大标题，第二行是小标题）然后按下面方法注释读取
  @ExcelProperty("初始点位编码")
    private String initialPointCoding;//初始点位编码
    @ExcelProperty({"行政区划", "乡"})
    private String township;
最后发现读取不到第一列的信息能读取到第二列“乡的信息” 
上面是问题描述 这里就是想问一下这是一个BUG还是已经有了解决的办法
我们这里的模板可能是有变化的所以不能用index来定位 只能通过名字来匹配，所以想问一下有什么解决办法

**Comment by zhuangjiaju** [comment]
目前仅仅只支持最后一行头去匹配。

**Comment by GenweiWu** [comment]
有支持的计划吗？
