### ISSUE TITLE
EasyExcel可以导出resources中设定好的excel文件吗？

### ISSUE THREAD

**Issue by iamiwangbo** [alibaba/easyexcel#1191]
我看了一圈，没发现这个方式

**Comment by pdkst** [comment]
推荐直接从resource中读取，然后写入到输出流中，不需要EasyExcel

或者，把resource中的文件设置为模板，导出空列表即可

**Comment by zhuangjiaju** [comment]
嗯 参照楼上的，直接返回文件流即可。不需要任何插件。

**Comment by iamiwangbo** [comment]
> 推荐直接从resource中读取，然后写入到输出流中，不需要EasyExcel
> 
> 或者，把resource中的文件设置为模板，导出空列表即可

> 推荐直接从resource中读取，然后写入到输出流中，不需要EasyExcel
> 
> 或者，把resource中的文件设置为模板，导出空列表即可

================================
我用了WorkbookFactary.create(in)，
pom中加上了<resource></resource>，
资源放在resources下面，
应该可以下载模板。
组长没采用，放到前端静态文件下载了，因为他要做微服务，后端资源都不放了
