### ISSUE TITLE
WEB的读

### ISSUE THREAD

**Issue by hjjoe1213123** [alibaba/easyexcel#1194]
WEB读经常会遇到业务需要返回读取成功条数和最终入库成功条数，可以增加一个回调方法吗？

**Comment by pdkst** [comment]
这个在监听器中处理一下就可以了，参考[监听器](https://www.yuque.com/easyexcel/doc/read#5c70a7ac)

**Comment by hjjoe1213123** [comment]
还是官方加一个泛型吧

**Comment by zhuangjiaju** [comment]
建议自己list统计。
