### ISSUE TITLE
列宽设置并不精确

### ISSUE THREAD

**Issue by liangmengmeng1993** [alibaba/easyexcel#1195]
x为设置列宽
y为实际结果
x | y
-- | --
54 | 49.5
50 | 45.79
55 | 50.43
20 | 17.93
30 | 27.21
40 | 36.5
10 | 8.64
60 | 55.07
70 | 64.36
80 | 73.64
27 | 24.43
25 | 22.57
101 | 93.14
18 | 16.07
25 | 22.57
17 | 15.14

**Comment by zhuangjiaju** [comment]
建议自定义列宽策略。然后直接调用poi的设置列宽接口
