### ISSUE TITLE
实体类不支持Lombok @Accessors(chain = true)链式编程,有这个注解那么全部就读取为null

### ISSUE THREAD

**Issue by 1725636955** [alibaba/easyexcel#1196]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**
![image](https://user-images.githubusercontent.com/43667484/77813206-b41d6800-70e1-11ea-847f-b858036d44bd.png)

![image](https://user-images.githubusercontent.com/43667484/77813211-bb447600-70e1-11ea-8887-6fa319121dc5.png)
![Uploading image.png…]()

**Comment by 1725636955** [comment]
![image](https://user-images.githubusercontent.com/43667484/77813216-d2836380-70e1-11ea-99a5-9f9b45689715.png)

**Comment by 1725636955** [comment]
当把这个lombok的注解去掉之后一切正常

**Comment by dota17** [comment]
这个问题有人问过    [Model使用了lombok.experimental.Accessors注解会导致读不到值 #836](https://github.com/alibaba/easyexcel/issues/836)

**Comment by 1725636955** [comment]
> 这个问题有人问过 [Model使用了lombok.experimental.Accessors注解会导致读不到值 #836](https://github.com/alibaba/easyexcel/issues/836)

好的
