### ISSUE TITLE
向excel写数据时，如何设置autoTrim为false？

### ISSUE THREAD

**Issue by yangziwen** [alibaba/easyexcel#1197]
```java
EasyExcel.write(output)
        .registerWriteHandler(new SimpleColumnWidthStyleStrategy(20))
        .head(headList)
        .sheet("报表结果")
        .doWrite(dataList);
```
使用上述方式向easyexcel中写数据时，writer会根据globalConfiguration中autoTrim的值对所有字符串的cell进行trim操作。
但是builder中找不到设置autoTrim的相关方法。

**Comment by yangziwen** [comment]
已通过如下方式手动构造解决，但是还是建议在builder中加上autoTrim和其他一些关键参数的设置方法。
```java
WriteWorkbook workbook = new WriteWorkbook();
workbook.setAutoTrim(false);
workbook.setOutputStream(output);
workbook.getCustomWriteHandlerList().add(new SimpleColumnWidthStyleStrategy(20));
workbook.setHead(headList);
new ExcelWriterSheetBuilder(new ExcelWriter(workbook))
        .sheetName("报表结果")
        .doWrite(dataList);
```

**Comment by hhuchang** [comment]
我是这样解决的：
workbook worksheet 都有autoTrim的参数，
我的例子：
ExcelWriter excelWriter=EasyExcel.write(outputstream).withTemplate(fileTemplate_inputStream).build();
WriteSheet writeSheet0=EasyExcel.writerSheet(0).build();
writeSheet0.setAutoTrim(false);
excelWriter.fill(fillData,writeSheet0);
