### ISSUE TITLE
在写入和写出时可以对Java模型里面属性是枚举类型进行转换吗

### ISSUE THREAD

**Issue by leTeng** [alibaba/easyexcel#120]
假如 

 Excel:
 id　　　状态         
 12　　　1

Java 模型 :
````java
class Order{
   private  Status  status
}
````
枚举：
````java
enum Status{
    STATUS1
}
````
可以将excel status列里面的1自动转换为Java 模型的 Status（枚举类型）吗？还是不自动进行转换，在AnalysisEventListener的实现里面自己手动转换。

**Comment by jipengfei-jpf** [comment]
仅支持基本类型，建议换成STRING
