### ISSUE TITLE
多列表fill时候forceNewRow

### ISSUE THREAD

**Issue by sixjo** [alibaba/easyexcel#1201]
多列表fill时候forceNewRow会出现空指针，ExcelWriteFillExecutor类中的shiftRows方法中AnalysisCell analysisCell : templateAnalysisCache.get(currentUniqueDataFlag)改为AnalysisCell analysisCell : analysisCellList就ok了

**Comment by zhuangjiaju** [comment]
已经在2.2.1里面修复
