### ISSUE TITLE
字符串格式为123,456,789时输出excel文件点击一次单元格会自动变成数值型

### ISSUE THREAD

**Issue by CodeBricklayer** [alibaba/easyexcel#1206]
对于字符串形式如标题所言，在导出文件后，点击一次单元格就会自动变成数值型的，数字字符串在单元格展示形式应该为  '123,456,789 ，在字符串数值前面加一个小单引号，即可变成字符串形式

**Comment by dota17** [comment]
可以使用ContentStyle注解将单元格设置为文本格式，可以解决各种数字精度丢失问题
例如：
  public class DemoData {
    @ExcelProperty("字符串标题")
    @ContentStyle(dataFormat = 0x31)   //设置单元格为文本格式
    private String string;
    @ExcelProperty("日期标题")
    private Date date;
    @ExcelProperty("数字标题")
    private Double doubleData;
    /**
     * 忽略这个字段
     */
    @ExcelIgnore
    private String ignore;
}
