### ISSUE TITLE
NumberFormatException 报错，并未被onException捕获

### ISSUE THREAD

**Issue by jy05568536** [alibaba/easyexcel#1210]
**触发场景描述**
版本2.1.6，导入时报错
**触发Bug的代码**
```java
EasyExcel.read(file.getInputStream(), dataClass, readListener).sheet().doRead();
```
正常的读取，invoke正常的数据会进，但一到有问题的那行就会报错，并且不会被onException捕获
**提示的异常或者没有达到的效果**
经过反复debug，发现问题数据，excel中有个字段为 `#NUM!`，我不知道这个是否触发什么关键字或者变量，一解析到那行就出现上述问题，把这个字符改掉后正常

**Comment by jy05568536** [comment]
more info
同事用Mac打开是正常一个数值，猜测应该是一个公式，用windows的同事打开情况一样，显示`#NUM!`，但导入都报同样的错

**Comment by zhuangjiaju** [comment]
这个需要提供下excel 有些不符合规范的数据是会异常。

**Comment by zhuangjiaju** [comment]
不知道是否解决了问题？如果未解决，请重新打开问题。

**Comment by shenyubao** [comment]
@zhuangjiaju 该问题我们也遇到了 .    EasyExcel 版本 v2.2.7 .   Excel 重新保存后恢复. 

原始文件中的数据格式
<c r="J3" s="19"><v></v></c>
重新保存后的文件格式
<c r="J3" s="16"/>

目测是 Excel 中某列为数字, 但<v>为空

**Comment by shenyubao** [comment]
v2.2.11 该问题已修复
