### ISSUE TITLE
web 下载的时候，数据量超过10000条，使用多次写入的方式，文件下载成功，但是文件打开的时候报部分内容有问题

### ISSUE THREAD

**Issue by xuewuyang** [alibaba/easyexcel#1217]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by pdkst** [comment]
请提供一下可以触发问题的demo代码：

建议尝试以下方式
- 拆分业务，多个文件打包下载
- 多次写入必须在`finish()`调用之前
- 生成中间文件，然后异步下载

**Comment by xuewuyang** [comment]
> 请提供一下可以触发问题的demo代码：
> 
> 建议尝试以下方式
> 
> * 拆分业务，多个文件打包下载
> * 多次写入必须在`finish()`调用之前
> * 生成中间文件，然后异步下载

非常感谢您们的关注，这个问题我已经解决了，是我的问题，我之前重复写入的时候，WriteSheet是由ExcelWriterBuilder.sheet().build()方法得到，不是从EasyExcel.writerSheet().build()得到的，所以导致后面的问题；但是我看了源码，有一个疑问，这里都是new 出的writeSheet，应该没什么不一样的，具体原因我也没有深入，再次感谢！
