### ISSUE TITLE
无对象时，能否支持List<Map>格式的数据，head可以用List<Map>,从而让表头与数据匹配对应

### ISSUE THREAD

**Issue by QiFeiLXH** [alibaba/easyexcel#1219]
有时候查询的数据因为是动态列不能写成Bean，数据结果为List<Map>格式，
建议head与data都能支持List<Map>，来达到导出时，能根据Map的key对应输出

**Comment by BeyondTheBlade** [comment]
我也遇到这个问题了，目前我使用的是用流的形式，导出的时候业务上的数据从List<Map>转List<List>，导入的时候List<List>转List<Map>，需要自己处理这个转换

**Comment by QiFeiLXH** [comment]
没怎么明白你的意思，能否说的略微详细点呢，麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Longevity tips"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午3:39
收件人:&nbsp;"alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送:&nbsp;"林旭辉"<1005488340@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 无对象时，能否支持List<Map&gt;格式的数据，head可以用List<Map&gt;,从而让表头与数据匹配对应 (#1219)





 
我也遇到这个问题了，目前我使用的是用流的形式，导出的时候业务上的数据从List转List，导入的时候List转List，需要自己处理这个转换

**Comment by BeyondTheBlade** [comment]
很简单啊，自己业务里做遍历，把数据List<Map<k,v>和你自己的表头模板对应起来（因为是动态的，没有实体类）key相同的，重新构建一个List<List<Object>>返回给easyExcel就好了

**Comment by QiFeiLXH** [comment]
哦哦，那和我现在做的一样的，先处理表头，再处理数据对应起来，还是谢谢你哈





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Longevity tips"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午4:12
收件人:&nbsp;"alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送:&nbsp;"林旭辉"<1005488340@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 无对象时，能否支持List<Map&gt;格式的数据，head可以用List<Map&gt;,从而让表头与数据匹配对应 (#1219)





 
很简单啊，自己业务里做遍历，把数据List<Map<k,v&gt;和你自己的表头模板对应起来（因为是动态的，没有实体类）key相同的，重新构建一个List<List&gt;返回给easyExcel就好了

**Comment by zhuangjiaju** [comment]
目前架构表头是先解析好的，所以暂时先不支持。后续考虑支持。

**Comment by okkpp** [comment]
很多都提到了支持List<Map<String, Object>>的需求, 现在仍然未得到支持,
而上面讨论的临时解决方案, 我认为是非常影响使用体验的, 甚至包括性能...
希望这个需求能提高优先级
