### ISSUE TITLE
ReadSheet的autoTrim默认为true,建议改为false

### ISSUE THREAD

**Issue by sakuraemma** [alibaba/easyexcel#1220]
因为ExcelReader.excelExecutor().sheetList()返回集合中ReadSheet对象的sheetName是未trim的。当使用者不知道该参数时，会导致默认调用查询时找不到包含空格符sheet名的sheet。

**Comment by zhuangjiaju** [comment]
目前看来大部分需求还是需要trim的 暂时不考虑修改。
