### ISSUE TITLE
你好， 问一下导入 验证验证不通过的数据 新增一列 填充失败原因，返回文件怎么做呢。

### ISSUE THREAD

**Issue by houzhao666** [alibaba/easyexcel#1223]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**

**Comment by zhuangjiaju** [comment]
这个需要一个读 一个写。
