### ISSUE TITLE
如果表格后面一列为空，前一列过长，前一列就会把后面的列占据

### ISSUE THREAD

**Issue by BeyondTheBlade** [alibaba/easyexcel#1232]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
如题
**触发Bug的代码**
```java
   // 长数据格式
   .registerWriteHandler(new LongestMatchColumnWidthStyleStrategy())
```
**提示的异常或者没有达到的效果**
没有达到想要的效果，由于模板是动态的，所以不可能事先指定列宽。不知道能否支持自动拉宽列

**Comment by zhuangjiaju** [comment]
自定义样式 有个`warptext`
