### ISSUE TITLE
导入精准度问题

### ISSUE THREAD

**Issue by zhouluoyang0406** [alibaba/easyexcel#1234]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
listener这样接受
invoke(Map<Integer, String> prop, AnalysisContext analysisContext)

excel中是11.111，prop中会变成11.111000000001
excel中是2020/9/14，prop中会变成44088
![image](https://user-images.githubusercontent.com/42863611/79115232-e4d6f000-7db7-11ea-9a2d-a455835ab2a0.png)
![image](https://user-images.githubusercontent.com/42863611/79115251-f7512980-7db7-11ea-962c-0d41845cbe62.png)

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhouluoyang0406** [comment]
切换成2.1.7也木有用

**Comment by zhouluoyang0406** [comment]
@zhuangjiaju 大佬有什么跟进结果么？

**Comment by HusenHuang** [comment]
我这边更新到2.2.0-beta1就可以了

**Comment by zhouluoyang0406** [comment]
@HusenHuang 好的我试试。

**Comment by liqour** [comment]
@HusenHuang @zhouluoyang0406 你们的没问题了吗，我升级了还是有精度丢失的情况

**Comment by HusenHuang** [comment]
我升級了 是沒問題。

**Comment by liqour** [comment]
![image](https://user-images.githubusercontent.com/30460113/79962694-f48ebc80-84ba-11ea-9042-fa4bfcad3593.png)
@HusenHuang 我这边是部分数据出问题

**Comment by liqour** [comment]
我这边尝试了最新的两个版本还是有问题，主要是这几个数值 @HusenHuang 
![image](https://user-images.githubusercontent.com/30460113/79962873-33bd0d80-84bb-11ea-8a2c-658f380bf549.png)

**Comment by zhuangjiaju** [comment]
升级到最新版本。
