### ISSUE TITLE
我的response是一些乱码不知道啥错误。。。能帮忙看下嘛

### ISSUE THREAD

**Issue by LancCJ** [alibaba/easyexcel#1235]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
//获取报表的开始时间和结束时间

        log.info("开始时间:"+startDay);
        log.info("结束时间:"+endDay);

        //查询数据
        List<ExcelDTO> list = tbGarbageBuyService.queryReport(startDay,endDay);

        ExcelWriter writer = null;
        OutputStream outputStream = response.getOutputStream();
        long startTime=System.currentTimeMillis();
        try {
            String fileName = URLEncoder.encode("测试", "UTF-8");
            //添加响应头信息
            response.setHeader("Content-disposition", "attachment; filename=" + fileName+".xlsx");
            response.setContentType("application/msexcel;charset=UTF-8");//设置类型
            response.setHeader("Pragma", "No-cache");//设置头
            response.setHeader("Cache-Control", "no-cache");//设置头
            response.setDateHeader("Expires", 0);//设置日期头

            //实例化 ExcelWriter
            writer = new ExcelWriter(outputStream, ExcelTypeEnum.XLSX, true);

            //实例化表单
            Sheet sheet = new Sheet(1, 0, ExcelDTO1.class);
            sheet.setSheetName("统计表");
            //获取数据
            log.info("查询时间：{}s.条数:{}",(float)(System.currentTimeMillis()-startTime)/1000,list.size());

            startTime=System.currentTimeMillis();
            //输出
            writer.write(list, sheet);
            writer.finish();
            outputStream.flush();
        } catch (IOException e) {
            log.info("导出异常",e);
        } finally {
            try {
                response.getOutputStream().close();
            } catch (IOException e) {
                log.info("导出异常",e);
            }
        }
        log.info("导出：{}s",(float)(System.currentTimeMillis()-startTime)/1000);
```
**异常提示**
PK�;�P_rels/.rels���j�0�_���8�`�Q��2�m��4[ILb��ږ���.[K
�($}��v?�I�Q.���uӂ�h���x>=��@��p�H"�~�}�	�n����*"�H�׺؁�����8�Z�^'�#��7m{��O�3���G�u�ܓ�'��y|a�����D�	��l_EYȾ����vql3�ML�eh���*���\3�Y0���oJ׏�	:��^��}PK��z��IPK�;�P[Content_Types].xml�S�n�0����*6�PU�C���\{�X�%����]8�R�
q�cfgfW�d�q�ZCB|��|�*�*h㻆},^�{Va�^K<4�6�N�XQ�ǆ�9�!P��$��҆�d�c�D�j);��ѝP�g��E�M'O�ʕ����H7L�h���R���G��^�'�{��zސʮB��3�˙��h.�h�W�жF�j娄CQՠ똈���}ιL�U:D�����%އ����,�B���[�	�� ;˱�	�{N��~��X�p�ykOL��kN�V��ܿBZ~����q�� �ar��{O�PKz��q;PK�;�PdocProps/app.xmlM��
�0D�~EȽ��ADҔ���A? ��6�lB�J?ߜ���0���ͯ�)�@��׍H6���V>��$;�SC
;̢(�ra�g�l�&�e��L!y�%��49��`_���4G���F��J��Wg
�GS�b����
~�PK�|wؑ�PK�;�PdocProps/core.xmlm��J�0E%佝���veAP\pE�-$c[l��D���i]+�B��g��6�q �CoMMy�(A���M[���6��$Di����K7M��P���[�>�HҘ ��i�Au8ʐ'¤���Q���-8��d�P0v#F�e�03��Q�ժt�~XZ8��x�ᗍ���oÒ��!�+5MS>��&��|w����f��B�TG�PeDM�@�O�6�<�W��-m
V���e���(y:/�韅�w�˴����f��r'kn�PK����PK�;�Pxl/sharedStrings.xml=�A� ﾂ��.z0Ɣ�`������,�����q2��o�ԇ���N�E��x5�z>�W���(R�K���^4{�����ŀ�5��y�V����y�m�XV�\�.�j����
8�PKp��&x�PK�;�P
xl/styles.xml�TK��0�s
�{&�M�F(�H�Ԉ�4[wRI��O�{H�
,�7�6p�v~3�᳉����˕*�W����Zt{��T�k�ڂ~<^^ҫ�E�� �����޼�2Wu ����4�J�qi���vA$E��l�d�qE�\��AzG*}V����y�Ղ�h��ݓ;&0��*-�%\��C]�ˀ)&!����'ˣ�\	� F:�$W�0K������ۗ߿F�t�>�JKoϰ����b�Ğ&��
��:�����`��J��&�`��޾�lx��i��?�#��~��]�`�Ζq��������˿�T��r��.�^��H���8�9k�b"0)��$�f���y&'y?�q=&�_�x�?b�`�+�&�>5s����!��>ԡ�H��i��g�&���k�佲���-���w���~�V�5aƈ!��k	x����F�̱�[%Ay��2s�~�
O��Uh�
��R�i��Q��0fc����kH��nC�Ͻ�7c�b���M,PK��R��GPK�;�Pxl/workbook.xml���N�0�w�º��A�K�ԍ��_�Kc5�#۴�
����@�1pR:2�~�w�����vlO!�$s���ڸ�������Uu�a��~�26���<��,ƹ���M�Ŕc���B[�d;~-��h�
e���7�Q���ՒKgI�S.[�G��=�1Q� n%4�E^W����!��Cd����7���p�<M�В������t�J�%���6"��Q2]��W�PK�e�&�`PK�;�Pxl/_rels/workbook.xml.rels��Mk�0@���}q���n/c����c+qh"K�迟���@;�$��{��~Γy�"#���i� �#
^�O7�`D=E?1�b�n��8y�?$�YLE�8H���Z		g/
g����^�6�p��U���r΀%�좃����/�I�`|�Rˤ��:f����~���mF�v�����:���ׯ�������p9HB�SyݵK~�����PK�;��3PK�;�Pxl/worksheets/sheet1.xml��Qo�6���+��d^���&N�%�	�uۻ+�Q�
du��%;�N�K��b�X���L�<���������.��,�XD�zs�,���Y����6�x���s�~�>�u7q�o����>L�ۻ�z=���S�q��7�z�9�>L�Om=_E��T
a���r]].��z�78i��Y����p�_��y;����~i����]�"׽n��s������V�����CW~k'��~�m���<���s�R�����ͼ���6ϓֽ����'�&��W�ܬ���s׺�/]���w�e�^��H%�*E�
��I/.���U���j�x}�Q
����3�CF��&bxU��M�.�IkFo$��p#Ya�\�L
&I����;Ҭ��N�~�멃rD#�h���攣$�u�n'�n'�}f䎼���[;|{J�<n\W��gP9�/b1�y�~��?8܂C	�zQ�Sq*��÷�-?�k�6Q�������r�7�
���Yð ��U)/H}��)� �Z�`���rΗ2�cgȰ��3	
Ip(AU�K�I�7��k�0ô���'Q���+wD
�s�dU�b�9��Rp.!��P���izD��i�֨Dg
(A圯[�b������<B ��U�^����S^��lX��2^�|�[j�~��rx��PP9�O"31�CL
�$DJP��͎D�7�k�ںO�%�IP9��#Oٱ	&g��0��Ue^�$F�]���b+��j?Ͼ#�(s�:�2Nٕ]
�E���!CMJ��A��:������=�D$ֿ��{1�J��������J���!�bcX��d	ɒ��(���7�
�>ix�J$*�(g���-��G���qA�b���ѦDY�+��pD|�9�g�����!�f"�kf:���2g��F��.m
�&�Z�G��"b�Qd�@�9
9�^�Sô����	e�Z��&Nx���X��bzBY�??�(@Q I#�n&���@q����Cў0K���&܆U-�)��uK�&U(+��*�*
�Ӏ��q{��0Z���&�[ M,�,��OJB�c�BY�?d�(e�\D����P��}-�9k�6��5
�k�0l����h��(�N#
�<�"�Z(s�چ�Ф`MH�,pN�6%ʊ���F���k<8����U��e�Z�v�Z�\1y�6*KW>(`�BY�?}�Q���u�k����+�)e�6A:S֭a�?��F��5r�B�c=�-��O����,&GYL��iāg'ϲ$f1�9k�v�:��B���!�]��-ڔ(+�*�M��.�u�P_׫�vt��L��'9<���4�����v��f=�D��]�}�tu�+�/�狃X���pW4iw���y����O^�PK�'��\�PK�;�P��z��I_rels/.relsPK�;�Pz��q;[Content_Types].xmlPK�;�P�|wؑ��docProps/app.xmlPK�;�P����gdocProps/core.xmlPK�;�Pp��&x��xl/sharedStrings.xmlPK�;�P��R��G
exl/styles.xmlPK�;�P�e�&�`�xl/workbook.xmlPK�;�P�;��3�xl/_rels/workbook.xml.relsPK�;�P�'��\��	xl/worksheets/sheet1.xmlPK		?x
**建议描述**

**Comment by dota17** [comment]
这个可能是mvn 编码方式的问题，以前遇到过   [MAVEN编码从GBK改为UTF-8](https://blog.csdn.net/starcraft501/article/details/82718285)

**Comment by LancCJ** [comment]
不是吧 这个我已经发送请求 返回的错误了，这个错误代码是浏览器F12查看response拿下来的

**Comment by LancCJ** [comment]
找到原因了 和编码没关系 我前端页面使用了ajax发送下载的请求就是如此问题，假如直接将地址黏贴到地址就能下载到文件response也不会乱码，这是什么操作？？？？前端JS该咋弄呢。。。。

**Comment by LancCJ** [comment]
我是直接使用 window.location.href = url; 替换原来的ajax解决问题了 。

**Comment by 985231980** [comment]
> 我是直接使用 window.location.href = url; 替换原来的ajax解决问题了 。

谢谢

**Comment by doubleLLL3** [comment]
我也遇到了，倒是把OutputStream换成File的方式，就可以了。好奇什么原因？
