### ISSUE TITLE
能否增加LabelSSTRecord类型数据的支持

### ISSUE THREAD

**Issue by lvvgang** [alibaba/easyexcel#1236]
**建议描述**
目前不支持LabelSSTRecord类型数据的读取，能够添加对应的支持，或者提供注册AbstractXlsRecordHandler的方法

**Comment by zhuangjiaju** [comment]
读取这个字段的需求是什么？

**Comment by lvvgang** [comment]
因为有些excel的列就是这种类型，会导致读取失败

**Comment by zhuangjiaju** [comment]
比如 能否提供个demo

**Comment by zhuangjiaju** [comment]
不知道是否已经解决了问题？如果未解决 请重新打开问题。
