### ISSUE TITLE
是否能考虑支持Android使用，目前Android使用会有一些包异常

### ISSUE THREAD

**Issue by lc824767150** [alibaba/easyexcel#1242]
是否能考虑支持Android使用，目前Android使用会有一些包异常

**Comment by zhuangjiaju** [comment]
安卓不是特别懂。以前也有人问过，不知道最终有人解决了没。解决到时候 可以写个方案。

**Comment by tanbo091** [comment]
android 这边目前 easyexcel 2.2.3 可以用。
gradle 配置
`
//easyexcel  && xmlbeans 一起用编译不会出错
    implementation ('com.alibaba:easyexcel:2.2.3')
    implementation group: 'org.apache.xmlbeans', name: 'xmlbeans', version: '3.1.0'//xmlbeans 需要覆盖
`
proguard 文件配置。 
`
-keep class jxl.** {*;}
-keep class common.log.** {*;}`

基本功能可用，还有很多细节我没深入，我这边可以混淆编译使用就没深究

**Comment by zhaoyouzhi** [comment]
> android 这边目前 easyexcel 2.2.3 可以用。
> gradle 配置
> `//easyexcel && xmlbeans 一起用编译不会出错 implementation ('com.alibaba:easyexcel:2.2.3') implementation group: 'org.apache.xmlbeans', name: 'xmlbeans', version: '3.1.0'//xmlbeans 需要覆盖`
> proguard 文件配置。
> ` -keep class jxl.** {*;} -keep class common.log.** {*;}`
> 
> 基本功能可用，还有很多细节我没深入，我这边可以混淆编译使用就没深究

如何解决rt.jar包下，javax.xml.stream.XMLEventFactory等缺失问题？

**Comment by zxc503** [comment]
> android 这边目前 easyexcel 2.2.3 可以用。
> gradle 配置
> `//easyexcel && xmlbeans 一起用编译不会出错 implementation ('com.alibaba:easyexcel:2.2.3') implementation group: 'org.apache.xmlbeans', name: 'xmlbeans', version: '3.1.0'//xmlbeans 需要覆盖`
> proguard 文件配置。
> ` -keep class jxl.** {*;} -keep class common.log.** {*;}`
> 
> 基本功能可用，还有很多细节我没深入，我这边可以混淆编译使用就没深究

我按你方法试了，但是会出现找不到javax.xml.stream.XMLStreamReader的类文件

**Comment by zxc503** [comment]
> android 这边目前 easyexcel 2.2.3 可以用。
> gradle 配置
> `//easyexcel && xmlbeans 一起用编译不会出错 implementation ('com.alibaba:easyexcel:2.2.3') implementation group: 'org.apache.xmlbeans', name: 'xmlbeans', version: '3.1.0'//xmlbeans 需要覆盖`
> proguard 文件配置。
> ` -keep class jxl.** {*;} -keep class common.log.** {*;}`
> 
> 基本功能可用，还有很多细节我没深入，我这边可以混淆编译使用就没深究

请问你使用的poi是什么版本的

**Comment by tanbo091** [comment]
我这边是引入正确的 依赖，然后让 easy excel 去移除相应的依赖。
例如我当时，因为 xmlbeans 出错，所以引入自己的xmlBean 3.1.0，覆盖掉 easyexcel 里面自带的 xmlBean

implementation ('com.alibaba:easyexcel:2.2.3') 
implementation group: 'org.apache.xmlbeans', name: 'xmlbeans', version: '3.1.0'
