### ISSUE TITLE
如何在自定义Listener中读取外层参数

### ISSUE THREAD

**Issue by leslie010203** [alibaba/easyexcel#1243]
String paramConfigs = "2233";
            ExcelImportListener excelImportListener = new ExcelImportListener();
            ExcelReader build = EasyExcel.read(file.getInputStream()).build();
            List<ReadSheet> readSheets = build.excelExecutor().sheetList();
            //多sheet处理
            //1.参数传递
            for (ReadSheet readSheet : readSheets) {
                EasyExcel.read(file.getInputStream()).sheet(readSheet.getSheetNo()).doReadSync();
            }

如何在自定义监听中获取paramConfigs  这个参数呢

**Comment by leslie010203** [comment]
晓得了

**Comment by wangyuhuich** [comment]
请问这个问题是如何解决的？

**Comment by leslie010203** [comment]
在listener中定义变量，然后用到的时候set进去




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"王昱辉"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 上午9:02
收件人:&nbsp;"alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送:&nbsp;"超级美的吴大梦"<872263002@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 如何在自定义Listener中读取外层参数 (#1243)





 
请问这个问题是如何解决的？

**Comment by wangyuhuich** [comment]
明白了，谢谢。
Map<String, Object> param= new HashMap<>();
ExcelReader reader = EasyExcel.read(file.getInputStream()).customObject(param).build();
