### ISSUE TITLE
关于如何自定义head头部单元格合并策略问题

### ISSUE THREAD

**Issue by huangfenghai** [alibaba/easyexcel#1248]
**建议描述**
大佬你好，请问下目前easyexcel框架支持自定义head头部单元格合并策略吗，目前似乎源码里head类中只能使用loopMergerstrategy策略，只要head()方法的list元素中有相同的值就会自动合并，无法达到自定义合并效果，盼回复~

**Comment by zhuangjiaju** [comment]
可以自己参照`LoopMergeStrategy` 书写，只要`isHead`参数等于`true`的时候，就是可以处理自己的合并。
