### ISSUE TITLE
excel导出时，向首行或指定行插入数据

### ISSUE THREAD

**Issue by 908216809** [alibaba/easyexcel#1252]
导出的数据存在计算逻辑，计算完成后需要将汇总计算行插入到表头下第一行中。
我们目前的组件是否支持此功能。

**Comment by zhuangjiaju** [comment]
建议使用填充功能 https://www.yuque.com/easyexcel/doc/fill

**Comment by 908216809** [comment]
表头数据是动态配置的，没有模板，没有实体，同一报表不同用户导出的表头是不一样的。
