### ISSUE TITLE
最新的2.2.0-beta2 版本，会出现空行一直读取的问题

### ISSUE THREAD

**Issue by Mooneal** [alibaba/easyexcel#1257]
之前的正式版2.1.3 版本没有

**Comment by zhuangjiaju** [comment]
能否详细描述下 没理解什么意思。只要空行有数据 或者格式 就应该读出来。

**Comment by Mooneal** [comment]
是这样的，
![企业微信截图_100d7641-e185-4ee2-bfbe-d9ff0440397b](https://user-images.githubusercontent.com/22398229/79964726-af1fbe80-84bd-11ea-8058-baf7c7192d12.png)
比如像这样的情况，之前的版本解析到7429行 就不会再解析了。但是我换成2.2.0-beta2 之后，它会一直解析。

**Comment by zhuangjiaju** [comment]
嗯 这个是对的 自己需要加入一个判断标志 到哪一行数据为空 就忽略。因为这些空行有样式，所以读取出来了。

**Comment by wallacepang** [comment]
> 嗯 这个是对的 自己需要加入一个判断标志 到哪一行数据为空 就忽略。因为这些空行有样式，所以读取出来了。

这个判断标识要怎么加
