### ISSUE TITLE
能不传入监听器java been么？

### ISSUE THREAD

**Issue by lizhou1994** [alibaba/easyexcel#1258]
我这有一个需求 ，读取一个 大概100W条数据的 excel，然后根据这个excel新建一张表 并插入 100W条数据。
此时  表头的列数 是不确定的  ，表头名也是不确定的，所以 当我 要用 easy excel 的时候  必须 传入 Map   
例如 ：

public class ExcelDataListener extends AnalysisEventListener<HashMap<Integer,String>> {

    private List<HashMap<Integer,String>> result = new ArrayList<>();

    @Override
    public void invokeHead(Map<Integer, CellData> headMap, AnalysisContext context) {
        //表头
        System.out.println("--------head---------");
        for(int i =0;i<headMap.size();++i){
            CellData cellData = headMap.get(i);
            System.out.println(cellData.getStringValue());
        }
        System.out.println("--------head---------");
    }

    @Override
    public void invoke(HashMap<Integer,String> o, AnalysisContext analysisContext) {
        //每列的数据
        System.out.println("---------"+analysisContext.readRowHolder().getRowIndex()+"---------");
        result.add(o);
        System.out.println("-------------------");
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext analysisContext) {
        System.out.println();
    }
}

我想要的效果是   ：
//有一个 类似行 数据的java been
public class ExcelDataListener extends AnalysisEventListener<<RowCell>> {

    private List<RowCell> result = new ArrayList<>();

    @Override
    public void invokeHead(Map<Integer, CellData> headMap, AnalysisContext context) {
        //表头
        System.out.println("--------head---------");
        for(int i =0;i<headMap.size();++i){
            CellData cellData = headMap.get(i);
            System.out.println(cellData.getStringValue());
        }
        System.out.println("--------head---------");
    }

    @Override
    public void invoke(RowCell o, AnalysisContext analysisContext) {
        //每列的数据
        System.out.println("---------"+analysisContext.readRowHolder().getRowIndex()+"---------");
        result.add(o);
        System.out.println("-------------------");
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext analysisContext) {
        System.out.println();
    }
}

**Comment by zhuangjiaju** [comment]
请用Map去接收。自己可以转成自己需要的bean
