### ISSUE TITLE
@NumberFormat和@ExcelProperty(converter = BigDecimalNumberConverter.class)冲突，@NumberFormat失效

### ISSUE THREAD

**Issue by Accright** [alibaba/easyexcel#1261]
**触发场景描述**
在字段上同时注解了
@NumberFormat(",###.##")和@ExcelProperty(converter = BigDecimalNumberConverter.class)
想要的效果是导出的格式类型为数字格式并且带有千位分隔符，但是发现@NumberFormat(",###.##")失效，如果去除converter = BigDecimalNumberConverter.class该注解，导出的带有千位分隔符，但是Excel中保存的为文本类型，不再是数字类型。
**触发Bug的代码**
```java
@NumberFormat(",###.##")
@ExcelProperty(value ={"测试"}, converter = BigDecimalNumberConverter.class, index=1)
private BigDecimal test;
```
**提示的异常或者没有达到的效果**
预期：输出带千位分隔符的数字格式cell
异常：NumberFormat不生效

**Comment by zhuangjiaju** [comment]
这个需要自定义样式 然后社会dataformat实现
