### ISSUE TITLE
关于填充excel问题

### ISSUE THREAD

**Issue by liubai-paroniria** [alibaba/easyexcel#1263]
**问题**
照着官方demo的最简单的填充excel方法：simpleFill() 出现一个莫名问题，警告提示之后会重启项目两次
**截图如下**
![代码](https://user-images.githubusercontent.com/64222796/80139238-b7205100-85d8-11ea-9688-1fc532e4711c.png)
![问题](https://user-images.githubusercontent.com/64222796/80139240-b8ea1480-85d8-11ea-9c9e-8453ec72eb48.png)

**Comment by zhuangjiaju** [comment]
eclipse的报错 忽略就行。
https://bugzilla.redhat.com/show_bug.cgi?id=146959

**Comment by liubai-paroniria** [comment]
但是我用的是idea，填充excel完会重启项目
