### ISSUE TITLE
映射entity使用lombok的@Accessors(chain = true)注解时,无法映射

### ISSUE THREAD

**Issue by bozer666** [alibaba/easyexcel#1264]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
映射entity使用lombok的@Accessors(chain = true)注解时,无法映射,去掉正常
![微信截图_20200424120849](https://user-images.githubusercontent.com/34758797/80174144-5e76a580-8624-11ea-87cf-ea6808ab0910.png)

![微信截图_20200424120800](https://user-images.githubusercontent.com/34758797/80174105-47d04e80-8624-11ea-9929-9d9e10e2f669.png)

**触发Bug的代码**
[栗子](https://github.com/bozer666/easyexcel-test)
**提示的异常或者没有达到的效果**
映射的entity属性值为null

**Comment by zhuangjiaju** [comment]
这个是cglib的问题暂时不考虑 解决 后续会考虑
