### ISSUE TITLE
easyexcel软件测试

### ISSUE THREAD

**Issue by dota17** [alibaba/easyexcel#1268]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
@zhuangjiaju   我发现社区基于easyexcel测试是基于使用方式进行的。单元测试、接口测试
比较欠缺，某些模块覆盖率也稍微低了些。如果想补充单元测试用例，您能给一些意见吗？

**Comment by zhuangjiaju** [comment]
按照现有格式 覆盖率的模块可以自接补充。
