### ISSUE TITLE
如果想要导出的数据是不确定的，无法构建实体类，有没有好的办法？

### ISSUE THREAD

**Issue by PaulWang92115** [alibaba/easyexcel#1271]
比如，数据库里存了几个字段，我需要随机选出几个字段组成 excel 导出，该如何做？

**Comment by dota17** [comment]
把这些字段放入到一个list中，然后传入head()，参考[动态头，实时生成头写入](https://www.yuque.com/easyexcel/doc/write)

**Comment by zhuangjiaju** [comment]
有个 根据参数 只导出指定列 可以参考下。
