### ISSUE TITLE
使用自动调整列宽方法不稳定

### ISSUE THREAD

**Issue by hanhaiszw** [alibaba/easyexcel#1277]
EasyExcel.write(outputStream, HttpFloorMsgExpand.class).sheet("数据")
        .registerWriteHandler(new LongestMatchColumnWidthStyleStrategy())
        .doWrite(dataList);

列宽首次可以自动调整宽度，之后就不能调整了

**Comment by zhuangjiaju** [comment]
升级到2.2.3
