### ISSUE TITLE
动态表头建议

### ISSUE THREAD

**Issue by scott-zhu** [alibaba/easyexcel#1278]
**建议描述**
目前的动态表头需要全部重写表头才能使用setHead方法，建议能够同时支持模板文件表头和自定义表头，可以节省很多代码啊，谢谢

**Comment by zhuangjiaju** [comment]
没理解什么意思 能否详细描述下

**Comment by scott-zhu** [comment]
private List<List<String>> head() {
        List<List<String>> list = new ArrayList<List<String>>();
        List<String> head0 = new ArrayList<String>();
        head0.add("字符串" + System.currentTimeMillis());
        list.add(head0);
        return list;
    }
EasyExcel.write(fileName)
            // 这里放入动态头
            .head(head()).sheet("模板")
            // 当然这里数据也可以用 List<List<String>> 去传入
            .doWrite(data());
目前动态头是这种形式，自定义文本，然后调用head方法。

@Data
public class DemoData {
    @ExcelProperty("字符串标题")
    private String string;
    @ExcelProperty("日期标题")
    private Date date;
    @ExcelProperty("数字标题")
    private Double doubleData;
}
我想要同时使用@ExcelProperty注解标识的字段和head方法标识的字段

**Comment by scott-zhu** [comment]
> private List<List> head() {
> List<List> list = new ArrayList<List>();
> List head0 = new ArrayList();
> head0.add("字符串" + System.currentTimeMillis());
> list.add(head0);
> return list;
> }
> EasyExcel.write(fileName)
> // 这里放入动态头
> .head(head()).sheet("模板")
> // 当然这里数据也可以用 List<List> 去传入
> .doWrite(data());
> 目前动态头是这种形式，自定义文本，然后调用head方法。
> 
> @DaTa
> public class DemoData {
> @ExcelProperty("字符串标题")
> private String string;
> @ExcelProperty("日期标题")
> private Date date;
> @ExcelProperty("数字标题")
> private Double doubleData;
> }
> 我想要同时使用@ExcelProperty注解标识的字段和head方法标识的字段

**Comment by zhuangjiaju** [comment]
这个暂时不考虑。2个合并还有先后等问题。后续如果遇到的同学多，可以考虑加入。

**Comment by taosehngyijiushi** [comment]
怎么在注解头上面动态加一行内容
