### ISSUE TITLE
能否在使用STRING接收Number类型数据时，新增判断，最大程度的避免.0么

### ISSUE THREAD

**Issue by zhuzhoulin** [alibaba/easyexcel#1279]
今天项目出现一个需求，使用easyExcel读取文件时，不传递head.class,则默认使用String接收Excel，在处理number类型时，出现 .0 的情况。后面我发现可以在 StringNumberConverter 中，对 contentProperty 进行判空，然后使用 numberFormat.format(cellData.getDoubleValue()） 解决。能否官方也加上这个呢？最大程度的避免出现.0的情况。 以下为我的代码
     // Excel defines formatting
        if (cellData.getDataFormat() != null) {
            if (DateUtil.isADateFormat(cellData.getDataFormat(), cellData.getDataFormatString())) {
                return DateUtils.format(HSSFDateUtil.getJavaDate(cellData.getDoubleValue(),
                        globalConfiguration.getUse1904windowing(), null));
            }  else if(contentProperty == null) {
                try{
                    //解决easyExcel 解析无 CLASS 对象时，Number to string  用String去接收数字，出现小数点等情况
                    NumberFormat numberFormat =  NumberFormat.getInstance();
                    numberFormat.setGroupingUsed(false);
                   return numberFormat.format(cellData.getDoubleValue());
                } catch (Exception e) {
                    return NumberUtils.format(cellData.getDoubleValue(), contentProperty);
                }
            } else {
                return NumberUtils.format(cellData.getDoubleValue(), contentProperty);
            }
        }

**Comment by zhuangjiaju** [comment]
请使用2.2.3级以上版本。
