### ISSUE TITLE
如何压缩写入的数据String类型的内存占用?

### ISSUE THREAD

**Issue by greydesolate** [alibaba/easyexcel#128]
这两天做了下测试,大量数据情况下(100万的几列String数据情况)String消耗内存几百MB,感觉是写入Excel内存压力的重大来源,不知道大家有什么好方法降低这个String消耗内存的方法么?

[当前使用的esaypoi的方法](http://easypoi.mydoc.io/#text_202984)

本打算想试试esayexcel是不是可以降低写入这块内存消耗,但是暂时没找到续写Excel的途径.

**Comment by jipengfei-jpf** [comment]
导出不要一次写，第一批写一批。
