### ISSUE TITLE
请问如何从excel的指定行追加内容，原来的行数据不覆盖

### ISSUE THREAD

**Issue by KoalaInTree** [alibaba/easyexcel#1281]
`
int index = 0;      

 for (int i = 0; i < 10; i++) {
            ExcelWriterSheetBuilder build = EasyExcel.write(file).relativeHeadRowIndex(index).sheet("sheetName");
            List list = new ArrayList();
            list.add(1);
            build.doWrite(list);
            index+=list.size();
        }`

上面是我的伪代码。 我最终生成的excel会把前面九次生成的数据覆盖。只留下最后一次的数据，所在行是对的

**Comment by KoalaInTree** [comment]
期待回复

**Comment by zhuangjiaju** [comment]
参照多次写入。
