### ISSUE TITLE
如何实现预读合并单元格信息？

### ISSUE THREAD

**Issue by Double-z-Z** [alibaba/easyexcel#1283]
如何在读取数据之前，获取到合并单元格的信息，用于拆分合并单元格的值？

- 使用场景：处理数据时，通常要将合并单元格会被拆分为多行、列相同的值来处理，而这依赖于mergeCell信息。
- 具体原因：mergeCell的标签信息位于sheet.xml末尾，合并单元格的信息如果必须要读取所有数据之后再获得，就无法在流式处理中拆分单元格信息。

我尝试读两次这个流，但是文件较大时，会多耗费很长时间，不能采取。这个需求可能不会被本项目考虑，能否有一些建议我去实现这个事情，谢谢。

**Comment by zhuangjiaju** [comment]
xlsx的其实可以调整顺序，xls无法调整。后续考虑下。

**Comment by zhuangjiaju** [comment]
这个目前没法实现 只能一个文件读2遍 第一次读merge 然后自己记录到内存 第二次读取内容
