### ISSUE TITLE
提供全局Converter的注册方式

### ISSUE THREAD

**Issue by guodzh1** [alibaba/easyexcel#1284]
### 建议描述
希望能提供一个配置**全局Converter**的方式，当前最新的2.2.2版本只能在AbstractParameterBuilder中注册自定义的Converter。

### 使用场景
- 比如我为jdk8的日期相关类写了一系列的Converter，那么我每次使用都得写一长串代码去注入converter：![converter注册示例](https://user-images.githubusercontent.com/23622923/80559216-6a40de00-8a0f-11ea-9222-dd5740f43513.png)
- 我想过再封装一层，但是发现场景丰富用的参数比较多，封装的方法会非常多，直接用原生的builder链式调用的形式会更简洁。
- 在每个VO的字段里标明使用的自定义Converter倒是可以用，但是感觉不优雅。

### 建议实现
改造下DefaultConverterLoader，公开read converter和write converter的注册方式，保证存储Converter的map线程安全即可。

**Comment by zhuangjiaju** [comment]
可能会有多个excel的读写，所以全局的需要考虑下。

**Comment by ch219318** [comment]
发现一种改变全局converter的方法：easyexcel版本：3.2.1
@Slf4j
@Component
public class CustomerDefaultConverterLoader implements ApplicationRunner {
    
    @Override
    public void run(ApplicationArguments args) throws Exception {
        log.info("=====加载自定义easyexcel的converter开始");
        Map<ConverterKeyBuild.ConverterKey, Converter<?>> allConverter = DefaultConverterLoader.loadAllConverter();
        putCustomConverter(allConverter, new CustomBigDecimalStringConverter());
        putCustomConverter(allConverter, new CustomIntegerStringConverter());
        putCustomConverter(allConverter, new CustomLongStringConverter());
        putCustomConverter(allConverter, new CustomStringStringConverter());
        putCustomConverter(allConverter, new CustomDateStringConverter());
        log.info("=====加载自定义easyexcel的converter结束：" + allConverter.size());
    }
    
    private void putCustomConverter(Map<ConverterKeyBuild.ConverterKey, Converter<?>> allConverter,
            Converter<?> converter) {
        allConverter.put(ConverterKeyBuild.buildKey(converter.supportJavaTypeKey(), converter.supportExcelTypeKey()),
                converter);
    }
}
