### ISSUE TITLE
求助：导入一个7M左右大小的.xlsx文件，报异常信息

### ISSUE THREAD

**Issue by 66coder66** [alibaba/easyexcel#1287]
**异常代码**
```java
InputStream ins = file.getInputStream();
ExcelListener listen = new ExcelListener(tableName);
第一种写法：
EasyExcel.read(ins,listen).readCache(new Ehcache(20)).doReadAll();
第二种写法：
ExcelReader ereader = EasyExcel.read(ins,listen).build();
```
**异常提示**
com.alibaba.excel.exception.ExcelAnalysisException: java.lang.NoSuchMethodError: org.terracotta.statistics.StatisticsManager.tags([Ljava/lang/String;)Ljava/util/Set;
at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:51)
**建议描述**
1.两种写法在读同一个7M左右（7000多条数据）的xlsx文件时都报异常了
2.项目中自己依赖的可能影响到的jar:net.sf.ehcache-version-2.10.4
试了好多次没有解决这个异常，请大家帮忙！

**Comment by zhuangjiaju** [comment]
`ehcache`至少3.4.0

**Comment by 66coder66** [comment]
在保持项目jar包不变的情况下，针对我的项目，引入org.ehcache.ehcache版本高于3.5的jar解决此异常

**Comment by angiely1115** [comment]
我这边org.ehcache.ehcache版本3.6.3;net.sf.ehcache版本2.10.6也有此异常
