### ISSUE TITLE
数据追加问题

### ISSUE THREAD

**Issue by KennCai** [alibaba/easyexcel#1289]
**异常代码**
```java
@Test
    public void noModelWrite() throws FileNotFoundException {
        //初始化文件
        String fileName = "F:\\test\\aa.xlsx";
        EasyExcel.write(fileName).head(head()).sheet("模板").doWrite(dataList());
        //追加写入
        FileOutputStream out = new FileOutputStream(fileName,true);
        EasyExcel.write(out).head(head()).sheet("模板").doWrite(dataList());
    }
```
**异常提示**
![image](https://user-images.githubusercontent.com/22788420/80697163-2cc17b00-8b0b-11ea-9718-a40393348141.png)
![image](https://user-images.githubusercontent.com/22788420/80697191-364ae300-8b0b-11ea-8fe2-1bef713a1344.png)

**建议描述**
对excel文件做追加数据的操作，数据并未追加写入，而且会破坏文件 ，

**Comment by zhuangjiaju** [comment]
使用`withTemplate`
