### ISSUE TITLE
导入的时候是否能判断是我们想要的模板

### ISSUE THREAD

**Issue by kuangfengyi** [alibaba/easyexcel#1294]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
这个需要自己解析后判断。
