### ISSUE TITLE
1.0.2读取excel

### ISSUE THREAD

**Issue by Luffyera** [alibaba/easyexcel#130]
读取使用office打开过的excel的时候会在经纬度字段上加很多莫名奇妙的数字，比如29.321会被解析成29.23100000000001，这个后面的00000000001还是不固定的，会出现随机的数字字符串，用wps打开就不会这样,麻烦问一下是什么原因，还有maven库最新的版本是1.1.1，最新的这个EasyExcelFactory类无法使用，什么时候更新maven库呢

**Comment by Luffyera** [comment]
![default](https://user-images.githubusercontent.com/24861532/48525668-f87ae000-e8bf-11e8-8be6-9ddda18ed48f.png)

**Comment by jipengfei-jpf** [comment]
已解决
