### ISSUE TITLE
19位长度数字用String接收，读到的值和实际不一致

### ISSUE THREAD

**Issue by lineagezd** [alibaba/easyexcel#1301]
easyexcel 版本 2.2.3

通过String接收如下数值

3101011021236150000

最终显示为

3101011021236149800

**Comment by lm16** [comment]
好像没问题

**Comment by lm16** [comment]
好像没问题，简单跑了一下

**Comment by lineagezd** [comment]
试了下，标记成String没问题，但是如果是数字类型的话excel默认把值变成科学计数法，精度就缺失了
