### ISSUE TITLE
求：在使用head()自定义表头时如何生成复杂表头（两行表头）

### ISSUE THREAD

**Issue by GxSukn** [alibaba/easyexcel#1302]
//这里面的head()的参数怎么diy才能生成复杂表头（两行表头）
EasyExcel.write(fileName).head(head()).sheet("模板").doWrite(data());

private static List<List<String>> head() {
        List<List<String>> list = new ArrayList<List<String>>();
        List<String> head0 = new ArrayList<String>();
        head0.add("字符串");
        List<String> head2 = new ArrayList<String>();
        head2.add("日期");
        list.add(head0);
        list.add(head0);
        list.add(head2);
        return list;
    }

例如：
|        总表头         |
|字符串 | 日期|

**Comment by GxSukn** [comment]
第一行 总表头占据两个单元格
第二行 字符串与日期各占一个单元格

**Comment by keanepeng** [comment]
请参阅官方文档https://alibaba-easyexcel.github.io/quickstart/write.html
写excel -> 复杂头写入
![image](https://user-images.githubusercontent.com/33192717/81764901-308acf80-9505-11ea-84ac-0bc156b25f94.png)

**Comment by GxSukn** [comment]
> 请参阅官方文档https://alibaba-easyexcel.github.io/quickstart/write.html
> 写excel -> 复杂头写入
> ![image](https://user-images.githubusercontent.com/33192717/81764901-308acf80-9505-11ea-84ac-0bc156b25f94.png)

官方文档看过了，里面只写了使用对象时的复杂头，我想用list来生成数据，怎么才能实现复杂头呢

**Comment by zhuangjiaju** [comment]
就是双重list解决。

**Comment by GxSukn** [comment]
> 就是双重list解决。

算了，java实现excel 太麻烦了，还是选择入手python解决吧

**Comment by GxSukn** [comment]
在发问题到现在已经自学python处理好了，说实话，python处理Excel真的比java方便太多了

**Comment by sunxiang0918** [comment]
双重list 只能创建出 两行的表头, 不能创建出跨列的表头. 

比如:我希望的是

|    header1                  |  header2|
| header1.1|header1.2|                 |

**Comment by 8bun** [comment]
> 双重list 只能创建出 两行的表头, 不能创建出跨列的表头.
> 
> 比如:我希望的是
> 
> |---header1----------| header2|
> | header1.1|header1.2|----------|

兄弟，这种表头还能不能用easyexcel来创建了？
