### ISSUE TITLE
自适应列宽只有第一次生效的bug

### ISSUE THREAD

**Issue by hzzgit** [alibaba/easyexcel#1303]
public class LongestMatchColumnWidthStyleStrategy extends AbstractColumnWidthStyleStrategy {
    private static final int MAX_COLUMN_WIDTH = 255;
    private static final Map<Integer, Map<Integer, Integer>> CACHE = new HashMap(8);

自适应列宽的这个类当中用来缓存每一行的单元的最大字段长度,这边用了私有静态最终的Map,导致了每次导出的自适应列宽都用第一次导出的宽度
我改为 private  Map<Integer, Map<Integer, Integer>> CACHE = new HashMap(8);
之后就正常了,
版本是
    <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>2.1.4</version>
        </dependency>
注:才疏学浅,若有错误请见谅

**Comment by zhuangjiaju** [comment]
非常感谢您的已经。这个是个bug。已经在2.2.3修复。
