### ISSUE TITLE
怎么让单元格内的内容强制换行，使用\r\n后，导出的文件单元格必须获得鼠标焦点后才换行，有没有方法导出之后鼠标不聚焦就是换行的

### ISSUE THREAD

**Issue by lovesyx2012** [alibaba/easyexcel#1308]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by lovesyx2012** [comment]
需要自己设置样式，
HorizontalCellStyleStrategy
setWrapped(true)

**Comment by wzdlagrange** [comment]
如果是用JavaBean打注解来实现导出样式
可以在字段上面加 注解 @ContentStyle(wrapped = true)
