### ISSUE TITLE
写excel标题，不能从第二行开始写

### ISSUE THREAD

**Issue by orangesea525** [alibaba/easyexcel#1310]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
写excel标题，不能从第二行开始写。也没有对外接口可扩展，对数据行进行单独设置高度宽度的，这样无法隐藏某一行数据。后面可否考虑加上？

**Comment by zhuangjiaju** [comment]
`relativeHeadRowIndex` 参数设置。
自定义高度参照自定义样式。
