### ISSUE TITLE
导入wps新建的Excel文件报错

### ISSUE THREAD

**Issue by literatureandyou** [alibaba/easyexcel#1311]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
导入wps新建的Excel文件报错
**触发Bug的代码**
```List<Object> excelReaderBuilder = EasyExcel.read(inputStream).doReadAllSync();
   这里写代码
```
**提示的异常或者没有达到的效果**
java.lang.NoClassDefFoundError: org/openxmlformats/schemas/spreadsheetml/x2006/main/impl/CTSheetsImpl$1SheetList

**Comment by zhuangjiaju** [comment]
查看常见问题。应该是版本冲突。

**Comment by literatureandyou** [comment]
是的    多了一个poi的3.15版本，已经解决，谢谢您的解答。
