### ISSUE TITLE
如何对多行表头，分行设置不同的样式？

### ISSUE THREAD

**Issue by yu514950381** [alibaba/easyexcel#1317]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
![image](https://user-images.githubusercontent.com/31887388/82109824-b27c3200-976b-11ea-94c8-72ff4b88cd84.png)
你好，请问一下，我所要导出的Excel一般有两行表头，假如我第一行想要底色是白色，第二行想要底色是蓝色，应该如何分别处理？

我曾经按照自定义拦截器写了处理代码，貌似这种思路不太对？我在下列代码设置为白色后，head1和head2所在的行都会变成白色
```java
@Override
    public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, List<CellData> list, Cell cell, Head head, Integer integer, Boolean aBoolean) {
        if(cell.getRowIndex() == 0){
            CellStyle cellStyle = cell.getCellStyle();
            cellStyle.setFillForegroundColor(IndexedColors.WHITE.getIndex());
            cell.setCellStyle(cellStyle);
        }
    }
```

**Comment by zhuangjiaju** [comment]
自定义样式  可以拦截到每一行头

**Comment by yu514950381** [comment]
你好，我有创建自定义拦截器，我在问题中的代码就是自定义的一个handler，里面给第一行进行自定义特殊处理。但是我导出的样式的效果是，两行的头的样式都发生了改变

**Comment by GaryLeessang** [comment]
> 你好，我有创建自定义拦截器，我在问题中的代码就是自定义的一个handler，里面给第一行进行自定义特殊处理。但是我导出的样式的效果是，两行的头的样式都发生了改变

请问这个问题有找到原因和解决思路嘛=。=
