### ISSUE TITLE
使用2.2.1版本 使用OnceAbsoluteMergeStrategy合并单元格失效

### ISSUE THREAD

**Issue by angiely1115** [alibaba/easyexcel#1319]
ExcelWriterBuilder excelWriterBuilder = EasyExcel.write(newFilesPath).withTemplate(resource.getInputStream());
            for (OnceAbsoluteMergeStrategy onceAbsoluteMergeStrategy : onceAbsoluteMergeStrategies) {
                excelWriterBuilder = excelWriterBuilder.registerWriteHandler(onceAbsoluteMergeStrategy);
            }
            ExcelWriter excelWriter = null;
            FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.TRUE).direction(WriteDirectionEnum.HORIZONTAL).build();
            try {
                Map<String,String> stringMap = Maps.newHashMapWithExpectedSize(1);
                stringMap.put("year","{.year}");
                excelWriter = excelWriterBuilder.build();
                WriteSheet writeSheet = EasyExcel.writerSheet().build();
                excelWriter.fill(exportHeadDataVos, fillConfig, writeSheet);
                excelWriter.fill(stringMap, writeSheet);

            }finally {
                if (excelWriter != null) {
                    excelWriter.finish();
                }
            }

**Comment by zhuangjiaju** [comment]
这个是个bug 建议使用 `2.2.3`

**Comment by zhong1990** [comment]
forceNewRow设置为TRUE是  新生成的row  OnceAbsoluteMergeStrategy失效   2.2.3和2.2.7都遇到同样的问题
