### ISSUE TITLE
复杂表头未按预期跨行显示

### ISSUE THREAD

**Issue by sweeter-box** [alibaba/easyexcel#1322]
**触发场景描述**
- 复杂表头导出，我无意的设置了ExcelProperty的index从1开始
例如：    
    @ColumnWidth(25)
    @ExcelProperty(value = {"订单统计", "年月"}, index = 1)
    private String yearMonth;

    @ColumnWidth(25)
    @ExcelProperty(value = {"订单统计", "订单数量"}, index = 2)
    private Integer orderNum;
![错误格式](https://user-images.githubusercontent.com/30773069/82231630-fd5e9b00-995f-11ea-9e85-6545e0d6c7bd.png)
![正确格式](https://user-images.githubusercontent.com/30773069/82231680-11a29800-9960-11ea-8f26-c1638244047a.png)

导致复杂表头没有跨列显示，只显示在最后一列，将index改为0开始后恢复正常

**提示的异常或者没有达到的效果**
-  即便不从excel的第一列开始填充数据也应该保持复杂表头跨行显示

**Comment by sweeter-box** [comment]
版本使用的最新版2.2.3

**Comment by zhuangjiaju** [comment]
非常感谢您的意见，已经在最新版修复。
