### ISSUE TITLE
xls公式的值获取在同一行前序所有单元格无其他内容时无法获取

### ISSUE THREAD

**Issue by laiyijie** [alibaba/easyexcel#1324]
xls公式的值获取在同一行前序所有单元格无其他内容时无法获取

xls数据

![image](https://user-images.githubusercontent.com/7499201/82303662-d64eaa80-99ed-11ea-831e-c4499b81052f.png)
这种情况下无法获取红框标志的公式的值

{0=null, 1=null, 2=null, 3=null, 4=null, 5=3}
{0=null, 1=null, 2=null, 3=2}
{0=null, 1=21, 2=1, 3=null, 4=3}
{0=null, 1=null, 2=null, 3=null, 4=null, 5=4}
{0=null, 1=12, 2=2}
{0=null, 1=12}

如果前序增加任何一个值
![image](https://user-images.githubusercontent.com/7499201/82303772-fda57780-99ed-11ea-8c02-8e6ebd2efeb0.png)
此时读取正常

{0=null, 1=12, 2=1}
{0=null, 1=null, 2=null, 3=null, 4=null, 5=3}
{0=null, 1=null, 2=null, 3=2}
{0=null, 1=21, 2=1, 3=null, 4=3}
{0=null, 1=null, 2=null, 3=null, 4=null, 5=4}
{0=null, 1=12, 2=2}
{0=null, 1=12}
{0=str, 1=57, 2=4, 3=2, 4=3, 5=7}

**Comment by zhuangjiaju** [comment]
非常感谢您的意见，已经在最新版修复。

**Comment by songtangwei** [comment]
能不能写一个配置项 我们需求有时候不想读公式有公式的列
