### ISSUE TITLE
Listener中怎样将读取的一行数据后重新组装成一个List<Object>

### ISSUE THREAD

**Issue by tanjoc** [alibaba/easyexcel#1326]
![20200519192204](https://user-images.githubusercontent.com/19592817/82320539-0c982400-9a06-11ea-9baa-04af0f3fc016.png)
加入有上面一种表格，我如果要将一行数据拆分成一个[t1, t2]这种List，可以怎样去实现？

**Comment by tanjoc** [comment]
如果我需要定义接收类，该怎样去定义以及如何设置index呢

**Comment by zhuangjiaju** [comment]
目前不支持 一行只能对应一个object 需要自己去拆分。
