### ISSUE TITLE
Converter可以支持一些条件处理

### ISSUE THREAD

**Issue by tanjoc** [alibaba/easyexcel#1330]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
建议自定的Converter可以使用有参构造，传入一些条件限制，例如我需要将excel表单中的端口进行转换的时候，就可以传入一个最大最小值
	public class PortConverter implements Converter<Integer> {

		@Override
		public Class supportJavaTypeKey() {
			return Integer.class;
		}

		@Override
		public CellDataTypeEnum supportExcelTypeKey() {
			return CellDataTypeEnum.STRING;
		}

		@Override
		public Integer convertToJavaData(CellData cellData, ExcelContentProperty excelContentProperty, GlobalConfiguration globalConfiguration) throws Exception {
	//        System.out.println(cellData);
			int port = cellData.getNumberValue().intValue();
			if (port < 1 || port > 65535) {
				throw new ExcelConvertException("The port " + port + " to be converted out of range [1, 65535].");
			}
			return port;
		}

		@Override
		public CellData convertToExcelData(Integer integer, ExcelContentProperty excelContentProperty, GlobalConfiguration globalConfiguration) throws Exception {
			return null;
		}
	}

**Comment by zhuangjiaju** [comment]
可以自己传一个转换器。但是这样就没法指定特定字段了。我考虑下，是否可以执行index来指定字段。

**Comment by thon-ju** [comment]
自定义转换器，然后通过@NumberFormat传参，在转换器里面通过contentProperty.getNumberFormatProperty().getFormat()获取参数
```
/** 用户性别 */
    @ExcelProperty(value = "用户性别", converter = CustomDictConverter.class)
    @NumberFormat("sys_user_sex")
    private String sex;
```
