### ISSUE TITLE
特殊字符解析问题

### ISSUE THREAD

**Issue by paulzhu8597** [alibaba/easyexcel#1335]
2002851571 | 川普$stupid～？/》>\) | K2002851571681 | 399 | 10.00
-- | -- | -- | -- | --
解析后
"spuName":"川普$stupid～？/》"  "skuNo":">"  "costPrice":"\\)"  "salePrice":"399"
是特殊字符被转义了？

**Comment by zhuangjiaju** [comment]
测试没问题。请尝试使用最新版本。
