### ISSUE TITLE
读取文件时出现Zip bomb detected

### ISSUE THREAD

**Issue by jiangdailun** [alibaba/easyexcel#1338]
com.alibaba.excel.exception.ExcelAnalysisException: java.io.IOException: Zip bomb detected! The file would exceed the max. ratio of compressed file size to the size of the expanded data.
This may indicate that the file is used to inflate memory usage and thus could pose a security risk.
You can adjust this limit via ZipSecureFile.setMinInflateRatio() if you need to work with files which exceed this limit.
Uncompressed size: 820250, Raw/compressed size: 8192, ratio: 0.009987
Limits: MIN_INFLATE_RATIO: 0.010000, Entry: xl/styles.xml

**Comment by zhuangjiaju** [comment]
你的excel 不太正常 。可以在读取前设置
```java
ZipSecureFile.setMinInflateRatio(-1.0d);
```
解决问题。
但是这样就不能防止`zip bomb`了。
建议excel重新保存后导入。
