### ISSUE TITLE
easyexcel-2.1.6无法兼容以前的poi代码

### ISSUE THREAD

**Issue by small-code-cat** [alibaba/easyexcel#1343]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**
easyexcel-2.1.6中的poi是3.17，而我之前程序中使用的是poi3.8，所以使用easyexcel后在使用以前的导出功能会报错
java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFSheet.setDefaultColumnWidth(S)V
应该怎么做，既可以使用easyexcel，又可以兼容以前的导出功能呢

**Comment by zhuangjiaju** [comment]
建议升级到3.17
