### ISSUE TITLE
cellIndex不会自增

### ISSUE THREAD

**Issue by iWuYc** [alibaba/easyexcel#1346]
https://github.com/alibaba/easyexcel/blob/665f1e2f0e72a17da4b531326cfad4236149da05/src/main/java/com/alibaba/excel/write/executor/ExcelWriteAddExecutor.java#L157

在该行，如果在WriteSheet配置了includeIndex，并且cellIndex=0的时候，是不包含在内的时候，if (uselessData)为0，则，后面的数据都不会填充到指定的单元格中。
```java
 final ExcelWriterSheetBuilder sheetBuilder = new ExcelWriterSheetBuilder();
        sheetBuilder.includeColumnIndexes(this.includeIndex()).needHead(true).head(this.head);
        return sheetBuilder.build();
```
```java
// 该用例中所有的判断都为false
boolean uselessData = !beanMap.containsKey(filedName) || beanMapHandledSet.contains(filedName)
                || ignoreMap.containsKey(filedName) || writeContext.currentWriteHolder().ignore(filedName, cellIndex);
```
相同的，因为cellIndex的自增是在if (uselessData)之后，则表示，如果该段代码出现过一次uselessData=false，则后续的数据都不会被填充。

**Comment by zhuangjiaju** [comment]
非常感谢您的意见，已经在最新版修复。
