### ISSUE TITLE
excel格式读取数值的问题

### ISSUE THREAD

**Issue by Jon-Gaara** [alibaba/easyexcel#1349]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
你好，使用easyexcel读取excel数值类型时，如果实际值是500.59，但是通过点击excel减少小数点操作，使得excel中显示是501，用2.1.6版本读取出来的是500.59，但是用2.2.3版本读取出来的却是501，我想问下，不应该读取的是它的真实值500.59么？
**建议描述**

**Comment by zhuangjiaju** [comment]
请提供excel，`2.2.3`应该读起来和看到的一样。

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？未解决的话重新打开问题。
