### ISSUE TITLE
建议将文档写操作完毕之后提供hook 接口，以方便自定义单元格合并操作

### ISSUE THREAD

**Issue by KOkkmiao** [alibaba/easyexcel#1353]

**Comment by KOkkmiao** [comment]
//ExcelBuilderImpl:例如在实现类写操作结束之后
` public void addContent(List data, WriteSheet writeSheet, WriteTable writeTable) {
          context.currentSheet(writeSheet);
            context.currentTable(writeTable);
            doAddContent(data);
            /** 这里添加hook接口如CellWriteHandler 接口*/
}`

**Comment by KOkkmiao** [comment]
建议能加这个功能吗？大佬 @wenyi-zhou @alibaba-oss

**Comment by zhuangjiaju** [comment]
详细需求是什么？

**Comment by KOkkmiao** [comment]
![](https://ftp.bmp.ovh/imgs/2020/06/e55e98ae30c15388.jpg)

像这样的。
具体实现就是在ExcelBuilderImpl类中addConent 书写完所有内容之后给用户一个自己重新定义表合并的方式 @zhuangjiaju

**Comment by zhuangjiaju** [comment]
自定义拦截器 `AbstractSheetWriteHandler` 即可
