### ISSUE TITLE
请教一下：怎么获取每个单元格的数据类型？第一行表头的数据类型可以获取到，其他行怎么获取？

### ISSUE THREAD

**Issue by denlaku** [alibaba/easyexcel#1354]

**Comment by junlinmeng** [comment]
`  for (int rowNum = 1; rowNum < rowCount; rowNum++) {
            Row row1 = sheet.getRow(rowNum);
            if (row1 != null){
                int countNum = row1.getPhysicalNumberOfCells();
                for(int column = 0;column < countNum;column++){
                    int cellType = row1.getCell(column).getCellType();
                    Cell cell = row1.getCell(column);
                    switch (cellType){
                        case HSSFCell.CELL_TYPE_STRING:
                            System.out.print("[字符串]");
                            value = cell.getStringCellValue();
                            break;
                        case HSSFCell.CELL_TYPE_BOOLEAN:
                            System.out.print("[布尔值]");
                            value = String.valueOf(cell.getBooleanCellValue());
                            break;
                        case HSSFCell.CELL_TYPE_NUMERIC:
                            System.out.print("[数字类型]");
                            if(HSSFDateUtil.isCellDateFormatted(cell)){
                                System.out.println("[转换为日期输出]");
                                Date date = cell.getDateCellValue();
                                value = new DateTime(date).toString("yyyy-MM-dd");
                            }else{
                                System.out.print("[转换为数字输出]");
                                value = String.valueOf(cell.getNumericCellValue());
                            }
                            break;
                        case HSSFCell.CELL_TYPE_ERROR:
                            System.out.println("错误");
                            break;
                    }
                    System.out.println(value);
                }
            }
        }`

**Comment by zhuangjiaju** [comment]
监听器的`invokehead`
