### ISSUE TITLE
希望增加一个计算模板变量值的接口

### ISSUE THREAD

**Issue by 694551594** [alibaba/easyexcel#1356]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**

希望增加一个计算模板变量值的接口，在使用的过程中，模板的变量可能是el表达式，或者是其他表达式，可以增加一个接口。默认实现为从map里面直接取值，也可以自定义表达式引擎取值。

**Comment by zhuangjiaju** [comment]
后续考虑，暂时不考虑表达式。
