### ISSUE TITLE
springboot使用了easyExcel的模版填充功能，打成jar包报文件找不到

### ISSUE THREAD

**Issue by okwen5566** [alibaba/easyexcel#1357]
springboot使用了easyExcel的模版填充功能，在本地可以正常使用；
打成jar包后，报模版文件找不到

**Comment by kilowang** [comment]
模版是放在哪个位置的？还要看你读取模版的方式，这个可能和你查找文件的方式有关。
在IDE中能正常启动读取模版填充，但是打成jar包找不到文件，是因为jar内的文件读取方式不太一样。
最好还是贴出来你的代码以及异常信息

**Comment by zhuangjiaju** [comment]
找不到文件需要自己网上查询下。
