### ISSUE TITLE
读excel下的子目录点击查看excel示例，都会回到“最简单的读”的示例

### ISSUE THREAD

**Issue by dyx0226** [alibaba/easyexcel#1363]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
嗯 就是看这个就行了 同一个excel
