### ISSUE TITLE
excelWriter.finish()之后没有反应，程序突然中断

### ISSUE THREAD

**Issue by HTT1995** [alibaba/easyexcel#1364]
com.alibaba.excel.exception.ExcelGenerateException: IO error

**Comment by HTT1995** [comment]
版本：1.1.2-beta5
poi版本：4.1.0

**Comment by HTT1995** [comment]
debug程序到excelWriter.finish()，既没有报异常也没有继续执行

**Comment by zhuangjiaju** [comment]
这个需要打印下 gc日志。是否内存超了。
