### ISSUE TITLE
headRowNumber

### ISSUE THREAD

**Issue by haoyousb** [alibaba/easyexcel#1367]
2.1.6版本
假如配置了headRowNumber(2)
在doReadSync的时候会忽略前两行不解析

更新版本后headRowNumber(2)不起作用了

**Comment by zhuangjiaju** [comment]
实际测试没问题，能否提供下excel.

**Comment by haoyousb** [comment]
[Test.xlsx](https://github.com/alibaba/easyexcel/files/4750981/Test.xlsx)
您试下这个excel，用这种方式去解析


        List<Object> objects = EasyExcel.read(file).headRowNumber(2).sheet().doReadSync();
        System.out.println(objects.size());


解析出来的list里面会带着2个空行  2.1.6版本的不回

**Comment by zhuangjiaju** [comment]
还是没理解啥问题。我测试了显示43行。然后`{0:"1",1:"2",2:"3",3:"3",4:"5",5:"0"}`开始。最上面2行忽略了。

**Comment by 993640191** [comment]
2.13版本也不起作用
EasyExcel.read(excelInputStream, ImportNewsDto.class, listener).headRowNumber(2).sheet(1).doReadSync();
