### ISSUE TITLE
提个建议~，有模型的excel读取 model类型能不能不使用继承?

### ISSUE THREAD

**Issue by cc-cfg** [alibaba/easyexcel#137]
先有一业务需求，读取excel数据插入到数据库，数据库model应该继承了基类，所以  假如使用easyexcel去读取excel，那需要另外新建model去继承，然后读取记过 再转为model去执行插入数据库

可以参考  https://github.com/Crab2died/Excel4J    他这个使用方法貌似更简洁~~

**Comment by jipengfei-jpf** [comment]
考虑会在下个版本去掉，感谢
