### ISSUE TITLE
下拉菜单

### ISSUE THREAD

**Issue by chenye-2020** [alibaba/easyexcel#1376]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**
版本支持下拉菜单么？

**Comment by zhuangjiaju** [comment]
建议参照文档。
