### ISSUE TITLE
读取excel，校验数据有效性

### ISSUE THREAD

**Issue by Maijh97** [alibaba/easyexcel#138]
请问，如果我需要进行在读取的时候，动态做数据校验，现在处理方式：每读取一行，就进行做大量的校验动作，发现数量大的时候，会导致解析excel的时候就很慢了。麻烦有什么更好的提议吗？数据校验最要是有，单元格是否为空，单元格的数据是否和系统的匹配！

**Comment by jipengfei-jpf** [comment]
你可以异步去做参数校验

**Comment by JanYunkai** [comment]
请问有考虑集成jsr303，380吗，我想在读取出bean的时候就做参数验证。
