### ISSUE TITLE
导出文件中文字部分显示不是宋体，如图

### ISSUE THREAD

**Issue by 570384220** [alibaba/easyexcel#1386]
如下图中的 直销 的直 显示不正常，再windows中显示正常，在mac中就会出现这个问题，是怎么回事

![image](https://user-images.githubusercontent.com/30338882/84029536-26090c00-a9c5-11ea-8a56-941a0b5b0634.png)

**Comment by zhuangjiaju** [comment]
是否mac中不存在宋体？

**Comment by zhuangjiaju** [comment]
该问题是否已经解决？未解决请重新打开问题。

**Comment by 570384220** [comment]
指定一下字体就好了
