### ISSUE TITLE
2.2.3 版本中删除了AbstractMergeStrategy

### ISSUE THREAD

**Issue by 908216809** [alibaba/easyexcel#1387]
最新版本中删除了AbstractMergeStrategy，是有其他方式更好的支持动态单元格合并吗。
导出时需要根据数据来确认需要合并单元格的行数。

**Comment by zhuangjiaju** [comment]
`2.2.4`已经加回去了

**Comment by 908216809** [comment]
多谢，多谢&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jiaju Zhuang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月9日(星期二) 晚上10:44
收件人:&nbsp;"alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送:&nbsp;"❤ 执子之手"<908216809@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 2.2.3 版本中删除了AbstractMergeStrategy (#1387)





 
2.2.4已经加回去了
