### ISSUE TITLE
时间格式2018-10-11  15:23:07的字段读取出起来 结果是：43384.6410532407

### ISSUE THREAD

**Issue by ZeusMartin** [alibaba/easyexcel#139]

**Comment by jipengfei-jpf** [comment]
2中方式1，写javaModel这个字段类型设置成Date，这样会帮你转成Date类型。如果每行解析结果是List<String>你需要用HSSFDateUtil.getJavaDate(d, false);把double变成date。因为poi在底层存储日期是自己的double格式。

**Comment by ZeusMartin** [comment]
感谢大神

**Comment by Will-M-Lee** [comment]
> 两中解决方式，方式一：写javaModel这个字段类型设置成Date，这样会帮你转成Date类型。方式二：如果每行解析结果是List你需要用HSSFDateUtil.getJavaDate(d, false);把double变成date。因为poi在底层存储日期是自己的double格式。

方式一:自定义excel,无固定格式
方式二:不知道此行是不是日期格式,所以无法使用HSSFDateUtil.getJavaDate(d, false)来强转所有数字
此种情境下怎么办

**Comment by 1069355234** [comment]
> > 两中解决方式，方式一：写javaModel这个字段类型设置成Date，这样会帮你转成Date类型。方式二：如果每行解析结果是List你需要用HSSFDateUtil.getJavaDate(d, false);把double变成date。因为poi在底层存储日期是自己的double格式。
> 
> 方式一:自定义excel,无固定格式
> 方式二:不知道此行是不是日期格式,所以无法使用HSSFDateUtil.getJavaDate(d, false)来强转所有数字
> 此种情境下怎么办

遇到同样的问题，有啥解决办法没?

**Comment by lhq-github** [comment]
> > > 两中解决方式，方式一：写javaModel这个字段类型设置成Date，这样会帮你转成Date类型。方式二：如果每行解析结果是List你需要用HSSFDateUtil.getJavaDate(d, false);把double变成date。因为poi在底层存储日期是自己的double格式。
> > 
> > 
> > 方式一:自定义excel,无固定格式
> > 方式二:不知道此行是不是日期格式,所以无法使用HSSFDateUtil.getJavaDate(d, false)来强转所有数字
> > 此种情境下怎么办
> 
> 遇到同样的问题，有啥解决办法没?

我也遇到这种问题，有啥解决办法没？
