### ISSUE TITLE
com.alibaba.excel.exception.ExcelAnalysisException: java.lang.NoClassDefFoundError: org/objectweb/asm/Type

### ISSUE THREAD

**Issue by LzbNewBie** [alibaba/easyexcel#1390]
请问easyexcel使用2.2.3 version，poi使用3.17 version出现类找不到的问题怎么解决
com.alibaba.excel.exception.ExcelAnalysisException: java.lang.NoClassDefFoundError: org/objectweb/asm/Type

**Comment by zhuangjiaju** [comment]
`cglib` 3.1+

**Comment by iluoxuan** [comment]
和jetty中的asm冲突，把cglib降低到2.x版本 就可以

**Comment by LzbNewBie** [comment]
通过引入3.3.0的cglib包解决了这个问题，maven配置如下：
<dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>2.2.3</version>
                <exclusions>
                    <exclusion>
                            <groupId>cglib</groupId>
                            <artifactId>cglib</artifactId>
                    </exclusion>
                </exclusions>
</dependency>
<dependency>
    <groupId>cglib</groupId>
    <artifactId>cglib</artifactId>
    <version>3.3.0</version>
</dependency>

**Comment by iluoxuan** [comment]
重新尝试了 为了解决asm冲突建议 引用 cglib-nodep jar；不会取引用外部asm ；

**Comment by fisherman-0510** [comment]
大佬 可以写出具体的 pom 配置文件嘛, 我现在也遇到这个情况 谢谢啦

**Comment by LzbNewBie** [comment]
> 大佬 可以写出具体的 pom 配置文件嘛, 我现在也遇到这个情况 谢谢啦

               <dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>easyexcel</artifactId>
			<version>2.2.6</version>
			<exclusions>
				<exclusion>
					<groupId>cglib</groupId>
					<artifactId>cglib</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>cglib</groupId>
			<artifactId>cglib</artifactId>
			<version>3.3.0</version>
		</dependency>
