### ISSUE TITLE
在windows 环境下导出没问题 linux 下导出回报错的问题

### ISSUE THREAD

**Issue by YangSii** [alibaba/easyexcel#1392]
我在本地windows 下导出是没有问题的，但是运行到生产环境就出现了问题。这个问题以前是没有遇到的，在我的系统里发布了新的版本就在 linux 环境下出现了问题，但该部分的代码没有做过修改

```java
    EasyExcel.write(savePath).head(heads).sheet("模板").doWrite(dataList);
```
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.alibaba.excel.write.builder.ExcelWriterBuilder.head(Ljava/util/List;)Lcom/alibaba/excel/metadata/AbstractParameterBuilder;

**Comment by zhuangjiaju** [comment]
重新打包，这个类肯定在的。
