### ISSUE TITLE
合并单元格后，表格的求和值没有变化

### ISSUE THREAD

**Issue by yuzhenhua86** [alibaba/easyexcel#1395]
wps for mac 1.0.1 easyexcel 2.2.4
![image](https://user-images.githubusercontent.com/47058349/84343426-bc624b00-abda-11ea-956a-a9abe44d8b8c.png)

**Comment by zhuangjiaju** [comment]
请详细描述您的问题。

**Comment by zhuangjiaju** [comment]
该问题是否已经解决？如果未解决 请重新打开问题。
