### ISSUE TITLE
使用@RestController注解，导致访问工具可以下载excel，但是网页无法下载

### ISSUE THREAD

**Issue by BSTK-collab** [alibaba/easyexcel#1397]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
这个需要自己实现，`EasyExcel`核心是给你一个流，剩下的自己处理。
