### ISSUE TITLE
同步方法读取excel时，使用String接收小数，在linux服务器上小数点会被解析成逗号，windows电脑上正常

### ISSUE THREAD

**Issue by xxbeam** [alibaba/easyexcel#1398]
例如：1.15在windows电脑上正常解析，但是在服务器上解析成1,15
由于该字段不一定是数字，所以无法使用NumberFormat注解，请问有什么解决办法么

**Comment by zhuangjiaju** [comment]
请提供版本号，或者升级版本试试。

**Comment by xxbeam** [comment]
> 请提供版本号，或者升级版本试试。

使用的2.2.4，升级到最新的2.2.5还是存在这个问题

**Comment by zhuangjiaju** [comment]
提供下excel。

**Comment by xxbeam** [comment]
> 提供下excel。

[测试.xlsx](https://github.com/alibaba/easyexcel/files/4822762/default.xlsx)

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
