### ISSUE TITLE
easyexcel设计蛮优秀的，就是日志太少太少

### ISSUE THREAD

**Issue by cqrickychen** [alibaba/easyexcel#14]
日志原生日志太少、
Debug日志没有，INFO没有，ERROR没有；
请问是否考虑 增加各类型日志输出

**Comment by jipengfei-jpf** [comment]
感谢建议预计会在月底发布新版本，会增加日志适配

**Comment by jipengfei-jpf** [comment]
最新版1.1.2-beat1异常处理需要调用者catch
