### ISSUE TITLE
首页“web下载示例写法”细节似乎有误

### ISSUE THREAD

**Issue by Seayon** [alibaba/easyexcel#140]
首页“web下载实例写法” 示例代码中，似乎应添加
writer.finish();
才能正确的完成处理。

**Comment by jipengfei-jpf** [comment]
额，谢谢是的。粘帖漏掉了

**Comment by miaoo92** [comment]
web下载实例写法，按照示例代码，没有弹出下载框，而是返回了一堆乱码。请两位指教。

**Comment by wangxuesong123** [comment]
<img width="895" alt="1" src="https://user-images.githubusercontent.com/25112276/50969399-4ce5b900-1519-11e9-94a8-73e3d915c78f.png">
