### ISSUE TITLE
Exception控制流程

### ISSUE THREAD

**Issue by iWuYc** [alibaba/easyexcel#1402]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
查看各位大大的代码发现，com.alibaba.excel.event.AnalysisEventListener#hasNext使用的是异常来控制流程。阿里规范中不是不建议使用异常来做流程控制吗？往下读取的控制，应该有更加优雅的方式进行。
SPI支持得太少了，我希望在读取sheet中的某一行（中间，非最后一行）时，跳过当前sheet之后的数据读取，直接读取下一个sheet的数据。

**Comment by zhuangjiaju** [comment]
单独异常抛出问题不大。目前仅支持 跳过所有。后续会考虑跳过单个。
