### ISSUE TITLE
不使用定义表头，如何写入图片数据？

### ISSUE THREAD

**Issue by HTT1995** [alibaba/easyexcel#1410]
**现状**
做的是一个组件化的excel写入，所以一直使用如下方法来写入数据
public ExcelWriter write0(List<List<String>> data, Sheet sheet, Table table) {
        this.excelBuilder.addContent(data, sheet, table);
        return this;
    }

**问题**
所以问题是我拿到的图片数据是字节数组类型转成的json字符串（这里不做过多解释为什么要转成json字符串），我直接write0写入会报错数据过长，明显这把图片的json字符串当成string类型写入了，我应该如何操作才能正常写入图片数据？

**痛点**
无法定义类似文档中ImageData的这种表头对象，也就无法使用
EasyExcel.write(fileName, ImageData.class).sheet().doWrite(list);
这种类型方法来写excel。

**Comment by zhuangjiaju** [comment]
这个需要自己提前转好了。自定义或者可以新增自定义转换器。

**Comment by HTT1995** [comment]
你好，想问下如何在使用动态表头情况下使自定义的转换器生效，目前使用下面这种形式来设置表头
            // 创建一个表格             Table table = new Table(1);             // 动态添加 表头 headList --&gt; 所有表头行集合             List<List<String&gt;&gt; headList = new ArrayList<List<String&gt;&gt;();             // 第 n 行 的表头             List<String&gt; headTitle0 = new ArrayList<String&gt;();             List<String&gt; headTitle1 = new ArrayList<String&gt;();             List<String&gt; headTitle2 = new ArrayList<String&gt;();             headTitle0.add("最顶部-1");             headTitle0.add("标题1");             headTitle1.add("最顶部-1");             headTitle1.add("标题2");             headTitle2.add("最顶部-1");             headTitle2.add("标题3");             headList.add(headTitle0);             headList.add(headTitle1);             headList.add(headTitle2);             table.setHead(headList);             excelWriter.write1(list,sheet,table);
而不是使用对象形式
@Data @NoArgsConstructor @AllArgsConstructor public class User { 	@ExcelProperty(value = "姓名", index = 0) 	private String name; 	@ExcelProperty(value = "年龄", index = 1) 	private Integer age;     // 1 男   0 女 	@ExcelProperty(value = "性别", index = 2) 	private Integer sex; 	@ExcelProperty(value = "创建时间", index = 3) 	private LocalDateTime createTime; }
想问下在使用List<List<String&gt;&gt; headList这种动态表头如何使自定义的转换器生效？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jiaju Zhuang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月23日(星期二) 晚上6:52
收件人:&nbsp;"alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送:&nbsp;"胡宏周"<1490643280@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 不使用定义表头，如何写入图片数据？ (#1410)





 
这个需要自己提前转好了。自定义或者可以新增自定义转换器。
