### ISSUE TITLE
关于excelWriter.finish()  多个sheet写入excel报错

### ISSUE THREAD

**Issue by ls0618** [alibaba/easyexcel#1412]
**异常代码**
ServletOutputStream outputStream = null;
		ExcelWriter excelWriter = null;
		try {
			ShiftParameterResp shiftParameterResp = shiftParameterService.queryByPrimaryKey(shiftId);
			String start = LocalDateUtil.date2LocalDate(shiftParameterResp.getStartDate()).format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
			String end = LocalDateUtil.date2LocalDate(shiftParameterResp.getEndDate()).format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
			List<String> dateList = LocalDateUtil.getBetweenDate(start, end);

			outputStream = response.getOutputStream();
			response.setContentType("application/vnd.ms-excel");
			response.setCharacterEncoding("utf-8");
			response.setHeader("Pragma", "No-cache");
			response.setHeader("Cache-Control", "no-cache");
			response.setDateHeader("Expires", 0);
			String fileName = shiftParameterResp.getShift() + "-轮班结果";
			response.setHeader("Content-disposition", "attachment;filename=" + URLEncoder.encode(fileName, "UTF-8") + ".xlsx");
			// 头的策略
			WriteCellStyle headWriteCellStyle = new WriteCellStyle();
			// 背景设置为白
			headWriteCellStyle.setFillForegroundColor(IndexedColors.WHITE.getIndex());
			// 内容的策略
			WriteCellStyle contentWriteCellStyle = new WriteCellStyle();
			HorizontalCellStyleStrategy horizontalCellStyleStrategy =
					new HorizontalCellStyleStrategy(headWriteCellStyle, contentWriteCellStyle);

			excelWriter = EasyExcel.write(outputStream).registerWriteHandler(horizontalCellStyleStrategy).build();
			int sheetNo = 0;

			if (isDriver == 1) {
				List<StatisticsShiftResp> shiftRespList = shiftDetailsService.queryDriverShift(shiftId);
				List<StatisticsShiftExcel> driverList = Lists.newArrayList();
				for (int i = 0; i < shiftRespList.size(); i++) {
					StatisticsShiftResp statisticsShiftResp = shiftRespList.get(i);
					StatisticsShiftExcel statisticsShiftExcel = new StatisticsShiftExcel();
					String groupName = getGroupName(statisticsShiftResp.getShiftFlag());
					statisticsShiftExcel.setGroupName(i + 1 + groupName);
					statisticsShiftExcel.setWorkCarCount(statisticsShiftResp.getWorkCarCount());
					statisticsShiftExcel.setRestDay(statisticsShiftResp.getRestDay());
					statisticsShiftExcel.setDays(statisticsShiftResp.getDays());
					if (!CollectionUtils.isEmpty(statisticsShiftResp.getDrivers())) {
						String nameStr = statisticsShiftResp.getDrivers().stream().map(ShiftChainDriverRelation::getDriverName).collect(Collectors.joining());
						statisticsShiftExcel.setNameStr(nameStr);
					}
					driverList.add(statisticsShiftExcel);
				}
				WriteSheet writeSheet = EasyExcel.writerSheet(sheetNo++, "驾驶员轮班表").head(StatisticsShiftExcel.class).build();
				excelWriter.write(driverList, writeSheet);
			}

			if (isVehicle == 1) {
				List<StatisticsShiftResp> shiftRespList = shiftDetailsService.queryCarShift(shiftId);
				List<StatisticsShiftExcel> vehicleList = Lists.newArrayList();
				for (int i = 0; i < shiftRespList.size(); i++) {
					StatisticsShiftResp statisticsShiftResp = shiftRespList.get(i);
					StatisticsShiftExcel statisticsShiftExcel = new StatisticsShiftExcel();
					String groupName = getGroupName(statisticsShiftResp.getShiftFlag());
					statisticsShiftExcel.setGroupName(i + 1 + groupName);
					statisticsShiftExcel.setWorkCarCount(statisticsShiftResp.getWorkCarCount());
					statisticsShiftExcel.setRestDay(statisticsShiftResp.getRestDay());
					statisticsShiftExcel.setDays(statisticsShiftResp.getDays());
					if (!CollectionUtils.isEmpty(statisticsShiftResp.getVehicles())) {
						String nameStr = statisticsShiftResp.getVehicles().stream().map(ShiftChainCarRelation::getVehicleCode).collect(Collectors.joining());
						statisticsShiftExcel.setNameStr(nameStr);
					}
					vehicleList.add(statisticsShiftExcel);
				}
				WriteSheet writeSheet = EasyExcel.writerSheet(sheetNo++, "车辆轮班表").head(StatisticsShiftExcel.class).build();
				excelWriter.write(vehicleList, writeSheet);
			}

			if (isDriverCalendar == 1) {
				List<ShiftChainDriverRelation> shiftChainDriverRelationList = shiftChainDriverRelationService.queryShiftChainDriverRelation(shiftId);
				Map<Long, String> driverMap = shiftChainDriverRelationList.stream()
						.collect(Collectors.toMap(ShiftChainDriverRelation::getDriverId, ShiftChainDriverRelation::getDriverName, (k1, k2) -> k1));
				List<CalendarShiftExt> driverCalendarList = getDriverCalendarShiftExtList(shiftId);
				List<List<String>> headList = Lists.newArrayList();
				List<List<String>> contentList = Lists.newArrayList();
				List<String> head0 = new ArrayList<>();
				head0.add("月度班组");
				List<String> head1 = new ArrayList<>();
				head1.add("人员");
				headList.add(head0);
				headList.add(head1);
				for (String date : dateList) {
					List<String> head3 = new ArrayList<>();
					head3.add(date);
					headList.add(head3);
				}

				for (int i = 0; i < driverCalendarList.size(); i++) {
					CalendarShiftExt item = driverCalendarList.get(i);
					List<String> rowList = Lists.newArrayListWithCapacity(dateList.size() + 2);
					for (int j = 0; j < dateList.size() + 2; j++) {
						rowList.add(null);
					}
					String groupName = getGroupName(item.getShiftFlag());
					rowList.add(0, i + 1 + groupName);
					rowList.add(1, driverMap.get((long) item.getSerialNumber()));
					if (item.getShiftRespList() != null) {
						for (CalendarShiftResp calendarShiftResp : item.getShiftRespList()) {
							int index = dateList.indexOf(StringUtils.substring(calendarShiftResp.getDay(), 5));
							rowList.add(index + 2, String.valueOf(calendarShiftResp.getCarNumber() == 0 ? "休" : calendarShiftResp.getCarNumber()));
						}
					}
					contentList.add(rowList);
				}
				WriteSheet writeSheet = EasyExcel.writerSheet(sheetNo++, "人员轮班月历表").head(headList).build();
				excelWriter.write(contentList, writeSheet);
			}
			if (isVehicleCalendar == 1) {
				List<ShiftChainCarRelation> shiftChainCarRelationList = shiftChainCarRelationService.queryShiftChainCarRelation(shiftId);
				Map<Long, String> vehicleMap = shiftChainCarRelationList.stream()
						.collect(Collectors.toMap(ShiftChainCarRelation::getCarId, ShiftChainCarRelation::getVehicleCode, (k1, k2) -> k1));
				List<CalendarShiftExt> vehicleCalendarList = getVehicleCalendarShiftExtList(shiftId);
				List<List<String>> headList = Lists.newArrayList();
				List<List<String>> contentList = Lists.newArrayList();
				List<String> head0 = new ArrayList<>();
				head0.add("月度班组");
				List<String> head1 = new ArrayList<>();
				head1.add("车辆");
				headList.add(head0);
				headList.add(head1);
				for (String date : dateList) {
					List<String> head3 = new ArrayList<>();
					head3.add(date);
					headList.add(head3);
				}

				for (int i = 0; i < vehicleCalendarList.size(); i++) {
					CalendarShiftExt item = vehicleCalendarList.get(i);
					List<String> rowList = Lists.newArrayListWithCapacity(dateList.size() + 2);
					for (int j = 0; j < dateList.size() + 2; j++) {
						rowList.add(null);
					}
					String groupName = getGroupName(item.getShiftFlag());
					rowList.add(0, i + 1 + groupName);
					rowList.add(1, vehicleMap.get((long) item.getSerialNumber()));
					if (item.getShiftRespList() != null) {
						for (CalendarShiftResp calendarShiftResp : item.getShiftRespList()) {
							int index = dateList.indexOf(StringUtils.substring(calendarShiftResp.getDay(), 5));
							rowList.add(index + 2, String.valueOf(calendarShiftResp.getCarNumber() == 0 ? "休" : calendarShiftResp.getCarNumber()));
						}
					}
					contentList.add(rowList);
				}
				WriteSheet writeSheet = EasyExcel.writerSheet(sheetNo, "车辆轮班月历表").head(headList).build();
				excelWriter.write(contentList, writeSheet);
			}
		} catch (Exception e) {
			e.printStackTrace();
			// 重置response
			response.reset();
			response.setContentType("application/json");
			response.setCharacterEncoding("utf-8");
			Map<String, String> map = new HashMap<String, String>();
			map.put("status", "failure");
			map.put("message", "下载文件失败" + e.getMessage());
			try {
				response.getWriter().println(JSON.toJSONString(map));
			} catch (IOException ex) {
				ex.printStackTrace();
			}
		} finally {
			try {
				if( excelWriter != null){
					excelWriter.finish();
				}

				if(outputStream != null){
					outputStream.close();
				}
			} catch (IOException e) {
				logger.error("文件导出异常" + e.getMessage());
			}

		}
**异常提示**
nested exception is com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.] with root cause
**建议描述**
下载excel一次写入多个sheet表,excelWriter.finish() 提示报错
部分情况又不会报错

**Comment by zhuangjiaju** [comment]
贴全异常。

**Comment by zhuangjiaju** [comment]
是否已经解决问题？如果未解决，请重新打开。
