### ISSUE TITLE
导出时 集合data为空时可以导出 但是文件已经损坏

### ISSUE THREAD

**Issue by liangbaika** [alibaba/easyexcel#1414]
**触发场景描述**
  导出时 没有查到数据 但还是能够导出 不过导出的文件显示已经损坏
**触发Bug的代码**
```java
   这里写代码
![Uploading image.png…]()

```
**提示的异常或者没有达到的效果**

**Comment by liangbaika** [comment]
List<ScoreRecord> datas = scoreRecordService.list(queryWrapper);
        List<ScoreRecordExport> data = Convert.copyList(datas, ScoreRecordExport.class);
        EasyExcel.write(response.getOutputStream(), ScoreRecordExport.class).sheet(fileName).doWrite(data);


data.size==0 触发

**Comment by zhuangjiaju** [comment]
实测没问题，尝试升级版本
