### ISSUE TITLE
导入Excel，连续两列非文本格式的长数字(科学计数法)，会使读取到的数据相同

### ISSUE THREAD

**Issue by fuukangun** [alibaba/easyexcel#1417]
引用的版本为2.2.4
A、B列的数据分别为
2019023422001107701947295232，490612344951567
但是Excel中A,B列不是文本格式，而是科学计数法。
easyExcel在解析后，对象的a,b属性(String型)会是同一个值。
另外有什么办法能够判断单元格的格式吗？

**Comment by zhuangjiaju** [comment]
用celldata 去接收可以判断。
问题我这里没复现，请提供下代码和excel

**Comment by fuukangun** [comment]
> 用celldata 去接收可以判断。
> 问题我这里没复现，请提供下代码和excel

代码放到https://github.com/fuukangun/demo.git上了，我试了一下还是复现。虽然提这个issue的时候，已经用CellData<String> 读取，通过CellDataTypeEnum判断单元格类型解决我自己的问题了。不过当时2列读到相同结果的现象，还是不清楚问题在哪儿。
