### ISSUE TITLE
如何按页（A4）填充

### ISSUE THREAD

**Issue by joey-lucky** [alibaba/easyexcel#1418]
需求：数据模板是按页的，结构复杂不是简单的列表，如何按页填充？
尝试：循环调用 fill ，并且forceNewRow设置成true，结果只有一页（模板那页），并没有追加到第二页。

**Comment by zhuangjiaju** [comment]
这个建议尝试使用`jxls`,其他开源框架。

**Comment by joey-lucky** [comment]
> 这个建议尝试使用`jxls`,其他开源框架。

好的，不过还是期望贵司能做这方面的兼容。
