### ISSUE TITLE
web导出excel时如何实现以数据流输出，从而实现“另存为”效果？

### ISSUE THREAD

**Issue by BlueStar0821** [alibaba/easyexcel#142]
web导出excel时如何实现以数据流输出，从而实现“另存为”效果？

**Comment by jipengfei-jpf** [comment]
这个是文件下载，可以google

**Comment by yangnaihua** [comment]
@GetMapping(value = "/{ids}/preStockIn/excel/allTransferCenter/{inBoundDate}")
    public ResponseEntity<byte[]> generatePreStockInRecordForAllTransferCenter(
        @PathVariable("ids") @NotEmpty ValidList<String> ids,
        @PathVariable("inBoundDate") @NotEmpty String inBoundDate) throws IOException {
        byte[] excel = preStockInService.generatePreStockInRecordForAllTransferCenter(ids, inBoundDate);
        return ControllerUtils.getExcelResponse(excel);
    }
-------------------------------
public final class ControllerUtils {



    public static ResponseEntity<byte[]> getExcelResponse(byte[] excel){
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-disposition", "attachment;filename="+ (LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmm")))+ ".xls");
        headers.add("Content-type", "application/x-xls; charset=UTF-8");
        headers.setContentLength(excel.length);
        return new ResponseEntity<>(excel, headers, HttpStatus.OK);
    }
}
