### ISSUE TITLE
如何以追加的方式写Excel

### ISSUE THREAD

**Issue by cmzdandan** [alibaba/easyexcel#1421]
目前提供的web示例，是把一个 数据集丢给doWrite() 方法。
如果我的数据量非常大，那么我期望的是分批写入到Excel里面，请问，该怎么做呢？
(查看了相关示例，没有找到类似的场景解决方案)

**Comment by cmzdandan** [comment]
终于查到了一篇参考博客：https://blog.csdn.net/AllenJoe666/article/details/100697786

**Comment by zhuangjiaju** [comment]
集合 多次写入即可。

**Comment by Sdky** [comment]
> 

请问怎么多次写入？

**Comment by Sdky** [comment]
> 集合 多次写入即可。

请问怎么多次写入？

**Comment by Sdky** [comment]
> 集合 多次写入即可。

请问多次写入时怎么设置每次写入时的合并策略？
