### ISSUE TITLE
写入excel，动态生成多行头时，头数据嵌套list顺序建议

### ISSUE THREAD

**Issue by uenglish** [alibaba/easyexcel#1423]
**建议描述**
问题：写入Excel，动态生成多行头时，头的数据是List<List<String>>,外层list现在是列数据，里层list是行数据，与读取时监听器中的头信息不一致

建议：改为外层list为每一行数据也就是y轴，里层为一行中的每一列数据也就是x轴

**Comment by zhuangjiaju** [comment]
这个 后续考虑是否修改。用户在升级版本后，在没有报错的情况下结果和老版本出现不一致会非常麻烦。
