### ISSUE TITLE
使用EasyExcel.read(InputStream inputStream, Class head, ReadListener readListener);方法时出现异常

### ISSUE THREAD

**Issue by sunyi-server** [alibaba/easyexcel#1425]
**触发场景描述**
在使用EasyExcel.read(InputStream inputStream, Class head, ReadListener readListener);时从OSS上下载excel大小超过1MB进行流读取时出现异常如下：
![image](https://user-images.githubusercontent.com/29943343/85409569-8fc61000-b598-11ea-93d0-bfd20551583e.png)
很明显可以看出来是因为未能获取到excelType这个时候我给ExcelReaderSheetBuilder设置excelType时又出现其他异常如下：
![image](https://user-images.githubusercontent.com/29943343/85409930-095dfe00-b599-11ea-8fa3-0ed9a372869b.png)

**触发Bug的代码**
```
未设置excelType代码
`            
EasyExcel.read(ossObject.getObjectContent(), GiftCodeBO.class,
                    new ExcelGiftCodeListener(giftImportMessage.getGiftId(), btGiftCodeService, batch, password,
                            redisTemplate, msgId)).sheet().doRead();`
设置excelType代码
`            EasyExcel.read(ossObject.getObjectContent(), GiftCodeBO.class,
                    new ExcelGiftCodeListener(giftImportMessage.getGiftId(), btGiftCodeService, batch, password,
                            redisTemplate, msgId)).excelType(giftImportMessage.getFileName().contains(ExcelTypeEnum.XLSX.getValue()) ? ExcelTypeEnum.XLSX
                            : ExcelTypeEnum.XLS).sheet().doRead();`
```
**提示的异常或者没有达到的效果**
未能从OSS上下载超过大小为1MB的excel中读取数据。
希望有大佬能够回复，万分感谢

**Comment by sunyi-server** [comment]
文件格式为xlsx

**Comment by JiayuanChan** [comment]
请问这个问题解决了吗？

**Comment by sunyi-server** [comment]
临时方案：将xlsx文件替换成xls文件类型

**Comment by zhuangjiaju** [comment]
贴全异常。大概率你读取的文件 不完整。

**Comment by Mrhao1024** [comment]
刚刚解决 可能是你的inputstream流重复利用了
解决方法：每次使用inputstream流都要重新获取新的
