### ISSUE TITLE
如果文档是个不规则的，那我该怎么去操作呢？

### ISSUE THREAD

**Issue by prayjourney** [alibaba/easyexcel#1428]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
如果文档是个不规则的，那我该怎么去操作呢？还是创建一个对应的POJO？这也太麻烦了吧

**Comment by zhuangjiaju** [comment]
读还是写？建议先看demo
