### ISSUE TITLE
List<List<String>> 类型的数据导出结果为什么是空的？

### ISSUE THREAD

**Issue by BlueStar0821** [alibaba/easyexcel#143]
try {
			Short intervalType = Short.valueOf(type);
			String typeDesc = transformType(intervalType);
			String fileName = exchangeLabel + "_bch_analysis_" + "_" + typeDesc; 
			if(StringUtils.isNotBlank(startTime)){
				//startDate = DateUtils.parseDate(startTime);
				fileName += "_from" + startTime;
				startDate = org.apache.commons.lang3.time.DateUtils.parseDate(startTime, pattern);
			}
			
			List<List<String>> contentList = binanceKlineService.findBCHAnalysisData(startDate);
			
			out = response.getOutputStream();
			ExcelWriter writer = new ExcelWriter(out, ExcelTypeEnum.XLSX, false);
			
			/*String sheetName = "sheet1";
			//Sheet sheet1 = new Sheet(1, 0);
			ExcelUtil.writeExcel(response, list, fileName, sheetName, new BinanceKline());*/
			Sheet sheet1 = new Sheet(1, 0);
			
			sheet1.setSheetName("sheet1");
			sheet1.setHead(Global.bchAnalysisHeadList);
			
			Table table1 = new Table(1);
			table1.setHead(Global.bchAnalysisHeadList);
			
			writer.write0(contentList, sheet1);
			
			response.setContentType("multipart/form-data");
			//response.setContentType("APPLICATION/OCTET-STREAM");
			response.setCharacterEncoding("utf-8");
			response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx");
			
			out.flush();
			writer.finish();
			
		} catch (Exception e) {
			logger.error(e.getMessage(),e);
			
		} finally {
			if (out != null) {
				try {
					
					out.close();
					
				} catch (IOException e) {
					logger.error(e.getMessage(),e);
				}
			}
		}

**Comment by jipengfei-jpf** [comment]
我看到你的代码只有写没有读操作
