### ISSUE TITLE
自定义表头，自定义转换器的ExcelContentProperty参数为null

### ISSUE THREAD

**Issue by HTT1995** [alibaba/easyexcel#1435]
问题：目前使用自定义表头，自定义了一个转换器，但转换器的第二个参数是null
excelWriter = EasyExcel.write("test").head(headList).registerConverter(new ImageConverter()).build();

public CellData convertToExcelData(String value, ExcelContentProperty contentProperty, GlobalConfiguration globalConfiguration)
中的 ExcelContentProperty contentProperty字段为null

**Comment by zhuangjiaju** [comment]
该参数 本来就可以为null
