### ISSUE TITLE
java.lang.IllegalArgumentException: The workbook already contains a sheet named

### ISSUE THREAD

**Issue by VSunKnightV** [alibaba/easyexcel#1436]
本地导出没有问题 线上环境出现java.lang.IllegalArgumentException: The workbook already contains a sheet named '新人礼836.4861964102627'  这是什么情况

**Comment by 764763903a** [comment]
该异常由于自己的环境变量缺少swing需要的字体配置。
1. 该异常由于自己的环境变量缺少swing需要的字体配置，检查自己应用是否有配置-Djava.awt.headless=true，如果没有请加上该系统参数
2. 如果仍旧不行，看下服务器是否安装了字体，jdk8字体需要自己安装请安装字体：dejavu-sans-fonts 和 fontconfig 在dockerfile中增加字体安装命令：RUN yum install dejavu-sans-fonts fontconfig -y

**Comment by lankk1** [comment]
我今天也遇到类似的问题，debug了一下，发现是apache poi在校验sheet名是否已存在时对过长的sheet名称进行截取，允许最大长度是31，用截取后的字符串和已存在的sheet进行名称比对。
    查看org.apache.poi.xssf.usermodel.XSSFWorkbook#containsSheet
    name = name.substring(0, MAX_SENSITIVE_SHEET_NAME_LEN);

希望对你有所帮助。

**Comment by caojinlin** [comment]
使用xls，不用xlsx格式，可以解决

**Comment by yayi2456** [comment]
我的话遇到的确实是@764763903a 描述的情况，附上官方给的解决方法，避免后来的小白在这个坑花更多时间：https://www.yuque.com/easyexcel/faq/ftdw35
