### ISSUE TITLE
请教下Sheet 类中 headLineMun 是干嘛的？

### ISSUE THREAD

**Issue by wwggyy** [alibaba/easyexcel#144]
我用的是 1.1.2-beta4版本， Sheet类中有个属性headLineMun，随便设置个值都可以，没什么意义？

**Comment by jipengfei-jpf** [comment]
在你中间表头和内容有空格时候有用

**Comment by chenajun1234** [comment]
> 在你中间表头和内容有空格时候有用

sheetNo headLineMun 这两参数能具体说明么

**Comment by SunChestnut** [comment]
表示从第几行开始读  public Sheet(int sheetNo, int headLineMun)

**Comment by xiongfeihan** [comment]
> 在你中间表头和内容有空格时候有用

能具体说明一下吗？
