### ISSUE TITLE
解析较大excel时ehcache拖慢解析速度

### ISSUE THREAD

**Issue by sage417** [alibaba/easyexcel#1442]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
看截图可以发现对解析速度影响很大
<img width="1133" alt="f5c53f5a-6055-406b-b6d1-1a38c29aebd6" src="https://user-images.githubusercontent.com/7111791/86121901-6e6da280-bb09-11ea-9d6a-913a4002692d.png">
excel 50w行 6列

**Comment by zhuangjiaju** [comment]
建议开启急速模式。这样数据都在内存。确保内存足够大。
