### ISSUE TITLE
导入excel时如果单元格为空的时候，导入时获取不到该行下标索引

### ISSUE THREAD

**Issue by dengqiquan** [alibaba/easyexcel#1443]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
导入的excel 一列有空白单元格式，读取不到单元格下标索引，设置下单元格格式后，就能读取空白单元格下标索引
**触发Bug的代码**
        ExcelReader reader = null;
        reader = ExcelUtil.getReader(file.getInputStream());
        List<List<Object>> list = reader.read();// 触发代码
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
最新版中间部分会补充，但是也不一定。

**Comment by abelzha** [comment]
3.1.1版本仍存在该问题
