### ISSUE TITLE
@ContentFontStyle注解中默认的字体大小和不添加注解时不一致

### ISSUE THREAD

**Issue by miqiang1986** [alibaba/easyexcel#1444]
@HeadFontStyle注解为14，@ContentFontStyle为-1，不添加注解的字体大小默认为11。这样会导致使用这两个注解时必须统一字体大小

**Comment by zhuangjiaju** [comment]
这个默认设置 就是 这样子的。很久以前的版本 就是 头和身体的字体不一样，暂时不修改。需要样式可以自己调整。
