### ISSUE TITLE
现在EasyExcel支持对某行动态赋值吗？比如，表标题下面一行，是对该表所属的个人或者物体的简单介绍，这些个人简单介绍有人姓名，所属部门等

### ISSUE THREAD

**Issue by yuxioman** [alibaba/easyexcel#1445]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
这个不支持。简单的建议直接poi
