### ISSUE TITLE
动态生成表头时，能否先写入数据，再写入表头。

### ISSUE THREAD

**Issue by jojo1900** [alibaba/easyexcel#1446]
**由于表头是根据表体数据动态生成的，目前需要先遍历一遍数据生成表头、再遍历一遍写入数据，共遍历两次数据。     能否支持不传表头，先写入数据，写入过程中 解析到表头，最后再写入表头，这样只需遍历一次数据。**

**Comment by zhuangjiaju** [comment]
这个目前无法支持。写入是类似于流式的，无法回退。

**Comment by Granado** [comment]
这个问题现在有解决方案了吗
