### ISSUE TITLE
单元格合并后，数字求和有问题

### ISSUE THREAD

**Issue by spcoker** [alibaba/easyexcel#1447]
你好，我现在遇到了这个问题，几个数字合并后的和，是合并前的和，
如图 所示，按理来说合并后 的和应该是 31.33，但是下面显示求和：62.66
![image](https://user-images.githubusercontent.com/28853168/86360998-c6411080-bca5-11ea-8aab-08721e8e5def.png)

**Comment by zhuangjiaju** [comment]
合并单元格 第二格不要输入数据。
