### ISSUE TITLE
表头列超过一定程度，并且有多个合并列的情况下调用excludeColumnFiledNames会错位

### ISSUE THREAD

**Issue by 13538551977** [alibaba/easyexcel#1448]
**触发场景描述**
表头列数超过一定程度，并且有多个合并列的情况下，如果调用排除列的方法，会导致表头错位。
![image](https://user-images.githubusercontent.com/26815418/86465667-b2101880-bd64-11ea-8c10-446831dbbd6f.png)
![image](https://user-images.githubusercontent.com/26815418/86465693-bb998080-bd64-11ea-8449-5395fbcde7a6.png)
![image](https://user-images.githubusercontent.com/26815418/86465638-a886b080-bd64-11ea-822f-eab782051d30.png)

**Comment by 13538551977** [comment]
![image](https://user-images.githubusercontent.com/26815418/86465782-eaaff200-bd64-11ea-9fcb-3c4175b4056c.png)

**Comment by zhuangjiaju** [comment]
最新版 order
