### ISSUE TITLE
Program type already present: org.apache.xmlbeans.xml.stream.Location

### ISSUE THREAD

**Issue by BugRui** [alibaba/easyexcel#1449]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

依赖 报错 Program type already present: org.apache.xmlbeans.xml.stream.Location

**触发Bug的代码**
```java
  // EasyExcel
    api 'com.alibaba:easyexcel:2.2.6'
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
安卓么? 这个需要自己研究下。
