### ISSUE TITLE
与lombok不兼容

### ISSUE THREAD

**Issue by tenstone** [alibaba/easyexcel#1450]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)

**触发场景描述**

@Accessors(chain = true)
实体类使用上述注解时，监听器读不到内容

**触发Bug的代码**
```java

```

**提示的异常或者没有达到的效果**

**Comment by pdkst** [comment]
请遵循java规范：因为EasyExcel底层使用BeanMap进行属性复制，如果getter/setter方法不是标准的就会导致属性复制失败
