### ISSUE TITLE
使用XLSX模板导出，多个list数据，格式显示问题

### ISSUE THREAD

**Issue by q419499249** [alibaba/easyexcel#1452]
使用XLSX模板导出的数据，单元格有```设置自动换行功能```，导出的行数据，数据量并没有达到增加行的高度的条件，只有第一行数据是正常展示，第一行以后的数据 都会自动调整行高

使用XLS模板导出，没有此问题，只是使用XLS模板导出，需要扩展的时候，没有copyRow的功能，所以采用XLSX模板导出

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
