### ISSUE TITLE
在有框线情况下 如何在填充Excl时同时合并单元格

### ISSUE THREAD

**Issue by Chaos-ting** [alibaba/easyexcel#1458]
**当前效果**

![微信截图_20200709180808](https://user-images.githubusercontent.com/57206775/87027367-a5317000-c20f-11ea-82bc-0a929d5ae029.png)
**理想效果**
![微信截图_20200709180834](https://user-images.githubusercontent.com/57206775/87027413-b5e1e600-c20f-11ea-888d-6e15d329f822.png)

**Comment by Chaos-ting** [comment]
hello  有没有人呀

**Comment by Chaos-ting** [comment]
在有框线情况下 如何在填充Excl时同时合并单元格

**Comment by zhuangjiaju** [comment]
自定义样式
