### ISSUE TITLE
读取文件时发现每隔100多行，就读不出数据值来

### ISSUE THREAD

**Issue by ChengLibra** [alibaba/easyexcel#146]
读取文件时发现每隔100多行，就读不出数据值来，而是Sheet{headLineMun=1, sheetNo=1, sheetName='null', clazz=null, head=null, tableStyle=null, columnWidthMap={}}；例如从后台记录看4081、4183、4285、4387..... 行的数据都是如此

**Comment by whpat126** [comment]
看看是不是有隐藏的行

**Comment by jipengfei-jpf** [comment]
文件方便发我一下吗

**Comment by alterhu2020** [comment]
隐藏的行数据如果检测 @whpat126

**Comment by DamonDBT** [comment]
是不是BATCH_COUNT没设置，好像不设置是按100切分，返回最后一次0-100行的数据。
