### ISSUE TITLE
最新版本2.2.6 解析String类型的数值 精度丢失

### ISSUE THREAD

**Issue by uuu901210** [alibaba/easyexcel#1462]
com.opay.payment.risk.provider.server.utils.RiskRefundBlackListener -- 请求的金额为:2.0099999999999998
![image](https://user-images.githubusercontent.com/37365631/87141501-b775e180-c2d5-11ea-988c-d135f0b9e3c0.png)

解决办法 ：
       将easyexcel 版本降级为2.0.0 并重写对double 转换的处理器 
            EasyExcel.read(is, RiskRefundBlackVO.class, new RiskRefundBlackListener(riskRefundBlackContext)).registerConverter(new CustomStringNumberConverter()).sheet(0).doRead();

**Comment by zhuangjiaju** [comment]
能否详细描述下问题。2.0.0 会导致数据读取失败。没懂你 那个值 想要读到多少 结果读到多少。

**Comment by lethal233** [comment]
我这边测试的没问题，能否提供详细的testcase代码？

**Comment by zhuangjiaju** [comment]
是否已经解决问题？如果未解决，可以重新打开问题。
