### ISSUE TITLE
关于read里面的 AnalysisEventListener

### ISSUE THREAD

**Issue by iPopular89** [alibaba/easyexcel#1463]
我想问下，参照你的文档 读excel
https://www.yuque.com/easyexcel/doc/read

是不是每次有新的读取需求时，都需要创建一个类 去extends AnalysisEventListener  然后再使用EasyExcel.read里面的方法

**Comment by pdkst** [comment]
参考`com.alibaba.excel.read.builder.ExcelReaderBuilder#doReadAllSync` API

示例：
```java
        final List<DemoData> demoDataList = EasyExcel.read(fileName)
                .head(DemoData.class)
                .doReadAllSync();
```

选择sheet页
```java
        final List<DemoData> demoDataList = EasyExcel.read(fileName)
                .head(DemoData.class)
                .sheet()
                .doReadSync();
```

**Comment by iPopular89** [comment]
> 参考`com.alibaba.excel.read.builder.ExcelReaderBuilder#doReadAllSync` API
> 
> 示例：
> 
> ```java
>         final List<DemoData> demoDataList = EasyExcel.read(fileName)
>                 .head(DemoData.class)
>                 .doReadAllSync();
> ```
> 
> 选择sheet页
> 
> ```java
>         final List<DemoData> demoDataList = EasyExcel.read(fileName)
>                 .head(DemoData.class)
>                 .sheet()
>                 .doReadSync();
> ```

谢谢，这个回答不是我想问的，不过我已经找到了答案，https://www.cnblogs.com/FraserYu/p/11717665.html

其实我就是想知道，比如我一个是导入用户信息，一个是导入部门信息，还有一个是导入设备信息，这样是需要写3个不同的类 去继承extends AnalysisEventListener吧

**Comment by pdkst** [comment]
> > 参考`com.alibaba.excel.read.builder.ExcelReaderBuilder#doReadAllSync` API
> > 示例：
> > ```java
> >         final List<DemoData> demoDataList = EasyExcel.read(fileName)
> >                 .head(DemoData.class)
> >                 .doReadAllSync();
> > ```
> > 
> > 
> > 选择sheet页
> > ```java
> >         final List<DemoData> demoDataList = EasyExcel.read(fileName)
> >                 .head(DemoData.class)
> >                 .sheet()
> >                 .doReadSync();
> > ```
> 
> 谢谢，这个回答不是我想问的，不过我已经找到了答案，https://www.cnblogs.com/FraserYu/p/11717665.html
> 
> 其实我就是想知道，比如我一个是导入用户信息，一个是导入部门信息，还有一个是导入设备信息，这样是需要写3个不同的类 去继承extends AnalysisEventListener吧

简单读取新版已经不需要自己写自定义的`AnalysisEventListener`了，用上面的API就可以了
