### ISSUE TITLE
excel公式写入后未进行计算的问题

### ISSUE THREAD

**Issue by KennCai** [alibaba/easyexcel#1464]
我定义了一个celldata字段，在写入execl中的时候公式写入成功了，但是该单元格没有发生计算，输出正确的结果。
在填充的时候也出现了这个问题，

```java
  CellData c=new CellData();
  c.setFormula(true);
  c.setFormulaValue("=5*3");
  dto.setTest(c);
```
![image](https://user-images.githubusercontent.com/22788420/87378904-8c370f00-c5c1-11ea-86e8-320ef0c7d3b0.png)

**Comment by fujhmcuxx** [comment]
你好，请问你解决了吗，我也遇到同样的问题

**Comment by ZhaoShaw** [comment]
@zhuangjiaju @fujhmcuxx @KennCai 追踪了一下源码，原因是由于easyexcel调用的poi的setCellFormula方法只设置cell公式字符串，并不进行计算。参考：[https://poi.apache.org/apidocs/3.17/org/apache/poi/ss/usermodel/Cell.html#setCellFormula(java.lang.String)](url)
我暂时的解决方法是设置公式后，激活计算，需要改easyexcel源码重新打包。
例如，AbstractExcelWriteExecutor.converterAndSet的修改（只是数值公式，鲁棒性更强的可以再想想）
`protected CellData converterAndSet(WriteHolder currentWriteHolder, Class clazz, Cell cell, Object value,
        ExcelContentProperty excelContentProperty, Head head, Integer relativeRowIndex) {
        **FormulaEvaluator formulaEvaluator = this.writeContext.writeWorkbookHolder().getWorkbook().getCreationHelper().createFormulaEvaluator();**
        if (value == null) {
            return new CellData(CellDataTypeEnum.EMPTY);
        }
        if (value instanceof String && currentWriteHolder.globalConfiguration().getAutoTrim()) {
            value = ((String)value).trim();
        }
        CellData cellData = convert(currentWriteHolder, clazz, cell, value, excelContentProperty);
        if (cellData.getFormula() != null && cellData.getFormula()) {
            cell.setCellFormula(cellData.getFormulaValue());
            **cell.setCellValue(formulaEvaluator.evaluate(cell).getNumberValue());**
        }
        if (cellData.getType() == null) {
            cellData.setType(CellDataTypeEnum.EMPTY);
        }
        WriteHandlerUtils.afterCellDataConverted(writeContext, cellData, cell, head, relativeRowIndex, Boolean.FALSE);
        switch (cellData.getType()) {
            case STRING:
                cell.setCellValue(cellData.getStringValue());
                return cellData;
            case BOOLEAN:
                cell.setCellValue(cellData.getBooleanValue());
                return cellData;
            case NUMBER:
                cell.setCellValue(cellData.getNumberValue().doubleValue());
                return cellData;
            case IMAGE:
                setImageValue(cellData, cell);
                return cellData;
            case EMPTY:
                return cellData;
            default:
                throw new ExcelDataConvertException(cell.getRow().getRowNum(), cell.getColumnIndex(), cellData,
                    excelContentProperty, "Not supported data:" + value + " return type:" + cell.getCellType()
                        + "at row:" + cell.getRow().getRowNum());
        }
    }`

**Comment by kensinxie** [comment]
> @zhuangjiaju @fujhmcuxx @KennCai 追踪了一下源码，原因是由于easyexcel调用的poi的setCellFormula方法只设置cell公式字符串，并不进行计算。参考：[https://poi.apache.org/apidocs/3.17/org/apache/poi/ss/usermodel/Cell.html#setCellFormula(java.lang.String)](url)
> 在Fill以后，整体做一次计算：
> `excelWriter.writeContext().writeWorkbookHolder().getWorkbook().getCreationHelper().createFormulaEvaluator().evaluateAll()`

测试了一下，就是这个原因。
但是在fill以后，需要进行两步操作，才能进行公式的重新计算。
```
excelWriter.writeContext().writeWorkbookHolder().getWorkbook().setForceFormulaRecalculation(true);
excelWriter.writeContext().writeWorkbookHolder().getWorkbook().getCreationHelper().createFormulaEvaluator().evaluateAll();
```

**Comment by zhuangjiaju** [comment]
参照楼上即可。
