### ISSUE TITLE
Excel导出时同一字段表头不同命名

### ISSUE THREAD

**Issue by kkevinzhang** [alibaba/easyexcel#1468]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**
某个字段在每次导出时命名都不同，不知道能不能实现

**Comment by pdkst** [comment]
建议参考：[官方文档：动态头，实时生成头写入](https://www.yuque.com/easyexcel/doc/write#b4b9de00)
