### ISSUE TITLE
导出excel的单元格下拉列表中，超过255个字怎么办?

### ISSUE THREAD

**Issue by jerryqx** [alibaba/easyexcel#1469]
导出excel的单元格下拉列表中，超过255个字怎么办?

**Comment by zhangshuai6060** [comment]
请问你解决了吗  我也遇到这个问题了

**Comment by pdkst** [comment]
建议使用序列，来源里选择单元格 [百度链接](https://baijiahao.baidu.com/s?id=1610485371326222406&wfr=spider&for=pc)

**Comment by jerryqx** [comment]
> 请问你解决了吗 我也遇到这个问题了

解决了，使用的就是使用序列，来源里选择单元格。 把需要下拉的值写到另外的sheet页中进行引用

**Comment by jerryqx** [comment]
> 建议使用序列，来源里选择单元格 [百度链接](https://baijiahao.baidu.com/s?id=1610485371326222406&wfr=spider&for=pc)

谢谢，按照这种方式解决了

**Comment by zhangshuai6060** [comment]
使用序列 解决了！  谢谢！
