### ISSUE TITLE
[RFC] Closing pull requests while a new build is starting causes failures

### ISSUE THREAD

**Issue by maldoinc** [alibaba/easyexcel#1470]
Build failures often indicate a fault with the software being built such as compilation or test failures. However, there is a subset of build failures (called *environmental* or *non-verification failures*) that are not expected within a standard application development lifecycle, such as build configuration failures, dependency resolution failures, infrastructure failures, and so on.

**Problem:** One type of environmental failure is due to due to git references being no longer available at the time a build job starts. For example, pull requests are merged shortly before the start of the scheduled build, causing a build failure due to an unfound (because merged) branch. In your project, we detected 1 failure of this type over the May-June timespan. For instance, we found that [Build #404](https://travis-ci.org/alibaba/easyexcel/builds/698948869) did not pass due to the above issue.

**Solution:** It is generally recommended to wait for the build results before merging a pull request. If you wish to skip builds you may also use the [SKIP CI](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build) tag in your commit message. Additionally, it is also possible to skip builds containing non-code changes as shown in [this example](https://github.com/google/EarlGrey/pull/383/files/3b38a5dea36a88aba42a42931e77a7c5429a1837) and below:

```diff

+ before_install:
+  - |
+      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.png)|(.pdf)|(.html)|^(LICENSE)|^(docs)'
+      then
+        echo "Only doc files were updated, not running the CI."
+        exit
+      fi

```
---
*Disclaimer:* I developed a tool that repairs environmental build failures and I am now evaluating its usefulness for open-source projects.

*Please up/downvote the issue to indicate whether you agree/disagree with the report and the proposed fix.*

**Comment by zhuangjiaju** [comment]
Thank you for your suggestion.
