### ISSUE TITLE
读取Excel的数据时，会有个别单元格数据读取错误

### ISSUE THREAD

**Issue by 98jiang** [alibaba/easyexcel#1472]
读取Excel的时候有一些单元格数据会缺少一部分，比如“1234.56”读出来会变成“123”.

实体类的该字段是这样的：
`@NumberFormat("#.##")`
`private String jiesuanjine;`

excel是Spring框架的MultipartFile类，读取Excel的代码如下：
`EasyExcel.read(excel.getInputStream(),testData.class, newEmailListener).sheet().doRead();`

单元格已经复制到新的sheet并且只粘贴值，没有公式，文件格式是.xlsx，只有1600行数据。
![TIM图片20200716113157](https://user-images.githubusercontent.com/40812030/87624193-b3284900-c759-11ea-89f2-81ee2377810b.png)

调试模式获取到的对象内容：
![111](https://user-images.githubusercontent.com/40812030/87634697-600dc080-c770-11ea-8e37-491e2d35167b.png)

poi版本：4.0.1
easyexcel版本：2.2.6（改为2.0版本之后的都有这个问题）

**Comment by zhuangjiaju** [comment]
请提供下excel

**Comment by zhuangjiaju** [comment]
是否已经解决问题？如果未解决 请重新打开问题。
