### ISSUE TITLE
easyExcel模板填充导致数据被挤到下一列问题（原因是每填充一行数据都会产生一个新空列导致数据下移）

### ISSUE THREAD

**Issue by lzh86** [alibaba/easyexcel#1475]
`第一种方案
FillConfig fillConfig1 = FillConfig.builder().forceNewRow(Boolean.FALSE).build();
excelWriter.fill(creatWorkInfoVOList(),fillConfig1,writeSheet);

FillConfig fillConfig2 = FillConfig.builder().forceNewRow(Boolean.FALSE).build();
excelWriter.fill(createRewardInfoVOList(), fillConfig2, writeSheet);

后来查到方案说用 FillWrapper
第二种方案
 FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.FALSE).build();
            EasyExcelFillUtil easyExcelFillUtil = new EasyExcelFillUtil(excelWriter);
            FillWrapper fillWrapper = new FillWrapper(creatStudentInfoVOList());
            easyExcelFillUtil.fillWithSheet(fillWrapper,fillConfig,writeSheet);

            EasyExcelFillUtil easyExcelFillUtil1 = new EasyExcelFillUtil(excelWriter);
            FillWrapper fillWrapper1 = new FillWrapper(creatWorkInfoVOList());
            easyExcelFillUtil1.fillWithSheet(fillWrapper1,fillConfig,writeSheet);

自定义fillWithSheet  @方法
public  static  boolean fillWithSheet(FillWrapper fillWrapper,FillConfig fillConfig, WriteSheet writeSheet) {
        try {
            if (null != fillWrapper) {
                excelWriter.fill(fillWrapper,fillConfig, writeSheet);
                System.out.println("你已经填充了一组数据");
                return true;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            return false;
        }
        return false;
    }

`
[1594980914665.xlsx](https://github.com/alibaba/easyexcel/files/4937270/1594980914665.xlsx)
[Uploading 1594980914665.xlsx…]()

**Comment by lzh86** [comment]
>

**Comment by zhuangjiaju** [comment]
实际测试没问题 请使用new FillWrapper("data1", data()) 然后升级到 2.2.11
