### ISSUE TITLE
提个bug,相同的表头名会导致合并单元格

### ISSUE THREAD

**Issue by fangming-yi** [alibaba/easyexcel#148]
一个excel表头很有相同的列名是很常见的，他们之间不是连续的。easyexcel在添加表头的时候，直接将相同的表头之间的单元格合并，这会有点问题：如果只是这两个表头相同，但是他们不是连续的，这就不应该将他们合并单元格。问题出现在：
GenerateContextImpl#appendHeadToExcel()  调用ExcelHeadProperty#getCellRangeModels，然后在计算getLastRangColumn()时，

```java
private int getLastRangColumn(String value, List<String> headByRowNum, int i) {
        if (headByRowNum.indexOf(value) < i) {
            return -1;
        } else {
            return headByRowNum.lastIndexOf(value);
        }
    }
```

不应该直接取lastIndexOf，而是取连续的最后一个相同value的index

**Comment by jipengfei-jpf** [comment]
升级最新版本1.1.2-beta4已经修复了
