### ISSUE TITLE
如果model层里面不同的两个字段有对应的两个不同的converter，只生效一个

### ISSUE THREAD

**Issue by luciferwzh** [alibaba/easyexcel#1483]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
放在注解上面
