### ISSUE TITLE
导出空数组时，会报导出的文件已损坏。版本：2.2.6

### ISSUE THREAD

**Issue by yu514950381** [alibaba/easyexcel#1485]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
数据库查询出来没有符合条件的数据，然后对size为0的ArrayList执行导出，浏览器能下载文件，但是下载下来的excel为0kb，且无法打开
**触发Bug的代码**
```java
WriteSheet writeSheet = EasyExcel.writerSheet(sheetNames).registerWriteHandler(horizontalCellStyleStrategy).head(clazz).build();
excelWriter.write(dataList, writeSheet);
```
**提示的异常或者没有达到的效果**
![image](https://user-images.githubusercontent.com/31887388/88037941-2118aa00-cb78-11ea-89c9-79b1340e7bd4.png)
![image](https://user-images.githubusercontent.com/31887388/88037966-28d84e80-cb78-11ea-8cea-b679ff50f88a.png)

**Comment by Jiaxiayuan** [comment]
@yu514950381 这个不算bug，是你的代码里面没有进行finish()

excelWriter.write(dataList, writeSheet).finish();

**Comment by yu514950381** [comment]
> @yu514950381 这个不算bug，是你的代码里面没有进行finish()
> 
> excelWriter.write(dataList, writeSheet).finish();

我后来检查了一下，这个确实是我忘了做dataList的空值判断了，我在其它地方有finish来着。多谢提醒。我加上判断后，发现就可以正常导出空数组了
