### ISSUE TITLE
基于多个模板fill数据，如何切换模板

### ISSUE THREAD

**Issue by iamlake** [alibaba/easyexcel#1488]
我有一个需求，想要通过模板生成excel。模板有A、B两个sheet，A是目录，B是明细页面。
想要完成的填充效果是，A填充一次，B根据条目数重复填充N次（sheetA，sheetB1，sheetB2...sheetBn）

我现在的设想是把模板拆开，变成A/B两个模板。
但写的时候是往同一个excel中写。
模板A的数据写完之后，这时要切换到模板B，但我没有找到可切换的方法，

请问ExcelWriter支持切换模板写数据吗？

不胜感激！

**Comment by iamlake** [comment]
ExcelWriter excelWriter = EasyExcel.write(response.getOutputStream()).withTemplate(template1).build();
WriteSheet writeSheet = EasyExcel.writerSheet("sheet1").build();
//使用模板1写入到sheet1中
excelWriter.fill(dataList1, fillConfig, writeSheet);

//切换到模板2写入到sheet2
WriteSheet writeSheet = EasyExcel.writerSheet("sheet2").build();
....withTemplate(template2).build(); //TODO 切换模板
excelWriter.fill(dataList2, fillConfig, writeSheet);

是否可支持类似操作？

**Comment by xx0508** [comment]
同问，或者有什么变通的方法也行

**Comment by zhuangjiaju** [comment]
参照多次写入demo,结合下 很容易的。

**Comment by 2021404** [comment]
解决了嘛？
