### ISSUE TITLE
导出 Date 为字符串类型, 在 Excel 中批量设置单元格格式无法生效, 需要先设置数据选项卡->分列操作

### ISSUE THREAD

**Issue by rogerandgithub** [alibaba/easyexcel#1499]
**触发场景描述**
当前使用最新版本 2.2.6
导出 Date 为字符串类型, 在 Excel 中批量设置单元格格式无法生效, 需要先设置数据选项卡->分列操作
**触发Bug的代码**
```java
    @DateTimeFormat("yyyy-MM-dd")
    @ExcelProperty("日期")
    private Date createTime;
```
**提示的异常或者没有达到的效果**
希望能跟 https://github.com/SheetJS/sheetjs 前端导出效果一样, 导出后 Date 为 Excel 可识别的原生日期类型
我看了一下贵项目 issue, 有反应过类似问题, 但解决方式需要自定义拦截器, 想请问下有没有更简单的实现方式或者后续贵项目会修复这个问题

**Comment by zhuangjiaju** [comment]
这个比较复杂后续版本会考虑。

**Comment by ivan0x7cd** [comment]
" 我看了一下贵项目 issue, 有反应过类似问题, 但解决方式需要自定义拦截器, 想请问下有没有更简单的实现方式或者后续贵项目会修复这个问题。"

！！！急急急，请求回答，请问怎么自定义拦截器，来转换日期？

**Comment by 520goodguys** [comment]
这个问题我本地调试，也没有解决多嘛。为什么关闭了啊。
