### ISSUE TITLE
解析效率越来越慢是什么原因呢

### ISSUE THREAD

**Issue by cqrickychen** [alibaba/easyexcel#15]
首先说明一下；
字段比较多，30个多，excel文件12w行多；基本都是String类型，部分String还是特别长那种。

CurrentName:workbook
CurrentName:fileVersion
CurrentName:workbookPr
CurrentName:mc:AlternateContent
CurrentName:mc:Choice
CurrentName:x15ac:absPath
CurrentName:bookViews
CurrentName:workbookView
CurrentName:sheets
CurrentName:3
CurrentName:name
CurrentName:sheetId
CurrentName:r:id
CurrentName:calcPr
CurrentName:extLst
CurrentName:ext
CurrentName:x15:workbookPr
09:46:01.038,当前行:1000
09:46:01.647,当前行:2000
09:46:02.506,当前行:3000
09:46:03.691,当前行:4000
09:46:05.174,当前行:5000  时差 5秒内

09:46:06.969,当前行:6000
09:46:09.326,当前行:7000
09:46:12.556,当前行:8000
09:46:17.643,当前行:9000
09:46:25.334,当前行:10000  时差20秒；

09:46:33.416,当前行:11000
09:46:42.668,当前行:12000
09:46:53.480,当前行:13000
09:47:07.068,当前行:14000
09:47:21.796,当前行:15000，耗时接近60秒

09:47:37.288,当前行:16000
09:47:54.542,当前行:17000
09:48:13.341,当前行:18000
09:48:34.387,当前行:19000
09:48:58.630,当前行:20000  时差接近90秒

09:49:27.398,当前行:21000
09:49:57.990,当前行:22000
09:50:28.021,当前行:23000
09:51:00.486,当前行:24000
09:51:34.667,当前行:25000  时差 90秒

09:52:09.690,当前行:26000
09:52:44.884,当前行:27000
09:53:20.641,当前行:28000
09:53:59.985,当前行:29000
09:53:59.985,当前行:29000
09:54:41.963,当前行:30000 时差 180多秒，

09:55:25.776,当前行:31000
09:56:08.334,当前行:32000
09:57:02.900,当前行:33000
09:57:58.525,当前行:34000
09:58:56.699,当前行:35000  时差250秒，4分多’

效率承递减递减，逐级递减，

**Comment by jipengfei-jpf** [comment]
看一下是不是自己时间算的总计算算错了呢

**Comment by jipengfei-jpf** [comment]
处理一些数据后尽快处理了不要长时间占用内存
