### ISSUE TITLE
有没有类似flush的方法立刻写

### ISSUE THREAD

**Issue by goldenduo** [alibaba/easyexcel#1501]
**场景**：因为程序随时可能中断，中断时候 虽然已经调用到write，但是实际上并没有写到硬盘，导致数据丢失。
**问题**：多次写入Excel时候并不会实时写入，有没有类似flush的方法，可以将缓存立刻输出的，但是又不用关闭？
或者有接口可以设置缓冲区大小？

**Comment by zhuangjiaju** [comment]
目前没有。程序中断就重新去数据库读取导出。
