### ISSUE TITLE
使用填充的功能时，必须要先创建一个目标.xlsx文件吗，不可以直接填充模板吗，这样的话我把被填充完的目标.xlsx文件读取后传到服务器还得手动删除本地的目标文件？？？

### ISSUE THREAD

**Issue by Yangsuyi** [alibaba/easyexcel#1503]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
可以放到流里面。

**Comment by Yangsuyi** [comment]
放流里的话怎么转换成输入流啊，我要上传到服务器------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jiaju&amp;nbsp;Zhuang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月29日(星期六) 下午2:03
收件人:&nbsp;&quot;alibaba/easyexcel&quot;<easyexcel@noreply.github.com&gt;;
抄送:&nbsp;&quot;Yangsuyi&quot;<2289081844@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 使用填充的功能时，必须要先创建一个目标.xlsx文件吗，不可以直接填充模板吗，这样的话我把被填充完的目标.xlsx文件读取后传到服务器还得手动删除本地的目标文件？？？ (#1503)
