### ISSUE TITLE
期望大佬们能够发布一个依赖poi 4.1.0以上的版本

### ISSUE THREAD

**Issue by xhyan0427** [alibaba/easyexcel#1505]
我先是fill了一个list，然后fill了一个map，这样就触发excel自动修复的问题，导致位于list后面的数据都丢失了。。我的原因是我引用了poi-tl 1.7.3，它最低需要使用poi 4.1.0版本，但是easyexcel的poi版本最高才3.17。删除poi-tl的依赖后，EasyExcel的功能是正常的，所以期望大佬能够发布一个依赖poi 4.1.0以上的版本，谢谢。。

**Comment by cn-src** [comment]
期望早点升级，之前用过高版本POI不兼容。
做好兼容也行，poi本身更新频率就不高。

**Comment by datastairs** [comment]
同样希望早点升级支持高版本的POI，谢谢

**Comment by zhuangjiaju** [comment]
poi 后续版本最低兼容jdk8。很多同学在用Jdk6，后续3+版本会考虑升级。
