### ISSUE TITLE
excelProperty 注解 类型是个List ,如何处理list? 如何把list 添加到单元格里面

### ISSUE THREAD

**Issue by valar-lee** [alibaba/easyexcel#1508]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by tldzyx** [comment]
遍历 list, 每个 item 写一行, 以此类推

**Comment by valar-lee** [comment]
> 遍历 list, 每个 item 写一行, 以此类推

可以具体讲下细节吗

**Comment by Muscleape** [comment]
感觉类似于类型转换，可以考虑在converter里面把list数据处理成需要在单元格里展示的形式

**Comment by valar-lee** [comment]
private void addOneRowOfDataToExcel(Object oneRowData, int n, int relativeRowIndex,
        Map<Integer, Field> sortedAllFiledMap) {
        if (oneRowData == null) {
            return;
        }
        WriteHandlerUtils.beforeRowCreate(writeContext, n, relativeRowIndex, Boolean.FALSE);
        Row row = WorkBookUtil.createRow(writeContext.writeSheetHolder().getSheet(), n);
        WriteHandlerUtils.afterRowCreate(writeContext, row, relativeRowIndex, Boolean.FALSE);
        if (oneRowData instanceof List) {
            addBasicTypeToExcel((List) oneRowData, row, relativeRowIndex);
        } else {
            addJavaObjectToExcel(oneRowData, row, relativeRowIndex, sortedAllFiledMap);
        }
        WriteHandlerUtils.afterRowDispose(writeContext, row, relativeRowIndex, Boolean.FALSE);
    }


这里 好像做了处理 但是小弟水平有限 没看懂,是怎么处理的.求指教啊

**Comment by icemanjc** [comment]
看你是想把list里面的值写到一个cell里还是多个cell里，可以如楼上所说自己实现Converter<T>接口

**Comment by valar-lee** [comment]
好的

**Comment by 5721617zzw** [comment]
@valar-lee  这个问题处理了吗？怎么处理的？
