### ISSUE TITLE
不加ExcelProperty注解的，也会出现在excel中

### ISSUE THREAD

**Issue by waterChens** [alibaba/easyexcel#1511]
不加ExcelProperty注解的，也会出现在excel中；
如何排除实体中不加注解的字段。

**Comment by yudonz** [comment]
怎么关了，答案是什么

**Comment by waterChens** [comment]
在对应的类上面添加@ExcelIgnoreUnannotated注解。就可以解决这个问题





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上6:48
收件人:&nbsp;"alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送:&nbsp;"尐氏 _/~-尛"<791388069@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 不加ExcelProperty注解的，也会出现在excel中 (#1511)





 
怎么关了，答案是什么

**Comment by RUAN-ZX** [comment]
帮了大忙了 正打算拿Excel entity改改 直接作为数据库字段对应的ORM实体 否则按传统方式 要做两个对象 还要做转换方法 adapter也好 还是自己写valueOf方法也好 耦合度都太高 改一个 两个都要改 两个所涉及的所有get set valueOf等方法都要改 对于企业动辄30列以上的情况 稍微改改 就算借助IDEA统一改 总归还是不优雅 

> 在对应的类上面添加@ExcelIgnoreUnannotated注解。就可以解决这个问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alibaba/easyexcel" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月19日(星期三) 晚上6:48 收件人:&nbsp;"alibaba/easyexcel"<easyexcel@noreply.github.com&gt;; 抄送:&nbsp;"尐氏 _/~-尛"<791388069@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;; 主题:&nbsp;Re: [alibaba/easyexcel] 不加ExcelProperty注解的，也会出现在excel中 (#1511) 怎么关了，答案是什么 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
