### ISSUE TITLE
读取Excel并编辑功能

### ISSUE THREAD

**Issue by dazong** [alibaba/easyexcel#152]
在做一个往已有excel里插数据的项目，看到easyexcel也是支持已有template的。但我还需要更改excel里面自定义的数据表的数据范围，这个功能对excel里图表制作很重要。请问是否考虑支持。

**Comment by jipengfei-jpf** [comment]
目前easyexcel不支持图标功能

**Comment by jipengfei-jpf** [comment]
如果需要读取前面数据，可以先读取模板文件
