### ISSUE TITLE
表头是否支持自定义合并

### ISSUE THREAD

**Issue by wangchengxin** [alibaba/easyexcel#1523]
**想要实现的效果**
![dPQuDJ.png](https://s1.ax1x.com/2020/08/14/dPQuDJ.png)

**当前翻阅所有官方文档后实现的效果**
![dPQECV.png](https://s1.ax1x.com/2020/08/14/dPQECV.png)

目前我们只能实现列头的列合并，没有找到列头的行合并的方法，请各位大佬指点迷津！

**Comment by Zslaiye** [comment]
表头自定义，合并的话你可以尝试在单元格创建后的时机 添加你自己的合并策略 当然了  还是要使用poi的相关方法

**Comment by zhuangjiaju** [comment]
头两列 name 取成一样 即可。
