### ISSUE TITLE
发现一个BUG无法处理麻烦告知下怎么解决

### ISSUE THREAD

**Issue by qq984876303** [alibaba/easyexcel#1530]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
![image](https://user-images.githubusercontent.com/22909818/90615788-2896a600-e23f-11ea-906b-339654126167.png)
![image](https://user-images.githubusercontent.com/22909818/90615812-30eee100-e23f-11ea-8341-9ea07fff8a92.png)

**触发Bug的代码**
```java
    EasyExcel.write(fileName).head(head).sheet("模板").doWrite(contents);
```
**提示的异常或者没有达到的效果**
![image](https://user-images.githubusercontent.com/22909818/90615688-0c930480-e23f-11ea-8112-19b49270fb79.png)

**Comment by zhuangjiaju** [comment]
这个不是bug，设计的不太合理。参照下下写入demo. 需要 `List<List<String>>`
