### ISSUE TITLE
如何在模板填充中导出图片

### ISSUE THREAD

**Issue by leehaoxindehao** [alibaba/easyexcel#1537]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
入参是文件就行
