### ISSUE TITLE
导出excel的时候为什么要加.autoCloseStream(Boolean.FALSE)？

### ISSUE THREAD

**Issue by shigzh** [alibaba/easyexcel#1539]
您好，请问excel导出的时候，为什么要加
.autoCloseStream(Boolean.FALSE) 这个，不自动关闭流，看了源码，如果设置了这个，doWrite里就不会自动关闭流，请问什么时候关闭呢？没有搞明白，请解答一下，谢谢

**Comment by wolf9236** [comment]
我也好奇为啥在web导出 需要设置不关闭流

**Comment by Yangqi0338** [comment]
自己手动关闭 就可以封装一个json参数给前端
