### ISSUE TITLE
计算400多条记录金额总数错误

### ISSUE THREAD

**Issue by coderbruis** [alibaba/easyexcel#1542]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

使用了easyexcel的2.0.0版本来读取400多条记录，然后计算记录中金额总数结果不正确。

**触发Bug的代码**

**提示的异常或者没有达到的效果**

金额总数计算不正确。

**Comment by zhuangjiaju** [comment]
建议升级版本
