### ISSUE TITLE
2.0.5 版本导出数据 list 有值 ，excel有的列为空，升到高版本，不能生成下载的excel，报错java.lang.NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader

### ISSUE THREAD

**Issue by yanjiejiecn** [alibaba/easyexcel#1543]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader
**建议描述**

**Comment by yanjiejiecn** [comment]
一个excel有三个sheet，第一个有几列数据为空，第二 第三sheet正常输出

**Comment by zhuangjiaju** [comment]
统一poi版本
