### ISSUE TITLE
写入文件时,  创建文件时如果使用了自定义的时间转换 yyyy-MM-dd 当excel的名称 就会报错 你们有遇到过吗 

### ISSUE THREAD

**Issue by 123321hui** [alibaba/easyexcel#1549]
写入文件时,  创建文件时如果使用了自定义的时间转换 yyyy-MM-dd 当excel的名称 就会报错 说没有这个文件 但是使用了官网给的demo System.currentTimeMillis() 就不会错误  你们有遇到过吗

**Comment by pdkst** [comment]
可能创建的文件名中包含特殊字符，逐个排除下试试
![image](https://user-images.githubusercontent.com/8915631/94154348-5b703180-feb0-11ea-94c6-68d417257b18.png)
