### ISSUE TITLE
第一步生成excel模板，第二步然后再用生成的模板进行填充数据，第一步用代码生成的excel模板能正常打开，第二部用模板进行填充数据生成的excel打不开，紧接着我把excel模板里生成的{.xxx}行给格式刷一下保存，然后再直接用这个模板进行填充数据就能正常打开且填充结果正确

### ISSUE THREAD

**Issue by timeAlreadyLocked** [alibaba/easyexcel#1552]
第一步部分代码：
![image](https://user-images.githubusercontent.com/35451875/92425412-c257d000-f1b9-11ea-8975-845571e0ab93.png)

第二步部分代码
![image](https://user-images.githubusercontent.com/35451875/92425459-e9ae9d00-f1b9-11ea-9074-ed6711e94e53.png)

大致就是：生成模板，使用生成的模板进行填充数据 （之前用 xxx.fill()进行填充生成模板没有出现类似问题）

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
