### ISSUE TITLE
模板填充单元格合并问题

### ISSUE THREAD

**Issue by jiang-jian-jian** [alibaba/easyexcel#1553]
一、使用2.2.6版本的模板填充功能，模板文件有多个数据集，其中有一个数据集需要合并的单元格。在填充数据的过程中，合并的单元格第一行正常，第二行开始，单元格未合并，如下图所示
![image](https://user-images.githubusercontent.com/38133323/92427066-15338680-f1be-11ea-8f31-c7830f9e5cd6.png)
二、我的模板文件
![image](https://user-images.githubusercontent.com/38133323/92427175-6479b700-f1be-11ea-99b2-0218aabc8ccf.png)
三、我的代码
![image](https://user-images.githubusercontent.com/38133323/92427194-72c7d300-f1be-11ea-8c0a-6104c98a6134.png)

**Comment by 13661411934** [comment]
同遇到 ， 填充好像不会合并单元格

**Comment by l523402485** [comment]
我也有相同的问题， 版本2.2.6
而且有的单元格格式丢失(粗体、自动换行)，边框异常
![微信截图_20210204103940](https://user-images.githubusercontent.com/35321032/106837701-e9b5b900-66d5-11eb-81b1-060fc9ccdfa9.png)
![微信截图_20210204104019](https://user-images.githubusercontent.com/35321032/106837718-f0443080-66d5-11eb-9b35-6448f9a5ffe3.png)
![微信截图_20210204104037](https://user-images.githubusercontent.com/35321032/106837724-f4704e00-66d5-11eb-9976-756d859dd8fe.png)
<details>
<summary>code：</summary>

```java
public ByteArrayInputStream complexFill(Object data, String template, List<JSONArray> lists) {
    ByteArrayOutputStream bOutput = new ByteArrayOutputStream();
    InputStream inputStream;
    try {
        inputStream = new ClassPathResource(template).getInputStream();
    } catch (IOException e) {
        return null;
    }
    ExcelWriter excelWriter = EasyExcel.write(bOutput)
            .excelType(".xls".equals(getFileType(template)) ? ExcelTypeEnum.XLS : ExcelTypeEnum.XLSX)
            .withTemplate(inputStream)
            .build();
    WriteSheet writeSheet = EasyExcel.writerSheet().build();
    FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.TRUE).build();
    for (JSONArray list : lists) {
        excelWriter.fill(list, fillConfig, writeSheet);
    }
    excelWriter.fill(data, writeSheet);
    excelWriter.finish();
    return new ByteArrayInputStream(bOutput.toByteArray());
}
```
</details>

**Comment by jiang-jian-jian** [comment]
> 我也有相同的问题， 版本2.2.6
> 而且有的单元格格式丢失(粗体、自动换行)，边框异常
> ![微信截图_20210204103940](https://user-images.githubusercontent.com/35321032/106837701-e9b5b900-66d5-11eb-81b1-060fc9ccdfa9.png)
> ![微信截图_20210204104019](https://user-images.githubusercontent.com/35321032/106837718-f0443080-66d5-11eb-9b35-6448f9a5ffe3.png)
> ![微信截图_20210204104037](https://user-images.githubusercontent.com/35321032/106837724-f4704e00-66d5-11eb-9976-756d859dd8fe.png)
> 
> code：

**Comment by jiang-jian-jian** [comment]
> > 我也有相同的问题， 版本2.2.6
> > 而且有的单元格格式丢失(粗体、自动换行)，边框异常
> > ![微信截图_20210204103940](https://user-images.githubusercontent.com/35321032/106837701-e9b5b900-66d5-11eb-81b1-060fc9ccdfa9.png)
> > ![微信截图_20210204104019](https://user-images.githubusercontent.com/35321032/106837718-f0443080-66d5-11eb-9b35-6448f9a5ffe3.png)
> > ![微信截图_20210204104037](https://user-images.githubusercontent.com/35321032/106837724-f4704e00-66d5-11eb-9976-756d859dd8fe.png)
> > code：
我通过自定义的CellWriteHandler解决了。
`@Data
@AllArgsConstructor
@NoArgsConstructor
public class ExcelColumnMergeHandler implements CellWriteHandler {
	//从哪列开始合并
    private int mergeColumnIndex;
	//需要合并的列数
    private int mergeColumnSize;
	……
	@Override
    public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, List<CellData> list, Cell cell, Head head, Integer integer, Boolean aBoolean) {
        int currentRowIndex = cell.getRowIndex();
        int currentColumnIndex = cell.getColumnIndex();
        if (currentColumnIndex == mergeColumnIndex) {
            Row row = cell.getRow();
            CellStyle cellStyle = cell.getCellStyle();
            Cell cell1 = row.getCell(currentColumnIndex);
            cell1.setCellStyle(cellStyle);
            CellRangeAddress cellRangeAddress = new CellRangeAddress(currentRowIndex, currentRowIndex, currentColumnIndex, currentColumnIndex + mergeColumnSize);
            writeSheetHolder.getSheet().addMergedRegion(cellRangeAddress);
            cell.setCellStyle(cellStyle);
        }
    }
	
｝`

**Comment by zxy-0116** [comment]
您好，我也同样出现了相同的情况，请问您这里有得到解决吗
![image](https://user-images.githubusercontent.com/66982958/200264841-4bba6f78-4bd4-4b61-98f2-a67d49e4d4d6.png)
