### ISSUE TITLE
目前是否支持多个sheet的excel填充？

### ISSUE THREAD

**Issue by JohnHello** [alibaba/easyexcel#1554]
@zhuangjiaju 这么着急关issue干嘛，确认支持吗？全部issues加语雀评论，我没看到有一个用户是可以成功实现多sheet的excel填充的。既然你说支持，给写个demo实际跑一下啊。不是说一句支持就直接关闭issue完事的

_Originally posted by @JohnHello in https://github.com/alibaba/easyexcel/issues/1438#issuecomment-688384598_

**Comment by timeAlreadyLocked** [comment]
支持的

**Comment by hanyu658** [comment]
自己不会看文档吗 https://www.yuque.com/easyexcel/doc/write#b8e4013d

**Comment by tofdragon** [comment]
多个sheet填充是支持的，但是如果模板中只有一个sheet 要填充完一个sheet,在继续使用第一个sheet作为第二个 是不支持的 @timeAlreadyLocked

**Comment by yangsiyuan0** [comment]
> 自己不会看文档吗 https://www.yuque.com/easyexcel/doc/write#b8e4013d
问的是填充，你这个写入

> 多个sheet填充是支持的，但是如果模板中只有一个sheet 要填充完一个sheet,在继续使用第一个sheet作为第二个 是不支持的 @timeAlreadyLocked

多个sheet填充时，导出文档的sheet和模板文档的sheet按照编号是一一对应的，如果模板文件中没有对应编码的sheet，就会抛出NullPointerException

**Comment by hanyu658** [comment]
@yangsiyuan0  
确实没看仔细，不好意思。
多sheet填充的话，我理解把旧数据读出来，和填充数据做合并处理之后，再重新写入可能会简单些？

**Comment by jaedonghan** [comment]
多sheet写入，其中一个sheet写报异常，之后的sheet数据就不会写入了，不知道大家有没有遇到过

**Comment by jf11480** [comment]
> 多sheet写入，其中一个sheet写报异常，之后的sheet数据就不会写入了，不知道大家有没有遇到过

官方的意思是  sheet1 对应sheet1 的模板填充,sheet2 对应sheet2的模板填充,如果没有sheet2就报错,太逗了
