### ISSUE TITLE
使用easyexcel时遇到Could not initialize class net.sf.cglib.beans.BeanMap$Generator

### ISSUE THREAD

**Issue by liuyongfei1** [alibaba/easyexcel#1562]
**异常提示**
```java
nested exception is com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.beans.BeanMap$Generator] with root cause]
java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.beans.BeanMap$Generator
```
**建议描述**
使用easyexcel工具开发excel的上传和下载功能时，本机环境测试没有问题，部署到测试环境时，却发现下载excel文件的功能一直异常。

**Comment by liuyongfei1** [comment]
问题已经解决，主要原因是 easyexcel的 cglib 依赖的 asm 和 springboot依赖的asm jar包冲突:

详情看以看这篇文章：
https://mp.weixin.qq.com/s?__biz=MzAwMjk5NTY3Mw==&mid=2247483950&idx=1&sn=47c6c1fed54b134f46f6dedafd34db0c&chksm=9ac0a698adb72f8e769bcfbff5a4fb0450f181bb754a2ad615dc17002f14d7ec039c0e24a1d7&token=395785991&lang=zh_CN#rd

**Comment by wenstonqq** [comment]
建议升级最新的easyexcel包，官方已经解决该问题
  <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>4.0.1</version>
  </dependency>
<img width="1366" alt="image" src="https://github.com/user-attachments/assets/73d77141-0b81-47e8-bef8-956d9751861f">
