### ISSUE TITLE
最新版本2.2.6 通过对象继承方式读取数据错乱

### ISSUE THREAD

**Issue by qianchang8358** [alibaba/easyexcel#1563]
**触发场景描述**
项目中读取Excel的众多表格中，存在一些公共的属性 如下
![1599726898(1)](https://user-images.githubusercontent.com/28428826/92702681-144c5180-f384-11ea-8743-9f4ebd974f7a.jpg)
未抽取到父类之前，正常读取结果如下
![1599727356(1)](https://user-images.githubusercontent.com/28428826/92703356-b3714900-f384-11ea-9d9d-f872bffc775e.jpg)
当我把公共属性抽取到父类之后，读取结果发生了错乱
![image](https://user-images.githubusercontent.com/28428826/92703988-35617200-f385-11ea-8219-71b2ac7d292e.png)

**触发Bug的代码**
```java
   这里写代码
```

1. 

**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
使用`@ExcelIgnoreUnannotated` 注解

**Comment by angiely1115** [comment]
使用@ExcelIgnoreUnannotated依然未解决问题
