### ISSUE TITLE
大文件读取，读取到某一行，不再继续？如何中断读取

### ISSUE THREAD

**Issue by kipin** [alibaba/easyexcel#1566]
AnalysisEventListener的实例中，读取一行执行invoke方法。比如，15000行的excel，怎么在读取5000行，不再**往下读取**数据，想要的业务已经完成了。
读取到想要的数据，**中断**程序。
是不是AnalysisContext有什么参数可以设置，找了半天，没能解决。谢谢

**Comment by mmzhi** [comment]
invoke方法里面写个计数器，然后到了指定数量，抛出异常，catch处理之后，继续处理后续业务

**Comment by yissan** [comment]
重写hasNext方法，业务决定返回true or false
