### ISSUE TITLE
导出excel想要支持行分组请问该如何实现呢

### ISSUE THREAD

**Issue by laoqian** [alibaba/easyexcel#1567]
类似POI中groupRow的功能。

**Comment by wuxjNo1** [comment]
EasyExcel.write(out)
                .head(excelHeadList)
                .inMemory(true) // **inMemory 很关键**
                .sheet("sheet1")
                .registerWriteHandler(new AbstractRowWriteHandler() {
                    @Override
                    public void afterRowCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Row row, Integer relativeRowIndex, Boolean isHead) {
                        if (relativeRowIndex==excelDataList.size()-1){
                            Sheet sheet = writeSheetHolder.getSheet();
                            sheet.groupRow(6,20);
                        }
                    }
                })
                .doWrite(excelDataList);
