### ISSUE TITLE
@ExcelProperty能支持到 Getter方法上吗?

### ISSUE THREAD

**Issue by jacktang** [alibaba/easyexcel#1568]
**建议先去看文档**

[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)

**建议描述**

像ActiveJDBC等一些 OR Wrapper框架并没有field, 但是有getter, 希望@ExcelPropert能支持到getter方法。另一方方面也能更好的支持virtual attributes

**Comment by jacktang** [comment]
如果标注到getter method上，需要注意什么，能给点建议吗？我想提个PR

**Comment by zhuangjiaju** [comment]
这个暂时不考虑支持。
