### ISSUE TITLE
如何读取合并单元格，在测试中的例子也没读出数据来

### ISSUE THREAD

**Issue by yuanzhou-mo** [alibaba/easyexcel#1572]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
目前仅仅支持 读取合并单元格的第一个值
