### ISSUE TITLE
使用InputStreamImageConverter无法将图片读取成流，结果是null

### ISSUE THREAD

**Issue by chenlaiqing1987** [alibaba/easyexcel#1573]
public class ImageExcelDTO implements Serializable {

    private static final long serialVersionUID = -4691788793083711462L;

    @ExcelProperty(index = 0,converter = InputStreamImageConverter.class)
    private  InputStream workerImg;

    public InputStream getWorkerImg() {
        return workerImg;
    }

    public void setWorkerImg(InputStream workerImg) {
        this.workerImg = workerImg;
    }

}

**Comment by zhuangjiaju** [comment]
请详细描述您的问题

**Comment by chenlaiqing1987** [comment]
myExcel have a image and I want to read it to inputstream,my dto is above但是执行以下的方法无法获取图片输入流 
![image](https://user-images.githubusercontent.com/26426653/114662241-ec163e00-9d2a-11eb-9bba-070e4dbca430.png)

public final class ImageReadUtil {
    public static void main(String[] args) {
        EasyExcel.read(new File("D:\\Users\\admin\\Desktop\\excel.xls"),ImgExcelDTO.class,new ImgTestListener()).sheet(0).doRead();
    }
}

public class ImgTestListener extends AnalysisEventListener <ImageExcelDTO> {
    private List<ImgExcelDTO> imgExcelDTOS=new ArrayList<>();

    @Override
    public void invoke(ImgExcelDTO imgExcelDTO, AnalysisContext analysisContext) {
        imgExcelDTOS.add(imgExcelDTO);
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext analysisContext) {
        System.out.println(imgExcelDTOS);
    }
}

**Comment by lethal233** [comment]
@zhuangjiaju @chenlaiqing1987 这个bug的问题在于图片不是嵌入单元格内的，easyexcel是把图片浮于单元格之上的，所以压根就读不到单元格内的数据。
wps可以将图片嵌入单元格（Microsoft excel不行），但是easyexcel读取的时候会出问题，这是wps的锅，放到excel里面是显示不出来图片的。
当然，easyexcel写图片是没问题的，读图片是读不了的。
