### ISSUE TITLE
导出对象如果是内部类对象会多出一列 this$0

### ISSUE THREAD

**Issue by SpinSi** [alibaba/easyexcel#1574]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
easyexcel/src/test/java/com/alibaba/easyexcel/test/demo/web/WebTest.java 
内部的 DownLoadData.java 改成内部类就可以复现

**触发Bug的代码**
/**
     * 文件下载（失败了会返回一个有部分数据的Excel）
     * <p>
     * 1. 创建excel对应的实体对象 参照{@link DownloadData}
     * <p>
     * 2. 设置返回的 参数
     * <p>
     * 3. 直接写，这里注意，finish的时候会自动关闭OutputStream,当然你外面再关闭流问题不大
     */
    @GetMapping("download")
    public void download(HttpServletResponse response) throws IOException {
        // 这里注意 有同学反应使用swagger 会导致各种问题，请直接用浏览器或者用postman
        response.setContentType("application/vnd.ms-excel");
        response.setCharacterEncoding("utf-8");
        // 这里URLEncoder.encode可以防止中文乱码 当然和easyexcel没有关系
        String fileName = URLEncoder.encode("测试", "UTF-8").replaceAll("\\+", "%20");
        response.setHeader("Content-disposition", "attachment;filename*=utf-8''" + fileName + ".xlsx");
        EasyExcel.write(response.getOutputStream(), DownloadData.class).sheet("模板").doWrite(data());
    }
如图示
![image](https://user-images.githubusercontent.com/12402442/93315135-430f6f80-f83d-11ea-9135-2be79409027e.png)

**提示的异常或者没有达到的效果**

**Comment by KID0031** [comment]
您好，我们对这个issue比较感兴趣，希望能尝试解决它

**Comment by zhuangjiaju** [comment]
使用新版本
