### ISSUE TITLE
@ContentStyle注解的dataFormat，除了内建的BuiltinFormats格式之外，是否支持自定义格式呢

### ISSUE THREAD

**Issue by Accright** [alibaba/easyexcel#1578]
目前有需求需要通过自定义dataFormat格式实现，但是@ContentStyle注解的dataFormat，除了内建的BuiltinFormats格式之外，无法支持，目前的最新版本是否有办法支持自定义dataFormatString呢

**Comment by Accright** [comment]
已找到办法，在CellWriteHandler中覆盖dataFormat即可，对于自定义的dataFormat，如果符合格式，可以使用DataFormat#getFormat实现

**Comment by shanfeiyang** [comment]
> 



> 已找到办法，在CellWriteHandler中覆盖dataFormat即可，对于自定义的dataFormat，如果符合格式，可以使用DataFormat#getFormat实现

请问一下怎么覆盖dataFormat，看了下代码传入的dataFormat最终也是读取内置BuiltinFormats中的格式

**Comment by wangtian076** [comment]
> > 
> 
> > 已找到办法，在CellWriteHandler中覆盖dataFormat即可，对于自定义的dataFormat，如果符合格式，可以使用DataFormat#getFormat实现
> 
> 请问一下怎么覆盖dataFormat，看了下代码传入的dataFormat最终也是读取内置BuiltinFormats中的格式

![image](https://github.com/alibaba/easyexcel/assets/9692429/454f97b0-c4c0-4c23-965f-bb5a19c019a5)
