### ISSUE TITLE
从阿里Oss下载的excel inputStream解析bug

### ISSUE THREAD

**Issue by MrWangSoul** [alibaba/easyexcel#1582]
**触发场景描述**
我的excel内列行数比实体多两行
将Excel文件上传到oss后从Oss下载获取InputStream后未能按照我的注解value进行解析，而是根据excel列顺序逐个映射实体类字段(默认通过index了？)，导致ExcelDataConvertException
但是上传文件不上传oss直接解析是没有问题的，方法是同一个
**触发Bug的代码**
```java
 //根据路径从阿里云Oss下载Excel文件
 InputStream inputStream = fileUpload.downloadExcel(entity.getFileUrl());

List<ProductInfoDTO> list;
try {
   list = EasyExcel.read(inputStream).head(ProductInfoDTO.class).sheet().doReadSync();
   logger.info("convert ExcelImport success");
 } catch (Exception e) {
 }

//实体注解全采用设置value值映射，未设置index混用
for example:
@ExcelProperty("*商品名称")
@ExcelProperty("*品牌名称")
、、
```
**提示的异常或者没有达到的效果**
c.h.e.s.factory.ProductInfoConsumer      : convert ExcelImport error!,message:com.alibaba.excel.exception.ExcelDataConvertException: Convert data WWW192281A301AA54 to int error

如果是直接上传文件解析是可以通过注解的value映射到excel内的列解析成实体的
但是上传文件后上传到oss再下载解析就未按照@ExcelProperty的value进行解析

**Comment by MrWangSoul** [comment]
产生错误代码截图
<img width="801" alt="image" src="https://user-images.githubusercontent.com/23009670/93670447-027a5500-face-11ea-87bc-2cbc84ea61b6.png">
相同excel直接上传解析成功代码截图
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/23009670/93670464-23db4100-face-11ea-83f2-50dd80a4e8cb.png">

**Comment by zhuangjiaju** [comment]
WWW192281A301AA54 这个数据 不能用int 接收
