### ISSUE TITLE
通过ExcelWriterBuilder的excludeColumnIndexes方法排除指定的索引的列有问题，中间会空出很多列，希望告知正确的排除方式！

### ISSUE THREAD

**Issue by Reed-Young** [alibaba/easyexcel#1586]
版本2.2.6
如题，自己跟代码进去后发现ClassUtils 类的declaredFields方法：
    public static void declaredFields(Class clazz, Map<Integer, Field> sortedAllFiledMap,
        Map<Integer, Field> indexFiledMap, Map<String, Field> ignoreMap, Boolean convertAllFiled,
        Boolean needIgnore, Holder holder) {
        FieldCache fieldCache = getFieldCache(clazz, convertAllFiled);
        if (fieldCache == null) {
            return;
        }
        if (ignoreMap != null) {
            ignoreMap.putAll(fieldCache.getIgnoreMap());
        }
        Map<Integer, Field> tempIndexFildMap = indexFiledMap;
        if (tempIndexFildMap == null) {
            tempIndexFildMap = new TreeMap<Integer, Field>();
        }
        tempIndexFildMap.putAll(fieldCache.getIndexFiledMap());

        if (!needIgnore) {
            sortedAllFiledMap.putAll(fieldCache.getSortedAllFiledMap());
            return;
        }

        int index = 0;
        for (Map.Entry<Integer, Field> entry : fieldCache.getSortedAllFiledMap().entrySet()) {
            Field field = entry.getValue();
            if (((WriteHolder) holder).ignore(entry.getValue().getName(), entry.getKey())) {
                if (ignoreMap != null) {
                    ignoreMap.put(field.getName(), field);
                }
                while (tempIndexFildMap.containsKey(index)) {
                    tempIndexFildMap.remove(index);
                    index++;
                }
            } else {
                sortedAllFiledMap.put(index, field);
                index++;
            }
        }
    }
其中的下面这部分代码，在设置了排除指定的字段时，会导致索引一直循环增加到最大索引，然后再继续递增处理下一个表头字段
 while (tempIndexFildMap.containsKey(index)) {
                    tempIndexFildMap.remove(index);
                    index++;
 }
不知道是不是我其他一些设置没有进行设置，希望告知正确的排除字段的方式！

**Comment by Reed-Young** [comment]
导出的Excel效果如图

**Comment by zhuangjiaju** [comment]
使用  order 而不是index
