### ISSUE TITLE
多行表头设置单元格居左失效

### ISSUE THREAD

**Issue by zhangfanwen007** [alibaba/easyexcel#1591]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
自定义静态双行表头：

@Data
public class ClassTemplate {

    @ExcelIgnore
    private String id;

    @ExcelProperty(value = {**Constants.IMPORT_TEMPLATE_NOTES_CLASS**, "所属班级(必填，唯一)"}, index =
            Constants.CLASS_COLUMN_CLASS_CODE)
    @ExcelStyle(width = 24*256)
    private String classCode;

    @ExcelProperty(value = {**Constants.IMPORT_TEMPLATE_NOTES_CLASS**, "班级名称(必填)"}, index =
            Constants.CLASS_COLUMN_CLASS_NAME)
    private String className;
}
继承CellWriteHandler并在afterCellDispose中设置首行居左。

    @Override
    public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, List<CellData> cellDataList, Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {

        if (0 == cell.getRowIndex()) {
            log.info("<afterCellDispose> in head1, rowIndex:{}", cell.getRowIndex());
            Sheet sheet = writeSheetHolder.getSheet();
            Workbook workbook = writeSheetHolder.getSheet().getWorkbook();

            // 设置列宽
            sheet.setColumnWidth(cell.getColumnIndex(), Constants.IMPORT_TEMPLATE_DESC_WIDTH);
            // 设置行高
            sheet.getRow(head1).setHeight(Constants.IMPORT_TEMPLATE_DESC_HEIGHT);

            // 每次cell的渲染复用同一个CellStyle
            if (cellStyleHead1 == null) {
                WriteCellStyle headWriteCellStyle = new WriteCellStyle();
                // 设置垂直居中为居中对齐
                headWriteCellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
                // 设置左右对齐为靠左对齐
                **headWriteCellStyle.setHorizontalAlignment(HorizontalAlignment.LEFT);**
                cellStyleHead1 = StyleUtil.buildHeadCellStyle(workbook, headWriteCellStyle);
            }
            cell.setCellStyle(cellStyleHead1);
}
}

```
**提示的异常或者没有达到的效果**
首行没有居左。
![图片](https://user-images.githubusercontent.com/71801619/94091446-d7d02980-fe4a-11ea-977e-48727b4944ac.png)

**Comment by zhuangjiaju** [comment]
建议直接用注解

**Comment by yyangdr** [comment]
> 

使用什么注解能让多行头的第一行居左？

**Comment by topsuder** [comment]
我也想知道
