### ISSUE TITLE
doReadSync读取excel时，可以获取数据的行号吗

### ISSUE THREAD

**Issue by liubin95** [alibaba/easyexcel#1593]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
获取到list，我需要获取数据对应的行号。以便返回错误信息

**Comment by zhuangjiaju** [comment]
上下文中有。

**Comment by fg6a5gf** [comment]
> **建议先去看文档** [快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq) **建议描述** 获取到list，我需要获取数据对应的行号。以便返回错误信息

先继承AnalysisEventListener，然后可以通过context.readRowHolder().getRowIndex()获取到

代码示例：

```
@Slf4j
public class RowIndexListener implements ReadListener<Object> {

    @Override
    public void invoke(Object data, AnalysisContext context) {
        log.info(context.readRowHolder().getRowIndex())
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
    }
}
```



版本：3.0.5
