### ISSUE TITLE
使用模板execl填充，如果对象的数据集合里存在某些对象属性值为null，会报空指针异常

### ISSUE THREAD

**Issue by zjzlq** [alibaba/easyexcel#1597]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
  使用模板execl填充，如果对象的数据集合里存在某些对象属性值为null，会报空指针异常
**触发Bug的代码**
```java
   ConverterKeyBuild.buildKey(clazz)
```
**提示的异常或者没有达到的效果**

**Comment by KID0031** [comment]
您好，请问可以贴一下完整的代码么(我在填充时并未出现空指针异常)以及我们希望尝试解决这个bug
