### ISSUE TITLE
实体使用了lombok的链式编程注解 @Accessors(chain = true) 导入时全null

### ISSUE THREAD

**Issue by xunkoo** [alibaba/easyexcel#1598]
如题，Listener 的 invoke方法读取到的都是null

**Comment by pdkst** [comment]
`@Accessors(chain = true)`会导致lombok不会生成标准**getter/setter**，

但是EasyExcel对属性的赋值依赖目标对象的**getter/setter**，

所以，改用`@Builder`可以相对兼容
