### ISSUE TITLE
使用EasyExcel.write()导出表格时,内容有空格的,空格会丢失

### ISSUE THREAD

**Issue by daweizi310** [alibaba/easyexcel#1599]
使用EasyExcel.write()导出表格时,内容有空格的,空格会丢失,,请问表格中有空格,特别是单元格内容的最后是空格的,会丢失,怎么解决

**Comment by huangxinchao-work** [comment]
请问解决了吗，我现在也遇到了同样的问题，有没有什么好的解决方式。

**Comment by JuvenileQ** [comment]
.autoTrim(false) 该方法默认为true，修改为false试试
