### ISSUE TITLE
web导出Excel，浏览器报错“无法访问此网站 ERR_INVALID_RESPONSE”

### ISSUE THREAD

**Issue by zhang0107** [alibaba/easyexcel#1601]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
// 这里注意 有同学反应使用swagger 会导致各种问题，请直接用浏览器或者用postman
        response.setContentType("application/vnd.ms-excel");
        response.setCharacterEncoding("utf-8");
        // 这里URLEncoder.encode可以防止中文乱码 当然和easyexcel没有关系
        String fileName = URLEncoder.encode("测试", "UTF-8").replaceAll("\\+", "%20");
        response.setHeader("Content-disposition", "attachment;filename*=utf-8''" + fileName + ".xlsx");
        EasyExcel.write(response.getOutputStream(), DownloadData.class).sheet("模板").doWrite(data());
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**
无法访问此网站网址为 。。。。。。。。。。。。。。 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_INVALID_RESPONSE

**Comment by zhuangjiaju** [comment]
这个需要查看自己原因
