### ISSUE TITLE
demo 中的ExcelListener有bug 

### ISSUE THREAD

**Issue by fangjilue** [alibaba/easyexcel#161]
public class ExcelListener extends AnalysisEventListener {

    private List<Object>  data = new ArrayList<Object>();

    @Override
    public void invoke(Object object, AnalysisContext context) {
        System.out.println(context.getCurrentSheet());
       data.add(object); //不管是否满足一页数据都加入，不然demo中会丢掉一条数据
        if(data.size()>100){
            doSomething();
            data = new ArrayList<Object>();
        }
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
        doSomething();
    }
    public void doSomething(){
        for (Object o:data) {
            System.out.println(o);
        }
    }
}

**Comment by jipengfei-jpf** [comment]
doAfterAllAnalysed 会把其余没处理的处理掉
