### ISSUE TITLE
我尝试在Android studio使用2.2.6，提示xmlbeans重复

### ISSUE THREAD

**Issue by ZhangTengCR7** [alibaba/easyexcel#1612]
这是POI库的问题，请问怎么解决。

**Comment by tanbo091** [comment]
我这边是引入正确的 依赖，然后让 easy excel 去移除相应的依赖。
例如我当时，因为 xmlBean出错，所以引入自己的xmlBean，然后 easy excel 移除对应的xml bean

**Comment by zhuangjiaju** [comment]
这个不太清楚 解决了记得分享下。
