### ISSUE TITLE
请问为什么无法导出指定容量的List？

### ISSUE THREAD

**Issue by hjs557523** [alibaba/easyexcel#1615]
您好，请问下为什么EasyExcel不支持导出指定容量的List数据，像这样：List<XXX> list = new ArrayList<100>();，

**Comment by pdkst** [comment]
因为指定容量是`List<DemoData> list = new ArrayList<>(100);`......

EasyExcel导出的是list的内容，list的容量为100，但是内容为空

碗再大也不能让我吃饱，因为碗里面没有饭
