### ISSUE TITLE
在读Excle的时，重写的方法中手动抛出异常 最后会转换成ExcelAnalysisException

### ISSUE THREAD

**Issue by baijuexzz** [alibaba/easyexcel#1617]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
