### ISSUE TITLE
读取Excel时Exception处理方式是否合理

### ISSUE THREAD

**Issue by firekirin67** [alibaba/easyexcel#1618]
在读取Excel的时候 自定义AnalysisEventListener内抛出定义异常后被XlsxSaxAnalyser.parseXmlSource()内的异常处理再次封装成 ExcelAnalysisException 
catch (Exception e) {
            throw new ExcelAnalysisException(e);
}
这样设计是否合理?导致无法正确的捕捉异常,虽然可以通过instanceof等方式去处理

**Comment by zhuangjiaju** [comment]
后续版本修复
