### ISSUE TITLE
希望增加指定行和列写入数据功能

### ISSUE THREAD

**Issue by zheng6789** [alibaba/easyexcel#1619]
**建议描述**
不可能都通过表头或者变量这种填充写入。excel是写了vbs校验的，不能在写入的地方设置变量，写入的值也做了校验的。表头更不可能写了 类似简历格式，希望增加指定行和列写入。灵活度更高

**Comment by weizhiwen** [comment]
我也觉得这个功能很有必要增加

**Comment by zhuangjiaju** [comment]
请使用填充。指定行的话 建议自定义拦截器。可以操作poi

**Comment by yzstu** [comment]
> 请使用填充。指定行的话 建议自定义拦截器。可以操作poi

确实很期待能够支持按行和列写入数据

**Comment by Wiilz** [comment]
> excel是写了vbs校验的，不能在写入的地方设置变量，写入的值也做了校验的。

遇到了同样这种情况，希望支持增加坐标写入的方式

**Comment by ccx0lw** [comment]
可以自己实现，指定坐标
Row row = excelWriter.writeContext().writeSheetHolder().getCachedSheet().getRow(行);
row.createCell(列).setCellValue(数据);
