### ISSUE TITLE
java.lang.NoClassDeffoundError:org/ehcache/config/builders/CacheManagerBuilder

### ISSUE THREAD

**Issue by zk0019928** [alibaba/easyexcel#1626]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
当使用时 excel文件条数 大于10万的时候就会出现这个java.lang.NoClassDeffoundError:org/ehcache/config/builders/CacheManagerBuilder，问题
**建议描述**

**Comment by zhuangjiaju** [comment]
`ehcache`版本错误
