### ISSUE TITLE
可以自定义表头吗(动态表头)

### ISSUE THREAD

**Issue by globalbirdjoingithub** [alibaba/easyexcel#163]

**Comment by SnakeTom** [comment]
同问，我们表头都是可配置的生成的。

**Comment by mingjia-vip** [comment]
对，动态表头怎么设置

**Comment by linavv1** [comment]
同问，在导出时，表头不是固定的，列数都不固定，可能需要合并，

**Comment by duhonglei520** [comment]
同问 动态表头要怎么设置

**Comment by jianhh** [comment]
可以用javaassist动态生成model

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写

**Comment by jianhh** [comment]
还是有问题哦，我改了一下代码，你看一下：





------------------ 原始邮件 ------------------
发件人: "Jiaju Zhuang"<notifications@github.com>;
发送时间: 2019年8月28日(星期三) 晚上7:19
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "小灰灰"<52285084@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 可以自定义表头吗(动态表头) (#163)




这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
