### ISSUE TITLE
EasyExcel中的writer和fill不支持流式写入outputStream么

### ISSUE THREAD

**Issue by ZWMdarker** [alibaba/easyexcel#1633]
使用easyExcel的writer或者fill的时候，不能配合chunked进行分块的导出。这块有什么好的解决办法么？
看了一下源码好像是在finish方法中才把整体处理完才写入outputStream，这样的话如何减少的内存消耗呢？有熟悉源码的大神解释下么。。。
            response.setContentType("application/octet-stream");
            response.setCharacterEncoding("utf-8");
            String fileName = URLEncoder.encode("aaa"+".xlsx", "utf-8");
            response.addHeader("Content-Disposition", "attachment;filename=" + fileName);
            response.addHeader("Transfer-Encoding", "chunked");
            outputStream= response.getOutputStream();
            Long startTime = System.currentTimeMillis();
            Long endTime = startTime;
            ExportCreditorExcelDto exportCreditorExcelDto1 = JSON.parseObject("{\"composition\":\"双方同时\",\"creditorIdNum\":\"110101199002071195\",\"creditorName\":\"个人测试69\",\"creditorTypeFlag\":\"个人\",\"grzqrSjhm\":\"86-11111111222\",\"grzqrXm\":\"test12\",\"grzqrZjhm\":\"1111\",\"testFlag\":\"否\",\"userNo\":\"111\",\"voteFlag\":\"否\",\"wtdlrSjhm\":\"15810682229\",\"wtdlrXm\":\"zcw2\",\"wtdlrZjhm\":\"2102234444\"}",ExportCreditorExcelDto.class);
            ExcelWriter excelWriter = EasyExcel.write(outputStream,ExportCreditorExcelDto.class).build();
            WriteSheet writeSheet = EasyExcel.writerSheet("模板").build();
            int i=0;
            while (endTime-startTime<10*60*1000L){ 
                log.info("第"+i+"次写入");
                i++;
//                outputStream.write(testString.getBytes());
//                outputStream.flush();
                excelWriter.write(Arrays.asList(exportCreditorExcelDto1),writeSheet);
                outputStream.flush();
                Thread.sleep(10*1000L);
                endTime = System.currentTimeMillis();
            }
            excelWriter.finish();

**Comment by pdkst** [comment]
excel你可以把它当成压缩的xml，只有写入完成才能压缩

**Comment by zhuangjiaju** [comment]
数据临时存储成xml的 ，最后统一转成流。
