### ISSUE TITLE
POI版本兼容问题

### ISSUE THREAD

**Issue by grayxk** [alibaba/easyexcel#1634]
本地poi版本引入的是4.1.0，今天试了一下读取方法，报错：java.lang.NoSuchMethodError: org.apache.poi.poifs.filesystem.DirectoryNode.getFileSystem()Lorg/apache/poi/poifs/filesystem/NPOIFSFileSystem;

请问在不动poi版本的情况下，有什么解决方法吗？

**Comment by babyface23484** [comment]
如何解决
