### ISSUE TITLE
请问easyexcel是否可以不实现定义描述类，直接通过填充行列的方式生成xlsx文件

### ISSUE THREAD

**Issue by praynise** [alibaba/easyexcel#1635]
我的场景是需要通过执行SQL，并将结果导出EXCEL。由于SQL经常会发生调整和变化，通过实现定义类的方式输出excel不够灵活，请问是否可以像POI一样，通过操作行列的方式，直接生成xlsx文件呢？在文档中并未找到相应的方法，烦请作者或其他朋友提示，非常感谢

**Comment by zhuangjiaju** [comment]
参照不创建对象的写
