### ISSUE TITLE
麻烦保留正式版本的分支！！

### ISSUE THREAD

**Issue by curtiscai** [alibaba/easyexcel#164]
首先感谢开源EasyExcel的代码，解析大量Excel数据时内存占用解析效率方便都有很大的优势，之前使用过程中虽然会有些BUG，但是修复了很多，但是请保留正式版本的分支，今天看到只保留了了beta版本，我想使用正式的版本已经找不到相应的test和sample，阿里是个伟大的公司，也希望任何发布在仓库中的开源项目能有负责的态度

**Comment by zhuangjiaju** [comment]
正式版会在1个月内 发布。目前需要再收集下意见
