### ISSUE TITLE
图片导出是否能加边距，使图片距离单元格边缘有一点空隙

### ISSUE THREAD

**Issue by zxiaozhou** [alibaba/easyexcel#1641]
1. 图片导出能否支持通过一个注解配置完全填充与有一定边距的填充。
2. 现在图片导出都是完全填充，特别是单元格还有边框的那种，完全填充边框都覆盖了很不好看。。。

### 两种样式如下
1. 有边距的(好看多了，能看见单元格边框)
![image](https://user-images.githubusercontent.com/62740686/97837431-2362d680-1d19-11eb-99b9-04aa2873484f.png)

2. 无边距的(一大片，看不见单元格边框,很慢看)
![image](https://user-images.githubusercontent.com/62740686/97837439-28278a80-1d19-11eb-8ffe-d0451f99f0ec.png)

**Comment by lethal233** [comment]
尝试在`src/main/java/com/alibaba/excel/write/executor/AbstractExcelWriteExecutor.java`中手动调整一下 @zxiaozhou

**Comment by zxiaozhou** [comment]
> 尝试在`src/main/java/com/alibaba/excel/write/executor/AbstractExcelWriteExecutor.java`中手动调整一下 @zxiaozhou

谢谢，，我先试下，，但是官方估计还是得提供一个统一优雅的加进方案比较合适些

**Comment by garbage-rubbish** [comment]
请问解决了嘛？怎么解决的

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
然后参照：https://www.yuque.com/easyexcel/doc/write#cb1b271f
