### ISSUE TITLE
1、Data对象的属性命名不能首字母大写 2、属性名大小写不区分 同字母数据相同

### ISSUE THREAD

**Issue by RUAN-ZX** [alibaba/easyexcel#1642]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
这个暂时性不会去解决 请使用驼峰命名
