### ISSUE TITLE
自定义合并单元格策略并且使用动态表头，自定义合并单元格策略失效

### ISSUE THREAD

**Issue by FuPingstar** [alibaba/easyexcel#1643]
自定义合并单元格策略并且使用动态表头，自定义合并单元格策略失效

            EasyExcel.write(response.getOutputStream(), PbExportData.class).head(dynamicHeadTittle("2020")).autoCloseStream(Boolean.FALSE)
                    .registerWriteHandler(horizontalCellStyleStrategy)
                    .registerWriteHandler(new PbCustomerMergeStrategy(strategyMap))
                    .sheet("sheet1")
                    .doWrite(exportDatas);

**Comment by zhuangjiaju** [comment]
贴全代码

**Comment by zhuangjiaju** [comment]
是否已经解决了问题？
