### ISSUE TITLE
extra.getText() 无法获取合并单元格的内容

### ISSUE THREAD

**Issue by loncool** [alibaba/easyexcel#1645]
@Override
    public void extra(CellExtra extra, AnalysisContext context) {
     //这里，当extra.getType() == MERGE的时候， 执行extra.getText() 无法获取合并单元格的内容。
   }

**Comment by zhuangjiaju** [comment]
仅仅只有第一个单元格才能获取到合并的内容

**Comment by viccP** [comment]
Excel的XML描述中对于合并单元格只有下述类似的表达：
` <mergeCells count="323">`
        `<mergeCell ref="D1657:D1661"/>`
......
`</mergeCells>`
在easyexcel的hanlder中可以看到
`  @Override`
`   public void startElement(XlsxReadContext xlsxReadContext, String name, Attributes attributes) {`
`        String ref = attributes.getValue(ExcelXmlConstants.ATTRIBUTE_REF);`
`        if (StringUtils.isEmpty(ref)) {`
`            return;`
`        }`
`        CellExtra cellExtra = new CellExtra(CellExtraTypeEnum.MERGE, null, ref);`
`        xlsxReadContext.readSheetHolder().setCellExtra(cellExtra);`
`        xlsxReadContext.analysisEventProcessor().extra(xlsxReadContext);`
`    }`
在CellExtra 初始化的时候text给的是null，目前看起来这个合并区域的文本并不能从attributes中获取到，所以这是个问题
