### ISSUE TITLE
BigDecimal数据类型，NumberFormat的Annotation格式化后导出的Excel的单元格不是数字格式

### ISSUE THREAD

**Issue by guyinsheng** [alibaba/easyexcel#1646]
**触发场景描述**
版本：2.2.6
BigDecimal数据类型，NumberFormat的Annotation格式化后导出的Excel的单元格不是数字格式。

**触发Bug的代码**
```java
    @ExcelProperty(value = "2月含税总金额（元）", index = 5)
    @NumberFormat("#,##0.00")
    private BigDecimal totalAmountMonth02;
```
**提示的异常或者没有达到的效果**
从单元格的数据上来看，即为左对齐，且左上角有绿色的标识。
导出的文件用Excel编辑时，该列使用SUM函数，不能正确计算，计算结果都是0。

巧合的是，我把代码的Annotation改成@DateTimeFormat("#,##0.00")，
导出的结果可以达到预期，即为数字右对齐，且左上角没有绿色标识，
并且Excel软件进行编辑时，可以使用SUM的函数正确计算。

**Comment by linhaihai** [comment]
这摸久了还没解决bug？

**Comment by Sokasa** [comment]
。。这个解决了吗？ 或者有替代方案？

**Comment by lethal233** [comment]
我这边测试的没有问题= =，如果还有问题能提供一下 实体类，Junit代码和生成的excel吗？我可以尝试解决这个问题 @linhaihai @Sokasa @guyinsheng

**Comment by KID0031** [comment]
可以在转换完NumberFormat之后将celldata改为数字类型

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
