### ISSUE TITLE
是否能获取到根据模板文件中定义的填充字段名的相关映射关系，例如我定义了一个{id}，通过easyExcel的方法可以获取到这个{id}的坐标位置（第几行第几列），在第几个sheet的数据

### ISSUE THREAD

**Issue by wushengxin** [alibaba/easyexcel#1652]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
是否能获取到根据模板文件中定义的填充字段名的相关映射关系，例如我定义了一个{id}，通过easyExcel的方法可以获取到这个{id}的坐标位置（第几行第几列），在第几个sheet的数据

**Comment by zhuangjiaju** [comment]
目前不支持。
