### ISSUE TITLE
为什么不把poi版本升级到4.x呢？

### ISSUE THREAD

**Issue by imic07** [alibaba/easyexcel#1653]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
如题。

**Comment by wangzihaogithub** [comment]
我也遇到了, 项目中同时用到了其他开源软件, 他们需要的poi版本是4.x , 导致不能和easy-excel同时使用

**Comment by zhuangjiaju** [comment]
直接升级4.12就行
