### ISSUE TITLE
只读取指定的行数的数据，但是希望最后能得到合并单元格等信息

### ISSUE THREAD

**Issue by wyctxwd1** [alibaba/easyexcel#1654]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
com.alibaba.excel.analysis.v07.handlers.AbstractXlsxTagHandler#support
希望在这边也能提供一个api出来设置，至少在运行时能设置，以便于跳过解析cell，但是不跳过解析extraData

**Comment by zhuangjiaju** [comment]
这个无法解决。在文件存储的时候 无法读取过来。

**Comment by wyctxwd1** [comment]
你好
其实是可以做到，原先已经提供了support希望可以在运行时把support设置成false即可，这样数据部分的标签可以跳过不解析
不知道能否提供这样一个参数







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 只读取指定的行数的数据，但是希望最后能得到合并单元格等信息 (#1654)





 
这个无法解决。在文件存储的时候 无法读取过来。
