### ISSUE TITLE
Beanmap

### ISSUE THREAD

**Issue by syzbiaoren** [alibaba/easyexcel#1657]
https://user-images.githubusercontent.com/55923514/98903716-1c934b00-24f3-11eb-8494-79b9f40fd011.png
https://user-images.githubusercontent.com/55923514/98903816-451b4500-24f3-11eb-8d1b-b38b1025c4e9.png

如果导出的集合是map,你们的BeanMap 却不能获取该集合的数据，这是很常用的类型啊。

**Comment by zhuangjiaju** [comment]
新版本会支持 `Map<Integer,Object>`

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
