### ISSUE TITLE
最新版本2.2.6使用BigDecimal接收小数导致溢出

### ISSUE THREAD

**Issue by Kunxian615** [alibaba/easyexcel#1658]
**触发场景描述**
使用BigDecimal读取小数导致溢出
**触发Bug的代码**
List<Object> objects = EasyExcel.read("testxiaoshu.xlsx")
            .head(DemoData.class).sheet().doReadSync();

```java
@Data
public class DemoData {
    @ExcelProperty("字符串标题")
    private String string;
    @ExcelProperty("日期标题")
    private Date date;
    @ExcelProperty("数字标题")
    private BigDecimal doubleData;
}
List<Object> objects = EasyExcel.read("testxiaoshu.xlsx")
            .head(DemoData.class).sheet().doReadSync();
```
**提示的异常或者没有达到的效果**
![image](https://user-images.githubusercontent.com/33412590/98913905-f4abe380-2502-11eb-846c-f03f93f98f2e.png)
![image](https://user-images.githubusercontent.com/33412590/98913987-0db49480-2503-11eb-840d-1757bb6fac56.png)
[testxiaoshu.xlsx](https://github.com/alibaba/easyexcel/files/5529133/testxiaoshu.xlsx)

**Comment by zhsongGithub** [comment]
您好，请问您这个问题解决了吗？

**Comment by Kunxian615** [comment]
> 您好，请问您这个问题解决了吗？

没有，只能等作者修改bug；
上传的excel单元格式必须为文本格式，上传才不会溢出

**Comment by zhuangjiaju** [comment]
这个无法解决。要么用文本接收，要么自己用数字接收转换。

**Comment by Kunxian615** [comment]
我在公司内网用double接收也会溢出

**Comment by Kunxian615** [comment]
> 这个无法解决。要么用文本接收，要么自己用数字接收转换。

你好，我在公司内网用double接收也会溢出；如果用String接收，当前excel单元格是数字类型，并且有隐藏长度，接收到的值，是隐藏后的值；

**Comment by 350845110** [comment]
这个问题我也遇到的。我用的是2.27版本的
