### ISSUE TITLE
与springboot集成时，excel实体使用@lombok注解会冲突 导致监听类获取数据为null

### ISSUE THREAD

**Issue by marc123gg** [alibaba/easyexcel#1660]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by marc123gg** [comment]
try yourself

**Comment by zhuangjiaju** [comment]
仅支持基础的get set
