### ISSUE TITLE
模板填充导出的时候出现空指针异常

### ISSUE THREAD

**Issue by lq1448061208** [alibaba/easyexcel#1663]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
web端点击触发后端代码,到了`excelWriter.fill(new FillWrapper("data1", data),fillConfig,writeSheet);`这里就直接报出空指针
**触发Bug的代码**
```java
   String templateFileName = EasyExcelUtil.getPath() + "templates" + File.separator + "dome.xlsx";
            ExcelWriter excelWriter = EasyExcel.write("数据.xlsx").withTemplate(templateFileName).build();
            WriteSheet writeSheet = EasyExcel.writerSheet().build();
            FillConfig fillConfig= FillConfig.builder().direction(WriteDirectionEnum.HORIZONTAL).build();


            excelWriter.fill(new FillWrapper("data1", hourReports),fillConfig,writeSheet);
            excelWriter.fill(new FillWrapper("data1", hourReports),fillConfig,writeSheet);
            excelWriter.fill(new FillWrapper("data2", dayReportList), writeSheet);
            excelWriter.fill(new FillWrapper("data2", dayReportList), writeSheet);
            excelWriter.fill(new FillWrapper("data3", supplierReports), writeSheet);
            excelWriter.fill(new FillWrapper("data3", supplierReports), writeSheet);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("date", date);
            excelWriter.fill(map, writeSheet);

            // 别忘记关闭流
            excelWriter.finish();
```
**提示的异常或者没有达到的效果**
java.lang.NullPointerException
	at com.alibaba.excel.write.executor.ExcelWriteFillExecutor.doFill(ExcelWriteFillExecutor.java:191)
	at com.alibaba.excel.write.executor.ExcelWriteFillExecutor.fill(ExcelWriteFillExecutor.java:118)
	at com.alibaba.excel.write.ExcelBuilderImpl.fill(ExcelBuilderImpl.java:78)
	at com.alibaba.excel.ExcelWriter.fill(ExcelWriter.java:185)

**Comment by yangzy1029** [comment]
同问

**Comment by Fyee** [comment]
这个bug 修复了吗？

**Comment by lethal233** [comment]
请问有人在处理这个issue吗，我对这个issue感兴趣，我会在最近几个月尝试去修复这个bug。 @zhuangjiaju

**Comment by Albert1881** [comment]
我分析了这个bug出现的可能原因，并提出交了pull request。不知道是否能满足需求修复bug？ @zhuangjiaju

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
