### ISSUE TITLE
在导入excel时，如果是插入数据库，有一些逻辑判断需要返回到客户端，但是看了easyexcel的导入操作，捕捉不到返回值，这个问题怎么解决？

### ISSUE THREAD

**Issue by longaili520** [alibaba/easyexcel#1665]
一个场景：假如先导入一条数据到数据库，接着误操作，又导入一次，这样的操作是不被允许的，所以做了判断，并且要把重复的数据返回到客户端，作为提示信息，但是easyexcel的监听中的方法都是void的，如果想拿到这些返回值，需要怎么操作？

**Comment by Yangqi0338** [comment]
doReadSync()?

**Comment by zhuangjiaju** [comment]
给`listener`创建一个成员变量 读取完成了获取就行

**Comment by longaili520** [comment]
> doReadSync()?

这个应该获取传入的excel数据，不是过程中处理的业务数据

**Comment by longaili520** [comment]
> 给`listener`创建一个成员变量 读取完成了获取就行

嗯，我现在按照这个思路重构一下。（注：因为我之前的监听是范型公用的，通过consumer传输数据的，这样就可以接受任何数据，consumer将数据丢给不同的表入库接口。）
