### ISSUE TITLE
如何在监听器里获得某个表头的样式信息

### ISSUE THREAD

**Issue by Yangqi0338** [alibaba/easyexcel#1667]
如题

**Comment by Yangqi0338** [comment]
![image](https://user-images.githubusercontent.com/25914993/99499710-44335900-29b4-11eb-91e6-33f56084e0ab.png)
当用户导入这个Excel的时候，我可以获取得到 第一行第一个基础的表头样式颜色为橘色

**Comment by zhuangjiaju** [comment]
目前不支持获取样式信息
