### ISSUE TITLE
单元格合并性能问题

### ISSUE THREAD

**Issue by 1010830256** [alibaba/easyexcel#1668]
使用writeBuilder.registerWriteHandler(new OnceAbsoluteMergeStrategy(startRow, endRow, startColumn, endColumn));这种方式进行单元格合并，我大概new了1200多个OnceAbsoluteMergeStrategy，导出excel的性能极差，数据总共2000多行，导出用了5分钟，如果不使用单元格合并，导出时间非常快，在1秒内就能搞定，希望能修复一下性能问题，或者提供一下其他的解决方法

**Comment by zhuangjiaju** [comment]
请使用`LoopMergeStrategy `

**Comment by Sdky** [comment]
为什么使用 OnceAbsoluteMergeStrategy 会导致导出很慢呢？
