### ISSUE TITLE
关于java model映射 excel数据显示的问题

### ISSUE THREAD

**Issue by xiaobu1994** [alibaba/easyexcel#167]
我想问下这个java model是根据什么来映射的。由于我的vo类不是按照驼峰命名规则来的。
![image](https://user-images.githubusercontent.com/44577736/49918135-f024bd80-fedc-11e8-969d-4ef40a5ee820.png)
![image](https://user-images.githubusercontent.com/44577736/49918247-4bef4680-fedd-11e8-9264-6ccb381c6956.png)

但是我指定了json字段的名称（确保vo里面的字段和json的字段的name一致），我把查询之后的数据放入excel输出但是仍然是个空的excel除了标题之外。
![image](https://user-images.githubusercontent.com/44577736/49918274-6d503280-fedd-11e8-84cb-c496269008cb.png)
但是如果我把vo里面的字段名改成驼峰规则之外，不设定json的字段名，
我这边excel就能输出从数据库查到的值 。
![image](https://user-images.githubusercontent.com/44577736/49918450-2d3d7f80-fede-11e8-99fc-e73b630aebd7.png)
![image](https://user-images.githubusercontent.com/44577736/49918457-34648d80-fede-11e8-841e-f3852fcc4874.png)
![image](https://user-images.githubusercontent.com/44577736/49918468-3dedf580-fede-11e8-92b3-20e42062f0e4.png)

**Comment by zhuangjiaju** [comment]
使用了 `cglib`的`BeanMap`创建，目前必须使用驼峰命名
