### ISSUE TITLE
同一个实体表头的写操作，写完之后将表头从缓存移除功能

### ISSUE THREAD

**Issue by xiaour** [alibaba/easyexcel#1670]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**

**场景：不发布重启应用程序的情况下，重新修改表头名称或调整顺序**

目前来说，多行表头存在一个问题，当程序初始化（导出过一次）过后，表头就缓存起来了，如果在应用持续启动的过程中我想将@ExcelProperty中的index或value重新赋值后再导出，发现不可以。希望能有一个方法，导出后自行决定是否清除当前实体表头的缓存。

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
`ClassUtils.FIELD_CACHE` 清理掉就行
