### ISSUE TITLE
A potential NPE bug

### ISSUE THREAD

**Issue by JulyChen728** [alibaba/easyexcel#1671]
Hi all,
our bug scanner has reported a NPE bug.

The variable `cell` is checked for whether being `null` at [WriteHandlerUtils.java#L161](https://github.com/alibaba/easyexcel/blob/3111cbedd0dd622cd8a5115aedf6695d9ff37b8e/src/main/java/com/alibaba/excel/util/WriteHandlerUtils.java#L161), and a NPE bug may take place in [afterCellDispose()](https://github.com/alibaba/easyexcel/blob/3111cbedd0dd622cd8a5115aedf6695d9ff37b8e/src/main/java/com/alibaba/excel/util/WriteHandlerUtils.java#L181) when it is invoked at [WriteHandlerUtils.java#L164](https://github.com/alibaba/easyexcel/blob/3111cbedd0dd622cd8a5115aedf6695d9ff37b8e/src/main/java/com/alibaba/excel/util/WriteHandlerUtils.java#L164).

Thanks.

**Comment by zhuangjiaju** [comment]
Thank you very much. This will be fixed in a later release
