### ISSUE TITLE
后端返回的实体填充的数据，可以单独生成背景色，这样的功能挺好，

### ISSUE THREAD

**Issue by mnjianglf** [alibaba/easyexcel#1672]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
参照自定义样式
