### ISSUE TITLE
写Excel时，如果一列有合并单元格时，用excel对该列求和，会重复计算

### ISSUE THREAD

**Issue by onebetters** [alibaba/easyexcel#1673]
![image](https://user-images.githubusercontent.com/37861666/99892424-aee3dd80-2caf-11eb-9cc4-9695a7ada64f.png)

**Comment by haohao1121** [comment]
我也遇到了这个问题,求解决方案

**Comment by onebetters** [comment]
> 我也遇到了这个问题,求解决方案
这个问题出现的原因是合并单元格后只是样式发生变化了，其实内部每个单元格的值都是一样的（你复制出来就会发现）
我的解决方案可能不是最好的：我是记录好每个合并单元格的索引位置，然后置空这个合并单元格其他的cell内容，只保留一个
部分代码：
`
public class MarketTradeMergeStrategy extends AbstractMergeStrategy {

    /**
     * 需要合并的列数
     */
    private Map<Integer, Field> columnMergeMap;
    /**
     * Map<行index，往下merge（合并）的行数>
     */
    private final Map<Integer, Long> mergeMap = new HashMap<>();

    /**
     * 需要清除内容的行index
     */
    private final List<Integer> blankRowList = new ArrayList<>();

    public MarketTradeMergeStrategy(@Nonnull final List<?> data, @Nonnull final Class<?> clazz) {
        List<MarketTradeExcelExportDTO> list       = (List<MarketTradeExcelExportDTO>) data;
        int                             totalRowNo = list.size() + 1;
        if (list.size() == 0) {
            return;
        }
        columnMergeMap = CustomUtils.getNeedColumnIndex(clazz, AnnotationType.MERGER);
        if (columnMergeMap.size() == 0) {
            return;
        }
        Map<String, Long> tradeMap = list.stream().collect(Collectors.groupingBy(MarketTradeExcelExportDTO::getTradeId, Collectors.counting()));
        String lastOrderNo = "";
        for (int i = 0; i < list.size(); i++) {
            String orderNo = list.get(i).getTradeId();
            if (orderNo.equals(lastOrderNo)) {
                lastOrderNo = orderNo;
                continue;
            }
            Long orderNoCount = tradeMap.get(orderNo);
            if (orderNoCount > 1) {
                mergeMap.put(totalRowNo - list.size() + i, orderNoCount - 1);
                //配合Excel求和计算，记录要清除内容的行index
                for (int j = 1; j <= orderNoCount - 1; j++) {
                    blankRowList.add(totalRowNo - list.size() + i + j);
                }
            }
            lastOrderNo = orderNo;
        }
    }

    @Override
    protected void merge(Sheet sheet, Cell cell, Head head, Integer relativeRowIndex) {
        if (columnMergeMap.containsKey(cell.getColumnIndex())) {
            if (mergeMap.containsKey(cell.getRowIndex())) {
                Long mergeCount     = mergeMap.get(cell.getRowIndex());
                int  nowRowIndex    = cell.getRowIndex();
                int  nowColumnIndex = cell.getColumnIndex();
                CellRangeAddress cellRangeAddress = new CellRangeAddress(nowRowIndex, nowRowIndex + mergeCount.intValue(), nowColumnIndex, nowColumnIndex);
                sheet.addMergedRegionUnsafe(cellRangeAddress);
            } else {
                if (blankRowList.contains(cell.getRowIndex())) {
                    cell.setCellType(CellType.BLANK);
                }
            }
        }
    }
`

**Comment by onebetters** [comment]
> 我也遇到了这个问题,求解决方案

这个问题出现的原因是合并单元格后只是样式发生变化了，其实内部每个单元格的值都是一样的（你复制出来就会发现）
我的解决方案可能不是最好的：我是记录好每个合并单元格的索引位置，然后置空这个合并单元格其他的cell内容，只保留一个
部分代码：
`
public class MarketTradeMergeStrategy extends AbstractMergeStrategy {

    /**
     * 需要合并的列数
     */
    private Map<Integer, Field> columnMergeMap;
    /**
     * Map<行index，往下merge（合并）的行数>
     */
    private final Map<Integer, Long> mergeMap = new HashMap<>();

    /**
     * 需要清除内容的行index
     */
    private final List<Integer> blankRowList = new ArrayList<>();

    public MarketTradeMergeStrategy(@Nonnull final List<?> data, @Nonnull final Class<?> clazz) {
        List<MarketTradeExcelExportDTO> list       = (List<MarketTradeExcelExportDTO>) data;
        int                             totalRowNo = list.size() + 1;
        if (list.size() == 0) {
            return;
        }
        columnMergeMap = CustomUtils.getNeedColumnIndex(clazz, AnnotationType.MERGER);
        if (columnMergeMap.size() == 0) {
            return;
        }
        Map<String, Long> tradeMap = list.stream().collect(Collectors.groupingBy(MarketTradeExcelExportDTO::getTradeId, Collectors.counting()));
        String lastOrderNo = "";
        for (int i = 0; i < list.size(); i++) {
            String orderNo = list.get(i).getTradeId();
            if (orderNo.equals(lastOrderNo)) {
                lastOrderNo = orderNo;
                continue;
            }
            Long orderNoCount = tradeMap.get(orderNo);
            if (orderNoCount > 1) {
                mergeMap.put(totalRowNo - list.size() + i, orderNoCount - 1);
                //配合Excel求和计算，记录要清除内容的行index
                for (int j = 1; j <= orderNoCount - 1; j++) {
                    blankRowList.add(totalRowNo - list.size() + i + j);
                }
            }
            lastOrderNo = orderNo;
        }
    }

    @Override
    protected void merge(Sheet sheet, Cell cell, Head head, Integer relativeRowIndex) {
        if (columnMergeMap.containsKey(cell.getColumnIndex())) {
            if (mergeMap.containsKey(cell.getRowIndex())) {
                Long mergeCount     = mergeMap.get(cell.getRowIndex());
                int  nowRowIndex    = cell.getRowIndex();
                int  nowColumnIndex = cell.getColumnIndex();
                CellRangeAddress cellRangeAddress = new CellRangeAddress(nowRowIndex, nowRowIndex + mergeCount.intValue(), nowColumnIndex, nowColumnIndex);
                sheet.addMergedRegionUnsafe(cellRangeAddress);
            } else {
                if (blankRowList.contains(cell.getRowIndex())) {
                    cell.setCellType(CellType.BLANK);
                }
            }
        }
    }
`

**Comment by zhuangjiaju** [comment]
这个 需要自己第二个值不设置。不然无法解开。
