### ISSUE TITLE
使用Model读Excel模型时，只设置注解ExcelProperty的value值读取无效

### ISSUE THREAD

**Issue by RoyalXC** [alibaba/easyexcel#168]

**Comment by RoyalXC** [comment]
![image](https://user-images.githubusercontent.com/21688678/49934888-89b69400-ff0a-11e8-9666-ccabddd44934.png)
只设置model类注解中的value属性
![image](https://user-images.githubusercontent.com/21688678/49934938-ad79da00-ff0a-11e8-8d5b-daad07cdd505.png)
读取这个excel
最终结果读取为null

**Comment by rjjrrjjr** [comment]
同样的问题

**Comment by napoleon-he** [comment]
升级版本

**Comment by WangShuangQuan-A** [comment]
升级为最新的版本还是同样的问题

**Comment by ZK666** [comment]
Demo里的Model是设置了index的

**Comment by WangShuangQuan-A** [comment]
我的分支修改了这个bug

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
