### ISSUE TITLE
导出Excel时，设置部分列不可修改改如何实现

### ISSUE THREAD

**Issue by rangersboom** [alibaba/easyexcel#1683]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by drgnchan** [comment]
可以自定义CellWriteHandler，新增CellStyle，并设置setLocked(true)，然后对相应的cell设置该CellStyle。
