### ISSUE TITLE
调用代码时报NoSuchMethodError: com.alibaba.excel.ExcelWriter.<init>(Lcom/alibaba/excel/write/metadata/WriteWorkbook;)V

### ISSUE THREAD

**Issue by 501956430** [alibaba/easyexcel#1685]
调用代码时报
NoSuchMethodError: com.alibaba.excel.ExcelWriter.<init>(Lcom/alibaba/excel/write/metadata/WriteWorkbook;)V
version 2.1.17

@zhuangjiaju

**Comment by zhuangjiaju** [comment]
建议 `mvn clean`下
