### ISSUE TITLE
多行复合表头的表头识别可否根据多行合并的表头而不是最后一行的表头做标题进行识别？

### ISSUE THREAD

**Issue by rongjoker** [alibaba/easyexcel#1692]
你好，我搜索了一下issue，关闭的issue里也有很多人提过这个问题。复合表头，比如"联系人-姓名"，"联系人-手机号"，"负责人-姓名"，"负责人-手机号"，导出可以正常导出为复合的数据，导入的话只有最后一个手机号和姓名的列有数据。
多行的表头，仅仅按照最后一行的表头来作为标题进行识别，是否欠妥？以多行表头合并来确认对应的index是否更合理？

**Comment by zhuangjiaju** [comment]
这个情况建议直接使用index指定
