### ISSUE TITLE
同时导出两个list, 导出的excel文档不正常

### ISSUE THREAD

**Issue by tiger822** [alibaba/easyexcel#1694]
由于github不能upload图片, 所以我在csdn上讲的问题, https://blog.csdn.net/rocklee/article/details/110645660
搞不懂为什么三个list, 其中两个list用forceNewRow的fillConfig都没问题,唯独其中一个list有问题, 谢谢.

**Comment by JackeyXps** [comment]
请问有没有出现问题的数据和代码样例？我这边仿造导出多个list没有出现这个问题
