### ISSUE TITLE
Cannot call sendError() after the response has been committed

### ISSUE THREAD

**Issue by yulei-fighting** [alibaba/easyexcel#1697]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
try {
            response.setContentType("application/vnd.ms-excel");
            response.setCharacterEncoding("utf-8");
            // 这里URLEncoder.encode可以防止中文乱码
            excelName = URLEncoder.encode(excelName, "UTF-8").replaceAll("\\+", "%20");
            response.setHeader("Content-disposition", "attachment;filename=" + excelName + ExcelTypeEnum.XLSX.getValue());
            // 设置不关闭流
            EasyExcel.write(response.getOutputStream())
                    .autoCloseStream(Boolean.FALSE)
                    .head(head)
                    .sheet(sheetName)
                    .doWrite(data);
        } catch (IOException e) {
            // 重置response
            response.reset();
            response.setContentType("application/json");
            response.setCharacterEncoding("utf-8");
            Map<String, String> map = new HashMap<>();
            map.put("status", "failure");
            map.put("message", "下载文件失败" + e.getMessage());
            response.getWriter().println(JSON.toJSONString(map));
            e.printStackTrace();
        }
**异常提示**
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
**建议描述**

**Comment by linyongfu2013** [comment]
同样问题，文件能正常下载，但控制台会打印上述异常

**Comment by KID0031** [comment]
您好，请问用的是什么版本呢。我这里没有出现异常

**Comment by KID0031** [comment]
您好，请问用的是哪一个版本呢。我这里没有出现异常

**Comment by zhuangjiaju** [comment]
应该是其他spring拦截器的问题。
