### ISSUE TITLE
生成多个Excel

### ISSUE THREAD

**Issue by gofocus** [alibaba/easyexcel#1698]
请问在一个请求里可以生成多个Excel吗？可以的话麻烦给个Example，谢谢！

**Comment by psxjoy** [comment]
@gofocus 一个http请求，生成多个excel，然后把多个excel下载吗？

**Comment by gofocus** [comment]
> @gofocus 一个http请求，生成多个excel，然后把多个excel下载吗？

我想把多个Excel写到一个流里，然后生成压缩文件

**Comment by psxjoy** [comment]
@go

> > @gofocus 一个http请求，生成多个excel，然后把多个excel下载吗？
> 
> 我想把多个Excel写到一个流里，然后生成压缩文件

Hi，最简单的方法就是首先在一个临时文件夹中生成excel，然后对文件夹打包。另外，我在网上搜索到了[这段代码](https://blog.csdn.net/u013055490/article/details/87604705)，和你描述的需求一致，你可以参考一下。

**Comment by gofocus** [comment]
感谢，目前已经使用这种方式实现了，不过还是想避免生成临时文件，不知道能不能做到。

**Comment by gofocus** [comment]
> @go
> 
> > > @gofocus 一个http请求，生成多个excel，然后把多个excel下载吗？
> > 
> > 
> > 我想把多个Excel写到一个流里，然后生成压缩文件
> 
> Hi，最简单的方法就是首先在一个临时文件夹中生成excel，然后对文件夹打包。另外，我在网上搜索到了[这段代码](https://blog.csdn.net/u013055490/article/details/87604705)，和你描述的需求一致，你可以参考一下。

感谢，目前已经使用这种方式实现了，不过还是想避免生成临时文件，不知道能不能做到。
