### ISSUE TITLE
quickstart文档中图片不存在

### ISSUE THREAD

**Issue by Childe-Chen** [alibaba/easyexcel#170]
https://github.com/alibaba/easyexcel/blob/master/quickstart.md 中图片应该丢失了，加载不到。

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
