### ISSUE TITLE
填充Excel是否可以考虑嵌套循环

### ISSUE THREAD

**Issue by caiyl1314** [alibaba/easyexcel#1701]
**建议描述**
如填充如下数据
[
公司名 ：{}      公司编号：{}
员工列表：
姓名      工号
{.name}            {.no}
] ... (数量不固定)
就是模板中公司列表是个list、每个公司一个模板循环在一个sheet（即公司也是个list，不固定数量）。好像也没法通过固定的{data1.name}这样 需要到 {data(n).name} 模板无法写死，是否可以考虑嵌套循环模板填充

**Comment by zhuangjiaju** [comment]
建立多个table
