### ISSUE TITLE
模板列表填充,合并两个单元格，有方框，但填充后没有合并单元格，并且后面一个单元格没有方框

### ISSUE THREAD

**Issue by fluganto** [alibaba/easyexcel#1704]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
需要自定义合并策略
