### ISSUE TITLE
模板列表填充，格式覆盖问题

### ISSUE THREAD

**Issue by Denjor** [alibaba/easyexcel#1710]
模板列表填充，模板Excel有设定的格式，每行不一样，但是填充后全是按照第一行的格式往下复制，怎么办？
试了使用afterCellDispose，只设置了cell.setCellStyle(style)，但是其他的cell全变成这样了
```
@Override
    public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, List<CellData> cellDataList, Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {
        CellStyle style = cell.getCellStyle();
        //设置边框样式
        if(StringUtils.isNotBlank(cell.getStringCellValue())) {
            style.setBorderLeft(BorderStyle.THICK);
            // contentWriteCellStyle.setBottomBorderColor(IndexedColors.BLUE.getIndex()); //颜色
            style.setBorderRight(BorderStyle.THICK);
            style.setBorderBottom(BorderStyle.THIN);
            cell.setCellStyle(style);
        }
    }
```

![image](https://user-images.githubusercontent.com/30165776/102184065-ccd8e280-3ee9-11eb-9cf5-4db16eba844a.png)

**Comment by AliceNg429** [comment]
使用 POI提供的方法 - cloneStyleFrom 来克隆一个 style 出来专门为这个 cell 来设置 style。
CellStyle style = cell.getRow().getSheet().getWorkbook().createCellStyle();
style.cloneStyleFrom(cell.getCellStyle());    // 克隆出一个 style
针对style设置就可以解决这个问题
style.setBorderRight(BorderStyle.THICK);
style.setBorderBottom(BorderStyle.THIN);
cell.setCellStyle(style);

**Comment by jaedonghan** [comment]
老哥问题怎么解决的

**Comment by AliceNg429** [comment]
就像我在github里说的一样excle多个cell会共用一个格式，可以使用POI提供的cloneStyleFrom 来克隆一个 style 出来专门为这个 cell 来设置 style


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月7日(星期五) 上午9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 模板列表填充，格式覆盖问题 (#1710)





 
老哥问题怎么解决的

**Comment by jaedonghan** [comment]
我是批量填充单元格，当前单元格的格式不一定和哪个固定的单元格格式相同，所以不好克隆style。我需要的是填充的时候只是替换掉值，而单元格格式不变













韩浩


***@***.***


15251583448







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: AliceNg429  ***@***.***>
 

 
 发送时间: 2021-05-07 09:29:31
 

 
 收件人:alibaba/easyexcel ***@***.***> 

 
 抄送:15251583448 ***@***.***>,Manual ***@***.***> 

 
 主题: Re: [alibaba/easyexcel] 模板列表填充，格式覆盖问题 (#1710)
 





 就像我在github里说的一样excle多个cell会共用一个格式，可以使用POI提供的cloneStyleFrom 来克隆一个 style 出来专门为这个 cell 来设置 style 
 
 
 ------------------&nbsp原始邮件&nbsp------------------ 
 发件人: "alibaba/easyexcel" ***@***.***&gt 
 发送时间:&nbsp2021年5月7日(星期五) 上午9:21 
 ***@***.***&gt 
 ***@***.******@***.***&gt 
 主题:&nbspRe: [alibaba/easyexcel] 模板列表填充，格式覆盖问题 (#1710) 
 
 
 
 
 
 
 老哥问题怎么解决的

**Comment by jaedonghan** [comment]
老哥把原来这里的代码删掉，就可以使用模板原来各自单元格的格式了，没必要都跟第一行的单元格格式一样，













韩浩


***@***.***


15251583448







电子名片新出VIP模板啦，快来体验>>




扫一扫,


快速添加名片到手机




--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: AliceNg429  ***@***.***>
 

 
 发送时间: 2021-05-07 09:29:31
 

 
 收件人:alibaba/easyexcel ***@***.***> 

 
 抄送:15251583448 ***@***.***>,Manual ***@***.***> 

 
 主题: Re: [alibaba/easyexcel] 模板列表填充，格式覆盖问题 (#1710)
 





 就像我在github里说的一样excle多个cell会共用一个格式，可以使用POI提供的cloneStyleFrom 来克隆一个 style 出来专门为这个 cell 来设置 style 
 
 
 ------------------&nbsp原始邮件&nbsp------------------ 
 发件人: "alibaba/easyexcel" ***@***.***&gt 
 发送时间:&nbsp2021年5月7日(星期五) 上午9:21 
 ***@***.***&gt 
 ***@***.******@***.***&gt 
 主题:&nbspRe: [alibaba/easyexcel] 模板列表填充，格式覆盖问题 (#1710) 
 
 
 
 
 
 
 老哥问题怎么解决的

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
FillConfig新增参数：autoStyle 设置成false即可
