### ISSUE TITLE
使用Model解析Excel时无法将数值映射到Byte类型的属性上

### ISSUE THREAD

**Issue by curtiscai** [alibaba/easyexcel#172]
使用Model解析Excel时无法将数值映射到Byte类型的属性上，是不是没有增加Byte的转换器，请支持下，很多时候为了节约更多的内存以及和数据库中的tinyint做更好的映射关系，回经常使用Byte类型的属性

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
