### ISSUE TITLE
使用EasyExcel时如何对某些列进行求和？

### ISSUE THREAD

**Issue by lmy950715** [alibaba/easyexcel#1722]
我在使用 propery写入excel时，如何对某些列进行累加求和呢？我想查找相关的api和资料，请问可以指教一下去哪里查找吗？

**Comment by small-ora** [comment]
我也有类似的需求,我是在代码里面直接计算出来然后导出的,在文档里面也没看到添加公式的说明,你找到了也可以跟我说一下,谢谢.

**Comment by zhuangjiaju** [comment]
建议手动求和。
