### ISSUE TITLE
有些服务器读取excel特别慢的原因

### ISSUE THREAD

**Issue by zhugw** [alibaba/easyexcel#1727]
最近遇到了这么一个问题 一个70多万的Excel 本地解析完只需几分钟 但是部署到阿里云服务器上之后 解析要30多分钟 试了下其他服务器 发现centos7 慢  centos6 不慢 但是我自己购买了一个centos7服务器 试了下不慢

故 搞不清楚状况 怎么只是读取excel而已 有的机器就特别慢呢 慢在哪里呢 cpu 还是 磁盘IO 还是 什么系统内核参数配置

**Comment by zhuangjiaju** [comment]
这个看下磁盘 是否慢。需要写很大的磁盘。
