### ISSUE TITLE
Excel文件 使用 Double和String 接收 小数位保留处理方式不同

### ISSUE THREAD

**Issue by vergil-ong** [alibaba/easyexcel#1732]
**问题描述**
jar包版本为 2.2.7  
## 问题一  
1.  xlsx文件本身我这面解压之后，查看sheet1.xml 后 发现有些坐标的数据小数位很长
![image](https://user-images.githubusercontent.com/25544312/103123090-fcdc6e80-46bd-11eb-8926-0b1083e3c197.png)

2. 我发现 源码中 DoubleNumberConverter 和 StringNumberConverter 处理不一样
在DoubleNumberConverter 中是直接使用 Bigdecimal 的 doubleValue
![image](https://user-images.githubusercontent.com/25544312/103123185-6eb4b800-46be-11eb-8eab-66d1946ccd6c.png)
而 StringNumberConverter 中对于 默认，没有格式的数字类型 在 ExcelGeneralNumberFormat 这个类中format 方法 进行了数字位的处理
![image](https://user-images.githubusercontent.com/25544312/103123247-a9b6eb80-46be-11eb-885a-d0e11f223023.png)
  
**建议描述**
**这会导致我这面使用Bean接收的时候 Double和String 有不同的表现，我是觉得 如果String的处理是有规范要求的话，是不是应该进行统一的处理?**
**Double 会有很多位小数，String 会按照最多10位小数进行处理后，在四舍五入**

## 问题二  
ExcelGeneralNumberFormat 类里面提到的 https://support.microsoft.com/en-us/kb/65903
这个要求 我在微软的网站中没有找到，是地址换了，还是微软的支持范围变更了呢？
![image](https://user-images.githubusercontent.com/25544312/103123439-53967800-46bf-11eb-850c-254882858b3f.png)

**Comment by zhuangjiaju** [comment]
使用最新版。 String 接收你看到的。double 接收你存储的。

**Comment by vergil-ong** [comment]
> 使用最新版。 String 接收你看到的。double 接收你存储的。

不好意思，不知道是不是我没有描述完整，我的疑问 就是 在WPS、Excel、甚至是一些协同编辑软件（office online、一起写等）上 这种数据156.229999999999999999展示上 表现为 156.23， 而使用EasyExcel 用String 接收，会保留10位小数后四舍五入，Double 接收 会直接接收 原数据。 这两种 接收方式 都和 其他桌面、或者协同软件 表现不一致。
