### ISSUE TITLE
数据列的合计

### ISSUE THREAD

**Issue by BenBoombang** [alibaba/easyexcel#1735]
导出excel主要是为了规范化数据，除了对数据一目了然，同时肯定也想要对数据进行汇总合计，希望后续的更新中可以加入数据列的合计功能。

**Comment by zhuangjiaju** [comment]
这个暂时不考虑支持 。建议自定义拦截器。统计情况太多了。

**Comment by paynezhuang** [comment]
> 这个暂时不考虑支持 。建议自定义拦截器。统计情况太多了。

自定义拦截器怎么实现啊。有demo参考下么。
