### ISSUE TITLE
能否移植到android上使用

### ISSUE THREAD

**Issue by swallowsonny** [alibaba/easyexcel#174]
安卓上使用出现包名重复问题，能否移植到android上

**Comment by liuguicen** [comment]
> 安卓上使用出现包名重复问题，能否移植到android上

请问解决这个问题了吗

**Comment by swallowsonny** [comment]
> 我报了个这个错
> Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: org.apache.xmlbeans.xml.stream.XMLName
> 不知道安卓上能不能用



> > 安卓上使用出现包名重复问题，能否移植到android上
> 
> 请问解决这个问题了吗

https://github.com/andruhon/android5xlsx 我最后用的这个

**Comment by greenBro** [comment]
> > 我报了个这个错
> > Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: org.apache.xmlbeans.xml.stream.XMLName
> > 不知道安卓上能不能用
> 
> > > 安卓上使用出现包名重复问题，能否移植到android上
> > 
> > 
> > 请问解决这个问题了吗
> 
> https://github.com/andruhon/android5xlsx 我最后用的这个

非常感谢

**Comment by ijero** [comment]
我用这个方式，解决了在Android Studio编译运行的问题：

implementation('com.alibaba:easyexcel:1.1.2-beta5') {
        exclude group: "org.apache.xmlbeans", module: "xmlbeans"
}
