### ISSUE TITLE
听说excel中含图片的情况，以前不支持导入图片，想知道现在有没有支持？

### ISSUE THREAD

**Issue by ht03kunye** [alibaba/easyexcel#1744]

**Comment by ht03kunye** [comment]
使用了ByteArrayImageConverter和InputStreamImageConverter都读取步不到图片数据，@ExcelProperty(index=0,converter = ByteArrayImageConverter.class或者InputStreamImageConverter.class) 返回的byte[] image或者InputStream image均为null，大佬们有遇到过的吗？

**Comment by ht03kunye** [comment]
使用了ByteArrayImageConverter和InputStreamImageConverter都读取步不到图片数据，@ExcelProperty(index=0,converter = ByteArrayImageConverter.class或者InputStreamImageConverter.class) 返回的byte[] image或者InputStream image均为null，大佬们有遇到过的吗？

**Comment by lanfen100** [comment]
@ht03kunye 你好，目前支持么？我翻了一圈文档没看到有这方面相关的

**Comment by zhuangjiaju** [comment]
目前不支持 后续会考虑
