### ISSUE TITLE
windows服务生成的excel部分样式在linux服务上导出失效

### ISSUE THREAD

**Issue by yubaogu** [alibaba/easyexcel#1746]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   代码都运行正常
```
**异常提示**
没有异常
**建议描
[导入模板(1).xlsx](https://github.com/alibaba/easyexcel/files/5774409/1.xlsx)
[导入模板.xlsx](https://github.com/alibaba/easyexcel/files/5774411/default.xlsx)
分别是windos中和linux中代码运行导出的excel模板
述**

**Comment by zhuangjiaju** [comment]
参照常见问题
