### ISSUE TITLE
请求升级或者兼容 poi 4.x版本

### ISSUE THREAD

**Issue by cn-src** [alibaba/easyexcel#1748]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)

**建议描述**
Apache POI 的使用还是很广泛的，所以希望能提供兼容的版本，而且一般只要是还维护的都会使用较新版本的 POI，许多其它框架都依赖了 4.x 的，这样几乎没法同时与easyexcel一起使用。

就像这个开源软件的做法一样通过artifactId提供不同版本的兼容 https://simpleflatmapper.org/0105-getting-started-poi.html

**Comment by zhuangjiaju** [comment]
兼容4.x 直接用就行。后续会升级。
