### ISSUE TITLE
转换excel格式异常。您可以尝试自己指定“ excelType” 

### ISSUE THREAD

**Issue by suiquantong** [alibaba/easyexcel#1751]
转换excel格式异常。您可以尝试自己指定“ excelType” 

Convert excel format exception.You can try specifying the 'excelType' yourself
![image](https://user-images.githubusercontent.com/37520861/103879412-c6b5da80-5112-11eb-9f11-47de88d35b9a.png)

`java   
ExcelListener excelListener = new ExcelListener();
        EasyExcel.read(filePath, ReadData.class, excelListener).sheet().doRead();
`

**Comment by zhangxinping63** [comment]
> 转换excel格式异常。您可以尝试自己指定“ excelType”
> 
> Convert excel format exception.You can try specifying the 'excelType' yourself
> ![image](https://user-images.githubusercontent.com/37520861/103879412-c6b5da80-5112-11eb-9f11-47de88d35b9a.png)
> 
> `java ExcelListener excelListener = new ExcelListener(); EasyExcel.read(filePath, ReadData.class, excelListener).sheet().doRead(); `

**Comment by zhuangjiaju** [comment]
传入的Excel格式有问题。
