### ISSUE TITLE
运行springboot jar导出xls文件导出不了，xlsx可以导出

### ISSUE THREAD

**Issue by zhuangchongyi** [alibaba/easyexcel#1752]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
nested exception is org.apache.poi.poifs.filesystem.OfficeXmlFileException: The supplied data appears to be in the Office 2007+ XML. POI only supports OLE2 Office documents
**建议描述**
运行jar导出xls文件导出不了

**Comment by zhuangjiaju** [comment]
贴全代码

**Comment by zhuangjiaju** [comment]
是否已经解决问题？如果未解决 请重新打开问题。
