### ISSUE TITLE
EasyExcel.read() 为什么自定义的listener无法读取到第一行的数据？

### ISSUE THREAD

**Issue by HeNanFei** [alibaba/easyexcel#1754]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by HeNanFei** [comment]
代码如下

package com.zjt.elasticsearch.dto;

import com.alibaba.excel.context.AnalysisContext;
import com.alibaba.excel.event.AnalysisEventListener;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

public class CheckSheetListener  extends AnalysisEventListener<LinkedHashMap<Integer,Object>> {

    private List<LinkedHashMap> linkedHashMap;


    public CheckSheetListener(List<LinkedHashMap> excelLinkedHash) {
        this.linkedHashMap = excelLinkedHash;
    }

    @Override
    public void invoke(LinkedHashMap<Integer,Object> data, AnalysisContext context) {
        linkedHashMap.add(data);
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
        System.out.println(linkedHashMap);
    }
}

**Comment by wzcJava** [comment]
设置表头行数为0试试 
EasyExcel.read(inputStream, Model.class, listener).headRowNumber(0).sheet().doRead()

**Comment by MoxiseTou** [comment]
我遇到了相同的问题。设置headRowNumber(0)就可以了
