### ISSUE TITLE
字段中涉及到不规范的英文拼写时，在调用BeanMap后会将字段第一个不规范字母改为大写。导致无法匹配模型

### ISSUE THREAD

**Issue by wxfmm** [alibaba/easyexcel#1755]
![image](https://user-images.githubusercontent.com/45766291/103988735-91b88f00-51c9-11eb-88ec-ada449a85311.png)
通过BeanMap.create(oneRowData)获取的beanMap对象中的字段首字母已变为大写，

**Comment by wxfmm** [comment]
private void addJavaObjectToExcel(Object oneRowData, Row row, int relativeRowIndex, List<Field> fieldList) {
        WriteHolder currentWriteHolder = this.context.currentWriteHolder();
        **BeanMap beanMap = BeanMap.create(oneRowData);**
        Set<String> beanMapHandledSet = new HashSet();
        。。。。。。。
}

**Comment by zhuangjiaju** [comment]
后续版本会修复

**Comment by YangJingf** [comment]
请问哪一个版本修复了呢

**Comment by alanOO7** [comment]
请问修复了吗，2.2.11版本还是存在

**Comment by alanOO7** [comment]
3版本网上修复了
