### ISSUE TITLE
表头和列名相同的时候会自动合并

### ISSUE THREAD

**Issue by MonkeyBrothers** [alibaba/easyexcel#1756]
我需要下面这样的表头：
![image](https://user-images.githubusercontent.com/36203824/103990856-d2fe6e00-51cc-11eb-8372-36bfa55cdd50.png)
然后我进行字段的设置：
![image](https://user-images.githubusercontent.com/36203824/103990920-f0cbd300-51cc-11eb-8648-693d46c20220.png)
得到的结果：
![image](https://user-images.githubusercontent.com/36203824/103991042-1a84fa00-51cd-11eb-9a10-814616974da9.png)
 有什么好的办法解决吗？

**Comment by zhuangjiaju** [comment]
建议第二个 加个空格

**Comment by Sdky** [comment]
> 建议第二个 加个空格

加个空格不就改变了原来的内容了么？
