### ISSUE TITLE
同一个单元格能不能导出既有文字又有图片,查了很多资料了没找到

### ISSUE THREAD

**Issue by luoxiaofeng1029** [alibaba/easyexcel#1758]
同一个单元格能不能导出既有文字又有图片,查了很多资料了没找到,有的是一个单元格放一张,还有的是一个单元格放多张.不知道能不能多张同时带文字的

**Comment by zhuangjiaju** [comment]
自定义拦截器 。常见问题有。

**Comment by ps271828** [comment]
请问这个在哪里有例子可以参考

**Comment by lyc0428** [comment]
> 自定义拦截器 。常见问题有。

这个解决办法在哪，没找到
