### ISSUE TITLE
@ExcelProperty 注解的index，可以动态传入吗

### ISSUE THREAD

**Issue by felekos** [alibaba/easyexcel#1762]
通过用户设置模板stundentTemplate，例如（姓名 1列）（年龄 2列）（性别 3列）；学生实体中，private String name;上的注解@ExcelProperty(index = steudentTemplate.getNameCol)；实现动态传入

**Comment by liubenwei** [comment]
你可以使用不创建对象的写，把header封装成List<List<String>>

**Comment by shanxu9198** [comment]
@liubenwei 能详细解释下吗？
我遇到的场景也是希望能动态传入index。多个excel表，都存在一样的几列内容，只不过对应的列顺序不一样。表1（姓名1列、年龄2列、性别3列），表2（姓名2列、年龄3列、性别1列），表3（姓名3列、年龄1列、性别2列）。希望能定义一个对象，通过动态传入index解决。
盼回复，谢谢！

**Comment by liubenwei** [comment]
没看过源码 ，如果你的项目有使用spring框架，你这个功能可以使用aop去修改注解里的值，就可以达到动态的效果。，如果没有用到spring，可以使用不创建对象的写（easyExcel文档里有）。

**Comment by felekos** [comment]
我才用的不读到对象中，读取到map中，自己在service中解析
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: shanxu9198 <notifications@github.com&gt;
发送时间: 2021年1月23日 15:44
收件人: alibaba/easyexcel <easyexcel@noreply.github.com&gt;
抄送: felekos <1151200122@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/easyexcel] @ExcelProperty 注解的index，可以动态传入吗 (#1762)





 
@liubenwei 能详细解释下吗？
 我遇到的场景也是希望能动态传入index。多个excel表，都存在一样的几列内容，只不过对应的列顺序不一样。表1（姓名1列、年龄2列、性别3列），表2（姓名2列、年龄3列、性别1列），表3（姓名3列、年龄1列、性别2列）。希望能定义一个对象，通过动态传入index解决。
 盼回复，谢谢！

**Comment by felekos** [comment]
收到，我后来改用读取到list的方式，自己在service中解析


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: liubenwei <notifications@github.com&gt;
发送时间: 2021年1月23日 15:56
收件人: alibaba/easyexcel <easyexcel@noreply.github.com&gt;
抄送: felekos <1151200122@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/easyexcel] @ExcelProperty 注解的index，可以动态传入吗 (#1762)





 
没看过源码 ，如果你的项目有使用spring框架，你这个功能可以使用aop去修改注解里的值，就可以达到动态的效果。，如果没有用到spring，可以使用不创建对象的写（easyExcel文档里有）。

**Comment by shanxu9198** [comment]
改成不创建对象方式读实现了，谢谢！ @liubenwei
