### ISSUE TITLE
post请求（参数比较多）下载excel， 文件打不开，用postman是正常的，请问是不可以用post还是前端接收问题

### ISSUE THREAD

**Issue by huangxian119** [alibaba/easyexcel#1764]
![image](https://user-images.githubusercontent.com/43724064/104804911-7f170900-580c-11eb-9c2a-0269633c6b04.png)

    response.setContentType("application/vnd.ms-excel");
    response.setCharacterEncoding("utf-8");
    // 这里URLEncoder.encode可以防止中文乱码 当然和easyexcel没有关系
    try {
      String fileName = URLEncoder.encode("test", "UTF-8");
      response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx");
      EasyExcel.write(response.getOutputStream(), InvitePageVo.class).sheet("test").doWrite(rows);
    } catch (IOException e) {
      log.error(e.getMessage());
    }

**Comment by baichangda** [comment]
@huangxian119 
尝试设置一下
response.setContentType("application/octet-stream");

**Comment by cdoer** [comment]
@huangxian119 前端是不是开了mock   关掉,被拦截了

**Comment by shaohuaboy** [comment]
同问 @huangxian119  你解决了吗
