### ISSUE TITLE
建议增加多张图片导入一个单元格的demo.

### ISSUE THREAD

**Issue by luoxiaofeng1029** [alibaba/easyexcel#1766]
建议增加多张图片导入一个单元格的demo.单元格宽度自动适应.一张图片满足不了需求

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
参照：https://www.yuque.com/easyexcel/doc/write#cb1b271f
