### ISSUE TITLE
行数据比较及删除的问题

### ISSUE THREAD

**Issue by 2008010688sn** [alibaba/easyexcel#1767]
请问
1.支持行数据之间的比较吗，比如（第一行的第一列的值加上第二列的值）和（第二行的第一列的值加上第二列的值）进行比较？
2.支持列的删除吗？

**Comment by Tloops** [comment]
请问这个功能需要帮忙做吗？我想在未来几个月尝试做一做这个功能 @zhuangjiaju

**Comment by zhuangjiaju** [comment]
1. 不支持
2. 不支持
