### ISSUE TITLE
设置contentWriteCellStyle.setHorizontalAlignment(HorizontalAlignment.FILL);后单元格出现重复数据显示

### ISSUE THREAD

**Issue by harvies** [alibaba/easyexcel#1768]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
设置contentWriteCellStyle.setHorizontalAlignment(HorizontalAlignment.FILL);后单元格出现重复数据显示

**触发Bug的代码**
```java
   contentWriteCellStyle.setHorizontalAlignment(HorizontalAlignment.FILL);
```
**提示的异常或者没有达到的效果**
![image](https://user-images.githubusercontent.com/16585330/105024743-6e25fc00-5a87-11eb-9a3f-11c908c69eb5.png)

**Comment by Mcliuyi** [comment]
http://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/HorizontalAlignment.html

这个参数功能就是这样

**Comment by harvies** [comment]
> http://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/HorizontalAlignment.html
> 
> 这个参数功能就是这样

加这个是为了不溢出，但是会导致重复，原来是一个”是“ 加了之后就是图上的

**Comment by Mcliuyi** [comment]
![image](https://user-images.githubusercontent.com/37773013/106694681-025d9a80-6614-11eb-945c-d23c0cd4e2b1.png)
文档这里描述是 单元格显示值会被填充 ，同时测试是 poi 本身功能就是这样，并不是 easyexcel 的bug。你认真看一下文档，做个测试吧

**Comment by harvies** [comment]
> ![image](https://user-images.githubusercontent.com/37773013/106694681-025d9a80-6614-11eb-945c-d23c0cd4e2b1.png)
> 文档这里描述是 单元格显示值会被填充 ，同时测试是 poi 本身功能就是这样，并不是 easyexcel 的bug。你认真看一下文档，做个测试吧

了解了，谢谢
