### ISSUE TITLE
读取文件过大导致内存溢出

### ISSUE THREAD

**Issue by napoleon-he** [alibaba/easyexcel#177]
读取的文件过大，OPCPackage.open(InputStream is) 方法内部会进行流的拷贝，导致内存溢出，是否考虑读取的方式可以传递路径的方式，将OPCPackage.open(String filePath)对外提供可以多种路径读取方式。

**Comment by zlsss** [comment]
+1，50m文件oom

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
