### ISSUE TITLE
想在上一次创建的excel文件上继续往下写数据的api是什么

### ISSUE THREAD

**Issue by xiaoyuaaaaa** [alibaba/easyexcel#1771]
想在上一次创建的excel文件上继续往下写数据的api是什么

**Comment by spice-wolf** [comment]
是否只能先读取原excel中的数据，然后再把新数据加入到数据集合中，然后再一起写入excel？

**Comment by gl28-iu** [comment]
有找到对应api吗

**Comment by spice-wolf** [comment]
> 有找到对应api吗

我没有找到。我是将原数据先读出来，然后把新数据加进去，最后再重新写入Excel中

**Comment by zhuangjiaju** [comment]
参照 根据模板读取demo
