### ISSUE TITLE
某些列的属性的格式，基本是相似的，那么对于多个字段重复使用的注解有没有合并注解的功能

### ISSUE THREAD

**Issue by chenchengbest** [alibaba/easyexcel#1777]
**建议描述**
比方说number字段，一般都是固定的格式，一个字段可以使用
    @HeadStyle(fillPatternType = FillPatternType.SOLID_FOREGROUND, fillForegroundColor = 55,
            horizontalAlignment = HorizontalAlignment.RIGHT,verticalAlignment = VerticalAlignment.CENTER)
    @ColumnWidth(30)
    @ContentStyle(horizontalAlignment = HorizontalAlignment.RIGHT,verticalAlignment = VerticalAlignment.CENTER)
如果多个字段都是相似的number字段，就会导致多个字段重复上述的注解，有没有方式能够将这些注解合并，或者封装使用

**Comment by zhuangjiaju** [comment]
目前没有
