### ISSUE TITLE
复合表头数据读取，只能读取到第二列表头对应的值，第一列读取不到

### ISSUE THREAD

**Issue by object360** [alibaba/easyexcel#1782]
实体类：

    @ExcelProperty("名称")
    private String name;

   
    @ExcelProperty({"尺寸","高（米）"})
    private BigDecimal height;

    
    @ExcelProperty({"尺寸","宽（米）"})
    private BigDecimal width;

监听器类：
 @Override
    public void invoke(Entity data, AnalysisContext context) {

//在这里调试data对象，只能找到尺寸-高（米）和尺寸-宽（米）的值，名称的值为空，这个是什么问题

}

**Comment by zhuangjiaju** [comment]
升级到最新版
