### ISSUE TITLE
自定义策略样式怎么不生效，头部是自定义的一个表头

### ISSUE THREAD

**Issue by hancab** [alibaba/easyexcel#1784]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
![图片](https://user-images.githubusercontent.com/10796683/106218271-f9cf2380-6211-11eb-8123-df147fb0c45a.png)
这是表头
而且设置了不用默认的，好像生成就是默认的
![图片](https://user-images.githubusercontent.com/10796683/106218143-bd9bc300-6211-11eb-8554-4315e5619e67.png)
![图片](https://user-images.githubusercontent.com/10796683/106218193-d6a47400-6211-11eb-85ad-b08dcd75b22e.png)

**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by tangcent** [comment]
***是否是这个原因?***

- 自定义表头导致没有`headClass`

https://github.com/alibaba/easyexcel/blob/756f16e42fbd7bc5c7fa18426cbc02fc81a42057/src/main/java/com/alibaba/excel/metadata/AbstractParameterBuilder.java#L15-L35

- 没有`headClass`就不会解析其中的`Field`,亦不会取上面的注解

https://github.com/alibaba/easyexcel/blob/756f16e42fbd7bc5c7fa18426cbc02fc81a42057/src/main/java/com/alibaba/excel/metadata/property/ExcelHeadProperty.java#L116-L136

**Comment by zhuangjiaju** [comment]
实测不会出现 建议升级版本
