### ISSUE TITLE
excel 导出日期格式筛选问题

### ISSUE THREAD

**Issue by zhaoqf-cq** [alibaba/easyexcel#1785]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
![image](https://user-images.githubusercontent.com/27794583/106219102-b1186a00-6213-11eb-94d9-74f38a0684b5.png)
```
**异常提示**
easyexcel 2.2.4
使用的数据
![image](https://user-images.githubusercontent.com/27794583/106219279-05234e80-6214-11eb-8950-7861c457624e.png)

如果您使用过excel的日期排序, 它应该是这样的
![image](https://user-images.githubusercontent.com/27794583/106219263-ff2d6d80-6213-11eb-8d9b-11065fb4e0c4.png)

但是使用easyexcel 导出之后, excel筛选居然是这样的
![image](https://user-images.githubusercontent.com/27794583/106219404-3a2fa100-6214-11eb-8375-02f45e1b3078.png)
![image](https://user-images.githubusercontent.com/27794583/106219414-4156af00-6214-11eb-801c-ab58545c58cb.png)
![image](https://user-images.githubusercontent.com/27794583/106219534-8844a480-6214-11eb-8801-2f3ffc078a60.png)
![image](https://user-images.githubusercontent.com/27794583/106219575-a5797300-6214-11eb-9881-0710f84cb0a4.png)

目前多种尝试, 除非手动修改excel, 不然导出的excel日期类型筛选都不是想要的, 请问一下这个有好的解决方案么

**Comment by zhaoqf-cq** [comment]
经过一段时间的学习... 解决了该问题... 我自己来结帖吧....

根据巨硬对 [Excel 的日期系统](https://support.microsoft.com/zh-cn/office/excel-%E4%B8%AD%E7%9A%84%E6%97%A5%E6%9C%9F%E7%B3%BB%E7%BB%9F-e7fe7167-48a9-4b96-bb53-5612a800b487)的解释, 然后我就不多逼逼了, 看上面链接... (注意, Excel 貌似有bug, 计算经过实际的时候, 少了一天, 应该是 1900年是平年, 被算成了闰年)

我将实体属性设置为 Long 类型, set 的值为(展示的日期 - 1899年12月31日 +1), 然后属性上面添加了 @ContentStyle(dataFormat = 14) 来解决了我本次的问题

**Comment by shiyi-ly** [comment]
哈哈哈，自己结贴可还行，我也遇到了类似的问题

**Comment by zhaoqf-cq** [comment]
> 呵呵，自己结可还行，我也遇到贴了类似的问题

没办法啊... 大神都看不太起这种小问题... 其实还有好几种解决方法...比如样式设置为空, 然后去自定义... 写一大堆... 小项目直接用 Long 真香
