### ISSUE TITLE
导出emoji表情第一行不显示，第二行正常

### ISSUE THREAD

**Issue by GSumme** [alibaba/easyexcel#1786]
![image](https://user-images.githubusercontent.com/23045162/106346526-c4e6cd80-62f2-11eb-8728-e0a7105a0286.png)

**Comment by lethal233** [comment]
能提供复现bug的testcase吗？

**Comment by feijifei** [comment]
I am interested in this issue, I will fix this bug in few mouths. @zhuangjiaju

**Comment by zhuangjiaju** [comment]
贴全代码

**Comment by SmireG** [comment]
我用emoji-java工具得到emoji，并写入xlsx，发现没有bug

```java
 private List<TestData> data() {
        List<TestData> list = new ArrayList<TestData>();
        for (int i = 0; i < 10; i++) {
            TestData data = new TestData();
            data.setIdx(i);
            data.setDate(new Date());
            String str="\uD83E\uDD17\uD83D\uDE0F\uD83D\uDE36\uD83D\uDE10\uD83D\uDE44";
            String result= EmojiParser.parseToAliases(str);
            String res = EmojiParser.parseToUnicode(result);
            System.out.println(result);
            System.out.println(res);
            data.setTitle(res);
            list.add(data);
        }
        return list;
    }
```

![image](https://user-images.githubusercontent.com/60234283/115107493-b75ded00-9f9d-11eb-83cc-865a6462a837.png)

然后我尝试把你的emoji直接复制粘贴进xlsx然后读，发现**2021-04-17 16:53:06.150 WARN [main] com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor:41 - Empty row!**

读不到

请把你的测试样例发一下！ @GSumme

**Comment by lethal233** [comment]
我在mac系统上面复现不了bug，你这个应该是自己写入的问题 @GSumme
