### ISSUE TITLE
读取excel文件有多个空格数据重复了16384多次

### ISSUE THREAD

**Issue by papabattery** [alibaba/easyexcel#179]
在2016版excel文件中，两个有文字的输入行之间有多个空格，读取到这里的时候出现了16384多的重复数据

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
