### ISSUE TITLE
导出合并表头时会出现重复数据

### ISSUE THREAD

**Issue by vin9712** [alibaba/easyexcel#1791]
我使用的是是[这个教程](https://www.cnblogs.com/oukele/p/11444234.html)里的多表头生成方法，如下效果是想要的
![image](https://s3.ax1x.com/2021/02/02/ynkAc4.png)

但当我取消合并单元格后，发现其下面是包含这些多出来的数据 请问有什么方法来处理？
![image](https://s3.ax1x.com/2021/02/02/ynFxns.png)
![image](https://s3.ax1x.com/2021/02/02/ynkCNV.png)

另外 如何根据 excel 文件来设置读取表头数据，我能在 `invokeHeader` 里面一行行读取，并根据表头数据来进行判断，但复用度不高，如果有好的方法更棒了。

**Comment by Zhang-Muyang** [comment]
我们想试着解决一下。: )

**Comment by zhuangjiaju** [comment]
需要自定义拦截器 可以自己处理
