### ISSUE TITLE
自定义复杂头

### ISSUE THREAD

**Issue by BSTK-collab** [alibaba/easyexcel#1802]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
   @Data
public class ComplexHeadData {
private static final String time = "";
    @ExcelProperty({time, "字符串标题"})
    private String string;
    @ExcelProperty({time, "日期标题"})
    private Date date;
    @ExcelProperty({time, "数字标题"})
    private Double doubleData;
}
```
**异常提示**
Attribute value must be constant
**建议描述**
我怎样可以将”主标题“ 换成自定义的呢，比如加一串时间？

**Comment by small-ora** [comment]
使用拦截器可以实现,
或者使用动态头 https://www.yuque.com/easyexcel/doc/write#b4b9de00
