### ISSUE TITLE
导出文件损毁无法打开

### ISSUE THREAD

**Issue by zqszzs** [alibaba/easyexcel#1803]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
response.addHeader("Pragma", "No-cache");
        response.addHeader("Cache-Control", "No-cache");
        response.setHeader("Content-disposition", "attachment;filename=" + URLEncoder.encode(fileName + "_" + System.currentTimeMillis(),"UTF-8") + ".xlsx");
        response.setContentType("application/vnd.ms-excel;charset=UTF-8");
List<List<String>> header = new ArrayList<>();
        header.add(Arrays.asList(
                new String [] {
                        "会员id",
                        "活动id",
                        "手机号",
                        "奖品类型",
                        "奖品名称",
                        "活动名称",
                        "活动类型",
                        "获取奖品的时间",
                }
        ));
        ExcelWriter writer = EasyExcel.write(outputStream).excelType(ExcelTypeEnum.XLSX).build();
        WriteSheet writeSheet = EasyExcel.writerSheet(fileName).head(header ).build();
        int pageNo = 1, pageSize = 1000, limitPageSize = 50;
        param.setPageSize(pageSize);
        while (true) {
             // 业务逻辑
            if(resultResultDTO.getData().getList().size() < pageSize || pageNo >= limitPageSize) {
                break;
            }
            pageNo++;
        }
        writer.finish();
        outputStream.flush();
        response.getOutputStream().close();
```
**提示的异常或者没有达到的效果**
可以生成excel文件，倒是文件损坏无法打开

**Comment by lethal233** [comment]
能提供完整的触发bug的代码吗？

**Comment by zqszzs** [comment]
该问题系我们代码所致，非bug
