### ISSUE TITLE
某一列存在公式时，会导致一直读取空行

### ISSUE THREAD

**Issue by wuguangkuo** [alibaba/easyexcel#1807]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
假设A列是个下拉框选项有：男、女，B列是个公式，根据A列内容计算出单元格的值应该是0还是1。
这种情况会导致一直读取空行
**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by Albert1881** [comment]
请问有人处理这个bug吗，我对这个issue感兴趣，将在未来几个月处理这个bug @zhuangjiaju

**Comment by feijifei** [comment]
I'm also interested in this issue, maybe we crashed!
11712707

**Comment by zhuangjiaju** [comment]
这个 自己用 `CellData`来接收公式。自己计算。easyexcel 不会去计算公式的 这个非常耗性能。
尝试重新保存excel  应该就能读取出来了。

**Comment by leileih** [comment]
@zhuangjiaju 你好，我遇到了类似的现象，因为有公式，读取到了空行。我的问题是，如何能忽略这个公式，不读取空行？请问不用CellData读数据的时候，如何能识别出公式？ 谢谢！
