### ISSUE TITLE
设置开始读取列的偏移量

### ISSUE THREAD

**Issue by jogeen** [alibaba/easyexcel#1808]
```java
public class User{
@ExcelProperties("姓名")
String name;
@ExcelProperties("年龄")
Integer age;
@ExcelProperties("部门")
String dept;
}
```

姓名 | 年龄 | 部门 | 姓名 | 年龄 | 部门
-- | -- | -- | -- | -- | --
  |   |   |   |   |  

我希望通过设置偏移量,读取两次这个文件,然后用两个User对象分别装下1-3,4-6列的属性
比如像这样
read(1);
read(4);
希望能提供相关功能,谢谢

**Comment by small-ora** [comment]
这个可以直接读一次,然后自己在Listener自己处理吧.

**Comment by zhuangjiaju** [comment]
创建一个大对象 后自己分开。或者参照不创建对象的读。
