### ISSUE TITLE
可以实现一个单元格填充多张远程图片吗？

### ISSUE THREAD

**Issue by zhangzl0119** [alibaba/easyexcel#1809]
查看了文档https://www.yuque.com/easyexcel/doc/write#cb1b271f
发现只能填充单张图片，使用集合URL会报错，请问有什么方法填充多张图片？

**Comment by no-one258** [comment]
我也想问，你解决了吗

**Comment by zhuangjiaju** [comment]
这个需要自定拦截器 目前比较复杂 后续再想想办法。常见问题里面有方案。
