### ISSUE TITLE
导出时怎么对特定列的数据进行有效性约束

### ISSUE THREAD

**Issue by chenchenk** [alibaba/easyexcel#181]

**Comment by chenchenk** [comment]
![1](https://user-images.githubusercontent.com/31459822/50280849-926a1580-0488-11e9-8296-37c4bf600f35.png)
sheet根本不会执行

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。  并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
