### ISSUE TITLE
ExcelProperty value 注释和代码不一致

### ISSUE THREAD

**Issue by vimilai** [alibaba/easyexcel#1811]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
ExcelProperty value 注释和代码不一致,读显示的是最后一个而不是最后一个。

HI, i use the code with ExcelProperty value  that has multi-value ,your comment was  'read: When you have multiple heads, take the first one'
![image](https://user-images.githubusercontent.com/19221051/109377075-e348e480-7903-11eb-8e17-bf20ce25b4dd.png)
你的一场
**触发Bug的代码**
```java
 But  i found out the 
com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor#buildHead
![image](https://user-images.githubusercontent.com/19221051/109377099-0ffcfc00-7904-11eb-90a0-d3870f02456d.png)
So  it's really find out that the head-name was the last one rather than the first one
```
**提示的异常或者没有达到的效果**
 the result  show  the last one   head-value,using first-head Name ，return null

**Comment by vimilai** [comment]
![image](https://user-images.githubusercontent.com/19221051/109381947-5197a200-7918-11eb-8b73-56e9289324b5.png)

**Comment by zhuangjiaju** [comment]
感谢 新版本会修复
