### ISSUE TITLE
Could not initialize class com.alibaba.excel.write.ExcelBuilderImpl

### ISSUE THREAD

**Issue by robinkang1003** [alibaba/easyexcel#1812]
java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.excel.write.ExcelBuilderImpl
	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:47)
	at com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:130)
	
easyexcel版本2.2.3，poi均是3.17

**Comment by robinkang1003** [comment]
别用2.2.3，用2.2.6就好了

**Comment by jefferyqjy** [comment]
![image](https://user-images.githubusercontent.com/5515566/113278021-f8a29b80-9313-11eb-98a9-c286de8e4a9b.png)

我用的2.2.8，参考github的demo代码也报这个错~

**Comment by jefferyqjy** [comment]
> ![image](https://user-images.githubusercontent.com/5515566/113278021-f8a29b80-9313-11eb-98a9-c286de8e4a9b.png)
> 
> 我用的2.2.8，参考github的demo代码也报这个错~

2.2.6以上与poi版本3.9不兼容~将poi 3.3.9的maven依赖删除即可用
