### ISSUE TITLE
关于获取总行数 ReadSheetHolder.approximateTotalRowNumber 的提问

### ISSUE THREAD

**Issue by WhiteBookMan1994** [alibaba/easyexcel#1813]
approximateTotalRowNumber 可能是不精确的，自己试了几个Excel，得到的结果是正确的总行数。【easyexcel-2.2.6.jar版本】
有一些场景，可能在上传读Excel文件时会限制Excel的行数，因为异步处理Excel文件，不想读完后再统计总行数，所以想知道 approximateTotalRowNumber 什么情况下得到的值一定是正确的总行数？这个值与实际总行数的误差范围有多大？
还没有来得及分析底层实现，不知道有没有熟悉的同学能解答一下

**Comment by zhuangjiaju** [comment]
可能会为空  如果是普通office软件的 基本正确。但是 第三方office  或者软件导出的可能为空。
