### ISSUE TITLE
AbstractCellValueTagHandler里有个地方不太理解

### ISSUE THREAD

**Issue by mjnjust** [alibaba/easyexcel#1815]
AbstractCellValueTagHandler.endElement方法，为什么empty最后被赋予number的类型，new BigDecimal("")会报错
![image](https://user-images.githubusercontent.com/11895349/110433046-ee152d80-80ea-11eb-8018-e9bf8b4da0b6.png)
easyexcel 2.2.7

**Comment by zhuangjiaju** [comment]
已经在 ` 2.2.8` 修复
