### ISSUE TITLE
怎么冻结首行

### ISSUE THREAD

**Issue by zhaochuanzhen** [alibaba/easyexcel#1817]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by cucuzi** [comment]
参考：https://www.yuque.com/easyexcel/doc/write#591ee418

**Comment by zhaochuanzhen** [comment]
可以了、感谢分享
