### ISSUE TITLE
com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader

### ISSUE THREAD

**Issue by arrayest** [alibaba/easyexcel#1819]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
easyexcel不兼容poi 5.0.0版本。运行异常。com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader
。降低poi版本到4.1.2后正常运行。
**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**
com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader

**Comment by zhuangjiaju** [comment]
暂时不支持 5.0.0
