### ISSUE TITLE
使用Java model 格式化日期有问题

### ISSUE THREAD

**Issue by chuckma** [alibaba/easyexcel#182]
在使用 Java model 的 时候，日期字段使用了  Date 类型， 经过 format = "yyyy-MM-dd" 之后 貌似还是不对，都是 4XXXX，excel 日期字段格式是日期类型， 像这样2017/10/17

**Comment by coderzhw** [comment]
我也遇到了这个问题，请问怎么解决？

**Comment by coderzhw** [comment]
我也遇到这个了问题，具体的看看这篇文章就知道这个4XXX数字是什么意思了，https://www.myonlinetraininghub.com/excel-date-and-time

**Comment by 545314690** [comment]
@ExcelProperty(index = 2,format = "yyyy/MM/dd")
    private Date loanDate;

写上格式化注解没用啊，写入文件的是这样的Thu May 02 00:00:00 CST 2019

**Comment by qijun4tian** [comment]
升级到1.1.1 版本就没问题了

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
