### ISSUE TITLE
模板中的表格如何根据条件动态显示

### ISSUE THREAD

**Issue by zhen5902** [alibaba/easyexcel#1823]
比如：已经设计好一个excel模板。其中，模板内有两个不同的表格。两个表格中的数据，来源于两个list。如何根据list是否为空，在excel模板中动态显示不同的表格。如果，其中一个表格为空，则模板内显示一个表格。另一个表格不显示。
麻烦大神！！！

**Comment by zhuangjiaju** [comment]
创建多个模板

**Comment by zhen5902** [comment]
嗯，谢谢zhuangjiaju。目前采用的就是多个模板，但模板中的list有4个。现在排列组合有点多啊。。希望能通过动态标签类的东西可以动态解决
