### ISSUE TITLE
文件导出并下载之后，文件打不开，说文件损坏

### ISSUE THREAD

**Issue by no-one258** [alibaba/easyexcel#1826]
`

    public void downloadExcel(String contact, String status, HttpServletRequest request, HttpServletResponse response)throws IOException  {
        List<BmtCertApply> excelModelData = getExcelModelData(contact, status);
        System.out.println(excelModelData);//有值

        // 这里注意 使用swagger 会导致各种问题，请直接用浏览器或者用postman
        response.setContentType("application/vnd.ms-excel");
        response.setCharacterEncoding("utf-8");
        // 这里URLEncoder.encode可以防止中文乱码 当然和easyexcel没有关系
        String fileName = URLEncoder.encode("ceshi", "UTF-8").replaceAll("\\+", "%20");
        response.setHeader("Content-disposition", "attachment;filename*=utf-8''" + fileName + ".xlsx");
        EasyExcel.write(response.getOutputStream(), BmtCertApply.class).sheet("模板").doWrite(excelModelData);

    }

`

**Comment by LiHaoGit** [comment]
试一下 右键点击文件 确保 【解除锁定】**不被勾选**
![image](https://user-images.githubusercontent.com/7036191/111251867-03d6a580-864b-11eb-848d-264b3a8af913.png)

**Comment by zhaoxilingcheng** [comment]
我也遇到这个问题， 代码和文档一样，数据也不是空的

**Comment by zhuangjiaju** [comment]
检查是否有其他spring 的拦截器 写入了额外的流。
