### ISSUE TITLE
如何将获取的数据生成对应的List实体类

### ISSUE THREAD

**Issue by xianda666** [alibaba/easyexcel#183]
数据自动转成javamodel,转完之后还是List<Object>类型 无法使用model的get/set等方法， 个人理解为 应该把单行数据封装为Bean==

**Comment by Lsx1131188021** [comment]
作者已经考虑到了，再仔细看看文档，继承AnalysisEventListener自行实现，EasyExcelFactory.readBySax(inputstream, new Sheet(1, 1, Bean.class), listener);可以实现你说的，读取数据封装成bean

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
