### ISSUE TITLE
根据列索引进行数据映射，未指定列索引会解析到其他字段

### ISSUE THREAD

**Issue by sixmillions** [alibaba/easyexcel#1830]
# 背景
我们用easyexcel的列解析功能，发现一个bug

# 正常
我们分别将id,name,age几个字段解析到实体类对应字段，但是这个motto这列我们不需要就不解析了
![image](https://user-images.githubusercontent.com/41658874/111717281-b64c7980-8892-11eb-8d34-aa5abb88957d.png)

解析后结果：正常
![image](https://user-images.githubusercontent.com/41658874/111717501-1fcc8800-8893-11eb-87d1-793fe4175264.png)

# 不正常
在上面的基础上，假设我们实体类有一个其他字段，比如height，
解析excel的时候，easyexcel会将excel中的motto解析到height
![image](https://user-images.githubusercontent.com/41658874/111717712-97021c00-8893-11eb-8802-056be964318b.png)

解析结果：不正常
错误的将motto字段解析到了我未指定的height字段
但是motto字段是String类型，height字段是integer类型，所以解析报错了
![image](https://user-images.githubusercontent.com/41658874/111718300-a2a21280-8894-11eb-9042-17ec7ccfe48d.png)

# 总结
这个我们觉得应该是一个bug

**Comment by sixmillions** [comment]
我们解决办法是构建一个新的实体类，来接受这个没用的字段

**Comment by zhuangjiaju** [comment]
目前的逻辑 参照了其他序列化框架。如果没有任何注解的字段 会根据 排序去匹配 excel里面的字段。所以需要加上`@ExcelIgnore

`注解
