### ISSUE TITLE
请问如何指定导出excel的某列单元格的类型

### ISSUE THREAD

**Issue by 418545106** [alibaba/easyexcel#1831]
在有些情况下，我想让单元格的第一列类型都为日期类型，这个日期类型不仅是导出的数据看起来像是日期`yyyy-MM-dd`，而且是那个excel的单元格类型为日期类型
![image](https://user-images.githubusercontent.com/29942834/111718333-b2215b80-8894-11eb-9e14-b2f7de30c8da.png)

**Comment by qinzixuan** [comment]
可以试一下在字段或者数据模型类上添加@ContentStyle(dataFormat = 22)    
dataFormat取值来自com.alibaba.excel.constant.BuiltinFormats
在2.2.10版本应该是可以的

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
然后使用`@DateTimeFormat` 注解即可指定样式
