### ISSUE TITLE
数据类型为CellData时rowIndex和columnIndex值未放进去，实际开发可能需要

### ISSUE THREAD

**Issue by mingshenyue** [alibaba/easyexcel#1832]
建议映射实体数据类型为CellData 时能否将行号和列号索引值也放入到CellData属性中，
![image](https://user-images.githubusercontent.com/21308752/111968138-d0f14d80-8b33-11eb-9355-1b4052da5794.png)

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
