### ISSUE TITLE
请问，replace这种功能，后面是否会提供。就是key和value可以互相转换的

### ISSUE THREAD

**Issue by Joyonline** [alibaba/easyexcel#1835]
![image](https://user-images.githubusercontent.com/28465958/112271841-64528c00-8cb6-11eb-83a8-191311f7ec8e.png)

**Comment by zhuangjiaju** [comment]
这个可以考虑

**Comment by guanpeijia** [comment]
> 这个可以使用自定义转换器。

虽然使用自定义转换器可以实现，但是会增加很多Converter的类，期待这种replace的实现
