### ISSUE TITLE
想知道支持excle内部图片读取吗？api是什么没有找到。

### ISSUE THREAD

**Issue by harborbest** [alibaba/easyexcel#1837]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
目前不支持
