### ISSUE TITLE
对应poi版本

### ISSUE THREAD

**Issue by xinhaohch** [alibaba/easyexcel#184]
easyExcel支持的jdk及poi的最低版本是多少？

**Comment by wqh0109663** [comment]
作者真的是懒

**Comment by wqh0109663** [comment]
1.6

**Comment by zhuangjiaju** [comment]
jdk 1.6 
poi 4.0.1

**Comment by xinhaohch** [comment]
Think You


------------------ 原始邮件 ------------------
发件人: "Jiaju Zhuang"<notifications@github.com>;
发送时间: 2019年8月28日(星期三) 晚上7:26
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "信号"<3468086140@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 对应poi版本 (#184)




jdk 1.6
 poi 4.0.1
