### ISSUE TITLE
关于2.2.8自定义表头时，内容单元格自定义样式需要点击后才生效

### ISSUE THREAD

**Issue by Wetkin** [alibaba/easyexcel#1843]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
在动态头，对单行列进行进行自定时样式的修改（版本2.2.8）
**触发Bug的代码**
  ExcelWriter excelWriter = EasyExcel.write(out).head(this.head(export)).registerWriteHandler(newCustomCellWriteHandler()).excelType(ExcelTypeEnum.XLSX).build();

 @Override
    public void afterCellDataConverted(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, CellData cellData, Cell cell, Head head, Integer integer, Boolean isHead) {

        if (!isHead) {
            CreationHelper createHelper = writeSheetHolder.getSheet().getWorkbook().getCreationHelper();
            CellStyle cellStyle = writeSheetHolder.getSheet().getWorkbook().createCellStyle();
            if (cellStyle != null) {
                DataFormat dataFormat = createHelper.createDataFormat();
                cellStyle.setWrapText(true);
                cellStyle.setFillBackgroundColor(IndexedColors.GREEN.getIndex());
                cellStyle.setDataFormat(dataFormat.getFormat(DateUtils.DEFAUTL_PATTERN));
                cell.setCellStyle(cellStyle);

            }

        }

    }

**提示的异常或者没有达到的效果**
head是List时，内容单元格的样式需要点击之后才生效。默认不生效

**Comment by zhuangjiaju** [comment]
设置参数有误 建议参照
```java
        // 这里需要指定 FillPatternType 为FillPatternType.SOLID_FOREGROUND 不然无法显示背景颜色.头默认了 FillPatternType所以可以不指定
        contentWriteCellStyle.setFillPatternType(FillPatternType.SOLID_FOREGROUND);
        // 背景绿色
        contentWriteCellStyle.setFillForegroundColor(IndexedColors.GREEN.getIndex());

```

**Comment by 285643846** [comment]
你好，我也遇到了相同的问题，我是通过注解的方式  @ContentStyle(dataFormat = 2)设置单元格式，但是导出后发现默认没有生效，点击查看单元格式是正确的，需要双击单元格才会变成设置的格式
