### ISSUE TITLE
导出文件背景色整体是黑色，office打开的效果是黑色的，wps打开没事

### ISSUE THREAD

**Issue by flyingbird2** [alibaba/easyexcel#1847]
![文件内部](https://user-images.githubusercontent.com/17829253/113243452-9e8ae180-92e5-11eb-9b81-66aff4b1394a.jpg)
![文件缩率图](https://user-images.githubusercontent.com/17829253/113243451-9e8ae180-92e5-11eb-8055-771c5d77251f.jpg)

**Comment by flyingbird2** [comment]
版本号是
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>2.2.7</version>
        </dependency>

**Comment by flyingbird2** [comment]
我自己定义的handler
//列宽
    public static SimpleColumnWidthStyleStrategy columnWidth = new SimpleColumnWidthStyleStrategy(27);

    //行高
    public static SimpleRowHeightStyleStrategy rowHeight = new SimpleRowHeightStyleStrategy(new Short("28"), new Short("40"));

    //合并单元格
    public static OnceAbsoluteMergeStrategy onceAbsoluteMergeStrategy =
            new OnceAbsoluteMergeStrategy(0, 1, 0, 1);

    //单元格样式
    private static List<WriteCellStyle> contentWriteCellStyleList = new ArrayList<>(Lists.newArrayList(getCustomerCellStyle()));
    public static HorizontalCellStyleStrategy horizontalCellStyleStrategy = new HorizontalCellStyleStrategy(new WriteCellStyle(), contentWriteCellStyleList);

    private static WriteCellStyle getCustomerCellStyle() {
        WriteCellStyle cellStyle = new WriteCellStyle();
        cellStyle.setFillPatternType(FillPatternType.SOLID_FOREGROUND);
        cellStyle.setFillForegroundColor(IndexedColors.WHITE.index);
        cellStyle.setBorderBottom(BorderStyle.THIN);
        cellStyle.setBorderLeft(BorderStyle.THIN);
        cellStyle.setBorderRight(BorderStyle.THIN);
        cellStyle.setBorderTop(BorderStyle.THIN);
        cellStyle.setBottomBorderColor(IndexedColors.BLACK1.index);
        cellStyle.setHorizontalAlignment(HorizontalAlignment.CENTER);
        cellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
        cellStyle.setWrapped(true);
        return cellStyle;
    }

**Comment by small-ora** [comment]
你的自定义样式里面设置底部边框颜色的代码删掉看看,边框颜色默认就是黑色的啊.
cellStyle.setBottomBorderColor(IndexedColors.BLACK1.index);
