### ISSUE TITLE
我现在数据库里的一个字段，存了好几张图片的地址，而且图片的数量是不一定的。这个easyExcel是可以导出来的吗

### ISSUE THREAD

**Issue by no-one258** [alibaba/easyexcel#1848]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by no-one258** [comment]
给个思路也可以，跪求

**Comment by small-ora** [comment]
试试看自定义拦截器,在拦截器里面把所有的图片写在一个格子里面,
https://www.yuque.com/easyexcel/doc/write#591ee418
这只是一个思路,我没验证,不确定可不可以.

**Comment by zhuangjiaju** [comment]
参照常见问题
