### ISSUE TITLE
怎么给每个单元格设置样式呢

### ISSUE THREAD

**Issue by juzi214032** [alibaba/easyexcel#185]
我往BaseRowModel的子类中添加了CellStyle 但是样式并不是我自己设置的，而是当前表头的样式，不知道是为什么

**Comment by juzi214032** [comment]
知道问题所在了，创建的CellStyle不是使用对应的Workbook创建的，easyexcel好像没有提供获取当前workbook的方法，只能自己写一个吗？

**Comment by PhilosophyBuns** [comment]
楼主问题解决了吗，同样不知道怎么使用BaseModel里的addStyle方法

**Comment by juzi214032** [comment]
> 楼主问题解决了吗，同样不知道怎么使用BaseModel里的addStyle方法

解决了，我刚写了个博客https://juzibiji.top/index.php/archives/267/

**Comment by PhilosophyBuns** [comment]
> > 楼主问题解决了吗，同样不知道怎么使用BaseModel里的addStyle方法
> 
> 解决了，我刚写了个博客https://juzibiji.top/index.php/archives/267/

并没有找到writerHandle这个类啊，作者删除了吗？ 版本1.1.2-beta4

**Comment by juzi214032** [comment]
> > > 楼主问题解决了吗，同样不知道怎么使用BaseModel里的addStyle方法
> > 
> > 
> > 解决了，我刚写了个博客https://juzibiji.top/index.php/archives/267/
> 
> 并没有找到writerHandle这个类啊，作者删除了吗？ 版本1.1.2-beta4

用beta5版本

**Comment by PhilosophyBuns** [comment]
> > > > 楼主问题解决了吗，同样不知道怎么使用BaseModel里的addStyle方法
> > > 
> > > 
> > > 解决了，我刚写了个博客https://juzibiji.top/index.php/archives/267/
> > 
> > 
> > 并没有找到writerHandle这个类啊，作者删除了吗？ 版本1.1.2-beta4
> 
> 用beta5版本
非常感谢你给我的启发，其实使用writerHandle 不需要那么麻烦的设置样式，我自己写了基于注解的样式设置，详见
https://github.com/alibaba/easyexcel/issues/205

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
