### ISSUE TITLE
请问如何进行追加写入和指定列内容的修改

### ISSUE THREAD

**Issue by gl28-iu** [alibaba/easyexcel#1850]
请问如何进行追加写入和指定列内容的修改

**Comment by small-ora** [comment]
追加写入暂时没有什么好的办法,指定列修改的话可以自定义一个拦截器;
https://www.yuque.com/easyexcel/doc/write#591ee418

**Comment by zhuangjiaju** [comment]
调用 `withTemplate`可以追加 暂时不支持修改。
