### ISSUE TITLE
如何在所有的readListener执行完毕后统一执行一段逻辑

### ISSUE THREAD

**Issue by leslie-gl** [alibaba/easyexcel#1852]
我注意到在AnalysisEventProcessor的实现中：
![image](https://user-images.githubusercontent.com/62866504/113710263-127a1f00-9716-11eb-8249-122b8ea7a13e.png)

我该怎么设置自己的Processor？

或者有更合适的其他解决方案吗？

**Comment by zhuangjiaju** [comment]
建议直接在处理完成后书写

**Comment by small-ora** [comment]
我提供一个曲线救国的方法你可以参考一下.
弄一个工具类,把你要执行的逻辑写在一个静态方法里面,然后在每个Listener的doAfterAllAnalysed里面调用一下.
