### ISSUE TITLE
如何优雅自定义字典转换器

### ISSUE THREAD

**Issue by lls-liweiye** [alibaba/easyexcel#1853]
导出的时候对特定字段进行转换，比如1转为男，2转为女，alibaba转为阿里巴巴, tencent转为腾讯，这些以key value格式保存在数据库。我自定义了一个转换器，里面先查出对应小范围的字典(数据库获取),然后就进行转换了。

问题:这样带来的问题是每次转换都要查一下库，效率低下，能否用一下类似threadLocal缓存的方式获取，但是线程结束的时候释放这个内存的动作在哪里执行比较妥当？类似spring的后置增强这样

**Comment by zhuangjiaju** [comment]
考虑直接放内存 或者缓存
