### ISSUE TITLE
是否可以新增读取表头的功能？

### ISSUE THREAD

**Issue by xzxiaoshan** [alibaba/easyexcel#1855]
**建议描述**
使用EasyExcel现在可以读取表头的文本，可以读取内容的文本，但是读取不了表头的样式和文本的样式。
建议：
比如有这样的一个需求，从一个有内容的Excel中只只提取表头然后存储为模板。

**Comment by zhuangjiaju** [comment]
这个建议只用poi 就可以。短期内不会支持读取样式。
