### ISSUE TITLE
Data对象的属性命名不能首字母大写 

### ISSUE THREAD

**Issue by ijry** [alibaba/easyexcel#1857]
因为数据表字段是TestUser这样的驼峰法，用mybatis-plus的自动生成代码生成的实体无法将首字母转为小写，导致在easyExcel中无法读取到值。

**Comment by zhuangjiaju** [comment]
必须使用驼峰

**Comment by ijry** [comment]
> 需要排查下

这个已经修复了吗？

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。

**Comment by ijry** [comment]
牛



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jiaju Zhuang ***@***.***&gt;
发送时间: 2021年9月17日 22:42
收件人: alibaba/easyexcel ***@***.***&gt;
抄送: jry ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[alibaba/easyexcel] Data对象的属性命名不能首字母大写  (#1857)






已经在3.0.0-beta1 版本修复，beta版本会在一个月内升级成正式版。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
