### ISSUE TITLE
大标题 次级标题 头

### ISSUE THREAD

**Issue by Ahaolin** [alibaba/easyexcel#1860]
能否提供实现类似 大的标题 次即标题的功能,通过注解和自定义请求头来完成,目前通过模板可以实现 。
`
       List<String> head0 = new ArrayList<String>();
        head0.add("标题");
        head0.add("字符串" + System.currentTimeMillis());
        List<String> head1 = new ArrayList<String>();
        head1.add("标题");
        head1.add("数字" + System.currentTimeMillis());
`

![image](https://user-images.githubusercontent.com/37574890/114120372-f0072200-991e-11eb-83a1-6b919e472aa6.png)
但是无法自定义头的样式和 次级标题的功能。

**Comment by zhuangjiaju** [comment]
通过注解 或者自定义拦截器

**Comment by Ahaolin** [comment]
能详细说说哪个注解吗
