### ISSUE TITLE
easyexcel模板填充多个sheet的时候，一个sheet fill()填充报错调用finishOnException关闭流，后面的sheet数据就不再填充

### ISSUE THREAD

**Issue by jaedonghan** [alibaba/easyexcel#1861]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
  
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
这个 暂时不考虑解决。需要自己解决报错
