### ISSUE TITLE
linux环境执行报错，字体问题？？

### ISSUE THREAD

**Issue by lls-liweiye** [alibaba/easyexcel#1862]

**Comment by lls-liweiye** [comment]
![Uploading 1617938572329.jpg…]()

**Comment by lls-liweiye** [comment]
FontConfiguration.getVersion空指针

**Comment by lls-liweiye** [comment]
已解决

**Comment by Aissue** [comment]
为啥我的还报呢？

**Comment by xiaour** [comment]
> 已解决

咋解决的？给的方案啊

**Comment by liweiye-2021** [comment]
我这边是用docker的，打包镜像选择的jdk有问题，导致字体有缺失
<baseImage>openjdk-with-full-font:latest</baseImage>

maven里配置如上的jdk就没问题，你可以检查一下

**Comment by xiaour** [comment]
好的，我这边是直接扔在服务器的，需要给服务器安装一些组件，希望对后来人有用：
yum install -y fontconfig urw-fonts
