### ISSUE TITLE
使用模板填报，xlsx格式会丢失行高，xls正常

### ISSUE THREAD

**Issue by Physicalyy** [alibaba/easyexcel#1869]
**触发场景描述**
使用XLSX模板导出的数据，单元格有设置自动换行功能，导出的行数据，内容长度超过一行理论上应该增加行高，只有第一行数据是正常展示，第一行以后的数据 都会自动调整为一行高度
使用xls模板导出则数据显示正常

**Comment by Albert1881** [comment]
请问目前是否有人处理这个bug，我对这个issue感兴趣，会在最近几个月尝试去修复这个bug @zhuangjiaju

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
