### ISSUE TITLE
某注解字段不导出

### ISSUE THREAD

**Issue by dalao-G** [alibaba/easyexcel#187]
在具体业务中碰到如下情况，导出时只导出部分注解字段。例如：人员统计表有7个字段如下，
![image](https://user-images.githubusercontent.com/22167737/50440366-e5344900-0930-11e9-8c40-50ffb125c343.png)
正常业务导出如下，
![image](https://user-images.githubusercontent.com/22167737/50440396-0137ea80-0931-11e9-9e92-8e1c948b44ee.png)
现有特殊要求，只需要导出姓名及年龄如下，
![image](https://user-images.githubusercontent.com/22167737/50440420-20cf1300-0931-11e9-9b57-1f8a24a322a8.png)
请教，在不创建新模型实体的情况下，能否实现？

**Comment by Lsx1131188021** [comment]
做了下测试，在不需要导出的字段不要加@ExcelProperty注解就可以了

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写即可
