### ISSUE TITLE
导出excel会存在中间表头为空的列

### ISSUE THREAD

**Issue by panlinfu** [alibaba/easyexcel#1873]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zjr2000** [comment]
请问有没有出问题的代码样例 @panlinfu

**Comment by panlinfu** [comment]
> 请问有没有出问题的代码样例@panlinfu
@Data
public class PartDowExcel extends PageReqVO implements Serializable {
    @Excel(name = "sku")
    private String sku;
    @Excel(name = "主SKU")
    private String mainsku;
    @Excel(name = "商品名称（中文）")
    private String nameCn;
    @Excel(name = "商品名称（英文）")
    private String nameEn;
    @Excel(name = "采购价")
   ...........
就是这样的实体接收的

**Comment by zjr2000** [comment]
好的谢谢 @panlinfu

**Comment by panlinfu** [comment]
> 请问有没有出问题的代码样例@panlinfu

PageReqVO 这个是自己写的分页参数

**Comment by panlinfu** [comment]
> 好的谢谢@panlinfu也没有报错信息，不确定问题出在哪里

**Comment by lethal233** [comment]
能提供复现该bug的最小完整代码吗，把所有的代码贴全，这样才能有机会能fix该issue @panlinfu

**Comment by zjr2000** [comment]
> > 好的谢谢@panlinfu也没有报错信息，不确定问题出在哪里

您好，抱歉这么久才回复，我这边测试了一下您给的数据，没有发现问题。
