### ISSUE TITLE
现在easyexcel不去维护了吗 ，连续四五个月没有更新了哦

### ISSUE THREAD

**Issue by liaoliang** [alibaba/easyexcel#1882]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by lethal233** [comment]
可能在闷大招

**Comment by zhuangjiaju** [comment]
相对比较稳定
