### ISSUE TITLE
导入excel报错，org.apache.poi.util.RecordFormatException: Unexpected remaining size 

### ISSUE THREAD

**Issue by johlon** [alibaba/easyexcel#1888]
导入excel，excel有7-10ge sheet，其中有几个是隐藏的，我按sheetName去读取，报错

EasyExcel.read((InputStream)multipartFile.getInputStream(), listener).sheet("PL").autoTrim(true).doReadSync();
org.apache.poi.util.RecordFormatException: Unexpected remaining size (22)

**Comment by lethal233** [comment]
@johlon 我用自己的文件尝试了一下，不会报错，你能贴一下你的excel（简化版本）和完整代码吗？

**Comment by johlon** [comment]
[INB21040528-332360-USA.xls](https://github.com/alibaba/easyexcel/files/6355330/INB21040528-332360-USA.xls)
对不起，不知道这个可以上传附件，请帮忙再看看，感谢！

**Comment by lethal233** [comment]
> [INB21040528-332360-USA.xls](https://github.com/alibaba/easyexcel/files/6355330/INB21040528-332360-USA.xls)
> 对不起，不知道这个可以上传附件，请帮忙再看看，感谢！

ok，我尝试一下

**Comment by johlon** [comment]
有新的进展吗

**Comment by lethal233** [comment]
> 有新的进展吗

暂时还没有，bug已经复现，已经大概定位，最近ddl有点多.....不好意思

**Comment by feijifei** [comment]
> 导入excel，excel有7-10ge sheet，其中有几个是隐藏的，我按sheetName去读取，报错
> 
> EasyExcel.read((InputStream)multipartFile.getInputStream(), listener).sheet("PL").autoTrim(true).doReadSync();
> org.apache.poi.util.RecordFormatException: Unexpected remaining size (22)

读取.xls文件会产生这样的报错，如果将文件转化为.xlsx读取则没有错误。

**Comment by johlon** [comment]
好的，等修复，我先转为xlsx导入，谢谢了！

**Comment by zhuangjiaju** [comment]
贴全异常 然后提供excel  感谢

**Comment by zhuangjiaju** [comment]
这个问题已经修复了么？ 已经修复了话请重新打开问题
