### ISSUE TITLE
能否通过配置文件设置表头解析为Mode

### ISSUE THREAD

**Issue by guqing** [alibaba/easyexcel#189]
请问能不能通过配置文件的方式配置表头而不是通过注解  这种方式用不起来很不爽  比如pojo通过mybatis逆向工程自动生成注解不太方便加，而且如果是继承的话也不太方便，父类加了@ExcelProperty()，子类也加这个注解还无法解析成Mode。
总而言之就是能不能通过配置文件说明excel表哪一列对应哪一个pojo属性，然后直接读取excel就能将数据赋值到Model中？
谢谢

**Comment by zhuangjiaju** [comment]
非常感谢您的意见。这个内部讨论了下，目前没有精力去做这个，不排除后溪兼容的可能。
