### ISSUE TITLE
怎么从已经存在的Excel-Sheet 之间整体copy 到新的Excel 中，只能先解析在一点点拼装吗？

### ISSUE THREAD

**Issue by zhangqingzhou1024** [alibaba/easyexcel#1892]
因为有些表格结构比较复杂，解析后再拼接会比较麻烦，所以想知道有没有直接copy Sheet 的方法呢？

**Comment by skrlst** [comment]
楼主解决了吗？
我这边也有类似问题，想要从 excel 模板中 copy 特定的 sheet，然后用这个 copy 的 sheet 动态生成多个 sheet。

**Comment by zhangqingzhou1024** [comment]
> 楼主解决了吗？
> 我这边也有类似问题，想要从 excel 模板中 copy 特定的 sheet，然后用这个 copy 的 sheet 动态生成多个 sheet。

没有，我用的笨方法，读取->解析->写入，然后自己重新设置的样式

**Comment by zhuangjiaju** [comment]
这个目前不支持额
