### ISSUE TITLE
问一下导入excel的时候，怎么 处理空白栏 而不是跳过

### ISSUE THREAD

**Issue by lambdafish** [alibaba/easyexcel#1893]
比如导入3行数据，
第1、3行是有数据的，第2行是空数据，但最后通过监听创建的集合内只有2个对象，
想让第2行数据也变成一个对象，对象的各个值是null或者空字符串，请问怎么做呢

**Comment by lethal233** [comment]
在 `src/main/java/com/alibaba/excel/read/metadata/holder/ReadWorkbookHolder.java` 里面有这么一个属性，是可以设置false不跳过空行的，可以看看api文档如何设置，默认是true，代表跳过空行。
```java
    /**
     * Ignore empty rows.Default is true.
     */
    private Boolean ignoreEmptyRow;
```

在 `src/main/java/com/alibaba/excel/read/processor/DefaultAnalysisEventProcessor.java` 的 `38-47`行的`endrow()`函数里面调用了
```java
            if (analysisContext.readWorkbookHolder().getIgnoreEmptyRow()) {
                return;
            }
```
默认是true，所以直接return出去了，你设置成false就好了。
