### ISSUE TITLE
合并单元格，以单元格为单位合并不太合理

### ISSUE THREAD

**Issue by seetbw** [alibaba/easyexcel#1898]
如果遇到同时需要列和行合并的情况几乎不可用，需要自己加缓存记录需要合并的单元格，不如等单元格数据样式渲染完成以后进行整体的合并，提供一个行的列表，用户根据需求进行合并操作

**Comment by seetbw** [comment]
开始不知道还有个RowWriteHandler,与CellWriteHandler可以实现，行合并和列合并

**Comment by guanpeijia** [comment]
> RowWriteHandler

自己实现合并规则？
