### ISSUE TITLE
无法把下载的文件设置为xlsx后缀名

### ISSUE THREAD

**Issue by modefang** [alibaba/easyexcel#1899]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
       public static void exportExcel(String fileName, List data, Class clazz, HttpServletResponse response) {
        try {
            // 初始化样式
            WriteCellStyle headWriteCellStyle = new WriteCellStyle();
            WriteFont headWriteFont = new WriteFont();
            headWriteFont.setFontHeightInPoints((short) 11);
            headWriteCellStyle.setWriteFont(headWriteFont);
            HorizontalCellStyleStrategy handler = new HorizontalCellStyleStrategy(headWriteCellStyle, new WriteCellStyle());

            response.setContentType("application/vnd.ms-excel");
            response.setCharacterEncoding(StandardCharsets.UTF_8.toString());
            // 处理中文乱码
            String encode = URLEncoder.encode(fileName, StandardCharsets.UTF_8.toString());
            response.setHeader("Content-disposition", "attachment;filename=" + encode + ExcelTypeEnum.XLSX.getValue());
            EasyExcel.write(response.getOutputStream(), clazz)
                    .excelType(ExcelTypeEnum.XLSX)
                    .registerWriteHandler(handler)
                    .sheet("Sheet1")
                    .doWrite(data);
        } catch (IOException e) {
            throw new GlobalDefaultException(ResponseEnum.ERROR_EXCEL_EXPORT, e);
        }
    }
```
**提示的异常或者没有达到的效果**
下载出来的文件还是xls，然后打开的时候会有提醒
![企业微信截图_20210425173713](https://user-images.githubusercontent.com/21217474/115988555-e7843c00-a5ec-11eb-9c9a-bf164b43c5e1.png)

**Comment by SmireG** [comment]
我对这个Bug感兴趣，希望在之后的几个月尝试解决这个bug @zhuangjiaju

**Comment by summinter** [comment]
@SmireG 您好，我已经成功复现了这个bug并尝试对其进行了修复，在执行excelType()函数改变类型的同时对file的后缀进行更改

**Comment by summinter** [comment]
@modefang 您好，我已经成功复现了这个bug并尝试对其进行了修复，在执行excelType()函数改变类型的同时对file的后缀进行更改

**Comment by summinter** [comment]
@modefang  你好，我对这个问题很感兴趣，尝试复现了一下这个bug。

该bug的起因是在使用`excelType()`函数将后缀类型修改为`XLSX`时，程序并没有将`ExcelWriterBuilder`类中`file`文件输出流的文件路径后缀名进行修改，还是保留原来的`xls`后缀，所以在进行修改后，文件名没有发生变化。

我尝试在`ExcelWriterBuilder`中的`excelType()`函数中，在更改类型后对文件名的后缀进行判断，若是`file`是`xls`类型，而更改后的`excelType`是`XLSX`,则通过`file()`函数将`file`的后缀更改为`xlsx`

修复后程序执行结果如下：

![screenshot](https://user-images.githubusercontent.com/49226728/116106836-09f98080-a6e5-11eb-9e91-f82844e3f744.png)

@zhuangjiaju  我会尝试提交一次pull request，希望进行code review。

**Comment by modefang** [comment]
🎉

**Comment by zhuangjiaju** [comment]
导出文件名 后缀设置为xlsx
