### ISSUE TITLE
设计混乱的建议

### ISSUE THREAD

**Issue by FjieYi** [alibaba/easyexcel#1904]
使用也看了源码，感觉设计有以下几个问题：
1. 职责不匹配，如ExcelWriterSheetBuilder，只应该提供build方法，为什么要能够生成ExcelWriterTableBuilder？为什么能执行数据操作（doWrite，doFill，借助的ExcelWriter）？，剥离这些不该存在的方法，那么变量ExcelWriter就没用处；进一步剥离ExcelWriter，只剩一个WriteSheet成员变量，是在构造器里new，build直接返回，那么该成员变量也没意义，可直接在静态build里生成。那么最后该类其实是个鸡肋，因为WriteSheet的生成很简单，静态封装没起到简化过程的作用。
2. 大量重复功能。ExcelWriterSheetBuilder可由工厂创建ExcelWriterBuilder，再通过其创建，也可直接通过工厂创建，还可直接new（创建并不复杂）
3. 最恶劣的结果：组件的功能逻辑混乱，参考jdbc连接db，提供工厂入口，然后一步步递进创建对象，实现功能，线性逻辑清晰简洁。因为1,2的存在，有很多种写法实现功能，代码仿佛绕迷宫一样前进。对理解和使用都造成太大困扰。
建议：简化静态工具方法，进而简化成员变量甚至类，以线性方式设计逻辑。

**Comment by heliusjing** [comment]
同感，希望作者加油。

**Comment by zhuangjiaju** [comment]
兄弟可以啊 有兴趣一起加入不 直接加钉钉或者QQ群联系我就行
