### ISSUE TITLE
list填充模板时所有单元格格式复制的初始的单元格，应该是使用原本单元格本身的格式

### ISSUE THREAD

**Issue by jaedonghan** [alibaba/easyexcel#1908]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by wj19960923** [comment]
老哥这问题解决了吗

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
FillConfig新增参数：autoStyle 设置成false即可
