### ISSUE TITLE
NPE in ConverterUtils.java

### ISSUE THREAD

**Issue by ErrReporter** [alibaba/easyexcel#1917]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
Hello,
Our code analyses found the following potential NPE:

1. null作为第2个参数传递给函数convertToJavaObject
https://github.com/alibaba/easyexcel/blob/bb3166345d8d873b92c7d5bc7246fd27c38c6802/src/main/java/com/alibaba/excel/read/listener/ModelBuildEventListener.java#L62

2. 调用field的java.lang.reflect.Field.getGenericType方法(field可能为空指针)
https://github.com/alibaba/easyexcel/blob/bb3166345d8d873b92c7d5bc7246fd27c38c6802/src/main/java/com/alibaba/excel/util/ConverterUtils.java#L90

Commit: bb3166345d8d873b92c7d5bc7246fd27c38c6802
**提示的异常或者没有达到的效果**
NPE

**Comment by lethal233** [comment]
看了一下，应该不是bug，在84-86行
```java
if (field == null) {
        clazz = String.class;
}
```
这里有判断如果`field`是`null`，`clazz`会赋值为`String.class`
然后下面90行进入的条件是`clazz == CellData.class`，所以不会导致NPE @ErrReporter
