### ISSUE TITLE
如何每次write的时候就把sheet的数据写入文件而不是finish的时候多个sheet一起写入？

### ISSUE THREAD

**Issue by yangwz001** [alibaba/easyexcel#1920]
![image](https://user-images.githubusercontent.com/83849768/117522097-f5e53700-afa0-11eb-983a-5032b8d07725.png)
write的时候只是写入内存的，finish的时候才输出到文件，现在有10个sheet，每个100000行，结果这100W行全都在内存最后finish才写入的文件，
![image](https://user-images.githubusercontent.com/83849768/117522181-62603600-afa1-11eb-9c69-fe63fade49f5.png)
手动掉write(outputStream)的时候又会关闭流，下一次就报stream close的异常导致只能写入一个sheet，有没有什么方式能解决这个问题？

**Comment by MXDC** [comment]
https://stackoverflow.com/a/2674936

**Comment by zhuangjiaju** [comment]
这个需要最后压缩 ，写入的情况 easyexcel是基于的poi写的。
