### ISSUE TITLE
支持：实体类含有List属性，根据这个属性来决定合并单元格的效果

### ISSUE THREAD

**Issue by X1aoHei** [alibaba/easyexcel#1921]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
假设有这样一个实体：
public class Data {

    @ExcelProperty("父标题")
    private String father;

    @ExcelProperty("子标题")
    private List<String> child;
}

实际导出的时候，父标题能根据子标题的size来动态调整合并单元格的逻辑

**Comment by zhuangjiaju** [comment]
这个需要自己去合并，目前不支持解析list
