### ISSUE TITLE
获取首行为空

### ISSUE THREAD

**Issue by zhaochuanzhen** [alibaba/easyexcel#1925]
com.alibaba.excel.write.handler.RowWriteHandler#afterRowDispose
在写入第2行时，获取第一行的表头，此时获取到的Row有时候为空，为什么呢，难道RowWriteHandler不是按照写入顺序、写入一行执行一次吗
![image](https://user-images.githubusercontent.com/17918232/117643457-fd802800-b1ba-11eb-97d4-b200de8f8852.png)

**Comment by JackeyXps** [comment]
请问有没有复现bug的文件和代码样例？

**Comment by zhaochuanzhen** [comment]
Row firstRow = writeSheetHolder.getSheet().getRow(0);
图中获取第0行时为空，本地复现不了

**Comment by zhuangjiaju** [comment]
所有的数据获取一次后不会存储，所以第二行获取第一行为空，建议自己存储第一行。

**Comment by guangshuowang** [comment]
我在afterWorkbookDispose方法里也遇到了这种情况，奇怪的不是总是空，我这第一次获取就是空的，没法保存
