### ISSUE TITLE
CellData中rowIndex，columnIndex为何不设置，保持为空，处于什么设计想法？

### ISSUE THREAD

**Issue by yuechao4039** [alibaba/easyexcel#1928]
在自定义Converter中想拿到rowIndex或columnIndex，结果拿不到

**Comment by yuechao4039** [comment]
在自定义Converter中想拿到rowIndex或columnIndex结果拿不到

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
