### ISSUE TITLE
注释能否添加？

### ISSUE THREAD

**Issue by heiheiyuan** [alibaba/easyexcel#193]

**Comment by zsf513** [comment]
确实，看了源码，里面好多地方没有注释，希望作者加上注释。

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。然后自定义拦截器去处理
