### ISSUE TITLE
List对象里面包含map

### ISSUE THREAD

**Issue by js20166098** [alibaba/easyexcel#1930]
如果我导出的格式是list实体对象集合，但是实体对象里面套了一个Map怎么弄。

**Comment by zhuangjiaju** [comment]
ExcelIgnore 忽略掉不需要的数据即可

**Comment by js20166098** [comment]
有些场景map需要打印出来，是否可以通过注解解析生成的时候扫描例如声明@Map的形式，遇到这个就遍历打印
