### ISSUE TITLE
希望增加在自定义转换器中，可以获取到当前行的整行数据（或当前对象）

### ISSUE THREAD

**Issue by Xiaotian0617** [alibaba/easyexcel#1931]
举个实际场景。

用户 A，B，分别隶属于两个工种（厨师和园丁）
但他们都有一个共同的属性 即  工作工具。
厨师的工作工具属性可能会是一个单独的枚举。
园丁的工作工具属性会是一个新的单独的枚举。

这样的话，导出 Excel ，就需要判断他们的角色，继而进行字段的转换。

望采纳。

**Comment by caifenglin** [comment]
这个功能确实很重要，之前遇到过，没办法处理，只能for循环处理数据了

**Comment by zhuangjiaju** [comment]
这个需要自己用string 读取 然后转换。
