### ISSUE TITLE
invoke上添加@Transactional，手动事务回滚失败

### ISSUE THREAD

**Issue by wsndw** [alibaba/easyexcel#1932]
业务需求：
读excel时在一个invoke会分成两次insert
在第二次失败时，使用手动事务回滚`TransactionAspectSupport.currentTransactionStatus().setRollbackOnly();`
我的@Transactional注解是打在invoke方法上的
这时候会报错
`com.alibaba.excel.exception.ExcelAnalysisException: org.springframework.transaction.NoTransactionException: No transaction aspect-managed TransactionStatus in scope`

可能指向excelReader.read(readSheet);
我还有什么办法可以实现事务回滚吗？

**Comment by sizzlecar** [comment]
easyexcel 的listener 没有被Spring 管理，所以不能用事物注解，可以使用 TransactionTemplate 手动回滚

**Comment by zhuangjiaju** [comment]
这个需要自己了解下spring事务的原理。
建议在 读的最外层 直接加入事务注解即可。
