### ISSUE TITLE
excel填充数据能使用转换器吗？还有根据模板写入的时候不能带上样式很鸡肋

### ISSUE THREAD

**Issue by liweiye-2021** [alibaba/easyexcel#1933]
其实我的需求就是写excel，需要较多样式，不想写各种注解，直接用excel模板弄好样式来写入。
结果excel填充貌似用不了转换器，根据excel模板写内容又带不上模板自身的样式

**Comment by zhuangjiaju** [comment]
使用填充可以带上样式
