### ISSUE TITLE
web 中可以写多个sheet吗？

### ISSUE THREAD

**Issue by MrPierce34** [alibaba/easyexcel#1934]

**Comment by MrPierce34** [comment]
figure out

**Comment by LucasDove** [comment]
@MrPierce34 能分享一下您的方案吗？

**Comment by MrPierce34** [comment]
> 
> 
> @MrPierce34 能分享一下您的方案吗？

ExcelWriterBuilder writerBuilder = EasyExcel.write(response.getOutputStream());
            ExcelWriter excelWriter = writerBuilder.build();

            //第一张sheet
            int sheetNo = 0;
            List<List<String>> firstSheetHead = firstSheetHead();
            ExcelWriterSheetBuilder firstSheetBuilder = EasyExcel.writerSheet(sheetNo, citycode + "-" + sheetNo)
                    .head(firstSheetHead)
                    .registerWriteHandler(new CustomColumnWidthStyleStrategy(columnIndex2columnWidth(firstSheetHead)));
            excelWriter.write(firstSheetData(firstSheetData), firstSheetBuilder.build());

            //第二张sheet
            sheetNo++;
            ExcelWriterSheetBuilder secondSheetBuilder =
                    EasyExcel.writerSheet(sheetNo, citycode + "-" + sheetNo).head(Entity.class);
            registerWriteHandler(count, secondSheetBuilder);
            excelWriter.write(secondSheetData, secondSheetBuilder.build());

            excelWriter.finish();
