### ISSUE TITLE
什么时候能够兼容poi的4.xx版本

### ISSUE THREAD

**Issue by NeverBack2015** [alibaba/easyexcel#1935]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**

**Comment by lethal233** [comment]
确实，有一些bug就是poi库版本引起的，不得不拉出源码出来重写 #1624 
然后 #1937   也是因为poi库导致的bug。 
@NeverBack2015 @zhuangjiaju

**Comment by xishian** [comment]
POI出5.0.0了

**Comment by NeverBack2015** [comment]
感谢大佬，🎉🎉



在 2021-06-23 15:20:37，"QyLin" ***@***.***> 写道：

POI出5.0.0了

**Comment by zhuangjiaju** [comment]
目前兼容 poi 4.1.2
