### ISSUE TITLE
非对象读取 java.lang.NumberFormatException

### ISSUE THREAD

**Issue by wangruice** [alibaba/easyexcel#1936]
`java.lang.NumberFormatException
com.alibaba.excel.exception.ExcelAnalysisException: java.lang.NumberFormatException
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.parseXmlSource(XlsxSaxAnalyser.java:183)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.execute(XlsxSaxAnalyser.java:201)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:115)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:182)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:172)
`	
code:
非对象读取
`String savePath = "test.xlsx";

EasyExcel.read(savePath, new AnalysisEventListener<LinkedHashMap<Integer,String>>() {
    @Override
    public void invoke(LinkedHashMap<Integer,String> data, AnalysisContext context) {
        count++;
        System.out.println("num:" + count);
        System.out.println(data);
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
        System.out.println("doAfterAllAnalysed");
    }

    /**
     * 这里会一行行的返回头
     *
     * @param headMap
     * @param context
     */
    @Override
    public void invokeHeadMap(Map<Integer, String> headMap, AnalysisContext context) {
        System.out.println(headMap);
    }
}).sheet(0).autoTrim(true).doRead();	
`
读取数据列报错例子：216182179759700115

**Comment by lethal233** [comment]
@wangruice 
我这边测试的没问题，代码如下：
```java
public class Issue1936Test {
    public static void main(String[] args) {
        String savePath = TestFileUtil.getPath() + "demo" + File.separator + "test.xlsx";
        EasyExcel.read(savePath, new AnalysisEventListener<LinkedHashMap<Integer,String>>(){
            int count = 0;
            @Override
            public void invoke(LinkedHashMap<Integer, String> data, AnalysisContext context) {
                count++;
                System.out.println("num:" + count);
                System.out.println(data);
            }

            @Override
            public void doAfterAllAnalysed(AnalysisContext context) {
                System.out.println("doAfterAllAnalysed");
            }

            @Override
            public void invokeHeadMap(Map<Integer, String> headMap, AnalysisContext context) {
                System.out.println(headMap);
            }
        }).sheet(0).autoTrim(true).doRead();
    }
}
```
excel 文件在此
[test.xlsx](https://github.com/alibaba/easyexcel/files/6501158/test.xlsx)

**Comment by wangruice** [comment]
我重新定位问题了，数字列里面有字符‘-’，请问如何设置能按字符串读取，不转成其他的类型
