### ISSUE TITLE
非对象读取，如何设置全部按字符串读取

### ISSUE THREAD

**Issue by wangruice** [alibaba/easyexcel#1938]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
直接读取 默认返回的就是字符串
