### ISSUE TITLE
关于excel导入导出乱码问题

### ISSUE THREAD

**Issue by yuyu414** [alibaba/easyexcel#1945]
使用了关于excel的导入导出，现在面临一个问题：我们的用户比较杂，他们电脑操作系统有的是win10、MacBook。然后他们的电脑的编码格式还不同，外加上有的使用微软的office、也有使用WPS。就导致了我们这边的导入导出乱码问题，主要是导入乱码的问题。
我看了源代码，未找到在解析表格的时候关于表格的格式的处理。
希望得到的帮助：
1.可能是我没有找到，如果有希望告知工具中获取表格文件编码格式的方法在哪里？
2.然后第一步完成之后，第二步需要按照编码读取。但是很可惜 我也没找到这个方法，请告诉我在哪里？
希望得到你们的帮助 谢谢~

**Comment by CeresY** [comment]
我也是导出多sheet页使用wps打开一直提示需要修复乱码，但是wps从来没有成功修复过。

**Comment by zhuangjiaju** [comment]
不用设置编码格式 你用最简单的读写 试试 都可以的。
