### ISSUE TITLE
使用ByteArrayOutputStream 写入 10万数据， 然后使用 ResponseEntity<byte[]>导出文件。 内存不释放

### ISSUE THREAD

**Issue by pengJeff** [alibaba/easyexcel#1954]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
ByteArrayOutputStream 本来就是在内存的
