### ISSUE TITLE
excel时间列解析错误 版本2.2.3

### ISSUE THREAD

**Issue by AugustFire** [alibaba/easyexcel#1956]
**触发场景描述**
制作excel 一行时间格式为yyyy-MM-dd HH:mm:ss  2022-06-15  23:59:59 ,然后手动鼠标右键拖动成2行(必须拖动)
2022-06-15  23:59:59
2022-06-16  23:59:59
2022-06-17  23:59:59

**触发Bug的代码**
```java
EasyExcel.read(fileName, CustomerGroupPriceImportDTO.class, defaultListener).sheet().doRead();
```
**提示的异常或者没有达到的效果**
得到的结果却是  (用字符串接受这个时间)  显然后面的记录少了1秒
2022-06-15 23:59:59
2022-06-16 23:59:58
2022-06-17 23:59:58

**Comment by zhuangjiaju** [comment]
这个应该是计算时间的有问题 实际查看poi 也有问题 具体原因我需要去排查下

**Comment by tmlx1990** [comment]
> 这个应该是计算时间的有问题 实际查看poi 也有问题 具体原因我需要去排查下

我试了下 好像是有59分59秒的这种会出现问题，目前看写入的excel的时候，自动填充的数据和手动写入的字段，转成数值类型，末几位存在差异。
<img width="452" alt="image" src="https://user-images.githubusercontent.com/5753992/167784175-52247447-5fc8-4909-8da8-54a1be1ac0b2.png">

<img width="453" alt="image" src="https://user-images.githubusercontent.com/5753992/167784232-2fe6ac96-b54b-4141-9f59-2be162a0258f.png">

**Comment by tmlx1990** [comment]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/5753992/167785691-c1f33b5b-03e8-485a-919e-64192bdf878e.png">
刚转成XML看了下 自动填充的59:59 是59:58.995

**Comment by zhuangjiaju** [comment]
这个问题已经在`3.2.0`中修复，建议升级到最新版本。
