### ISSUE TITLE
模板填充表格时继承CellWriteHandler接口,对某个单元格进行操作

### ISSUE THREAD

**Issue by liuyandeng** [alibaba/easyexcel#1959]
因为需求要在一个单元格中导出一张以上的图片,然后就实现了CellWriteHandler接口,手动填充某个单元格,重写afterCellDataConverted方法,但是Head对象参数一直为空,所以也不能head.getColumnIndex()获取单元格索引了,在什么情况下Head对象不为空呢,我的模板文件也设置了表头,截图如下
![image](https://user-images.githubusercontent.com/19473507/120128740-5446b380-c1f5-11eb-8232-a7d964bb5c1b.png)
![image](https://user-images.githubusercontent.com/19473507/120128754-5a3c9480-c1f5-11eb-849d-0f940ed3b0d8.png)
![image](https://user-images.githubusercontent.com/19473507/120128767-6294cf80-c1f5-11eb-9aaa-fbc8d4ec6a07.png)
![image](https://user-images.githubusercontent.com/19473507/120128775-658fc000-c1f5-11eb-9846-69d1e6a7f84c.png)
![image](https://user-images.githubusercontent.com/19473507/120128780-69234700-c1f5-11eb-8e80-f5cd098f869c.png)

**Comment by liuyandeng** [comment]
@zhuangjiaju 

    /**
     * 读取excel
     * @param args
     */
    public static void main(String[] args) throws Exception {
        String templateFileName =  "E:/upload/ExcelFill.xlsx";
        File file = new File(templateFileName);
        if (!file.exists()) {//不存在这个文件
            System.out.println("模板文件不存在");
            InputStream inputStream = ExcelFill.class.getClassLoader().getResourceAsStream("templates/ExcelFill.xlsx");
            int index;
            byte[] bytes = new byte[1024];
            FileOutputStream downloadFile = new FileOutputStream(templateFileName);
            while ((index = inputStream.read(bytes)) != -1) {
                downloadFile.write(bytes, 0, index);
                downloadFile.flush();
            }
            downloadFile.close();
            inputStream.close();
        }
        List<FillData> list = new ArrayList<FillData>();
        for(int i=1;i<=5;i++){
            FillData fillData = new FillData();
            fillData.setTest1("姓名"+i);
            fillData.setTest2("性别"+i);
            fillData.setTest3("年龄"+i);
            fillData.setTest4("手机号"+i);
            fillData.setTest5("学历"+i);
            fillData.setTest6("家庭住址"+i);
            fillData.setImgUrl( new URL("http://file.fangzuobiao.com:9000/5,04e1833f2957e9.jpg"));
            list.add(fillData);
        }
        String currentDate = DateUtil.getStringDateNum();//当前时间
        String fileName =  "Excel填充案例" +currentDate+".xlsx" ;
        String url = "http://localhost:8080/" + fileName;
        System.out.println(url);
        try {
            //EasyExcel.write("E:/upload/" +fileName).withTemplate(templateFileName).sheet().doFill(list);
            EasyExcel.write("E:/upload/" +fileName, FillData.class).registerWriteHandler(new MyCellWriteHandler()).withTemplate(templateFileName).sheet().doFill(list);
        }catch (Exception e){
            File errorFile=new File("E:/upload/" +fileName);
            errorFile.delete();
            e.printStackTrace();
        }

    }

**Comment by zhuangjiaju** [comment]
填充head 永远为空。
