### ISSUE TITLE
填充数据后公式显示异常

### ISSUE THREAD

**Issue by 1255598067** [alibaba/easyexcel#1962]
**代码**
   ExcelWriter excelWriter = EasyExcel.write(CreateExcelPath).withTemplate(TemplExcelPath).build();
          Workbook workbook = excelWriter.writeContext().writeWorkbookHolder().getWorkbook();
            //设置强制计算公式：不然公式会以字符串的形式显示在excel中
          workbook.setForceFormulaRecalculation(true);
          WriteSheet writeSheet = EasyExcel.writerSheet().build();
          excelWriter.fill(stringObjectMap, writeSheet).finish();
**问题**
数据填充后，最下面的公式计算也对改变了，但是在预览的时候计算的值还是未填充之前的，这个时候打开文件按下ctrl+S再预览就是最新的数据了请问这是为什么呢？

**Comment by zhuangjiaju** [comment]
这个设置的意思是 在打开之后重新计算数据。

**Comment by zhangjing007** [comment]
请问这个问题你解决了吗？

**Comment by dochaocn** [comment]
也遇到了一样的问题，重新打开后需要重新保存，请问解决了吗，感谢

**Comment by zhangjing007** [comment]
> 也遇到了一样的问题，重新打开后需要重新保存，请问解决了吗，感谢

没有解决哦。我最后是通过在windows环境下写了一个接口，然后java调取接口保存一下。😂😂😂
