### ISSUE TITLE
关于直接写入web中，重复写入问题。

### ISSUE THREAD

**Issue by xuanyupan** [alibaba/easyexcel#1965]
在demo例子web中的写部分，写这一步操作。
` EasyExcel.write(response.getOutputStream(), DownloadData.class).sheet("模板").doWrite(data()); `
与代码注释的提示
 `3. 直接写，这里注意，finish的时候会自动关闭OutputStream,当然你外面再关闭流问题不大；`
这个doWrite方法 finish 直接关闭了流。 

这块代码能否改善一下？支持重复写入然后用户主动关闭流。这里关闭流了实际请求就已经返回了。
面对多此获取数据场景就只能先去查询构造完所有的数据再去写，不能边获取数据后边写了。
这块能否优化下支持重复写入，不关闭流来应对多数据的情况？

**Comment by ZanePoe** [comment]
可以设置不自动关闭流，ExcelWriter excelWriter = EasyExcel.write(zip)
                    .withTemplate(resource.getFile()).autoCloseStream(Boolean.FALSE).build();
然而easyexcel 这个不自动关闭流的功能是假的，依然会自动关闭流，之前提的issue还被关闭了，debug就知道，在判断自动关闭流之前，流就已经被关闭了；
![image](https://user-images.githubusercontent.com/16047426/122786031-77412080-d2e6-11eb-94f8-0fcbf5b4b0f3.png)

**Comment by zhuangjiaju** [comment]
这个研究下了 poi 写死的暂时无法修改
