### ISSUE TITLE
图片导出功能能否将图片嵌入单元格内

### ISSUE THREAD

**Issue by Cocoaccc** [alibaba/easyexcel#1966]
现在导出图片是以悬浮方式在excel单元格上的，删除整行数据是无法删除图片的，有办法将图片嵌入单元格内解决这个问题吗？

**Comment by lainT** [comment]
你好，图片可以指定位置导出吗

**Comment by Cocoaccc** [comment]
可以的，看下文档里是有demo的。https://www.yuque.com/easyexcel/doc/write#cb1b271f

**Comment by Cocoaccc** [comment]
> 你好，图片可以指定位置导出吗

可以的，看下文档里是有demo的。https://www.yuque.com/easyexcel/doc/write#cb1b271f

**Comment by lainT** [comment]
> > 你好，图片可以指定位置导出吗
> 
> 可以的，看下文档里是有demo的。https://www.yuque.com/easyexcel/doc/write#cb1b271f

谢谢，我刚也成功了，不过图片的大小设置(imageData 注解设置的)有问题，没作用，这个你有遇到吗

**Comment by Cocoaccc** [comment]
> mageData 注解设置的

你好，我是直接用的属性+样式注解，没有遇到问题。
