### ISSUE TITLE
你的dome跟能不能弄个具体一点的,还用@Test,一点步骤都没有

### ISSUE THREAD

**Issue by lyqzzwAdmin** [alibaba/easyexcel#1970]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**

**Comment by heliusjing** [comment]
你指的是Demo?

**Comment by lyqzzwAdmin** [comment]
你好,问一下,你遇见过这个错误吗
com.alibaba.excel.exception.ExcelCommonException: Convert excel format exception.You can try specifying the 'excelType' yourself


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 你的dome跟能不能弄个具体一点的,还用@Test,一点步骤都没有 (#1970)





 
你指的是Demo?

**Comment by lethal233** [comment]
> ert excel format exception.You can tr

你总得把触发这个错误的描述/代码发出来大伙才能帮你看把。easyexcel的demo已经挺清楚的了，你有什么问题可以提issue问的

**Comment by zhuangjiaju** [comment]
这个错误大概率是 你的文件流错误。也就是文件指定错误。
