### ISSUE TITLE
注释最好规范一点

### ISSUE THREAD

**Issue by boatrainlsz** [alibaba/easyexcel#1971]
既然用英语注释，常见的语法错误就不要犯了。比如CellTagHandler中的it's mean明显就是错的，应该是it means

**Comment by plusmancn** [comment]
@boatrainlsz 如果楼主英文较好的话，建议提 PR 修正语法错误，共同参与社区建设。

**Comment by zhuangjiaju** [comment]
亲 非常欢迎加入啊 。四级刚过 六级没过，然后全靠谷歌翻译。可以加入帮忙翻译。笔芯。
