### ISSUE TITLE
如何引入项目？使用maven的示例？

### ISSUE THREAD

**Issue by mingRookieClimb** [alibaba/easyexcel#1973]
这个有maven直接引入吗？还是要打包到自己的私仓？

**Comment by heliusjing** [comment]
> 这个有maven直接引入吗？还是要打包到自己的私仓？

mavne 仓库一搜就有

**Comment by lethal233** [comment]
详情请见https://mvnrepository.com/artifact/com.alibaba/easyexcel

**Comment by bearxsh** [comment]
能通过jar包引入吗，目前项目不是maven项目

**Comment by bearxsh** [comment]
> > 这个有maven直接引入吗？还是要打包到自己的私仓？
> 
> mavne 仓库一搜就有

<br class="Apple-interchange-newline">能通过jar包引入吗，目前项目不是maven项目

**Comment by lethal233** [comment]
> > > 这个有maven直接引入吗？还是要打包到自己的私仓？
> > 
> > 
> > mavne 仓库一搜就有
> 
> 
> 能通过jar包引入吗，目前项目不是maven项目

你把源码编译打包成jar，然后导入自己工程试试？
