### ISSUE TITLE
AutoCloseStream设置为false不起作用，从源码上看就不能起作用

### ISSUE THREAD

**Issue by ZanePoe** [alibaba/easyexcel#1983]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
读取多个data在单线程中循环用ExcelWriter生成多个excel，并直接写入到ZipOutputStream中，期望在全部写入完成后关闭ZipOutputStream流。
**触发Bug的代码**
```java
for(int i=0;i<3;i++){
    ExcelWriter excelWriter = EasyExcel.write(zip)
                    .withTemplate(resource.getFile()).autoCloseStream(Boolean.FALSE).build();
zip.putNextEntry(new ZipEntry(name+
                    File.separator+"测试.xlsx"));
WriteSheet writeSheet = builder.build();
FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.TRUE).build();
 excelWriter.fill(data(), fillConfig, writeSheet);
excelWriter.finish();
}
```
**提示的异常或者没有达到的效果**
在写入之后就会立即关闭流，AutoCloseStream并不会起作用
代码在WriteContextImpl.java,如图：
![image](https://user-images.githubusercontent.com/16047426/122789646-1b789680-d2ea-11eb-913a-0bf1e4602a8f.png)
原因是在写excel文件的时候会创建一个临时文件，会包装一次传入的输出流，关闭临时文件之后，就自动关闭了传入的输出流，导致写入中断。
代码在SXSSFWorkbook.java 如图：
![image](https://user-images.githubusercontent.com/16047426/122790106-92ae2a80-d2ea-11eb-88f6-4aa00a2f1a57.png)

**Comment by ooooooook** [comment]
在读取的时候AutoCloseStream=false也不起效，可以自己封装一个包装流,  覆盖colse方法，避免EasyExcel在处理过程中关闭流。

![image](https://user-images.githubusercontent.com/28836525/124229576-67c0a380-db40-11eb-9cda-761dfc2f6c62.png)

![image](https://user-images.githubusercontent.com/28836525/124229733-a5253100-db40-11eb-8d73-8092ff3e439b.png)

这只是临时解决办法，希望官方可以早日修复。

**Comment by zhuangjiaju** [comment]
这个poi的 暂时无法修改 建议导出文件后再试
