### ISSUE TITLE
仓库地址在哪里？

### ISSUE THREAD

**Issue by chris-zh** [alibaba/easyexcel#1984]
请问仓库地址再哪里?

**Comment by 1332987** [comment]
这个不是工具jar包，这个只是阿里为了kpi写的项目

**Comment by 1332987** [comment]
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>easyexcel</artifactId>
    <version>2.2.10</version>
</dependency>

**Comment by 1332987** [comment]
`
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>easyexcel</artifactId>
    <version>2.2.10</version>
</dependency>
`

**Comment by 1332987** [comment]
`
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>easyexcel</artifactId>
    <version>2.2.10</version>
</dependency>
`

**Comment by jjnnzb** [comment]
https://search.maven.org/artifact/com.alibaba/easyexcel
