### ISSUE TITLE
重写了AnalysisEventListener的onException方法后，没抛出异常，但是碰到格式转化异常之后，程序还是直接停止运行了

### ISSUE THREAD

**Issue by sai117** [alibaba/easyexcel#1988]
重写了AnalysisEventListener的onException方法后，没抛出异常，但是碰到格式转化异常之后，程序还是直接停止运行了；

**Comment by sai117** [comment]
我想要的效果是遇到异常之后继续读取下一行，下面是我的代码
@Override
    public void onException(Exception exception, AnalysisContext context) {
        logger.info("解析出错：" + exception.getMessage());

        int row = 0, column = 0;
        if (exception instanceof ExcelDataConvertException) {
            ExcelDataConvertException convertException = (ExcelDataConvertException) exception;

            logger.error("解析出");
        }
    }

下面是我的运行结果
![image](https://user-images.githubusercontent.com/50079978/123360819-8bb04200-d5a0-11eb-889a-08aa1dc8f5d7.png)

**Comment by sai117** [comment]
可以看到此处我的程序直接停止运行了，我看了demo说的是支持继续读取下一行的，我的版本是2.2.10

**Comment by heliusjing** [comment]
> 可以看到此处我的程序直接停止运行了，我看了demo说的是支持继续读取下一行的，我的版本是2.2.10

你应该使用的是readSync方法，使用同步的这种方式，其内部自定义了一个listener，默认是抛出异常的

**Comment by sai117** [comment]
数据量大的情况下是推荐用doRead方法吗？确实，使用doReadSync方法会抛出异常

**Comment by chaochaoZhao** [comment]
请问，使用readSync方法的异常可以重写或者如何实现不中断呢？
