### ISSUE TITLE
The return data always null when using lombok annotation @Accessors(chain = true) on the Data object.

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/easyexcel#1989]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
使用lombok的注解@Accessors(chain = true)在需要导出数据的实体上时，会出现无法赋值给数据实例的情况。

**触发Bug的代码**
```java
@Data
@Accessors(chain = true)
@FieldDefaults(level = AccessLevel.PRIVATE)
public class XxxReaderVO {
    
    @ExcelProperty(index = 0)
    String xxx;
}
```
**提示的异常或者没有达到的效果**
Listener中返回的所有数据对象，字段均为null

**Comment by zhuangjiaju** [comment]
底层使用了cglib 目前cglib 无法支持 @Accessors(chain = true)
