### ISSUE TITLE
运行报错，编译可以，easyexcel2.2.10和poi4.1.2不兼容

### ISSUE THREAD

**Issue by DragonSuper** [alibaba/easyexcel#1990]
升级降级easyexcel都不行
日志：
{"msg":"Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.excel.write.ExcelBuilderImpl","code":500}
easyexcel就不能升级一下poi依赖吗？

**Comment by zhuangjiaju** [comment]
重新clean 项目试试。4.1.2 至少jdk8 所以升级没这么容易
