### ISSUE TITLE
Repeated write use outputStream export, excel file size zero.

### ISSUE THREAD

**Issue by breezezephyr** [alibaba/easyexcel#1996]
@Test
    public void repeatedWriteStream() throws IOException {
        String fileName = "/tmp/" + "repeatedWrite" + System.currentTimeMillis() + ".xlsx";
        // 这里 需要指定写用哪个class去写
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        ExcelWriter excelWriter = EasyExcel.write(os, DemoData.class).build();
        // 这里注意 如果同一个sheet只要创建一次
        WriteSheet writeSheet = EasyExcel.writerSheet("模板").build();
        // 实际使用时根据数据库分页的总的页数来
        for (int i = 0; i < 5; i++) {
            // 分页去数据库查询数据 这里可以去数据库查询每一页的数据
            List<DemoData> data = data();
            excelWriter.write(data, writeSheet);
        }
        FileUtils.writeByteArrayToFile(new File(fileName), os.toByteArray());
        // 千万别忘记finish 会帮忙关闭流
        excelWriter.finish();
    }
ExcelWriter excelWriter = EasyExcel.write(file, DemoData.class).build(); 写入文件OK，写入OutputStream会有问题。

**Comment by zhuangjiaju** [comment]
参照web中的写即可

**Comment by Buywatermelon** [comment]
这两天我也碰到了一样的问题。
发现这个问题的原因是因为真正写入流的时机是在finish()函数中。
![image](https://user-images.githubusercontent.com/49096074/225849426-8b7f003c-f666-4975-9ad3-271149b5f6e1.png)
具体的写入时机如上图所示。

这也意味着`FileUtils.writeByteArrayToFile(new File(fileName), os.toByteArray());`这行代码调用时，`os.toByteArray()`里是没有数据的。所以这里写入OutputStream会有问题。

**Comment by Buywatermelon** [comment]
> 参照web中的写即可

作者大大，在issues中有看到几个类似问题的issues。
就是将excel写入流后，没有显式或隐式的调用`finish()`方法，就去操作流中的字节（比如这个issue中将其写入文件中）。
是否能把类似的case补充在EasyExcel的常见问题文档中。
