### ISSUE TITLE
关于读取 Excel 日期的问题

### ISSUE THREAD

**Issue by duke-james** [alibaba/easyexcel#200]
如下图所示：我的Excel文件中日期实际为 2017/10/20 11:05:40，单元格显示格式为 yyyy/MM/dd，然后我再读取时只能取到年月日，取不到时分秒。
![image](https://user-images.githubusercontent.com/20369982/50627750-fce28180-0f6f-11e9-819b-b4f8934d7819.png)
![image](https://user-images.githubusercontent.com/20369982/50627902-a32e8700-0f70-11e9-97c8-287bbd5793ff.png)
![image](https://user-images.githubusercontent.com/20369982/50627919-bb060b00-0f70-11e9-91cd-760f83c7226c.png)
![image](https://user-images.githubusercontent.com/20369982/50627934-ce18db00-0f70-11e9-8b05-314748dd06b4.png)

**Comment by duke-james** [comment]
![image](https://user-images.githubusercontent.com/20369982/50628007-24861980-0f71-11e9-903a-f909d3a8e258.png)

**Comment by duke-james** [comment]
目前只有 03 xls的存在这个问题，07 xlsx 的是正常的

**Comment by dazong** [comment]
遇到类似问题，03和07读取excel日期返回的值不一样，07返回一个数字例如43511，03返回的是有格式的日期例如2-Feb-2019 ，建议统一

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
