### ISSUE TITLE
easyexcel 2.26版本怎么读取上传的excel文件总行数

### ISSUE THREAD

**Issue by RedA1ert** [alibaba/easyexcel#2001]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
建议直接读取整个文件获取行数
