### ISSUE TITLE
head类字段不全，出现数据错乱

### ISSUE THREAD

**Issue by ankoye** [alibaba/easyexcel#2004]
**触发场景描述**
假设 data 的数据（Class A）有20个字段，然后head（Class B）只有10个字段，这时导出的Excel会有数据错乱的可能。

**触发Bug的代码**
```java
   EasyExcel.write(response.getOutputStream())
                    .autoCloseStream(true)
                    .excelType(type)
                    .sheet(sheet)
                    .head(Class A)
                    .doWrite(Class B);
```

**出现的问题**
![Snipaste_2021-07-12_17-23-26](https://user-images.githubusercontent.com/56569932/125264084-21d0c000-e336-11eb-8b94-9576a1e7e695.png)

如图，在`com.alibaba.excel.write.executor.ExcelWriteAddExecutor#addJavaObjectToExcel`方法中，框住的那段。
这样设计的目的是为了 补全 Class A 字段的数据？（还没看懂这段代码的真正目的）
这里会出现几点问题，比如：
1 多出来字段的 cellIndex 在 row 中存在，这样导出的excel，原index数据被覆盖了
2 多出来字段的 cellIndex 在 row 中不存在，这样导出的excel，这些数据是没有表头的
3 多出来的字段需要converter，没有在Class B中忽略掉，还会报错

个人觉得可以不用这段代码，这样数据就会以 Class B 为准，并且不会出现错误。

**临时解决办法**
让Class B 的字段与Class A保持一致（或者直接使用 Class A），不需要的字段加@ExcelIgnore。

**Comment by zhuangjiaju** [comment]
这个功能是head 不是class 的情况下的处理方案，建议使用同一个class 不然会有很多情况。
