### ISSUE TITLE
读取Excel，表头为空时，invokeHeadMap无法读取表头行内容，无法处理表头为空的情况

### ISSUE THREAD

**Issue by xh752400584** [alibaba/easyexcel#2005]
**触发场景描述**
读表格，校验表头，表头行为空时，invokeHeadMap会直接跳过，只有有内容时，才会走此方法，无法捕获表头为空的读取
**触发Bug的代码**
![image](https://user-images.githubusercontent.com/39983251/125269429-8a2f8b00-e2bd-11eb-87ca-80fe9c349957.png)

**提示的异常或者没有达到的效果**
无法捕获表头为空的情况

**Comment by xiashui1994** [comment]
遇到了同样的问题，如果excel为空，vokeHeadMap会直接跳过，没有任何处理

**Comment by xh752400584** [comment]
读excel的时候默认是忽略空行的，已解决。加上这个就行啦。ignoreEmptyRow(false)
![image](https://user-images.githubusercontent.com/39983251/125615805-34a86af1-d60d-4ac3-9889-52f7563aa09f.png)

**Comment by xh752400584** [comment]
> 遇到了同样的问题，如果excel为空，vokeHeadMap会直接跳过，没有任何处理

加上ignoreEmptyRow(false)试试

**Comment by tianbsama** [comment]
> > 遇到了同样的问题，如果excel为空，vokeHeadMap会直接跳过，没有任何处理
> 
> 加上ignoreEmptyRow(false)试试

加上这个后，导入正常模板的话，就会生成很多条空数据，是什么原因
