### ISSUE TITLE
在Android中引入报有重复的类

### ISSUE THREAD

**Issue by api888** [alibaba/easyexcel#2006]
Duplicate class org.apache.xmlbeans.xml.stream.Location found in modules jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0) and jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.ReferenceResolver found in modules jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0) and jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.XMLEvent found in modules jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0) and jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.XMLInputStream found in modules jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0) and jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.XMLName found in modules jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0) and jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.XMLStreamException found in modules jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0) and jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.utils.NestedThrowable found in modules jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0) and jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0)
Duplicate class org.apache.xmlbeans.xml.stream.utils.NestedThrowable$Util found in modules jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0) and jetified-xmlbeans-2.6.0 (org.apache.xmlbeans:xmlbeans:2.6.0)

**Comment by yuzhiqiang1993** [comment]
有冲突的module，我是把冲突的module排除了可以正常运行：
`
    implementation('com.alibaba:easyexcel:2.2.10')
            {
                exclude group: 'org.apache.xmlbeans'
            }

`

**Comment by gotoorder** [comment]
@yuzhiqiang1993 用你的方法依然报错
com.alibaba.excel.exception.ExcelAnalysisException: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLEventFactory;
        at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:57)
        at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:145)
        at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:193)
        at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:229)
        at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:217)
