### ISSUE TITLE
关于导出数据，Excel怎么设置导出的内容格式都为文本，而不是常规格式

### ISSUE THREAD

**Issue by spectrelb** [alibaba/easyexcel#201]
举个列子导出身份证，导出后，修改以下，就变成科学计数法了，这样体验很不友好，能不能在导出的时候设置导出成文本格式

**Comment by PhilosophyBuns** [comment]
使用String类型，或者自己更改cell类型

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
