### ISSUE TITLE
读取excel文件不执行doAfterAnalysed方法

### ISSUE THREAD

**Issue by LibraSlyvia** [alibaba/easyexcel#2010]
从数据库直接导出的excel文件直接解析，invoke执行了，但是没有执行doAfterAnalysed方法。
但打开excel文件重新保存一下，invoke和doAfterAnalysed方法都执行了。

另外直接导出的文件会出现最后一条不进行invoke的情况，保存下excel文件又是正常的了。

**Comment by zhuangjiaju** [comment]
这个需要提供excel

**Comment by zhuangjiaju** [comment]
这个是否已经解决？如果未解决则重新打开问题。
