### ISSUE TITLE
复杂表头怎样自定义

### ISSUE THREAD

**Issue by Nuclear-Liu** [alibaba/easyexcel#2012]
我想实现复杂表头,表头背景色的不同应该怎样实现?

![image](https://user-images.githubusercontent.com/31722995/126428818-eda772bc-7e5d-42ea-a34a-39d4f663e343.png)

**Comment by wendongchao** [comment]
是否想实现这种
![image](https://user-images.githubusercontent.com/33962056/130033997-934e7995-2dca-4c25-a76a-25f9de9cf7a1.png)

**Comment by wendongchao** [comment]
还是这种效果
![image](https://user-images.githubusercontent.com/33962056/130040089-adacf0b7-75e8-44f5-9904-47e0c5cb8171.png)
这种类型在网上找的，链接：https://blog.csdn.net/NanXiaoFengCS/article/details/113375888

**Comment by Nuclear-Liu** [comment]
非常感谢是实现这种方式。

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
