### ISSUE TITLE
空列数据解析丢失

### ISSUE THREAD

**Issue by smart-techs** [alibaba/easyexcel#2014]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
不指定head class，excel读取的数据会丢失最后的空列
![image](https://user-images.githubusercontent.com/1968652/126750779-21e245f6-9aec-4aa3-865c-b22bfb8da42c.png)

**触发Bug的代码**
读取如上xlsx文件：
```java
  List<Map<Integer, String>> listMap = EasyExcel.read("test.xlsx").sheet().doReadSync();
```
**提示的异常或者没有达到的效果**
如上，结果columnC丢失，map只有两列，期望是返回3列内容

**Comment by ProphetCai** [comment]
+1 我也有这个问题

**Comment by zhuangjiaju** [comment]
map 仅仅会返回有数据的列，底层无法判断 你是1列 还是2列 还是3列，比如你第二行有4列，excel也会给你4列，和头没关系。
