### ISSUE TITLE
导出图片时如何设置图片在单元格上下内边距？

### ISSUE THREAD

**Issue by garbage-rubbish** [alibaba/easyexcel#2018]
现在导出的图片是完全铺满整个单元格，请问如何设置图片在单元格上下内边距？谢谢！

**Comment by zhuangjiaju** [comment]
参照：https://www.yuque.com/easyexcel/doc/write#cb1b271f
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
