### ISSUE TITLE
建议：对CGLIB的`BeanMap`不要强依赖

### ISSUE THREAD

**Issue by panlw** [alibaba/easyexcel#2021]
**建议描述**

![image](https://user-images.githubusercontent.com/60350/127278663-d94b4b56-6064-49fa-9e27-d5f6e6b44895.png)

可以提供两个接口（例如：BeanReader, BeanReaderFactory）让用户去实现BeanMap的功能：

- `BeanReaderFactory#newBeanReader(object): BeanReader`代替`BeanMap.create(object): BeanMap`
- `BeanReader#containsKey(String)`代替`BeanMap.containsKey(Object)`
- `BeanReader#get(String)`代替`BeanMap.get(Object)`
- `BeanReader#size()`代替`BeanMap.size()`

**Comment by zhuangjiaju** [comment]
这个需求是什么？没搞懂。设计中任何一块设计的越灵活越好，但是不能过度设计，抽象出一个reader当然更好，但是这一块目前没有用户述求需要使用。
