### ISSUE TITLE
不创建对象读取，判断不了日期数字那些

### ISSUE THREAD

**Issue by liweiye-2021** [alibaba/easyexcel#2027]

**Comment by liweiye-2021** [comment]
前提：基于对读的功能的大致使用，认真阅读了官方源码介绍。
效果：不创建对象的读取，可以判断字段是否为日期并对日期做对应的格式化处理。
开发过程：
1. AnalysisEventListener的使用看到CellData对象，尝试对CellData对象分析及怎么判断日期
2. excel中设置一些日期列，并且格式不一样比如有些是YYYY-MM-DD，有些是2021年8月4日
3. 对2中的excel进行普通的不创建对象读取，即官方的NoModelDataListener，并断点调试但是CellData对象实际为String，这样就不方便判断日期及改造
4. 查看官方源码介绍，读的时候默认处理器ModelBuildEventListener，查看相关源码，发现不加入自定义的readListener时默认使用ModelBuildEventListener，加入一个自定义的readListener则会使用2个即包括默认的，循环调用ReadListener。
5. 加入自定义的readListener，断点调试，发现在ModelBuildEventListener的时候CellData对象还是原始的CellData，但在自定义的处理器就变成string了，也就是ModelBuildEventListener做了转换。
6. 需要排除掉ModelBuildEventListener的使用，于是看了下源码取决于布尔变量useDefaultListener,也就最后使用EasyExcel.read(file,excelReadMapListener).useDefaultListener(false).sheet().doRead()即可在自定义的处理器中拿到CellData对象
7. 后面则是怎么对CellData来判断日期以及转为日期对象后再格式化，这里参考了poi源码的Cell接口相关的方法有对应日期判断和数字转为日期，把源码挪过来改造一些，终实现了功能，大致伪代码：
            ```
if(ExcelUtil.isCellDateFormatted(cellData)) {
                Date date = DateUtil.getJavaDate(cellData.getNumberValue().doubleValue(), false);
                map.put(key, DateUtils.dateToString(date,DateUtils.FORMAT_ONE));
            }
```

**Comment by 1054678524** [comment]
我也遇到了这个问题，不创建对象实现AnalysisEventListener<Map<Integer, String>>，虽然解决但是并不是真正的解决，通过断点发现，读取yyyy-mm-dd hh:mm:ss格式，发现秒丢失。我调整了excel表格的单元格式，自定义格式，解决了问题。

**Comment by 1054678524** [comment]
![image](https://user-images.githubusercontent.com/52780929/134859530-43b8a624-1a60-4438-9a27-902341aab736.png)

**Comment by cd-cd7** [comment]
大佬，我想请问一下关于自定义的时间格式，只展示分秒，不展示年月日的这种类型，自定义的listener解析不到全部数据，只能拿到分秒的文本数据，这种情况有没有大佬处理过的？
![image](https://user-images.githubusercontent.com/111980946/186410030-3016e9a8-de1d-4a27-9a3e-bad382e6fc7c.png)

**Comment by liweiye-2021** [comment]
这种没试过哦，之前的版本用的2.2.6，现在都出到3.1.1了，用最新版本试试吧，具体深入的问题只能研究源码POI了

**Comment by liweiye-2021** [comment]
有需要可以把文件发来测试

**Comment by cd-cd7** [comment]
这种数据格式在excel里面调整格式设置成短日期可以处理，但是客户非要求在程序里面实现。唉，我把文件发给您，麻烦您帮忙看看，谢谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 不创建对象读取，判断不了日期数字那些 (#2027)





 
有需要可以把文件发来测试
