### ISSUE TITLE
你好，通过Listener的方法读取，怎么只读第一行就停止读取，直接在监听器中向外抛异常吗？

### ISSUE THREAD

**Issue by leecx** [alibaba/easyexcel#2028]
你好，通过Listener的方法读取，怎么只读第一行就停止读取，直接在监听器中向外抛异常吗？
 @Override
    public void invoke(Map<Integer, String> data, AnalysisContext context) {
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
    }

**Comment by heliusjing** [comment]
看你监听器的父类，有一个方法控制是否继续读取下一行的，不需要把所有行都读取完毕才停止。抛异常也是一种路子，但不够优雅。

**Comment by fengyts** [comment]
我的正好相反，我在监听器中获取异常之后直接就不往后执行了，我不想让他停啊，怎么才能让他中间出现异常也不中断往后解析

**Comment by zhuangjiaju** [comment]
抛出`ExcelAnalysisStopException` 即可
