### ISSUE TITLE
二级表头相同时默认合并，

### ISSUE THREAD

**Issue by Ice450028456** [alibaba/easyexcel#203]
如下图：
![image](https://user-images.githubusercontent.com/17718701/50837778-72e35000-1397-11e9-8575-bd1aac91ef26.png)

错误信息如下：
![image](https://user-images.githubusercontent.com/17718701/50838028-06b51c00-1398-11e9-81a4-9f7326fff515.png)

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
