### ISSUE TITLE
创建 xlsx 文件，写入数据出现 sheet 名称重复问题

### ISSUE THREAD

**Issue by lhd951220** [alibaba/easyexcel#2039]
**异常代码**
```java
   package com.gdzd.download.stream;

import com.alibaba.excel.EasyExcel;
import com.alibaba.excel.ExcelWriter;
import com.alibaba.excel.support.ExcelTypeEnum;
import com.alibaba.excel.write.metadata.WriteSheet;

import java.io.File;
import java.util.List;
import java.util.UUID;

/**
 * @author Haidong Liu
 * @date 2021/8/4 10:09
 */
public class DataWriter {
    private final ExcelWriter excelWriter;

    private final String fileName;

    private final String fileUrl;

    public DataWriter(String parentUrl, String fileName) {
        this.fileName = fileName;
        fileUrl = parentUrl + fileName + ".xlsx";
        excelWriter = EasyExcel.write(fileUrl).excelType(ExcelTypeEnum.XLSX).inMemory(false).build();
    }

    public DataWriter(String parentUrl) {
        this(parentUrl, UUID.randomUUID().toString());
    }


    public DataWriter() {
       this("/home/lhd/data_download/");
    }

    public void write(List<DataModel> data, int sheetNo, String sheet, List<List<String>> head){
        WriteSheet writeSheet = EasyExcel.writerSheet(sheetNo, sheet).head(head).build();
        excelWriter.write(data, writeSheet);
    }

    public void finish(){
        excelWriter.finish();
    }

    public String getFileName(){
        return fileName;
    }

    public String getFileUrl(){
        return fileUrl;
    }

    public File getFile(){
        return excelWriter.writeContext().writeWorkbookHolder().getFile();
    }
}

```

**异常提示**
在 windows 下可以正常生成文件，在 linux 下，则在第一次写入数据时，即发生 sheet 名称重复

java.lang.IllegalArgumentException: The workbook already contains a sheet named 'BP1_B1电压0'
gdzd-download-xlsx | 	at org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetName(XSSFWorkbook.java:890)
gdzd-download-xlsx | 	at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:843)
gdzd-download-xlsx | 	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:679)
gdzd-download-xlsx | 	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:90)
gdzd-download-xlsx | 	at com.alibaba.excel.util.WorkBookUtil.createSheet(WorkBookUtil.java:66)
gdzd-download-xlsx | 	at com.alibaba.excel.context.WriteContextImpl.createSheet(WriteContextImpl.java:205)
gdzd-download-xlsx | 	at com.alibaba.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:182)
gdzd-download-xlsx | 	at com.alibaba.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:122)
gdzd-download-xlsx | 	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:53)
gdzd-download-xlsx | 	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
gdzd-download-xlsx | 	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)
gdzd-download-xlsx | 	at com.gdzd.download.stream.DataWriter.write(DataWriter.java:40)
gdzd-download-xlsx | 	at com.gdzd.download.stream.AbstractDownloadStreamProcessor.lambda$writeExcel$0(AbstractDownloadStreamProcessor.java:100)
gdzd-download-xlsx | 	at java.util.ArrayList.forEach(ArrayList.java:1257)
gdzd-download-xlsx | 	at com.gdzd.download.stream.AbstractDownloadStreamProcessor.writeExcel(AbstractDownloadStreamProcessor.java:79)
gdzd-download-xlsx | 	at com.gdzd.download.stream.DownloadStreamProcessor.lambda$process$0(DownloadStreamProcessor.java:118)
gdzd-download-xlsx | 	at java.util.ArrayList.forEach(ArrayList.java:1257)
gdzd-download-xlsx | 	at com.gdzd.download.stream.DownloadStreamProcessor.process(DownloadStreamProcessor.java:116)
gdzd-download-xlsx | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
gdzd-download-xlsx | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
gdzd-download-xlsx | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
gdzd-download-xlsx | 	at java.lang.reflect.Method.invoke(Method.java:498)
gdzd-download-xlsx | 	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
gdzd-download-xlsx | 	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
gdzd-download-xlsx | 	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
gdzd-download-xlsx | 	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:134)
gdzd-download-xlsx | 	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:62)
gdzd-download-xlsx | 	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
gdzd-download-xlsx | 	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133)
gdzd-download-xlsx | 	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106)
gdzd-download-xlsx | 	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:72)
gdzd-download-xlsx | 	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:570)
gdzd-download-xlsx | 	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:520)
gdzd-download-xlsx | 	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)
gdzd-download-xlsx | 	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)
gdzd-download-xlsx | 	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
gdzd-download-xlsx | 	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
gdzd-download-xlsx | 	at org.springframework.integration.endpoint.MessageProducerSupport.sendMessage(MessageProducerSupport.java:208)
gdzd-download-xlsx | 	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.access$1300(AmqpInboundChannelAdapter.java:65)
gdzd-download-xlsx | 	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.lambda$onMessage$0(AmqpInboundChannelAdapter.java:294)
gdzd-download-xlsx | 	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
gdzd-download-xlsx | 	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
gdzd-download-xlsx | 	at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter$Listener.onMessage(AmqpInboundChannelAdapter.java:290)
gdzd-download-xlsx | 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:1591)
gdzd-download-xlsx | 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.actualInvokeListener(AbstractMessageListenerContainer.java:1510)
gdzd-download-xlsx | 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:1498)
gdzd-download-xlsx | 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:1489)
gdzd-download-xlsx | 	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:1433)
gdzd-download-xlsx | 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:975)
gdzd-download-xlsx | 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:921)
gdzd-download-xlsx | 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$1600(SimpleMessageListenerContainer.java:83)
gdzd-download-xlsx | 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.mainLoop(SimpleMessageListenerContainer.java:1296)
gdzd-download-xlsx | 	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1202)
gdzd-download-xlsx | 	at java.lang.Thread.run(Thread.java:748)

**Comment by nengshengqian** [comment]
请问如何解决的
