### ISSUE TITLE
如何对excel文件中的数据进行修改？写excel的时候如何对某些cell设置样式？

### ISSUE THREAD

**Issue by mingjia-vip** [alibaba/easyexcel#204]
1，想修改excel文件中的cell数据及样式
2，写excel的时候只能通过模板的时候才能使用WriteHandler吗？我想写excel的时候对个别的cell设置样式应该怎么办？（List<String>无模型方式）

**Comment by PhilosophyBuns** [comment]
可以使用WriteHandler来为cell添加样式

**Comment by PhilosophyBuns** [comment]
参见这个 issus https://github.com/alibaba/easyexcel/issues/205

**Comment by mingjia-vip** [comment]
> 参见这个 issus #205

嗯谢谢，我现在也只是看到通过EasyExcelFactory.getWriterWithTempAndHandler方式的时候指定writeHandler可以设定样式（原来模板输入流可以指定为null）

**Comment by mingjia-vip** [comment]
> 可以使用WriteHandler来为cell添加样式
请问问题1怎么解决？

**Comment by mingjia-vip** [comment]
> 可以使用WriteHandler来为cell添加样式

请问问题1知道怎么处理吗？

**Comment by PhilosophyBuns** [comment]
> > 可以使用WriteHandler来为cell添加样式
> 
> 请问问题1知道怎么处理吗？
修改excel文件样式 也是要进行重新生成Excel的，也可以在writerHandler里面进行设置

**Comment by mingjia-vip** [comment]
> > > 可以使用WriteHandler来为cell添加样式
> > 
> > 
> > 请问问题1知道怎么处理吗？
> > 修改excel文件样式 也是要进行重新生成Excel的，也可以在writerHandler里面进行设置
就是先把数据读出来，然后再写入一个新的excel是吗？

**Comment by PhilosophyBuns** [comment]
> > > > 可以使用WriteHandler来为cell添加样式
> > > 
> > > 
> > > 请问问题1知道怎么处理吗？
> > > 修改excel文件样式 也是要进行重新生成Excel的，也可以在writerHandler里面进行设置
> > > 就是先把数据读出来，然后再写入一个新的excel是吗？

是的

**Comment by mingjia-vip** [comment]
> > > > > 可以使用WriteHandler来为cell添加样式
> > > > 
> > > > 
> > > > 请问问题1知道怎么处理吗？
> > > > 修改excel文件样式 也是要进行重新生成Excel的，也可以在writerHandler里面进行设置
> > > > 就是先把数据读出来，然后再写入一个新的excel是吗？
> 
> 是的

3q

**Comment by zhuangjiaju** [comment]
目前不支持修改。写的时候 需要样式 请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel  。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。设置`headRowNumber`即可
