### ISSUE TITLE
建议在readme中添加maven或gradle依赖坐标

### ISSUE THREAD

**Issue by Zongji** [alibaba/easyexcel#2041]
readme中添加maven或gradle依赖坐标说明，会方便初次使用的人员，使用者不用到处去找了。

**Comment by zhuangjiaju** [comment]
非常感谢您的意见，参照了spring等多个开源框架，未看到有直接写入的，暂时也先不加入。

**Comment by guogyh** [comment]
readme中添加maven或gradle依赖坐标说明，会方便初次使用的人员，使用者不用到处去找了。
