### ISSUE TITLE
导出的图片能不能固定在对应的单元格上

### ISSUE THREAD

**Issue by Henaner** [alibaba/easyexcel#2044]
现在excel导出的图片，这个图片是浮在excel单元格上面的。一旦手动调整了对应的单元格大小，图片就还在那里一动不动。请问作者能不能添加如下图所示的图片导出功能，图片就像是嵌入到单元格里面了，怎么改变单元格都不怕。
**类似下面这样**
![Image of Yaktocat](https://pic2.zhimg.com/v2-9b8c27796a72847b1c9414f5afdfd3d9_b.webp)

**Comment by zhuangjiaju** [comment]
参照图片导出：https://www.yuque.com/easyexcel/doc/write#cb1b271f
