### ISSUE TITLE
执行"读操作"时,报错Failed resolution of: Ljavax/xml/stream/XMLEventFactory;

### ISSUE THREAD

**Issue by shijia2118** [alibaba/easyexcel#2052]
调用该方法执行"读操作"时,报错了:EasyExcel.read("/storage/emulated/0/demo.xlsx", DemoData.class, new DemoDataListener()).sheet().doRead().

**Comment by zhuangjiaju** [comment]
贴全异常

**Comment by zhuangjiaju** [comment]
这个是否已经解决？如果未解决则重新打开问题。
