### ISSUE TITLE
能否将ClassUtils缓存变成可设置

### ISSUE THREAD

**Issue by zinny1990** [alibaba/easyexcel#2063]
由于2.1.1版本之后加入ClassUtils缓存，这样开发过程中，想要修改class属性，例如ExcelProperty注解index值，第一次修改生效，但是ClassUtils会缓存这个class，下次再调用同样的class导致，后续设置失效。
源码：
        synchronized (clazz) {
            fieldCacheSoftReference = FIELD_CACHE.get(clazz);
            if (fieldCacheSoftReference != null && fieldCacheSoftReference.get() != null) {
                return fieldCacheSoftReference.get();
            }
            declaredFields(clazz, convertAllFiled);
        }
        return FIELD_CACHE.get(clazz).get();
会去拿缓存class

**Comment by zinny1990** [comment]
@zhuangjiaju

**Comment by zhuangjiaju** [comment]
后续版本会将`ClassUtils.FIELD_CACHE` 改成public，运行之前clean 就行

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
