### ISSUE TITLE
从1w行开始读取excel数据，1w行前的数据不要，要设置哪个参数

### ISSUE THREAD

**Issue by 18359638560** [alibaba/easyexcel#2065]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java

   EasyExcelFactory.read(file, new TestListener()).headRowNumber(10000).doReadAll();
  除了这种设置表头行数的方法，还有其他的方法吗

```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
这个需要自己创建监听器，然后忽略前面的数据即可。无法做到数据直接中间读取。
