### ISSUE TITLE
怎样实现列表填充时 一条记录填充多行 后换行再填充下一条数据

### ISSUE THREAD

**Issue by Niarz1** [alibaba/easyexcel#2066]
![image](https://user-images.githubusercontent.com/76695199/132366074-7baabb10-4eee-496b-be9c-141381a06b44.png)
怎样实现列表填充时 一条记录填充多行 后换行再填充下一条数据

**Comment by zhuangjiaju** [comment]
这个目前不支持 建议使用jxls
