### ISSUE TITLE
@ColumnWidth 这个注解对性能影响大吗？如果导出有几万条数据的话，字段有五十左右

### ISSUE THREAD

**Issue by zhourui0105** [alibaba/easyexcel#2069]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
可以使用
