### ISSUE TITLE
单元格中多个字体样式

### ISSUE THREAD

**Issue by cheng1222** [alibaba/easyexcel#2102]
原始excel中一个单元格中有两行文字，两行文字的字体样式不一致，使用模板模式，只读取并设置了单元格的字体样式，有一个字体样式被改成了单元格的字体样式；
还有如果不使用模板模式，使用普通写的方法，如何在一个单元格中展示不同的字体样式

**Comment by zhuangjiaju** [comment]
https://www.yuque.com/easyexcel/doc/write#orUi8

**Comment by cheng1222** [comment]
之前访问云雀这个网站前好几次都没打开还以为错了，万分感谢提供帮助

**Comment by cheng1222** [comment]
> https://www.yuque.com/easyexcel/doc/write#orUi8

之前访问云雀这个网站前好几次都没打开还以为错了，万分感谢提供帮助
