### ISSUE TITLE
有模板的情况下如何获取模板里面的sheet并写入数据？

### ISSUE THREAD

**Issue by zeroabc** [alibaba/easyexcel#211]
如题，看了使用的说明文档，有模板的时候也是只能通过新建sheet写数据，请问能不能获取模板里面的sheet再写入数据？另外，写数据的时候不能随意修改单元格样式也是个很麻烦的问题，如果可以读取模板里面已经有的sheet的话，单元格样式直接改模板就好了，不用修改代码，代码只负责填充数据，这样才合理啊

**Comment by juzi214032** [comment]
请问你有找到方法吗？我也遇到这个问题了

**Comment by zeroabc** [comment]
> 请问你有找到方法吗？我也遇到这个问题了

没有，我找不到实现的方法，作者没回复。readme.md介绍的那个有模板的用法也不好使

**Comment by juzi214032** [comment]
> > 请问你有找到方法吗？我也遇到这个问题了
> 
> 没有，我找不到实现的方法，作者没回复。readme.md介绍的那个有模板的用法也不好使

我刚才找到方法了 用原生poi就可以，像这样对每个单元格设置数据，然后再写出文件就好

```java
            POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream("src/main/resources/表头.xls"));
            //读取excel模板
            HSSFWorkbook wb = new HSSFWorkbook(fs);
            //读取了模板内所有sheet内容
            HSSFSheet sheet = wb.getSheetAt(0);
            sheet.getRow(6).getCell(i).setCellValue(value);

            wb.write(fileOutputStream);

**Comment by zeroabc** [comment]
> ```java
> sheet 
> ```

其实这个easyexcel就是没有方法拿到已经存在的sheet

**Comment by zhangxiaosan123** [comment]
原生的poi向已有的xlsx追加内容，怎么做

**Comment by zhuangjiaju** [comment]
样式新版本已经支持。修改的话后面需要考虑

**Comment by 721806280** [comment]
@zhuangjiaju 修改样式多会支持？
