### ISSUE TITLE
继承AbstractColumnWidthStyleStrategy导致未注册成 CellWriteHandler实例

### ISSUE THREAD

**Issue by joker-pper** [alibaba/easyexcel#2112]
**代码**

` EasyExcel.write(new FileOutputStream(xxx))
                .head(Model.class)
                 .registerWriteHandler(new LongestMatchColumnWidthStyleStrategy()).registerWriteHandler(new XxxRowWriteHandler())
                .useDefaultStyle(false)
                .sheet("Sheet1")
                .doWrite(modelList);`

**提示的异常或者没有达到的效果**

在使用代码后自适应列宽的功能未生效进行debug打断点后发现未进入方法

**相关截图**

<img width="684" alt="debug" src="https://user-images.githubusercontent.com/20161452/135635595-0c2eb753-2e99-433b-a67b-28a7ddd41fdd.png">

<img width="684" alt="debug" src="https://user-images.githubusercontent.com/20161452/135635637-58cf60e2-a180-4dc6-ae70-6363d99e8ac2.jpg">

**其他**

经初步分析在 AbstractWriteHolder 类的 sortAndClearUpHandler方法中有过滤NotRepeatExecutor uniqueValue只会添加一次的逻辑，将导致 AbstractColumnWidthStyleStrategy （implements NotRepeatExecutor）的子类在未重写uniqueValue指定不同值的情况下都无法注册成为CellWriteHandler.class 的实例

**Comment by zhuangjiaju** [comment]
重写` String uniqueValue();` 方法 即可
