### ISSUE TITLE
对于ExcelProperty指定value无效，修改如下（建议作者给默认index设-1）

### ISSUE THREAD

**Issue by WangShuangQuan-A** [alibaba/easyexcel#213]
AnalysisContextImpl ：170行
`        if (head != null && headOneRow != null) {
            for (int i = 0; i < headOneRow.size(); i++) {
                for (String s : head) {
                    if (headOneRow.get(i).equals(s)) {
                        ExcelColumnProperty excelColumnProperty = this.excelHeadProperty.getExcelColumnPropertyMap2().get(s);
                        this.excelHeadProperty.getExcelColumnPropertyMap1().put(i,excelColumnProperty);
                    }
                }
            }
        }`
ExcelHeadProperty ： 78行
`if (p != null) {
            excelHeadProperty = new ExcelColumnProperty();
            excelHeadProperty.setField(f);
            excelHeadProperty.setHead(p.value());
            excelHeadProperty.setIndex(p.index());
            excelHeadProperty.setFormat(p.format());
            if (p.index() == ExcelColumnProperty.DEFAULT_INDEX) {
                excelColumnPropertyMap2.put(p.value(), excelHeadProperty);
            }else {
                excelColumnPropertyMap1.put(p.index(), excelHeadProperty);
            }
        } `

**Comment by zhuangjiaju** [comment]
这个在新版本已经处理
