### ISSUE TITLE
升级之后导出报错了java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by indiff** [alibaba/easyexcel#2136]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
        EasyExcel.write(response.getOutputStream(), XXX.class).autoCloseStream(Boolean.FALSE).sheet("测试").doWrite(result);

```
**异常提示**
 {"message":"下载文件失败java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.beans.BeanMap$Generator","status":"failure"}
**建议描述**

**Comment by chenmaochang** [comment]
我用的jdk17,升级之后也是这样,搞了一下午,maven依赖已经很干净没有冲突项,是cglib的反射机制改了

**Comment by chenmaochang** [comment]
加上这行到jvm参数里去 --add-opens java.base/java.lang=ALL-UNNAMED

**Comment by zhangloveyan** [comment]
> 

感谢  我也是同样的问题。。。

**Comment by zhangloveyan** [comment]
神奇的是 本地爆出的问题 和 正式环境的问题 不一样
