### ISSUE TITLE
关于在Linux上文件加密损坏的问题

### ISSUE THREAD

**Issue by TatobaZeroOne** [alibaba/easyexcel#2137]
这段代码在本地windows可以获取正常的文件，但是在Linux测试环境上文件会损坏。但是如果不使用加密，也不会损坏，是否是暂不支持Linux

 public static void exportSingleSheet(HttpServletResponse response, String password, String fileName, ExcelDataExportDto dto) throws IOException {
        fileName = StringUtils.isBlank(fileName) ? "test" : fileName;
        response.reset();
        response.setHeader("Content-Disposition",
                "attachment;filename=" + URLEncoder.encode(fileName + ".xls", "UTF-8"));
        response.setContentType("application/vnd.ms-excel;charset=UTF-8");
        response.setHeader("Pragma", "no-cache");
        response.setHeader("Cache-Control", "no-cache");
        response.setDateHeader("Expires", 0);
        EasyExcel.write(response.getOutputStream(), dto.getClazz()).autoCloseStream(true)
                .password(password)
                .sheet(dto.getSheetName())
                .doWrite(dto.getDataList());
        response.getOutputStream().flush();
        response.getOutputStream().close();
    }

**Comment by zhuangjiaju** [comment]
这个是否已经解决？未解决的话请重新打开问题
