### ISSUE TITLE
上传excel并读取遇到的问题

### ISSUE THREAD

**Issue by hzqgit** [alibaba/easyexcel#215]
做excel上传的时候，流是获取到了，但是在
     public static ExcelTypeEnum valueOf(InputStream inputStream){
        try {
            if (!inputStream.markSupported()) {
                return null;
            }
            FileMagic fileMagic =  FileMagic.valueOf(inputStream);
            if(FileMagic.OLE2.equals(fileMagic)){
                return XLS;
            }
            if(FileMagic.OOXML.equals(fileMagic)){
                return XLSX;
            }
            return null;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

inputStream.markSupported中报错，返回的为false，我上传的文件是xlsx类型的，确认没问题，看源码发现作者把值设为了true,我这边改不了源码，求解

**Comment by hzqgit** [comment]
问题解决了，文件流还要转成buffer,
inputStream = new BufferedInputStream(file.getInputStream());
建议作者在读取的时候标注下inputStream的类型，以免引起混淆。
EasyExcelFactory.read(inputStream, new Sheet(1, 1, ApiInputParamsModel.class));

**Comment by zhuangjiaju** [comment]
新版本 可以不用这个。遇到这个问题建议升级版本
