### ISSUE TITLE
你好，3.0.2这个版本，自定义head（List）后，使用@ColumnWidth注解会失效

### ISSUE THREAD

**Issue by cornucopib** [alibaba/easyexcel#2161]
之前有提过这个问题：
https://github.com/alibaba/easyexcel/issues/2143
但是3.0.2还是存在，麻烦看下，谢谢。

具体信息：

添加了：
EasyExcel.write(response.getOutputStream(), ExportedTaskDto.class)
                        .registerWriteHandler(excelManager.getExcelCellStyle())
                        .sheet(excelManager.getSheetName(language))
                        .head(excelManager.getHeaders(language))
                        .doWrite(exportedTaskDtoList); 

.head()加了这个设置，添加自定义head，@ColumnWidth还是会失效

**Comment by zhuangjiaju** [comment]
升级到`3.0.3`

**Comment by cornucopib** [comment]
> 升级到`3.0.3`

还是不行啊，3.0.3版本。设置了宽度没有变化。


@Data
@ColumnWidth(30)
public class ExportedTaskDto {
    @ColumnWidth(30)
    private Integer serialNumber;

    private String commonTaskName;

    private String priority;

    private String status;

    private String objectType;

    private String objectName;

    private String userAccount;

    private String scheduledStart;

    private String scheduledEnd;

    private String taskProcess;
}

**Comment by BoGeManger** [comment]
这个问题解决了吗，我升级到了3.0.5了

**Comment by cornucopib** [comment]
> 这个问题解决了吗，我升级到了3.0.5了

可以了。
