### ISSUE TITLE
自定义输出列没有按照指定顺序输出

### ISSUE THREAD

**Issue by crossyamaxun** [alibaba/easyexcel#2163]
建议输出Excel的时候，按照传入的属性名输出。

EasyExcel.write(response.getOutputStream(), BasSpacePackageVo.class)
                .sheet("自定义sheet名称")
                .includeColumnFiledNames(Lists.newArrayList("propName"))
                .doWrite(basSpacePackageVos);

**Comment by cornucopib** [comment]
试着，修改下：BasSpacePackageVo中定义的顺序和excel中从左到有的顺序一致，看看。

**Comment by crossyamaxun** [comment]
> excel

如果通过修改BasSpacePackageVo中属性的定义顺序的话，就不算动态按自定义传入includeColumnFiledNames输出了。这是个功能建议。不是bug.

**Comment by crossyamaxun** [comment]
翻到以前有这样的issue，已经列入开发计划。关闭
