### ISSUE TITLE
@HeadFontStyle 合并

### ISSUE THREAD

**Issue by anhw** [alibaba/easyexcel#2164]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
建议将类上的 @HeadFontStyle  和 属性上的 @HeadFontStyle  注解中的 属性合并，而不是属性直接覆盖类上的，比如
类上是  @HeadFontStyle(fontName = "宋体 (正文)",fontHeightInPoints = 12,color = 9)
属性上是 @HeadFontStyle(color = 10)
那属性的最终效果是 @HeadFontStyle(fontName = "宋体 (正文)",fontHeightInPoints = 12,color = 10

**Comment by zhuangjiaju** [comment]
这个需要使用3次注解
