### ISSUE TITLE
按照demo整合我的工程报错：Caused by: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by longxian435** [alibaba/easyexcel#2167]
![f68f23bac0eb1e109d257783f847d78](https://user-images.githubusercontent.com/9113179/139652891-64047686-d8f6-4380-9603-17f4390078a4.png)

![5dc712da61a54cbc4a91bb32b793c5a](https://user-images.githubusercontent.com/9113179/139652743-cac9f4ea-8e60-4590-95b5-5f3508af6a3c.png)
![068bdee6d60f0527aaa023f5f013502](https://user-images.githubusercontent.com/9113179/139652757-77eb95da-26f7-49c2-88bb-006da7d99e9d.png)
![5264f75a47bc5ff1c9653529fd729f5](https://user-images.githubusercontent.com/9113179/139652779-94e12eec-c966-43af-9db4-48522e491e55.png)

**Comment by zhuangjiaju** [comment]
确认下asm版本 大概率是版本冲突

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？未解决请重新打开问题
