### ISSUE TITLE
建议升级到 `2.2.11`

### ISSUE THREAD

**Issue by WilliamHua2016** [alibaba/easyexcel#2168]
建议升级到 `2.2.11`

_Originally posted by @zhuangjiaju in https://github.com/alibaba/easyexcel/issues/2157#issuecomment-954665712_

升级后发现整数读取有时候会加上“.0”， 例如11 读取成“11.0”,用的xlsx 文件

**Comment by zhuangjiaju** [comment]
提供下excel 目前最新版本是 读出来的就是你用office 软件打开的效果。

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？未解决请重新打开问题
