### ISSUE TITLE
web下载实例写法 逻辑不对

### ISSUE THREAD

**Issue by liaoyllv** [alibaba/easyexcel#217]
web下载实例写法里面输出文件之后再设置response不生效。

**Comment by gitHubForLz** [comment]
response.setContentType("multipart/form-data");
        response.setCharacterEncoding("utf-8");
      // UserInfo处有空格 导致后缀出错
        String fileName = fileName = new String(("UserInfo" + new SimpleDateFormat("yyyy-MM-dd").format(new Date()))
                .getBytes(), "UTF-8");
        response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx");

        ServletOutputStream out = response.getOutputStream();
        ExcelWriter writer = new ExcelWriter(out, ExcelTypeEnum.XLSX, true);
        Sheet sheet1 = new Sheet(1, 0);
        sheet1.setSheetName("第一个sheet");
        writer.write0(Arrays.asList(Arrays.asList("number1", "number2", "number3"), Arrays.asList("str1", "str2", "str3")), sheet1);
        writer.finish();
        out.flush();
// response响应头应在response.getOutputStream()前面;

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
