### ISSUE TITLE
导出的图片支持引用超连接吗，目前我只能给单元格链接超连接

### ISSUE THREAD

**Issue by Lanceff** [alibaba/easyexcel#2181]
@Override
    public void afterCellDataConverted(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, CellData cellData, Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {
        if (cellData.getType() == CellDataTypeEnum.IMAGE) {
            //设置列宽
            head.setColumnWidthProperty(new ColumnWidthProperty(90));
            //设置行高
            cell.getRow().setHeight((short) 2200);
            //设置单元格超连接
            CreationHelper helper = writeSheetHolder.getSheet().getWorkbook().getCreationHelper();
            Hyperlink hyperlink = helper.createHyperlink(HyperlinkType.URL);
            hyperlink.setAddress(cellData.getData().toString());
            cell.setHyperlink(hyperlink);
            cellData.setColumnIndex(relativeRowIndex);
        }
    }

**Comment by nanhuaijin** [comment]
或者说 poi有没有支持图片超链接的？ 一个单元格多张图片，每个一个超链接

**Comment by zhuangjiaju** [comment]
这个可以用自定义拦截器实现，或者成员变量定义成 `WriteCellData` 使用`3.0.5`版本。

**Comment by dnjat** [comment]
@zhuangjiaju 作者,你有说可以用自定义拦截器实现,可是ImageData并没有设置Hyperlink的方法, 除了能设置单元格的超链接,并没有找到其它地方还能设置超链. 想用Drawing create 但没有找到添加相关的方法., 我也是想一个单元格多张图片,每张图片一个链接.

**Comment by dnjat** [comment]
@Lanceff 你后面有找到什么方法实现吗

**Comment by chengmaoyun** [comment]
这个问题解决了吗？ @dnjat

**Comment by zkmingjing** [comment]
您好，我已经收到您的来信，我会尽快回复给您！

**Comment by chengmaoyun** [comment]
是的，我现在也遇到这个问题，设置图片所在的单元格超链接后，点击不跳转，需要把图片移开才能点击跳转


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 下午5:50
***@***.***&gt;;
抄送:&nbsp;"谁暖了 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 导出的图片支持引用超连接吗，目前我只能给单元格链接超连接 (Issue #2181)





 &nbsp;
 您好，我已经收到您的来信，我会尽快回复给您！
