### ISSUE TITLE
EasyExcel表头自定义颜色不生效

### ISSUE THREAD

**Issue by hnxydq** [alibaba/easyexcel#2182]
**异常代码**
```java
   @Override
    protected void setHeadCellStyle(Cell cell, Head head, Integer relativeRowIndex) {
        XSSFCellStyle cellStyle = (XSSFCellStyle) cell.getCellStyle();
        cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        cellStyle.setFillForegroundColor(new XSSFColor(new java.awt.Color(84, 131, 194)));
        cell.setCellStyle(cellStyle);
    }
```
**异常提示**
  重写AbstractCellStyleStrategy的上述方法，断点跟踪执行了，但是实际颜色未生效。
**建议描述**
  希望能帮忙看看这样使用是否正确？

**Comment by kaciry0927** [comment]
You can use this annotatoon `@HeadFontStyle(fontName = "等线", fontHeightInPoints = 11)`

**Comment by kangyu06** [comment]
+1，最后咋解决的啊

**Comment by santiini** [comment]
我是通过拦截器实现的:

**Comment by kaciry0927** [comment]
> 

WriteCellStyle cellStyle = context.getFirstCellData().getWriteCellStyle();
这个方法找不到呢，这是哪个版本的呢

**Comment by LuckyClover1** [comment]
> > 我是通过拦截器实现的:
> 
> ```java
>                 .registerWriteHandler(new CellWriteHandler() {
> 
>                     @Override
>                     public void afterCellDispose(CellWriteHandlerContext context) {
>                         if (context.getHead()) {
>                             XSSFCellStyle cStyle = (XSSFCellStyle) context.getWriteWorkbookHolder().getWorkbook().createCellStyle();
>                             cStyle.setFillForegroundColor(new XSSFColor(new Color(223, 169, 169)));
>                             cStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
> 
>                             WriteCellStyle cellStyle = context.getFirstCellData().getWriteCellStyle();
>                             // WriteCellStyle 中的 short 设置高于 XSSFCellStyle, 需要设置为 null
>                             cellStyle.setFillForegroundColor(null);
>                         }
>                     }
>                 })
> ```
我用这个方法试过了也没用

**Comment by anchogin** [comment]
> > 我是通过拦截器实现的:
> 
>                 .registerWriteHandler(new CellWriteHandler() {
> 
>                     @Override
>                     public void afterCellDispose(CellWriteHandlerContext context) {
>                         if (context.getHead()) {
>                             XSSFCellStyle cStyle = (XSSFCellStyle) context.getWriteWorkbookHolder().getWorkbook().createCellStyle();
>                             cStyle.setFillForegroundColor(new XSSFColor(new Color(223, 169, 169)));
>                             cStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
> 
>                             WriteCellStyle cellStyle = context.getFirstCellData().getWriteCellStyle();
>                             // WriteCellStyle 中的 short 设置高于 XSSFCellStyle, 需要设置为 null
>                             cellStyle.setFillForegroundColor(null);
>                         }
>                     }
>                 })

我用这个不生效，反而是最后一行是有用的，如
>                     @Override
>                     public void afterCellDispose(CellWriteHandlerContext context) {
>                         if (context.getHead()) {
>                             WriteCellStyle cellStyle = context.getFirstCellData().getWriteCellStyle();
>                             // WriteCellStyle 中的 short 设置高于 XSSFCellStyle, 需要设置为 null
>                             cellStyle.setFillForegroundColor(IndexedColors.RED.getIndex()); // 只有这一行设置颜色才有用，不设置就是黑的，>                             上面的其余的代码似乎没发现有效果
>                         }
>                     }
