### ISSUE TITLE
请问下针对自定义转换器怎么动态传参，比如LocalDateTime不同的时间格式

### ISSUE THREAD

**Issue by zxuanhong** [alibaba/easyexcel#2185]
**建议描述**
目前文档和示例都没有找到自定义转换器怎么动态传参，比如我自定义一个LocalDateTime转换器，我怎么传入时间格式，不可能这个接口导入是yyyy-MM-dd HH:mm，另外一个接口是yyyy年MM月dd日 HH时mm分，我又得重新弄一个转换器吧。。。。。感觉这个设计很不合理

**Comment by zhuangjiaju** [comment]
目前不支持动态传参，后续会规划

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
