### ISSUE TITLE
Can not close IO.

### ISSUE THREAD

**Issue by moshengkang** [alibaba/easyexcel#2195]
版本：
com.alibaba：easyexcel：2.2.10；
org.apache.poi：poi：4.1.0

代码：
try {
            //输出Excel文件
            response.setHeader("Content-disposition", "attachment; filename=" +
                    new String(fileName.getBytes(StandardCharsets.UTF_8), StandardCharsets.ISO_8859_1) + ".xls");
            response.setContentType("application/x-xls");
            ExcelWriter writer = EasyExcel.write(response.getOutputStream()).build();
            for (int i = 0; i < entities.size(); i++) {
                EasyExcelMoreSheetEntity entity = entities.get(i);
                Class clazz = entity.getClazz();
                List list = entity.getList();
                Map<String, String> vars = entity.getVars();
                resetCLassAnnotationValue(clazz);
                setExportClassAnnotation(clazz, vars);
                String sheetName = entity.getSheetName();
                List<WriteHandler> handlers = entity.getHandlers();
                ExcelWriterSheetBuilder builder = EasyExcel.writerSheet(i, sheetName);
                if (!ObjectUtils.isEmpty(handlers)) {
                    for (WriteHandler handler : handlers) {
                        builder.registerWriteHandler(handler);
                    }
                }
                WriteSheet writeSheet = builder.head(clazz).build();
                writer.write(list, writeSheet);
            }
        } catch (Exception e) {
            log.error("EasyExcel export more sheet excel error:[{}]", CommonUtil.getExceptionMessage(e));
        }
出现：Can not close IO.

**Comment by zhuangjiaju** [comment]
这个需要贴全堆栈异常

**Comment by JanGin** [comment]
```
                ExcelWriter writer = null;
		try {
                        response.setCharacterEncoding(StandardCharsets.UTF_8.toString());
			response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
			response.setHeader(HttpHeaders.CACHE_CONTROL, CacheControl.noCache().mustRevalidate().toString());
			response.setHeader(HttpHeaders.CONTENT_DISPOSITION, ContentDisposition.builder("attachment")
					.filename(fileName, StandardCharsets.UTF_8)
					.build().toString());
			response.setHeader(HttpHeaders.PRAGMA, "no-cache");
			response.setHeader(HttpHeaders.EXPIRES, "0");
			
			writer = EasyExcel.write(response.getOutputStream(), ExportOverallTrend.class)
					                    .needHead(Boolean.TRUE)
										.excelType(ExcelTypeEnum.XLSX)
					                    .autoCloseStream(Boolean.TRUE).build();
			WriteSheet sheet = EasyExcel.writerSheet(dto.getFilename())
					                   .registerWriteHandler(new CustomCellWriteHandler())
								.registerWriteHandler(getExcelWriterStrategy()).build();
			List<Data> data= excelService.getData(dto);
			writer.write(data, sheet);

		} catch (Exception e) {
			log.error("export data exception", e);
		} finally {
			if (writer != null) {
				writer.finish();
			}
		}
	}
```

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？未解决请重新打开
