### ISSUE TITLE
当数值小于1e-10，同时单元格样式为常规时，读入会变成0

### ISSUE THREAD

**Issue by kpshao** [alibaba/easyexcel#2196]
@Override
      public void invoke(Map<Integer, String> row, AnalysisContext analysisContext) {
          ....
      }

重载这个函数时，发现row中value值为0

可以参考附件表格中的第四列
[bug.xlsx](https://github.com/alibaba/easyexcel/files/7574574/bug.xlsx)

**Comment by zhuangjiaju** [comment]
这个自己可以设置double来读取，string的话会读取到你看到的。
