### ISSUE TITLE
2.2.6版本中再listener中的invoke方法里面怎么样throw exception才能让接口层捕获呢？

### ISSUE THREAD

**Issue by konghao1** [alibaba/easyexcel#2197]
看过issue中有写throw ExcelAnalyseStopException的，但是试过在invoke方法中throw并不能抛出异常，而是继续执行下一行代码，请问这个在2.2.6版本中怎么处理呢？或者是有没有其他的解决方法？感谢。

**Comment by FRookie** [comment]
直接抛不就行了？
![image](https://user-images.githubusercontent.com/33781946/142817408-342b5f05-3d61-4668-8ae1-93af0df8036d.png)
![image](https://user-images.githubusercontent.com/33781946/142817450-83062341-71a4-4cfa-b46a-e2d2b1eba838.png)

**Comment by qianzzbatt** [comment]
throw new RuntimeException 试试

**Comment by konghao1** [comment]
> 

我试过这样，但是在接口层拿不到异常信息，而且下一行数据会继续走invoke方法

**Comment by zhuangjiaju** [comment]
抛出rt异常即可，会被封装成 ExcelAnalyseException ，然后getCause即可
