### ISSUE TITLE
导出表格时表头名称异常（表头名称变成了表格名称）

### ISSUE THREAD

**Issue by ChangeLivingWorld** [alibaba/easyexcel#2199]
问题描述：
         服务部署采用的是Docker+ K8S，通过Jenkins部署安装后，导出数据到表格一切正常。替换其中与导出表格相关的微服务的补丁后，导出表格的表头名称，变成了表格的名称，导致文件为空。
版本：
        JDK8      EasyExcel 2.2.8（换成最新版本3.0.5亦无帮助）
服务器报错：
com.alibaba.excel.exception.ExcelGenerateException: java.lang.UnsatisfiedLinkError: /opt/jre-11.0.9/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

Caused by: java.lang.UnsatisfiedLinkError: /opt/jre-11.0.9/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

**Comment by ChangeLivingWorld** [comment]
![image](https://user-images.githubusercontent.com/70186321/142827780-e1852122-3d35-4f91-a48e-26c76a405ecc.png)
这是表格的图片描述

**Comment by zhuangjiaju** [comment]
这个 复现比较复杂，能否本地复现的？指定jdk版本之后

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？未解决请重新打开

**Comment by kiwimg** [comment]
这个问题怎么解决的?
