### ISSUE TITLE
关于自定义拦截器设置单元格格式

### ISSUE THREAD

**Issue by zhangxiaowei-wn** [alibaba/easyexcel#2200]
The maximum number of Cell Styles was exceeded. You can define up to 64000 style in a .xlsx Workbook 大量写的时候容易出现这种现象请问这个现在又解决方案吗

**Comment by 1842626921** [comment]
你好这种情况是因为重复创建样式造成的，因为最多支持64000个样式对象，其实我看到作者在3+版本做了相关优化。当出现重复样式的格子时候自动取前样式对象。你可以试着使用3+版本。或者自己在createStyle（）的时候做个重复样式的判断。希望能帮到您、

**Comment by zhuangjiaju** [comment]
升级到3.0.5 +版本 ，然后参照demo书写即可
