### ISSUE TITLE
导出几十个xls,堆内存实例hssf相关类直接进入老年代,并且相关实例非常多

### ISSUE THREAD

**Issue by create1072627512** [alibaba/easyexcel#2202]
![ce1eed950368c862985f9ae60ccbeda](https://user-images.githubusercontent.com/22511736/142962070-268ed5db-346c-40f9-a674-916f395d76f1.png)
![a02fe81d9989b9d3295c74811b7a096](https://user-images.githubusercontent.com/22511736/142962079-b2a874f4-7885-4361-afc2-eff969dc8e5f.png)

**Comment by zhuangjiaju** [comment]
建议 使用xlsx， xls本来就会存在这个问题
