### ISSUE TITLE
读取长数值类型（展示为科学计数法）的单元格时精度丢失

### ISSUE THREAD

**Issue by perry320** [alibaba/easyexcel#2204]
采用不创建对象的读取方法，读进来的都是字符串，字段原始文件里有的是带字母的编码 有的是不带字母的编码，但不带字母的长编码是数值类型的，读取后数值的字符串尾部发生了变化。
![(IN_( @6 VYG%WQH5L4I(@V](https://user-images.githubusercontent.com/38579045/143390260-662f9f76-b072-45fb-8f8c-3c4fefd64fdb.jpg)

![IN0@MU6)_MNO70UIPTX` @K](https://user-images.githubusercontent.com/38579045/143390285-810ef0c7-95a6-45f7-9dc8-ba3b19ed3bb8.png)

比如这样  一个是文本类型的编码  一个是数值类型的编码 他们的原始值是一样的
351030001351351000,  3.5103E+17(真实值 351030001351351000 )
![{MD0IG9B30U60(E808HZUWC](https://user-images.githubusercontent.com/38579045/143390218-cf41a84d-f439-4563-9761-f5a0361f8020.jpg)

读进来以后,数值类型的跟原始值不一样
351030001351351000，351030001351350980
![_%}D_FV14XX{8%OXDNXYXJX](https://user-images.githubusercontent.com/38579045/143390249-0058beb1-266d-49b6-a303-8180f2851c2e.jpg)

**Comment by sj1314520** [comment]
只需要在导出的时候设置一个转换器即可,例如
EasyExcel.write(fileName, cls)
.registerConverter(new LongStringConverter())
就会将Long类型的转换成String类型,就可以解决精度丢失
