### ISSUE TITLE
上传功能建议

### ISSUE THREAD

**Issue by shenningfly** [alibaba/easyexcel#2205]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
冒昧提一个需求，不知道我们这个插件是否支持，业务场景：按着指定模板上传exce数据，执行成功后结果 返回VO 属性包括执行总行数，成功数 和失败数的Toast提示，如果有失败数据自动下载错误数据为excel文件形式导出。

**Comment by shenningfly** [comment]
目前使用我们插件文件上传功能，怎么返回影响行数对象。

**Comment by kaciry0927** [comment]
在Listener中定义一个计数器，创建get方法即可获取
