### ISSUE TITLE
一个实体类的属性是否在导出文件的时候可以导出两列数据

### ISSUE THREAD

**Issue by Rich-Cheng** [alibaba/easyexcel#2207]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
两列的话 支持的。
如果是两行的话，不支持，需要创建2个对象
