### ISSUE TITLE
3.0.5版本会读多sheet的时候相关数据问题

### ISSUE THREAD

**Issue by 1842626921** [alibaba/easyexcel#2208]
我发现个很奇怪的问题；
问题场景：读的场景；一个Excel中有N个sheet，每个sheet都注册了监听器，结果其中走第一个sheet监听对象的时候doAfterAllAnalysed 方法走了一次，问题是走第二个sheet监听对象的时候doAfterAllAnalysed 方法走了两次，这里我看到第二个sheet的时候居然把第一个sheet也走了一次；加上自身的一次也就成了两次，以此类推。
总结问题：有N个sheet。则最后一个sheet就会把前面的sheet都走一次；其实只需要执行当前sheet就可以了，我会把每次监听器的校验后的sheet数据全部收集到一个新的Excel文件中，发现收集sheet数据时候发现也错乱了，拿到的是最后一个sheet的数据；

以下是相关代码：
![image](https://user-images.githubusercontent.com/48815267/143797596-831aee08-f9e0-4f2e-8e10-b8a62cfc9075.png)

![image](https://user-images.githubusercontent.com/48815267/143804144-975da65e-5e60-45b5-84e6-88c19a6b13f3.png)

![image](https://user-images.githubusercontent.com/48815267/143804385-40628d4c-7bd9-4ba3-ad07-f140f0a85b8b.png)

**Comment by 1842626921** [comment]
补充场景：每个sheet中有30条数据，为了保证一次走完数据，我 BATCH_COUNT 设置的是1000，然后出现了这种问题

**Comment by zhuangjiaju** [comment]
这个代码严重的问题 是
在for 循环里面 addlistener ，加了多次导致，参照下最简单的读即可
