### ISSUE TITLE
不创建对象读取excel，货币格式数据读取的数字为字符串

### ISSUE THREAD

**Issue by keven0706** [alibaba/easyexcel#2209]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
比如单元格数据1000,000 为货币形式，不创建对象读取时，为字符串1000,000  请问如何解决，谢谢！

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
自己需要自己创建对象 即可，不创建对象就是读到你在excel 看到的
