### ISSUE TITLE
3.0.5 版本读取到了空行

### ISSUE THREAD

**Issue by liangyi2017** [alibaba/easyexcel#2211]
代码读取到了空行，debug 看cellDataMap 里面有数据，所有 cell 的 type 值都是 CellDataTypeEnum.EMPTY

private void dealData(AnalysisContext analysisContext) {
        ReadRowHolder readRowHolder = analysisContext.readRowHolder();
        Map<Integer, ReadCellData<?>> cellDataMap = readRowHolder.getCellMap();
请看截图
![image](https://user-images.githubusercontent.com/34703695/144194747-14bea9e1-4f2b-4669-98d7-a3e4c99e1749.png)

excel 截图，下面的空白行也能被读到
![image](https://user-images.githubusercontent.com/34703695/144195444-8c80b421-e529-416c-ab15-7ba08b259af2.png)

**Comment by FengZhongShaoNian** [comment]
我刚刚也遇到了同样的问题

**Comment by Reagan1947** [comment]
> 代码读取到了空行，debug 看cellDataMap 里面有数据，所有 cell 的 type 值都是 CellDataTypeEnum.EMPTY
>
> ```java
> private void dealData(AnalysisContext analysisContext) { 
>   ReadRowHolder readRowHolder = analysisContext.readRowHolder(); 
>   Map<Integer, ReadCellData<?>> cellDataMap = readRowHolder.getCellMap();
>  
> ```
>
>  请看截图 ![image](https://user-images.githubusercontent.com/34703695/144194747-14bea9e1-4f2b-4669-98d7-a3e4c99e1749.png)
>
>
> excel 截图，下面的空白行也能被读到 ![image](https://user-images.githubusercontent.com/34703695/144195444-8c80b421-e529-416c-ab15-7ba08b259af2.png)

## 1. Sources Required

希望提供 Excel 原始文件，或能复现 bug 资源

## 2. Check Required

已知使用 @Accessors(chain = true) 会导致读空，ISSUE #1598

**Comment by MrGo123** [comment]
### 问题
同 3.0.5 版本读到空行。

### 使用背景
1. 使用 easyexcel 方式如官网 demo “最简单读示例”；
2. 未使用  @accessors(chain = true) ；
3. 解析数据量修改后的同一个Excel文件。

### 问题描述
解析同一个文件：
1. 每次解析的 Excel 文件为初次接收并解析时，能正常解析并识别有效行数。
2. 在该Excel文件的基础上追加数据后二次解析时，能正常解析并识别有效行数。
3. 问题：**在该Excel文件的基础上减少数据后再次解析时，能正常解析，但是解析行数为该文件上一次解析的最大有效行数，导致读取到空行**。

### 问题演示
1. 新建Excel文件，存入4条数据，正常解析：

![firstcommitresult](https://user-images.githubusercontent.com/53072382/155272523-14f4109c-ee15-4562-80f9-9a742b0dfb8c.png)

2. 在该文件基础上新增4条数据，正常解析：

![addDataresult](https://user-images.githubusercontent.com/53072382/155272628-19d377cf-6e09-4a5a-9105-b99ece4533ec.png)

3. 在该文件基础上减少6条数据，解析（含空行）8行数据：

![reduceDataresult](https://user-images.githubusercontent.com/53072382/155272765-2d0d2e3c-a28e-4bb2-8483-cf9be1476c8f.png)

dedug相关信息

![reduceDatadugInfo2](https://user-images.githubusercontent.com/53072382/155273093-ea8358c4-7ca6-40e8-bb68-c562ebc7c061.png)

![reduceDatadugInfo](https://user-images.githubusercontent.com/53072382/155273203-d809cbec-a005-4acc-b1a5-d97706c91cbe.png)

**Comment by CJH876492153** [comment]
这个目前有什么解决办法吗

**Comment by zhuangjiaju** [comment]
建议根据某一列为空的情况判断为空行
