### ISSUE TITLE
关于invoke抛出异常终止解析问题

### ISSUE THREAD

**Issue by Nicky213Zhang** [alibaba/easyexcel#2215]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
翻看其他问题，发现作者提示抛出该异常throw new ExcelAnalysisStopException()，照做之后，出现catch不到该异常的问题，而抛出throw new ExcelAnalysisException()却是可以被catch到，满足了业务要求，不知道是什么问题，还请作者帮忙解答下，感谢！！！
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by kaciry0927** [comment]
使用instanceof自定义需要捕获的异常

**Comment by zhuangjiaju** [comment]
这个会在3.1.0 版本中修复，后续所有rt异常都会直接给外部用户
