### ISSUE TITLE
2.2.11导入读取到空行

### ISSUE THREAD

**Issue by ChenMeng-1919** [alibaba/easyexcel#2216]
读取的代码为，已经设置了过滤空行
ZZAccountEntityListener zzAccountEntityListener = new ZZAccountEntityListener();
EasyExcel.read(file.getInputStream(), ZZAccountEntity.class, zzAccountEntityListener).ignoreEmptyRow(true).sheet().doRead();
List<ZZAccountEntity> ZZAccountlist = zzAccountEntityListener.getList();
excel中有 10行数据，读取到了27行
![image](https://user-images.githubusercontent.com/58204041/144578301-d7970c42-4faa-4283-8d7c-284de45310b2.png)
![image](https://user-images.githubusercontent.com/58204041/144578250-ded64b09-bd22-4c13-b822-2bb461f1bd66.png)
空行是我之前输入数据，但是后来把数据删除掉了

**Comment by gengxiz** [comment]
3.x 版本也有这个问题

**Comment by zhuangjiaju** [comment]
这会在3.1.0修复

**Comment by ChenMeng-1919** [comment]
> 这会在3.1.0修复

请问3.1.0计划什么时候上线
