### ISSUE TITLE
导出复杂报表时出现 force new row  copy出来的行，没有完整复制行的样式（比如合并单元格），修改了部分代码，望采纳。

### ISSUE THREAD

**Issue by czwanmmwhh** [alibaba/easyexcel#2219]
[code.zip](https://github.com/alibaba/easyexcel/files/7659310/code.zip)
我是使用的编译的类，没有使用源码，主要修改：ExcelWriteFillExecutor.shiftRows

下面是我导出的模版
[人员导出.xlsx](https://github.com/alibaba/easyexcel/files/7659323/default.xlsx)

**Comment by zhuangjiaju** [comment]
这个建议直接提交pr
