### ISSUE TITLE
registerConverter() 影响其他导出方法

### ISSUE THREAD

**Issue by wanggaodeng** [alibaba/easyexcel#2220]
在一个导出方法里注册了自定义转换器，导致defaultWriteConverter改变影响其他导出方法，怎么从defaultWriteConverter中删除自定义的转换器？
是自定义的转换器有问题吗，还是registerConverter没用对？

1. 第一次导出，未注册自定义转换器，defaultWriteConverter默认29个转换器
![2-29](https://user-images.githubusercontent.com/34469094/144960072-bb35ade4-05a7-42f5-825c-879c2061a3d0.png)
2. 自定义转换器
![image](https://user-images.githubusercontent.com/34469094/144960296-3f9b166f-5e95-477d-8207-694b202b447a.png)

3. 注册自定义转换器，
![image](https://user-images.githubusercontent.com/34469094/144959961-a46b22c6-5f81-440b-8946-9b12060a3955.png)

4. 注册自定义转换器后，其他导出方法导出时defaultWriteConverter都发生了变化，数量还是29个，但是有两个是我自定义的。
![4-29(1)](https://user-images.githubusercontent.com/34469094/144960635-c9eb5611-aa2f-4b62-9598-b562659691ad.png)
5. 再用其他导出功能时，没有注册转换器还是会加载两个自定义的转换器，影响导出功能。

**Comment by zhuangjiaju** [comment]
什么版本？我测试没问题

**Comment by wanggaodeng** [comment]
demo里有说明，应该是这个原因，我没看到。


王高登
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 晚上8:43
***@***.***&gt;;
抄送:&nbsp;"أنا ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] registerConverter() 影响其他导出方法 (Issue #2220)





 
什么版本？我测试没问题
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
