### ISSUE TITLE
导出数据间隔性带空行，是不是可以加一个忽略空行的配置

### ISSUE THREAD

**Issue by wypzj** [alibaba/easyexcel#2221]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
一个List<DTO>作为doWrite的对象，size是10，但是List中的对象不全是需要导出的（被标记了@ExcelProperty的属性值为null），这些不需要导出的对象就会变成空行
**触发Bug的代码**
下图被标记方法value值为null会默认创建个空的cell，如果整个对象里需要导出的属性值都是null，就会成为一个空行，不确定这种场景是不是需要处理
![image](https://user-images.githubusercontent.com/33473633/145385377-48c987df-af32-4cf9-9674-870e805cd61d.png)

**提示的异常或者没有达到的效果**

**Comment by kaciry0927** [comment]
Listener中判断EmptyBean即可

**Comment by zhuangjiaju** [comment]
这个需要字段判断对象是否为空
