### ISSUE TITLE
windows可以，ubantu不行，java.lang.reflect.invocationtargetexception-- null

### ISSUE THREAD

**Issue by 799452017** [alibaba/easyexcel#2226]
![image](https://user-images.githubusercontent.com/35019617/145804470-2c195e54-7b94-480b-b415-70cf1b2d97c1.png)
一切ok，到了服务器就凉，咱也看不懂这迷之报错。

**Comment by 799452017** [comment]
![image](https://user-images.githubusercontent.com/35019617/145804830-d465b82a-09d0-4e92-84d3-e02db25669ed.png)

**Comment by zhuangjiaju** [comment]
贴全异常

**Comment by zhuangjiaju** [comment]
这个是否已经解决？未解决的话请重新打开问题
