### ISSUE TITLE
读取file后，无法删除（3.0.5）

### ISSUE THREAD

**Issue by sandnul025** [alibaba/easyexcel#2228]
File file = new File("D:\\1.csv");
EasyExcel.read(file).sheet().doRead();
file.delete(); // false

**Comment by zhuangjiaju** [comment]
实际测试可以删除 什么场景？

**Comment by sandnul025** [comment]
> 实际测试可以删除 什么场景？

我在window上测试的，就定时任务去读取文件，读取完删除，刚才又试了一下。
``
@Slf4j
@Component
public class TestKafka {

    @Autowired
    private KafkaTemplate kafkaTemplate;

    private final String topic = "test_topic";
    private Boolean flag = true;

    @Scheduled(cron = "0/5 * * * * ?")
    public void produ() {

        if (flag) {
            File file = new File("D:\\1.csv");
            EasyExcel.read(file).sheet().doRead();
            System.out.println(file.delete());
            flag = false;
        }

        Map<String, Object> data = new HashMap<>();
        data.put("name", "test");
        data.put("desc", IdUtil.fastSimpleUUID());
        kafkaTemplate.send(topic, JSON.toJSONString(data));
    }

    @KafkaListener(id = topic, topics = topic)
    public void coum(ConsumerRecord consumerRecord) {
        System.out.println(consumerRecord.key() + " " +JSON.toJSONString(consumerRecord.value()));
    }
}

``

**Comment by zhuangjiaju** [comment]
有没有尝试过 不读取 直接删除？

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？如果未解决 请重新打开问题。
