### ISSUE TITLE
是否支持导出树形结构,并父节点数据不被合并？

### ISSUE THREAD

**Issue by xiongkai3538** [alibaba/easyexcel#2231]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
请详细描述您的问题

**Comment by zhuangjiaju** [comment]
这个是否已经解决？未解决的话请重新打开问题

**Comment by xiongkai3538** [comment]
已有解决方案

**Comment by YeYuZhang** [comment]
> 

请问如何导出树形结构

**Comment by xiongkai3538** [comment]
没导出树形结构。换了个思路，只是讲树形结构数据组装好了，第一列看起来是树形结构（类似1、1.1、这种）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月10日(周一) 中午11:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/easyexcel] 是否支持导出树形结构,并父节点数据不被合并？ (Issue #2231)




   
请问如何导出树形结构
