### ISSUE TITLE
用代码生成的模板填充时变量无法被替换

### ISSUE THREAD

**Issue by fuxujiang** [alibaba/easyexcel#2232]
![image](https://user-images.githubusercontent.com/5848645/146342665-11b7b2a2-8e76-4662-8859-8d18dbad18fa.png)

用easyexcel生成的模板, 使用该模板导出数据时, 第一行没有被替换, 且数据丢失;
求解~

**Comment by zhuangjiaju** [comment]
看下3.0.5版本试试

**Comment by zhuangjiaju** [comment]
这个是否已经解决？未解决的话请重新打开问题
