### ISSUE TITLE
3.0.5读取表格，出现异常如何回滚

### ISSUE THREAD

**Issue by jgybzx** [alibaba/easyexcel#2234]
/**
     * 每隔5条存储数据库，实际使用中可以100条，然后清理list ，方便内存回收
     */
    private static final int BATCH_COUNT = 10;
这个表示达到一定数量就去存到数据库里边。如果有这样的情况，第一批10条已经入库，但是第二批读取的时候，出现异常了，此时程序结束，第二批的10条没法报存。但是现在第一批10条已经入库了，如何在第二批报错的时候，回滚之前的报存操作呢？

**Comment by zhuangjiaju** [comment]
这个需要交给数据库 数据量不大用事务 数据量大了用版本号
