### ISSUE TITLE
想请教一下easyexcel使用监听器去读取excel的好处在哪

### ISSUE THREAD

**Issue by clip-tail** [alibaba/easyexcel#2235]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
感觉easyexcel中EasyExcel.read(Inputstream,Sheet)这个方法更符合人们读取excel的使用习惯，如果返回值可以是一个泛型就更好用了，但是这个方法已经打上了@Deprecated注解，并且官方文档上也并无提及，都是使用监听器去读取excel，请问是出于什么考虑的呢

**Comment by GuitarXY** [comment]
我觉得一个是规范吧，监听器可以自定义数据结果，一个避免导致ex太大oom,还可以过滤你不需要的数据，甚至读取到一半报异常你还可以把前面一半的数据保存起来，

**Comment by clip-tail** [comment]
> 我觉得一个是规范吧，监听器可以自定义数据结果，一个避免导致ex太大oom,还可以过滤你不需要的数据，甚至读取到一半报异常你还可以把前面一半的数据保存起来，

在官方文档上找到读成list<T>那种方式了，不过现在换了个名字，叫“同步的返回”
