### ISSUE TITLE
使用源码读取excel，出现读不全问题，有记录没读到

### ISSUE THREAD

**Issue by ycc20180408** [alibaba/easyexcel#2236]
用的是下载的3.0.5版本源码，有4行但是只读到3行，在ReadTest中的测试代码如下：
![image](https://user-images.githubusercontent.com/38174835/146733384-8ccc41ca-4f5a-47f2-b656-d5bdd86d6e3d.png)
这是读取用到的excel文件：
[产品资料模板 会少记录 - 副本 - 副本.xls](https://github.com/alibaba/easyexcel/files/7743549/-.-.xls)

**Comment by zhuangjiaju** [comment]
这个文件比较特殊，重新编辑保存后能解决问题。或者升级到`3.1.0`以后也会兼容这个文件
