### ISSUE TITLE
Excel设置单元格格式为整型或者百分数后，读取的为格式后的数据，而非实际值

### ISSUE THREAD

**Issue by franplk** [alibaba/easyexcel#2237]
比如：
1. Excel中实际值为 1.6，格式化后显示为2；读取后为 2，应该如何读取为 1.6
2. Excel中实际值为 0.1，百分数格式化为10%，如何读取为 0.1 而非 10%

**Comment by zhuangjiaju** [comment]
用 double 接收就可以
