### ISSUE TITLE
Can not close IO 线程安全

### ISSUE THREAD

**Issue by hbyscx001** [alibaba/easyexcel#2238]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
  try {
 ***
} finally {
    excelWriter.finish()
}
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**
爆出Stream is closed异常。
是不是由于finally中手动调用的finish与gc回收excelWriter时调用finalize并发冲突了？

**Comment by zhuangjiaju** [comment]
贴全异常看看

**Comment by zhuangjiaju** [comment]
这个是否已经解决？未解决的话请重新打开问题
