### ISSUE TITLE
EasyExcel的read方法

### ISSUE THREAD

**Issue by tenglin-git** [alibaba/easyexcel#2244]
EasyExcel如果有返回值为List<T> 的read方法会更好用，很多场景都需要直接读出一个结果，而不是放在PageReadListener里面，这块目前是
```
public PageReadListener(Consumer<List<T>> consumer) {
        this.consumer = consumer;
    }
```
不好从外界拿到返回值。

**Comment by zhuangjiaju** [comment]
用`doReadAllSync`会返回所有数据，但是容易oom。
这个用法的目的就是不让你外面拿到，在里面一批批的处理掉。
