### ISSUE TITLE
官方有没有自定义格式的例子啊找了很多没有找到

### ISSUE THREAD

**Issue by nuo010** [alibaba/easyexcel#2245]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
指定对单个字段使用注解设置单元格内容格式 想要设置居中 加粗 颜色等这些格式有没有

**Comment by zhuangjiaju** [comment]
`@ContentStyle` 设置

**Comment by zhuangjiaju** [comment]
`@ContentStyle` 设置
