### ISSUE TITLE
为什么web导出excel 是zip格式 不是 xlsx

### ISSUE THREAD

**Issue by gjklop** [alibaba/easyexcel#225]

**Comment by adonis2014** [comment]
@gjklop  解决了没？我也遇到这个问题

**Comment by ghostlwp** [comment]
![image](https://user-images.githubusercontent.com/18080269/53077230-8522e300-352c-11e9-9b15-08e04ff0c275.png)
![image](https://user-images.githubusercontent.com/18080269/53077266-94099580-352c-11e9-8bd5-77ce326406fc.png)
代码这样的，导出是zip
![image](https://user-images.githubusercontent.com/18080269/53077284-a257b180-352c-11e9-857c-9eaa1b6d5584.png)

**Comment by wapmnw** [comment]
直接调接口会出现这种吗？如果是前端页面调你的接口出现的，可以看看是不是因为前端服务器有代理

**Comment by yuzhaocai** [comment]
出现同样的问题，请问解决了吗？

**Comment by jeremain** [comment]
参考#217把response的头部参数设置提前

**Comment by 542869246** [comment]
这样就行。
`

    @GetMapping(value = "/exportExcel")
    public void exportExcel(HttpServletResponse response) throws Exception {
        PageData pd = this.getPageData();
        ExcelWriter writer = new ExcelWriter(getOutputStream("采购合同设备", response), ExcelTypeEnum.XLSX);
        Sheet sheet = new Sheet(1, 0, ThPurchaseBoxModel.class);
        sheet.setSheetName("sheet");
        sheet.setAutoWidth(Boolean.TRUE);
        List<ThPurchaseBoxModel> data = thPurchaseBoxService.selectPurchasesByPd4Excel(pd);
        writer.write(data, sheet);
        writer.finish();
    }


    /**
     * 导出文件时为Writer生成OutputStream.
     *
     * @param fileName 文件名
     * @param response response
     * @return ""
     */
    public OutputStream getOutputStream(String fileName,
                                                HttpServletResponse response) throws Exception {
        try {
            fileName = URLEncoder.encode(fileName, "UTF-8");
            response.setContentType("application/vnd.ms-excel");
            response.setCharacterEncoding("utf8");
            response.setHeader("Content-Disposition", "attachment; filename=" + fileName + ".xlsx");
            response.setHeader("Pragma", "public");
            response.setHeader("Cache-Control", "no-store");
            response.addHeader("Cache-Control", "max-age=0");
            return response.getOutputStream();
        } catch (IOException e) {
            throw new Exception("导出excel表格失败!", e);
        }
    }

`

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
