### ISSUE TITLE
请问下excel作为导出模板，某一列是下拉单元格，这个模板怎么定义

### ISSUE THREAD

**Issue by zxiaozhou** [alibaba/easyexcel#2253]
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**
1. excel文件作为模板怎么定义有下拉格式的列，如果设置会不能保存模板提示如下：
![image](https://user-images.githubusercontent.com/62740686/147540996-b632874c-518f-47e2-a006-f83ab70559d0.png)

**Comment by jiangxiaoqiang** [comment]
可以在数据验证里定义，不知道是不是你想要的效果
![image](https://user-images.githubusercontent.com/4521375/147555934-03447d77-1db2-4c0e-b475-e1b7a6aef9ec.png)

**Comment by jiangxiaoqiang** [comment]
![image](https://user-images.githubusercontent.com/4521375/147556028-87051925-16a6-47be-9b29-c9f7c186d78d.png)

**Comment by zxiaozhou** [comment]
问题是我无法定义填充字段，一定义提示不匹配无法保存



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月28日 18:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [alibaba/easyexcel] 请问下excel作为导出模板，某一列是下拉单元格，这个模板怎么定义 (Issue #2253) |

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiangxiaoqiang** [comment]
你要字典字段是动态的？

**Comment by zxiaozhou** [comment]
不是这个意思，你看我截图，我列表定义了一部分，定义有下拉列的不让保存，提示不匹配。能否提供一个模板，并且有一列是可以填充代有下拉验证的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月28日 19:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [alibaba/easyexcel] 请问下excel作为导出模板，某一列是下拉单元格，这个模板怎么定义 (Issue #2253) |

你要字典字段是动态的？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zxiaozhou** [comment]
你定义填充字段不就是使用{.data}的占位付吗？但有下拉列的不行，因为{.data}是与下拉列不匹配的，保存模板时直接不让保存



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月28日 19:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [alibaba/easyexcel] 请问下excel作为导出模板，某一列是下拉单元格，这个模板怎么定义 (Issue #2253) |

你要字典字段是动态的？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jiangxiaoqiang** [comment]
好吧，没明白。我也不知道怎么才能解决你的问题，抱歉

**Comment by zxiaozhou** [comment]
@jiangxiaoqiang 简单说，就是有下拉验证单元格的表格无法设置填充字段{.XXX},这是excel限制（只要设置就不让保存），有没有其他方式去设置填充字段{.XXX}

**Comment by songpo** [comment]
@jiangxiaoqiang 他的意思是单元格是下拉，比如你的数据来源是：离婚、离异、未婚、已婚，在这格式，你在单元格里，再输入占位表达式时，会报错，因为允许输入的值是：离婚、离异、未婚、已婚，不是${.data}

他想问的是这种情况下，这个单元格的模板信息怎么设置才可以保持下拉，并不会报错

**Comment by zxiaozhou** [comment]
对的，就是这个意思。我觉得我截图描述应该很清楚啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月31日 17:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [alibaba/easyexcel] 请问下excel作为导出模板，某一列是下拉单元格，这个模板怎么定义 (Issue #2253) |

@jiangxiaoqiang 他的意思是单元格是下拉，比如你的数据来源是：离婚、离异、未婚、已婚，在这格式，你在单元格里，再输入占位表达式时，会报错，因为允许输入的值是：离婚、离异、未婚、已婚，不是${.data}

他想问的是这种情况下，这个单元格的模板信息怎么设置才可以保持下拉，并不会报错

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by songpo** [comment]
@zxiaozhou 我觉得这个问题，可能确实不太好解决，或者从easyexcel不太容易解决。首先下拉框是通过excel的功能设置的，那么excel检测我们输入的表达式的时候，对于excel来说，数值肯定是非法的。
如果这是一个输出结果后的excel，那么我们可以通过检查如何给单元格的下拉设置数据来源的方式去排查问题；否则，这将是个不太好解决的问题，因为我们违背了excel的数据验证的要求。

**Comment by zhuangjiaju** [comment]
自定义拦截器试试
