### ISSUE TITLE
版本3.0.4、3.0.5(3.0.2、3.0.3版本正常)自定义excel模板导出无法保留原始样式

### ISSUE THREAD

**Issue by zxiaozhou** [alibaba/easyexcel#2255]
**提示的异常或者没有达到的效果**
1. 3.0.5版本无法保留使用excel作为模板导出的原始模板样式，导出结果如下，左边为导出结果，右边为模板，顶部data位置样式明显不一致
![image](https://user-images.githubusercontent.com/62740686/147624030-d9fb88d2-3d46-4111-aa8f-26612125d2c2.png)
2. 这是模板
[data.xlsx](https://github.com/alibaba/easyexcel/files/7787163/data.xlsx)
3. 已经测试3.0.2，3.0.3版本正常，能完整保留下来，3.0.1(无法测试报空指针)，3.0.4、3.0.5无法保留

**Comment by zhuangjiaju** [comment]
该问题已经在`3.1.0`+版本里面解决，最新版本：[![Maven central](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel)
