### ISSUE TITLE
ExcelWriter#write方法,接收data的类型为map时的问题. Excel没有数据

### ISSUE THREAD

**Issue by OnemansCity** [alibaba/easyexcel#2256]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
   `JSONArray jsonArray = JSON.parseArray(data);

            // 创建工作簿
            WriteWorkbook writeWorkbook = new WriteWorkbook();
            writeWorkbook.setExcelType(ExcelTypeEnum.XLSX);
            writeWorkbook.setCharset(Charset.forName("UTF-8"));
            writeWorkbook.setOutputStream(outputStream);
            writeWorkbook.setAutoCloseStream(Boolean.FALSE);

            // 创建sheet
            WriteSheet writeSheet = new WriteSheet();
            writeSheet.setSheetName(fileName);

            // 创建写入者,指定对应的工作簿
            ExcelWriter writer = new ExcelWriter(writeWorkbook);

            // 执行写入
            writer.write(head, writeSheet);
            writer.write(jsonArray.toJavaList(Map.class), writeSheet);#跟踪源码至com.alibaba.excel.write.executor.ExcelWriteAddExecutor#addOneRowOfDataToExcel中发现变量oneRowData判断为map类型
addBasicTypeToExcel(new MapRowData((Map<Integer, ?>)oneRowData), row, rowIndex, relativeRowIndex);
这一行的(Map<Integer, ?>)oneRowData是否应该是有问题的呢, 导致这个map没有变成预期的Map类型后面根据这个map获取key的时候入参是index但是对应的key实际上还是原本的字符串类型
最后导致出现问题的位置在com.alibaba.excel.write.executor.ExcelWriteAddExecutor#doAddBasicTypeToExcel内的一行
cellWriteHandlerContext.setOriginalValue(oneRowData.get(dataIndex));
`

```
**提示的异常或者没有达到的效果**
这个问题出现的现象是excel是没有具体数据的,因为对应写cell的时候根据map获取数据为null
![Snipaste_2021-12-29_17-01-50](https://user-images.githubusercontent.com/89824231/147645028-5f6c1d2c-8f00-4afe-91c3-ad2b90a0b599.png)

**Comment by zhuangjiaju** [comment]
和这个情况直接使用 list 即可

**Comment by wangwufan** [comment]
> 和这个情况直接使用 list 即可

我也遇到同样问题，您这句话怎么理解？

**Comment by yanghuabang** [comment]
用的时候只能写入List<Map<Integer, Object>>这种形式的数据，本质上还是当成了List<List<Object>>来用。如果要改成支持List<Map<String, Object>> 的话，可以从doAddBasicTypeToExcel方法的head参数中，拿到headNameList，第一个值就是了，暂时没测试过多级表头。另外由于它是用下标取值的，excelWriterBuilder.includeColumnFieldNames也会无效。

**Comment by LSL1618** [comment]
@OnemansCity @wangwufan @yanghuabang 由于用的是动态表头的写，所以我是这样处理Map类型数据的
```
/*
@Schema(description = "结果集列头集合")
List<String> columnNames = new ArrayList<>();
@Schema(description = "结果集列值集合")
List<Map<String, Object>> columnValues = new ArrayList<>();
*/
// 封装导出表头
List<List<String>> exportHeader = rsModel.getColumnNames()
        .stream().map((item) -> Lists.newArrayList(item))
        .collect(Collectors.toList());
// 封装导出内容
List<List<Object>> exportBody = Lists.newArrayList();
for (Map<String, Object> row : rsModel.getColumnValues()) {
    List<Object> exportItem = Lists.newArrayListWithCapacity(row.size());
    for (String header : rsModel.getColumnNames()) {
        exportItem.add(row.get(header));
    }
    exportBody.add(exportItem);
}
// 写入到响应输出流
EasyExcel.write(response.getOutputStream())
        .excelType(ExcelTypeEnum.XLSX)
        .sheet(sheetName)
        .head(exportHeader)
        .doWrite(exportBody);
```
本质上就是**根据表头顺序**，把单个`Map<String, Object>`转换成了一个`List<Object>`，最终多个`Map`就变成了`List<List<Object>>`，这样就符合了`doWrite`方法要求的参数类型。
@OnemansCity 你这里的`jsonArray.toJavaList(Map.class)`，我觉得你用错了，`JSONArray`本质上就是个`List`，开头的`JSONArray jsonArray = JSON.parseArray(data);`中的`data`，如果它是普通JSON字符串，应该解析成`JSONObject`，`JSONObject`本质上就是个`Map`，如果它是数组JSON字符串，那解析成`JSONArray`就没有错。

**Comment by zivfuture** [comment]
> @OnemansCity @wangwufan @yanghuabang 由于用的是动态表头的写，所以我是这样处理Map类型数据的
> 
> ```
> /*
> @Schema(description = "结果集列头集合")
> List<String> columnNames = new ArrayList<>();
> @Schema(description = "结果集列值集合")
> List<Map<String, Object>> columnValues = new ArrayList<>();
> */
> // 封装导出表头
> List<List<String>> exportHeader = rsModel.getColumnNames()
>         .stream().map((item) -> Lists.newArrayList(item))
>         .collect(Collectors.toList());
> // 封装导出内容
> List<List<Object>> exportBody = Lists.newArrayList();
> for (Map<String, Object> row : rsModel.getColumnValues()) {
>     List<Object> exportItem = Lists.newArrayListWithCapacity(row.size());
>     for (String header : rsModel.getColumnNames()) {
>         exportItem.add(row.get(header));
>     }
>     exportBody.add(exportItem);
> }
> // 写入到响应输出流
> EasyExcel.write(response.getOutputStream())
>         .excelType(ExcelTypeEnum.XLSX)
>         .sheet(sheetName)
>         .head(exportHeader)
>         .doWrite(exportBody);
> ```
> 
> 本质上就是**根据表头顺序**，把单个`Map<String, Object>`转换成了一个`List<Object>`，最终多个`Map`就变成了`List<List<Object>>`，这样就符合了`doWrite`方法要求的参数类型。 @OnemansCity 你这里的`jsonArray.toJavaList(Map.class)`，我觉得你用错了，`JSONArray`本质上就是个`List`，开头的`JSONArray jsonArray = JSON.parseArray(data);`中的`data`，如果它是普通JSON字符串，应该解析成`JSONObject`，`JSONObject`本质上就是个`Map`，如果它是数组JSON字符串，那解析成`JSONArray`就没有错。



你这性能岂不是差到极点?

**Comment by LSL1618** [comment]
@zivfuture 优先保证功能可以实现，其次才会考虑性能问题，如果功能都实现不了，性能好或差有啥意义。由于我的需求是动态表头导出，表头不固定必须从结果集中抽取出来，所以只能使用不创建对象的写来导出，这就限制了表头数据类型必须是List<List<String>>，而表体数据类型，从题主的分析来看传LIst<Map<String, Object>>类型显然无效，那就只能转换为List<List<Object>>类型了，这多出来的转换消耗就避免不了！
