### ISSUE TITLE
老版本发现一个bug,新版本已经解决，还有提交修改的必要吗

### ISSUE THREAD

**Issue by GuitarXY** [alibaba/easyexcel#2259]
2.xx老版本会继续维护吗，一个函数字段读取的问题读的结果不正确，我想改这个问题
已经明确是一个bug,我应该和谁讨论，（因为我也是刚开始读源码，可能对框架还不是很熟，想思想碰撞一下，qq群没响应）
是否其他地方还有隐藏的问题
不知道怎么为大家做贡献

**Comment by GuitarXY** [comment]
3.0版本上的解析的方式都变了，我这应该怎么fork代码提交pr

**Comment by aboutZZ** [comment]
定位到出bug要修改的文件，自己写一个Java类，包名、类名和`easyexcel`出bug地方的Java文件一致，这样加载class文件优先加载你的，而不是jar包里的。
不知道怎么fork、提交pr，建议你先系统地学习下 git 的使用方法再来
