### ISSUE TITLE
表头固定

### ISSUE THREAD

**Issue by dtbdtb** [alibaba/easyexcel#2263]
我希望导出的EXCEL的表头是固定不能被修改的，那么，比如我们导出模板，只有第一行，就是表头列字段，
那么用setlocked true就行，但是问题来了，其他的CELL我必须setlocked false,才能输入，但是，我总不能将剩下的所有的cell都设置一遍把
请问大家有什么好办法吗？

**Comment by zhuangjiaju** [comment]
尝试注解`@ContentStyle.locked=true`试试

**Comment by sermonlizhi** [comment]
我试了这个注解还是还行，换成@HeadStyle(locked=true)也不行
