### ISSUE TITLE
读取多行表头时存在的问题

### ISSUE THREAD

**Issue by wo5557511** [alibaba/easyexcel#2267]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
按照ExcelProperty注解中的描述，当value存在多个值的时候读取的时候只使用最后一个，存在的一个问题是
如果有两行表头，第一行表头不同，但是第二行表头相同的时候读取到的实体类只会给最后一个属性赋值
当然：这种情况可以指定index，然后很多时候表头是动态的，无法指定，这个时候貌似就无解了，示例demo实体类：
public class DemoData{

  @ExcelProperty({"a","b"})
  private String x;

 @ExcelProperty({"c","b"})
  private String y;
}
使用上面实体类读取表格的时候，可能存在y属性可以读取到值，x属性读取不到，并且y读取到的是错误的，假如index暂时无法指定（因为不能使用动态表头），貌似目前无解，或者是现在已有办法处理，我没有找到，请告知解决办法

**Comment by zhuangjiaju** [comment]
这个只能要index 去指定到 动态的用map 去接 然后自己处理
