### ISSUE TITLE
3.0.5 版本web导出 无表头

### ISSUE THREAD

**Issue by BlackCatCats** [alibaba/easyexcel#2268]
**版本是 3.0.5**

实体类 --- 
@ExcelProperty(value = "运单号",index = 0)
    private String waybill;
    @ExcelProperty(value = "提货日期",index = 1)
    @DateTimeFormat("yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8" )
    private Date deliveryDate;
    @ExcelIgnore
    private String customerName;

---实现类

![image](https://user-images.githubusercontent.com/56637432/148340589-1c4a4bcf-5661-47b9-bb74-9ed64dced7a3.png)

**Comment by zhuangjiaju** [comment]
请详细描述您的问题

**Comment by ResetMan** [comment]
同样遇到这个问题， 导出没有表头
