### ISSUE TITLE
同事将csv文件转为xls文件后，导入时报错，Book 不在

### ISSUE THREAD

**Issue by antique777** [alibaba/easyexcel#2269]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
使用的2.2.11版本，同事将csv文件转为xls文件后，导入时报错，debug发现是因为entryNames中的`Book`在枚举类WORKBOOK_DIR_ENTRY_NAMES中不存在，只有一个`BOOK`,然后后续导致了fileNotFoundException。然后同事使用的是微软的excel将csv文件另存为xls文件时entryNams 里包含的是`Book`，我是用的WPS转换的话就是`BOOK`，也许注释要改成 `//some old documents hava "WORKBOOK" or "BOOK" or "Book"啦，可能只有很老的xls文件格式才会导致这个问题吧。然后看了一遍更新日志，觉得类似的issue也都点进去看了，应该没人反应这个问题。第一次提issue，有什么做的不对的希望不要怼我，谢谢。。
**触发Bug的代码**
```java
   //不需要代码，应该是文件格式的支持问题
```
**提示的异常或者没有达到的效果**
```java
java.io.FileNotFoundException: no such entry: \"Workbook\", had: [Book, SummaryInform
```
![微信图片1](https://user-images.githubusercontent.com/55785480/148346428-187372f1-d432-4831-b9e4-de72248e85a6.png)

**Comment by zhuangjiaju** [comment]
重新保存下 是否可以i？

**Comment by zhuangjiaju** [comment]
这个是否已经解决？未解决的话请重新打开问题
