### ISSUE TITLE
写的时候怎么合并单元格，或者怎么在model中定义

### ISSUE THREAD

**Issue by 942bc** [alibaba/easyexcel#227]

**Comment by micolore** [comment]
好蠢啊，合并的条件，如果值一样就会合并

**Comment by 942bc** [comment]
> 好蠢啊，合并的条件，如果值一样就会合并

😆没找到规律。多谢，我试试

**Comment by tyfwe** [comment]
> 好蠢啊，合并的条件，如果值一样就会合并

请问，这个问题有解决办法了吗？我也遇到这个问题了，我试过好多办法，也不行

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
