### ISSUE TITLE
ExcelWritee.finish()关闭流是关闭response的输出流还是所有？

### ISSUE THREAD

**Issue by Nicky213Zhang** [alibaba/easyexcel#2276]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**
关于模板填充，用的是远程仓库的模板文件，故而涉及到InputStream输入流，采用EasyExcel.write(response.getOutputStream()).withTemplate(inputStream).build()构建ExcelWriter对象，后续也使用ExcelWritee.finish()关闭流，对于InputStream还需要单独处理吗，finish()可以处理它吗？

**Comment by zhuangjiaju** [comment]
会close的
