### ISSUE TITLE
SheetUtil.getDefaultCharWidth在web容器启动后第一次执行非常慢

### ISSUE THREAD

**Issue by xuanwoa** [alibaba/easyexcel#2277]
**建议先去看文档**
[快速开始]
**触发场景描述**
springmvc每次第一次启动，调用如下伪代码的demo接口，会非常耗时。第二次调用恢复正常。

**触发Bug的伪代码**
```java
@RequestMapping("demo")
public void demo(){
            EasyExcel.write(response.getOutputStream())
                    .sheet("Sheet1")
                    .head(headTitles)
                    .doWrite(ListUtil.empty());
}
```
**提示的异常或者没有达到的效果**
![image](https://user-images.githubusercontent.com/24318414/148725242-7ed84bb2-7a47-4833-ba3b-b98e448d5146.png)

**Comment by 1725636955** [comment]
> 

这个耗时监控的工具是什么老哥？

**Comment by 1725636955** [comment]
> **建议先去看文档** [快速开始] **触发场景描述** springmvc每次第一次启动，调用如下伪代码的demo接口，会非常耗时。第二次调用恢复正常。
> 
> **触发Bug的伪代码**
> 
> ```java
> @RequestMapping("demo")
> public void demo(){
>             EasyExcel.write(response.getOutputStream())
>                     .sheet("Sheet1")
>                     .head(headTitles)
>                     .doWrite(ListUtil.empty());
> }
> ```
> 
> **提示的异常或者没有达到的效果** ![image](https://user-images.githubusercontent.com/24318414/148725242-7ed84bb2-7a47-4833-ba3b-b98e448d5146.png)

这个耗时检测的工具是什么老哥？

**Comment by xuanwoa** [comment]
> > **建议先去看文档** [快速开始] **触发场景描述** springmvc每次第一次启动，调用如下伪代码的demo接口，会非常耗时。第二次调用恢复正常。
> > **触发Bug的伪代码**
> > ```java
> > @RequestMapping("demo")
> > public void demo(){
> >             EasyExcel.write(response.getOutputStream())
> >                     .sheet("Sheet1")
> >                     .head(headTitles)
> >                     .doWrite(ListUtil.empty());
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **提示的异常或者没有达到的效果** ![image](https://user-images.githubusercontent.com/24318414/148725242-7ed84bb2-7a47-4833-ba3b-b98e448d5146.png)
> 
> 这个耗时检测的工具是什么老哥？

jrebel带的xrebel插件

**Comment by zhuangjiaju** [comment]
这个是poi的功能 真的无解

**Comment by WangWei0905** [comment]
能不能从代码的角度分析一下poi为什么第一次执行非常慢

**Comment by zhangjz777** [comment]
遇到了同样的问题，排查代码后定位到的原因是：
> 容器启动后第一次执行导出excel文件时，会触发程序装载字体，系统中的字体越多，这个装载的过程就越耗时，装载完成后才会继续执行导出的代码。

环境：
> poi-5.2.2.jar 
> jdk 1.8.0_202

具体排查的代码路径为：
<img width="773" alt="image" src="https://user-images.githubusercontent.com/38269045/189125359-b5225796-2f3b-4cc9-9b4f-b0aff35fc460.png">
<img width="913" alt="image" src="https://user-images.githubusercontent.com/38269045/189125620-7054ae0e-1bc7-4182-9d86-36ba5bf436f0.png">
<img width="778" alt="image" src="https://user-images.githubusercontent.com/38269045/189125758-a598304d-55b7-4333-b9be-93eee809e6d7.png">
<img width="895" alt="image" src="https://user-images.githubusercontent.com/38269045/189125930-77e53b47-8ed1-4929-805a-f376c5b003f9.png">
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/38269045/189126310-98ace284-436a-4fc2-9ffb-02535dc668ed.png">
<img width="887" alt="image" src="https://user-images.githubusercontent.com/38269045/189127940-1ddee594-3248-474c-8e9f-d3c93e6ca8d6.png">
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/38269045/189128101-be212782-434f-4e75-ad88-9cfd0f590f44.png">
<img width="802" alt="image" src="https://user-images.githubusercontent.com/38269045/189129650-f9ac0f37-c5f1-4f74-b9b8-0fad92c2cca3.png">

因此为了解决第一次导出时加载字体较为耗时的问题，可以在容器启动后，主动调用一次创建字体的过程，将触发字体装载的过程前置。

<img width="617" alt="image" src="https://user-images.githubusercontent.com/38269045/189130228-06f5b7da-fbdb-4d0e-89e1-5ff9b32bf05f.png">

@xuanwoa @WangWei0905 @zhuangjiaju
