### ISSUE TITLE
自定义数据类型转换器无法获取到，还是会使用默认的IntegerStringConverter 

### ISSUE THREAD

**Issue by zmhjjj** [alibaba/easyexcel#2278]
**在使用自定义转换器时，无法获取到自定义转换器**

**触发Bug的转换器代码**
``
@Getter
@Setter
@EqualsAndHashCode
public class PersonalNetwork {
    @ExcelProperty(index = 0)
    private String user_id;
    @ExcelProperty(index = 1)
    private String province;
    @ExcelProperty(index = 3,converter = CustomIntConverter.class)
}
public class CustomIntConverter extends IntegerStringConverter {

    @Override
    public CellDataTypeEnum supportExcelTypeKey() {
        return CellDataTypeEnum.STRING;
    }

    @Override
    public Integer convertToJavaData(ReadCellData<?> cellData, ExcelContentProperty contentProperty, GlobalConfiguration globalConfiguration) throws ParseException {
       // return super.convertToJavaData(cellData, contentProperty, globalConfiguration);
        try {
            return NumberUtils.parseInteger(cellData.getStringValue(), contentProperty);
        } catch (Exception e) {
            return 0;
        }
    }
}
```
*bug截图如下**
![image](https://user-images.githubusercontent.com/55120348/148738440-e1aeccae-c11c-4ff4-8263-ab3b6a01434b.png)

**Comment by Lingering666** [comment]
我也遇到这个问题，我是自定义LocalDate类型转换器，我debug下发现自定义转换器确实setConvert（），但是在获取的时候又是变为null，从而使用的是默认的转换器，这个问题困扰了很久，请问怎么解决
