### ISSUE TITLE
有没有考虑过excel表头不确定的场景？

### ISSUE THREAD

**Issue by chenshun00** [alibaba/easyexcel#228]
在像一些发送短信以及其他的通知场景下，用户批量导入到excel中通知用户，但是每一种通知的场景可能导入的excel又不一样，这种场景不知道作者考虑过没有 @jipengfei-jpf

**Comment by zhuangjiaju** [comment]
可以用 `Map<Integer,Object>` 来接收数据。使用最新版本 并参照demo书写
