### ISSUE TITLE
Demo中的doAfterAllAnalysed方法再去调用saveData()的目的是什么???

### ISSUE THREAD

**Issue by zhangyuanlin666** [alibaba/easyexcel#2280]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   public void doAfterAllAnalysed(AnalysisContext context) {
        // 这里也要保存数据，确保最后遗留的数据也存储到数据库
        log.info("doAfterAllAnalysed...");
         saveData();
        log.info("所有数据解析完成！");
    }
```
**异常提示**
![Uploading image.png…]()

**建议描述**

加个判读是不是更合理些
public void doAfterAllAnalysed(AnalysisContext context) {
        // 这里也要保存数据，确保最后遗留的数据也存储到数据库
        log.info("doAfterAllAnalysed...");
        if (cachedDataList.size() > 0) {
            saveData();
        }
        log.info("所有数据解析完成！");
    }

**Comment by fufeii** [comment]
demo里面是批量保存的。如果有106行数据，每10行为一个批次保存一次。那么最后的6条数据需要通过doAfterAllAnalysed保存

**Comment by fufeii** [comment]
如果你对内容格式比较确定（不是在五花八门的格式），当然也可以在invoke方法里面，判断当前行数和总行数作比较，从而直接保存最后一批数据
