### ISSUE TITLE
导出的文件只有表头，没有内容

### ISSUE THREAD

**Issue by Theunfounded** [alibaba/easyexcel#2281]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   list = starRocksJdbcUtil.executeQueryForList(previewSql);
   List<List<String>> head = getHead(previewDto.getShowColumnsList());
   EasyExcel.write(fullPath) // 文件路径
              .head(head)       // 表头信息
              .sheet(previewDto.getBaseTableName()) // sheet名称
              .doWrite(list); 
```
**异常提示**
list里面存的是map，文档可以生成，但是导出的文档只有表头，没有内容，dowriter里面只能是具体的数据类集合，不能是map集合吗
**建议描述**

**Comment by HexisLuo** [comment]
不可以，map集合需要配合write(OutputStream outputStream, Class head)或者head(Class<?> clazz)方法

**Comment by zhuangjiaju** [comment]
导出数据 只能是map<index,data> 或者找 list
