### ISSUE TITLE
填充时，一个单元格如何使用两种样式

### ISSUE THREAD

**Issue by jacky33** [alibaba/easyexcel#2282]
![企业微信截图_20220112162014](https://user-images.githubusercontent.com/24823451/149090044-d00e028b-ea53-4072-bc6b-2d3d5bacd084.png)

![企业微信截图_20220112162033](https://user-images.githubusercontent.com/24823451/149090048-b7255140-04e6-450c-92ae-07ff8fd76802.png)

我想实现填充的字体有特殊的样式，但是输出的结果，样式会被修改为单元格的样式
怎么样实现保留模板时候变量的样式

**Comment by jacky33** [comment]
暂时先用自定义handler解决

![QQ图片20220112175522](https://user-images.githubusercontent.com/24823451/149117782-49fdb48d-c7ce-4132-8a8c-5074a8a1dae7.png)
![QQ图片20220112175533](https://user-images.githubusercontent.com/24823451/149117792-af72d0c7-e34e-44e7-83db-232f6d22c84c.png)

**Comment by zhuangjiaju** [comment]
这个只能通过自定义样式解决

**Comment by jacky33** [comment]
谢谢

**Comment by bajie-git** [comment]
> 暂时先用自定义handler解决
> 
> ![QQ图片20220112175522](https://user-images.githubusercontent.com/24823451/149117782-49fdb48d-c7ce-4132-8a8c-5074a8a1dae7.png) ![QQ图片20220112175533](https://user-images.githubusercontent.com/24823451/149117792-af72d0c7-e34e-44e7-83db-232f6d22c84c.png)

感谢 解决了我得问题
