### ISSUE TITLE
Excel某些单元格设置了保留两位小数显示， 怎么拿到实际数据呢？求大佬讲解下，新年快乐~~

### ISSUE THREAD

**Issue by dandelionflying** [alibaba/easyexcel#2285]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by dandelionflying** [comment]
没找到合适的方式。有没有朋友是用Map存的数据啊，而非实体类？我用我用map存，那就只能注册converter处理，但没有找到可行的方法，有没有朋友遇到的？请求指教，万分感谢~！！！！！！！！

**Comment by dandelionflying** [comment]
没有用实体类，所以注解的方式用不了。（业务上的需求导致选择了map而不是实体类）

**Comment by zhuangjiaju** [comment]
设置`useDefaultListener=false` ，然后会拿到`Map<Integer, ReadCellData<?>> cellDataMap` 自己解析即可
