### ISSUE TITLE
3.0.5 版本 怎么一个单元格写多行数据？？用\n 生成数据，必须双击一下单元格才展开，默认显示最后一行和多个空行

### ISSUE THREAD

**Issue by crashiers** [alibaba/easyexcel#2286]
3.0.5 版本 怎么一个单元格写多行数据？？用\n 生成数据，必须双击一下单元格才展开，默认显示最后一行和多个空行

![image](https://user-images.githubusercontent.com/33898314/149468183-9c67f105-6ee6-487d-b57b-268589281fe0.png)
实际上数据格式是这样
![image](https://user-images.githubusercontent.com/33898314/149468239-5a59949d-f65c-4f9b-82f3-da761df04c3a.png)

**Comment by HexisLuo** [comment]
是不是没加自动换行设置？

**Comment by crashiers** [comment]
> 是不是没加自动换行设置？

设置过

**Comment by zhuangjiaju** [comment]
对象加上注解`    @ContentStyle(wrapped = BooleanEnum.TRUE)`
然后用 `\r\n` 来换行

**Comment by shihaoH** [comment]
> 对象加上注解` @ContentStyle(wrapped = BooleanEnum.TRUE)` 然后用 `\r\n` 来换行

@zhuangjiaju 这样还是不行呀，单元格里直接把\r\n打印出来了

**Comment by shihaoH** [comment]
link: #2623
