### ISSUE TITLE
能否识别数据是文本数据，以解决1.10、1.20等数据识别为1.1、1.2

### ISSUE THREAD

**Issue by FishNorth** [alibaba/easyexcel#229]
如下
1
--1.1
--1.2
...
--1.10
如果将1.10识别为1.1就重复了~~~

**Comment by wcccode** [comment]
@FishNorth 有解决方案吗

**Comment by dongjun613** [comment]
3、抛弃不重要的数据
Excel解析时候会包含样式，字体，宽度等数据，但这些数据是我们不关心的，如果将这部分数据抛弃可以大大降低内存使用。Excel中数据如下Style占了相当大的空间。

估计是不会做这个功能的。

**Comment by zhuangjiaju** [comment]
这个问题已经在 `2.0.0` 中解决
