### ISSUE TITLE
easyexcel默认引入的ehcache版本过低，会造成初始化缓存失败

### ISSUE THREAD

**Issue by lichong-a** [alibaba/easyexcel#2295]
如下图，已测试3.0.4和3.0.5的easyexcel引入的ehcache版本都有这样的问题
![image](https://user-images.githubusercontent.com/43563802/150083131-e3efa8fc-d9c3-42ff-a178-9ce1759ed335.png)

**Comment by zhuangjiaju** [comment]
默认 3.8.1 你是否其他还引用了包
