### ISSUE TITLE
docker容器中创建workbook空指针

### ISSUE THREAD

**Issue by tongzige** [alibaba/easyexcel#2296]
在MAC上运行正常，docker容器中运行报错。
系统版本和java版本如下：
![image](https://user-images.githubusercontent.com/40231684/150255557-c6fe4dd9-733c-4ecd-a9ff-220e8a79fe47.png)

报错代码：
`ExcelWriter excelWriter = EasyExcel.write(integrationExportTask.getFilePath())
                    .withTemplate(integrationExportTask.getTemplatePath()).build();`

报错信息：
![image](https://user-images.githubusercontent.com/40231684/150256843-e413714f-1a2d-488f-8d03-49c12da03312.png)

**Comment by tongzige** [comment]
安装字体之后报另一个错误
![image](https://user-images.githubusercontent.com/40231684/150284254-cba76ebb-daa8-4f24-9573-f87b09476355.png)

**Comment by zhuangjiaju** [comment]
看下 常见问题 有解决方案
