### ISSUE TITLE
最新版本3.0.5，读取csv文件，传file读取没问题，传inputstream会提示不支持该类型

### ISSUE THREAD

**Issue by ningxiaojian31** [alibaba/easyexcel#2297]
方法：com.alibaba.excel.support.ExcelTypeEnum#recognitionExcelType

![image](https://user-images.githubusercontent.com/41463166/150303622-df55c7b3-7e71-429c-967f-af2ba07391ca.png)

**Comment by lancelord-lajiao** [comment]
这个啥时候修复啊，宝儿

**Comment by menglingqi0814** [comment]
这个大概啥时候发布一版哇，excel也遇到这个问题了

**Comment by zhuangjiaju** [comment]
该问题已经在`3.1.0`+版本里面解决，最新版本：[![Maven central](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel)

**Comment by LZhComing** [comment]
> 
最新版本还是有问题啊，宝儿

**Comment by kuenng** [comment]
最新版本还是有问题啊，宝儿

**Comment by Bleoo** [comment]
最新版本还是有问题啊，宝儿

**Comment by zhengzzv** [comment]
https://github.com/alibaba/easyexcel/pull/2598 考虑一下这个吗
