### ISSUE TITLE
列表一条数据占用多行复杂布局写入

### ISSUE THREAD

**Issue by cenggel** [alibaba/easyexcel#2299]
生成excel 表格的时候经常遇到如下格式
![image](https://user-images.githubusercontent.com/6281382/150488544-82928979-6809-4a20-af28-2e73b1951d5f.png)

一条工作经历占用多行显示，并且有合并单元格的情况，左边的“工作经历” 跟着工作经历合并行。

是否考虑填充功能支持这样的布局？
有没有已经实现的朋友？

**Comment by zhuangjiaju** [comment]
自定义合并策略

**Comment by cnericxu** [comment]
还有个办法，不要用easy excel, 用Apache POI自己实现类似填充功能，我就这么干了，没想到easyexcel连这么常用的功能都不支持。
