### ISSUE TITLE
3.0.5版读取csv文件后资源未释放

### ISSUE THREAD

**Issue by panqunjun** [alibaba/easyexcel#2309]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
以ExcelReader reader = EasyExcel.read(filePath).build();这种方式读取csv文件，读取完毕后资源未释放；
**触发Bug的代码**
```java
   详见http://blog.sina.com.cn/s/blog_667ac0360102z1p8.html
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
该问题已经在`3.1.0`+版本里面解决，最新版本：[![Maven central](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel)
