### ISSUE TITLE
标题后面出现多余的逗号，自定义converter不起作用

### ISSUE THREAD

**Issue by purgeyao** [alibaba/easyexcel#2313]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

比如下面表格数据
```
性别,班级,年龄,,,
男,二年级,1,,,
男,二年级,1,,,
男,二年级,1,,,
```

也就是说 因为用户使用软件的原因 编辑的表格  导致后面出现了多个无用的逗号
在`easyexcel`解析的时候就出现问题了。

@ExcelProperty(value = "性别", converter = GenderConverter.class)
private GenderEnum gender;

@ExcelProperty(value = "班级", converter = ClassConverter.class)

在读取性别的时候  GenderConverter#convertToJavaData 不会生效的
ClassConverter是有效果的

**触发Bug的代码**
```java
  List<Home> billList = EasyExcel.read(new ByteArrayInputStream(outputStream.toByteArray()))
                .head(Home.class).excelType(ExcelTypeEnum.CSV)
                .sheet(0).headRowNumber(1).doReadSync();
```

性别读出来的是空

**提示的异常或者没有达到的效果**

**Comment by purgeyao** [comment]
正常  下面的数据是正常的
```
性别,班级,年龄
男,二年级,1
男,二年级,1
男,二年级,1
```

**Comment by zhuangjiaju** [comment]
我测试了没有问题呀？吧转换器的代码也贴一下

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？如果未解决 请重新打开问题。
