### ISSUE TITLE
模板填充数据，表格下有一张图表，填充导出后表格数据被图表覆盖

### ISSUE THREAD

**Issue by kwin1113** [alibaba/easyexcel#2323]
表格后有一张图表，期望是导出时表格数据增加，图表位置会相应的后移，但是导出结果图表位置不变，将表格数据覆盖了。
PS：手动新建行时，图表会往后推移。
模板：
![导出模板](https://user-images.githubusercontent.com/45393045/154234653-b51b991f-8571-4253-88a2-e96d2d668681.png)
导出结果：
![导出结果](https://user-images.githubusercontent.com/45393045/154234712-222b6766-eb6e-4930-a2dd-a48306af62ec.png)

**Comment by EmptyInMind** [comment]
遇到同样的问题，图片位置没变，填充的数据一多，图片就把数据覆盖了

**Comment by vivtoum** [comment]
填充有一个参数，设置成新行填充

**Comment by kwin1113** [comment]
> 填充有一个参数，设置成新行填充

设置了，没用。行是新增了，但是导出之后的结果和手动新增的效果不同，手动新增不会覆盖，如原文PS里所说。

**Comment by zhuangjiaju** [comment]
尝试升级到3.1.0 然后使用：https://www.yuque.com/easyexcel/doc/fill#0b212861
强制插入行

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？如果未解决 请重新打开问题。

**Comment by liweihua274** [comment]
> > 填充有一个参数，设置成新行填充
> 
> 设置了，没用。行是新增了，但是导出之后的结果和手动新增的效果不同，手动新增不会覆盖，如原文PS里所说。

请问这个问题解决了么？
