### ISSUE TITLE
BigIntegerStringConverter写单元格还是数值类型

### ISSUE THREAD

**Issue by Learning-Hard** [alibaba/easyexcel#2325]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
BigInteger类型写入excel是期望转成String

**触发Bug的代码**
```java
 public WriteCellData<?> convertToExcelData(BigInteger value, ExcelContentProperty contentProperty,
        GlobalConfiguration globalConfiguration) {
        return NumberUtils.formatToCellData(value, contentProperty);
    }
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
这个是个bug 
将会在3.1.0中修复

**Comment by zhuangjiaju** [comment]
该问题已经在`3.1.0`+版本里面解决，最新版本：[![Maven central](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel)
