### ISSUE TITLE
读取时如何跳过特殊行

### ISSUE THREAD

**Issue by aboutZZ** [alibaba/easyexcel#2327]
现有一Excel账单需要导入，其中夹杂一些统计行，这个统计行导致将行数据转为`Bean`时抛出异常`ExcelDataConvertException`
现在已知这些统计行的特征（某一列为0或空白字符串），如何跳过这些行而不抛出异常？

PS：如果用户账单数据格式不对，还是要抛出`ExcelDataConvertException`的，现在只是忽略统计行的数据异常

**Comment by TungMan0801** [comment]
Hello Mr Zhuang, we are a school group for Software Engineering. We want to offer to try to fix or develop this issue, or at least do a little contribution! If this bug has been fixed please just leave a comment, thanks! Hope to get your consent and support:)

**Comment by zhuangjiaju** [comment]
比如0的情况下 很难知道是不是你要的，所以建议就是捕获异常 ，然后忽略掉这些数据

**Comment by aboutZZ** [comment]
> 比如0的情况下 很难知道是不是你要的，所以建议就是捕获异常 ，然后忽略掉这些数据

用户输入错误导致`ExcelDataConvertException`的情况下是需要报错的，而不是忽略。统计行需要忽略异常。
建议在`ExcelDataConvertException`中设置当前行数据，方便捕获异常后获取出错的行。
