### ISSUE TITLE
请问下easyexcel可以实时写出到文件或者输出流中吗？

### ISSUE THREAD

**Issue by miaoyibo** [alibaba/easyexcel#2331]
比如每写完一个sheet都可以刷新出去

**Comment by zhuangjiaju** [comment]
这个不支持，只能写完以后才能写入到文件流中。

**Comment by wuyaxin** [comment]
@zhuangjiaju 你好 请问为什么不可以啊，这样的话，造成了web实时下载的时候，分批写入流并没有意义啊，我测试了一下，在我把所以数据加载完之前它是不会写入流的，因为我这边分批查询数据本身就比较慢导致会很长一段时间都没有数据写入响应流，话说这个的低内存是怎么实现的呢，我以为是实时分批写入流实现的呢。
