### ISSUE TITLE
excel设置了只读，如何获取到数据

### ISSUE THREAD

**Issue by skddyj** [alibaba/easyexcel#2338]
如题，excel文档设置了只读模式，解析的时候获取不到数据，请问怎样操作能获取到只读文档的数据

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？未解决请重新打开

**Comment by skddyj** [comment]
你好，抱歉刚看到这个消息，我后来找到了读不出的原因，是因为有一个sheet页设置了绝对隐藏，导致了读取不到这个sheet，取消了绝对隐藏之后就可以了，不知道后面会增加绝对隐藏sheet的读取吗？
