### ISSUE TITLE
Excel读取时，如果某个格属性为Integer，excel中输入其他类型，直接抛异常，有什么好办法？

### ISSUE THREAD

**Issue by TavenYin** [alibaba/easyexcel#234]

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。自定义`Converter`或者 用string接收自己转化
