### ISSUE TITLE
在写入Excel流程中,在调用ExcelWriteAddExecutor.add之前添加一层类似于过滤器链的接口

### ISSUE THREAD

**Issue by moil-xm** [alibaba/easyexcel#2349]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
在写入Excel流程中,在调用ExcelWriteAddExecutor.add之前添加一层类似于过滤器链的接口
在处理数据之前先执行所有的过滤器
入参可以是表头与写入数据
不知道你们觉得怎样呢

**Comment by zhuangjiaju** [comment]
这个`com.alibaba.excel.write.handler.RowWriteHandler#beforeRowCreate(com.alibaba.excel.write.handler.context.RowWriteHandlerContext)` 是否能满足这个诉求？

**Comment by moil-xm** [comment]
> 这个 是否能满足这个诉求？`com.alibaba.excel.write.handler.RowWriteHandler#beforeRowCreate(com.alibaba.excel.write.handler.context.RowWriteHandlerContext)`

嗯 我大概清楚了 我后续查看一下 感谢回复
