### ISSUE TITLE
可以设置密码吗？

### ISSUE THREAD

**Issue by zhegexiaohuozi** [alibaba/easyexcel#235]
可以设置密码吗？

**Comment by shanjungit** [comment]
刚用上这本代码，没看到和这个相关的方法

**Comment by SilentTao** [comment]
可以做一层压缩,然后对压缩包进行密码加密.

**Comment by zhuangjiaju** [comment]
请参照demo  `password` 参数即可

**Comment by chenshaoao** [comment]
> 请参照demo `password` 参数即可

您好，demo 链接能贴一下吗？没有找到 demo 例子。
