### ISSUE TITLE
读取的内容自动过滤了空行ignoreEmptyRow不生效，有办法同步处理空行或者读取出吗

### ISSUE THREAD

**Issue by ShawnShiFan** [alibaba/easyexcel#2351]
//读取的内容自动过滤了空行ignoreEmptyRow不生效
ExcelReaderBuilder excelReaderBuilder =  EasyExcelFactory.read(is,excelListener)
                    .autoTrim(true)
                    .autoCloseStream(Boolean.FALSE)
                    .mandatoryUseInputStream(Boolean.TRUE)
                    .readCache(new MapCache())
                    .ignoreEmptyRow(Boolean.FALSE);
ExcelReader            excelReader = buildExcelReader(excelReaderBuilder);

**Comment by ShawnShiFan** [comment]
单元格若有边框则能识别空行，若什么都没有则无法识别空行

**Comment by zhuangjiaju** [comment]
这个不算空行 就是没有数据

**Comment by ShawnShiFan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
