### ISSUE TITLE
一些公式错误导入的时候报错

### ISSUE THREAD

**Issue by chenci16** [alibaba/easyexcel#2356]
**触发场景描述**
![image](https://user-images.githubusercontent.com/16287228/157639330-bc896b6a-7b14-4fcd-b95c-c5d0bdc3ec82.png)
![image](https://user-images.githubusercontent.com/16287228/157639370-86f50394-f583-4b89-9c34-b1e6939d5c2f.png)
这类错误，导致了com.alibaba.excel.analysis.v07.handlers.CellTagHandler.endElement(CellTagHandler.java:91)发生错误，默认的EMPTY类型会尝试转成double，我不知道为什么不用字符串接。希望遇到这种错误可以继续执行或者能捕获定位。
![image](https://user-images.githubusercontent.com/16287228/157639724-5e884d0b-c8fd-4931-a1d9-dacc3c4d1490.png)

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？未解决请重新打开
