### ISSUE TITLE
ExcelTypeEnum中支持csv，为何EasyExcel的read方法中没有支持ExcelTypeEnum的参数

### ISSUE THREAD

**Issue by neoDaice** [alibaba/easyexcel#2357]
我想要读取csv，file使用的是inputstream的方式，调用的方法如下:
public static ExcelReaderBuilder read(InputStream inputStream, Class head, ReadListener readListener){}
但是这个方法后报无法识别的文件格式的错误，可否给这个方法加上ExcelTypeEnum的参数，这样可以来读取csv

**Comment by fufeii** [comment]
EasyExcel.read().excelType(ExcelTypeEnum.CSV)
就正常读取了

**Comment by Melody0321** [comment]
hello, please give me some time to implement it, thanks. If you have more detailed information, you can contact me or comment here.

**Comment by zhuangjiaju** [comment]
read().exceltype可以设置，然后新版已经解决无法识别csv的问题
