### ISSUE TITLE
在导入excel的时候会多读取一行空行

### ISSUE THREAD

**Issue by didi12121** [alibaba/easyexcel#2359]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   EasyExcel.read(file.getInputStream(), MemberApplyDataImportVo.class, new ReadListener<MemberApplyDataImportVo>() {
            //批量保存的条数
            public static final int BATCH_COUNT = 100;

            private List<MemberApplyDataImportVo> cachedDataList = ListUtils.newArrayListWithExpectedSize(BATCH_COUNT);

            @Override
            public void invoke(MemberApplyDataImportVo o, AnalysisContext analysisContext) {
                log.info(o.toString());
                cachedDataList.add(o);
            }

            @Override
            public void doAfterAllAnalysed(AnalysisContext analysisContext) {

            }
        }).sheet().doRead();
```
**异常提示**
在导入excel的时候会多读取一行空行，excel中除了表头只有一行数据但是读取到的数据log出来有两个对象
excel文件内容截图：
![image](https://user-images.githubusercontent.com/33095817/158504905-a43638f2-81ea-4a20-9e42-3f97d1f424ef.png)

log日志截图：
![image](https://user-images.githubusercontent.com/33095817/158504821-80b61756-0b66-48d4-94d3-f659fb5312e5.png)

**建议描述**
在导入excel的时候会多读取一行空行，excel中除了表头只有一行数据但是读取到的数据log出来有两个对象

**Comment by fufeii** [comment]
设置  headRowNumber(1) 试试呢

**Comment by didi12121** [comment]
> 设置 headRowNumber(1) 试试呢

不行，还是会在最后一行结束后多一个所有属性都为null的实体类

**Comment by zhuangjiaju** [comment]
这个会在 3.1.0 解决

**Comment by Mars11** [comment]
导致这个bug的具体原因是什么呢，我这边什么都没有键入也有这个问题

**Comment by didi12121** [comment]
> 导致错误的具体原因是关于我这个问题都没有键入也有这个问题

emmm具体我也不清楚，我的解决办法是在放入list之前判断一次这个对象的所有属性最少有一个不为null
