### ISSUE TITLE
通过模板填充导出图片，图片为空白，请问需要怎么处理？

### ISSUE THREAD

**Issue by susery** [alibaba/easyexcel#2368]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
![image](https://user-images.githubusercontent.com/16741001/158984408-04c66d15-f6a1-4728-adda-8f2540c2ecdd.png)
![image](https://user-images.githubusercontent.com/16741001/158984515-ac703c63-f7eb-4fef-8414-65e0b9f50cee.png)
![image](https://user-images.githubusercontent.com/16741001/158984573-a6ec328e-ae88-4f02-8084-bde2bb7d6f9a.png)
其间，调整过转换器，一个是FileImageConverter 一个是StringImageConverter，但是都是空白的
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by susery** [comment]
使用的版本是3.0.5

**Comment by zhuangjiaju** [comment]
我实际测试没问题 看下`com.alibaba.excel.write.executor.AbstractExcelWriteExecutor#fillImage` 这个行代码有没有进去

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？未解决请重新打开

**Comment by kkblf** [comment]
我也遇到了这个问题，调查发现是和poi-ooxml的版本冲突，如果我使用easyExcel自带依赖没有问题，但是单独设置poi-ooxml就会出现问题。
