### ISSUE TITLE
关于2.1.2版本，内存泄漏问题。

### ISSUE THREAD

**Issue by China-Dwan** [alibaba/easyexcel#2369]
异常描述：
项目长时间不重启后，内存不断上升，最终会导致宕机。所以定期dump了文件下来。
发现有一内存可能是一直无法释放。详细如下。
![image](https://user-images.githubusercontent.com/43984599/159193635-fe5eb192-3672-4374-b8d6-989b3ffeb91a.png)
查看代码后，发现ExcelReader里面重写了finalize()方法，这个会对导致内存无法释放吗？
希望作者能帮忙看下这个问题。

**Comment by zhuangjiaju** [comment]
麻烦看下  info 后面被你隐藏的代码 为什么会常驻内存，看下这个什么地方有引用？

**Comment by China-Dwan** [comment]
后面又dump了一份日志，应该不是这个问题
