### ISSUE TITLE
单元格式为货币,无法读取默认货币符号

### ISSUE THREAD

**Issue by yia115** [alibaba/easyexcel#237]
单元格式为货币,无法读取默认货币符号，excel中显示为带货币符号的金额，导入后没有默认的货币符号

**Comment by zhuangjiaju** [comment]
这个目前需要自己去实现。请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 。然后用double 去接收数据 自己转化
