### ISSUE TITLE
使用mybits plus 批处理新增的时候会很慢 不知道什么原因

### ISSUE THREAD

**Issue by stan8259** [alibaba/easyexcel#2370]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by linghengqian** [comment]
There is no doubt that this problem is mybatis plus.

**Comment by zhuangjiaju** [comment]
这个需要检查下是否有事务之类的
