### ISSUE TITLE
简单导入报SAXNotRecognizedException错误

### ISSUE THREAD

**Issue by zly1024** [alibaba/easyexcel#2371]
EasyExcel.read(file.getInputStream(), RaExportVo.class,new UploadExcelListener()).sheet().doRead();

--------------------------------
org.xml.sax.SAXNotRecognizedException: unrecognized feature http://apache.org/xml/features/disallow-doctype-decl

**Comment by zhuangjiaju** [comment]
检查下是否是excel 文件

**Comment by zhuangjiaju** [comment]
是否已经解决了问题，如果未解决请重新打开问题
