### ISSUE TITLE
excel表头有换行符与实体类属性字段对应的问题

### ISSUE THREAD

**Issue by object360** [alibaba/easyexcel#2372]
1.Excel表头有一个字段中间有换行符号，java读取实现的符号为：收货地址\n区分类别。收货地址和区分类别之间有一个回车
2.java实体类属性
/**
     * 收货地址区分类别
     */
    @ExcelProperty("收货地址区分类别")
    private String address;
3.HqListener类  逐行数据解析事件
/**
     * 逐行数据解析事件
     */
    @Override
    public void invoke(Entity eitity, AnalysisContext context) {
        //这里获取的eitity实体类里的属性address，读取的数值为空
    }

 
//就算是修改了初始表单头部的headMap,替换了换行符，读取的属性还是为空

4.HqListener类  初始表单头部事件
/**
     * 初始表单头部事件
     */
    @Override
    public void invokeHead(Map<Integer, CellData> headMap, AnalysisContext context) {

        //将excel表格列的标题中的文字的空格和换行进行替换
        for (Map.Entry<Integer, CellData> item : headMap.entrySet()) {
            Integer key = item.getKey();
            CellData value = item.getValue();
            String stringValue = value.getStringValue();
            if(stringValue!=null){
                //替换所有的空格和回车
                stringValue = stringValue.replaceAll("\\s*", "").replace("\n","").replace("\r","");
                value.setStringValue(stringValue);
            }
            System.out.println(stringValue);
        }
        super.invokeHead(headMap, context);
    }

想咨询下有没有什么好的解决方法，不想在实体类属性下指定属性的index
因为实体类属性与excel的表头列位置不一定固定某个位置

**Comment by zhuangjiaju** [comment]
"收货地址\r区分类别“ 试试 
不行打开：`com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor#buildHead`
比较下 143行 会比较是否相等

**Comment by stop-bullshit** [comment]
我也遇到了类似的问题,映射的实体类字段中没有空格  但是实际业务提供的excel 列名称可能有一个HTML的 NBSP 空格   导致表头与实体类注解映射不一致,但是在`invokeHeadMap`处理后又无法读取到数据,现在只能在拿到数据,再对表头进行一次处理然后再映射
