### ISSUE TITLE
建议创建一个抽象异常类让所有的异常都去继承

### ISSUE THREAD

**Issue by Deycoesr** [alibaba/easyexcel#2375]
**建议描述**

建议创建一个 `EasyExcelRuntimeException` 这样的抽象异常类去继承 `RuntimeException`, 然后所有的异常类都去继承它, 这样方便捕捉的时候区分.

而不是所有的异常类都去直接继承 `RuntimeException`.

**Comment by zhuangjiaju** [comment]
很好的建议 会在下个版本加入

**Comment by Deycoesr** [comment]
我可以实现这个吗?
