### ISSUE TITLE
如何向convertre中传入参数

### ISSUE THREAD

**Issue by hefei-SXQ** [alibaba/easyexcel#2382]
我希望写一个字典转化的converter，通过传入字典类型的参数，支持所有字典数据的转化。但是需要给converter中传入参数，请问如何实现这种操作

**Comment by samlgl** [comment]
可以在字段上再加个注解，里面定义字典code之类的东西(eg:Dict)，在自定义Converter里面，通过contentProperty.getField().getAnnotation(Dict.class) ,然后再拿到Dict注解设置的值

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
