### ISSUE TITLE
同步读取数据，使用readSync(),数据类型转化异常后，直接中断了，怎样可以不中断呢

### ISSUE THREAD

**Issue by chaochaoZhao** [alibaba/easyexcel#2388]
虽然在listener中重新了onException,但是还是会抛出异常并报警

@Override
    public void onException(Exception exception, AnalysisContext context){
        log.error("解析失败，但是继续解析下一行{}",exception.getMessage());
        if (exception instanceof ExcelDataConvertException) {
            ExcelDataConvertException excelDataConvertException = (ExcelDataConvertException) exception;
            log.error("第{}行，第{}列解析异常", excelDataConvertException.getRowIndex(), excelDataConvertException.getColumnIndex());
        }
        System.out.println(1234);
    }

**Comment by zhuangjiaju** [comment]
实现 `onException `  即可，不要再重复抛出异常。
