### ISSUE TITLE
"###,###.##"格式数字导入转化问题

### ISSUE THREAD

**Issue by yufenghe** [alibaba/easyexcel#239]
在1.1.2-beta5版，com.alibaba.excel.util.TypeUtil对于"###,###.##"数字转化为float，double时会发生NumberFormatException异常

**Comment by PhilosophyBuns** [comment]
使用String接受参数，自己手动转换

**Comment by linavv1** [comment]
excel文本格式0.001读取后是1E-3，是哪里需要设置什么？

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
