### ISSUE TITLE
关于sheetName校验的必要性讨论

### ISSUE THREAD

**Issue by shallwetalkge** [alibaba/easyexcel#2396]
Hi，我们公司的需求是统一一套导入的代码逻辑，因此很多参数需要进行传递，在多sheet导入时，因为担心用户移动sheet的位置顺序，因此，我的readSheet代码为：
```java
String sheetName = (SheetName)domainClazz.getAnnotation(SheetName.class).value();
ReadSheet readSheet1 =EasyExcel.readSheet(sheetName).head(domainClazz).registerReadListener(new ImportDomainListener()).build();
```
此处，readSheet参数使用的String sheetName,非Interger sheetNo。
在ImportDomainListener()监听器中，使用invokeHeadMap方法去校验head的完整性。
但是我发现，如果文件类型上传错误，将其他domainClass的文件上传，且文件无数据，仅有表头时，不会调用到监听器中invokeHeadMap方法。
经过debug后发现在com.alibaba.excel.util.SheetUtils.match(ReadSheet readSheet, AnalysisContext analysisContext) 方法中47行对传入sheetName与excel文件中的sheetName做了比较，代码如下：
```java
if (!StringUtils.isEmpty(parameterSheetName)) {
    boolean autoTrim = (parameterReadSheet.getAutoTrim() != null && parameterReadSheet.getAutoTrim())
        || (parameterReadSheet.getAutoTrim() == null
            && analysisContext.readWorkbookHolder().getGlobalConfiguration().getAutoTrim());
    if (autoTrim) {
        parameterSheetName = parameterSheetName.trim();
    }
    match = parameterSheetName.equals(readSheet.getSheetName());
}
```
在比对不通过后，直接return null，并且无错误抛出，外层无法截获此信息
如果使用EasyExcel.readSheet(Interger sheetNo)，则不会出现该问题，但是如果客户上传excel时候移动了sheet顺序，则无法成功匹配。对此，是否添加参数判断是否进行sheetName比对，或添加错误信息抛出

**Comment by shallwetalkge** [comment]
@zhuangjiaju Hi，可以帮忙解答一下吗

**Comment by zhuangjiaju** [comment]
建议自己加个一个标记  来标记 是否读到了head ，没有则抛出异常
