### ISSUE TITLE
请问,写操作可不可以,不直接下载到磁盘,直接获取生成的Excel的文件流?需要拿到文件流上传到服务器

### ISSUE THREAD

**Issue by zhang3097** [alibaba/easyexcel#2399]
原业务是直接通过response.getOutputStream();把要下载的Excel直接通过浏览器下载,现在不需要直接通过浏览器下载,而是在代码里使用输入流上传到服务器.
请问写操作能不能获取到生成的Excel的输入流呢?
谢谢

**Comment by zhuangjiaju** [comment]
用`ByteArrayOutputStream` 或者 直接用临时文件 来存储就行

**Comment by zhang3097** [comment]
> 用 或者 直接用临时文件 来存储就行`ByteArrayOutputStream`

请问怎么实现呢?
