### ISSUE TITLE
,导入的时候, 读取一千条左右OutOfMemoryError 谁知道怎么解决 我们项目导入用的多每一个导入都是一个model 是不是这个原因 求大佬分析

### ISSUE THREAD

**Issue by lovefwl** [alibaba/easyexcel#240]

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
