### ISSUE TITLE
dbcp导致SAXNotRecognizedException

### ISSUE THREAD

**Issue by TTaRay** [alibaba/easyexcel#2401]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
dbcp1.2冲突，改为1.4解决
**触发Bug的代码**
<dependency>
      <groupId>commons-dbcp</groupId>
      <artifactId>commons-dbcp</artifactId>
      <version>1.2</version>
    </dependency>
```java
   这里写代码
```
**提示的异常或者没有达到的效果**
[org.xml.sax.SAXNotRecognizedException]

**Comment by zhuangjiaju** [comment]
优秀
