### ISSUE TITLE
数据写完之后要怎么新增类似表格footer的内容

### ISSUE THREAD

**Issue by fangzuoxian** [alibaba/easyexcel#2402]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**建议描述**
在写完所有数据之后，在后面增加比如一些表格列、公式等的说明，用单元格备注还是没那么直观

**Comment by zhuangjiaju** [comment]
这个用table 就行 ，在写入的文档有。
