### ISSUE TITLE
csv的编码为GBK时中文乱码

### ISSUE THREAD

**Issue by doupengfei** [alibaba/easyexcel#2404]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
csv文件
**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**
存储到数据后的中文为乱码，后期是否有指定编码的更新

**Comment by aboutZZ** [comment]
Duplicate of #2324

**Comment by zhuangjiaju** [comment]
该问题已经在`3.1.0`+版本里面解决，最新版本：[![Maven central](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel)

**Comment by doupengfei** [comment]
好的，谢谢

发自我的iPhone
