### ISSUE TITLE
3.0.5版本导出excel时，如果小数点后超过9位后就不显示了，怎么让他全部显示出来？

### ISSUE THREAD

**Issue by chnmarshal** [alibaba/easyexcel#2414]
比如数值是0.912312434645，导出到excel时显示为0.912312434，看到的就是这样，但是值是对的，如果手动调整小数点位数就会全部显示出来，这个怎么解决？麻烦帮忙看下，谢谢。我使用的时候没有用实体类，不能在属性上加注解。

**Comment by zhuangjiaju** [comment]
使用 string类型去处理，你在office 里面输入也无法处理这个问题
