### ISSUE TITLE
请问这个是什么原因？

### ISSUE THREAD

**Issue by longyihao** [alibaba/easyexcel#242]
com.alibaba.excel.exception.ExcelAnalysisException: File type error，io must be available markSupported,you can do like this <code> new BufferedInputStream(new FileInputStream(\"/xxxx\"))</code> "

Unable to read entire header; 153 bytes read; expected 512 bytes

**Comment by lymenglei** [comment]
![image](https://user-images.githubusercontent.com/8777889/53717805-411cd000-3e94-11e9-956e-76cb0e3f058d.png)
我也遇到类似的问题

**Comment by lymenglei** [comment]
这个问题不是必现，在有些机器上会出现，有些机器上不会出现这个问题。

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
