### ISSUE TITLE
自定义CellWriteHandler指定特定单元格样式，也注册了HorizontalCellStyleStrategy实现通用样式，出现样式异常

### ISSUE THREAD

**Issue by djors** [alibaba/easyexcel#2423]
1.自定义CellWriteHandler：我就想指定11行第2列的样式独特
//下面是模仿HorizontalCellStyleStrategy的setContentCellStyle()写的
public class CustomCellWriteHandler implements CellWriteHandler {
    @Override
    public void afterCellDispose(CellWriteHandlerContext context) {
        if (context.getRowIndex() == 11
                && context.getColumnIndex() == 2) {
            WriteCellData<?> writeCellData = context.getFirstCellData();
            WriteCellStyle writeCellStyle3 = new WriteCellStyle();
            WriteFont writeFont3 = new WriteFont();
            writeFont3.setFontName("Times New Roman");
            writeFont3.setFontHeightInPoints((short) 10);
            writeFont3.setItalic(Boolean.TRUE);
            writeCellStyle3.setWriteFont(writeFont3);
            WriteCellStyle.merge(writeCellStyle3, writeCellData.getOrCreateStyle());
        }
    }
}

2.也使用了HorizontalCellStyleStrategy设置了通用样式
public static HorizontalCellStyleStrategy specsStyleStrategy(){
        HorizontalCellStyleStrategy horizontalCellStyleStrategy = new HorizontalCellStyleStrategy();
        WriteCellStyle contentCellStyle = new WriteCellStyle();
        WriteFont contentWriteFont = new WriteFont();
        contentWriteFont.setFontName("微软雅黑");
        // 字体大小
        contentWriteFont.setFontHeightInPoints((short)18);
        contentCellStyle.setWriteFont(contentWriteFont);

        horizontalCellStyleStrategy.setContentWriteCellStyleList(ListUtils.newArrayList(contentCellStyle));
        return horizontalCellStyleStrategy;
    }

3.注册
 WriteSheet specs = EasyExcel.writerSheet(1,"xxx")
                    .needHead(Boolean.FALSE)
                    .head(VO.class)
                    .registerWriteHandler(new CustomCellWriteHandler())
                    .registerWriteHandler(specsStyleStrategy())
                    .build();

4.结果
第11行第2列单元格样式正确字体为 “Times New Roman” ，第11行第2列之前的所有单元格字体为通用的 “微软雅黑”，但是第11行第2列之后的所有单元格字体样式全变为了 “Times New Roman”...

5.期待结果
第11行第2列单元格样式正确字体为 “Times New Roman” ，第11行第2列之前和之后的所有单元格字体为通用的 “微软雅黑”。

**Comment by ljluestc** [comment]
```
public class CustomCellWriteHandler implements CellWriteHandler {
    private WriteCellStyle commonCellStyle; // 通用样式

    public CustomCellWriteHandler(WriteCellStyle commonCellStyle) {
        this.commonCellStyle = commonCellStyle;
    }

    @Override
    public void afterCellDispose(CellWriteHandlerContext context) {
        int rowIndex = context.getRowIndex();
        int columnIndex = context.getColumnIndex();

        if (rowIndex == 11 && columnIndex == 2) {
            WriteCellData<?> writeCellData = context.getFirstCellData();
            WriteCellStyle customCellStyle = new WriteCellStyle();
            WriteFont customFont = new WriteFont();
            customFont.setFontName("Times New Roman");
            customFont.setFontHeightInPoints((short) 10);
            customFont.setItalic(Boolean.TRUE);
            customCellStyle.setWriteFont(customFont);
            WriteCellStyle.merge(customCellStyle, writeCellData.getOrCreateStyle());
        } else {
            WriteCellData<?> writeCellData = context.getFirstCellData();
            WriteCellStyle cellStyle = writeCellData.getOrCreateStyle();
            WriteCellStyle.merge(commonCellStyle, cellStyle);
        }
    }
}

```

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
