### ISSUE TITLE
将数据写多个sheet，会导致

### ISSUE THREAD

**Issue by LucaOnly** [alibaba/easyexcel#243]
public void buildCurrentSheet(com.alibaba.excel.metadata.Sheet sheet) {
        if (this.sheetMap.containsKey(sheet.getSheetNo())) {
            this.currentSheet = (Sheet)this.sheetMap.get(sheet.getSheetNo());
        } else {
            this.currentSheet = this.workbook.createSheet(sheet.getSheetName() != null ? sheet.getSheetName() : sheet.getSheetNo() + "");
            this.currentSheet.setDefaultColumnWidth(20);
            this.sheetMap.put(sheet.getSheetNo(), this.currentSheet);
            this.buildHead(sheet.getHead(), sheet.getClazz());
            this.buildTableStyle(sheet.getTableStyle());
            if (this.needHead && this.excelHeadProperty != null) {
                this.appendHeadToExcel();
            }
        }

    }

这个代码中如果写sheet第二次进入，buildHead没有走，会导致当前context中的excelHeadProperty错误，异常

**Comment by zhuangjiaju** [comment]
非常感谢您的意见。这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
