### ISSUE TITLE
使用doWrite方法向excel写文件时能否设置从第几行开始写起

### ISSUE THREAD

**Issue by Zoeldas** [alibaba/easyexcel#2435]

**Comment by ttt-noora** [comment]
hello, please give me some time to implement it, thanks. If you have more detailed information, you can contact me or comment here.

**Comment by ttt-noora** [comment]
#2436

**Comment by zhuangjiaju** [comment]
这个不会支持，因为写入是流式的，不能往回写。
可以通过 relativeHeadRowIndex 来控制空几个后再写。
