### ISSUE TITLE
小数转换问题

### ISSUE THREAD

**Issue by MaskedMenhxy** [alibaba/easyexcel#244]
excel中文本类型的值 比如5.0在解析成String类型的时候会丢失后面的.0变成5

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。可以用`NumberFormat`注解 或者 自定义转换器来解决
