### ISSUE TITLE
读取文本格式的int存在问题

### ISSUE THREAD

**Issue by MoranSmile** [alibaba/easyexcel#2443]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述*
在数值格式下，1.0使用int类型读取存在问题，但如果使用文本格式就会报错。
**提示的异常或者没有达到的效果**
Convert data com.alibaba.excel.metadata.data.ReadCellData@9690669e to int error

**Comment by SUSTechEllison** [comment]
请给我一些时间，我会尽快修复它

**Comment by SUSTechEllison** [comment]
我刚才尝试成功复现了你的问题，并且我还发现在数值下使用int读取1.00依然存在问题，我会一并解决这个问题。

**Comment by zhuangjiaju** [comment]
该问题已经在`3.1.0`+版本里面解决，最新版本：[![Maven central](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel)
