### ISSUE TITLE
读取int类型将文末空格读取为0

### ISSUE THREAD

**Issue by MoranSmile** [alibaba/easyexcel#2446]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
读取excel文件时，在输入过数字的excel方格，即使后续删除，依然会将空格读取为0

**提示的异常或者没有达到的效果**
未提示异常，但读取结果错误

**Comment by Linly1080** [comment]
我可以帮忙修这个bug，可以把它分配给我吗

**Comment by MoranSmile** [comment]
> 我可以帮忙修这个bug，可以把它分配给我吗 @Linly1080 

好的，感谢回复，期待你的修复

**Comment by zhuangjiaju** [comment]
请定义成integer类型
