### ISSUE TITLE
easyExcel自定义导出功能 性能并不是很友好(因为我涉及到上下合并单元格的需求)

### ISSUE THREAD

**Issue by Mr-CSD** [alibaba/easyexcel#2449]
机器服务配置  8核64G  easyExcel版本:3.0.0-beta3   jvm性能暂且不谈，测试我自定义导出(存在上下单元格合并)平均每秒只能导出900行数据 ，追究代码发现,性能死在了单元格合并上,需要合并的单元格数据越多性能越糟糕。我把我合并单元格的代码粘上来，作者看一下这一块性能还能有什么更好的优化方案呢，因业务要求,我至少要保证在此机器上每秒可以导出三千行以上的数据,希望作者给点建议。作者如希望给点报酬也没问题，怎么说请你一杯咖啡应该也不算过分哈
我下面粘贴的是合并单元格的代码(我把整个类都粘贴了过来)：

package com.bozcloud.bozhi.analysis.excelHandler;

import cn.hutool.core.collection.CollUtil;
import cn.hutool.core.util.StrUtil;
import com.alibaba.excel.metadata.Head;
import com.alibaba.excel.metadata.data.WriteCellData;
import com.alibaba.excel.write.handler.CellWriteHandler;
import com.alibaba.excel.write.metadata.holder.WriteSheetHolder;
import com.alibaba.excel.write.metadata.holder.WriteTableHolder;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.util.CellRangeAddress;

import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

/**
 * Description: 生产进度明细自定义导出excelHandler
 * Date:2022-4-15 18:25:49
 *
 * @author 陈树栋
 */
@Slf4j
public class ProdPlanStatementCustomCellExcelHandler implements CellWriteHandler {

	public static final int MATERIAL_NO = 0;
	public static final int MATERIAL_NAME = 1;
	public static final int SALE_NO = 2;
	public static final int PROD_NO = 3;
	public static final int PLAN_NUM = 4;
	public static final int BALANCE_NUM = 5;
	public static final int FINISH_NUM = 6;
	public static final int DELIVERY_TIME = 7;
	public static final int PROJECT_STATUS = 8;
	public static final int START_TIME = 13;
	public static final int END_TIME = 14;
	public static final int ACTUAL_START_TIME = 15;
	public static final int CREATE_TIME = 16;
	public int lastRow;

	private final List<Integer> columnMergeList = new LinkedList<>();

	CopyOnWriteArrayList<String> list = new CopyOnWriteArrayList<>();

	public ProdPlanStatementCustomCellExcelHandler(int lastRow) {
		this.lastRow = lastRow;
	}

	@Override
	public void beforeCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Row row, Head head, Integer columnIndex, Integer relativeRowIndex, Boolean isHead) {
		//判断是否是头
		short height;
		if (isHead) {
			height = 680;
		} else {
			height = 450;
		}
		row.setHeight(height);
	}

	@Override
	public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, List<WriteCellData<?>> cellDataList, Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {
		//行索引
		int curRowIndex = cell.getRowIndex();
		//列索引
		int curColIndex = cell.getColumnIndex();

		//头无需合并
		if (!isHead) {

			//以第三列作为分点(计划工单编号)
			if (curColIndex == PROD_NO) {

				//当前行的值
				String currentValue = cell.getStringCellValue();
				//上一行的值
				String previousValue = cell.getSheet().getRow(curRowIndex - 1).getCell(PROD_NO).getStringCellValue();

				//判断如果上一行的值与当前行的值相同则合并此列的单元格
				if (StrUtil.equals(currentValue, previousValue)) {
					columnMergeList.add(curRowIndex - 1);
					columnMergeList.add(curRowIndex);
				}

				//判断如果上一行的值与当前行的值不同并且集合里面不为空则合并之前的单元格
				if (!StrUtil.equals(currentValue, previousValue)&&CollUtil.isNotEmpty(columnMergeList)) {
					Collections.sort(columnMergeList);
					Integer start = columnMergeList.get(0);
					Integer end = columnMergeList.get(columnMergeList.size() - 1);
					list.add(start + "," + end);
					columnMergeList.clear();
				}

				//判断当前行是否为最后一行,万一最后一行也有需要合并的则也需要合并
				if (curRowIndex == lastRow) {
					if (CollUtil.isNotEmpty(columnMergeList)) {
						Collections.sort(columnMergeList);
						Integer start = columnMergeList.get(0);
						Integer end = columnMergeList.get(columnMergeList.size() - 1);
						list.add(start + "," + end);
					}

					//合并单元格
					Sheet sheet = writeSheetHolder.getSheet();

					list.forEach(item->{
						String[] split = item.split(",");
						if (split.length > 1) {
							int start = Integer.parseInt(split[0]);
							int end = Integer.parseInt(split[1]);

							CellRangeAddress materialNoColumn = new CellRangeAddress(start, end, MATERIAL_NO, MATERIAL_NO);
							CellRangeAddress materialNameColumn = new CellRangeAddress(start, end, MATERIAL_NAME, MATERIAL_NAME);
							CellRangeAddress saleNoColumn = new CellRangeAddress(start, end, SALE_NO, SALE_NO);
							CellRangeAddress prodNoColumn = new CellRangeAddress(start, end, PROD_NO, PROD_NO);
							CellRangeAddress planNumColumn = new CellRangeAddress(start, end, PLAN_NUM, PLAN_NUM);
							CellRangeAddress balanceColumn = new CellRangeAddress(start, end, BALANCE_NUM, BALANCE_NUM);
							CellRangeAddress finishColumn = new CellRangeAddress(start, end, FINISH_NUM, FINISH_NUM);
							CellRangeAddress deliveryTimeColumn = new CellRangeAddress(start, end, DELIVERY_TIME, DELIVERY_TIME);
							CellRangeAddress projectStatusColumn = new CellRangeAddress(start, end, PROJECT_STATUS, PROJECT_STATUS);
							CellRangeAddress startTimeColumn = new CellRangeAddress(start, end, START_TIME, START_TIME);
							CellRangeAddress endTimeColumn = new CellRangeAddress(start, end, END_TIME, END_TIME);
							CellRangeAddress actualStartTimeColumn = new CellRangeAddress(start, end, ACTUAL_START_TIME, ACTUAL_START_TIME);
							CellRangeAddress createTimeColumn = new CellRangeAddress(start, end, CREATE_TIME, CREATE_TIME);

							sheet.addMergedRegionUnsafe(materialNoColumn);
							sheet.addMergedRegionUnsafe(materialNameColumn);
							sheet.addMergedRegionUnsafe(saleNoColumn);
							sheet.addMergedRegionUnsafe(prodNoColumn);
							sheet.addMergedRegionUnsafe(planNumColumn);
							sheet.addMergedRegionUnsafe(deliveryTimeColumn);
							sheet.addMergedRegionUnsafe(projectStatusColumn);
							sheet.addMergedRegionUnsafe(startTimeColumn);
							sheet.addMergedRegionUnsafe(endTimeColumn);
							sheet.addMergedRegionUnsafe(actualStartTimeColumn);
							sheet.addMergedRegionUnsafe(createTimeColumn);
							sheet.addMergedRegionUnsafe(balanceColumn);
							sheet.addMergedRegionUnsafe(finishColumn);
						}
					});

				}
			}
		}
	}
}

这个是导出的代码片段(看看这里是否还能优化呢,或者我是否写的过于啰嗦?):
		try {
			EasyExcel.write(getOutputStream(fileName, response))
					.excelType(ExcelTypeEnum.XLSX).sheet(sheetName)
					.head(prodPlanStatementHeader)
					.registerWriteHandler(ProdPlanStatementExcelHandler.getStyleStrategy())
					.registerWriteHandler(new ProdPlanStatementCustomCellExcelHandler(prodPlanStatementData.size()))
					.registerWriteHandler(new ProdPlanStatementExcelHandler())
					.doWrite(prodPlanStatementData);

		} catch (Exception e) {
			log.error("error:", e);
			e.printStackTrace();
		}

**Comment by Sdky** [comment]
请问有什么解决方法么？
