### ISSUE TITLE
列宽自适应问题

### ISSUE THREAD

**Issue by vogueboy** [alibaba/easyexcel#245]
看例子，设置了下面这个也不会自适
sheet1.setAutoWidth(Boolean.TRUE);
再看一下代码，调用链根本没有什么地方使用到，确实可以列宽自适应吗？？

**Comment by zhuangjiaju** [comment]
目前没有完美的自动列宽策略。poi也无法实现。可以使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。 相对靠谱的自适应列宽方案

**Comment by papadave66** [comment]
在最新的官方文档中，说是可以使用 `registerWriteHandler(new LongestMatchColumnWidthStyleStrategy())`  实现自动列宽
[easyexcel官方demo](https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write)
