### ISSUE TITLE
easyexcel 是否可以支持 bean 约束注解

### ISSUE THREAD

**Issue by wenchaomartin** [alibaba/easyexcel#2454]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```

比如说 我们导入excel 的时候 ，某些单元格上加一些 约束， 比如说 非空 ，字段长度， 正则， 等等。 
如果违反了， 实现能下载原始表格，提示错误。
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
这个目前不支持 需要自己开发
