### ISSUE TITLE
2.x版本和3.0.x版本使用问题

### ISSUE THREAD

**Issue by lyx-git** [alibaba/easyexcel#2458]
**触发场景描述**
         2.x版本使用password加密，输入密码打开会出现格式错误或者内容错误，不使用加密，可以正常打开excel，样式也可以正常生效，改成3.0.x 版本之后，可以正常打开加密内容，但是我自己写了一个样式继承 cellWriteHandler 进行单元格样式的处理，样式都不能生效

**Comment by zhuangjiaju** [comment]
可以改成 3+吧，样式处理的 参照：https://www.yuque.com/easyexcel/doc/write#W4u1e 改动量很小
