### ISSUE TITLE
关于使用forceNewRow之后  使用OnceAbsoluteMergeStrategy合并单元格  部分失效的问题 

### ISSUE THREAD

**Issue by YeYuZhang** [alibaba/easyexcel#2459]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**
![a25c61b302455867acaea0a650fae48](https://user-images.githubusercontent.com/65891396/166135191-7e81afd5-90b5-4101-b696-77981f79188f.png)
[模板.xlsx](https://github.com/alibaba/easyexcel/files/8598401/default.xlsx)

**Comment by YeYuZhang** [comment]
![33f265cf28c64c35f6bf18939fb61fc](https://user-images.githubusercontent.com/65891396/166135224-a6e96c6b-bf1a-4b12-bf0a-685360989c87.png)

**Comment by YeYuZhang** [comment]
使用OnceAbsoluteMergeStrategy   根据项目类型    通过个数算出合并的坐标  合并

**Comment by TungMan0801** [comment]
您好，我们对这个bug很感兴趣，请问可以提供更多更完整的触发主方法代码以及类似于getAllOnceAbsoluteMergeStrategy的方法内容有助于我们复现和修复吗？^^   -SUSTechHeyTeam

**Comment by YeYuZhang** [comment]
![1651470765(1)](https://user-images.githubusercontent.com/65891396/166190599-04663a9e-9eb1-4590-b91b-a64a9b09242a.png)
合并坐标都是根据 项目类型个数计算

**Comment by zhuangjiaju** [comment]
能提供下具体合并的单元格的行数么？

**Comment by zhuangjiaju** [comment]
就是异常的哪一行

**Comment by YeYuZhang** [comment]
就2行啊 OnceAbsoluteMergeStrategy onceAbsoluteMergeStrategy1 =
                new OnceAbsoluteMergeStrategy(13,
                    14，
                        0,
                        0);

**Comment by 592468495** [comment]
> 就2行啊 OnceAbsoluteMergeStrategy onceAbsoluteMergeStrategy1 = new OnceAbsoluteMergeStrategy(13,140,0); 图中i=6，j=2

请问这个问题解决了吗，我也有这个问题

**Comment by YeYuZhang** [comment]
换一种方式解决！自己重写CellWriteHandler   合并坐
![1655709967578](https://user-images.githubusercontent.com/65891396/174547614-69505812-c8e4-4b89-82d0-e438c80dd64a.png)
标

**Comment by 592468495** [comment]
> 换一种方式解决！自己重写CellWriteHandler 合并坐 ![1655709967578](https://user-images.githubusercontent.com/65891396/174547614-69505812-c8e4-4b89-82d0-e438c80dd64a.png) 标

感谢

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
