### ISSUE TITLE
easyexcel读取07版数据没问题，读取03版就没读到数据

### ISSUE THREAD

**Issue by daxiong-liang** [alibaba/easyexcel#246]
如题所示，我在本地中读取07版的excel文件没问题，是有数据的
同样读取数据量一样的03版excel文件，却为空
代码如下：
String filePath = "G:\\tmp\\file\\2003-2.xls";
//String filePath = "G:\\tmp\\file\\2007.xlsx";
    	
File file = new File(filePath);
InputStream inputStream = new BufferedInputStream(new FileInputStream(filePath));

List<Object> data = EasyExcelFactory.read(inputStream, new Sheet(0, 1));
inputStream.close();

03版的时候，读取时候，定位看了一下listener的invoke读不到任何数据，找不到原因在哪里

**Comment by daxiong-liang** [comment]
已找到问题

**Comment by maleeeei** [comment]
这个如何解决的，我这里报异常：
java.lang.NoClassDefFoundError: org/apache/poi/poifs/filesystem/FileMagic

	at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:34)

**Comment by stonesingsong** [comment]
> 这个如何解决的，我这里报异常：
> java.lang.NoClassDefFoundError: org/apache/poi/poifs/filesystem/FileMagic
> 
> ```
> at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:34)
> ```

我读03excel也出现了这个问题，请问你解决了吗?

**Comment by stonesingsong** [comment]
@daxiong-liang

**Comment by stonesingsong** [comment]
> 已找到问题

@daxiong-liang 请问你是什么原因，我03excel读出来也是空数据，谢谢

**Comment by daxiong-liang** [comment]
@stonesingsong sheet的起始数字不是0开始，是1，我就只有一个sheet，但是我写0了，所以读不了
