### ISSUE TITLE
有，设置整个excel的所有单元格的格式为文本的方法吗

### ISSUE THREAD

**Issue by fj1580332947** [alibaba/easyexcel#2465]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
自定义拦截器，`sheet.setDefaultColumnStyle` 可以设置一列的样式

**Comment by JTongChen** [comment]
> 自定义拦截器，`sheet.setDefaultColumnStyle` 可以设置一列的样式
![image](https://github.com/alibaba/easyexcel/assets/17989583/9ab0075d-9a31-4baf-adb9-877c5ec0aaa3)
用该方式设置了style之后，出现如图情况，感觉已写入数据的单元格还是为常规，输入"001"会变成"1"。
但是如果在后面的空白行写入"001"又正常？
