### ISSUE TITLE
相同excel文件，写不同的sheet页，可不可以支持不同的WriteHandler

### ISSUE THREAD

**Issue by YngJian** [alibaba/easyexcel#2467]
excelWriter = EasyExcel.write(response.getOutputStream()).registerWriteHandler(cellMergeStrategy).build();
不同的sheet页好像只能注册一个，而且每个sheet页都生效了。
可不可以支持特定的sheet页特定的WriteHandler

**Comment by zhuangjiaju** [comment]
registerWriteHandler 写到 `wirtesheet` 里面
