### ISSUE TITLE
导出数据，动态合并单元格

### ISSUE THREAD

**Issue by yangld2009** [alibaba/easyexcel#247]
我想导出这种效果，如何做：

![123](https://user-images.githubusercontent.com/34273054/53714758-89cf8b80-3e8a-11e9-8606-86be703ff017.jpg)

**Comment by yangld2009** [comment]
不好意思，图片上传错了

**Comment by yangld2009** [comment]
![123](https://user-images.githubusercontent.com/34273054/53714832-d9ae5280-3e8a-11e9-90f5-e8815ee1d05e.png)

**Comment by yangld2009** [comment]
我想实现这个效果，如何做？

**Comment by wqh0109663** [comment]
我今天刚接触这个玩意儿 我感觉是不是可以嵌套一个rowmodel这样的东西？

**Comment by JohnFantasy** [comment]
请问有没有解决？碰到同样的需求了。

**Comment by fish7790714** [comment]
先尝试 把xlsx写成这样
![image](https://user-images.githubusercontent.com/18475586/55464169-12c61800-562d-11e9-921e-5d7d7198f84d.png)
然后 调用方法
```java
        writer.merge(0, 2, 1, 1);
        writer.merge(3, 5, 1, 1);
```
这样就可以了，实际使用 可以加上for循环

**Comment by teaRRe** [comment]
@fish7790714  请问merge方法合并的是哪一个Sheet呢，假如有多个Sheet的话？

**Comment by FollowTheTrend** [comment]
> @fish7790714 请问 merge 方法合并的是哪一个 Sheet 呢, 假如有多个 Sheet 的话?

你好, 我也遇到了同样的问题.
答案是: 合并的是你最近一次 writer.write 的 sheet, 亲测

**Comment by zhuangjiaju** [comment]
新版本 可以有合并策略。请使用最新版本 更方便
