### ISSUE TITLE
写入excel时，如何隐藏title标题呢？我不想有标题，想第一行就是数据，但是@ExcelProperty默认会把属性名作为标题

### ISSUE THREAD

**Issue by ForDreamWorld** [alibaba/easyexcel#2481]
写入excel时，如何隐藏title标题呢？我不想有标题，想第一行就是数据，但是@ExcelProperty默认会把属性名作为标题

**Comment by kangyu06** [comment]
简单啊，类似这样就好了，多看看官网demo
![image](https://user-images.githubusercontent.com/53601447/168737328-740b0827-ec54-4e47-92ea-62f680429a2a.png)

**Comment by kangyu06** [comment]
write里传一个参数就行。

**Comment by zhuangjiaju** [comment]
`ignorehead=true` 设置
