### ISSUE TITLE
有一个headClass,需要根据条件判断是否展示某列

### ISSUE THREAD

**Issue by joey-happy** [alibaba/easyexcel#2482]

**Comment by joey-happy** [comment]
@Data
public class SubjectEcrfFormDataExcelVO {
    @ExcelProperty("表单代码")
    private String code;
  
    @ExcelProperty("表单名称")
    private String name;
}

name字段是在某种条件下展示到excel字段中 在不满足条件的时候 不展示 能实现吗？

**Comment by kangyu06** [comment]
![image](https://user-images.githubusercontent.com/53601447/168736959-949bda15-e622-45d6-8248-d046ecc478ec.png)
官网demo里支持动态表头，非注解。

**Comment by kangyu06** [comment]
![image](https://user-images.githubusercontent.com/53601447/168737051-f26cd2ce-f01c-4b7e-866e-e26c3e106491.png)

**Comment by joey-happy** [comment]
> ![image](https://user-images.githubusercontent.com/53601447/168737051-f26cd2ce-f01c-4b7e-866e-e26c3e106491.png)

/**
     * 构建sheet
     *
     * @param sheetName
     * @param sheetHeadClazz
     * @param excludeColumnFiledNameCollection
     * @param dataList
     * @return
     */
    public static WriteSheetDataWrapper build(String sheetName, Class<?> sheetHeadClazz, Collection<String> excludeColumnFiledNameCollection, Collection<?> dataList) {
        ExcelWriterSheetBuilder sheetBuilder = EasyExcel.writerSheet(sheetName).registerWriteHandler(new LongestMatchColumnWidthStyleStrategy());

        if (ObjectUtil.isNotNull(sheetHeadClazz)) {
            sheetBuilder.head(sheetHeadClazz).needHead(true);
        }

        if (CollUtil.isNotEmpty(excludeColumnFiledNameCollection)) {
            sheetBuilder.excludeColumnFiledNames(excludeColumnFiledNameCollection);
        }

        WriteSheet sheet = sheetBuilder.build();
        return new WriteSheetDataWrapper(sheet, dataList);
    }

我用excludeColumnFiledNames这个方法解决了

**Comment by kangyu06** [comment]
嗯，我刚刚想回复你用excludeColumnFiledNames这个，哈哈。

**Comment by joey-happy** [comment]
> 嗯，我刚刚想回复你用excludeColumnFiledNames这个，哈哈。

多谢哈 第一次用这个 api太多 不知道用啥
