### ISSUE TITLE
通过流读取csv文件失败

### ISSUE THREAD

**Issue by wujiea** [alibaba/easyexcel#2484]
**异常代码**
版本3.1.0
```java
//  File excleFile = new File("d:/dl/test.csv");
        InputStream inputStream = new FileInputStream("d:/dl/test.csv");
        EasyExcel.read(inputStream, new ReadListener() {
            @Override
            public void invoke(Object data, AnalysisContext context) {
                log.info(JSON.toJSONString(data));
            }

            @Override
            public void doAfterAllAnalysed(AnalysisContext context) {

            }
        }).sheet().doRead();
```
**异常提示**
com.alibaba.excel.exception.ExcelCommonException: Convert excel format exception.You can try specifying the 'excelType' yourself
**建议描述**

**Comment by TungMan0801** [comment]
sheet()前加excelType就可以指定了

**Comment by wujiea** [comment]
> sheet()前加excelType就可以指定了

加上excelType确实是可以。我看了源码，流那里有判断是CSV类型的，是不是那个判断有问题？
`private static ExcelTypeEnum recognitionExcelType(InputStream inputStream) throws Exception {
        // Grab the first bytes of this stream
        byte[] data = IOUtils.peekFirstNBytes(inputStream, MAX_PATTERN_LENGTH);
        if (findMagic(XLSX.magic, data)) {
            return XLSX;
        } else if (findMagic(CSV.magic, data)) {
            return CSV;
        } else if (findMagic(XLS.magic, data)) {
            return XLS;
        }
        throw new ExcelCommonException(
            "Convert excel format exception.You can try specifying the 'excelType' yourself");
    }`

**Comment by LZhComing** [comment]
我也复现了这个问题, 就是 ExcelTypeEnum 里面文件前面的编码有问题对不上
![image](https://user-images.githubusercontent.com/37789928/178206911-a9e29a0e-a9e7-4d9f-95ed-98006f75660e.png)

**Comment by LZhComing** [comment]
而且如果是从 xlsx / xls 重命名过来的 csv 不会有问题，直接写内容的 csv 就会出现此问题

**Comment by zhuangjiaju** [comment]
新版本应该已经解决这个问题了

**Comment by zhengzzv** [comment]
感谢回复
