### ISSUE TITLE
填充excel，填充的内容如何设置最小行高的前提下，填充的内容超过最小行高时，实现单元格或行的自动行高？

### ISSUE THREAD

**Issue by xunchong99** [alibaba/easyexcel#2487]
使用填充excel功能，填充的内容如何在设置最小行高的前提下，在填充的内容超过最小行高时，实现单元格或行的自动行高？

**Comment by liuhongjie001** [comment]
同问

**Comment by liuhongjie001** [comment]
针对于填充excel 模板实现行高自适应，可调整模板行高自适应，生成excel 即正常。

**Comment by yunwenlong** [comment]
我调整模板行高自适应，只有第一条数据有效果，其他数据无效果。

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
