### ISSUE TITLE
csv通过流的方式去解析扔出 "Convert excel format exception.You can try specifying the 'excelType' yourself"异常

### ISSUE THREAD

**Issue by wo-wo-wo** [alibaba/easyexcel#2495]
场景: 通过这种方式去远程获取流然后去解析读文件格式会识别不出来文件类型
EasyExcel.read(new URL("url").openStream()).build();

异常代码 ExcelTypeEnum#recognitionExcelType
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/38678744/169932370-8efe11aa-4981-43a3-89e1-5d7072cb8f68.png">

**Comment by TungMan0801** [comment]
read()方法后加excelType(ExcelTypeEnum.CSV)就能解决了，记得用最新版

**Comment by wo-wo-wo** [comment]
如果用excelType(ExcelTypeEnum.CSV)就能解决 那么如下图中的代码又有啥子意义呢,你都让我去用excelType去设置类型了，为啥还要适配用流的方式去判断格式类型
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/38678744/170622922-38cdfff8-bc5d-4db0-9f1b-e9163cb3d141.png">
<img width="964" alt="image" src="https://user-images.githubusercontent.com/38678744/170623033-592e35ea-cc8c-469f-9974-df459b10366e.png">

**Comment by zhuangjiaju** [comment]
3.1.0 版本应该会自动识别了

**Comment by wo-wo-wo** [comment]
我就是用的最新版本3.1.0 然后扔出的这个异常

**Comment by Bleoo** [comment]
我就是用的最新版本3.1.1 一样扔出的这个异常，magic 识别有问题

**Comment by Bleoo** [comment]
能不能重开这个 issue

**Comment by wo-wo-wo** [comment]
> 能不能重开这个 issue

好的

**Comment by wo-wo-wo** [comment]
> 场景: 通过这种方式去远程获取流然后去解析读文件格式会识别不出来文件类型 EasyExcel.read(new URL("url").openStream()).build();
> 
> 异常代码 ExcelTypeEnum#recognitionExcelType <img alt="image" width="1086" src="https://user-images.githubusercontent.com/38678744/169932370-8efe11aa-4981-43a3-89e1-5d7072cb8f68.png">

最新版本3.1.1 一样扔出的这个异常，magic 识别有问题
