### ISSUE TITLE
怎么读取多个excel文件？？？有个需求是读取两个excel文件合并数据生成一个excel，看文档没看到可以读取多个excel的api

### ISSUE THREAD

**Issue by adsion** [alibaba/easyexcel#2496]
怎么读取多个excel文件？？？有个需求是读取两个excel文件合并数据生成一个excel，看文档没看到可以读取多个excel的api

**Comment by qianlingo** [comment]
https://www.yuque.com/easyexcel/doc/read
文档-“读多个sheet”模块
