### ISSUE TITLE
    @DateTimeFormat(“yyyy-MM-dd HH:mm:ss”)不生效 导出execl之后 日期变成###########

### ISSUE THREAD

**Issue by joey-happy** [alibaba/easyexcel#2503]
@DateTimeFormat(“yyyy-MM-dd HH:mm:ss”)
    @ExcelProperty("操作时间")
    private Date createTime;

**Comment by TungMan0801** [comment]
这个我有遇到，点单元格的话可以看到正确内容已被填充，原因可能是列宽不够大，调整列宽或字号就可以看到完整的了

**Comment by joey-happy** [comment]
> 

我点击单元格也不行 我现在换成String类型了

**Comment by joey-happy** [comment]
> 这个我有遇到，点单元格的话可以看到正确内容已被填充，原因可能是列宽不够大，调整列宽或字号就可以看到完整的了

我点击单元格也不行 我现在换成String类型了

**Comment by joey-happy** [comment]
> 把列宽拉长

多谢  可以了

**Comment by joey-happy** [comment]
1.换成string类型 2.拉宽解决
