### ISSUE TITLE
EasyExcel.write(response.getOutputStream())中午乱码

### ISSUE THREAD

**Issue by pusamm1314** [alibaba/easyexcel#2516]
版本：2.2.10
Controller:
`@ApiOperation(value = "统计分析：导出")
	@RequestMapping(value = "exportCountyResultList", method = RequestMethod.GET)
	public void exportCountyResultList(HttpServletRequest request,HttpServletResponse response) throws Exception {
		String authToken = (request.getParameter("token") != null) ? request.getParameter("token") : request.getHeader("Authorization");
		String userId = BusinessJWTTokenUtil.getUsernameFromToken(authToken);
		String fileName = System.currentTimeMillis() + ".xlsx";
		reportService.exportCountyResultList(response,userId, fileName);
	}`
Service:
`public void exportCountyResultList(HttpServletResponse response, String userId, String fileName) throws CustomException, IOException {
OutputStream outputStream = new FileOutputStream(filePath);
		response.setContentType("application/vnd.ms-excel");
		response.setCharacterEncoding(StandardCharsets.UTF_8.toString());
		// 处理中文乱码
		String encode = URLEncoder.encode(fileName, StandardCharsets.UTF_8.toString());
		response.setHeader("Content-disposition", "attachment;filename=" + encode + ExcelTypeEnum.XLSX.getValue());

		EasyExcel.write(response.getOutputStream())
			.registerWriteHandler(new MyMergeStrategy(cellRangeAddressList))
			.registerWriteHandler(new SimpleColumnWidthStyleStrategy(20))
			.registerWriteHandler(writeColorHandler).head(headerList)
			.autoCloseStream(Boolean.TRUE).sheet("导出数据").doWrite(listO);
}`

Wps打不开，PostMan调用乱码

**Comment by pusamm1314** [comment]
PostMan返回值

**Comment by pusamm1314** [comment]
![image](https://user-images.githubusercontent.com/57690470/170971644-719de542-c72a-4ec7-be51-b6b6df0fd5fd.png)

**Comment by zhuangjiaju** [comment]
请使用浏览器访问，还不行的话参照：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/read#%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%8D%A2%E7%AD%89%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86

**Comment by doubleLLL3** [comment]
我也遇到了，用file的方式就没问题。
