### ISSUE TITLE
自定义的动态表头如何设置表头不可编辑

### ISSUE THREAD

**Issue by sermonlizhi** [alibaba/easyexcel#2527]

**Comment by sermonlizhi** [comment]
通过下面的代码设置不可编辑，也是没有用
```java
public class CustomCellWriteHandler implements CellWriteHandler {
    @Override
    public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, List<WriteCellData<?>> cellDataList, Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {
        if (isHead){
            CellStyle cellStyle = cell.getCellStyle();
            cellStyle.setLocked(true);
            WriteFont writeFont = new WriteFont();
            writeFont.setFontHeightInPoints((short) 15);
            cell.setCellStyle(cellStyle);
        }
    }
}
```

**Comment by gongxuanzhang** [comment]
POI

> 通过下面的代码设置不可编辑，也是没有用
> 
> ```java
> public class CustomCellWriteHandler implements CellWriteHandler {
>     @Override
>     public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, List<WriteCellData<?>> cellDataList, Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {
>         if (isHead){
>             CellStyle cellStyle = cell.getCellStyle();
>             cellStyle.setLocked(true);
>             WriteFont writeFont = new WriteFont();
>             writeFont.setFontHeightInPoints((short) 15);
>             cell.setCellStyle(cellStyle);
>         }
>     }
> }
> ```

POI要求  cellStyle.setLocked(true); 和保护密码同时创建才会生效

```
 Sheet sheet = workbook.getSheetAt(0);
            sheet.protectSheet("password"); // 设置表单保护密码
```

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
