### ISSUE TITLE
导入导出字段问题

### ISSUE THREAD

**Issue by genshin-Usagi** [alibaba/easyexcel#2528]
**一个类，导入需要所有字段，导出需要忽略几个字段，怎么操作**

**Comment by zhuangjiaju** [comment]
https://easyexcel.opensource.alibaba.com/docs/current/api/#excelignoreunannotated 参照

**Comment by genshin-Usagi** [comment]
忽略字段是直接不参与读写了，需求，某个字段，只参与读，不参与写

**Comment by genshin-Usagi** [comment]
> https://easyexcel.opensource.alibaba.com/docs/current/api/#excelignoreunannotated参照

只是写作，而不是直接参与，而不是参与，而不是参与
