### ISSUE TITLE
怎么给单元格设置自定义颜色，不是用IndexedColors中的颜色

### ISSUE THREAD

**Issue by nyzs** [alibaba/easyexcel#2529]
网上找了很多方法都用不了，没找到自己设置rgb颜色的方法

**Comment by gongxuanzhang** [comment]
实现CellWriteHandler拿到单元格对象
给你一段伪代码

```
// 创建自定义颜色对象
XSSFColor customColor = new XSSFColor(new java.awt.Color(128, 128, 128));

// 创建CellStyle对象
CellStyle style = workbook.createCellStyle();
style.setFillForegroundColor(customColor);
style.setFillPattern(FillPatternType.SOLID_FOREGROUND);

// 将CellStyle应用到单元格上
Cell cell = row.createCell(0);
cell.setCellValue("Hello World");
cell.setCellStyle(style);
```

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue

**Comment by laokewang** [comment]
你这个是什么版本的依赖，我2.2.6版本，setFillForegroundColor的入参是short类型 
![Uploading image.png…]()

**Comment by startbug** [comment]
需要将CellStyle强转成XSSFCellStyle，在调用setFillForegroundColor就可以了
亲测有效
Cell curCell = context.getCell();
Workbook workbook = context.getWriteWorkbookHolder().getWorkbook();
XSSFCellStyle cellStyle = (XSSFCellStyle) workbook.createCellStyle();
cellStyle.setFillForegroundColor(new XSSFColor(new Color(140, 221, 250)));
cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
curCell.setCellStyle(cellStyle);
context.getFirstCellData().setWriteCellStyle(null);
