### ISSUE TITLE
构造器中参数headLineMun的含义是什么？能具体解释其作用吗？

### ISSUE THREAD

**Issue by githublms** [alibaba/easyexcel#253]
public Sheet(int sheetNo, int headLineMun, Class<? extends BaseRowModel> clazz, String sheetName,
                 List<List<String>> head) {
        this.sheetNo = sheetNo;
        this.clazz = clazz;
        this.headLineMun = headLineMun;
        this.sheetName = sheetName;
        this.head = head;
    }

**Comment by hiyaojie** [comment]
应该是标题所占的行数吧

**Comment by helloworldtang** [comment]
![image](https://user-images.githubusercontent.com/13701989/56076717-c4700080-5e06-11e9-87fe-f38189716867.png)

如果当前列小于headLineMun则是表头
```java
/** Parsing header content **/
```

**Comment by dawangdedawang5** [comment]
> ![image](https://user-images.githubusercontent.com/13701989/56076717-c4700080-5e06-11e9-87fe-f38189716867.png)
> 
> 如果当前列小于headLineMun则是表头 【sheet解析时，第一行的下标是0】
> 
> ```java
> /** Parsing header content **/
> ```

但是 headLineMun 和 sheetNo 这两个参数并不会影响到你生成的excel

**Comment by zhuangjiaju** [comment]
这个参数已经删除，建议使用新版本
