### ISSUE TITLE
写入文件，当sheet页超过最大行时，如何让新的数据写入第二个sheet页或者第二个Excel文件

### ISSUE THREAD

**Issue by JadeQi** [alibaba/easyexcel#2530]
**写入文件，当sheet页超过最大行时，如何让新的数据写入第二个sheet页或者第二个Excel文件**
![image](https://user-images.githubusercontent.com/35448093/172291500-05334797-153c-43bc-83b0-9f58c09f05bf.png)
当写入Excel文件数据，超过了1048575(Excel最大行数限制) 会报错，所以想请教 如何让新的数据写入第二个sheet页或者第二个Excel文件

**Comment by zhuangjiaju** [comment]
参照多次写入，然后自己判断超过100W，切换到下一个sheet
