### ISSUE TITLE
在自己工程里面实现简单的demo case时读不到数据。

### ISSUE THREAD

**Issue by lilylei013** [alibaba/easyexcel#2531]
代码很简单，就是和IndexOrNameData 一样
@Getter
@Setter
public class IndexOrNameData implements Serializable {
    @ExcelProperty(index = 2)
    private Double doubleData;

    @ExcelProperty(index = 0)
    private String string;
    @ExcelProperty(index = 1)
    private Date date;
}
依赖是这些， apache 4.1.1 换成4.1.2 也是一样的效果
 implementation('org.apache.poi:poi:4.1.1')
    implementation('org.apache.poi:poi-ooxml:4.1.1')
    implementation('org.apache.poi:poi-scratchpad:4.1.1')
    implementation('com.alibaba:easyexcel:3.1.0')
  implementation('com.alibaba:fastjson:1.2.78')
    implementation 'org.projectlombok:lombok:1.18.22'

没有报任何错误和异常，但是读不到任何值，本地debug发现原因应该是这里
ModelBuildEventListener 107 行，put后，dataMap依然为空

**Comment by lilylei013** [comment]
<img width="1009" alt="step1_parse" src="https://user-images.githubusercontent.com/36144717/172326917-56648a31-6b03-41a9-802c-5f303c6ac1da.PNG">

<img width="945" alt="step2_put" src="https://user-images.githubusercontent.com/36144717/172326951-89957372-ba92-4c6b-bae8-e478b6841d2d.PNG">

**Comment by zhuangjiaju** [comment]
删除所有poi试试 用自带的

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决，如果未解决请重新打开问题
