### ISSUE TITLE
03版excel 在解析sheet页表格，在表格中存在批注的情况下,首先他会读取完所有行之后在次读取所有行列中的批注

### ISSUE THREAD

**Issue by wo-wo-wo** [alibaba/easyexcel#2532]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**触发场景描述**
03版excel 在解析sheet页表格，在表格中存在批注的情况下,首先他会读取完所有行之后在次读取所有行列中的批注
[test.xls](https://github.com/alibaba/easyexcel/files/8858082/test.xls)

**触发Bug的代码**
```java
   
public class Read {

    public static  class TestReadListener implements ReadListener<LinkedHashMap<Integer, Object>> {
        @Override
        public void invoke(LinkedHashMap<Integer, Object> data, AnalysisContext context) {
            //行
            Integer rowIndex = context.readRowHolder().getRowIndex();
            System.out.println("---当前行数:"+rowIndex+"列数据:"+ JSON.toJSONString(data) +" ----");
        }

        @Override
        public void doAfterAllAnalysed(AnalysisContext context) {

        }
    }
    
    public static void main(String[] args) {
        EasyExcel.read(new File(${path})).ignoreEmptyRow(false).headRowNumber(0).registerReadListener(new TestReadListener()).doReadAll();
    }
}



```
**提示的异常或者没有达到的效果**
表格:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/38678744/172524180-8d574063-97ea-42ba-9407-eca69b0a2f8a.png">
解析结果
<img width="1571" alt="image" src="https://user-images.githubusercontent.com/38678744/172523851-48269fef-6875-499d-b15a-d8a00296c41d.png">

**Comment by zhuangjiaju** [comment]
符合预期，两个2数据存在不同的地方，如果要一起读取需要都放到内存
