### ISSUE TITLE
使用模板导出数据怎样动态设置背景颜色

### ISSUE THREAD

**Issue by Nonchen** [alibaba/easyexcel#2537]
在使用模板导出数据时，怎样快速动态设置每行数据中的背景颜色

**Comment by zhuangjiaju** [comment]
自定义样式：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
