### ISSUE TITLE
目前使用"不创建对象的读"解析动态表头时,无法区分时间内容,并格式化

### ISSUE THREAD

**Issue by xuningnh** [alibaba/easyexcel#2538]
之前项目里是使用创建对象的方式,用`@DateTimeFormat("yyyy-MM-dd HH:mm:ss")`注解,将时间进行格式化;
但是现在,由于产品迭代,上传的Excel表头变成动态的了;
查阅文档,在使用`public void invoke(Map<Integer, String> data, AnalysisContext context)`进行解析行内容时,日期被默认格式化成;yyyy/MM/dd这种,导致和原有代码不兼容;
由于Excel里存储时间的CellDataTypeEnum是NUMBER,虽然我可以在`EasyExcel.read()`的时候使用自定义转换器针对NUMBER类型格式化,但是在重写`convertToJavaData()`的时候无法区分日期和普通数字(或许是我用的方法不对??但是文档里没有更清晰的说明);
希望easyExcel团队能提出更有效的办法解决这种情况

**Comment by zhuangjiaju** [comment]
参照定义样式：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F 
或者自定义转换器：
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/read#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%BD%AC%E6%8D%A2%E5%99%A8
