### ISSUE TITLE
使用ExcelWriter.write(Collection<?> data, WriteSheet writeSheet)无法真正落盘到磁盘文件

### ISSUE THREAD

**Issue by wigennn** [alibaba/easyexcel#2539]
**问题描述**
当我执行完方法后，
```java
   excelWriter.write(Collection<?> data, WriteSheet writeSheet)
```
打开本地的excel文件，发现是空表格无写入的数据，
只有真正执行完方法，
```java
    excelWriter.finish();
```
此时流关闭了，才会把数据真正写入到表格文件中，
如何才能excelwriter.write完立马落文件,又可以下次继续写入？

**Comment by Hsiang-YS** [comment]
大哥救大命，我是说怎么调用excelWriter.write方法之后老提示文件文件损坏。

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
