### ISSUE TITLE
建议ReadListener的onException方法可以自主选择异常是否抛出，方便在读文件的时候自己做数据处理部分的逻辑

### ISSUE THREAD

**Issue by wxy2015** [alibaba/easyexcel#2540]
我在使用ReadListener接口读excel的时候，想在invoke方法里增加业务相关的代码逻辑，可能需要通过抛出异常的方法，结束某行数据解析，但是我无法使用自带的ExcelDataConvertException，因为我在invoke方法中无法获取ExcelDataConvertException初始化需要的参数，所以我使用自定义Exception类，但是我自定义的Exception被捕获到后总是会抛出去，直接结束了整个任务，因此我想可以使用自定义异常，而且可以决定是否要抛出异常，结束整个解析还是结束单行的解析

**Comment by zhuangjiaju** [comment]
抛出异常了 怎么结束单行解析？ 你在最外层捕获异常了，不可能在回到解析器里面了
