### ISSUE TITLE
异常处理实现中能否解析失败数据为对应导入类，像解析成功数据一样？

### ISSUE THREAD

**Issue by qinzhijiang** [alibaba/easyexcel#2541]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
这个没法实现，已经转换失败了就不可能拼成正确的对象了
