### ISSUE TITLE
关于上传excel测试代码中关键注释`DemoDataListener 不能被spring管理`的疑问

### ISSUE THREAD

**Issue by nyingping** [alibaba/easyexcel#2545]
在一个快速开始的[测试代码](https://github.com/alibaba/easyexcel/blob/master/easyexcel-test/src/test/java/com/alibaba/easyexcel/test/demo/web/UploadDataListener.java)中  ，在上传监听器里有这样一段描述

> 有个很重要的点 DemoDataListener 不能被spring管理，要每次读取excel都要new,然后里面用到spring可以构造方法传进去

不知道，为什么不能被spring管理。线程安全问题吗？每个请求创建一个实例呢？在spring以外通过new的方式创建对象，总感觉有点不得劲。
#--------------------------------------------------------------
update:
[常见读问题](https://easyexcel.opensource.alibaba.com/qa/read)看到这的解释是并发问题。但是应该可以通过`Scope`来解决。
#--------------------------------------------------------------
```
@Slf4j
@Component
@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
public class UploadDataListener implements ReadListener<UploadData> {
```
我在自己的代码中测试是能够被管理的，但是在`doAfterAllAnalysed`方法中需要将`cachedDataList `进行初始化，在异常不清理情况下有可能会读到上一次请示的数据。
```
/**
     * 所有数据解析完成了 都会来调用
     *
     * @param context
     */
    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
        // 这里也要保存数据，确保最后遗留的数据也存储到数据库
        saveData();

       // add this code
       // 存储完成清理 list
        cachedDataList = ListUtils.newArrayListWithExpectedSize(BATCH_COUNT);

        log.info("所有数据解析完成！");
    }
```

同时重写`onException`方法。当出现异常情况时让全局异常捕获，同时初始化`cachedDataList `
```
@Override
    public void onException(Exception exception, AnalysisContext context) throws Exception {
        cachedDataList = ListUtils.newArrayListWithExpectedSize(BATCH_COUNT);
        ReadListener.super.onException(exception, context);
    }
```

**Comment by zhuangjiaju** [comment]
除非 你的service 也是设置成多例 ， 不然service 单例里面的对象不管单例多例，都是单例。
