### ISSUE TITLE
读取excel怎么获取下拉框所有的值

### ISSUE THREAD

**Issue by 120003808** [alibaba/easyexcel#2546]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
这个目前不支持
