### ISSUE TITLE
easyExcel是否支持对象的嵌套

### ISSUE THREAD

**Issue by 1874cc** [alibaba/easyexcel#2547]
日常开发中VO会有许多嵌套对象（一对一）跟列表（一对多），直接模板{}里写子对象的属性，没效果，看了官方文档也没提到这个问题。
![image](https://user-images.githubusercontent.com/48994744/173972034-13158b23-334a-4fc9-9d46-9792512bbefd.png)
例如这个，{company}可以填充，但是{info.address}就无效果
代码中是直接传一个vo进去的

**Comment by zhuangjiaju** [comment]
这个目前不支持 后续可能会规划

**Comment by NickFzzy** [comment]
大佬，目前这个支持嵌对象的是支持了没？

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。

**Comment by windhc** [comment]
可以先支持一对一的嵌套对象

**Comment by yozurukt** [comment]
请问这个特性支持了吗？
