### ISSUE TITLE
单元测试中有一些测试用例所使用的文件为本地写死文件

### ISSUE THREAD

**Issue by zhaoqiang1024** [alibaba/easyexcel#2553]
ParameterDataTest类中：
file07 = TestFileUtil.createNewFile("parameter07.xlsx");        //测试excel不存在
fileCsv = TestFileUtil.createNewFile("parameterCsv.csv");   //测试excel不存在
Lock2Test类中：
List<Object> list = EasyExcel.read("/Users/zhuangjiaju/test/test3.xlsx")   //测试excel不存在
File file = new File("/Users/zhuangjiaju/IdeaProjects/easyexcel/src/test/resources/converter/converter07.xlsx");  写死本地路径
File file = TestFileUtil.readUserHomeFile("test/test6.xlsx");  //测试excel不存在
String fileName = "D:\\test\\珠海 (1).xlsx";  //写死本地路径excel不存在
File file = new File("D:\\test\\converter03.xls");  //写死本地路径excel不存在

以上不存在的excel在进行本地覆盖度测试时无法正常进行

**Comment by zhuangjiaju** [comment]
覆盖测试 只跑 core 里面的
