### ISSUE TITLE
填充模板时，动态竖列头部使用forceNewRow后前面的数据被后面的覆盖，没有成功添加行数

### ISSUE THREAD

**Issue by 592468495** [alibaba/easyexcel#2556]
就是在第二层的时候感觉forceNewRow没有生效，请问这个问题有吗
代码
<img width="739" alt="image" src="https://user-images.githubusercontent.com/39726178/174544425-f9d84843-f0a9-4aef-b0ac-6a98e1508cf4.png">

我的模板是这样的
<img width="497" alt="image" src="https://user-images.githubusercontent.com/39726178/174542756-22eb70a9-ab4f-4d35-a8b1-ed9aba63043c.png">

预期是这样
<img width="205" alt="image" src="https://user-images.githubusercontent.com/39726178/174544370-80c8f1a2-2101-4163-9742-088efa5bfd25.png">

最后结果是这样
<img width="593" alt="image" src="https://user-images.githubusercontent.com/39726178/174544305-2bb90138-1329-4a8f-9a92-4c3cde0cd0df.png">

**Comment by yequanzhuo** [comment]
are you solve a problem?

**Comment by 592468495** [comment]
> are you solve a problem?

没有正面解决这个问题，最后是把标题跳冲到list往下，最后动态合并

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
