### ISSUE TITLE
从2.1.6升级到3.1.1后，读到的日期格式变了

### ISSUE THREAD

**Issue by YSMull** [alibaba/easyexcel#2558]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**建议描述**
目前只支持注解方式，动态读取的情况下，无法指定日期格式。

**Comment by zhuangjiaju** [comment]
自定义转换器

**Comment by YSMull** [comment]
> 自定义转换器


自定义转换器只支持读取固定格式的excel，在class 的字段上加日期格式的注解。
