### ISSUE TITLE
Cannot invoke "com.alibaba.excel.read.metadata.holder.xls.XlsReadSheetHolder.setRowIndex(java.lang.Integer)" because "xlsReadSheetHolder" is null

### ISSUE THREAD

**Issue by oswardlx** [alibaba/easyexcel#2561]
**异常代码**
```public class DummyRecordHandler extends AbstractXlsRecordHandler implements IgnorableXlsRecordHandler {
    @Override
    public void processRecord(XlsReadContext xlsReadContext, Record record) {
        XlsReadSheetHolder xlsReadSheetHolder = xlsReadContext.xlsReadSheetHolder();
        if (record instanceof LastCellOfRowDummyRecord) {
            // End of this row
            LastCellOfRowDummyRecord lcrdr = (LastCellOfRowDummyRecord)record;
            xlsReadSheetHolder.setRowIndex(lcrdr.getRow());//!!!!!!!!!!!!!!!!!!!!!!!!!!!here!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            xlsReadContext.readRowHolder(new ReadRowHolder(lcrdr.getRow(), xlsReadSheetHolder.getTempRowType(),
                xlsReadContext.readSheetHolder().getGlobalConfiguration(), xlsReadSheetHolder.getCellMap()));
            xlsReadContext.analysisEventProcessor().endRow(xlsReadContext);
            xlsReadSheetHolder.setCellMap(new LinkedHashMap<Integer, Cell>());
            xlsReadSheetHolder.setTempRowType(RowTypeEnum.EMPTY);
        } else if (record instanceof MissingCellDummyRecord) {
            MissingCellDummyRecord mcdr = (MissingCellDummyRecord)record;
            xlsReadSheetHolder.getCellMap().put(mcdr.getColumn(),
                ReadCellData.newEmptyInstance(mcdr.getRow(), mcdr.getColumn()));
        }
    }
}
**异常提示**
java.lang.NullPointerException: Cannot invoke "com.alibaba.excel.read.metadata.holder.xls.XlsReadSheetHolder.setRowIndex(java.lang.Integer)" because "xlsReadSheetHolder" is null
	at com.alibaba.excel.analysis.v03.handlers.DummyRecordHandler.processRecord(DummyRecordHandler.java:29)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processRecord(XlsSaxAnalyser.java:158)
	at org.apache.poi.hssf.eventusermodel.MissingRecordAwareHSSFListener.processRecord(MissingRecordAwareHSSFListener.java:156)
	at org.apache.poi.hssf.eventusermodel.FormatTrackingHSSFListener.processRecord(FormatTrackingHSSFListener.java:92)
	at org.apache.poi.hssf.eventusermodel.HSSFRequest.processRecord(HSSFRequest.java:106)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.genericProcessEvents(HSSFEventFactory.java:172)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processEvents(HSSFEventFactory.java:129)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:80)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:53)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.execute(XlsSaxAnalyser.java:137)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:123)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:67)
	............
java.lang.RuntimeException: Cannot invoke "com.alibaba.excel.read.metadata.holder.xls.XlsReadSheetHolder.setRowIndex(java.lang.Integer)" because "xlsReadSheetHolder" is null
.............
   这里写你的代码
```  
    protected void readSheetList(ExcelReader excelReader, AbstractExcelCommonListener listener) {
        List<ReadSheet> readSheetList = new ArrayList<>();
        for (int x = 0; x < listener.getSheetSize(); x++) {
            ReadSheet readSheet = EasyExcel.readSheet(x).build();
            readSheetList.add(readSheet);
        }
        excelReader.read(readSheetList);
    }
**建议描述**
其他xls正常这个excel会出现这个问题
https://github.com/oswardlx/temp/blob/main/CmsAtWKwOrWAO91JALYyAL2JPWk771.xls

**Comment by gongxuanzhang** [comment]
贴完整代码，没法复现

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue

**Comment by heguyuan** [comment]
出现同样的问题  使用readAll() 方法会这样 
`package com.linuo.common.utils.easyexcel;

import com.alibaba.excel.context.AnalysisContext;
import com.alibaba.excel.event.AnalysisEventListener;
import com.linuo.common.core.domain.GenTableColumn;
import com.linuo.common.exception.ServiceException;
import com.linuo.common.json.JsonMap;
import lombok.extern.slf4j.Slf4j;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;

/**
 * EasyExcel消费监听.
 * @author www@yiynx.cn
 */
@Slf4j
public class EasyExcelGenTableDynamicConsumerListener extends AnalysisEventListener<Map<Integer, String>> {
    private final int pageSize;
    private final List<JsonMap> list;

    private final List<GenTableColumn> tbColumns;
    private Map<Integer, GenTableColumn> colMap;
    private final Consumer<List<JsonMap>> consumer;

    private final String firstHeadCellVal;
    private final int maxFirstHeadIndex = 100;


    public EasyExcelGenTableDynamicConsumerListener(int pageSize, String firstHeadCellVal, List<GenTableColumn> tbColumns, Consumer<List<JsonMap>> consumer) {
        this.pageSize = pageSize;
        this.firstHeadCellVal = firstHeadCellVal;
        this.tbColumns = tbColumns;
        this.consumer = consumer;
        list = new ArrayList<>(pageSize);
    }

    public static EasyExcelGenTableDynamicConsumerListener of(int pageSize, String firstHeadCellVal, List<GenTableColumn> tbColumns, Consumer<List<JsonMap>> consumer){
        return new EasyExcelGenTableDynamicConsumerListener(pageSize, firstHeadCellVal, tbColumns, consumer);
    }

    @Override
    public void invoke(Map<Integer, String> data, AnalysisContext context) {
        if (this.colMap == null){
            Integer rowIndex = context.readRowHolder().getRowIndex();
            if (rowIndex > maxFirstHeadIndex){
                throw ServiceException.of("没有找到对应标题行");
            }
            if (firstHeadCellVal.equals(data.get(0))){
                this.colMap = EasyExcelApi.tranColMap(this.tbColumns, data);
            }
            return;
        }


        JsonMap jsonMap = EasyExcelApi.tranJsonMap(this.colMap, data);
        if (!jsonMap.isEmpty())
            list.add(jsonMap);
        if (list.size() >= pageSize) {
            consumer.accept(list);
            list.clear();
        }
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
        consumer.accept(list);
        list.clear();
        this.colMap = null;
    }

    @Override
    public void onException(Exception exception, AnalysisContext context) throws Exception {
        if (exception instanceof ServiceException){
            log.info(exception.getMessage());
            return;
        }
        if (exception instanceof RuntimeException){
            log.info(exception.getMessage());
            return;
        }
        throw exception;
    }

}
`
