### ISSUE TITLE
使用 @ExcelProperty注解是设置value为数组 ,在数组不完全相同的情况下,映射的字段会不对应

### ISSUE THREAD

**Issue by laobai202004** [alibaba/easyexcel#2570]
例如:
    @ExcelProperty(value = {"A状态", "状态表述"})
    private String typeA;
    @ExcelProperty(value = {"B状态", "状态表述"})
    private String typeB;

在导入数据时  ,若
    A状态 | B状态
状态表述 | 状态表述
       1      |                
时  该值会被映射到typeB上

**Comment by zhuangjiaju** [comment]
目前是根据最后一行 匹配的。

**Comment by P0Pooooooo** [comment]
@ExcelProperty(value = {"设备类型", "设备型号"})  为什么这种写法读不到值，
换成单列的就行@ExcelProperty("设备类型")
