### ISSUE TITLE
关于2.2.10版本获取Excel总行数的问题

### ISSUE THREAD

**Issue by kaciry0927** [alibaba/easyexcel#2571]
**context.readSheetHolder().getApproximateTotalRowNumber()**
这个方法在2.2.10版本中调用不太准确，
在数据被右键点击删除行时是正确返回的，但是将行数据使用Delete键删除时，返回的数据不会变化，比如现在有两行数据，第二行我选中后点击Delete删除，这个方法还是返回的2

`public class CountTagHandler extends AbstractXlsxTagHandler {

    @Override
    public void startElement(XlsxReadContext xlsxReadContext, String name, Attributes attributes) {
       // 这里会将被Delete的行数也返回
        String d = attributes.getValue(ExcelXmlConstants.ATTRIBUTE_REF);
        String totalStr = d.substring(d.indexOf(":") + 1, d.length());
        String c = totalStr.toUpperCase().replaceAll("[A-Z]", "");
        xlsxReadContext.readSheetHolder().setApproximateTotalRowNumber(Integer.parseInt(c));
    }

}`

**Comment by zhuangjiaju** [comment]
这个不建议使用
