### ISSUE TITLE
3.1.1版本读取xlsx文件报格式错误

### ISSUE THREAD

**Issue by w347wee123** [alibaba/easyexcel#2575]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**触发场景描述**
上传读取一个xlsx模板，代码如下
**触发Bug的代码**
```java
 EasyExcel.read(file.getInputStream(), TbConfigInfoExcelPojo.class, new TbConfigInfoListener(ecService)).excelType(ExcelTypeEnum.XLSX).sheet().doRead();
```
**提示的异常或者没有达到的效果**
最终执行会报错
![image](https://user-images.githubusercontent.com/32285833/177675312-dae19c26-2cc4-4c7d-98bc-07c254fa6379.png)
同样的代码和文件，我用xls是正常的

**Comment by tmlx1990** [comment]
您好 我刚测试了3.1.1版本，目前没有复现问题 demo 中的方法可以正常解析。
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/5753992/179782511-741a8441-f331-4604-b183-8e349b159ae7.png">

**Comment by zhuangjiaju** [comment]
版本兼容的问题: https://easyexcel.opensource.alibaba.com/qa/#%E5%87%BA%E7%8E%B0-nosuchmethodexception--classnotfoundexception-noclassdeffounderror%E7%AD%89%E5%BC%82%E5%B8%B8
