### ISSUE TITLE
2.1.6 web浏览器下载不支持直接传入ZipOutputStream

### ISSUE THREAD

**Issue by GaoShuCheng** [alibaba/easyexcel#2577]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
参照 文档：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#web%E4%B8%AD%E7%9A%84%E5%86%99
