### ISSUE TITLE
继承AbstractCellStyleStrategy控制单元格样式，导致导出效率下降

### ISSUE THREAD

**Issue by lin-cq** [alibaba/easyexcel#2578]
因为客户要求的excel样式问题，导致我们导出需要根据客户的需求进行定制。并且多个客户可能用到同一个导出，所以并不能准确的知道具体哪一列需要什么样的样式，因此，只能通过继承 AbstractCellStyleStrategy 类对特殊格式的单元格格式进行控制，让客户可以自定义某种样式，然后在AbstractCellStyleStrategy的子类中进行判断并设置单元格格式，这就导致数据量稍微大一点的时候，导出时间直接翻倍，分析应该是因为每个单元格都重新设置了格式而导致，请问有没有什么更好的解决办法。

**Comment by zhuangjiaju** [comment]
升级到3.1.1 版本了没？

**Comment by lin-cq** [comment]
没有升级，后来通过别的方式优化了，3.1.1提供了新的解决方案吗，回头我去看下，谢谢
