### ISSUE TITLE
excle填充图片时会报 Can not find 'Converter' support class byte[]

### ISSUE THREAD

**Issue by masuoxiaobao** [alibaba/easyexcel#2579]
版本是 3.1.1

//目标excle
 String fileName = "D:\\123-fill.xlsx";

//填充excle中  客户签名字段evaluatorSign   是一张图片
 ExcelWriter excelWriter = EasyExcel
          .write(fileName)
          .registerWriteHandler(new ImageCellWriteHandler(imageRowIndexs))
          .withTemplate(inputStream).build();

Map<String, Object> param = new HashMap<>();
//备注这里的evaluatorSign 是客户签名的一张图片   这里不做具体地址展示 使用XXX代替  getImageFromNetByUrl 返回的类型是byte[]
param.put("evaluatorSign", getImageFromNetByUrl("xx"));
excelWriter.fill(param, writeSheet);
excelWriter.finish();

![image](https://user-images.githubusercontent.com/87377692/178019644-9abb4ca8-3739-490b-b8d7-a3691904f481.png)
![image](https://user-images.githubusercontent.com/87377692/178020242-d3c219d4-cb2a-4ab1-ac0e-56e0ad966148.png)

这样一来就会报错 Can not find 'Converter' support class byte[]

**Comment by masuoxiaobao** [comment]
找不到对应的类型转换器 就会报错 Can not find 'Converter' support class byte[] ，实际上转换器Map中是有ByteArrayImageConverter这个类的

**Comment by yxh312154247** [comment]
请问解决了吗？

**Comment by masuoxiaobao** [comment]
你也遇到了嘛，解决了，在使用前我自定义了转换器



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yxh312154247 ***@***.***&gt;
发送时间: 2023年3月9日 11:49
收件人: alibaba/easyexcel ***@***.***&gt;
抄送: masuoxiaobao ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/easyexcel] excle填充图片时会报 Can not find 'Converter' support class byte[] (Issue #2579)





 
请问解决了吗？

**Comment by hinlokchan** [comment]
`WriteSheet signWriteSheet =
                EasyExcel.writerSheet()
                        .registerConverter(new ByteArrayImageConverter())
                        .build();`
I register a DEFAULT **ByteArrayImageConverter** manually,then it works.

**Comment by gongxuanzhang** [comment]
尝试使用3.3.1版本
如果仍有问题可以提供完整复现代码

**Comment by gang4107** [comment]
我用也遇到同样的问题，我用的版本是3.3.2，也换过之前的版本，依然不行
代码如下
![image](https://github.com/alibaba/easyexcel/assets/35129857/398f3b9d-d279-4807-abd6-d4409bb4a726)
![image](https://github.com/alibaba/easyexcel/assets/35129857/62ac1e9d-c148-4413-99a9-e36c533f6ad2)
报错信息
![image](https://github.com/alibaba/easyexcel/assets/35129857/3be56b6e-7147-4f31-8d89-029bcd5a162c)
明明存在byte[]对应的转换器，为什么会匹配不到呢？
![image](https://github.com/alibaba/easyexcel/assets/35129857/1822bb1f-a395-4a08-9136-2c52d01c0b1a)

上面说的各位说自定义转换器的方法，我也试了，还是一样的报错信息

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
