### ISSUE TITLE
write1方法的参数List<List<Object>> data需要传什么？

### ISSUE THREAD

**Issue by 1850597152** [alibaba/easyexcel#258]
List<User> list = userService.selectByExample(new UserExample());

        List<List<Object>> lists = new ArrayList<>();

         lists.add(list);
我这里 add报错了（不能转为object）

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
