### ISSUE TITLE
针对最新版的POI 5.x，这句话是否依然成立？

### ISSUE THREAD

**Issue by WestFarmer** [alibaba/easyexcel#2582]
针对最新版的POI 5.x，这句话是否依然成立？
> 一个3M的excel用POI sax解析依然需要100M左右内存

**Comment by linghengqian** [comment]
If you feel that this sentence is not valid, you need to point to or write a unit test of JMH.

**Comment by zhuangjiaju** [comment]
解析 没有用poi
