### ISSUE TITLE
读取公式和单元格类型使用的CellData目前是获取不到对应单元格的坐标信息，建议是否可以添加对应的坐标信息

### ISSUE THREAD

**Issue by lililixuefei** [alibaba/easyexcel#2584]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**建议描述**
读取公式和单元格类型使用的CellData目前是获取不到对应单元格的坐标信息，建议是否可以添加对应的坐标信息

**Comment by zhuangjiaju** [comment]
升级到 3.1.1 版本 有几个支持
