### ISSUE TITLE
自定义多种样式导出，字体加租无效

### ISSUE THREAD

**Issue by rstyro** [alibaba/easyexcel#2588]
**BUG 过程**
- 在 `com.alibaba.easyexcel.test.demo.write.WriteTest` 下的 `writeCellDataWrite()` 这个示例方法中，代码片段如下：
```Java
       // 前2个字红色
        WriteFont writeFont = new WriteFont();
        writeFont.setColor(IndexedColors.RED.getIndex());
        // 这个加粗无效，是本身就不能这样用，还是算是一个bug
        writeFont.setBold(true);
        richTextStringData.applyFont(0, 2, writeFont);
```
- 我运行，导出的时候，红色 的内容还是没有加粗

**Comment by tmlx1990** [comment]
> **BUG 过程**
> 
> * 在 `com.alibaba.easyexcel.test.demo.write.WriteTest` 下的 `writeCellDataWrite()` 这个示例方法中，代码片段如下：
> 
> ```java
>        // 前2个字红色
>         WriteFont writeFont = new WriteFont();
>         writeFont.setColor(IndexedColors.RED.getIndex());
>         // 这个加粗无效，是本身就不能这样用，还是算是一个bug
>         writeFont.setBold(true);
>         richTextStringData.applyFont(0, 2, writeFont);
> ```
> 
> * 我运行，导出的时候，红色 的内容还是没有加粗

您好 请问您用的什么版本？我刚测试了最新版本是可以的  红色会被加粗

**Comment by tmlx1990** [comment]
<img width="118" alt="image" src="https://user-images.githubusercontent.com/5753992/179477300-8ee421e3-9645-4b5c-ac79-f11131994798.png">

**Comment by rstyro** [comment]
我使用的是 3.1.0 版本的，我试一下最新版本的看看

**Comment by tmlx1990** [comment]
你换下别用wps打开试试呢 我就是和你一样的代码 是可以的

**Comment by rstyro** [comment]
可以，window自带的excel可以加粗

**Comment by zhuangjiaju** [comment]
实际测试没问题 参照连接：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E8%B6%85%E9%93%BE%E6%8E%A5%E5%A4%87%E6%B3%A8%E5%85%AC%E5%BC%8F%E6%8C%87%E5%AE%9A%E5%8D%95%E4%B8%AA%E5%8D%95%E5%85%83%E6%A0%BC%E7%9A%84%E6%A0%B7%E5%BC%8F%E5%8D%95%E4%B8%AA%E5%8D%95%E5%85%83%E6%A0%BC%E5%A4%9A%E7%A7%8D%E6%A0%B7%E5%BC%8F

是不是没有用最新版的wps
