### ISSUE TITLE
springboot使用jar包部署后，下载的excel文件打不开，求解

### ISSUE THREAD

**Issue by JaloDeng** [alibaba/easyexcel#2590]
response.getOutputStream()下载文件content-length为0
![image](https://user-images.githubusercontent.com/20082952/179162834-341959f9-5b15-4bb8-97d6-e132b85ea3d2.png)

**Comment by MattVanArths** [comment]
这一般是后台有bug报错了

**Comment by zhuangjiaju** [comment]
参照：https://easyexcel.opensource.alibaba.com/qa/write#%E5%AF%BC%E5%87%BA%E7%9A%84excel%E6%89%93%E4%B8%8D%E5%BC%80
