### ISSUE TITLE
请问xls的事件模式如何获取图片

### ISSUE THREAD

**Issue by huangrenxi** [alibaba/easyexcel#2594]
![image](https://user-images.githubusercontent.com/10829700/179381860-32984584-b642-4062-af88-e3cd36afb24a.png)
![image](https://user-images.githubusercontent.com/10829700/179381791-2af70dcc-8d76-48b9-b76d-42e3d7ce8c84.png)
我通过删减图片测试出来，这个应该就是图片的记录，但是如果直接getRecordData得到的字节码输出到文件实际上不是图片来的，这块你比较有经验，所以想请问一下你知道怎么处理吗，谢谢！

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
