### ISSUE TITLE
单元格包含换行没法读取成功

### ISSUE THREAD

**Issue by haoge1942** [alibaba/easyexcel#26]

**Comment by jipengfei-jpf** [comment]
由于1.0.*版本核心考虑的是怎么解决读excel内存溢出问题，自己重写了读excel的POI的底层，写仍旧使用POI。可以从根本解决OOM问题。但是由于自己对excel的格式认识不全面，有很多坑产生了很多BUG。最新版本以POI为底层。最新版：1.1.2-beat1，虽然不能完全解决OOM但可以解决大部分的OOM问题，完全解决OOM版本会等稳定后再开放，敬请理解。目前稳定版本1.1.2-beat1
