### ISSUE TITLE
No valid entries or contents found, this is not a valid OOXML (Office Open XML) file

### ISSUE THREAD

**Issue by 2021404** [alibaba/easyexcel#2600]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**触发场景描述**
easyexcel 3.0.4版本：
**触发Bug的代码**
```java
   InputStream inputStream = new ClassPathResource("template/export_template.xlsx").getInputStream();
    XSSFWorkbook  workbook = new XSSFWorkbook(inputStream);
```
**提示的异常或者没有达到的效果**
org.apache.poi.openxml4j.exceptions.NotOfficeXmlFileException: No valid entries or contents found, this is not a valid OOXML (Office Open XML) file
	at org.apache.poi.openxml4j.util.ZipArchiveThresholdInputStream.getNextEntry(ZipArchiveThresholdInputStream.java:145)
	at org.apache.poi.openxml4j.util.ZipInputStreamZipEntrySource.<init>(ZipInputStreamZipEntrySource.java:49)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:106)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:307)
	at org.apache.poi.ooxml.util.PackageHelper.open(PackageHelper.java:47)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:309)

**Comment by Nobodylesszb** [comment]
你好，请问解决了吗。

**Comment by 2021404** [comment]
我之前的问题是 excel文件有问题导致发自我的iPhone------------------ Original ------------------From: 张博  ***@***.***>Date: Thu,Jul 28,2022 10:03 AMTo: alibaba/easyexcel ***@***.***>Cc: 2021404 ***@***.***>, Author ***@***.***>Subject: Re: [alibaba/easyexcel] No valid entries or contents found, this isnot a valid OOXML (Office Open XML) file (Issue #2600)
你好，请问解决了吗。

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/alibaba/easyexcel/issues/2600#issuecomment-1197565791",
"url": "https://github.com/alibaba/easyexcel/issues/2600#issuecomment-1197565791",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zhuangjiaju** [comment]
看下是不是没有读取到excel文件

**Comment by Nobodylesszb** [comment]
你好，解决了，问题是压缩后的excel文件格式报错了
