### ISSUE TITLE
写csv文件用excel2013打开中文乱码

### ISSUE THREAD

**Issue by liweiye-2021** [alibaba/easyexcel#2609]
代码如下：

 EasyExcelFactory.write(filePath + fileName).charset(Charset.forName("UTF-8")).excelType(ExcelTypeEnum.CSV).head(getHeader(mapList)).automaticMergeHead(false)
                        .sheet(fileName).doWrite(generateGzData(listMap));

doWrite里面的数据集合是中文的

**Comment by liweiye-2021** [comment]
设置GBK编码就没问题了，刚刚尝试

**Comment by linghengqian** [comment]
- This is apparently due to a configuration issue with Microsoft Excel in your Windows environment. 

- Commercial software should not be the focus of this project, and I recommend closing this issue.

**Comment by liweiye-2021** [comment]
close
