### ISSUE TITLE
关于读excel 单元格内容格式为=”xxx“时值为null 的问题

### ISSUE THREAD

**Issue by arjiangHe** [alibaba/easyexcel#261]
03版excel  xls格式下，当单元格内容为=”xxx“的时候 读取出来的值为null,
07版 xlxs 是正常的

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
