### ISSUE TITLE
类上使用lombok的@Accessors(chain = true) 注解则无法按照给定bean进行解析

### ISSUE THREAD

**Issue by greyfooswong** [alibaba/easyexcel#2610]
List<PO> list = new ArrayList();
EasyExcel.read(inputStream, PO.class,new PageReadListener<PO>(list::addAll)).sheet(0).doRead();

list中所有数据均为空，但能正确获取excel文件中的行对应的数量。

**Comment by JavaLionLi** [comment]
这个东西违规范 不支持也是正常的

**Comment by zhuangjiaju** [comment]
这个目前不支持
