### ISSUE TITLE
**请问入qq群的验证码是什么**

### ISSUE THREAD

**Issue by WyzelWong** [alibaba/easyexcel#2614]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by WyzelWong** [comment]
问题已解决

**Comment by linghengqian** [comment]
This issue should be closed and marked as invalid.
