### ISSUE TITLE
Fill填充方式，多sheet页对应填充不同模板

### ISSUE THREAD

**Issue by sasuke1199** [alibaba/easyexcel#2617]
目前ExcelWriter只能支持单模板。多sheet页对应单模板比较方便，但是项目中可能需要不同sheet页输出不同的模板样式。这边我在尝试开发。请问项目有这种规划吗？期待沟通

**Comment by zhuangjiaju** [comment]
这个目前已经支持的。不支持的是一个模板 复制到多个sheet

**Comment by sasuke1199** [comment]
多sheet页使用一个模板是支持的。创建ExcelWriter的时候inMemory(true)，即使用XSSFWorkBook，可以clone初始化的第一个sheet页。后续的sheet页就可以共享同一个模板。但是默认的SXXFWorkBook也不方便。因为它禁用了clone方法

發自我的iPhone


------------------ 原始邮件 ------------------
寄件人： Jiaju Zhuang ***@***.***&gt;
发送时间: 2022年8月2日 20:45
收件人： alibaba/easyexcel ***@***.***&gt;
抄送: sasuke1199 ***@***.***&gt;, Author ***@***.***&gt;
主旨： Re: [alibaba/easyexcel] Fill填充方式，多sheet页对应填充不同模板 (Issue #2617)





 
这个目前已经支持的。不支持的是一个模板 复制到多个sheet
