### ISSUE TITLE
关于不能设置单元格格式问题

### ISSUE THREAD

**Issue by morewindows0** [alibaba/easyexcel#262]
由于不能设置单元格格式，导致长数字在excel中会变成科学计数

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。使用自定义转换器或者使用`NumberFormat`注解
