### ISSUE TITLE
属性大小写会影响数据获取吗？数据丢失

### ISSUE THREAD

**Issue by AxinGitHub** [alibaba/easyexcel#2627]
`try {
                response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                response.setCharacterEncoding("utf-8");
                // 这里URLEncoder.encode可以防止中文乱码 当然和easyexcel没有关系
                String fileName = URLEncoder.encode("导出离线数据", "UTF-8").replaceAll("\\+", "%20");
                response.setHeader("Content-disposition", "attachment;filename*=utf-8''" + fileName + ".xlsx");
                // 这里需要设置不关闭流
                EasyExcel.write(response.getOutputStream(), TicketOff.class).autoCloseStream(Boolean.FALSE).sheet("sheet").doWrite(pagelist.getList());
            } catch (Exception e) {
                e.printStackTrace();
                throw new RuntimeException("下载报表异常");
            }`

![image](https://user-images.githubusercontent.com/17761813/182833199-d2d2cb03-a163-4efc-9648-ba1f42ab15b1.png)
![image](https://user-images.githubusercontent.com/17761813/182833243-bc4fc327-9898-4e95-bfdb-1065ea247718.png)

![image](https://user-images.githubusercontent.com/17761813/182833281-22122467-b6fd-4200-b3e0-1227710e16da.png)

**Comment by juzi214032** [comment]
变量名不会影响数据写入，有可复现demo吗？

**Comment by AxinGitHub** [comment]
下载地址：https://tutuwp.lanzouj.com/iiM6A096ueoj
运行后，访问地址；http://localhost:9991/domo/api/downloadFailedUsingJson

**Comment by juzi214032** [comment]
参考该issue：https://github.com/alibaba/easyexcel/issues/1467
这个bug后续我会考虑提个pr修复一下

**Comment by cheng6563** [comment]
@juzi214032 
3.1.1并没有解决，现在只要属性名为类似`aName`，用IDEA自带的Getter Setter生成，依然无法导出数据。

**Comment by zhuangjiaju** [comment]
建议改成驼峰形式。
aName 这个get  set 有争议 ，你可以试下lombok 和  idea生成的 get set 方法不一样，我们采用了lombok的

**Comment by Wangyisimida** [comment]
ok, got it
