### ISSUE TITLE
如何设置导出文件表头为红色，取消默认设置的灰色

### ISSUE THREAD

**Issue by moshengkang** [alibaba/easyexcel#2630]

**Comment by juzi214032** [comment]
导出bean上添加注解
```java
@HeadStyle(fillPatternType = FillPatternTypeEnum.SOLID_FOREGROUND, fillForegroundColor = 10)
```

参考文档：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E6%B3%A8%E8%A7%A3%E5%BD%A2%E5%BC%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
