### ISSUE TITLE
Excel中特殊单元格格式读取问题

### ISSUE THREAD

**Issue by hermeslch** [alibaba/easyexcel#2634]
在 #2343 中出现的特殊单元格格式读取问题仍然尚未解决，测试文件见附件
[测试文件.xls](https://github.com/alibaba/easyexcel/files/9291018/default.xls)
原有链接为https://github.com/alibaba/easyexcel/issues/2343

**Comment by juzi214032** [comment]
useDefaultListener 把该属性设置为 false，可以在 invoke 里面取得最原始的 ReadCellData，调 getNumberValue() 就能获取原始数值
