### ISSUE TITLE
读取excel列，无法按照指定标识去解析到固定实体对象属性中

### ISSUE THREAD

**Issue by Lsatin** [alibaba/easyexcel#2636]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**建议描述**

**Comment by juzi214032** [comment]
什么意思 没太明白 能详细说明一下么

**Comment by Lsatin** [comment]
比如：
-------------------------
excel
------------------------|
    A  |   B   |   C   |  D
------------------------|
 姓名| 性别 |     |  年龄
------------------------|
小明 |  男   |     |   18   
------------------------|

JavaBean
-------------------------
@ExcelPropertie(value="年龄")
private String name;

@ExcelPropertie(value="性别")
private String sex;

@ExcelPropertie(value="姓名")
private String age;
-----------------------------------------

读取的数据为：{name: "小明", sex:"男", age: "18"}
理想：{name: "18", sex:"男", age: "小明"}
最好能拓展个接口，让定义表头与实体间的属性绑定

**Comment by weirhp** [comment]
和我的问题有点像。未能正确按首行的列头，填充实体。十几个字段只有一个字段没有正确填充。

**Comment by juzi214032** [comment]
默认是按字段顺序填充的，可以直接调整字段顺序，或者指定 index 就可以绑定到具体某一列 @Lsatin

**Comment by Lsatin** [comment]
> 和我的问题有点像。未能正确按首行的列头，填充实体。十几个字段只有一个字段没有正确填充。

那是，因为，他在反射的时候，把实体的field给排序了。但是，不能按照列头去读取到固定的field

**Comment by Lsatin** [comment]
> 默认是按字段顺序填充的，可以直接调整字段顺序，或者指定 index 就可以绑定到具体某一列 @Lsatin

所以，现在才提了这个需求，希望下个版本可以通过列头去匹配固定的字段

**Comment by zhuangjiaju** [comment]
你自己指定index  或者根据名字匹配，你应该是名字没匹配上
