### ISSUE TITLE
想提问一下如何在拦截器自定义RGB颜色

### ISSUE THREAD

**Issue by yyanxiong** [alibaba/easyexcel#2642]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
public void afterCellDispose(CellWriteHandlerContext context) {
  Cell cell = context.getCell();
  Workbook workbook = context.getWriteSheetHolder().getSheet().getWorkbook();
  XSSFCellStyle cStyle =(XSSFCellStyle) workbook.createCellStyle();
  cStyle.cloneStyleFrom(cell.getCellStyle());
  cStyle.setFillForegroundColor(new XSSFColor(new Color(255,192,203)));
  cStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
  cell.setCellStyle(cStyle);
}
**异常提示**
没生效
**建议描述**
因为项目需要用到自定义的颜色，但是我看文档的方法writeCellStyle.setFillForegroundColor();似乎只支持预设的颜色。想用poi的方法设置，但是似乎从workbook创建出来的CellStyle不能生效。想问问是操作问题，还是说有其他办法实现

**Comment by juzi214032** [comment]
这样写
```java
@Override
public void afterCellDispose(CellWriteHandlerContext context) {
    XSSFCellStyle cStyle = (XSSFCellStyle) context.getWriteWorkbookHolder().getWorkbook().createCellStyle();
    cStyle.setFillForegroundColor(new XSSFColor(new Color(255, 192, 203)));
    cStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
    context.getFirstCellData().setOriginCellStyle(cStyle);
}
```

**Comment by yyanxiong** [comment]
> 这样写
> 
> ```java
> @Override
> public void afterCellDispose(CellWriteHandlerContext context) {
>     XSSFCellStyle cStyle = (XSSFCellStyle) context.getWriteWorkbookHolder().getWorkbook().createCellStyle();
>     cStyle.setFillForegroundColor(new XSSFColor(new Color(255, 192, 203)));
>     cStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
>     context.getFirstCellData().setOriginCellStyle(cStyle);
> }
> ```

**Comment by yyanxiong** [comment]
> 这样写
> 
> ```java
> @Override
> public void afterCellDispose(CellWriteHandlerContext context) {
>     XSSFCellStyle cStyle = (XSSFCellStyle) context.getWriteWorkbookHolder().getWorkbook().createCellStyle();
>     cStyle.setFillForegroundColor(new XSSFColor(new Color(255, 192, 203)));
>     cStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
>     context.getFirstCellData().setOriginCellStyle(cStyle);
> }
> ```

可以了，原来有个set和get的OriginCellStyle的方法。。十分感谢！！
