### ISSUE TITLE
excel 设置多选框 如何设置？

### ISSUE THREAD

**Issue by jones0828** [alibaba/easyexcel#2645]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by gongxuanzhang** [comment]
参考POI，使用writeHandler 拦截器添加

**Comment by lpgggggg** [comment]
> 
只能实现下拉，无法实现多选
如果能，实现把示例加上，

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
