### ISSUE TITLE
java写到excel 中，String 格式 到 excel中如何是 数字类型，且有千分位格式化

### ISSUE THREAD

**Issue by bangzhu-simple** [alibaba/easyexcel#2646]
java 代码 
    @ExcelProperty(value = "预期到期收益")
    private String expectAmount;  // 假如是  123456789.12345

excel 中是 数字格式，且展示  123，456，789.12345

**Comment by chenzhongyu11** [comment]
> java 代码 @ExcelProperty(value = "预期到期收益") private String expectAmount; // 假如是 123456789.12345
> 
> excel 中是 数字格式，且展示 123，456，789.12345

https://blog.csdn.net/qq_34306010/article/details/126131887?spm=1001.2014.3001.5502 看我的这个！解决了这个问题

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
