### ISSUE TITLE
如何自定义 DataFormat

### ISSUE THREAD

**Issue by bangzhu-simple** [alibaba/easyexcel#2648]
"General",
        "0",
        "0.00",
        "#,##0",
        "#,##0.00",
        "\"$\"#,##0_);(\"$\"#,##0)",
        "\"$\"#,##0_);[Red](\"$\"#,##0)",
        "\"$\"#,##0.00_);(\"$\"#,##0.00)",
        "\"$\"#,##0.00_);[Red](\"$\"#,##0.00)",
        "0%",
        "0.00%",
        "0.00E+00",
        "# ?/?",

目前 dataformat 支持的类型 已经写死，请问 如何自定义 dataformat 比如  我想返回 的是 5位小数的百分比

**Comment by cdgjzzy** [comment]
实现 CellWriterHandler，重写 public void afterCellDispose(CellWriteHandlerContext context)
```
            WriteCellData<?> firstCellData = context.getFirstCellData();
            WriteCellStyle cellStyle = firstCellData.getOrCreateStyle();
            DataFormatData dataFormatData = new DataFormatData();
            dataFormatData.setFormat("#,##0.00000;[Red](#,##0.00000)");
            cellStyle.setDataFormatData(dataFormatData);
```

**Comment by zhuangjiaju** [comment]
最简单 就是 用 ContentStyle 注解

**Comment by JerryBai0106** [comment]
@zhuangjiaju 用这个方案可以的
