### ISSUE TITLE
list中两行为一组换行填充的实现方式

### ISSUE THREAD

**Issue by goodleo** [alibaba/easyexcel#2649]
您好，list循环两行为一组如何实现呢？
<img width="246" alt="image" src="https://user-images.githubusercontent.com/7307798/184857741-d3243e9c-fee3-4f2e-b21d-863c35717e37.png">

FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.TRUE).build();
这个方法只能插入一行

**Comment by goodleo** [comment]
help

**Comment by tokyohost** [comment]
相同的需求  help

**Comment by kongzhilong** [comment]
相同的需求，help

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
