### ISSUE TITLE
关于demo

### ISSUE THREAD

**Issue by a464989624** [alibaba/easyexcel#265]
根据demo写了writer.write(createTestListJavaMode(), sheet1)总是报空指针
java.lang.NullPointerException
	at com.alibaba.excel.write.ExcelBuilderImpl.addOneRowOfDataToExcel(ExcelBuilderImpl.java:111)
	at com.alibaba.excel.write.ExcelBuilderImpl.addOneRowOfDataToExcel(ExcelBuilderImpl.java:151)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:59)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:67)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:71)

**Comment by JiangSongBai** [comment]
我也有这个问题，跟了一下代码发现context里ExcelHeadProperty没有值，循环的时候就报空指针，好像没发现设置头的地方

**Comment by RandomSolitude** [comment]
我是demo可以正常main方法跑,但是在开发环境上就报这个空指针异常at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:664)
backmanage-sysout> 	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:685)
backmanage-sysout> 	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:92)
backmanage-sysout> 	at com.alibaba.excel.util.WorkBookUtil.createSheet(WorkBookUtil.java:51)
backmanage-sysout> 	at com.alibaba.excel.context.WriteContext.currentSheet(WriteContext.java:112)
backmanage-sysout> 	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:69)
backmanage-sysout> 	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:78)

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
