### ISSUE TITLE
AM/PM 日期获取的问题

### ISSUE THREAD

**Issue by eureka-smir** [alibaba/easyexcel#2654]
excel 的数据是10:42 PM
读取通过@DateTimeFormat("hh:mm:ss a")转换得到的结果是10:42:00 下午
用什么日期格式才能使得到的结果的“下午”中文是英文的PM？

**Comment by zhuangjiaju** [comment]
这个是simpledateformat的语法，参照：https://www.cnblogs.com/xuehuashanghe/p/9662391.html
