### ISSUE TITLE
Excel导出字体不支持

### ISSUE THREAD

**Issue by 2017wen** [alibaba/easyexcel#2658]
之前都是好好的，升级jdk以后就报字体问题。 

Error: java.lang.reflect.InvocationTargetException com.alibaba.excel.exception.ExcelGenerateException: java.lang.InternalError: java.lang.reflect.InvocationTargetException

java.lang.NullPointerException: null at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)

**Comment by IsZouTao** [comment]
JDK12就会出现这个问题，官网版本指出采用easyexcel2.2.7最高支持jdk11。

**Comment by zhuangjiaju** [comment]
参考这个:https://easyexcel.opensource.alibaba.com/qa/#%E6%88%91%E5%9C%A8%E6%9C%AC%E5%9C%B0%E5%8F%AF%E4%BB%A5%E5%8F%91%E5%B8%83%E5%88%B0%E7%BA%BF%E4%B8%8A%E7%8E%AF%E5%A2%83%E6%80%8E%E4%B9%88%E4%B8%8D%E5%8F%AF%E4%BB%A5%E4%BA%86
