### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by zerogcl** [alibaba/easyexcel#2659]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**建议描述**
大佬啊，有时间您整理整理文档吧，这个项目文档介绍的东西太少了

**Comment by chenzhongyu11** [comment]
我想整理！！

**Comment by zhuangjiaju** [comment]
> 

可以加群一起

**Comment by zhuangjiaju** [comment]
> 我想整理！！

可以加群一起

**Comment by zhuangjiaju** [comment]
这个后续会慢慢整理的
