### ISSUE TITLE
读取Excel的时候我没看到一次性读取全部sheet的方法

### ISSUE THREAD

**Issue by fengfst** [alibaba/easyexcel#266]
读取Excel的时候我没看到一次性读取全部sheet的方法,我想去一次性读取所有的excel的数据,这是个有时候我很需要的功能,希望加上,还有之前我也做过sax读取excel的程序,有时候有些数据格式我们需要尽量保持与原数据格式一样(比如时间格式,这种格式通常都会对应一个formatId类似的东西,一个id对应一种格式的日期),不清楚easyexcel,有没有这个东西,文档并不是很详细

**Comment by loooog** [comment]
读取所有sheet方法有的 reader.read()，我想找 通过sheet名称定位sheet的办法 😂

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。可以获取到所有sheet
