### ISSUE TITLE
为什么excel表中的列名与ExcelProperty注解中value值不一样，但index一样，还是能录入？

### ISSUE THREAD

**Issue by zhaochong-byte** [alibaba/easyexcel#2662]
我又两张表，一张表1的列名为防守队，行号为2，另一张表2的列名为攻击队，行号也为2，但是我可以用表1的模板录入表2的模板，也能用表2的模板录入表1的模板，
![image](https://user-images.githubusercontent.com/73687296/185589518-88e6a1d5-33d5-43af-bcbf-70946da41f9b.png)
![image](https://user-images.githubusercontent.com/73687296/185589553-114b4dc8-35ba-47f8-a621-0e96efee9725.png)

**Comment by zhaochong-byte** [comment]
easyExcel的版本号为2.1.6

**Comment by zhaochong-byte** [comment]
导入方法调用如下
![Uploading image.png…]()

**Comment by GSephrioth** [comment]
index 优先级高，导入时会忽略列value
