### ISSUE TITLE
excel按模板导出数据，其中填充对像中还有一个对象，怎样做数据绑定，例如对象 A中包含对象B，要用B对像的name

### ISSUE THREAD

**Issue by ruanll** [alibaba/easyexcel#2672]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
这个目前的解决方案 只能把对象拍平
