### ISSUE TITLE
大佬求教，使用map接收动态模板，遇到非标日期要怎么处理？

### ISSUE THREAD

**Issue by cd-cd7** [alibaba/easyexcel#2675]
最近由于功能迭代，客户要求支持动态模板导入数据，然后遇到了这个非标日期格式，使用Map接收解析的时候只能拿到时、分的数据，就是单元格看到的数据，没办法拿到年月日的数据。大佬们有没有遇到相同情况？这种是怎么处理的
![image](https://user-images.githubusercontent.com/111980946/186441813-9f9a044f-f712-4b9b-82f7-b690b2917c45.png)
![企业微信截图_1661159144249](https://user-images.githubusercontent.com/111980946/186441879-20b169da-31d7-4807-9cb9-8d7e727ade91.png)

**Comment by GSephrioth** [comment]
按字符串获取，自己写converter

**Comment by zhuangjiaju** [comment]
这个需要使用最新版本，然后设置 readDefaultReturn= ACTUAL_DATA  https://easyexcel.opensource.alibaba.com/docs/current/api/#readworkbook
