### ISSUE TITLE
如何将写入输出流的数据放入输入流？

### ISSUE THREAD

**Issue by qcwu** [alibaba/easyexcel#2677]
Easyexcel将数据写入HttpOutput，如何将HttpOutput流中的数据全部写入输入流呢？试过HttpOutput.sendContent(inputstream)，但是没有写入任何内容。请问有什么其他方法实现写入吗？
谢谢！

**Comment by zhuangjiaju** [comment]
1. 使用 `bytearrayoutputstream` 临时存储，然后再想办法，当然这个也比较占用内存。
2. 或者 存储成临时文件，这个需要考虑删除磁盘。
