### ISSUE TITLE
如何设置单元格对角线样式？

### ISSUE THREAD

**Issue by mulzhang** [alibaba/easyexcel#2678]
![image](https://user-images.githubusercontent.com/38064516/186821488-d8bcd39e-4f45-4b20-b5f7-f7ba32b3156c.png)

**Comment by gongxuanzhang** [comment]
参考自定义样式文档
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
然后需要用POI原生API设置对角线

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
