### ISSUE TITLE
3.1.1版本字符串整数导出会默认加上.0

### ISSUE THREAD

**Issue by Meko1995** [alibaba/easyexcel#2679]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**触发场景描述**
给每条数据加上序号，但是是字符串整数类型，比如”1“ ，导出到excel时就就变成了”1.0“；

我暂时换成了数字类型采用convert和@NumberFormat("#")来处理这个问题
**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by HillCheuang** [comment]
我也遇到了这个问题，若是double类型的0.00使用了@NumberForamt("#.##")导出excel后只会显示 **.**

**Comment by zhuangjiaju** [comment]
能否提供下代码？ 我测试了都没有加 你用的是什么类型？

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
