### ISSUE TITLE
事件驱动式解析excel的部分日期无法正确解析处理

### ISSUE THREAD

**Issue by sodinger** [alibaba/easyexcel#268]
事件驱动解析时无法把单个数据拿出来做额外处理，特别是日期数据，excel中的日期格式太多，目前没有好的解析方式吗？难道只能获取Cell再处理？这样的话对于大文件就容易出现OOM。求指导

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
