### ISSUE TITLE
可以通过OSS的流式下载，使用easyExcel，使用OSS上的文件吗？

### ISSUE THREAD

**Issue by hqgordon** [alibaba/easyexcel#2683]
想要通过流式下载，然后通过流处理文件，而不是完全下载后再处理。有人实现过，或者可行吗？目前在处于设计阶段并且我这边测试条件有限

**Comment by zhuangjiaju** [comment]
这个后续会提供一个完整的oss 案例。

**Comment by zhuangjiaju** [comment]
直接调用`com.aliyun.oss.OSSClient#getObject(com.aliyun.oss.model.GetObjectRequest)` 然后获取流即可，如果可以话尽量获取压缩过的图片，整个过程中图片都存储在内存，且无法优化。
