### ISSUE TITLE
如何设置动态合并单元格数量？

### ISSUE THREAD

**Issue by get-ao** [alibaba/easyexcel#2688]
如何设置动态合并单元格数量，
![image](https://user-images.githubusercontent.com/55133499/187406873-29969cd7-925a-408e-b57f-14845c4b6821.png)
这种改成动态传入单元格数量。

**Comment by zhuangjiaju** [comment]
参考：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E5%90%88%E5%B9%B6%E5%8D%95%E5%85%83%E6%A0%BC
