### ISSUE TITLE
xls 读取数据出现 数据异常

### ISSUE THREAD

**Issue by biexuxiaoyao** [alibaba/easyexcel#269]
当存在标题栏时候，easyexcel读取数据会多取出一行 值全部是 （TODO）的数据
作者的03xls
![image](https://user-images.githubusercontent.com/22730229/54655053-5a13bb00-4afb-11e9-982a-265ebfa28b7e.png)
我的 03xls
![image](https://user-images.githubusercontent.com/22730229/54655075-7152a880-4afb-11e9-930f-94b1c724dff0.png)
异常数据检出结果：
![image](https://user-images.githubusercontent.com/22730229/54655139-ae1e9f80-4afb-11e9-8172-8df95bda3490.png)

**Comment by zhuangjiaju** [comment]
这个尝试使用最新版本，如果还有问题。需要提供对应的xls
