### ISSUE TITLE
对easy excel生成的文件使用fill操作无效

### ISSUE THREAD

**Issue by PieceOfLuka** [alibaba/easyexcel#2692]
我需要生成一个动态的复杂表头的文件，如下图所示：
<img width="906" alt="image" src="https://user-images.githubusercontent.com/44961882/187770815-3a3bb99a-8135-43e5-a373-08745f91bdee.png">
Basic Information等字段需要合并展示，而第三行Planned End不需要合并展示。

由于自动表头合并开启的关系，Planned End会被自动合并，变为如下效果：
<img width="909" alt="image" src="https://user-images.githubusercontent.com/44961882/187772091-484a337b-a07e-451e-9040-0410bc899649.png">

目前我想到的解决方案是，在生成表头时，将Planned End字段加上一个字增id，作为占位符传入，这样可以生成一个模板文件，如下：
<img width="938" alt="image" src="https://user-images.githubusercontent.com/44961882/187772431-30d2631d-d565-48bd-aa88-455c19ab3074.png">

使用EasyExcel.write(outputStream).withTemplate(template).build().fill(handleMap, buildSheet)的方法，将上图中的占位符修改为正确的值。

实际操作过程中，发现模板可以正确生成，但是直接对该模板文件使用fill方法并不能将占位符替换为正确的“Planned End”（导出的文件中表头中的占位符没有替换成功，但是数据成功写入），而如果将该模板使用excel打开后点击save按钮（没有其他任何操作），即可使用这份模版正确的将占位符替换为“Planned End”并导出。

替换失败时并没有报错信息，请问这个问题有什么解决办法么？

以下为部分代码：
String path = "src/main/resources/tmp/" + fileName;
// 生成template
new File(path).createNewFile();
FileOutputStream fileOutputStream = new FileOutputStream(path);
EasyExcel.write(fileOutputStream).sheet("ProjectInfo").registerWriteHandler(ExportUtils.getStyleStrategy()).registerWriteHandler(new CustomCellWriteHandler()).head(headers).doWrite(new ArrayList<>());
fileOutputStream.flush();

// 占位符替换，写入数据
ClassPathResource classPathResource = new ClassPathResource("tmp/" + "Project List_1661973188146.xlsx");
ExcelWriter excelWriter = EasyExcel.write(outputStream).withTemplate(classPathResource.getInputStream()).build();
WriteSheet buildSheet = EasyExcel.writerSheet(0).build();
excelWriter.fill(handleMap, buildSheet); //失败
excelWriter.write(dataList, buildSheet); //成功
excelWriter.finish();

**Comment by PieceOfLuka** [comment]
使用版本为2.2.6

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
