### ISSUE TITLE
读取多个Sheet时和事务有关吗

### ISSUE THREAD

**Issue by philjing** [alibaba/easyexcel#2694]
2.7版本，读取两个sheet内容的数据，需要每行和数据库交互，交互方法是另外的service的方法。采用了自定义的Listener只是读取数据，读取方法上加事务注解，第一个sheet只有第一行和数据库交互了，别的全部没有，但是第二个sheet没任何问题。去掉了事务注解又全部正常了。

**Comment by changdy** [comment]
你应该关注下 两个sheet 的写操作 是怎么进行的..
easyexcel 都没有jdbc 依赖 怎么可能会和事务有关呢..

**Comment by philjing** [comment]
> 你应该关注下 两个sheet 的写操作 是怎么进行的..
> easyexcel 都没有jdbc 依赖 怎么可能会和事务有关呢..

按顺序逐行读取

**Comment by ftdmao** [comment]
> 你应该关注下 两个sheet 的写操作 是怎么进行的.. easyexcel 都没有jdbc 依赖 怎么可能会和事务有关呢..

请教一下，两个sheet的写操作，能一个用fill一个用write吗。我用各种姿势试了都不行，fill放后面就fill生效 write放后面就write生效

**Comment by zhuangjiaju** [comment]
这个需要自己去理解下事务的原理，easyexcel读取操作是同步的，在一个线程里面的。
