### ISSUE TITLE
日期格式问题

### ISSUE THREAD

**Issue by zhaoqf-cq** [alibaba/easyexcel#2696]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**触发场景描述**
场景：Excel 最普通的导入
背景：为了业务兼容多种格式的日期格式（如：yyyy/MM/dd, yyyy-mm-dd, yyyyMMdd），程序在 Listener 中使用工具类处理为统一格式，Listener 解析时 model 中 String 类型的日期解析为 yyyyMMdd--, 其中 excel 为日期 yyyy-mm-dd 格式， 内容为纯数字类型（如：20221010）

**触发Bug的代码**
```java
  // model
 @ExcelProperty("*日期（如:2022-10-10）")
 @NotBlank(message = "日期不能为空")
 @Size(min = 8, max = 10, message = "日期格式不正确, 格式样例: 2022-10-10")
 private String date;


  // impl
DemoListener demoListener = new DemoListener(bean);
EasyExcel.read(inputStream, DemoModel.class, demoListener).sheet().doRead();

// Listener 略
```
**提示的异常或者没有达到的效果**
异常： String 类型的 date 读取 Excel 中的日期尾多了2个“-”。如：excel 中日期为 20221010， model 中为 20221010--

**Comment by zhuangjiaju** [comment]
这个需要提供下excel

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue

**Comment by zhaoqf-cq** [comment]
> 这个需要提供下excel

抱歉，找到问题原因后，解决自家程序问题后就来反馈了，描述也不够清晰，文件当时忘记上传了

原使用版本为：2.2.4

现在升级最新版本，未能复现了

**Comment by zhaoqf-cq** [comment]
> 这个需要提供下excel

抱歉，找到问题原因后，解决自家程序问题后就来反馈了，描述也不够清晰，文件当时忘记上传了

原使用版本为：2.2.4

现在升级最新版本，未能复现了
