### ISSUE TITLE
国产机上用奇安信浏览器导出来的excel打开是乱码

### ISSUE THREAD

**Issue by wzy010** [alibaba/easyexcel#2698]
客户有的使用的是国产机，上面用奇安信浏览器导出来的excel表格是乱码格式，找了找issue中没有发现类似的问题，大佬知道如何解决吗？

**Comment by linghengqian** [comment]
- You need to provide a reproducible unit test.
- You need to confirm whether the encoding format of the corresponding Microsoft Office or other office software is UTF-8.
- If you cannot provide more information, this issue should be closed and marked as invalid.

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
