### ISSUE TITLE
web下载Excel抛异常NoClassDefFoundError

### ISSUE THREAD

**Issue by zhuhaojava** [alibaba/easyexcel#2699]
Junit可以执行，可以下载到java目录，web下载就会报错
执行sheet方法的时候，idea打断点出现的异常

e = {NoClassDefFoundError@5398} "java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.excel.write.ExcelBuilderImpl"
 detailMessage = "Could not initialize class com.alibaba.excel.write.ExcelBuilderImpl"
 cause = {NoClassDefFoundError@5398} "java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.excel.write.ExcelBuilderImpl"
 stackTrace = {StackTraceElement[41]@5408} 
 suppressedExceptions = {Collections$UnmodifiableRandomAccessList@5409}  size = 0

有大佬遇到过吗

**Comment by hao96** [comment]
我遇到过这个问题：是easyexcel与poi版本不匹配导致的。

**Comment by zhuangjiaju** [comment]
你和这个 需要看下加载器里面有没有这个类，应该是配置或者clean 下

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
