### ISSUE TITLE
ExcelWriter设置needHead为false时,文件第一行是空行

### ISSUE THREAD

**Issue by Silence-Shen** [alibaba/easyexcel#270]
尝试过
1.1.2-beta2,
1.1.2-beta4,
1.1.2-beta5
三个版本都是一样的问题

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
