### ISSUE TITLE
数据量大的时候一直报错can not close io

### ISSUE THREAD

**Issue by linliang1231** [alibaba/easyexcel#2700]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**建议描述**
easyexcle跟poi版本有问题啊  好几个版本 每次导出大数据量的时候就报错， easyexcel用的4.1.0. 后来把poi换成3.1.17就好了。

**Comment by zhuangjiaju** [comment]
看下提示的异常信息？

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
