### ISSUE TITLE
在使用对象导出时表头的字体不是标题字体，与动态生成表头字体样式不一致

### ISSUE THREAD

**Issue by niceuz1** [alibaba/easyexcel#2707]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   没有代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
没有特别理解 可以贴下代码&效果么？

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
