### ISSUE TITLE
从一个excel读取数据，添加若干列，写入到另一个excel，请问怎么实现？（excel大概有10W数据）

### ISSUE THREAD

**Issue by nuptkwz** [alibaba/easyexcel#2708]
从一个excel读取数据，添加若干列，写入到另一个excel，请问怎么实现？（excel大概有10W数据）
一次性读取的然后写入的话，会有10W数据加载到内存中，可能有OOM的风险。请问从一个excel到另一个excel的分批读写，该如何实现？

**Comment by zhuangjiaju** [comment]
可以尝试边读边写即可。

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
