### ISSUE TITLE
不创建对象的写，复杂头的写，该怎么搞呢？

### ISSUE THREAD

**Issue by 472332557** [alibaba/easyexcel#2712]
由于项目导出非常多，若使用注解方式导出，便需要创建一个对象类，那样对象类就太多了，想搞个通用的导出方法，看了下有一个不创建对象写的例子，感觉可以用的上，但是复杂头的写又不懂该怎么搞了，还请大佬指定下，感谢

**Comment by luguangdong** [comment]
![image](https://user-images.githubusercontent.com/41789844/189848433-6318d9fb-5451-4388-be8f-6c6cb29e5c51.png)

**Comment by luguangdong** [comment]
![image](https://user-images.githubusercontent.com/41789844/189848681-6a6062bc-9420-49f6-b254-9ce6fe67d7ab.png)

**Comment by 472332557** [comment]
万分感谢，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月13日(星期二) 下午4:16
***@***.***&gt;;
抄送:&nbsp;"No compromise no ***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 不创建对象的写，复杂头的写，该怎么搞呢？ (Issue #2712)

**Comment by Humphrey75432** [comment]
谢谢大佬，正好我也在找不创建对象写文件的栗子。终于找到了。
