### ISSUE TITLE
不创建对象（文件太多，没办法创建，想写一个工具类），如何将数据写入指定的列中，以及不创建对象形式的追加数据，求各位大佬告知

### ISSUE THREAD

**Issue by chen-bug** [alibaba/easyexcel#2716]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
![微信图片_20220913211911](https://user-images.githubusercontent.com/63845373/189912219-ca30a64b-0b16-480e-9938-9ee47dab7226.jpg)
![微信图片_20220913212134](https://user-images.githubusercontent.com/63845373/189912250-6ed7016d-7b14-4d61-9769-cb1ffc6c0649.jpg)

**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
和这个需要自己读取以后 然后再写入。
