### ISSUE TITLE
使用easyexcel读取单元格的数据不是真实值，比如123456789.85，而是123456789.9

### ISSUE THREAD

**Issue by depovase** [alibaba/easyexcel#2717]
再比如1.11，设置单元格格式为一位数字后，实际值是1.11，但读取出来是1.1，有没有办法读取到真实值呢？我使用的读文件方式为不创建对象的读。
![image](https://user-images.githubusercontent.com/29626583/190035776-a1d17f59-ff67-4308-9d16-042e2bee63e1.png)

**Comment by BookaiJin** [comment]
EasyExcel.read(byteArrayInputStream, new ReadListener<Map<Integer, ReadCellData<?>>>() {
            @Override
            public void invoke(Map<Integer, ReadCellData<?>> data, AnalysisContext context) {

                ReadCellData<?> data1 = data.get(0);
                Object value = 0;
                switch (data1.getType()) {
                    case STRING:
                        value = data1.getStringValue();
                        break;
                    case BOOLEAN:
                        value = data1.getBooleanValue();
                        break;
                    case NUMBER:
                        value = data1.getNumberValue();
                }
                System.out.println(value);
            }

            @Override
            public void doAfterAllAnalysed(AnalysisContext context) {

            }

            @Override
            public void invokeHead(Map<Integer, ReadCellData<?>> headMap, AnalysisContext context) {

                List<String> eachRowHead = new ArrayList<>();
                headMap.forEach((key, value) -> {
                    eachRowHead.add(value.getStringValue());
                    value.getType().getDeclaringClass();
                });
                head.add(context.readRowHolder().getRowIndex(), eachRowHead);
            }
        }).useDefaultListener(false).headRowNumber(1).sheet().doRead();

**Comment by BookaiJin** [comment]
看了下源码
你可以去看一下ExcelReaderBuilder#useDefaultListener这个方法
去掉默认监听，你的读取结果就可以换成public void invoke(Map<Integer, ReadCellData<?>> data, AnalysisContext context)
这样就可以从ReadCellData拿到实际值了

**Comment by zhuangjiaju** [comment]
这个问题已经在`3.2.0`中修复，建议升级到最新版本。
用`string` 会接收到你看到的数据。
用`BigDecimal`会接收到你点击单元格，输入框看到的数据。

**Comment by huixian98** [comment]
> 这个问题已经在`3.2.0`中修复，建议升级到最新版本。 用`string` 会接收到你看到的数据。 用`BigDecimal`会接收到你点击单元格，输入框看到的数据。

大佬您好，那我想请教另一个格式的问题，一直没找到解决方案。我如何获取时间格式的单元格的原始输入呢，现在遇到的困难是两种情况：
①输入框是2024/11/5 15：00：01，但是不点击单元格只能看到2024/11/5 15：00；因此转换成String的时候，只能读取到2024/11/5 15：00；
②输入2024，转换成Date的时候，是190几年的时间差，但我只想得到2024这个原始输入，包括即使输入2024/11/5 15：00：01，我也只想得到2024/11/5 15：00：01。
