### ISSUE TITLE
表头如何设置富文本

### ISSUE THREAD

**Issue by Bore-TuDou** [alibaba/easyexcel#2720]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
自定义拦截器 ，拦截到表头后参照：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8B%A6%E6%88%AA%E5%99%A8%E4%B8%8A%E9%9D%A2%E5%87%A0%E7%82%B9%E9%83%BD%E4%B8%8D%E7%AC%A6%E5%90%88%E4%BD%86%E6%98%AF%E8%A6%81%E5%AF%B9%E5%8D%95%E5%85%83%E6%A0%BC%E8%BF%9B%E8%A1%8C%E6%93%8D%E4%BD%9C%E7%9A%84%E5%8F%82%E7%85%A7%E8%BF%99%E4%B8%AA
