### ISSUE TITLE
长时间使用会产生大内存对象 DeleteOnExitHook

### ISSUE THREAD

**Issue by wwulfric** [alibaba/easyexcel#2725]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**建议描述**

FileUtil 使用的是 DefaultTempFileCreationStrategy

```java
    public static void createPoiFilesDirectory() {
        File poiFilesPathFile = new File(poiFilesPath);
        createDirectory(poiFilesPathFile);
        TempFile.setTempFileCreationStrategy(new DefaultTempFileCreationStrategy(poiFilesPathFile));
        poiFilesPathFile.deleteOnExit();
    }
```

但是 DefaultTempFileCreationStrategy 的删除策略是 deleteOnExit，对于服务端程序来说，可能会造成java.io.DeleteOnExitHook 大对象，而且无法 GC 掉

<img width="819" alt="image" src="https://user-images.githubusercontent.com/8315997/191412068-e6f73b0a-64ff-49f3-acee-53dbda950500.png">

TempFileCreationStrategy 的注释也表示：

DefaultTempFileCreationStrategy deletes temporary files when the JVM exits. This may not be suitable for long-running applications that never shut down the JVM since the list of registered files and disk space usage would grow for as long as the JVM is running. You may wish to implement your own strategy that meets the needs of your situation.

**Comment by wwulfric** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/8315997/191496365-5c01428e-77b7-49ec-8884-4240c6f8c876.png">

可以看出，每当执行Excel相关操作时，这里就会增加

**Comment by zhuangjiaju** [comment]
这个是个问题 已经在 `3.1.2`中修复

**Comment by wwulfric** [comment]
![image](https://user-images.githubusercontent.com/8315997/211508650-2a851c41-9c02-4b3e-bbdb-af39e553c96d.png)
已经升级到3.1.3. 看起来似乎还是会增长
![image](https://user-images.githubusercontent.com/8315997/211508751-c403f88f-743b-4449-bd14-6179a88f9b88.png)

`TempFile.setTempFileCreationStrategy(new DefaultTempFileCreationStrategy(poiFilesPathFile));`之后，是不是有可能其他地方也会deleteOnExit
