### ISSUE TITLE
填写导出excel在开发环境都正常，在生产环境导出会缺失数据

### ISSUE THREAD

**Issue by lixiangjuan** [alibaba/easyexcel#2726]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
缺失什么数据？需要提供代码&案例

**Comment by lixiangjuan** [comment]
谢谢，现在没有这个问题了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiaju ***@***.***&gt;; 
发送时间: 2023年2月8日(星期三) 下午3:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/easyexcel] 填写导出excel在开发环境都正常，在生产环境导出会缺失数据 (Issue #2726)





 
缺失什么数据？需要提供代码&amp;案例
