### ISSUE TITLE
excel中某一列可能有多种类型，如何统一映射为Java中的Object？

### ISSUE THREAD

**Issue by 12482** [alibaba/easyexcel#2727]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
class MyTriple{
   @ExcelProperty(value = "objectId")
    private Object objectId;
}
```
excel中objectId列的值可能有：
3.14
张三
TRUE
此时easyExcel无法统一映射到objectId上去，自定义converter好像也只能从1中类型映射到object，无法映射多种类型到object

**Comment by CNtame** [comment]
有方法吗？最近也有这需求。两种表头

**Comment by zhuangjiaju** [comment]
建议 直接用 string  去接受 然后自己再想办法，或者用 readcelldata
