### ISSUE TITLE
导出csv ，sheetName和文件名称一样（尝试版本3.0.5和3.1.1）

### ISSUE THREAD

**Issue by JJdog** [alibaba/easyexcel#2730]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   EasyExcelFactory.write(outputStream)
                . 
                .head()
                .excelType(type)
                .sheet(sheetName)
                .doWrite(list);
```
**异常提示**

指定了sheetName，但是导出成功后打开 显示的是和文件名称一样

**建议描述**

**Comment by zhuangjiaju** [comment]
csv 是没有sheet name概念的，所以没法设置。
