### ISSUE TITLE
单元格的背景色能添加RGB颜色吗，只能是自带的颜色吗

### ISSUE THREAD

**Issue by YeYuZhang** [alibaba/easyexcel#2733]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by gongxuanzhang** [comment]
可以设置 ,给你一段伪代码     Color你可以自定义
```
XSSFColor customColor = new XSSFColor(new java.awt.Color(128, 128, 128));
CellStyle style = workbook.createCellStyle();
style.setFillForegroundColor(customColor);
style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
Cell cell = row.createCell(0);
cell.setCellValue("Hello World");
cell.setCellStyle(style);
```

**Comment by YeYuZhang** [comment]
public void afterCellDispose(CellWriteHandlerContext context) {
    XSSFCellStyle cStyle = (XSSFCellStyle) context.getWriteWorkbookHolder().getWorkbook().createCellStyle();
    cStyle.setFillForegroundColor(new XSSFColor(new Color(255, 192, 203)));
    cStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
    context.getFirstCellData().setOriginCellStyle(cStyle);
}
这样是可以的  setOriginCellStyle  之前没看见这个方法啊

**Comment by gongxuanzhang** [comment]
解决了就好
