### ISSUE TITLE
简单的读操作，ap列读取不到；

### ISSUE THREAD

**Issue by 18159800059** [alibaba/easyexcel#2742]
![1664414885940](https://user-images.githubusercontent.com/40299993/192918073-21fa7ebe-43f6-4019-b276-73f88e4b17fa.jpg)
![lQLPJxa66XnGLc7NBBjNB4Cwfje75FckfvcDM02OL4AFAA_1920_1048](https://user-images.githubusercontent.com/40299993/192918087-9fcdb773-c0b1-4a49-b4d3-0ab2028884f4.png)

**Comment by zhuangjiaju** [comment]
可否提供下excel? 这个可能是excel 有关系

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
