### ISSUE TITLE
某个字段的类型是集合类型该怎么操作

### ISSUE THREAD

**Issue by OpBao** [alibaba/easyexcel#2744]
如果类中某个字段的类型是集合类型（集合中元素数量固定），导出时该怎么操作

**Comment by zhuangjiaju** [comment]
自定义转换器，参照：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E6%97%A5%E6%9C%9F%E6%95%B0%E5%AD%97%E6%88%96%E8%80%85%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%BC%E5%BC%8F%E8%BD%AC%E6%8D%A2
