### ISSUE TITLE
Excel流式写入

### ISSUE THREAD

**Issue by qldsrx** [alibaba/easyexcel#275]
看了下源码，这个excel的产生是在内存里构建好了对象模型后才最终一次性输出的。
现在问题来了，如果是超大数据（1亿条），如何可以不管格式的情况下，流式输出到excel文件，实现数据库中读取一条就往文件中写入一条，格式是预先定义好的，正式写入文件时不会更改。

**Comment by eoc2015** [comment]
同问

**Comment by zhuangjiaju** [comment]
首先数据最多100W。其次写入会放到磁盘缓存的。是N行一起写入的，不是整个文件一起。不会占用太多内存
