### ISSUE TITLE
源码里面这个类org.apache.poi.hssf.usermodel.PoiUtils的包名和poi的重复了，java9以上怎么使用？

### ISSUE THREAD

**Issue by ioi301** [alibaba/easyexcel#2751]
module-info在requires会直接报错
reads package 'org.apache.poi.hssf.usermodel' from both 'poi' and 'easyexcel'
除了改包，貌似无解，真不理解为什么要命名apache这样一个包名
java9以下的没事。
还有什么其他办法？

**Comment by gongxuanzhang** [comment]
模块化无解。。。  要不直接把项目的module-info删掉吧   
9及以上其实可以用，但是不支持模块化

**Comment by gongxuanzhang** [comment]
3010的PR解决了这个问题 等待合并
