### ISSUE TITLE
公式计算的值无法正确读取

### ISSUE THREAD

**Issue by Bluewu129** [alibaba/easyexcel#2754]
### 根据模版填充Excel并读取时，其他不带公式的单元格没有问题，带公式的读取还是模版中的变量，打开修改后，才读取正常。

- 根据模版填充Excel

<img width="705" alt="image" src="https://user-images.githubusercontent.com/25638567/194699777-45245273-6efd-4674-89ac-cb1625b8e2ea.png">

- 填充后根据公式自动计算
<img width="651" alt="image" src="https://user-images.githubusercontent.com/25638567/194699795-c849f963-f023-43b8-815c-967e161f9475.png">

- 读取后的结果
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/25638567/194699873-e1aa11b9-9d92-4775-ab91-fea192c012f2.png">

**Comment by mytherf** [comment]
请问这个怎么解决的？
