### ISSUE TITLE
3.1.1临时文件不会删除，应该怎么处理

### ISSUE THREAD

**Issue by jianyun** [alibaba/easyexcel#2755]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
![image](https://user-images.githubusercontent.com/13871143/194735413-e23c4e33-d886-443f-8b8a-866392ec31f4.png)
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

临时文件不会删除，应该怎么处理
![image](https://user-images.githubusercontent.com/13871143/194735388-cd3c8c94-b011-4363-9d87-825c4d817ca0.png)

**Comment by zhuangjiaju** [comment]
你导出成功没？ 这个需要提供下复现场景，我试了很多次 都是删除的

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
