### ISSUE TITLE
easyexcel读取合并单元格text 为null

### ISSUE THREAD

**Issue by yzh-12** [alibaba/easyexcel#2759]
接口 extra 方法，读取到CellExtraTypeEnum.MERGE类型的单元格时，获取到的text 为null。
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/57436358/195241751-821b87d7-0d31-4067-a368-456dbc622d50.png">

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/57436358/195241511-dcefa77a-664c-4a05-a0ff-2d1d5af9299c.png">

**Comment by zhuangjiaju** [comment]
合并单元格无法获取到内容信息，只能获取哦到第几行到第几行合并。
