### ISSUE TITLE
单词拼写错误：headLineMun

### ISSUE THREAD

**Issue by qldsrx** [alibaba/easyexcel#277]
headLineMun应该为：headLineNum

**Comment by guomindong** [comment]
这种错误放在阿里是不是要拉出去枪毙五分钟

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
