### ISSUE TITLE
当表格的第一行第一个单元格是空的时，无法读取内容

### ISSUE THREAD

**Issue by cdmv23** [alibaba/easyexcel#2770]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**建议描述**
当表格的第一行第一个单元格是空的时，无法读取内容

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
