### ISSUE TITLE
easyexcel 3.0.5版本 读取excel数据 排除掉隐藏列 隐藏行的数据 读取其他所有数据

### ISSUE THREAD

**Issue by 6688-open** [alibaba/easyexcel#2771]
@Override
    public void invokeHeadMap(Map<Integer, String> data, AnalysisContext context) {
        atomicInteger.getAndIncrement();
        this.headMap = data;

        if(atomicInteger.get() == CommonConstants.NUM_FOUR) {
            verifyHead();
        }

    }
AnalysisContext  对象里面是否有判断单元格是隐藏的属性  怎么过滤掉隐藏行 隐藏列数据

**Comment by Tony-luorancx** [comment]
这个问题解决了吗？ 我也遇到类似的需求

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
