### ISSUE TITLE
excel导出设置下拉失败

### ISSUE THREAD

**Issue by peifg** [alibaba/easyexcel#2772]
我在写excel过程中，excel有一列是员工所在单位，要设置成下拉，入下图

![FH@X_HUQ0V6(Q~)JE@7J8P9](https://user-images.githubusercontent.com/76575574/196904257-13a4642b-d129-4aa5-98bd-30139b7ec650.png)

![TKIZT_QFIOTE0KZVV81FLIY](https://user-images.githubusercontent.com/76575574/196904315-652dd03c-1dd9-4954-9a0f-9a850e0f1f11.png)
单位比较多，大概60个左右，当list大于15个的时候，下拉显示不出来，
而在第15个元素，我去掉一个字，下拉就可以显示出来，不去掉下拉就显示不出来，请问一下，这个下来是不是有字数限制呢？或者是哪里有问题？

**Comment by awswt** [comment]
excel自身的问题,下拉框的数组长度超过255就会导致下拉框失效,.建议用隐藏表的做法,...搜索引擎即可
