### ISSUE TITLE
设置表格内容格式的时候 下拉框如何实现多级联动

### ISSUE THREAD

**Issue by chentengfei** [alibaba/easyexcel#2775]
动态生成excel的时候  需要设置表格内容区域单元格联动   比如  省  市  区  3个字段    内容区域需要预置全国地区名称   之间联动筛查    ，目前文档里面只看到了一般下拉框的设置，求教

**Comment by liuzhuangzhuang418** [comment]
是呢看到那个demo了，但是没看明白复杂点的怎么做，求大佬指教

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
