### ISSUE TITLE
在使用Java模块系统的情况下，添加easyexcel作为依赖无法构建成功

### ISSUE THREAD

**Issue by StarChenPy** [alibaba/easyexcel#2776]
在使用Java模块系统（module-info.java 文件）的情况下，添加easyexcel作为依赖无法构建成功
具体错误为：模块 xxx 同时从 easyexcel 和 easyexcel.core 读取程序包 com.alibaba.excel
导入换为easyexcel-core的情况下，报错为：模块 xxx 同时从 easyexcel.core 和 easyexcel.support 读取程序包 com.alibaba.excel.support
排除掉easyexcel.support以后，报错：模块 xxx 同时从 easyexcel.core 和 poi 读取程序包 org.apache.poi
继续删除掉easyexcel.core中的org文件夹后没有报错，但是easyexcel无法运行
我不清楚有没有办法可以指定使用的软件包的目录来避免这个问题，查找资料无果，特此在此询问
技术力较低，若问题很蠢还请见谅

构建工具为 Gradle
Java 版本 Java17

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
