### ISSUE TITLE
Java使用EasyExcel的问题

### ISSUE THREAD

**Issue by AutumnSenYu** [alibaba/easyexcel#2777]
开发者你好,我导入Excel到Java实体类 结果只能导入170列,之后的列的值就被舍弃了,请问是怎么回事

**Comment by yuhaowin** [comment]
provide a demo that can be repeated.

**Comment by zhuangjiaju** [comment]
这个需要提供下 代码&excel

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
