### ISSUE TITLE
微信小程序预览文档公式计算问题

### ISSUE THREAD

**Issue by 652031738** [alibaba/easyexcel#2779]
EasyExcel.write(response.getOutputStream()).withTemplate(templateFileName).build()
问题：方式给微信小程序预览文档，公式没有预计算（点击选择手机中的wps打开，wps打开时会计算一遍公式，电脑打开文档也会计算一遍公式）
就是微信小程序打开文档公式没有计算，是否可以先计算一遍公式再返回

**Comment by zhuangjiaju** [comment]
这个目前不支持 公式计算，建议自己写入具体的值。
