### ISSUE TITLE
在scala使用java类去调用easyExcel去根据模板进行导出

### ISSUE THREAD

**Issue by qq454634668** [alibaba/easyexcel#2782]
需求是在scala中去spark中取值 在调用Java类去使用easyExcel按照模板去导出excel
var out = new FileOutputStream("C:/Users/联想/Desktop/11/"+UUID.randomUUID()+".xlsx");
ExcelWriter excelWriter = EasyExcel.write(out).withTemplate(template)
        .registerWriteHandler(mergeStrategy).build();
//构建excel的sheet
WriteSheet writeSheet = EasyExcel.writerSheet().build();
FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.TRUE).build();
excelWriter.fill(fileData.asJava, writeSheet);
excelWriter.finish();
sacla脚本的编译和调用都是没有报错的，执行excelWriter.finish();后的日志打印也是正常的，控制台也没有错误报出，
就是导出的excel是空，连模板的内容都没有了

**Comment by zhuangjiaju** [comment]
建议下先试用java 试试看

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
