### ISSUE TITLE
导出execl后，直接导入，会出现重复数据

### ISSUE THREAD

**Issue by ZhangPastoral** [alibaba/easyexcel#2784]
导出一份excel，不打开编辑，直接再导入，就会出现重复的数据，调试得到重复的原因是sheet被重复了，其实只有一个sheet，但是读取的时候，变成了2个一模一样名称的sheet。所以数据就被翻倍了。
但是对导出的excel，打开即使不编辑，直接保存，再次导入就会正常了，也观察了一下，即使不编辑直接保存也会导致excel的大小发生变化。
刚刚接触java，恳请给出一些建议和思路

**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**

**异常提示**
无异常
**建议描述**

**Comment by zhuangjiaju** [comment]
这个需要提供下代码 ，实际测试并没有数据翻倍

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
