### ISSUE TITLE
如何给动态数据设置单元格格式为数值类型呢？(由于是动态数据就没有使用实体类注解的方式)

### ISSUE THREAD

**Issue by hubingkuan** [alibaba/easyexcel#2785]
`            EasyExcel.write(os)
                    .registerWriteHandler(new AutoHeadColumnWidthStyleStrategy())
                    .autoCloseStream(Boolean.TRUE)
                    .head(generateRoasExcelHeadTable(sspReportResponse)).sheet("ROAS Report")
                    .doWrite(generateRoasExcelData(sspReportResponse));`

`public class AutoHeadColumnWidthStyleStrategy extends AbstractColumnWidthStyleStrategy {
    private static final int MAX_COLUMN_WIDTH = 255;

    private final Map<Integer, Map<Integer, Integer>> cache = MapUtils.newHashMapWithExpectedSize(8);

    @Override
    protected void setColumnWidth(WriteSheetHolder writeSheetHolder, List<WriteCellData<?>> cellDataList, Cell cell,
                                  Head head, Integer relativeRowIndex, Boolean isHead) {
        if (isHead && cell.getRowIndex() != 0) {
            int columnWidth = cell.getStringCellValue().getBytes().length;
            if (columnWidth > MAX_COLUMN_WIDTH) {
                columnWidth = MAX_COLUMN_WIDTH;
            } else {
                columnWidth = columnWidth + 3;
            }
            writeSheetHolder.getSheet().setColumnWidth(cell.getColumnIndex(), columnWidth * 256);

        }
    }

    @Override
    public void afterCellCreate(CellWriteHandlerContext context) {
        Cell cell = context.getCell();
        if(cell.getRowIndex()!=0){
            if (cell.getStringCellValue().matches("-?[0-9]+.?[0-9]*")) {
                WriteWorkbookHolder writeWorkbookHolder = context.getWriteWorkbookHolder();
                Workbook workbook = writeWorkbookHolder.getWorkbook();
                CellStyle cellStyle = workbook.createCellStyle();
                cellStyle.setDataFormat(HSSFDataFormat.getBuiltinFormat("0.00"));
                cell.setCellStyle(cellStyle);
                //cell.setCellType(CellType.NUMERIC);
            }
        }
    }

/*    @Override
    public void afterCellDispose(CellWriteHandlerContext context) {
        Cell cell = context.getCell();
        if (cell.getStringCellValue().matches("-?[0-9]+.?[0-9]*")) {
            cell.setCellType(CellType.NUMERIC);
        }
    }*/

    private Integer dataLength(List<WriteCellData<?>> cellDataList, Cell cell, Boolean isHead) {
        if (isHead) {
            return cell.getStringCellValue().getBytes().length;
        }
        WriteCellData<?> cellData = cellDataList.get(0);
        CellDataTypeEnum type = cellData.getType();
        if (type == null) {
            return -1;
        }
        switch (type) {
            case STRING:
                return cellData.getStringValue().getBytes().length;
            case BOOLEAN:
                return cellData.getBooleanValue().toString().getBytes().length;
            case NUMBER:
                return cellData.getNumberValue().toString().getBytes().length;
            default:
                return -1;
        }
    }
}`

这里的cell.setCellType(CellType.NUMERIC)以及cell.setCellStyle(cellStyle)都无效

**Comment by hubingkuan** [comment]
![image](https://user-images.githubusercontent.com/67223231/199222600-d6cde5ac-bc35-4c85-880b-e573c4300496.png)

**Comment by hubingkuan** [comment]
这是导出之后的格式  非数值类型

**Comment by hubingkuan** [comment]
目前已经找到办法解决了  自定义一个转换器 将string转为number格式

**Comment by 18716032596** [comment]
麻烦问下，转换器是指拦截器吗？，可以给截一下“转换器”内块儿的代码吗

**Comment by 18716032596** [comment]
奥奥，说的是CellWriteHandler 吗

**Comment by joey-happy** [comment]
> 目前已经找到办法解决了 自定义一个转换器 将string转为number格式

能告知一下是怎么解决的吗？目前我也遇到了同样的问题
