### ISSUE TITLE
冻结表头

### ISSUE THREAD

**Issue by 874379178** [alibaba/easyexcel#2788]
我的代码如下
public class FreezeAndFilter implements SheetWriteHandler {

    public int colSplit = 0, rowSplit = 2, leftmostColumn = 0, topRow = 1;
    public String autoFilterRange = "1:1";
    @Override
    public void beforeSheetCreate(WriteWorkbookHolder writeWorkbookHolder, WriteSheetHolder writeSheetHolder) {

    }

    @Override
    public void afterSheetCreate(WriteWorkbookHolder writeWorkbookHolder, WriteSheetHolder writeSheetHolder) {
        Sheet sheet = writeSheetHolder.getSheet();
        sheet.createFreezePane(colSplit, rowSplit, leftmostColumn, topRow);
    }
}

wps打开能够正常固定住表头
office打开不能固定表头
不知道是什么原因

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
