### ISSUE TITLE
注解@ExcelProperty(value = "日期", index = 1, format = "yyyyMMdd")不支持LocalDate类型

### ISSUE THREAD

**Issue by youapple** [alibaba/easyexcel#279]
注解@ExcelProperty(value = "日期", index = 1, format = "yyyyMMdd")，format不支持LocalDate类型

**Comment by zcjm60** [comment]
看了下项目的jdk版本 是要用jdk7来做的 so java8的时间api不支持

**Comment by fish7790714** [comment]
我基于这个版本写了个新版本 支持了localdate
只要吧pom 改成即可
```xml
        <dependency>
            <groupId>com.github.easy-data</groupId>
            <artifactId>easy-data</artifactId>
            <version>1.0.0</version>
        </dependency>
```

连接：https://github.com/easy-data/easy-data

**Comment by zcjm60** [comment]
> 我基于这个版本写了个新版本 支持了localdate
> 只要吧pom 改成即可
> 
> ```
>         <dependency>
>             <groupId>com.github.easy-data</groupId>
>             <artifactId>easy-data</artifactId>
>             <version>1.0.0</version>
>         </dependency>
> ```
> 
> 连接：https://github.com/easy-data/easy-data

写excel有问题
代码如下：
![image](https://user-images.githubusercontent.com/22487059/56629646-9ef1bb00-6680-11e9-829a-0821bf298fc6.png)
![image](https://user-images.githubusercontent.com/22487059/56629658-aadd7d00-6680-11e9-9aaf-49a78b7b66a7.png)

异常：
![image](https://user-images.githubusercontent.com/22487059/56629680-c2b50100-6680-11e9-8cca-7833bb26d613.png)

后来我debug看是下图为空了
![image](https://user-images.githubusercontent.com/22487059/56629592-779aee00-6680-11e9-83ab-4047c4d4836f.png)

**Comment by xgj1988** [comment]
@zhuangjiaju  有问题。 WriteCellData 这个类，只支持localdatetime ，没有localdate 和localtime 的支持

**Comment by xgj1988** [comment]
只有把localDate和 LocalTime转换成 LocalDateTime。然后用 format 格式化。，感觉这个设计有问题。
