### ISSUE TITLE
请问可以设置跳过n行数据不读取吗

### ISSUE THREAD

**Issue by yaoYuan-hub** [alibaba/easyexcel#2791]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**建议描述**

我现在是自定义监听类，设置headRowNumber为我想跳过的行，可以实现
但是目前的业务场景的excel数据量较大，比如我要跳过100W行，那么还是会一直执行invokeHead方法，效率比较低
麻烦请问有别的方法可以实现直接从100w行开始读取数据吗？

**Comment by zhuangjiaju** [comment]
这个目前没有办法，底层excel是一个xml，不读取上一个标签，没法直接读取下一个，只能慢慢的读。
