### ISSUE TITLE
在3.1.1版本下多级表头想要设置不同的样式

### ISSUE THREAD

**Issue by ccchhh1** [alibaba/easyexcel#2803]
在3.1.1版本下多级表头想要设置不同的样式
但是已经没有之前的StyleUtil.buildHeadCellStyle(workbook, writeCellStyle)
现在应该怎么做呢 谢谢

**Comment by 6Weiqi** [comment]
同样需要

**Comment by zhuangjiaju** [comment]
参照下：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E6%B3%A8%E8%A7%A3%E5%BD%A2%E5%BC%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
