### ISSUE TITLE
请问如何获得某个Cell的类型

### ISSUE THREAD

**Issue by tangbutian123** [alibaba/easyexcel#281]
当导入一个Excel时，如何判断某个Cell或某列为百分比类型

**Comment by fish7790714** [comment]
目前没法获取某个cell的类型 作者全部用string接收 然后再转换的

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。然后成员变量用 CellData去接
