### ISSUE TITLE
生成只有标题、无内容的excel模板时，如何设置某标题下一列的单元格格式为金额类型

### ISSUE THREAD

**Issue by diegozhoudegao** [alibaba/easyexcel#2814]
生成只有标题、无内容的excel模板时，如何设置某标题下一列的单元格格式为金额类型

**Comment by gongxuanzhang** [comment]
自定义拦截器 实现SheetWriteHandler接口
文档参考 https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
