### ISSUE TITLE
 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Jasonandy** [alibaba/easyexcel#282]
java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Font.setBold(Z)V
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1006)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)

**Comment by kungyutucheng** [comment]
顶一下，我也遇到了，SXSSFWorkbook这个类没有setFold方法

版本号：1.1.2-beta4和1.1.2-beat1均不行

异常情景：使用ExcelTypeEnum.XLSX的文件类型

WorkBookUtil.java
`public static Workbook createWorkBook(InputStream templateInputStream, ExcelTypeEnum excelType) throws IOException {
        Object workbook;
        if (ExcelTypeEnum.XLS.equals(excelType)) {
            workbook = templateInputStream == null ? new HSSFWorkbook() : new HSSFWorkbook(new POIFSFileSystem(templateInputStream));
        } else {
            workbook = templateInputStream == null ? new SXSSFWorkbook(500) : new SXSSFWorkbook(new XSSFWorkbook(templateInputStream));
        }

        return (Workbook)workbook;
    }`


StyleUtil.java
`public static CellStyle buildDefaultCellStyle(Workbook workbook) {
        CellStyle newCellStyle = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setFontName("宋体");
        font.setFontHeightInPoints((short)14);
        font.setBold(true);
        newCellStyle.setFont(font);
        newCellStyle.setWrapText(true);
        newCellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
        newCellStyle.setAlignment(HorizontalAlignment.CENTER);
        newCellStyle.setLocked(true);
        newCellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        newCellStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
        newCellStyle.setBorderBottom(BorderStyle.THIN);
        newCellStyle.setBorderLeft(BorderStyle.THIN);
        return newCellStyle;
    }`


`font.setBold(true);`
这一行报错了

**Comment by kungyutucheng** [comment]
后来去除本地版本包对poi的依赖就可以了

**Comment by newCheng** [comment]
请确认本地是否引用了poi高版本的包。easyexcel 最新的1.1.2-beta4包使用的是poi 3.17。pom中如果被其他版本poi覆盖。请特别引用3.17版本的poi相关包。添加示例如下：
<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.17</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.17</version>
		</dependency>

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
