### ISSUE TITLE
@ContentFontStyle 注解设置字体问题

### ISSUE THREAD

**Issue by nian5241** [alibaba/easyexcel#2822]
version : 3.1.1
<img width="557" alt="CFA9BB1F-47C9-4246-8B8B-FA81319AD5CF" src="https://user-images.githubusercontent.com/25626648/202644871-f6c12667-355d-4721-b3ef-120054d0b0c8.png">
<img width="760" alt="36B073C4-D304-4EC3-A4DE-8DC443573B72" src="https://user-images.githubusercontent.com/25626648/202644893-40d04277-c1cb-4fb3-996e-282b3c79604e.png">

使用此注解设置内容字体大小有问题。demo中设置内容字体为10，导出的excel前两列字体正常显示为10，但是后一列却是11

**Comment by nian5241** [comment]
debug了下源码找到了问题所在：easyExcel在initColumnProperty的时候获取字段名称调用的是这个方法com.alibaba.excel.util.FieldUtils#resolveCglibFieldName，此方法其中有个策略：如果字段名称第一个是字母是小写第二个是大写，则此方法会将第一个字母变成大写，因此我定义的字段tExternalReturnCDC会变成TExternalReturnCDC。而系统的Map<Class<?>, Map<String, ExcelContentProperty>> CLASS_CONTENT_CACHE 这个map使用的字段名称是原始的名称，因此通过TExternalReturnCDC这个名称在map中找不到对应的属性，进而导致自定义的属性失效。
建议这两部分的fieldName的方式统一一下。

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
