### ISSUE TITLE
07

### ISSUE THREAD

**Issue by reddylin** [alibaba/easyexcel#2823]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**触发场景描述**
转换BigDecimal代码BUG, 丢失小数精度, 应该使用new BigDecimal(tempDataString)
**触发Bug的代码**
0.0001
```java
  com.alibaba.excel.analysis.v07.handlers.CellTagHandler#endElement
  ...
  tempCellData.setType(CellDataTypeEnum.NUMBER);
  tempCellData.setNumberValue(BigDecimal.valueOf(Double.parseDouble(tempDataString)));
```
**提示的异常或者没有达到的效果**
scale == 4

**Comment by zhuangjiaju** [comment]
这个比较坑 直接用也会有问题。

**Comment by zhuangjiaju** [comment]
这个问题已经在`3.2.0`中修复，建议升级到最新版本。
用`string` 会接收到你看到的数据。
用`BigDecimal`会接收到你点击单元格，输入框看到的数据。
