### ISSUE TITLE
多列表并行填充，出现数据错位 

### ISSUE THREAD

**Issue by small-Devil** [alibaba/easyexcel#2826]
![image](https://user-images.githubusercontent.com/37925386/203251056-f17d2914-2d94-433a-a556-ab6c2af42911.png)

这是模板：
![image](https://user-images.githubusercontent.com/37925386/203250800-64b265bc-2be2-4bc6-9bb1-581c953270f9.png)
这是导出的数据：
![image](https://user-images.githubusercontent.com/37925386/203250909-4df6151e-ff67-4269-8653-e54aad5537e4.png)
有没有方法避免这种数据错位呢

**Comment by ChrisonLeon** [comment]
我正好遇到，如果列表下面，没有其他数据了，改成Boolean.FALSE即可

**Comment by small-Devil** [comment]
> 我正好遇到，如果列表下面，没有其他数据了，改成Boolean.FALSE即可

问题是你怎么知道下面有没有其他数据呢？

**Comment by ChrisonLeon** [comment]
> > 我正好遇到，如果列表下面，没有其他数据了，改成Boolean.FALSE即可
> 
> 问题是你怎么知道下面有没有其他数据呢？

下面有没有数据，你看你模板就知道了，不是说列表是20条还是30条，而是列表下面是否有其他填充数据。
你只是两列并列的列表，列表下方并没有总计，合计之类的东西，不需要写Boolean.TRUE.    你仔细看下文档他也说了。

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue.
