### ISSUE TITLE
导出为csv文件时registerConverter不生效？

### ISSUE THREAD

**Issue by wcy1113** [alibaba/easyexcel#2827]
我要导出到csv文件中的数据有java.sql.Date的时间类型。我自定以转换器并注册后并没有生效
**导出的代码**
```java
   EasyExcel.write(path).registerWriteHandler(horizontalCellStyleStrategy())
                .excelType(ExcelTypeEnum.CSV)
                .registerWriteHandler(new AdaptiveColumnWidthStrategy())
                // java.sql.Date数据类型转换器
                .registerConverter(new SqlDateConverter())
                .head(head)
                .autoCloseStream(Boolean.TRUE)
                .sheet(sheetName)
                .doWrite(dataList);
   
```

**自定义的转换器**
```java
   public class SqlDateConverter implements Converter<Date> {

    @Override
    public Class<?> supportJavaTypeKey() {
        return Date.class;
    }

    @Override
    public CellDataTypeEnum supportExcelTypeKey() {
        return CellDataTypeEnum.STRING;
    }

    @Override
    public WriteCellData<?> convertToExcelData(Date value, ExcelContentProperty contentProperty,
                                               GlobalConfiguration globalConfiguration) {
        return new WriteCellData<>(DateUtil.format(value, "yyyy-MM-dd"));
    }
}
```
**异常提示**
com.alibaba.excel.exception.ExcelWriteDataConvertException: Can not find 'Converter' support class Date.

调试时converterMap中转换器的cellDataTypeEnum=null，为啥不是String类型？
![image-20221122145805630](https://user-images.githubusercontent.com/62496229/203259608-12e44e8e-12ec-481f-93bf-35dfd318998f.png)

**Comment by wcy1113** [comment]
版本3.1.1

**Comment by tangfan916** [comment]
![image](https://github.com/alibaba/easyexcel/assets/25817302/50bd5576-0acb-49a0-ab71-f5dd891104f2)
同样的问题，ConverterKeyBuild.buildKey(Class<?> clazz) 默认 CellDataTypeEnum 为null，csv格式，获取的时候 CellDataTypeEnum 为 STRING，导致获取 converter为null

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
