### ISSUE TITLE
Excel没有读取到Cell备注

### ISSUE THREAD

**Issue by MLeft** [alibaba/easyexcel#2831]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**触发场景描述**

Excel读取备注信息

**触发Bug的代码**
```java
 @Slf4j
public class NoModelDataListener implements ReadListener<Map<Integer, String>> {

    @Override
    public void extra(CellExtra extra, AnalysisContext context) {
        log.info("读取到了一条额外信息:{}", JSON.toJSONString(extra));
    }

    @Override
    public void invoke(Map<Integer, String> cellDataMap, AnalysisContext context) {
        ReadHolder readHolder = context.currentReadHolder();
        Map<Integer, Cell> cellMap = context.readRowHolder().getCellMap();
        ReadCellData<?> cellData = (ReadCellData<?>) cellMap.get(0);
        log.info("读取到了一行Cell信息:{}", JSON.toJSONString(cellDataMap));
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
        log.info("所有数据解析完成！");
    }
}
```
**提示的异常或者没有达到的效果**
存在备注的Excel，读取时没有触发`extra(CellExtra extra, AnalysisContext context)`回调
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/6762483/203690186-f981ca33-481b-4bb3-813a-978070fc5259.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/6762483/203690337-a9c001b0-55f2-48e3-b511-4b8ae76054b6.png">

**Comment by rangyf** [comment]
Already closed? I encountered the same problem with version 3.2.2

**Comment by viccP** [comment]
读取单元格额外信息的时候需要这样写：`          
EasyExcel.read(inputFile, SomeBean.class, excelReader)
                .extraRead(CellExtraTypeEnum.MERGE)
                .sheet()
                .doRead();`
