### ISSUE TITLE
有没有复选框这种表单的实现方式

### ISSUE THREAD

**Issue by mhcchenxi** [alibaba/easyexcel#2832]
有没有复选框这种表单的实现方式

**Comment by gongxuanzhang** [comment]
你说的是否是excel的下拉选择,如果是可以通过实现SheetWriteHandler 或者CellWriteHandler 进行操作
具体下拉框的代码可以参考 https://blog.csdn.net/a823007573/article/details/102955634
easyexcel接口的使用方式可以参考 https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#excel%E7%A4%BA%E4%BE%8B-11

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
