### ISSUE TITLE
如何删除指定列

### ISSUE THREAD

**Issue by zy-chuai** [alibaba/easyexcel#2837]
没有在文档上找到该方法，请问有什么别的处理方式吗

**Comment by zhuangjiaju** [comment]
什么场景需要删除？不导入不可以么?

**Comment by zhuangjiaju** [comment]
目前没有办法 删除原文件中的列，建议直接使用poi

**Comment by ysysycyc** [comment]
批量写入的时候，有时候需要再写入完成后判断删除空列，写之前判断该列是否有数据的成本太高
