### ISSUE TITLE
Apache poi 4.1.2 is having blackduck issue, while 5.2.3 is recommended version. Can update this?

### ISSUE THREAD

**Issue by OlajuwonZhu** [alibaba/easyexcel#2842]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by kevinkwok326** [comment]
上面提到的这笔提交似乎没合进发行版本？最新的3.3.1依赖的仍然是4.1.2版本，从Tag代码看，还是发行的pom看都是

![image](https://github.com/alibaba/easyexcel/assets/107452466/063d5219-fb39-46f0-9bc1-bd0f72cd2b83)

**Comment by psxjoy** [comment]
Hi, we have an update to poi-5！
This issue has been completed, I will close this issue.
