### ISSUE TITLE
自定义格式是G/通用格式;-G/通用格式; 解析出来是-General

### ISSUE THREAD

**Issue by xu040633** [alibaba/easyexcel#2843]
**异常代码**
用的是无对象的读，最终获取的数据是-General
```java

 EasyExcel.read(file.getInputStream(), dataListener).sheet().headRowNumber(3).doRead();
//监听器
 public void invoke(Map<Integer, Object> data, AnalysisContext context) {
list.add(data)
}


```
[test.xls](https://github.com/alibaba/easyexcel/files/10120976/test.xls)
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by gongxuanzhang** [comment]
感谢issues，我复现之后发现是你的单元格中有自定义的公式。 使用默认解析器StringNumberConverter 解析之后变成了你看到的样子。如果想更新解析可以清空公式或者自定义解析器。

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
