### ISSUE TITLE
你的例子代码能给全，这里少一块那里少一块？？？？？？？？？？？

### ISSUE THREAD

**Issue by 825909958** [alibaba/easyexcel#2844]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**建议描述**

**Comment by zhuangjiaju** [comment]
那一块代码没给全，详细说明下。 不行可以参考：https://github.com/alibaba/easyexcel/blob/master/easyexcel-test/src/test/java/com/alibaba/easyexcel/test/demo/read/ReadTest.java 有能直接运行的类

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
