### ISSUE TITLE
使用easyexcel，当我不创建对象去读文件时，得到数据只能是Map<Integer,String> 吗？不能是Map<Integer,Object>？或者有方法能让我自己转换excel中的数值为日期吗？

### ISSUE THREAD

**Issue by jnan0303** [alibaba/easyexcel#2845]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
## 问题
excel 中设置单元格是日期类型，读取之后拿到的数据是字符串类型，我能直接获取到日期类型的数据吗？

**异常代码**
```java
   这里写你的代码


import com.alibaba.excel.context.AnalysisContext;
import com.alibaba.excel.event.AnalysisEventListener;
import com.alibaba.excel.util.ListUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.Map;

/**
 * 直接用map接收数据
 *
 * @author Jiaju Zhuang
 */
public class NoModelDataListener extends AnalysisEventListener<Map<Integer, Object>> {

    Logger log = LoggerFactory.getLogger(this.getClass());
    /**
     * 每隔5条存储数据库，实际使用中可以100条，然后清理list ，方便内存回收
     */
    private static final int BATCH_COUNT = 1000;
    private List<Map<Integer, Object>> cachedDataList = ListUtils.newArrayListWithExpectedSize(BATCH_COUNT);

    int total = 0;

    @Override
    public void invoke(Map<Integer, Object> data, AnalysisContext context) {
        cachedDataList.add(data);
        if (cachedDataList.size() >= BATCH_COUNT) {
            saveData();
            cachedDataList = ListUtils.newArrayListWithExpectedSize(BATCH_COUNT);
        }
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
        saveData();
        log.info("所有数据解析完成！共:{}条数据", total);
    }

    /**
     * 加上存储数据库
     */
    private void saveData() {
        total += cachedDataList.size();
    }
}



```
**异常提示**
请提供完整的异常提示,记住是全部异常！

<img width="397" alt="image" src="https://user-images.githubusercontent.com/85336405/205016131-0f1bb46d-b528-4006-bfbb-aa59f7493eef.png">

**建议描述**

**Comment by zhuangjiaju** [comment]
这个问题在`3.2.0`中已经修复，建议升级到最新版本。
新增参数：
| readDefaultReturn           | STRING                                                       | `@since 3.2.0`。STRING:会返回一个Map<Integer,String>的数组，ACTUAL_DATA：会返回一个Map<Integer,Object>的数组，Object类型为`BigDecimal`、`Boolean`、`String`、`String`、null，中的一个，READ_CELL_DATA: 会返回一个Map<Integer,ReadCellData<?>>的数组,其中`?`类型参照ACTUAL_DATA的            |

可以参考api：https://easyexcel.opensource.alibaba.com/docs/current/api/#readworkbook
