### ISSUE TITLE
com.alibaba.excel.exception.ExcelAnalysisException: org.apache.poi.poifs.filesystem.NotOLE2FileException:

### ISSUE THREAD

**Issue by limengzhao** [alibaba/easyexcel#2846]
Invalid header signature; read 0x0A0D3E6C6D74683C, expected 0xE11AB1A1E011CFD0 - Your file appears not to be a valid OLE2 document

**Comment by zhuangjiaju** [comment]
这个原因是 你指定了excel的类型，但是实际上不是这个类型。
重新换个文件就行
