### ISSUE TITLE
读取excel获取sheet列表数据异常，会出现word中看不到得sheet名称

### ISSUE THREAD

**Issue by Arno-Code** [alibaba/easyexcel#2848]
**读取excel但是不知道excel的sheet数量时获取所有sheet出现异常数据   easyexcel版本3.1.2**
ming
**触发Bug的代码**
```java
       public static List<Map<String, Object>> readExcelAllSheet(String fileName) throws IOException {
        List<Map<String, Object>> result = ListUtils.newArrayListWithExpectedSize(10000);
        // 写法1
        try (ExcelReader excelReader = EasyExcel.read(fileName, new NoModelDataListener(result)).headRowNumber(0).build()) {
            // 这里为了简单 所以注册了 同样的head 和Listener 自己使用功能必须不同的Listener
            List<ReadSheet> sheets = excelReader.excelExecutor().sheetList();
            excelReader.read(sheets);
        }
        System.out.println(JSONObject.toJSONString(result));

        return result;
    }
```
触发bug代码

```java
 List<ReadSheet> sheets = excelReader.excelExecutor().sheetList();
```

这里获取到的sheets 有脏数据，读取的excel只有五个sheet，但是这里的sheets有6个sheet固有脏数据（sheetNo=0为脏数据），脏数据产生可能是有<Worksheet ss:Name="a7XGyh">这个标签，具体如下图所示：

![image](https://user-images.githubusercontent.com/47142725/204987978-b1a5b1ac-c5df-418e-9711-4423d2168b7e.png)
![image](https://user-images.githubusercontent.com/47142725/204988286-67f9f2d3-d9e5-44da-8810-86c5c482e6b9.png)

![image](https://user-images.githubusercontent.com/47142725/204988671-8e8dec95-79a4-4f0d-805e-303ce21f3310.png)

**Comment by gongxuanzhang** [comment]
@Arno-Code  
可以提供一份可以复现的excel吗  我自己测试是OK的

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
