### ISSUE TITLE
无模型模式，如何获取excel里面日期的自定义格式？

### ISSUE THREAD

**Issue by yangyue1943** [alibaba/easyexcel#285]
目前我使用正则判断列是否为日期，再使用HSSFDateUtil.getJavaDate(d, false)转为日期，但是会有误差，能否获取到单元格cell的自定义日期格式，以此来判断该列是日期还是数字。

**Comment by airsolstice** [comment]
我也想请教下关于无模型模式下，就没有办法获取每个单元格的数据类型吗？我这边有一个需求是在读取的时候显示单元格的meta信息，包括类型，精度等。

**Comment by fish7790714** [comment]
作者设计的逻辑是尽量简单，所以抛弃了poi，那一堆类型 ，统一自动转换。目前没法获取cell的类型

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
