### ISSUE TITLE
根据列名读取数据有的列读取不到，索引可以读到

### ISSUE THREAD

**Issue by rockit-ba** [alibaba/easyexcel#2854]
根据列名读取数据有的列读取不到，索引可以读到，请问这个是什么问题呢，谢谢大哥

**Comment by zhuangjiaju** [comment]
详细描述下问题，应该是有空格之类的

**Comment by zhuangjiaju** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
