### ISSUE TITLE
加了 @ExcelIgnore 依然报 Can not find 'Converter' support class List.

### ISSUE THREAD

**Issue by caiqichang** [alibaba/easyexcel#2858]
```java
   @ExcelIgnore
    private List<String> barcodeList;
```

com.alibaba.excel.exception.ExcelDataConvertException: Can not find 'Converter' support class List.

加了 @ExcelIgnore 依然报 Can not find 'Converter' support class List.

**Comment by WyattYiu** [comment]
类上加@ExcelIgnoreUnannotated试试

**Comment by zhuangjiaju** [comment]
是否还存在其他list?

**Comment by zhuangjiaju** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue

**Comment by MeituanRider** [comment]
> @ExcelIgnoreUnannotated

关闭个勾八

**Comment by MeituanRider** [comment]
> 不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue

确实解决了，嘿嘿
