### ISSUE TITLE
读取excel时，如何获取sheetName

### ISSUE THREAD

**Issue by seedtwj** [alibaba/easyexcel#2864]
需要模糊匹配sheetName，然后读取对应sheet中的数据

**Comment by wsxjoin** [comment]
可以通过 context.readSheetHolder().getSheetName()  获取sheet名称
或者 excelReader.excelExecutor().sheetList()

**Comment by gongxuanzhang** [comment]
EasyExcel.read(filename).sheet(sheetName); 可选择对应sheetName   暂不支持模糊匹配
