### ISSUE TITLE
只  行合并

### ISSUE THREAD

**Issue by GithubGey** [alibaba/easyexcel#2865]
目前导出的效果
<img width="413" alt="image" src="https://user-images.githubusercontent.com/86140803/206666199-f23e1fc1-8502-48c6-9f1c-cbc7a53a8df8.png">
我想实现导出的效果
<img width="191" alt="image" src="https://user-images.githubusercontent.com/86140803/206666373-26974a9e-7d22-4586-b333-03b032173657.png">
我想要导出实现 行 的合并效果  有什么方案或者借鉴

**Comment by gongxuanzhang** [comment]
你是用模板，还是怎么导出的，贴一些代码。或者原生POI

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue

**Comment by GithubGey** [comment]
> 不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果问题还存在请重新打开这个问题

已解决，谢谢
