### ISSUE TITLE
excel读取时可以设置指定编码格式吗

### ISSUE THREAD

**Issue by vinside2000** [alibaba/easyexcel#2868]
**异常提示**
Convert excel format exception.You can try specifying the 'excelType' yourself
**现象描述**
后台环境的默认语言是gbk格式，使用xftp上传excel文件时选择了utf-8格式，读取该文件时报了上述excel类型不支持的错误；当使用xftp上传excel文件时选择了gbk格式，则能正常读取。

上述情况，如何读取utf-8格式文件可以成功读取

**Comment by gongxuanzhang** [comment]
@zhuangjiaju     是否加入planning

**Comment by gongxuanzhang** [comment]
@zhuangjiaju

**Comment by tmlx1990** [comment]
excelType 这个是指的你文件的类型把 ？ .excelType(ExcelTypeEnum.CSV) 你用这个设置下试试呢  中间具体文件类型根据你的实际情况来

**Comment by vinside2000** [comment]
编码格式问题，导致中文文件名乱码，就解析不到excel得格式，解决的方法是用英文名命名或者是统一编码格式
