### ISSUE TITLE
读取excel可以不面向注解开发吗？

### ISSUE THREAD

**Issue by yobdms** [alibaba/easyexcel#2870]
读取excel可以不面向注解开发吗？

看见就脑壳痛。。正常调用函数实现读取功能能不能行？有没有代码。

**Comment by WyattYiu** [comment]
可以的，看下文档就知道了

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
