### ISSUE TITLE
easyExcel 读取很慢的一个场景。

### ISSUE THREAD

**Issue by liufuws** [alibaba/easyexcel#2871]
/** controller 层模拟场景代码 */
@GetMapping(value ="/finance")
    public  void sendMailController(){
        StopWatch sw = new StopWatch();
        List<BasicEmpInfoExcelDTO> basicEmpInfoDtoList = new ArrayList<>();
        File file = new File("E:\\IDEA_Code\\***\\excelResult\\员工基础信息报表20221213193018.xlsx");
        sw.start("读取人员基础信息");
        EasyExcel.read(file, BasicEmpInfoExcelDTO.class, EasyExcelListener.getListener(basicEmpInfoDtoList))
                .sheet("员工基础信息报表")
                .doRead(); //第①个读取 excel 场景
        sw.stop();
        System.out.println(sw.getTotalTimeSeconds());
        testExcel();
}

public void testExcel(){
        List<BasicEmpInfoExcelDTO> basicEmpInfoDtoList = Lists.newArrayList();
        File file = new File("E:\\IDEA_Code\\***\\excelResult\\员工基础信息报表20221213193018.xlsx");
        log.info("开始");
        EasyExcel.read(file, BasicEmpInfoExcelDTO.class, EasyExcelListener.getListener(basicEmpInfoDtoList))
                .sheet("员工基础信息报表")
                .doRead();   //第②个读取 excel 场景
        log.info("结束");
    }

/** 这里是我的监听器 */
public class EasyExcelListener {
  public static <T> AnalysisEventListener<T> getListener(List<T> list){
        return new AnalysisEventListener<T>() {
            @Override
            public void invoke(T data, AnalysisContext context) {
                log.info("解析到一条数据:{}", data.toString());
                list.add(data);
            }

            @Override
            public void doAfterAllAnalysed(AnalysisContext context) {
                log.info("所有数据解析完毕！共{}条！",list.size());
            }
        };
    }

}

上面是我的模拟场景代码；在一个 controller 上面读取 excel 两次，excel 文件数量 50W左右；第一个读取数据场景花时100秒左右，但是第二个场景中跑了半小时都没出来；个人也在测试单元中，使用 main 方法测试，也是在一个 A 方法中，调用 B 方法，其中 B 方法也有使用 EasyExcel 读取同一个文件，在 main 方法中测试，两个都是几十秒就能完成；所以我的疑问是，为什么在容器管理中的组件中，A 方法读取excel 100s, A方法调用B方法，在 B 方法中读取 excel ，但是 B 方法读取excel 半小时都没出来结果呢？跪求大佬们解答。

**Comment by gongxuanzhang** [comment]
可以提供一个测试excel吗(注意把数据脱敏)
