### ISSUE TITLE
在动态创建多sheet页，循环调用 write( 数据, WriteSheet对象)写入数据时报The maximum number of cell styles was exceeded. You can define up to 4000 styles in a .xls workbook

### ISSUE THREAD

**Issue by 335747949** [alibaba/easyexcel#2872]

**Comment by zhuangjiaju** [comment]
你创建了多少的sheet?

**Comment by 335747949** [comment]
问题已经解决了，更换了esyexcel更高的版本，代码成功运行。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月8日(星期三) 晚上8:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 在动态创建多sheet页，循环调用 write( 数据, WriteSheet对象)写入数据时报The maximum number of cell styles was exceeded. You can define up to 4000 styles in a .xls workbook (Issue #2872)





 
你创建了多少的sheet?
