### ISSUE TITLE
磁盘空间不足时poi-sheet.xml临时文件清理失败

### ISSUE THREAD

**Issue by WaitRainbow** [alibaba/easyexcel#2878]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**触发场景描述**
poi-sheet-xxxxxx.xml文件体量激增，导致出现磁盘空间不足的场景。理论上说，即使出现磁盘空间不足，也应该要在任务结束时将临时文件删除，但在org.apache.poi.xssf.streaming.SXSSFWorkbook类的dispose方法中，清理临时文件的逻辑会失败，此段代码会在catch中再次抛出一个”磁盘空间不足“的异常。
<img width="852" alt="image" src="https://user-images.githubusercontent.com/51317190/209042440-dbd2d394-daaf-4a72-a554-81ca78cea006.png">
在issues中检索后发现，已经有人提及这个bug：[poifiles临时文件无法删除 #2536](https://github.com/alibaba/easyexcel/issues/2536)
**触发Bug的代码**
```java
```
**提示的异常或者没有达到的效果**
<img width="839" alt="image" src="https://user-images.githubusercontent.com/51317190/209042552-6f4d65a8-2c13-406b-8863-91fa326403ef.png">
由于临时文件删除逻辑失效，会导致磁盘空间不足的状态一直持续（直到手动清理临时文件）
<img width="818" alt="image" src="https://user-images.githubusercontent.com/51317190/209043215-cf92b199-c715-4a02-9883-b4cf09584b96.png">

**Comment by WaitRainbow** [comment]
补充debug流程：
![image](https://user-images.githubusercontent.com/51317190/209077230-727cbbe8-5fee-4167-a06a-df5c72972452.png)
以及报错信息：
![image](https://user-images.githubusercontent.com/51317190/209077279-13fb01cd-df54-4a56-8e27-836b298bd9eb.png)
最后还是手动处理了临时文件。
曲线救国的方式是外挂了一个大空间的磁盘，并将java.io.tmpdir的位置指向到该磁盘上，避免出现磁盘空间不足的情况。

**Comment by zhuangjiaju** [comment]
这个建议参考这个文章，用性能换空间：https://zhuanlan.zhihu.com/p/598823680
