### ISSUE TITLE
导出多级表头时，一级表头相同没有自动合并

### ISSUE THREAD

**Issue by mafanaonb** [alibaba/easyexcel#2881]
[下载.xlsx](https://github.com/alibaba/easyexcel/files/10293317/default.xlsx)

**Comment by zhuangjiaju** [comment]
我看自动合并了，哪一列没有自动合并？

**Comment by zhuangjiaju** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
