### ISSUE TITLE
csv文件长字符串科学计数法问题

### ISSUE THREAD

**Issue by liuhedev** [alibaba/easyexcel#2882]
考虑csv比xls文件小，所以我们只考虑csv文件。
比如一个字符串超过15位，如"20221216699636271792163"，生成xls是没有问题的，生成的csv会被科学计数法，如图：
<img width="304" alt="image" src="https://user-images.githubusercontent.com/19663285/209358508-ada3c392-1030-49e7-8abf-21a03cb75393.png">

目前我的解决方案是自定义Converter，在这种字符串上拼接”\t“，**不知道还有没有别的解决方案？**

<img width="714" alt="image" src="https://user-images.githubusercontent.com/19663285/209359387-9be11e2a-e94e-477f-b4f9-fbe6128592af.png">

**Comment by zhuangjiaju** [comment]
有没有尝试过 用 文本打开？这个是预览的问题，或者可以尝试 改成文本后写入

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
