### ISSUE TITLE
表头斜线和文本框

### ISSUE THREAD

**Issue by sgw1276** [alibaba/easyexcel#2883]
使用自定义拦截器生成的表头斜线和文本框，不能移动和删除是怎么回事？移动的时候相当于复制一份？
XSSFClientAnchor anchor = drawing.createAnchor(0, 0,
                600, 1400, 5, 30, 11, 37);

        XSSFTextBox textBox1 = drawing.createTextbox(anchor);
        textBox1.setLineStyleColor(0, 0, 0);
        java.awt.Color col = Color.white;
        textBox1.setFillColor(col.getRed(), col.getGreen(), col.getBlue());
        //富文本字符串
        XSSFRichTextString address = new XSSFRichTextString("测试");
        textBox1.setText(address);
        //文字字符属性
        CTTextCharacterProperties rpr = textBox1.getCTShape().getTxBody().getPArray(0).getRArray(0).getRPr();
        //设置字体
        rpr.addNewLatin().setTypeface("Trebuchet MS");
        //设置字体大小9pt
        rpr.setSz(900);
        //设置字体颜色，蓝色
        col = Color.blue;
        rpr.addNewSolidFill().addNewSrgbClr().setVal(new byte[]{(byte) col.getRed(), (byte) col.getGreen(), (byte) col.getBlue()});

**Comment by gongxuanzhang** [comment]
我用你的方法导出的文本框是正常的， 从"不能移动和删除，移动的时候复制"看。 检查一下键盘是否长按了Ctrl或者Alt键。
如果不能解决问题，请把完成代码提供一下

**Comment by sgw1276** [comment]
和我用的是SXSSFWorkbook有关系吗
