### ISSUE TITLE
如何根据下拉框选项值（名称）获取其引用（数据验证）的单元格前一个单元格值（编号）？

### ISSUE THREAD

**Issue by cheng-qiang** [alibaba/easyexcel#2896]
[示例图片](https://foruda.gitee.com/images/1672815108478154724/93de59d7_7639516.png)

[参考代码](https://gitee.com/chengqiangxj/cheng-qiang-code-samples/tree/master/EasyExcel)

**Comment by cheng-qiang** [comment]
[图片](https://foruda.gitee.com/images/1672815108478154724/93de59d7_7639516.png)

**Comment by zhuangjiaju** [comment]
目前不支持读取下拉框，后续会考虑支持
