### ISSUE TITLE
excel单元格展示51.99 实际的数值51.9925，如何读取实际原始数据？

### ISSUE THREAD

**Issue by Lukeluhh** [alibaba/easyexcel#2898]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**
![image](https://user-images.githubusercontent.com/32117260/210716980-34b733c3-34b9-4d4e-a3cc-4b2ef1c71b8e.png)
![image](https://user-images.githubusercontent.com/32117260/210717011-270b4eda-334d-40c4-b6d1-280a82868257.png)
代码用String去获取 字段未加任何注解
怎么获取到原始数据

**Comment by Lukeluhh** [comment]
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>3.1.1</version>
        </dependency>
目前 单元格展示51.99  程序读取就是51.99

如何读取到51.9925

**Comment by zhuangjiaju** [comment]
这个我要规划下

**Comment by zhuangjiaju** [comment]
简单的方案 你用`BigDecimal` 去接受即可

**Comment by zhuangjiaju** [comment]
这个问题在`3.2.0`中已经修复，建议升级到最新版本。
可以使用string接受，会接收到到 51.99
建议使用BigDecimal 接受 ，然后自己格式化
