### ISSUE TITLE
只能读取相对路径，不能读取绝对路径

### ISSUE THREAD

**Issue by xiaofsu** [alibaba/easyexcel#290]
` InputStream inputStream = FileUtil.getResourcesFileInputStream("5566.csv");
        List<Object> data = EasyExcelFactory.read(inputStream, new Sheet(1, 0));
//这样是可以读取出来数据的，但是绝对路径inputStream读取出来是个null
//在windows下 E://***.csv  读取的inputStream是个null
//希望作者可以看到回复下谢谢。
`

**Comment by fish7790714** [comment]
这个和这个工具没关系  FileUtil.getResourcesFileInputStream的代码为
```java
  public static InputStream getResourcesFileInputStream(String fileName) {
        return Thread.currentThread().getContextClassLoader().getResourceAsStream("" + fileName);
    }
```
如果你要读取本地的文件 请用 
```java
new FileInputStream(new File(" E://***.csv"));
```

**Comment by xiaofsu** [comment]
好的，谢谢您。我这边已经测试通过了。

在 2019-04-03 16:32:20，"zhuangjiaju" <notifications@github.com> 写道：


这个和这个工具没关系 FileUtil.getResourcesFileInputStream的代码为

publicstaticInputStream getResourcesFileInputStream(String fileName) {

        returnThread.currentThread().getContextClassLoader().getResourceAsStream(""+ fileName);

    }

如果你要读取本地的文件 请用

newFileInputStream(newFile(" E://***.csv"));

**Comment by xiaofsu** [comment]
OK.Thanks.
