### ISSUE TITLE
web下载excel，文件中文名会被替换为下划线，编码问题吗？ utf-8无效

### ISSUE THREAD

**Issue by tyfwe** [alibaba/easyexcel#291]
List<List<String>> tempHeadList = new ArrayList<>();
            for (String tempHead: headList) {
                tempHeadList.add(Arrays.asList(tempHead));
            }
            HttpServletResponse response = getResponse();
            fileName = new String(fileName.getBytes(), "UTF-8");
            response.setContentType("multipart/form-data");
            response.setCharacterEncoding("utf-8");
            response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx");
            ServletOutputStream out = response.getOutputStream();
            ExcelWriter writer = new ExcelWriter(out, ExcelTypeEnum.XLSX, true);
            Sheet sheet1 = new Sheet(1, 0);
            sheet1.setSheetName(sheetName);
            sheet1.setHead(tempHeadList);
            writer.write0(dataList, sheet1);
            writer.finish();
            out.flush();

**Comment by tyfwe** [comment]
是中文名会被替换为下划线，编码问题吗？ utf-8无效

**Comment by fish7790714** [comment]
这个问题和工具类灭有任何关系吧 你本地默认gbk的
```java
fileName = new String(fileName.getBytes(), "UTF-8");
```
把代码转成utf8了，你尝试下把这行代码删除掉

**Comment by escapeI** [comment]
不是转成UTF-8，你试试这个，我是用这种方式的。
`fileName = new String(fileName.getBytes(),"iso-8859-1");`

**Comment by fish7790714** [comment]
直接使用
```java
fileName = new String(fileName.getBytes("gb2312"), "ISO8859-1" ) ;
```
试试

**Comment by fish7790714** [comment]
> 不是转成UTF-8，你试试这个，我是用这种方式的。
> `fileName = new String(fileName.getBytes(),"iso-8859-1");`

直接使用
```java
fileName = new String(fileName.getBytes("gb2312"), "ISO8859-1" ) ;
java
试试

**Comment by tyfwe** [comment]
> > 不是转成UTF-8，你试试这个，我是用这种方式的。
> > `fileName = new String(fileName.getBytes(),"iso-8859-1");`
> 
> 直接使用
> 
> ```java
> 文件名=  新 字符串（文件名。的getBytes（ “ GB2312 ”）， “ ISO8859-1 ”）;
> ```
> 
> 试试

谢谢

**Comment by JsonSong89** [comment]
纠结了好久,发现根本不是编码问题,也许你撞运气好了,但换个环境就又不行了.
 String encodeFilename = URLEncoder.encode(fileName, StandardCharsets.UTF_8.toString());
这个才是正解.

**Comment by githublms** [comment]
纠结了好久,发现根本不是编码问题,也许你撞运气好了,但换个环境就又不行了.
String encodeFilename = URLEncoder.encode(fileName, StandardCharsets.UTF_8.toString());
这个才是正解.
赞同，此处正解

**Comment by nkyy5** [comment]
> 纠结了好久,发现根本不是编码问题,也许你撞运气好了,但换个环境就又不行了.
> String encodeFilename = URLEncoder.encode(fileName, StandardCharsets.UTF_8.toString());
> 这个才是正解.

赞

**Comment by 493955394** [comment]
> 纠结了好久,发现根本不是编码问题,也许你撞运气好了,但换个环境就又不行了.
> String encodeFilename = URLEncoder.encode(fileName, StandardCharsets.UTF_8.toString());
> 这个才是正解.
> 赞同，此处正解

太棒了，试了好几个，就你这个好使

**Comment by githublms** [comment]
有用就好



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月15日(星期二) 下午2:10
收件人: ***@***.***&gt;; 
抄送: "逆 阳 影 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/easyexcel] web下载excel，文件中文名会被替换为下划线，编码问题吗？ utf-8无效 (#291)





  
纠结了好久,发现根本不是编码问题,也许你撞运气好了,但换个环境就又不行了.
 String encodeFilename = URLEncoder.encode(fileName, StandardCharsets.UTF_8.toString());
 这个才是正解.
 赞同，此处正解
  
太棒了，试了好几个，就你这个好使
