### ISSUE TITLE
多列表组合填充，Demo代码中没有ExcelWriter.finish()，运行官网上的Demo代码，生成了一个空文件，加上ExcelWriter.finish()即可

### ISSUE THREAD

**Issue by zhaoyuantt** [alibaba/easyexcel#2911]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
运行官网上多列表组合填充Demo代码，生成的是一个空文件
**建议描述**
加上ExcelWriter.finish()这行代码

**Comment by zhuangjiaju** [comment]
是否使用的是`2.x`的版本？然后看了`3.x`的文档，可以在右上角切换文档的版本。
`3.x`版本用了 `trywithresouce`的语法糖

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
