### ISSUE TITLE
官方文档搜不到registerWriteHandler

### ISSUE THREAD

**Issue by ssssshql** [alibaba/easyexcel#2912]
初学者，想问一下官方文档中写的api是不全的吗，我想要合并某些单元格，网上有代码，但是相关api我没有在官方文档中找到。

**Comment by coderlucifar** [comment]
是啊，我也有这个问题，网上的那些写法都是从哪参考的，想详细学习一下。希望有大佬可以在下面回复

**Comment by zhuangjiaju** [comment]
相对比较全了，后续有空我会继续补充：https://easyexcel.opensource.alibaba.com/docs/current/api/
