### ISSUE TITLE
EasyExcel 模板导出多个sheet,多次导出内存中会存储大量的 DeleteOnExitHook对象，怎么解决

### ISSUE THREAD

**Issue by longteng617** [alibaba/easyexcel#2913]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
这个问题已经在`3.1.2` 版本修复，建议使用最新版本：https://mvnrepository.com/artifact/com.alibaba/easyexcel

**Comment by Zxuxiong** [comment]
![image](https://user-images.githubusercontent.com/20884400/232429679-6aef7e24-46dd-4a30-aadf-b85cb4cfc64a.png)
使用了3.1.2 版本 arthas查看还是每次都会增加
