### ISSUE TITLE
如何实现写出带有合并单元格的excel?

### ISSUE THREAD

**Issue by JohnFantasy** [alibaba/easyexcel#292]
![image](https://user-images.githubusercontent.com/20753038/55451187-725bfd80-5604-11e9-96b7-2b1f8dc6aba8.png)

**Comment by JohnFantasy** [comment]
更新

**Comment by fish7790714** [comment]
先尝试 把xlsx写成这样
![image](https://user-images.githubusercontent.com/18475586/55464169-12c61800-562d-11e9-921e-5d7d7198f84d.png)
然后 调用方法
```java
        writer.merge(0, 2, 1, 1);
        writer.merge(3, 5, 1, 1);
```
这样就可以了，实际使用 可以加上for循环

**Comment by JohnFantasy** [comment]
多谢，已测试，可用，👍
