### ISSUE TITLE
easyexcel 3.1.5 版还不支持嵌套对象的读写？

### ISSUE THREAD

**Issue by 9997766** [alibaba/easyexcel#2921]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述

# 触发Bug的代码
```java
   这里写代码
```
# 提示的异常或者没有达到的效果

**Comment by zhuangjiaju** [comment]
目前不支持 ，后续会规划
