### ISSUE TITLE
复杂EXCEL表格填充求助（多行表格复制填充，求方法、方案

### ISSUE THREAD

**Issue by LeeM-521** [alibaba/easyexcel#2922]
# 暂无代码异常，主要是想求助方案（方法问题）。
目前有个excel数据填充需求，模板表格如下：
![1ba50639f292af0ba3d85329d45b23b](https://user-images.githubusercontent.com/35681383/212597183-11c41f7c-614e-48a5-97d1-6a481ff2507b.png)

数据1,数据2，数据3... 按此模板该如何填充数据，我目前get到的easyExcel方法都只有单行数据的复制插入填充，想问下大佬是有有类似的方案或者方法，谢谢。
第一次发帖求助，见谅。

**Comment by zhuangjiaju** [comment]
2个方案：
1. 直接用table 去操作，不用fill ，参照：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E4%BD%BF%E7%94%A8table%E5%8E%BB%E5%86%99%E5%85%A5
2. 直接用不用easyexcel 用 jxls 另外一个框架，对这种场景兼容的比较好
