### ISSUE TITLE
有需求需要查询大量数据，然后往excel中写入数据按照列写入数据

### ISSUE THREAD

**Issue by martintalor** [alibaba/easyexcel#2925]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
# 问题描述
easyexcel如何按照列写入excel，没有示例文档

**Comment by gongxuanzhang** [comment]
请详细描述问题，最好能附上demo

**Comment by gongxuanzhang** [comment]
按照列写入是什么意思

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
