### ISSUE TITLE
excel模板填充图片,图片属性丢失

### ISSUE THREAD

**Issue by LukeGitHub-xd** [alibaba/easyexcel#2926]
模板:
![image](https://user-images.githubusercontent.com/64684652/213109470-a9773387-1a5b-4f73-a45b-5619ad2bb9fd.png)
导出后:
![image](https://user-images.githubusercontent.com/64684652/213109522-f24372ab-41a1-43b1-b4f1-d44dde1d9b4b.png)

**Comment by lonecloud** [comment]
提供对应的文件模板，方便后续回答，注意数据脱敏

**Comment by lonecloud** [comment]
还有问题，请在提交问题哈，这个issue关闭了哈

**Comment by Chenyl666** [comment]
请问一下，你到导出图片后是如何设置图片的宽度和高度的，我导出的时候，图片都是直接占满了整个单元格，想要把图片缩小一点
