### ISSUE TITLE
版本3.2.0 和2.1.6 导入时一个Excel一个sheet页，触发3次doAfterAllAnalysed

### ISSUE THREAD

**Issue by changyu3590** [alibaba/easyexcel#2929]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/23330829/213679176-b6a9acd5-5066-4a0b-91e9-0830786b7106.png">
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/23330829/213679320-50ad83fd-ddfe-4be1-800b-b58cfb64c9f2.png">
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/23330829/213679400-b7a37225-a3bf-4fc2-b6ea-d7deccdbdc7a.png">
<img width="1743" alt="image" src="https://user-images.githubusercontent.com/23330829/213679810-621a037c-000c-49bf-8c41-4f78e73051a5.png">
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/23330829/213681578-219d0518-af4e-4399-b728-6809134a809e.png">
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/23330829/213681677-3de59d32-4cdf-4ae3-b21b-10db241f8b72.png">
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/23330829/213681705-977f969f-fddb-431d-91e5-83264d2746ae.png">

通过接口导入返利数据，在导入结束后触发了3次doAfterAllAnalysed方法。通过debug发现 读取到了第二个、第三个sheet，但事实是没有的，且第一个sheet页 sheetname也不对。其他版本未测试。

**Comment by gongxuanzhang** [comment]
可以提供一份可复现的demo和excel吗

**Comment by changyu3590** [comment]
附上了关键代码， 里面可以把相关没用的删掉，数据库存储的也可以删掉






                       
原始邮件
                       
                     

发件人："gongxuanzhang"< ***@***.*** &gt;;

发件时间：2023/2/1 15:10

收件人："alibaba/easyexcel"< ***@***.*** &gt;;

抄送人："changyu3590"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [alibaba/easyexcel] 版本3.2.0 和2.1.6 导入时一个Excel一个sheet页，触发3次doAfterAllAnalysed (Issue #2929)




 
可以提供一份可复现的demo和excel吗

**Comment by gongxuanzhang** [comment]
没有excel复现不了

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
