### ISSUE TITLE
关于表头国际化，有什么处理思路么？

### ISSUE THREAD

**Issue by escapeI** [alibaba/easyexcel#293]
看到之前已关闭的issues里，有这样的解释：

> 目前没有类似国际化支持想法，如果真有需要直接写入List这种方式。

如果使用这种方式，就无法实现多表头了吧？

有没有什么其他思路，可以实现国际化呢？

**Comment by escapeI** [comment]
List方式可以实现多表头，但表头merge的工作量偏大。
最终我选择的方式是在 `sheet.setClazz()` 之前，利用反射动态换掉表头数据，也算是曲线救国吧。
实现方式不够优雅，但项目工期紧迫，暂时先用着，之后有时间再优化。

**Comment by Uetty** [comment]
我的思路是考虑修改注解，注解的值设置成继承特定接口的枚举类，枚举类继承的接口对接国际化功能，如这样子
![image](https://user-images.githubusercontent.com/14183559/61627814-506db000-acb3-11e9-8b59-5a844a119010.png)
不过这种方案也不完美
