### ISSUE TITLE
easyExcel导出，前端下载文件流时只有表头没有数据

### ISSUE THREAD

**Issue by sgk102938** [alibaba/easyexcel#2930]
前端vue3：
            const link = document.createElement('a')
            let blob = new Blob([res.data], {type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})
            var fileName = '测试用例.xlsx'
            link.style.display = "none"
            link.href = URL.createObjectURL(blob)
            link.setAttribute('download', fileName)
            document.body.appendChild(link)
            link.click()
            URL.revokeObjectURL(link.href)
            document.body.removeChild(link)
后端controller：
        List<Assess> assesses = assessService.getSpecialSubTaskAssessByNetId(specialSubTaskId);
        response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;chartset=utf-8");
        response.setCharacterEncoding("utf-8");
        try {
            String fileName = URLEncoder.encode("测试用例", "UTF-8").replaceAll("\\+", "%20");
            response.setHeader("Content-disposition", "attachment;filename*=utf-8''" + fileName + ".xlsx");
            EasyExcel.write(response.getOutputStream()).autoCloseStream(Boolean.FALSE).head(Assess.class)
                    .excelType(ExcelTypeEnum.XLSX).sheet("评估表")
                    .doWrite(assesses);
如果直接后端下载成本地文件的话数据是没有问题的，但是返回给前端一下载就出上述问题

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue.
