### ISSUE TITLE
Excel导入，列名称如何先改再匹配，类似正则功能，比如 Excelz中字符串标题（必填）与Java  @ExcelProperty("字符串标题")匹配

### ISSUE THREAD

**Issue by zhaoxj2019** [alibaba/easyexcel#2933]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
# 问题描述
1.使用场景：Excel文件由其他三方生成，Excel文件的表头字段可能与标准导入api定义的字段有所出入，标准api不方便跟随第三方改，第三方众多，也比较难要求，期望能在导入时能对Excel表头进行加工后，再匹配导入。
2.官方Demo中，Excel列名改为字符串标题（必填），   使用如下注解对应
   @ExcelProperty("字符串标题")
    private String string;

如何让 字符串标题（必填）能与string匹配导入（即先加工），使用自定义Listener implements ReadListener，重写 invokeHead不满足，此时AnalysisContext 已按字符串标题（必填）进行解析，字符串标题（必填）列的数据没解析进去

**Comment by gongxuanzhang** [comment]
如果你是的表头是不确定的，你可以读取之后写入成符合你要求的新excel。暂不支持动态

**Comment by gongxuanzhang** [comment]
如果还有其他问题可以重新开启这个Issue
