### ISSUE TITLE
3.0.5版本以后，读取Excel合并单元格不符合预期

### ISSUE THREAD

**Issue by javaDreamDeer** [alibaba/easyexcel#2934]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述

# 触发Bug的代码
```java
   这里写代码
```
# 提示的异常或者没有达到的效果

**Comment by lonecloud** [comment]
请提供对应的代码和说明，方便后续回答

**Comment by lonecloud** [comment]
请提供对应的代码和说明，方便后续回答

**Comment by javaDreamDeer** [comment]
发现是监听器的问题，不是源码问题
