### ISSUE TITLE
生成的xls文件格式和文件扩展名不匹配?

### ISSUE THREAD

**Issue by panzd** [alibaba/easyexcel#2936]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述

使用esayExcel生成xls文件后，在windows下提示如下警告，点击“是”后，能够打开。但如何消掉这个警告，是代码的问题还是生成格式的问题？

![3f942895180e23cebd3b9c1a7c061cfe](https://user-images.githubusercontent.com/19729914/215690790-986fd42b-31ec-452f-9b87-f358f234fe81.jpg)

# 触发Bug的代码
```java
   这里写代码
```
# 提示的异常或者没有达到的效果
文件属性如下:
![1675150541709](https://user-images.githubusercontent.com/19729914/215699105-7f766801-a988-460f-ae6c-334939a1ec48.jpg)

**Comment by zJohny** [comment]
您好，我的问题和您发的这个很相似，本地测试完全无误，部署到Linux上后就会出现扩展名无效的问题，下载过程全程无报错，将扩展名改了以后就可以正常打开，我用的版本是 <version>4.0.3</version>，代码如下
InputStream resourceAsStream = GpCellsController.class.getResourceAsStream("/fill/exceltemplate/模板.xls");
        if (resourceAsStream == null) {
                throw new FileNotFoundException("未找到模板文件");
            }
             try(ExcelWriter excelWriter = EasyExcel.write(response.getOutputStream()).withTemplate(resourceAsStream).excelType(ExcelTypeEnum.XLS).build()){
                 if(maps!=null){
                     maps.forEach(map->{
                        WriteSheet writeSheet1 = EasyExcel.writerSheet("资产负债月报表").build();
                        excelWriter.fill(map, writeSheet1);
                   });
                 }
               
                   }
             String fileNamedownload = "财报详细信息" + System.currentTimeMillis()+".xls";
             log.info("生成的报表名：{}",fileNamedownload);
             response.setContentType("application/vnd.ms-excel");
             response.setCharacterEncoding("utf-8");
             String fileName1= URLEncoder.encode(fileNamedownload,"UTF-8").replaceAll("\\+","%20");
             response.setHeader("Content-disposition","attachment;filename*=utf-8''"+fileName1);
              excelWriter.finish();
             } catch (IOException e) {
                 throw new RuntimeException(e);
             }

**Comment by zJohny** [comment]
![Uploading 扩展名.jpg…]()
