### ISSUE TITLE
大数据量导出的断点续导

### ISSUE THREAD

**Issue by tangdaj** [alibaba/easyexcel#2938]
需求：大数据量前提下，当导出过程中出现程序中断时，可以实现从上一次的位置继续执行。
目前已尝试两种方案：
1、使用Template模板文件，采用本地文件交替写，但是这种方式非常消耗资源最终导致程序挂起，不可用；
2、使用ExcelWriter追加写，这种方式可以解决内存问题但无法获取实时文件，也无法获取xml临时文件。
希望能够提供可行方案，感谢。

**Comment by zhuangjiaju** [comment]
这个目前没法解决问题，写的底层基于poI,poi目前追加文件一定是全部加载到内存。
建议处理方案：将数据放到数据库 或者本地缓存 ，然后最终一次性放到excel里面。
