### ISSUE TITLE
表头自动合并问题

### ISSUE THREAD

**Issue by yeohx** [alibaba/easyexcel#2939]
版本：
<dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>3.0.5</version>
            </dependency>
方法：
 EasyExcel.write(filePath + fileName)
                // 这里放入动态头
                .head(List<List<String>>).sheet(sheetName)
                // 当然这里数据也可以用 List<List<String>> 去传入
                .doWrite();
问题：
List<List<String>> head = [[头1],[头1]].
当head 里面的list 两个头内容相同会自动合并，如何取消自动合并？

**Comment by dardaplanet** [comment]
调用方法automaticMergeHead,设置为false
EasyExcel.write(filePath + fileName).automaticMergeHead(false)

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
