### ISSUE TITLE
导出大文件时，如果出现io异常导出失败，/tmp/poifiles目录下生成的xml临时文件不会删除

### ISSUE THREAD

**Issue by wpj199582** [alibaba/easyexcel#2953]
### 问题描述
  1.excel中1个sheet行上限是1048576，当导出数据行数超过时，会抛出io异常，此时产生的xml临时文件没有删除 
  2.当导出的字段数量比较多时，产生的临时文件占用比较大，下面的Demo中，100万条数据，占用大概1.6g，由于不会删除，因此会逐渐占满系统磁盘空间
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/24318870/216548291-af51f13e-790c-4c07-b324-2a6935be1a71.png">

断点打到最后，发现临时文件没有删除，当程序结束，也就是jvm关闭或者tomcat重启，临时文件才会删除。

<img width="825" alt="image" src="https://user-images.githubusercontent.com/24318870/216547073-db3a0060-134a-42ac-9f8d-bace58ccfb0c.png">

### 测试代码

```java
import com.alibaba.excel.EasyExcel;
import com.alibaba.excel.ExcelWriter;
import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.support.ExcelTypeEnum;
import com.alibaba.excel.util.FileUtils;
import com.alibaba.excel.write.metadata.WriteSheet;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
class DemoData{

    @ExcelProperty(value = "id")
    private String id;

    @ExcelProperty(value = "商品")
    private String commodityName;

    @ExcelProperty(value = "商品2")
    private String commodityName2;

    @ExcelProperty(value = "商品3")
    private String commodityName3;

    @ExcelProperty(value = "商品4")
    private String commodityName4;

    @ExcelProperty(value = "商品5")
    private String commodityName5;

    @ExcelProperty(value = "商品6")
    private String commodityName6;

    @ExcelProperty(value = "商品7")
    private String commodityName7;

    @ExcelProperty(value = "商品8")
    private String commodityName8;

}

public class Testa {

    public static void main(String[] args) {

        System.out.println(FileUtils.getPoiFilesPath());
        String filePath = "/tmp/test.xlsx";
        ExcelWriter writer = EasyExcel.write(filePath).excelType(ExcelTypeEnum.XLSX).build();


        WriteSheet sheet = EasyExcel.writerSheet().head(DemoData.class).build();

        try{
            for (int i = 0; i < 10000; i++) {
                List<DemoData> rowData = new ArrayList<>();

                for (int j = 0; j < 110; j++) {
                    DemoData excelVo = new DemoData();
                    excelVo.setId("" + (i * 110 + j));
                    rowData.add(excelVo);
                }
                writer.write(rowData, sheet);
            }
            writer.finish();
        }catch (Exception e){
            e.printStackTrace();
        }


        System.out.println("导出执行完毕");

    }
}
```

**Comment by zhuangjiaju** [comment]
`            writer.finish();` 需要写到finnal里面去， 或者 用`try with resouce`

**Comment by wpj199582** [comment]
> ` writer.finish();` 需要写到finnal里面去， 或者 用`try with resouce`

试过了，是不行的，你可以试下。
因为writer.write(rowData, sheet)这一步抛出了异常，内部已经调用了一次 writeContextImpl.finish(true),finish标识会被更新成true，后面再主动调用writer.finish()方法，不管是在哪里调用，都执行不到writeContextImpl.finish里面的逻辑了。

<img width="688" alt="image" src="https://user-images.githubusercontent.com/24318870/217774322-5f2c9e42-83c0-4fec-894a-fe50e43f6768.png">

**Comment by WaitRainbow** [comment]
@wpj199582 可以看一下：https://github.com/alibaba/easyexcel/issues/2878#issue-1507165731
这是我之前提的issues，writer.write(rowData, sheet)这一步抛出了异常，内部已经调用了一次 writeContextImpl.finish(true)，finish标识会被更新成true，但是这个writeContextImpl.finish在
大概357行会失败，如图：
![image](https://user-images.githubusercontent.com/51317190/218970044-f463c2f4-0a16-43db-a154-f6cea02098d5.png)

我猜测的原因是，发生异常后，原本应该执行临时文件清理逻辑，可是这个dispose方法内部会有一个flush方法，应该是尝试将流里的数据写到文件中：
![image](https://user-images.githubusercontent.com/51317190/218970472-20d6c9ef-f13a-44d8-ab1f-ad4fd0161b7a.png)

那么问题来了，我们遇到的是IO异常已经不支持往文件中写入数据了，于是这个dispose方法就会再次抛出一个IO异常，dispose方法中删除临时文件的逻辑都还没来得及执行。而且像你所说的，我们再手动调用writer.finish()方法也没用了，永远无法执行到临时文件的删除逻辑。

**Comment by wpj199582** [comment]
> 所以这确实是个bug，我现在只能暂时用官方提供的方法，压缩临时文件的大小了~

**Comment by wenPKtalk** [comment]
<img width="932" alt="image" src="https://github.com/alibaba/easyexcel/assets/16517769/a67953d5-4aca-497f-a06e-4d85ed9e97a8">
最新的poi已经修复了这个问题，在pom中排除poi-ooxml这个引用最新的就可以了，是不是？

**Comment by shingle2302** [comment]
> 暂时用官方提供的方法，压缩临时文件的大小了~

什么方法
