### ISSUE TITLE
官方示例读Excel中的读多个sheet:repeatedRead()读全部sheet生成重复数据

### ISSUE THREAD

**Issue by dongguo4812** [alibaba/easyexcel#2955]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
[商品清单.xlsx](https://github.com/alibaba/easyexcel/files/10608657/default.xlsx)

# 触发Bug的代码
ReadTest
```java
 // 读取全部sheet
        // 这里需要注意 DemoDataListener的doAfterAllAnalysed 会在每个sheet读取完毕后调用一次。然后所有sheet都会往同一个DemoDataListener里面写
        EasyExcel.read(fileName, DemoData.class, new DemoDataListener()).doReadAll();

```

DemoDataListener
```java
    /**
     * 所有数据解析完成了 都会来调用
     *
     * @param context
     */
    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
        // 这里也要保存数据，确保最后遗留的数据也存储到数据库
        saveData();
        log.info("所有数据解析完成！");
    }
```
# 提示的异常或者没有达到的效果
读多个sheet时，读取每个sheet都会执行一次doAfterAllAnalysed()，当第一页sheet最后一次循环执行完毕，cachedDataList不足BATCH_COUNT（默认100），执行一次doAfterAllAnalysed()，此时cachedDataList并未清空   读取下一页sheet时，就会产生重复数据

可以在doAfterAllAnalysed方法  saveData()后清空缓存List

**Comment by gongxuanzhang** [comment]
实现SheetWriteHandler执行完手动释放剩余数据即可

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
