### ISSUE TITLE
如何使用easyexcel 添加打印分页符

### ISSUE THREAD

**Issue by fanshengfa** [alibaba/easyexcel#2956]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
# 问题描述

**Comment by gongxuanzhang** [comment]
自定义SheetWriteHandler拦截器，手动设置
```java 
        Sheet sheet = context.getWriteSheetHolder().getSheet();
        //设置在特定行的添加分页符
        sheet.setRowBreak(1);
        //取消excel默认的自动分页,打印时将excel文件打印在pdf的一页中。
        sheet.setAutobreaks(true);
```

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
