### ISSUE TITLE
模板填充后 会空指针报错或导出错乱

### ISSUE THREAD

**Issue by Guoxy0119** [alibaba/easyexcel#2957]
![image](https://user-images.githubusercontent.com/48587424/217156014-e965735f-3f98-45c6-a5c3-be3857f53287.png)
`    @Override
    public void setResponseExportList(HttpServletResponse response, String fileName, String path, List<T> data, Map<String,Object> map) throws IOException {
        // 设置模板
        InputStream inputStream = FileUtil.getResourcesFileInputStream(path);
        ServletOutputStream out = response.getOutputStream();
        response.setContentType("multipart/form-data");
        response.setCharacterEncoding("utf-8");
        response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx");
        //写第一个sheet
        ExcelWriter writer = EasyExcel.write(out)
                .withTemplate(inputStream)
                .excelType(XLSX)
                .needHead(true)
                .build();

        WriteSheet writeSheet = EasyExcel.writerSheet().build();
        FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.TRUE).build();
        writer.fill(data,fillConfig,writeSheet);
        writer.fill(map,writeSheet);
        // 获取当前条件查询结果
        writer.finish();
        out.close();
    }`

`    private void exportCommercialInvoice(TtDeliveryplan deliveryplan, HttpServletResponse response)  throws IOException{
        List<TtDeliveryplanDtl> ttDeliveryplanDtls = ttDeliveryplanDtlMapper.selectForCustomsDeclarationInvoice(deliveryplan);
        if(CollectionUtil.isEmpty(ttDeliveryplanDtls)){
            throw new BaseException(ExceptionEnum.DELIVERY_PLAN_DTL_IS_NULL.getMessage());
        }
        TtDeliveryplanDtl ttDeliveryplanDtl = ttDeliveryplanDtls.get(0);

        //获取贸易国信息
        TmDeliveryplanTradingCountry country = this.getDeliveryplanTradingCountry(ttDeliveryplanDtl);
        //获取销售表单固定定义字段
        TmDeliveryplanFixedFieldSales fixedField = this.getDeliveryplanFixedFieldSales(ttDeliveryplanDtl);

        Map<String,Object> map = new HashMap<>();
        map.put("plantNameEn",ttDeliveryplanDtl.getPlantNameEn());//工厂定义-英文名
        map.put("addressEn",ttDeliveryplanDtl.getAddressEn());//工厂定义-英文地址
        map.put("telPhone",ttDeliveryplanDtl.getTelPhone());//工厂定义-电话
        map.put("fax",ttDeliveryplanDtl.getFax());//工厂定义-传真

        map.put("customerName",ttDeliveryplanDtl.getCustomerName());//买方：客户定义-客户名称
        map.put("deliveryplanNo",ttDeliveryplanDtl.getDeliveryplanNo());//文件号：发货计划-单据号
        map.put("addressAll",ttDeliveryplanDtl.getAddressAll());//地址：销售订单-地址
        map.put("incoterm",ttDeliveryplanDtl.getIncoterm());//交易方式：销售订单-国际贸易术语
        map.put("incotermsTown",ttDeliveryplanDtl.getIncotermsTown());//交易方式：销售订单-国际贸易术语城镇
        map.put("areaCode",country.getAreaCode());//电话区号：title-贸易国
        map.put("contactNumber",ttDeliveryplanDtl.getContactNumber());//电话：客户定义-联系电话
        map.put("confirmDate",ttDeliveryplanDtl.getConfirmDate());//日期：发货计划-点击销售确认按钮的日期

        map.put("currencySystem",country.getCurrencySystem());//币制：贸易国
        map.put("unitCode",ttDeliveryplanDtl.getUnitCode());//单位

        int i = 1;
        BigDecimal totalQty = BigDecimal.ZERO;
        BigDecimal totalPrice = BigDecimal.ZERO;
        for (TtDeliveryplanDtl dtl : ttDeliveryplanDtls) {
            dtl.setIndex(i);
            if(CommonUtil.isEmpty(dtl.getUnitPrice())){
                throw new BaseException(ExceptionEnum.UNIT_PRICE_IS_EMPTY.getMessage(),dtl.getSalesorderNo());
            }
            dtl.setUnitPrice(dtl.getUnitPrice().setScale(3));
            dtl.setAmount(dtl.getUnitPrice().multiply(dtl.getMaterialQty()).setScale(2));//单价*数量
            totalQty = totalQty.add(dtl.getMaterialQty());
            totalPrice = totalPrice.add(dtl.getAmount());
            i++;
        }

        map.put("totalQty",totalQty);//总数
        map.put("totalPrice",totalPrice);//总价

        this.setResponseExportLists(response, "发货计划-商业发票", "template/04-Commercial-Invoice-商业发票.xlsx", ttDeliveryplanDtls,map);

    }`

![image](https://user-images.githubusercontent.com/48587424/217156650-7cd403b5-c5a9-4d56-85d1-3375621e927d.png)
![image](https://user-images.githubusercontent.com/48587424/217156888-67c6d96c-971b-44e3-a32f-d8941534cee5.png)
![image](https://user-images.githubusercontent.com/48587424/217157500-fd8c7762-3660-4d0d-9d7c-2c573dceccb8.png)

这是另外一个模板 下方会有很多样式重复
![image](https://user-images.githubusercontent.com/48587424/217157116-8975ce85-0458-48db-bd97-259849c338ad.png)

麻烦大佬给指点一下

**Comment by zhuangjiaju** [comment]
这个是什么版本？尝试升级到最新版试试

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
