### ISSUE TITLE
监听器中BATCH_COUNT值的定义

### ISSUE THREAD

**Issue by 001221211** [alibaba/easyexcel#2960]
监听器中BATCH_COUNT值在大批量导入的时候（10w条起步）怎么定义是合适的？之前我定义为10000的时候插入10w条数据很慢，修改为100000后再次插入10w条数据速度变快了许多，请问是越大越好吗？这个值对程序的影响都有哪些呢？

**Comment by zhuangjiaju** [comment]
这个需要自己设定，具体什么值对easyexcel影响不是很大，要根据数据库的性能来。
