### ISSUE TITLE
Excel填充list合并单元格边框线格式不能正确生成

### ISSUE THREAD

**Issue by LukeGitHub-xd** [alibaba/easyexcel#2963]
![image](https://user-images.githubusercontent.com/64684652/217723839-d3ce46d2-88bb-495b-ae43-ea12c1d6d2b0.png)
`    @Override
    protected void merge(Sheet sheet, Cell cell, Head head, Integer relativeRowIndex) {
        if (relativeRowIndex == null || relativeRowIndex == 0) {
            return;
        }
        int rowIndex = cell.getRowIndex();
        int colIndex = cell.getColumnIndex();
        sheet = cell.getSheet();
        Row preRow = sheet.getRow(rowIndex - 1);
        //获取上一行的该格
        Cell preCell = preRow.getCell(colIndex);
        List<CellRangeAddress> list = sheet.getMergedRegions();
        CellStyle cellStyle = preCell.getCellStyle();
        cell.setCellStyle(cellStyle);
        for (CellRangeAddress cellRangeAddress : list) {
            if (cellRangeAddress.containsRow(preCell.getRowIndex()) && cellRangeAddress.containsColumn(preCell.getColumnIndex())) {
                int lastColIndex = cellRangeAddress.getLastColumn();
                int firstColIndex = cellRangeAddress.getFirstColumn();
                CellRangeAddress cra = new CellRangeAddress(cell.getRowIndex(), cell.getRowIndex(), firstColIndex, lastColIndex);
                sheet.addMergedRegion(cra);
                if (preCell.getStringCellValue().equalsIgnoreCase("2023-01-16")) {
                    String stringCellValue = preCell.getStringCellValue();
                }
                RegionUtil.setBorderBottom(cellStyle.getBorderBottom(), cra, sheet);
                RegionUtil.setBorderLeft(cellStyle.getBorderLeft(), cra, sheet);
                RegionUtil.setBorderRight(cellStyle.getBorderRight(), cra, sheet);
                RegionUtil.setBorderTop(cellStyle.getBorderTop(), cra, sheet);
                return;
            }
        }
    }`

**Comment by LukeGitHub-xd** [comment]
上面的代码有点问题
` @Override
    protected void merge(Sheet sheet, Cell cell, Head head, Integer relativeRowIndex) {
        if (relativeRowIndex == null || relativeRowIndex == 0) {
            return;
        }
        int rowIndex = cell.getRowIndex();
        int colIndex = cell.getColumnIndex();
        sheet = cell.getSheet();
        Row preRow = sheet.getRow(rowIndex - 1);
        //获取上一行的该格
        Cell preCell = preRow.getCell(colIndex);
        List<CellRangeAddress> list = sheet.getMergedRegions();
        CellStyle cellStyle = preCell.getCellStyle();
        cell.setCellStyle(cellStyle);
        for (CellRangeAddress cellRangeAddress : list) {
            if (cellRangeAddress.containsRow(preCell.getRowIndex()) && cellRangeAddress.containsColumn(preCell.getColumnIndex())) {
                int lastColIndex = cellRangeAddress.getLastColumn();
                int firstColIndex = cellRangeAddress.getFirstColumn();
                CellRangeAddress cra = new CellRangeAddress(cell.getRowIndex(), cell.getRowIndex(), firstColIndex, lastColIndex);
                sheet.addMergedRegion(cra);
                RegionUtil.setBorderBottom(cellStyle.getBorderBottom(), cra, sheet);
                RegionUtil.setBorderLeft(cellStyle.getBorderLeft(), cra, sheet);
                RegionUtil.setBorderRight(cellStyle.getBorderRight(), cra, sheet);
                RegionUtil.setBorderTop(cellStyle.getBorderTop(), cra, sheet);
                return;
            }
        }
    }`

**Comment by zhuangjiaju** [comment]
具体是哪个符合期望？

**Comment by LukeGitHub-xd** [comment]
合并单元格框线颜色,部分和模板中的不一样
当前为:
![image](https://user-images.githubusercontent.com/64684652/217973949-2100631f-c14b-4a12-b98d-68e34627e241.png)
期望:合并单元格填充list后后面每一行都和第一行一样的框线样式
![image](https://user-images.githubusercontent.com/64684652/217974379-13e976b2-b982-468d-8b5d-c9d7e760e441.png)

**Comment by pandyzh** [comment]
`@Override
	protected void merge(Sheet sheet, Cell cell, Head head, Integer relativeRowIndex) {
		if (relativeRowIndex == null || relativeRowIndex == 0) {
			return;
		}
		int rowIndex = cell.getRowIndex();
		int colIndex = cell.getColumnIndex();
		Sheet thisSheet = cell.getSheet();
		Row preRow = thisSheet.getRow(rowIndex - 1);
		Row thisRow = thisSheet.getRow(rowIndex);
		Cell preCell = preRow.getCell(colIndex);// 获取上一行的该格
		Cell tmpCell = cell;
		List<CellRangeAddress> list = thisSheet.getMergedRegions();

		for (int i = 0; i < list.size(); i++) {
			CellRangeAddress cellRangeAddress = list.get(i);
			if (cellRangeAddress.containsRow(preCell.getRowIndex()) && cellRangeAddress.containsColumn(preCell.getColumnIndex())) {
				int lastColIndex = cellRangeAddress.getLastColumn();
				int firstColIndex = cellRangeAddress.getFirstColumn();
				CellRangeAddress cra = new CellRangeAddress(cell.getRowIndex(), cell.getRowIndex(), firstColIndex, lastColIndex);
				thisSheet.addMergedRegion(cra);
				for (int j = firstColIndex; j <= lastColIndex; j++) {
					preCell = preRow.getCell(j);// 获取上一行的该格
					tmpCell = thisRow.getCell(j);
					if (tmpCell == null) {
						tmpCell = thisRow.createCell(j);
					}
					tmpCell.setCellStyle(preCell.getCellStyle());
				}
				return;
			}
		}`


`	@Override
	public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, List<WriteCellData<?>> cellDataList, Cell cell,
			Head head, Integer relativeRowIndex, Boolean isHead) {
		if (relativeRowIndex == null) {
			return;
		}

		// 复制第一行的单元格式
		if (relativeRowIndex > 0) {
			Sheet thisSheet = cell.getSheet();
			Row preRow = thisSheet.getRow(cell.getRowIndex() - 1);
			Cell preCell = preRow.getCell(cell.getColumnIndex());// 获取上一行的该格
			cell.setCellStyle(preCell.getCellStyle());
		}

	}`

我是通过注册一个mergeStrategy和一个CellWriteHandler 来解决这个问题

**Comment by LukeGitHub-xd** [comment]
多谢,完美解决了,
我自己只能解决到这样了
![image](https://user-images.githubusercontent.com/64684652/219525691-9f5c704c-1cd4-4f2d-94d2-01e88a47033d.png)
