### ISSUE TITLE
3.1.1版本用String类型的字段读取整数内容的单元格时就会自动加 .0，将版本升级到3.2.0就没这个问题了

### ISSUE THREAD

**Issue by hbisbest** [alibaba/easyexcel#2964]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述

# 触发Bug的代码
```java
   这里写代码
```
# 提示的异常或者没有达到的效果

**Comment by zhuangjiaju** [comment]
请使用最新版
