### ISSUE TITLE
使用模板填充时，给某个sheet设置自定义拦截器进行字体颜色设置，不生效，目前使用3.2.1版本

### ISSUE THREAD

**Issue by yishanyishan100** [alibaba/easyexcel#2967]
![image](https://user-images.githubusercontent.com/52208028/218362615-0cffebf6-b681-4eb1-91b3-81323dbf7b91.png)
![image](https://user-images.githubusercontent.com/52208028/218362884-bbe7068f-b7e6-4c94-b597-d0d12b56d7f9.png)

**Comment by yishanyishan100** [comment]
已解决

**Comment by ycl19971207** [comment]
能咨询一下怎么解决的吗

**Comment by Kiderfly** [comment]
怎么解决的？
