### ISSUE TITLE
文件导入，单元格内容首尾是有空格的，代码读取后默认是没空格的

### ISSUE THREAD

**Issue by javassm** [alibaba/easyexcel#2969]
# 异常代码
![image](https://user-images.githubusercontent.com/28971156/218437846-2e2ce326-8e18-42b7-9450-262dda7a5963.png)

![image](https://user-images.githubusercontent.com/28971156/218439234-759a4b8e-72e5-44b1-9ed3-89c7fbed53c7.png)

# 问题描述
空格存在有业务价值的，代码默认去除空格，对原文件内容做了修改，这个行为不能是默认行为吧

**Comment by lonecloud** [comment]
还有问题，请在提交问题哈，这个issue关闭了哈
