### ISSUE TITLE
复杂头写入怎么不分成两行表头呢

### ISSUE THREAD

**Issue by sven-chan** [alibaba/easyexcel#2973]
![企业微信截图_1a0b09fe-e552-4cbc-8df9-645aff584b33](https://user-images.githubusercontent.com/59336272/218667540-7d29fe9d-4905-474e-b925-51ed5e29cad0.png)
想去掉第二行的表头，实现只有个表头，下面对应多个字段的形式。

**Comment by gongxuanzhang** [comment]
你思考一下没有表头程序是怎么把列对应起来的

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue.
