### ISSUE TITLE
读数据时，自定义转换器 Converter 中 contentProperty 无法获取到 contentFontProperty 等字体样式属性

### ISSUE THREAD

**Issue by ilwyiworld** [alibaba/easyexcel#2974]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/7789175/218672229-1fdc0619-5ca4-4985-9e61-97e4f5201259.png">

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/7789175/218672349-87ce2971-eff4-4d85-abe5-e94c73005281.png">

如图，这几个属性都为空，怎么才能在读数据时候获取字体样式等属性

**Comment by ilwyiworld** [comment]
版本 3.2.1

**Comment by gongxuanzhang** [comment]
实现CellWriteHandler 在过程中手动获取。

**Comment by ilwyiworld** [comment]
> 

所以读 Excel 的时候就是获取不到这些属性是吧，只有写数据的时候手动设置？

**Comment by gongxuanzhang** [comment]
> > 
> 
> 所以读 Excel 的时候就是获取不到这些属性是吧，只有写数据的时候手动设置？

是的
