### ISSUE TITLE
有没有 分析 性能的方法或者 思路

### ISSUE THREAD

**Issue by ChewJ404** [alibaba/easyexcel#2975]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述

## 导出数据 10w条 ，76列 花费15分钟
当中 用到了 1个 Handler  设置  首列 序号 ，和 9个字段用了 自定义 converter 转换格式 ，请问下大佬 ，如何分析 耗时点在哪
然后针对性的优化 ，

翻变了 官方文档 以及 issues ，没有找到 介绍如何  优化的 建议

**Comment by ChewJ404** [comment]
版本 3.2

**Comment by gongxuanzhang** [comment]
如果你代码很干净可能没有其他办法.
如果你的长时间是因为频繁gc导致
你可以尝试分批写入释放空间或者调大heap。
建议测试时候打印gclog 分析一下 。
如果确定没问题那可能优化空间不大
导出的话可能更多的还是要从业务做一个任务处理。

**Comment by ChewJ404** [comment]
> 如果你代码很干净可能没有其他办法. 如果你的长时间是因为频繁gc导致 你可以尝试分批写入释放空间或者调大heap。 建议测试时候打印gclog 分析一下 。 如果确定没问题那可能优化空间不大 导出的话可能更多的还是要从业务做一个任务处理。

非常感谢 ，查了下gc 还是很正常， 粗略算了下 每秒钟 画8000-1w个格子

**Comment by gongxuanzhang** [comment]
那估计只能从业务角度做一个延迟下载了
