### ISSUE TITLE
同步读Excel无法忽略异常

### ISSUE THREAD

**Issue by revprogramer** [alibaba/easyexcel#2977]
SyncReadListener的onException抛出异常导致doReadSync异常无法被忽略

**Comment by gongxuanzhang** [comment]
onException是捕获异常时的兜底策略。
你需要控制这个逻辑不出异常或者在方法中处理异常。
同理当你使用JDK的String.format() 作为模板当成异常信息  也可能再次抛出异常，这种情况需要你自己做处理

**Comment by wangxfholly** [comment]
自己怎么处理
