### ISSUE TITLE
模板填充支持操作复选框吗

### ISSUE THREAD

**Issue by SmileCocc** [alibaba/easyexcel#2979]
# 问题描述
![image](https://user-images.githubusercontent.com/57064716/219233935-11882858-db41-4825-9115-f63ac0c00dd9.png)

模板中带有大量的复选框,填充模板时该怎样做才能使模板正常勾选中呢？

**Comment by gongxuanzhang** [comment]
通过实现CellWriteHandler 或者RowWriteHandler  用POI api实现

**Comment by gongxuanzhang** [comment]
理论上poi能实现的都可以用拦截器实现

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
