### ISSUE TITLE
excel读取会计专用格式单元格问题咨询

### ISSUE THREAD

**Issue by shadowShui** [alibaba/easyexcel#2981]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述
excel单元格为会计专用格式的时候，如：excel单元格格式为_ * #,##0.00_ ;_ * -#,##0.00_ ;_ * "-"??_ ;_ @_ 。此时数据使用string接收。excel中的0读取进来会变成 - 0。负数-0.01读取进来会变成 (0.01)，同时如果格式中带有￥也会读取进来，有办法能在读取的时候适配单元格格式，自动进行转换吗？

**Comment by gongxuanzhang** [comment]
可以自定义解析器Converter

**Comment by gongxuanzhang** [comment]
如果你需要更详细的解释你可以贴上你的代码和excel例子，写出你的需求 我给你写个demo

**Comment by shadowShui** [comment]
转换器的问题已经解决了，感谢

**Comment by shadowShui** [comment]
再多请教一下，EasyExcel现在 ExcelProperty注解有多个value的时候，还是只能读取最后一个value作为实际值是吗？如果我这个单元格的表头是变幻的，同时列的顺序也不是固定的，并且我还需要使用转换器，无法使用Map作为接收的返回值，请问这个时候应该如何处理呢？

**Comment by gongxuanzhang** [comment]
额，我有点没听懂。。  能举个例子吗

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
