### ISSUE TITLE
读取excel 时，最后列无数据，获取到的数据data，在 Map<Integer, String>mao

### ISSUE THREAD

**Issue by ashengjiang** [alibaba/easyexcel#2982]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述

**Comment by lonecloud** [comment]
重复提交#2983 关闭其中一个，后续关注
