### ISSUE TITLE
读取excel 时，最后列无数据，获取到的数据data，在 Map<Integer, String>map中没有显示null

### ISSUE THREAD

**Issue by ashengjiang** [alibaba/easyexcel#2983]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
         String         fileName       = "/Users/jiangasheng/Desktop/太湖县人民医院_doc_郭彤彤_v1.0_20230209.xlsx";
        HeaderListener headerListener = new HeaderListener();
        EasyExcel.read(fileName, headerListener).sheet().autoTrim(true).doRead();
        Map<Integer, String> headMap = headerListener.getHeadMap();
        for (Map.Entry<Integer, String> entry : headMap.entrySet()) {
            System.out.println("Key = " + entry.getKey() + ", Value = " + entry.getValue());
        }
        log.info("headMap  size = {}", headMap.size());

        Map<Integer, String> headMap1 = headerListener.getFirstData();
        log.info("data  size = {}", headMap1.size());
        for (Map.Entry<Integer, String> entry : headMap1.entrySet()) {
            System.out.println("Key = " + entry.getKey() + ", Value = " + entry.getValue());
        }
```
# 异常提示
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/83191832/219292861-3ba4fe16-fd65-4332-af04-bdf752637a98.png">

# 问题描述
请问，如何在data中填充最后一列数据（null）

**Comment by lonecloud** [comment]
由于为最后一行
有如下几个解决方案
1. 将HeaderListener中的解析类型从Map<Integer,Object>类型改成JavaBean
2. 在HeaderListener中判断invoke数据，如数据key值不等，则进行数据填充。

**Comment by lonecloud** [comment]
还有问题，请在提交问题哈，这个issue关闭了哈

**Comment by xiaoqi951109** [comment]
我出现的是同样的问题 之前用3.0.5版本就是正常的，  现在的话 最后一列 如果无值的话，invoke 里面那一行就会少一个最后的null。这感觉像是一个bug   抱歉 您之前回复的原因和方案 我没有理解  @lonecloud  
![image](https://user-images.githubusercontent.com/14103130/231729220-a64c54e3-9e6a-41ff-93ce-7f2d9bccafe5.png)
![image](https://user-images.githubusercontent.com/14103130/231729302-028ac895-0270-429e-b4dc-3affff74c048.png)
