### ISSUE TITLE
使用LongestMatchColumnWidthStyleStrategy设置自动列宽

### ISSUE THREAD

**Issue by sWhite01111** [alibaba/easyexcel#2985]
# 触发场景描述
使用LongestMatchColumnWidthStyleStrategy设置excel自动列宽时，发现当列数据比较长的时候，还是会展示不全

# 触发Bug的代码
```java
    ExcelWriter excelWriter = EasyExcel.write(outputStream).head(header).registerWriteHandler(new LongestMatchColumnWidthStyleStrategy()).build();
        WriteSheet sheet = EasyExcel.writerSheet("data").build();
```
# 提示的异常或者没有达到的效果
![image](https://user-images.githubusercontent.com/17489600/219345688-26d76bc7-8d6f-4f5f-a355-33feb9cc379a.png)
数据比较长的时候，还是展示不全，比如统计日期这一列

**Comment by gongxuanzhang** [comment]
自动列宽确实是不太精确
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E8%87%AA%E5%8A%A8%E5%88%97%E5%AE%BD%E4%B8%8D%E5%A4%AA%E7%B2%BE%E7%A1%AE
官网写了的

**Comment by gongxuanzhang** [comment]
如果需要很精确可以自己手动指定

**Comment by 15526441465** [comment]
> 如果需要很精确可以自己手动指定

使用自动列宽，然后单独对某几个固定长度的字段使用 @ColumnWidth(50)指定宽度时。全部字段的自动列宽失效，这怎么弄？
