### ISSUE TITLE
Excel中的TRUE 变成了Java中的 true

### ISSUE THREAD

**Issue by w3n9** [alibaba/easyexcel#2987]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
 List<Map<Integer, String>> recordList = EasyExcel
      .read(in)
      .readDefaultReturn(ReadDefaultReturnEnum.STRING)
      .sheet(0).headRowNumber(0).doReadSync();
```
# 异常提示
无异常
# 问题描述
Excel中某一列单元格格式为General，值为TRUE
读取到内存中后为true

**Comment by w3n9** [comment]
https://easyexcel.opensource.alibaba.com/docs/current/api/#readworkbook
![image](https://user-images.githubusercontent.com/26791803/219544330-0ef89bee-9902-46a9-93ab-3cc94e094f28.png)

**Comment by gongxuanzhang** [comment]
这个是因为解析器的缘故，目前版本可能需要你自己使用实体进行操作。

**Comment by liumengyang-or** [comment]
单元格格式为General的时候，TRUE会被当做boolean类型来解析。

下面是从解压以后的xml中提取的TRUE对应的单元格格式：
`<c r="D1" t="b">`
对单元格的解析如下：
这是一个Excel电子表格中的单元格，其中包含一个数据项，具体解释如下：
<c> 是单元格标记；
r="D1" 表示该单元格位于第四行第一列（D1）；
t="b" 表示该单元格中的数据类型为布尔型（boolean），即true或false。

EasyExcel会按照.readDefaultReturn(ReadDefaultReturnEnum.STRING) 这个配置，把boolean类型的值转换为String类型，以下是转换器代码：BooleanStringConverter
`package com.alibaba.excel.converters.booleanconverter;

import com.alibaba.excel.converters.Converter;
import com.alibaba.excel.enums.CellDataTypeEnum;
import com.alibaba.excel.metadata.GlobalConfiguration;
import com.alibaba.excel.metadata.data.ReadCellData;
import com.alibaba.excel.metadata.data.WriteCellData;
import com.alibaba.excel.metadata.property.ExcelContentProperty;

/**
 * Boolean and string converter
 *
 * @author Jiaju Zhuang
 */
public class BooleanStringConverter implements Converter<Boolean> {

    @Override
    public Class<?> supportJavaTypeKey() {
        return Boolean.class;
    }

    @Override
    public CellDataTypeEnum supportExcelTypeKey() {
        return CellDataTypeEnum.STRING;
    }

    @Override
    public Boolean convertToJavaData(ReadCellData<?> cellData, ExcelContentProperty contentProperty,
        GlobalConfiguration globalConfiguration) {
        return Boolean.valueOf(cellData.getStringValue());
    }

    @Override
    public WriteCellData<?> convertToExcelData(Boolean value, ExcelContentProperty contentProperty,
        GlobalConfiguration globalConfiguration) {
        return new WriteCellData<>(value.toString());
    }

}`


解决方式是：把单元格的格式调整为文本类型

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
