### ISSUE TITLE
easyexcel 导出csv 格式文件时，表头是中文乱码

### ISSUE THREAD

**Issue by jasonliujiang** [alibaba/easyexcel#2991]
导出写文件时已经指定编码和 csv 类型。但是表头出现乱码
EasyExcel.write(httpResponse.getOutputStream(), BucketExcelInfoDTO.class)
                    .excelType(ExcelTypeEnum.CSV)
                    .charset(Charset.forName("UTF-8"))
                    .sheet("buckets")
                    .doWrite(bucketExcelInfoDTOList);

是导出 csv 类型文件，不能使用@ExcelProperty注解来实现吗？

**Comment by gongxuanzhang** [comment]
我用windows和Mac测试都没问题  
@ExcelProperty直接加在实体类是可以的呀   
```
 @Data
    public static class BucketExcelInfoDTO{
        @ExcelProperty("名字")
        private String name;
        @ExcelProperty("年龄")
        private int age;
    }
```

**Comment by gongxuanzhang** [comment]
移步私聊，这个issue关闭了
