### ISSUE TITLE
依赖org.apache.commons:commons-compress:1.19 漏洞

### ISSUE THREAD

**Issue by zhangbp** [alibaba/easyexcel#2992]
![image](https://user-images.githubusercontent.com/49581279/220226298-7572fe63-c107-4e99-bb1b-7c5e4aefb65f.png)

**Comment by GitHanter** [comment]
Upgrade POI 版本到最新版本5.2.3

**Comment by zhangbp** [comment]
能否下一个版本在easyexcel中直接升级，不需要额外引入

**Comment by zhangbp** [comment]
![image](https://user-images.githubusercontent.com/49581279/220241302-fb6ea857-b62a-4148-b76e-793c6a9acf7f.png)
需要同时引入poi和poi-ooxml，能否下个版本直接在easyexcel修复引入

**Comment by zhangbp** [comment]
> 升级兴趣点版本到最新版本5.2.3
![220241302-fb6ea857-b62a-4148-b76e-793c6a9acf7f](https://user-images.githubusercontent.com/49581279/221099507-f1448583-e2f2-45fe-a821-3905b2dabe0e.png)

需要同时引入poi和poi-ooxml，能否下个版本直接在easyexcel修复引入

**Comment by xiohuchi** [comment]
能否下个版本，直接在easyexcel，引入高一点的依赖

**Comment by psxjoy** [comment]
Hi, we have an update to poi-5！
This issue has been completed, I will close this issue.
