### ISSUE TITLE
有没有那种插入完所有数据 在自定义插入一行的处理器方法

### ISSUE THREAD

**Issue by zswdgithub** [alibaba/easyexcel#2994]

**Comment by zswdgithub** [comment]
@zhuangjiaju

**Comment by gongxuanzhang** [comment]
你可以直接实现WorkbookWriteHandler 
在afterWorkbookDispose方法中拿到Sheet手动插入
或者使用模板填充的方式在最后一行写下你需要的内容
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/fill#%E5%A4%8D%E6%9D%82%E7%9A%84%E5%A1%AB%E5%85%85

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
