### ISSUE TITLE
使用自动换行导出的excel文件会提示错误

### ISSUE THREAD

**Issue by xiaomaidang** [alibaba/easyexcel#2995]
//在填充完多结果数据后，要强制换行，不然后续的单结果数据会发生覆盖现象
		FillConfig fillConfig = FillConfig.builder().forceNewRow(true).build();

		// 填充
		excelWriter.fill(productDevVo,writeSheet);
		excelWriter.fill(new FillWrapper("item",productDevItemVoList),fillConfig,writeSheet);
		excelWriter.fill(new FillWrapper("rep",productDevItemReplVoList),fillConfig,writeSheet);

**Comment by xiaomaidang** [comment]
补充一下

**Comment by xiaomaidang** [comment]
![代码](https://user-images.githubusercontent.com/105032697/220254584-837c6b36-9ae7-4da5-b684-ed320e6850d6.jpg)
![打开文件的异常](https://user-images.githubusercontent.com/105032697/220254586-a3761aeb-f2b2-4790-9cd4-3b0ed61ff15b.jpg)
![错误的地方](https://user-images.githubusercontent.com/105032697/220254593-12ac26f8-9f2b-4c6d-ba3a-d6f73eaee277.jpg)
![应该是正确的地方](https://user-images.githubusercontent.com/105032697/220254595-8aea561b-d7e0-46c4-a833-fb4c657e74a4.jpg)
[导出的数据.xlsx](https://github.com/alibaba/easyexcel/files/10789848/default.xlsx)
[这是模板.xlsx](https://github.com/alibaba/easyexcel/files/10789849/default.xlsx)

**Comment by xiaomaidang** [comment]
HttpServletResponse response = WebUtils.getResponse();
		response.setContentType("application/vnd.ms-excel; charset=utf-8");
		response.setCharacterEncoding("utf-8");
		String fileName = URLEncoder.encode("excel", "UTF-8").replaceAll("\\+", "%20");
		response.setHeader("Content-disposition", "attachment;filename*=utf-8''" + fileName + ".xlsx");

		File file = ResourceUtils.getFile("classpath:template/importDev.xlsx");

		ExcelWriterBuilder writerBuilder = EasyExcel
				.write(response.getOutputStream())
				.withTemplate(file);

		WriteSheet writeSheet = writerBuilder.sheet().build();
		ExcelWriter excelWriter = writerBuilder.build();

		ProductDevVo productDevVo= getProductDevById(id);

		List<ProductDevItemVo> productDevItemVoList=getProductItemList(id);
	
		List<String> rePIds=productDevItemVoList.stream().map(ProductDevItemVo::getId).collect(Collectors.toList());
		List<ProductDevItemReplVo> productDevItemReplVoList=getProductRepl(rePIds);

		//在填充完多结果数据后，要强制换行，不然后续的单结果数据会发生覆盖现象
		FillConfig fillConfig = FillConfig.builder().forceNewRow(true).build();

		// 填充
		excelWriter.fill(productDevVo,writeSheet);
		excelWriter.fill(new FillWrapper("item",productDevItemVoList),fillConfig,writeSheet);
		excelWriter.fill(new FillWrapper("rep",productDevItemReplVoList),fillConfig,writeSheet);

		//调用finish方法
		excelWriter.finish();

**Comment by xiaomaidang** [comment]
HttpServletResponse response = WebUtils.getResponse();
		response.setContentType("application/vnd.ms-excel; charset=utf-8");
		response.setCharacterEncoding("utf-8");
		String fileName = URLEncoder.encode("excel", "UTF-8").replaceAll("\\+", "%20");
		response.setHeader("Content-disposition", "attachment;filename*=utf-8''" + fileName + ".xlsx");

		File file = ResourceUtils.getFile("classpath:template/importDev.xlsx");

		ExcelWriterBuilder writerBuilder = EasyExcel
				.write(response.getOutputStream())
				.withTemplate(file);

		WriteSheet writeSheet = writerBuilder.sheet().build();
		ExcelWriter excelWriter = writerBuilder.build();

		ProductDevVo productDevVo= getProductDevById(id);

		List<ProductDevItemVo> productDevItemVoList=getProductItemList(id);
	
		List<String> rePIds=productDevItemVoList.stream().map(ProductDevItemVo::getId).collect(Collectors.toList());
		List<ProductDevItemReplVo> productDevItemReplVoList=getProductRepl(rePIds);

		//在填充完多结果数据后，要强制换行，不然后续的单结果数据会发生覆盖现象
		FillConfig fillConfig = FillConfig.builder().forceNewRow(true).build();

		// 填充
		excelWriter.fill(productDevVo,writeSheet);
		excelWriter.fill(new FillWrapper("item",productDevItemVoList),fillConfig,writeSheet);
		excelWriter.fill(new FillWrapper("rep",productDevItemReplVoList),fillConfig,writeSheet);

		//调用finish方法
		excelWriter.finish();

**Comment by xiaomaidang** [comment]
HttpServletResponse response = WebUtils.getResponse();
response.setContentType("application/vnd.ms-excel; charset=utf-8");
response.setCharacterEncoding("utf-8");
String fileName = URLEncoder.encode("excel", "UTF-8").replaceAll("\\+", "%20");
response.setHeader("Content-disposition", "attachment;filename*=utf-8''" + fileName + ".xlsx");

File file = ResourceUtils.getFile("classpath:template/importDev.xlsx");

ExcelWriterBuilder writerBuilder = EasyExcel
				.write(response.getOutputStream())
				.withTemplate(file);

WriteSheet writeSheet = writerBuilder.sheet().build();
ExcelWriter excelWriter = writerBuilder.build();

ProductDevVo productDevVo= getProductDevById(id);

List<ProductDevItemVo> productDevItemVoList=getProductItemList(id);
	
List<String> rePIds=productDevItemVoList.stream().map(ProductDevItemVo::getId).collect(Collectors.toList());
List<ProductDevItemReplVo> productDevItemReplVoList=getProductRepl(rePIds);

		//在填充完多结果数据后，要强制换行，不然后续的单结果数据会发生覆盖现象
		FillConfig fillConfig = FillConfig.builder().forceNewRow(true).build();

		// 填充
		excelWriter.fill(productDevVo,writeSheet);
		excelWriter.fill(new FillWrapper("item",productDevItemVoList),fillConfig,writeSheet);
		excelWriter.fill(new FillWrapper("rep",productDevItemReplVoList),fillConfig,writeSheet);

		//调用finish方法
		excelWriter.finish();

**Comment by xiaomaidang** [comment]
HttpServletResponse response = WebUtils.getResponse();
		response.setContentType("application/vnd.ms-excel; charset=utf-8");
		response.setCharacterEncoding("utf-8");
		String fileName = URLEncoder.encode("excel", "UTF-8").replaceAll("\\+", "%20");
		response.setHeader("Content-disposition", "attachment;filename*=utf-8''" + fileName + ".xlsx");

		File file = ResourceUtils.getFile("classpath:template/importDev.xlsx");

		ExcelWriterBuilder writerBuilder = EasyExcel
				.write(response.getOutputStream())
				.withTemplate(file);

		WriteSheet writeSheet = writerBuilder.sheet().build();
		ExcelWriter excelWriter = writerBuilder.build();

		ProductDevVo productDevVo= getProductDevById(id);

		List<ProductDevItemVo> productDevItemVoList=getProductItemList(id);
	
		List<String> rePIds=productDevItemVoList.stream().map(ProductDevItemVo::getId).collect(Collectors.toList());
		List<ProductDevItemReplVo> productDevItemReplVoList=getProductRepl(rePIds);

		//在填充完多结果数据后，要强制换行，不然后续的单结果数据会发生覆盖现象
		FillConfig fillConfig = FillConfig.builder().forceNewRow(true).build();

		// 填充
		excelWriter.fill(productDevVo,writeSheet);
		excelWriter.fill(new FillWrapper("item",productDevItemVoList),fillConfig,writeSheet);
		excelWriter.fill(new FillWrapper("rep",productDevItemReplVoList),fillConfig,writeSheet);

		//调用finish方法
		excelWriter.finish();

**Comment by xiaomaidang** [comment]
完整代码

**Comment by gongxuanzhang** [comment]
贴一份完整代码或者给一个demo
