### ISSUE TITLE
我只能得到json格式的字符串，没有固定结构的实体类对应，能用esayexcel生成excel吗？

### ISSUE THREAD

**Issue by wangwufan** [alibaba/easyexcel#2999]
# 问题描述
如题，项目里数据结构是不固定的，官方文档里 写入的数据都有对应的实体类，比如DemoData ，我说的情况貌似没有，Map我试过了不好使。老师们能给个思路吗？只要把下面这个json字符串生成excel：
`[{"字段1":"值1","字段2":"值2"},{"字段1":"值3","字段2":"值4"}]`

**Comment by lonecloud** [comment]
可参考`com.alibaba.easyexcel.test.demo.write.WriteTest#dynamicHeadWrite`这个进行处理

**Comment by lonecloud** [comment]
还有问题，请再提交问题哈，这个issue关闭了哈
