### ISSUE TITLE
中文问题

### ISSUE THREAD

**Issue by JunfengL** [alibaba/easyexcel#30]
![image](https://user-images.githubusercontent.com/23209144/41161053-0c264c36-6b64-11e8-8bc0-03f63abf49b0.png)

![image](https://user-images.githubusercontent.com/23209144/41161036-fd21df98-6b63-11e8-9e0a-0f5069bd3482.png)

为什么这个解析成了这样？

**Comment by JunfengL** [comment]
文件是xlsx

**Comment by zhangyb0404** [comment]
请问你解决了吗  我也碰到这个问题了  个别字段解析出来的是乱码

**Comment by jipengfei-jpf** [comment]
最近版本已解决
