### ISSUE TITLE
可不可以考虑以支持带图导出吗

### ISSUE THREAD

**Issue by lurkerw** [alibaba/easyexcel#300]
![无标题](https://user-images.githubusercontent.com/38005052/55766847-0caabe00-5aa9-11e9-91c8-3c250b732e45.png)

**Comment by Bleach4Ever** [comment]
有文件服务器地址的话，改一下就可以了吧

**Comment by zhuangjiaju** [comment]
非常感谢您的意见。请升级到最新版本，最新版本已经支持。
