### ISSUE TITLE
HeadFontStyle设置 color=10(红色)，只在A字段上标识了。但是A字段后面的所有字段都变成红色了。这是系统的bug？还是本身就是这么设计的？有什么办法只对我标识的字段生效

### ISSUE THREAD

**Issue by stealth-Lee** [alibaba/easyexcel#3003]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
![image](https://user-images.githubusercontent.com/24888799/220828853-f8ed3fe0-e31b-4bdb-b711-21048b2b786a.png)
![image](https://user-images.githubusercontent.com/24888799/220828891-da1385bf-4001-4e9e-9e4d-333306fea569.png)

# 问题描述
HeadFontStyle设置 color=10(红色)，只在A字段上标识了。但是A字段后面的所有字段都变成红色了。这是系统的bug？还是本身就是这么设计的？有什么办法只对我标识的字段生效

**Comment by gongxuanzhang** [comment]
#2569

**Comment by lulongdong** [comment]
所以这个问题最后是怎么解决的，没有看懂

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
