### ISSUE TITLE
web下载excel本地正常，远程下载的文件损坏

### ISSUE THREAD

**Issue by carelessRose** [alibaba/easyexcel#301]
`ServletOutputStream out = response.getOutputStream();
String` userAgent = request.getHeader("USER-AGENT");
if (StringUtils.contains(userAgent, BROWSER_MOZILLA)) {
fileName = new String(fileName.getBytes(), StandardCharsets.ISO_8859_1);
} else {
fileName = URLEncoder.encode(fileName, "UTF8");
 }
            response.setContentType("application/octet-stream");
            response.setCharacterEncoding("utf-8");
            response.setHeader("Content-disposition", "attachment;filename=" + fileName);
            response.setHeader("Content-Type", "application/vnd.ms-excel");
            ExcelWriter writer = new ExcelWriter(out, ExcelTypeEnum.XLSX, true);
            Sheet sheet = new Sheet(1, 0, cla, sheetName, null);
            sheet.setTableStyle(createTableStyle());
            sheet.setAutoWidth(true);
            writer.write(list, sheet);
            writer.finish();
            out.flush();`

本地下载正常，远程下载文件损坏是什么原因

**Comment by zhangao1985** [comment]
到了远程，你的response估计不是同一个了

**Comment by zhuangjiaju** [comment]
请升级到最新版本，并按照demo书写。不会出现这个问题
