### ISSUE TITLE
easyExcel 锁定期间列相关的单元格失败

### ISSUE THREAD

**Issue by YangJingf** [alibaba/easyexcel#3013]
只有导出的列是期间（2022-02，字符串类型）的才会失败，其他列正常锁定。

加锁相关代码如下，columnList存放的是相关的列：
```java
   <html>
<body>
<!--StartFragment-->

@Override
--
  | public void afterCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Cell cell, Head head, Integer integer, Boolean aBoolean) {
  | cellStyle.setAlignment(HorizontalAlignment.CENTER);
  | if (!CollectionUtils.isEmpty(columnList))
  | {
  | if (columnList.contains(cell.getColumnIndex()))
  | {
  | // 设置表单保护密码（随机）
  | UUID uuid = UUID.randomUUID();
  | writeSheetHolder.getSheet().protectSheet(uuid.toString() );
  | // 设置锁定单元格
  | cellStyle.setLocked(true);
  | }
  | else
  | {
  | //非锁定单元格 必须手动设置为 false
  | cellStyle.setLocked(false);
  | }
  | }
  | // 填充单元格样式
  | cell.setCellStyle(cellStyle);
  | }
```
# 效果如下
灰色的代表禁用成功，白色的还是可以修改
<img width="1056" alt="企业微信截图_16775733234381" src="https://user-images.githubusercontent.com/33126647/221798520-ec7ae4e6-b7c9-4ef8-b06e-6b85df7cad32.png">

# 相关版本和变量
  <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>2.2.8</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.17</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.17</version>
        </dependency>

 @ContentStyle(dataFormat = 49)
    @ExcelProperty(value = "期间")
    private String periodName;

**Comment by gongxuanzhang** [comment]
感觉像是你自己判断逻辑的问题啊    
而且 writeSheetHolder.getSheet().protectSheet(uuid.toString() ); 应该只需要加一次就好了吧
可以在sheet或者workbook拦截器中用

**Comment by YangJingf** [comment]
> 感觉像是你自己判断逻辑的问题啊 而且 writeSheetHolder.getSheet().protectSheet(uuid.toString() ); 应该只需要加一次就好了吧 可以在sheet或者workbook拦截器中用

刚刚试过了，writeSheetHolder.getSheet().protectSheet(uuid.toString() ); 加一次也是一样的效果，最主要还是其他字段是正常的，期间字段就不行

**Comment by gongxuanzhang** [comment]
我觉得是因为你的cellStyle.setLocked(true); 代码没走进去  打断点试试

**Comment by YangJingf** [comment]
> 我觉得是因为你的cellStyle.setLocked(true); 代码没走进去 打断点试试

走进去了的

**Comment by YangJingf** [comment]
> 我觉得是因为你的cellStyle.setLocked(true); 代码没走进去 打断点试试

走进去了的，我感觉是因为我先对单元格渲染，之后EasyExcel又对单元格二次渲染，导致第一次的失效了

**Comment by gongxuanzhang** [comment]
afterCellCreate换成afterCellDispose

**Comment by YangJingf** [comment]
> afterCellCreate换成afterCellDispose

这个方案还真可以，感谢朋友

**Comment by gongxuanzhang** [comment]
OK
