### ISSUE TITLE
日期类型字符串的问题--解析时遇到

### ISSUE THREAD

**Issue by jonxx** [alibaba/easyexcel#302]
TypeUtil.convert()方法中，对日期格式的处理有点简单粗暴，只分析了"-"，"/"， ":"这三种特殊字符，只要是字符串中没有这三种的一律当作毫秒值，而不是用自定义格式。
这样对于20180312这种无分隔符的合法日期格式就会转换成无法保存的时间。

**Comment by fish7790714** [comment]
我基于这个版本写了个新版本 重新写了日期转换 支持yyyyMMddHHmmss了
只要吧pom 改成即可
```xml
        <dependency>
            <groupId>com.github.easy-data</groupId>
            <artifactId>easy-data</artifactId>
            <version>1.0.0</version>
        </dependency>
```

连接：https://github.com/easy-data/easy-data
