### ISSUE TITLE
这种复杂表头用easyexcel有办法实现吗

### ISSUE THREAD

**Issue by alittlenico** [alibaba/easyexcel#3025]
![1](https://user-images.githubusercontent.com/38160846/223070141-c288d10a-935e-44c4-a1ca-1817805afbbc.png)

**Comment by gongxuanzhang** [comment]
用模板可以的

**Comment by alittlenico** [comment]
![2](https://user-images.githubusercontent.com/38160846/223077607-34c2b896-a09a-4286-89c9-392d57ef089e.png)
但我这个时间列是动态的，有例子吗

> 用模板可以的

**Comment by gongxuanzhang** [comment]
如果用模板的话，你可以把这个时间也当成数据的一部分。
例子可以参考官方横向填充的例子
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/fill#%E6%A8%AA%E5%90%91%E7%9A%84%E5%A1%AB%E5%85%85

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue

**Comment by guangnix** [comment]
> 如果用模板的话，你把这个时间也当成数据的一部分。 例子可以参考官方横向填充的例子 [https://easyexcel.opensource.alibaba.com/docs/current/quickstart/fill#%E6%A8%AA %E5%90%91%E7%9A%84%E5%A1%AB%E5%85%85](https://easyexcel.opensource.alibaba.com/docs/current/quickstart/fill#%E6%A8%AA%E5%90%91%E7%9A%84%E5%A1%AB%E5%85%85)

这种只适合表头行 下面的数据也应是动态的 实际测试不出来这种输出
