### ISSUE TITLE
多sheet数据读取后上传到OSS，读取到 ByteArrayOutputStream 中数据为空

### ISSUE THREAD

**Issue by f-cs** [alibaba/easyexcel#3032]
//  最新版本 3.2.1

    @GetMapping(value = "t")
    public void test(HttpServletResponse response) {
        ExcelWriter excelWriter = null;
        List<String> sheetLists = ListUtil.of("业务量统计", "日提报量表");
        try {
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            excelWriter = EasyExcel.write(outputStream, UserModel.class).autoCloseStream(false).build();
            for (int i = 0; i < sheetLists.size(); i++) {
                WriteSheet writeSheet = EasyExcel.writerSheet(i, sheetLists.get(i))
                        .head(UserModel.class)
                        .build();
                excelWriter.write(userSaveService.list(), writeSheet);
            }
            // 数据为空，写入不进去
            System.out.println(outputStream.toByteArray().length);
        }
        catch (Exception e) {
            log.error("异常：", e);
        }
        finally {
            if (excelWriter != null) {
                excelWriter.finish();
            }
        }
    }

**Comment by lonecloud** [comment]
1. 如果想写完后就进行读取，可以在打印前面手动调用`ExcelWriter.finish()`方法

**Comment by f-cs** [comment]
已经选了其他方式，你这种我试了也可以，谢谢了

**Comment by mankouzhuya** [comment]
这个问题真是坑啊，我都调了半天，outputStream一直为空。结果需要加excelWriter.finish();真是醉了
