### ISSUE TITLE
写excel时，集合泛型是数组异常

### ISSUE THREAD

**Issue by lxp411** [alibaba/easyexcel#3035]
写excel时，集合泛型是数组（List<String[]>），报异常 com.alibaba.excel.support.cglib.core.CodeGenerationException: java.lang.NoClassDefFoundError-->IllegalName: [Ljava.lang.String;$$BeanMapByEasyExcelCGLIB$$1d6ef702
应该支持这种数据格式吧，必须强制是自定义类的话，那就没有通用性了。
目前我看可以用Map<Integer,?>这个代替

**Comment by gongxuanzhang** [comment]
要是没有实体类   用List<List<String>>

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
