### ISSUE TITLE
easyExcel模板导出支持sum函数求和吗？有教程吗

### ISSUE THREAD

**Issue by fausto2022** [alibaba/easyexcel#3036]
easyExcel模板导出支持sum函数求和吗？有教程吗

**Comment by gongxuanzhang** [comment]
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E8%B6%85%E9%93%BE%E6%8E%A5%E5%A4%87%E6%B3%A8%E5%85%AC%E5%BC%8F%E6%8C%87%E5%AE%9A%E5%8D%95%E4%B8%AA%E5%8D%95%E5%85%83%E6%A0%BC%E7%9A%84%E6%A0%B7%E5%BC%8F%E5%8D%95%E4%B8%AA%E5%8D%95%E5%85%83%E6%A0%BC%E5%A4%9A%E7%A7%8D%E6%A0%B7%E5%BC%8F

公式看文档
