### ISSUE TITLE
关于excel日期格式类型转换问题

### ISSUE THREAD

**Issue by zz540120240** [alibaba/easyexcel#3039]
[123.xls](https://github.com/alibaba/easyexcel/files/10953317/123.xls)
![image](https://user-images.githubusercontent.com/127710868/224603136-9b860a90-60a8-4f44-933d-d7635637106a.png)
![Uploading image.png…]()
之前没遇到问题，初步怀疑是文件格式的问题，但是哪里格式有问题又找不出，此文件rowindex = 180之后会出现日期格式转换问题
@Data
@ApiModel(value="SafetyCertificate对象", description="安全持证上岗表")
@TableName("safety_certificate")
@ExcelIgnoreUnannotated
public class SafetyCertificate implements Serializable {
    private static final long serialVersionUID = -23696867759867942L;

    private String id;

    @ApiModelProperty("设施")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","设施"})
    private String facility;

    /**
     * 班组
     */
    @ApiModelProperty("班组")
  //  @ExcelProperty("班组")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","班组"})
    private String workGroup;

    @ApiModelProperty("证书编号")
    private String trainCode;
    /**
     * 证书名称
     */
    @ApiModelProperty("证书名称")
    //@ExcelProperty("证书名称")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","证书名称"})
    private String certificateName;
    /**
     * 持证人姓名
     */

    @ApiModelProperty("持证人姓名")
    //@ExcelProperty("姓名")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","姓名"})
    private String certificateOwner;

    @ApiModelProperty("岗位编号")
    private String postCode;

    /**
     * 岗位
     */
    @ApiModelProperty("岗位名称")
   // @ExcelProperty("岗位")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","岗位"})
    private String operatingPost;
    /**
     * 取证日期
     */
    //@ExcelProperty("取证日期")
    @ApiModelProperty("取证日期")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","取证日期"})
    @JsonFormat(pattern = "yyyy-MM-dd")
    @DateTimeFormat("yyyy/MM/dd")
    private LocalDateTime getCertificateDate;
    /**
     * 第一次复审日期
     */
    //@ExcelProperty("第一次复审日期")
    @ApiModelProperty("第一次复审日期")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","第一次复审日期"})
    @JsonFormat(pattern = "yyyy-MM-dd")
   @DateTimeFormat("yyyy/MM/dd")
    private LocalDateTime firstReviewDate;

    /**
     * 第一次是否复审
     */
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","第一次是否复审"})
    @ApiModelProperty("第一次是否复审")
    private String fristReview;
    /**
     * 第二次复审日期
     */
    @ApiModelProperty("第二次复审日期")
   // @ExcelProperty("第二次复审日期")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","第二次复审日期"})
    @JsonFormat(pattern = "yyyy-MM-dd")
    @DateTimeFormat("yyyy/MM/dd")
    private LocalDateTime secondReviewDate;

    /**
     * 第二次是否复审
     */
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","第二次是否复审"})
    @ApiModelProperty("第二次是否复审")
    private String twoReview;

    @ApiModelProperty("到期日期")
    //@ExcelProperty("到期日期")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","到期日期"})
     @JsonFormat(pattern = "yyyy-MM-dd")
    @DateTimeFormat("yyyy/MM/dd")
    private LocalDateTime maturityDate;

    /**
     * 标志，0法定培训，1技能提升
     */
    @ApiModelProperty("标志，0法定培训，1技能提升")
    private String flag;

    //身份证号
    /**
     * 个人身份证号
     */
    @ApiModelProperty("个人身份证号")
    private String userNumber;
    //证书编号
    /**
     * 证书编号
     */@ApiModelProperty("证书号码（MTS系统)")
    private String certificateNumber;
    //mts卡号
    /**
     * mts卡号
     */
    @ApiModelProperty("mts卡号")
    private String mtsNumber;
    //mtsUserId
    /**
     * mtsUserId
     */
    @ApiModelProperty("mts用户id")
    private String mtsUserId;

    /**
     * 学时
     */
    @ApiModelProperty("学时")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","学时"})
    private Double classHour;

    /**
     * 邮件提醒
     */
    @ApiModelProperty("邮件提醒")
    private Boolean isEmailAlert;
    /**
     * 机构代码
     */
    @ApiModelProperty("机构代码")
    private String orgCode;
    /**
     * 生产单元
     */
    @ApiModelProperty("生产单元")
    private String productionUnitId;
    /**
     * 备注
     */
    @ApiModelProperty("备注信息")
    //@ExcelProperty("备注")
    @ExcelProperty(value = {"特殊岗位人员、特种作业人员证书登记跟踪表","备注"})
    private String remarks;
    /**
     * 逻辑删除
     */
    @ApiModelProperty("逻辑删除")
    @TableLogic
    private Integer deleted;

    @ApiModelProperty("创建时间")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDateTime createTime;

    @ApiModelProperty("创建人")
    private String createUser;

    @ApiModelProperty("修改时间")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDateTime updateTime;

    @ApiModelProperty("修改人")
    private String updateUser;

}

**Comment by gongxuanzhang** [comment]
<img width="979" alt="image" src="https://user-images.githubusercontent.com/48286053/224622452-9f7ad210-b23e-4081-97ec-68124c2367b5.png">

你的excel 207行的H列里面有内容，是一个空串  并不是空列，
同样有这个问题的还有H,J,M列     
具体还可能有问题我没有测，总之是因为你的excel里面是"Blank" 而不是"empty" 导致的

**Comment by zz540120240** [comment]
大佬，有什么预防措施吗

**Comment by gongxuanzhang** [comment]
> 大佬，有什么预防措施吗

没有，你excel有问题什么框架都没办法

**Comment by gongxuanzhang** [comment]
你可以自己先处理一遍excel
