### ISSUE TITLE
请问如何用easyExcel读取固定单元格的值，譬如A3单元格。现在有实体类了，但是未找到这种读取赋值方法。。

### ISSUE THREAD

**Issue by littlehBinBin** [alibaba/easyexcel#3040]
请问如何用easyExcel读取固定单元格的值，譬如A3单元格。现在有实体类了，但是未找到这种读取赋值方法。。

**Comment by gongxuanzhang** [comment]
在监听器中可以通过context.readRowHolder().getRowIndex() 拿到行号
数据都在上下文和实体中
