### ISSUE TITLE
java.lang.NumberFormatException: Character S is neither a decimal digit number, decimal point, nor "e" notation exponential mark.

### ISSUE THREAD

**Issue by DamonOuyang** [alibaba/easyexcel#3042]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
java.lang.NumberFormatException: Character S is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
# 触发Bug的代码
```java
   这里写代码
```
# 提示的异常或者没有达到的效果
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。

**Comment by DamonOuyang** [comment]
Excel格式有问题，Excel格式重新保存就可以了

**Comment by gongxuanzhang** [comment]
> Excel格式有问题，Excel格式重新保存就可以了

是已经解决了么

**Comment by DamonOuyang** [comment]
是的，15行 开始读，代码写到13行开始读，出的这个错
![image](https://user-images.githubusercontent.com/22972038/224667812-4a517e83-58ee-4bf8-8524-84691f3da0ec.png)

**Comment by gongxuanzhang** [comment]
好的
