### ISSUE TITLE
怎么获取单元格的颜色，有哪位知道吗？poi是获取cellstyle,但是翻了easyexcel好像根本获取不到

### ISSUE THREAD

**Issue by jf66882020** [alibaba/easyexcel#3043]
# 问题描述
怎么获取单元格的颜色，有哪位知道吗？poi是获取cellstyle,但是翻了easyexcel好像根本获取不到

**Comment by gongxuanzhang** [comment]
读的时候只能映射实体

**Comment by jf66882020** [comment]
有没有办法读到单元格的样式呢？

**Comment by gongxuanzhang** [comment]
context.readRowHolder().getCellMap()
可以在读取的时候用这个方法拿到cell

**Comment by jf66882020** [comment]
拿到cell后，只有rowindex和columnindex,没有其他东西

**Comment by gongxuanzhang** [comment]
没办法读到样式，只能读到扩展信息比如超链接等  
下个版本会增加

**Comment by jf66882020** [comment]
哦哦，能否通过获取easyexcel包装到的HssfRow获取到样式呢

**Comment by gongxuanzhang** [comment]
那是可以的,但是可能需要一番功夫去获取。
hssf还有戏  xssf肯定没戏

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue

**Comment by xuyoudun** [comment]
同样的疑问，API都翻烂了，调试过了，没有办法拿到单元格信息

**Comment by deaoyi123** [comment]
+1想要获取单元格样式，翻遍了demo和文档，调试了源码，没找到解决办法
