### ISSUE TITLE
通过ExcelTypeEnum.CSV方式导入excel，有一个字段为空

### ISSUE THREAD

**Issue by hxp20645** [alibaba/easyexcel#3044]
实体类：
![微信截图_20230314115311](https://user-images.githubusercontent.com/25942188/224889797-de54fdb1-fe2f-4bd9-92b2-0a88a0d4e21b.png)

导入代码：
EasyExcel.read(FileUtil.getInputStream(fileName)).excelType(ExcelTypeEnum.CSV).head(JwOrderYtfh.class).sheet().doReadSync();
excel:
![微信截图_20230314115931](https://user-images.githubusercontent.com/25942188/224889752-56bdc1e3-74bb-43eb-9ca6-ef461e83889a.png)

异常：
jwOrderNo字段获取不到值

**Comment by gongxuanzhang** [comment]
其他字段可以拿到吗

**Comment by hxp20645** [comment]
其他字段可以拿到，就商城订单号这个字段拿不到

**Comment by gongxuanzhang** [comment]
你看看订单号列的表头文字是不是有偏差

**Comment by hxp20645** [comment]
确认过了，直接复制的，然后如果另存为xlsx，不用CSV的方式是可以读取到的

**Comment by gongxuanzhang** [comment]
把数据脱敏一下 传个文件上来,再贴一下代码  我复现一下

**Comment by hxp20645** [comment]
麻烦能加下我微信：18035149141看吗，这个excel文件格式有问题，一修改格式就变了

**Comment by gongxuanzhang** [comment]
记录：  csv表头有不可见字符

**Comment by 1598339171** [comment]
怎么解决的，我也出现这个问题了

**Comment by 1598339171** [comment]
文本在保存时包含了BOM（Byte Order Mark，字节顺序标记，出现在文本文件头部）导致的，解决方法是使用 utf-8-sig 编码
