### ISSUE TITLE
填充数据时，会遇到多行列表填充，当前只能对第一行进行列表填充。

### ISSUE THREAD

**Issue by Ijiran** [alibaba/easyexcel#3048]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码

# 异常提示

# 问题描述

填充数据时，会遇到多行列表填充，当前只能对第一行进行列表填充。

请问这种情况有没有方案？

**Comment by gongxuanzhang** [comment]
听不懂问题

**Comment by Ijiran** [comment]
模板配置
![1678858588273](https://user-images.githubusercontent.com/28706330/225216822-633e970f-3a20-499a-96c3-888bd3ac01ea.jpg)

期望效果
![1678858542293](https://user-images.githubusercontent.com/28706330/225216739-33b53cb9-3143-440f-879d-131f8e7df154.jpg)

**Comment by Ijiran** [comment]
> 

模板配置
![1678858588273](https://user-images.githubusercontent.com/28706330/225216822-633e970f-3a20-499a-96c3-888bd3ac01ea.jpg)

期望效果
![1678858542293](https://user-images.githubusercontent.com/28706330/225216739-33b53cb9-3143-440f-879d-131f8e7df154.jpg)

**Comment by Ijiran** [comment]
> 听不懂问题

模板配置
![1678858588273](https://user-images.githubusercontent.com/28706330/225216822-633e970f-3a20-499a-96c3-888bd3ac01ea.jpg)

期望效果
![1678858542293](https://user-images.githubusercontent.com/28706330/225216739-33b53cb9-3143-440f-879d-131f8e7df154.jpg)

**Comment by gongxuanzhang** [comment]
模板以.开头  {.student}

文档 
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/fill#%E5%A1%AB%E5%85%85%E5%88%97%E8%A1%A8

**Comment by Ijiran** [comment]
> 模板以.开头 {.student}
> 
> 文档 https://easyexcel.opensource.alibaba.com/docs/current/quickstart/fill#%E5%A1%AB%E5%85%85%E5%88%97%E8%A1%A8

我用的多列表组合填充
![image](https://user-images.githubusercontent.com/28706330/225220216-e744cdd2-bbbd-464e-818c-dabaf55cef00.png)

**Comment by gongxuanzhang** [comment]
> > 听不懂问题
> 
> 模板配置 ![1678858588273](https://user-images.githubusercontent.com/28706330/225216822-633e970f-3a20-499a-96c3-888bd3ac01ea.jpg)
> 
> 期望效果 ![1678858542293](https://user-images.githubusercontent.com/28706330/225216739-33b53cb9-3143-440f-879d-131f8e7df154.jpg)

这种属于循环table 填充的话还不支持。
建议你把class,name,sort当成同一级别的数据，用write方式  不是fill方式
然后插入合并单元格的监听器。
可以参考table写入方式
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E4%BD%BF%E7%94%A8table%E5%8E%BB%E5%86%99%E5%85%A5


循环table填充的功能已经在开发中了

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue

**Comment by F-ch1** [comment]
请问最新版easyexcel填充这个问题解决了吗(填充数据时，会遇到多行列表填充，当前只能对第一行进行列表填充
)

**Comment by F-ch1** [comment]
循环table填充的功能怎么使用
