### ISSUE TITLE
动态修改表头不生效

### ISSUE THREAD

**Issue by 1012ydz** [alibaba/easyexcel#3053]
通过代理方式修改表头，偶尔会失效问题
 field = srcClass.getDeclaredField(key);
                ExcelProperty excel = field.getAnnotation(ExcelProperty.class);
                InvocationHandler excelH = Proxy.getInvocationHandler(excel);
                Field excelF = excelH.getClass().getDeclaredField("memberValues");
                excelF.setAccessible(true);
                Map excelValues = (Map) excelF.get(excelH);
                excelValues.put("value", new String[]{columnMap.get(key)});

**Comment by gongxuanzhang** [comment]
看不懂，说需求

**Comment by 1012ydz** [comment]
> 看不懂，说需求

通过修改实体类中ExcelProperty中的value值来达到动态表头的效果；目前修改了偶尔会不成功的问题

**Comment by gongxuanzhang** [comment]
动态参考文档 
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E5%8A%A8%E6%80%81%E5%A4%B4%E5%AE%9E%E6%97%B6%E7%94%9F%E6%88%90%E5%A4%B4%E5%86%99%E5%85%A5

**Comment by 1012ydz** [comment]
> 动态参考文档 https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E5%8A%A8%E6%80%81%E5%A4%B4%E5%AE%9E%E6%97%B6%E7%94%9F%E6%88%90%E5%A4%B4%E5%86%99%E5%85%A5

这种方式是可以的，但是想知道是否支持上面动态代理的方式修改excelProperty的value值，目前只是偶尔会出现问题

**Comment by gongxuanzhang** [comment]
你要是想用黑科技破坏封装，只要你写的是JAVA都能生效。
为什么不生效的答案就是你用错了

**Comment by 1012ydz** [comment]
> 你要是想用黑科技破坏封装，只要你写的是JAVA都能生效。 为什么不生效的答案就是你用错了

是使用的java注解代理，修改注解内容；如果使用错了，请大佬指教下

**Comment by gongxuanzhang** [comment]
给上一段能跑的代码，说出你的期望的结果

**Comment by 1012ydz** [comment]
> 
demo:
[excel-demo.zip](https://github.com/alibaba/easyexcel/files/10985981/excel-demo.zip)
顺便大佬也帮忙看下使用numberFormat出现的问题
![企业微信截图_16789319579120](https://user-images.githubusercontent.com/41256023/225490555-75d394b6-594e-42be-9042-559a438a9f20.png)

**Comment by 1012ydz** [comment]
> 给上一段能跑的代码，说出你的期望的结果

demo:
[excel-demo.zip](https://github.com/alibaba/easyexcel/files/10985981/excel-demo.zip)
顺便大佬也帮忙看下使用numberFormat出现的问题
企业微信截图_16789319579120

**Comment by 1012ydz** [comment]
> > 给上一段能跑的代码，说出你的期望的结果
期望：可以动态修改excelProperty中的value值
目前代码是正常运行的，但是偶尔会出现导出的标题是原来的excelProperty中的value值；
demo:
[excel-demo.zip](https://github.com/alibaba/easyexcel/files/10985981/excel-demo.zip)
顺便大佬也帮忙看下使用numberFormat出现的问题
 ![企业微信截图_16789323132087](https://user-images.githubusercontent.com/41256023/225490900-9a1f65d9-d3a5-4703-8ecf-7416dc5fd14f.png)

**Comment by 1012ydz** [comment]
> 给上一段能跑的代码，说出你的期望的结果

期望：可以动态修改excelProperty中的value值
目前代码是正常运行的，但是偶尔会出现导出的标题是原来的excelProperty中的value值；
demo:
[excel-demo.zip](https://github.com/alibaba/easyexcel/files/10985981/excel-demo.zip)
顺便大佬也帮忙看下使用numberFormat出现的问题
![企业微信截图_16789323132087](https://user-images.githubusercontent.com/41256023/225490900-9a1f65d9-d3a5-4703-8ecf-7416dc5fd14f.png)

**Comment by gongxuanzhang** [comment]
我跑你的代码是正常的，注解内容也修改了.
怎么复现你的问题

**Comment by 1012ydz** [comment]
> 我跑你的代码是正常的，注解内容也修改了. 怎么复现你的问题

注解修改问题是偶发的，目前不知道怎么复现；
numberFormat的问题是什么原因呢？

**Comment by gongxuanzhang** [comment]
numberformat升级一下版本试试

**Comment by 1012ydz** [comment]
> 

升级为3.2.1也不行

**Comment by 1012ydz** [comment]
> numberformat升级一下版本试试

升级依赖版本为3.2.1也不行

**Comment by gongxuanzhang** [comment]
应该是BigDecimal的转换问题，最好是能用double  如果不能的话需要自定义转换器
这个算是bug  下版本应该会修复

**Comment by changdy** [comment]
是修改了类 注解上的信息 ,, 
的确有点黑科技 , 其实不推荐使用, 因为一些 需要反射的框架都会有 缓存 ,
并且最重要的是 ,一定会有 线程安全的问题.

**Comment by luhengyu1** [comment]
我用aop把@ExcelProperty里面的列名改了，比如@ExcelProperty("${name"}),然后去国际化文件里找name，本地没问题，部署在服务器上过一段时间之后就会失效，本来应该导出为 姓名/name ,但是导出的文件，表头就是 ${name}, 而不是替换后的

**Comment by luhengyu1** [comment]
> 我用aop把@ExcelProperty里面的列名改了，比如@ExcelProperty("${name"}),然后去国际化文件里找name，本地没问题，部署在服务器上过一段时间之后就会失效，本来应该导出为 姓名/name ,但是导出的文件，表头就是 ${name}, 而不是替换后的

不是很懂多线程，没有实践过，看到上面有人说会有线程安全问题

**Comment by MagicalWhirlwind** [comment]
解决了吗  遇到相同的问题了

**Comment by MagicalWhirlwind** [comment]
暂时用这个办法解决了 https://blog.csdn.net/qq_48496989/article/details/121553611

**Comment by MagicalWhirlwind** [comment]
已经解决了现在将原因和方法告诉你 注解修改不可以传入xxx.class 应该传入vo.getClass() 这样相当于在vo对象上修改 而传入xxx.class则可能使用的是编译后的.class文件

**Comment by 1012ydz** [comment]
之前也改为了po.getClass()方法还是有问题，后面用了其它方式实现



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月24日(周一) 下午3:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/easyexcel] 动态修改表头不生效 (Issue #3053)




 
已经解决了现在将原因和方法告诉你 注解修改不可以传入xxx.class 应该传入vo.getClass() 这样相当于在vo对象上修改 而传入xxx.class则可能使用的是编译后的.class文件

**Comment by MagicalWhirlwind** [comment]
这样吗  最后写的时候有没有写我们的对象的名字
aClass=po.getClass()

ExcelSheetExportModel detail = new ExcelSheetExportModel();
detail.setClzz(aClass);

**Comment by MagicalWhirlwind** [comment]
目前按照po.getClass()的方法测了没有问题 ，后面我再观察一下。
请楼主告知下另一种写法，我也参考下哈。

**Comment by 1012ydz** [comment]
和初始化excel.head类似
通过重写CellWriteHandler来对head进行重写
&nbsp; Cell&nbsp;cell&nbsp;=&nbsp;context.getCell();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if&nbsp;(BooleanUtils.isTrue(context.getHead())
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&amp;&amp;&nbsp;cell.getRowIndex()&nbsp;==&nbsp;0)&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;String&nbsp;stringCellValue&nbsp;=&nbsp;cell.getStringCellValue();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if(columnMap.containsKey(stringCellValue)){
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cell.setCellValue(columnMap.get(stringCellValue));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月24日(星期一) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 动态修改表头不生效 (Issue #3053)





 
目前按照po.getClass()的方法测了没有问题 ，后面我再观察一下。
 请楼主告知下另一种写法，我也参考下哈。

**Comment by 1012ydz** [comment]
是的，是基于class修完成后直接将class返回，没有重新获取;这样偶尔还是会有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月24日(星期一) 下午4:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 动态修改表头不生效 (Issue #3053)





 
这样吗  最后写的时候有没有写我们的对象的名字
 aClass=po.getClass()
 
ExcelSheetExportModel detail = new ExcelSheetExportModel();
 detail.setClzz(aClass);

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
