### ISSUE TITLE
如何锁表头，让表头不允许修改

### ISSUE THREAD

**Issue by shendong015** [alibaba/easyexcel#3055]
现在公司有一个需求，导出excel模板，但是表头不允许修改，在easyExcel文档中也没有找到相关内容

**Comment by gongxuanzhang** [comment]
在CellWriteHandler中 拿到表头Cell 设置lock
然后在SheetWriteHandler中把workBook设置成保护模式即可
demo 可以参考
https://github.com/gongxuanzhang/support-demo/tree/lock_cell
(注意分支  别切错了)
解决了帮我点个星谢谢

**Comment by shendong015** [comment]
你好，很感谢，我打开演示项目并运行了，发现是全表锁，
**我只想锁第一行（表头那一行）的数据，其他行都可以编辑**，
在网上我也尝试找过，没有找到解决方案，请问这种怎么实现呢

**Comment by gongxuanzhang** [comment]
想锁什么单元格，你就在什么单元格设置啊

**Comment by gongxuanzhang** [comment]
```java

new CellWriteHandler() {
                @Override
                public void afterCellDispose(CellWriteHandlerContext context) {
                    if (BooleanUtils.isTrue(context.getHead())) {
                      context.getCell().getCellStyle().setLocked(true);
                    }
                }
            }
```


给demo项目点个星呀

**Comment by gongxuanzhang** [comment]
解决了么

**Comment by shendong015** [comment]
不行呀，还是全表锁了55555

**Comment by gongxuanzhang** [comment]
你怎么写的代码 贴出来

**Comment by shendong015** [comment]
public static void main(String[] args) {
        String fileName = "export.xlsx";
        EasyExcel.write(fileName).sheet("模板").registerWriteHandler(new SheetWriteHandler() {
            @Override
            public void afterSheetCreate(WriteWorkbookHolder writeWorkbookHolder, WriteSheetHolder writeSheetHolder) {
                writeSheetHolder.getSheet().protectSheet("password");
            }
        }).registerWriteHandler(new CellWriteHandler() {
            @Override
            public void afterCellDispose(CellWriteHandlerContext context) {
                if (BooleanUtils.isTrue(context.getHead())) {
                    context.getCell().getCellStyle().setLocked(true);
                }
            }
        }).doWrite(data());
    }

    private static List<DemoData> data() {
        List<DemoData> list = ListUtils.newArrayList();
        for (int i = 0; i < 10; i++) {
            DemoData data = new DemoData();
            data.setString("字符串" + i);
            data.setDate(new Date());
            data.setDoubleData(0.56);
            list.add(data);
        }
        return list;
    }

**Comment by gongxuanzhang** [comment]
第一，你需要指定导出的实体类Class,否则默认没有表头
<img width="738" alt="image" src="https://user-images.githubusercontent.com/48286053/225860841-82e7c36d-faf0-45d6-8c36-6c60f614018a.png">


第二 加一句  让非表头的样式不被覆盖
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/48286053/225867796-643d15b6-203c-452d-b0aa-287c7df52a53.png">

**Comment by shendong015** [comment]
感谢大佬耐心回答，还有最后一个小问题
因为导出的是一个模板，然后根据模板添加数据
但是这个空白部分的单元格也被锁了，那操作人就没办法添加新数据了，只能修改
我希望既能修改，也能添加数据。

**Comment by gongxuanzhang** [comment]
> 感谢大佬耐心回答，还有最后一个小问题 因为导出的是一个模板，然后根据模板添加数据 但是这个空白部分的单元格也被锁了，那操作人就没办法添加新数据了，只能修改 我希望既能修改，也能添加数据。

这个似乎满足不了

**Comment by shendong015** [comment]
好哦
