### ISSUE TITLE
通过注解指定主键，将需要合并的列进行动态合并

### ISSUE THREAD

**Issue by a1667834841** [alibaba/easyexcel#3056]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 建议描述
# 问题场景

这是一张订单明细表，可以根据主键orderNo，自定义指定其他列动态合并
![image](https://user-images.githubusercontent.com/34375481/225863926-0449e3ed-d6f7-45fb-aa36-be27e377ff65.png)

比如指定orderNo和orderCreateTime 两列需要动态合并 ，下面是效果
![image](https://user-images.githubusercontent.com/34375481/225864566-211ac15a-5fe7-4ef8-b869-b36ba601c13d.png)

**Comment by a1667834841** [comment]
这是我工作时需要的场景，我已经实现了，这个功能能提交上去吗？希望能进自己一点绵薄之力

**Comment by gongxuanzhang** [comment]
可以当成解决方案。
工具不可能满足所有需求，只做主要功能

**Comment by oneinhere** [comment]
> 这是我工作时需要的场景，我已经实现了，这个功能能提交上去吗？希望能进自己一点绵薄之力

您那边具体是怎么实现的 ？
