### ISSUE TITLE
空行直接跳过解析

### ISSUE THREAD

**Issue by liiibpm** [alibaba/easyexcel#3058]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 建议描述
现在逻辑是校验到空行，不解析该条数据，但是还会继续解析下面一行的数据，我的业务需求中需要将空行之后的数据全部忽略，即校验到空行后，直接推出解析，只收集前面不为空的数据，否则会出现大量的空行数据影响效率。我看这个代码的逻辑没法去通过监听器之类的去自定义，或者通过其他方式去替换这个DefaultAnalysisEventProcessor
谢谢
![image](https://user-images.githubusercontent.com/105549399/226231648-a2a8b5b7-8141-409d-8d97-de138a913458.png)

**Comment by gongxuanzhang** [comment]
可以在invoke里面读到空行抛出异常

**Comment by liiibpm** [comment]
> 可以在invoke里面读到空行抛出异常

谢谢你的解答。但是你说的invoke抛出异常，指的是listener的invoke是吧。前提是要他能够到达这个方法，空行数据在上图的47行中就会被返回出去（并打印日志 ”Empty row！“），而需要走到51行的dealData方法才会执行到invoke对吧。

**Comment by liiibpm** [comment]
> > 可以在invoke里面读到空行抛出异常
> 
> 谢谢你的解答。但是你说的invoke抛出异常，指的是listener的invoke是吧。前提是要他能够到达这个方法，空行数据在上图的47行中就会被返回出去（并打印日志 ”Empty row！“），而需要走到51行的dealData方法才会执行到invoke对吧。



> 可以在invoke里面读到空行抛出异常

你的意思是不忽略空行   然后到invoke中抛出异常是吗

**Comment by gongxuanzhang** [comment]
是的

> > > 可以在invoke里面读到空行抛出异常
> > 
> > 
> > 谢谢你的解答。但是你说的invoke抛出异常，指的是listener的invoke是吧。前提是要他能够到达这个方法，空行数据在上图的47行中就会被返回出去（并打印日志 ”Empty row！“），而需要走到51行的dealData方法才会执行到invoke对吧。
> 
> > 可以在invoke里面读到空行抛出异常
> 
> 你的意思是不忽略空行 然后到invoke中抛出异常是吗

是的

**Comment by liiibpm** [comment]
> 是的
> 
> > > > 可以在invoke里面读到空行抛出异常
> > > 
> > > 
> > > 谢谢你的解答。但是你说的invoke抛出异常，指的是listener的invoke是吧。前提是要他能够到达这个方法，空行数据在上图的47行中就会被返回出去（并打印日志 ”Empty row！“），而需要走到51行的dealData方法才会执行到invoke对吧。
> > 
> > 
> > > 可以在invoke里面读到空行抛出异常
> > 
> > 
> > 你的意思是不忽略空行 然后到invoke中抛出异常是吗
> 
> 是的

好的  谢谢   我试下

**Comment by gongxuanzhang** [comment]
解决了么

**Comment by liiibpm** [comment]
> 解决了么

可以了  感谢
