### ISSUE TITLE
读取Excel时，每隔几行就有一行标题行

### ISSUE THREAD

**Issue by wangjxGitHub** [alibaba/easyexcel#3059]
# 问题描述
如题，**每隔几行就有一行表头将上下部分数据分隔开，如何做到一次全部读取，只读取数据**。还是说没办法，只能拆分多个sheet，分多次读取。
表样如下。
![1679284287113](https://user-images.githubusercontent.com/83507687/226242460-7e01b6d7-d52a-4557-a53b-99825ef922d9.png)

**Comment by gongxuanzhang** [comment]
没办法，但是你可以把每个表头都作为数据读取。
在invoke方法中判断value是否是特殊值，然后将listener里面切分

**Comment by wangjxGitHub** [comment]
好吧。那考虑数据类型转换问题，如果使用JavaBean存储的话，数据类型都得设置为String，后面再转呗。

**Comment by gongxuanzhang** [comment]
目前是的，这个问题已经在设计更优化的解决方案了

**Comment by wangjxGitHub** [comment]
了解

**Comment by Bluewu129** [comment]
> 目前是的，这个问题已经在设计更优化的解决方案了

想问下这个问题现在有解决方案了吗？
