### ISSUE TITLE
复杂EXCEL表格能用easyexcel来实现吗？

### ISSUE THREAD

**Issue by pjg113** [alibaba/easyexcel#3063]
![2201679364070_ pic](https://user-images.githubusercontent.com/51736469/226502251-c4197963-aeac-4118-b243-4b128d594f42.jpg)
如图，横坐标的日期列是动态的，纵坐标的不良项目列也是动态的，并且需要将对应日期下的不良项目的值（QTY，DR)渲染上，能使用模板填充或者导出实现吗？

**Comment by gongxuanzhang** [comment]
听不懂，上例子上图

**Comment by gongxuanzhang** [comment]
导出可以实现，需要用动态头和数据 
参考文档 
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E5%8A%A8%E6%80%81%E5%A4%B4%E5%AE%9E%E6%97%B6%E7%94%9F%E6%88%90%E5%A4%B4%E5%86%99%E5%85%A5

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
