### ISSUE TITLE
2GB文件读取卡住，文件存储在FTP上，读取卡住

### ISSUE THREAD

**Issue by laglangyue** [alibaba/easyexcel#3064]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
 EasyExcelListener easyExcelListener = new EasyExcelListener(0, 1);
    ExcelReaderBuilder read = EasyExcel.read(inputStream, easyExcelListener).headRowNumber(0);
    ExcelReaderSheetBuilder sheet = read.sheet();
    sheet.doRead();
    Map<Integer, String> headMap = easyExcelListener.getHeadMap();
    List<LinkedHashMap<Integer, String>> result = easyExcelListener.getResult();
```

# 问题描述
debug到里面，发现会创建一个文件拷贝。不知道是否有优化手段，直接从ftp的流进行读取
![image](https://user-images.githubusercontent.com/35491928/226540460-77a93236-70b4-443b-875b-c5e7369a936a.png)

**Comment by laglangyue** [comment]
这样意味着会先将ftp文件下载到本地，然后读取tmp文件，是否有相关配置，直接从流里面去读取数据

**Comment by songjian449** [comment]
?
