### ISSUE TITLE
关于重复多次写入问题

### ISSUE THREAD

**Issue by CanaanWang** [alibaba/easyexcel#3065]
一次性导出  EasyExcel.write(response.getOutputStream(),DemoData.class).sheet("sheet1").doWrite(data);
这样写可以正常导出
但是通过循环分页查询数据后导出的文件就报错

**Comment by gongxuanzhang** [comment]
报什么错，什么是循环查询，上代码上异常

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
