### ISSUE TITLE
合并单元格后,wps打开正常,Microsoft Excel打开还是没有合并

### ISSUE THREAD

**Issue by AnthonyChenny** [alibaba/easyexcel#3068]
# 合并单元格
wps打开正常,Microsoft Excel(2007)打开还是没有合并
# 异常代码
```java
  Row lastRow = sheet.getRow(row.getRowNum() - 1);
  // 将本行和上一行是同一类型的数据(通过主键字段进行判断)，则需要合并
  if (lastRow.getCell(pkIndex).getStringCellValue().equalsIgnoreCase(row.getCell(pkIndex).getStringCellValue())) {
      for (Integer needMerIndex : needMergeColumnIndex) {
          CellRangeAddress cellRangeAddress = new CellRangeAddress(row.getRowNum() - 1, row.getRowNum(),
                  needMerIndex, needMerIndex);
          sheet.addMergedRegionUnsafe(cellRangeAddress);
      }
  }
```
# 异常提示
![22](https://user-images.githubusercontent.com/26462382/227411260-761f355f-74c1-442a-96a3-2e47c97bdd70.png)
![11](https://user-images.githubusercontent.com/26462382/227411258-cbfa9962-9b59-4042-b3b7-1abfda27fbdd.png)

**Comment by gongxuanzhang** [comment]
API相同打开不同可能是微软excel版本太低没支持?

**Comment by KegFmn** [comment]
解决了吗

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
