### ISSUE TITLE
不创建对象读数据的时候能否表头和数据对应返回

### ISSUE THREAD

**Issue by noviceZ** [alibaba/easyexcel#3069]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述
目前返回{0=数据1，1=数据1}。能不能设置成{表头1=数据1，表头2=数据2}的形式

**Comment by gongxuanzhang** [comment]
自己转换一下

**Comment by noviceZ** [comment]
> 自己转换一下

我想的也是自己转换，如果本身就有方法可以设置返回的话就可以直接用了。我是想问有没有这种方法能直接返回

**Comment by gongxuanzhang** [comment]
没有的

**Comment by noviceZ** [comment]
> 没有的

好的 谢谢。
我在做练习的时候还有一个问题你能帮看下吗
https://github.com/alibaba/easyexcel/issues/3071
