### ISSUE TITLE
不创建对象读取数据时，如果标题是数字，读出来的是null

### ISSUE THREAD

**Issue by noviceZ** [alibaba/easyexcel#3071]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   public void invokeHead(Map<Integer, ReadCellData<?>> headMap, AnalysisContext context) {
  log.info("解析到一条头数据:{}", JSON.toJSONString(headMap));
}
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述
这里读完的headMap参数。key是正常的0 1 2。 value的值是null。怎么解决

**Comment by gongxuanzhang** [comment]
传excel和完整代码

**Comment by noviceZ** [comment]
> 传excel和完整代码

通过代理上网 无法复制粘贴，我手打吧
excel:  表头【0|1|2|3|4|5|6】
          数据【A|B|C|D|E|F|G】
监听器获取表头代码如上。
调用代码：ExcelReader er = EasyExcel.read("path").build();
                 er.read(EasyExcel.readSheet(0).registerReadListener(new Listener()).build());

表头如果是字母或文字正常读出来，是数字的话读的是空。数据正常读取。
同时提示错误：An I/O error has occurred while writing a response message entity to the container output stream

**Comment by noviceZ** [comment]
> 我没法复现你的问题，你需要给我一个能复现的环境

没事 我再想想  谢谢哈
