### ISSUE TITLE
使用password设置密码后文件损坏

### ISSUE THREAD

**Issue by linbaochenggit** [alibaba/easyexcel#3077]
原本的写入
EasyExcel.write((OutputStream) response.getOutputStream()).head(headerList).automaticMergeHead(false).sheet(metaForm.getFormName()).doWrite(datas);
可以正常导出。
EasyExcel.write((OutputStream) response.getOutputStream()).password("111111").head(headerList).automaticMergeHead(false).sheet(metaForm.getFormName()).doWrite(datas);
文件损坏
![图片](https://user-images.githubusercontent.com/71746091/227885742-68619936-08d2-4e94-8f21-e7834637b8af.png)

![图片](https://user-images.githubusercontent.com/71746091/227885776-74923c48-3dfc-4538-a32e-8f6cf249978a.png)

**Comment by gongxuanzhang** [comment]
帖全代码

**Comment by gongxuanzhang** [comment]
加密之后用 easyexcel 密码解析。
都加密了你还想打开吗

**Comment by linbaochenggit** [comment]
> 
![图片](https://user-images.githubusercontent.com/71746091/228113857-eaa4f610-a6a8-4858-bb55-4f87e07005bd.png)
不报错还是文件损坏

**Comment by gongxuanzhang** [comment]
加密了你就不能用你的excel打开了   如果想解析你需要用easyexcel read
加密了你怎么打开？？？

**Comment by linbaochenggit** [comment]
> 加密了你就不能用你的excel打开了 如果想解析你需要用easyexcel read 加密了你怎么打开？？？

没有需要解析呀，现在的场景是我要写入数据后就加密，但是顺序问题是吗

**Comment by gongxuanzhang** [comment]
你加密的目的是什么？    压缩加密？

**Comment by linbaochenggit** [comment]
> 你加密的目的是什么？ 压缩加密？

场景是导出数据到excel并且加密，没有压缩

**Comment by gongxuanzhang** [comment]
你知道什么是加密吗
如果你是想要那种，打开输入密码的加密。
那你自己用其他的zip库解决   这不是easyexcel的功能

**Comment by gongxuanzhang** [comment]
你在过程中加入了其他过滤器吗  只有

**Comment by gongxuanzhang** [comment]
如果你有合并策略，使用不规范，是可能导致加密文件被破坏的

**Comment by gongxuanzhang** [comment]
默认表头是合并的 ，我觉得可能是表头的问题，你尝试用简单数据导出。 应该是没问题的

**Comment by gongxuanzhang** [comment]
参考这个issues
https://github.com/alibaba/easyexcel/issues/3086
如果没解决你把代码贴出来我给你解决

**Comment by BruceOuyang** [comment]
遇到了相同的问题，版本 2.1.4

代码：
```
EasyExcel.write(fileName, DemoData.class)
.password("1234")    // password 注释的时候，excel可以正常打开，加上之后输入密码后提示文件有问题
.sheet("demo")
.doWrite(list);
```
