### ISSUE TITLE
如何实现从多个excel模板(包含一个sheet)，填充到包含多个sheet的单个excel？有没有代码可供参考

### ISSUE THREAD

**Issue by chushiyan** [alibaba/easyexcel#3078]

**Comment by lonecloud** [comment]
这种是否可以将多个模板合并到一个模板上呢？然后通过模板进行填充，例子可参考`com.alibaba.easyexcel.test.temp.fill.FillTempTest#compositeFill`

**Comment by chushiyan** [comment]
> 
上百个模板，合并到一个模板不好维护。目前已经找到其他方案了。

**Comment by lemos1235** [comment]
> > 
> 
> 上百个模板，合并到一个模板不好维护。目前已经找到其他方案了。

打扰一下，能分享一下你的方案吗？
