### ISSUE TITLE
为什么有的excel可以，有的解析不了？

### ISSUE THREAD

**Issue by liuxm1218** [alibaba/easyexcel#3079]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   public class EasyExcelTestObj {
    public static void main(String[] args) throws FileNotFoundException {
        testStudentRead("C:\\Users\\Administrator\\Desktop\\图纸解析\\H7D09353.xls");
    }

    public static void testStudentRead(String targetFilePath) throws FileNotFoundException {
        List<Map<String, String>> dataList = new ArrayList<>();
        // 读取excel
        EasyExcelStudentListener listener = new EasyExcelStudentListener(dataList);
        EasyExcel.read(targetFilePath, listener).sheet(0).headRowNumber(4).doRead();
        // 输出读到的内容
        for (Map dto : dataList) {
            System.out.println(JSON.toJSONString(dto));
        }
    }
```
# 异常提示
Exception in thread "main" java.lang.NullPointerException
	at com.alibaba.excel.analysis.v03.handlers.DummyRecordHandler.processRecord(DummyRecordHandler.java:29)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processRecord(XlsSaxAnalyser.java:157)
	at org.apache.poi.hssf.eventusermodel.MissingRecordAwareHSSFListener.processRecord(MissingRecordAwareHSSFListener.java:156)
	at org.apache.poi.hssf.eventusermodel.FormatTrackingHSSFListener.processRecord(FormatTrackingHSSFListener.java:92)
	at org.apache.poi.hssf.eventusermodel.HSSFRequest.processRecord(HSSFRequest.java:106)
# 问题描述
这是我的excel文件
[H7D09353.xls](https://github.com/alibaba/easyexcel/files/11080089/H7D09353.xls)

**Comment by gongxuanzhang** [comment]
EasyExcelStudentListener是什么，代码贴全

**Comment by liuxm1218** [comment]
@gongxuanzhang 谢谢！
EasyExcelStudentListener就是一个普通的listener。如果新建一个excel，将上面要解析的excel内容拷进去，新建的excel是可以正常读取的。

**Comment by gongxuanzhang** [comment]
你改成xlsx吧

**Comment by liuxm1218** [comment]
![图片](https://user-images.githubusercontent.com/34080282/228100196-a7867bae-d16e-4a7a-a435-3bff42c47e39.png)

改成xlsx不行

**Comment by gongxuanzhang** [comment]
是存成xlsx  不是把文件后缀改成xlsx就完了

**Comment by liuxm1218** [comment]
是因为excel里面有宏吗？我用poi也做了测试，得到的都是跟宏相关的信息。
![图片](https://user-images.githubusercontent.com/34080282/228104783-7b523498-d73a-4d92-8a20-f9afc3c37cb3.png)

**Comment by gongxuanzhang** [comment]
可能是poi对xls的解析有冲突,解决了就好
