### ISSUE TITLE
在使用Converter接口时，能否使用枚举类来返回映射的值？

### ISSUE THREAD

**Issue by Lxxxxxxy** [alibaba/easyexcel#3083]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 建议描述
目前有很多字段是有枚举来做映射的，现在导出时我需要对每个枚举类进行转换，所以想能否支持按枚举类来直接做映射，而不是手动去写

**Comment by gongxuanzhang** [comment]
枚举Converter和普通Converter没有任何区别，你自定义就行了啊 。不懂你想问的问题

**Comment by Lxxxxxxy** [comment]
> 枚举Converter和普通Converter没有任何区别，你自定义就行了啊 。不懂你想问的问题

是这样，我现在有几十个枚举类，我不想每个导出都要写一个converter接口实现类，所以想问问有没有通用的方案

**Comment by gongxuanzhang** [comment]
你可以把这几十个枚举实现一个接口，然后把定义接口的converter

**Comment by gongxuanzhang** [comment]
你可以定义一个接口，让你的枚举实现。然后写这个接口的converter

**Comment by Lxxxxxxy** [comment]
> 你可以定义一个接口，让你的枚举实现。然后写这个接口的converter

是的，我刚才想到这个了，正在尝试

**Comment by gongxuanzhang** [comment]
甚至你可以直接写一个Enum的converter也可以。手动注册进你本次执行就可以

**Comment by gongxuanzhang** [comment]
```java
  public  class EnumConverter implements Converter<Enum<?>> {

        @Override
        public Class<?> supportJavaTypeKey() {
            return Enum.class;
        }
        @Override
        public WriteCellData<?> convertToExcelData(WriteConverterContext<Enum<?>> context) {
            return new WriteCellData<>("自定义：" + context.getValue().name());
        }
    }
```

**Comment by Lxxxxxxy** [comment]
> 
好的，谢谢，我试一下

**Comment by Lxxxxxxy** [comment]
> ```java
>   public  class EnumConverter implements Converter<Enum<?>> {
> 
>         @Override
>         public Class<?> supportJavaTypeKey() {
>             return Enum.class;
>         }
>         @Override
>         public WriteCellData<?> convertToExcelData(WriteConverterContext<Enum<?>> context) {
>             return new WriteCellData<>("自定义：" + context.getValue().name());
>         }
>     }
> ```
好的，谢谢，我试一下

**Comment by Crazy-x** [comment]
> > ```
> >   public  class EnumConverter implements Converter<Enum<?>> {
> > 
> >         @Override
> >         public Class<?> supportJavaTypeKey() {
> >             return Enum.class;
> >         }
> >         @Override
> >         public WriteCellData<?> convertToExcelData(WriteConverterContext<Enum<?>> context) {
> >             return new WriteCellData<>("自定义：" + context.getValue().name());
> >         }
> >     }
> > ```
> 
> 好的，谢谢，我试一下
这样写还是要在每个字段加注解吧

**Comment by Lxxxxxxy** [comment]
> > > ```
> > >   public  class EnumConverter implements Converter<Enum<?>> {
> > > 
> > >         @Override
> > >         public Class<?> supportJavaTypeKey() {
> > >             return Enum.class;
> > >         }
> > >         @Override
> > >         public WriteCellData<?> convertToExcelData(WriteConverterContext<Enum<?>> context) {
> > >             return new WriteCellData<>("自定义：" + context.getValue().name());
> > >         }
> > >     }
> > > ```
> > 
> > 
> > 好的，谢谢，我试一下
> > 这样写还是要在每个字段加注解吧

是的，是不行，我之前放弃了

**Comment by Lxxxxxxy** [comment]
> > > ```
> > >   public  class EnumConverter implements Converter<Enum<?>> {
> > > 
> > >         @Override
> > >         public Class<?> supportJavaTypeKey() {
> > >             return Enum.class;
> > >         }
> > >         @Override
> > >         public WriteCellData<?> convertToExcelData(WriteConverterContext<Enum<?>> context) {
> > >             return new WriteCellData<>("自定义：" + context.getValue().name());
> > >         }
> > >     }
> > > ```
> > 
> > 
> > 好的，谢谢，我试一下
> > 这样写还是要在每个字段加注解吧

我转换了下思路，实现了，不知道你那边是否可以这样使用
![image](https://github.com/alibaba/easyexcel/assets/42913395/90a4eb46-0471-4f8d-ac5a-e3fc040b540e)
EnumConvert是通用转换类，LocationAreaTypeEnum是我对应的枚举类
@EasyExcelConvertAnnotation是我自己定义的一个注解，主要传入一个枚举类
![image](https://github.com/alibaba/easyexcel/assets/42913395/1dd5f209-0542-44dc-b2c6-486db8f2e44b)
接着在通用转换类中使用excelContentProperty对象，将注解上的枚举类获取到，接着映射一下就可以了

**Comment by Crazy-x** [comment]
> celContentProperty对象，将注解上的枚举类获取到，接着映射一下就可以了

你搞这么麻烦干嘛，把导出VO类里面需要枚举的字段，设置成枚举类型，这个枚举实现一个接口，获取name，然后用通用枚举就行了啊

**Comment by Crazy-x** [comment]
![image](https://github.com/alibaba/easyexcel/assets/31130075/4da6bc19-b62f-4773-aa77-f2e83bd2e177)
![image](https://github.com/alibaba/easyexcel/assets/31130075/0dfcf060-0fbd-461b-8c8d-27400acbf6bc)
![image](https://github.com/alibaba/easyexcel/assets/31130075/101200b6-7a9b-4caf-b995-8125b171de21)
![image](https://github.com/alibaba/easyexcel/assets/31130075/73f95fc7-3ca0-4726-8c6c-7e82a42329e3)
泛型E是我自用的，可以不用带

**Comment by Crazy-x** [comment]
现在的问题是，每个枚举字段都要带上注解
 @ExcelProperty(converter = EnumConverter.class)
 我的意思是，不能全局注解EnumConverter，如果能注册，这个注解我都不用带

**Comment by Lxxxxxxy** [comment]
> > celContentProperty对象，将注解上的枚举类获取到，接着映射一下就可以了
> 
> 你搞这么麻烦干嘛，把导出VO类里面需要枚举的字段，设置成枚举类型，这个枚举实现一个接口，获取name，然后用通用枚举就行了啊

我的业务场景不能改字段类型，我这种适合我当前的业务

**Comment by Lxxxxxxy** [comment]
> ![image](https://user-images.githubusercontent.com/31130075/276514970-4da6bc19-b62f-4773-aa77-f2e83bd2e177.png) ![image](https://user-images.githubusercontent.com/31130075/276515091-0dfcf060-0fbd-461b-8c8d-27400acbf6bc.png) ![image](https://user-images.githubusercontent.com/31130075/276515208-101200b6-7a9b-4caf-b995-8125b171de21.png) ![image](https://user-images.githubusercontent.com/31130075/276515316-73f95fc7-3ca0-4726-8c6c-7e82a42329e3.png) 泛型E是我自用的，可以不用带

你的这种方式我考虑过，但是放弃了
