### ISSUE TITLE
是否支持组合注解的方式设置excel导出的样式

### ISSUE THREAD

**Issue by IsZxm** [alibaba/easyexcel#3091]
_依赖版本：2.2.6_
1、新建一个组合注解：
```
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.FIELD, ElementType.TYPE})
@Documented
@HeadStyle(fillPatternType = FillPatternType.SOLID_FOREGROUND)
@ColumnWidth(50)
public @interface SysExcelStyle {
}
```
2、应用于导出对象中：
```
@Data
@SysExcelStyle
public class IdExcelVO {
    @ApiModelProperty(value = "id", example = "1")
    private Integer id;
}
```

实际应用中发现@SysExcelStyle组合注解并未生效，导出的样式仍然是默认样式

**Comment by gongxuanzhang** [comment]
暂不支持，后续会支持

**Comment by lianyiwuming** [comment]
目前有两个办法处理默认设置：

1. 使用注解的继承特性。
       两步：定义抽象类A，用注解注释；具体的导出类继承A。
      
![image](https://user-images.githubusercontent.com/23331492/230586573-794628e7-a3df-4ba2-ad23-67a4baade72e.png)

2. 注册Handler。
       handler可以自定义。
       
![1680860694546](https://user-images.githubusercontent.com/23331492/230587265-4a865157-79a2-432e-a8bb-5866dc9f06eb.jpg)

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
