### ISSUE TITLE
请问如何更新一个已有的excel某一列

### ISSUE THREAD

**Issue by codxiao** [alibaba/easyexcel#3093]
需求是每次更新指定excel的某一列。
我的做法是使用easyExcel的withTemplate方式写文件，但是我翻了很久文档和源码，好像只能在原始文件的列后追加，没办法删掉原文件数据后重新写

**Comment by gongxuanzhang** [comment]
什么叫 每次更新指定的某一列。
如果你说的是修改一个已经存在的excel。
那只能全读之后重写，没办法修改某一个位置

**Comment by daouly** [comment]
EasyExcel.write(pathName, DemoData.class).inMemory(Boolean.TRUE)
            .registerWriteHandler(new CommentWriteHandler())
            .sheet("模板").doWrite(data());  // 用这个 registerWriteHandler 注册一个写操作，源码中的CommentWriteHandler implements RowWriteHandler ，
public class CommentWriteHandler implements RowWriteHandler {
    @Override
    public void afterRowDispose(RowWriteHandlerContext context) {
        log.info("--------rowindex:" + context.getRowIndex());
       // 每行第4列创建单元格，写入值
        if (BooleanUtils.isTrue(context.getHead())) {
            context.getRow().createCell(3).setCellValue("列头哈哈1");
        } else {
            context.getRow().createCell(3).setCellValue("哈哈哈哈哈2");
        }
    }

}

**Comment by yuthzi** [comment]
直接调用POI的接口修改
