### ISSUE TITLE
填充超链接

### ISSUE THREAD

**Issue by ppppppcl** [alibaba/easyexcel#3096]
在填充模板的时候怎么设置填充内容为超链接呢

**Comment by gongxuanzhang** [comment]
填充模板需要自定CellWriteHandle中手动加入

**Comment by ppppppcl** [comment]
> 填充模板需要自定CellWriteHandle中手动加入

感谢，设置成功了

**Comment by ppppppcl** [comment]
> 填充模板需要自定CellWriteHandle中手动加入

感谢，设置成功了
