### ISSUE TITLE
版导出excel,数量大了之后，后面的sheet wps展示样式问题

### ISSUE THREAD

**Issue by GoodYellow** [alibaba/easyexcel#3098]
模版导出excel,数量大了之后，后面的sheet wps展示样式展示有问题
` InputStream template = getInputStream("template/AllDrawExportTemplate.xlsx", proNameEnd, "施工图设计进度统计表");

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        //ExcelWriter该对象用于通过POI将值写入Excel
        ExcelWriter excelWriter = EasyExcel.write(out).withTemplate(template)
                //行注册
                .registerWriteHandler(excelFillCellMergeStrategyUtils)
                //列注册
                .registerWriteHandler(excelFillCellMergePrevColUtils)
                .registerWriteHandler(new CustomCellStyleStrategy(2))
                .build();
        //构建excel的sheet
        if (!CollectionUtils.isEmpty(allProDrawingList)) {
            for (int i = 0; i < allProDrawingList.size(); i++) {
                WriteSheet writeSheet = EasyExcel.writerSheet(i).build();
                excelWriter.fill(allProDrawingList.get(i).getAllDrawingList(), writeSheet);
            }
        } else {
            List<AllDrawingExportVO> allDrawingList = new ArrayList<>();
            WriteSheet writeSheet = EasyExcel.writerSheet().build();
            excelWriter.fill(allDrawingList, writeSheet);
        }
        excelWriter.finish()`

`Workbook workbook = sheet.getWorkbook();
        [//字体](url)
        CellStyle cellStyle = workbook.createCellStyle();
       // cellStyle.setFont(font);
        //水平居中
        cellStyle.setAlignment(HorizontalAlignment.CENTER);
        //垂直居中
        cellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
        //边框
        cellStyle.setBorderTop(BorderStyle.THIN);
        cellStyle.setBorderBottom(BorderStyle.THIN);
        cellStyle.setBorderLeft(BorderStyle.THIN);
        cellStyle.setBorderRight(BorderStyle.THIN);`

**Comment by GoodYellow** [comment]
[https://qtsk-sjxt.oss-cn-hangzhou.aliyuncs.com/public/dev/施工图设计进度统计表2023-03-30 11:32:53.xlsx](url)

**Comment by gongxuanzhang** [comment]
excel的样式对象是有上限的，如果能复用尽量复用

<img width="899" alt="image" src="https://user-images.githubusercontent.com/48286053/230838672-79eb736a-85fc-43d5-b6ba-97b1da98e036.png">


https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E4%BB%A3%E7%A0%81-11
