### ISSUE TITLE
读取excel文件，怎么读合并单元格中的数据

### ISSUE THREAD

**Issue by dreamSummer** [alibaba/easyexcel#310]

**Comment by fish7790714** [comment]
先尝试 把xlsx写成这样
![image](https://user-images.githubusercontent.com/18475586/55464169-12c61800-562d-11e9-921e-5d7d7198f84d.png)
然后 调用方法
```java
        writer.merge(0, 2, 1, 1);
        writer.merge(3, 5, 1, 1);
```
这样就可以了，实际使用 可以加上for循环

**Comment by zhuangjiaju** [comment]
升级版本会有更好的写法 ，请升级版本后参照demo书写
