### ISSUE TITLE
模板替换法导出 横向渲染数据时forceNewRow 失效会覆盖掉后面列的数据

### ISSUE THREAD

**Issue by blpjcsb** [alibaba/easyexcel#3107]
导出模板
![image](https://user-images.githubusercontent.com/130639339/231677286-35a462c9-5f60-4f62-99c0-71630ea3881b.png)
![image](https://user-images.githubusercontent.com/130639339/231677336-099c4e47-8503-44a7-bd4d-714cdc94e3a8.png)

**Comment by gongxuanzhang** [comment]
你这个不涉及填充的方向吧，你这个都是固定的 没有循环数据呀

**Comment by blpjcsb** [comment]
> 你这个不涉及填充的方向吧，你这个都是固定的 没有循环数据呀
中间对标单位那一列是list

**Comment by blpjcsb** [comment]
> 你这个不涉及填充的方向吧，你这个都是固定的 没有循环数据呀

导出后d列和e列都是list里面的数据

**Comment by gongxuanzhang** [comment]
你不应该把两个循环的数据放在一横排，你的数据结构组织有问题

**Comment by blpjcsb** [comment]
e列是一个对象 我的需求是d列的数据循环渲染完后 e列的数据紧跟在后面  我现在改成把d列和e列数据放在一个list里面了   我在使用easyexcel时 list向下渲染  list下方有对象的话 对象内容就会换行 不会被覆盖掉

**Comment by blpjcsb** [comment]
> 好嘞

**Comment by coder-tq** [comment]
这个问题解决了吗

> 建议你把 DE 列交换顺序，如果需求不允许.把E列放在list的最后一个数据，你的使用是对的。或者换成write方式。横向循环可能有一些问题，后续会改进
> 
> > e列是一个对象 我的需求是d列的数据循环渲染完后 e列的数据紧跟在后面 我现在改成把d列和e列数据放在一个list里面了 我在使用easyexcel时 list向下渲染 list下方有对象的话 对象内容就会换行 不会被覆盖掉
