### ISSUE TITLE
ReadDataListener  invoke 新版本若最后一列无数据  则会丢失一个null值 导致总列数不对

### ISSUE THREAD

**Issue by xiaoqi951109** [alibaba/easyexcel#3108]
和 issue 2983 同样的问题

用3.0.5版本就是正常的， 现在的话用3.2.1 最后一列 如果无值的话，invoke 里面那一行就会少一个最后的null。这感觉像是一个bug 

一共21列数据
![image](https://user-images.githubusercontent.com/14103130/231731422-dc580334-533b-4326-8584-77657edd462a.png)

![image](https://user-images.githubusercontent.com/14103130/231731472-dfc629a9-8939-4d82-85d4-35a533332717.png)
![image](https://user-images.githubusercontent.com/14103130/231731485-6def5ae6-6059-49bb-a878-491fe3f17659.png)

**Comment by xiaoqi951109** [comment]
package com;

import com.alibaba.excel.EasyExcel;
import com.alibaba.excel.context.AnalysisContext;
import com.alibaba.excel.event.AnalysisEventListener;
import com.alibaba.excel.read.builder.ExcelReaderBuilder;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.Map;

public class Test {

    public static void main(String[] args) {
        //测试文件下载地址 https://file.ai.kxkx888.com/upload/file/20230413/168134782373902689.xlsx
        String filePath = "C:\\Users\\26901\\Desktop\\test.xlsx";
        try {
            //根据魔数校验文件类型  todo
            BufferedInputStream bufferedInputStream = null;
            try {
                bufferedInputStream = new BufferedInputStream(new FileInputStream(filePath));
            } catch (Exception e) {
                e.printStackTrace();
                throw e;
            } finally {
                if (null != bufferedInputStream) {
                    bufferedInputStream.close();
                }
            }
            ExcelReaderBuilder excelReaderBuilder = EasyExcel.read(new File(filePath));//线上用；
            excelReaderBuilder.registerReadListener(new ReadDataListener()).headRowNumber(2);
            excelReaderBuilder.sheet(0).doRead();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static class ReadDataListener extends AnalysisEventListener<Map<Integer, String>> {
        @Override
        public void invoke(Map<Integer, String> integerStringMap, AnalysisContext analysisContext) {
            System.out.println("size:" + integerStringMap.size());
        }

        @Override
        public void doAfterAllAnalysed(AnalysisContext analysisContext) {

        }
    }
}

**Comment by xiaoqi951109** [comment]
@gongxuanzhang    这里有下载地址  和复现代码

**Comment by xiaoqi951109** [comment]
![1681436842061](https://user-images.githubusercontent.com/14103130/231920609-dc9909d3-20a3-4e52-a86e-e2358c4ebbc8.jpg)
![1681436795353](https://user-images.githubusercontent.com/14103130/231920622-2ec7b32c-e40d-49f4-ac2e-06e0cf606267.jpg)

**Comment by xiaoqi951109** [comment]
这是我不同版本执行的结果

**Comment by gongxuanzhang** [comment]
额   下载地址我没看到

**Comment by xiaoqi951109** [comment]
> 

![image](https://user-images.githubusercontent.com/14103130/231924456-6d634401-a93a-4e19-be29-db7e03037b0a.png)

**Comment by gongxuanzhang** [comment]
哦哦  抱歉

**Comment by xiaoqi951109** [comment]
@gongxuanzhang  大佬  请问该问题您能复现么，这边如果有什么参数配置可以设置的话可以告诉我 我尽早用上3.2.1   如果要等下一个版本的话   方便问一下有大概的预期时间么

**Comment by xiaoqi951109** [comment]
@zhuangjiaju  大佬 这个是新版本哪里要改什么参数配置么

**Comment by gongxuanzhang** [comment]
这边建议你定义一个实体，可能是excel的问题，

**Comment by xiaoqi951109** [comment]
但是我们业务系统是无实体类结构的后端 而且参数值也不固定的，不太好定义实体。  然后这个excel 在老版本是正常的，是新版本什么判断的情况变得严格了么

**Comment by xiaoqi951109** [comment]
很多情况下客户可能也是复制别的excel的数据进来 用于导入    格式的话没办法保证一定要是怎么样， 目前我看起来excel还算是正常的，  这种情况 我跟客户说 你传过来的excel不对，他们无法理解，而且在之前都可以  他们可能认为是我们有问题

**Comment by gongxuanzhang** [comment]
没有变，你哪个版本是好用的   我去对比一下

**Comment by xiaoqi951109** [comment]
3.0.5

**Comment by gongxuanzhang** [comment]
```java
 static class ReadDataListener extends AnalysisEventListener<Map<Integer, String>> {

        @Override
        public void invokeHead(Map<Integer, ReadCellData<?>> cellDataMap, AnalysisContext context) {
            context.readSheetHolder().setMaxNotEmptyDataHeadSize(CollectionUtils.size(cellDataMap));
        }

        @Override
        public void invoke(Map<Integer, String> integerStringMap, AnalysisContext analysisContext) {
            System.out.println("size:" + integerStringMap.size());
        }

        @Override
        public void doAfterAllAnalysed(AnalysisContext analysisContext) {

        }
    }
```

**Comment by gongxuanzhang** [comment]
暂时用这种方式修改吧

**Comment by gongxuanzhang** [comment]
确实两个版本有改动，你先用这种方式解决问题  
后面我会关注一下这个  感谢你

**Comment by xiaoqi951109** [comment]
可以了  感谢你 @gongxuanzhang

**Comment by gongxuanzhang** [comment]
好的
