### ISSUE TITLE
读取excel里面点击单元格才能看到的内容

### ISSUE THREAD

**Issue by unclexuya** [alibaba/easyexcel#3109]
//文件解析
        ExcelReader build = EasyExcelFactory.read(fileInputStream,listener)
                //文件类型
                .excelType(fileAttributes.getExcelTypeEnum())
                //编码
                .charset(fileAttributes.getCharset())
                //表头所在行
                .headRowNumber(10)
                //不忽略空行
                .ignoreEmptyRow(false)
                .readDefaultReturn(ReadDefaultReturnEnum.READ_CELL_DATA)
                .build();
    设置了ReadDefaultReturnEnum.READ_CELL_DATA，但是监听的返回的时间类型还是BigDecimal
    public void invokeHead(Map<Integer, ReadCellData<?>> headMaps, AnalysisContext context)
    单元格不点击内容是2023/4/12 11:20，点击后2023/4/12 11:20:30
    版本是最新版3.2.1

**Comment by gongxuanzhang** [comment]
这个应该是你excel设置有关把。
你可以试试修改poi参数有没有改善，如果可以的话直接写在Writehandler中就好

**Comment by unclexuya** [comment]
好的
