### ISSUE TITLE
“&”导致数据读取错位

### ISSUE THREAD

**Issue by lurkerw** [alibaba/easyexcel#311]
表格中有AA&ZZ导致封装时数据错乱
![image](https://user-images.githubusercontent.com/38005052/56403350-80ac4980-6293-11e9-9f9f-43fe9d067a18.png)
![image](https://user-images.githubusercontent.com/38005052/56403355-8bff7500-6293-11e9-9934-a319a020d12a.png)

**Comment by fish7790714** [comment]
我测试了读取中有 AA&ZZ 并没有问题

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
