### ISSUE TITLE
导出复杂模板的excel

### ISSUE THREAD

**Issue by xiaole5** [alibaba/easyexcel#3111]
![1](https://user-images.githubusercontent.com/106718739/232075065-54cd0922-bf74-4f4c-90be-7639751851f5.png)
各位大佬，请问导出这样格式的excel，应该怎么封装数据结构呢？

**Comment by gongxuanzhang** [comment]
可以参考https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E4%BD%BF%E7%94%A8table%E5%8E%BB%E5%86%99%E5%85%A5

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
