### ISSUE TITLE
使用@NumberFormat("#,##0.00") 导出金额 ，excel中的金额类变成 #### ,自适应宽度失效

### ISSUE THREAD

**Issue by karrley** [alibaba/easyexcel#3117]
代码如下

```
    /**
     * 合同金额(单位:分)
     */
    @HeadStyle(fillPatternType = FillPatternTypeEnum.SOLID_FOREGROUND, fillForegroundColor = 10)
    @ExcelProperty("合同额")
    @ColumnWidth(value = 100)
    @NumberFormat("#,##0.00")
    private BigDecimal actualContractAmount;
```
版本3.1.5

**Comment by tmlx1990** [comment]
您好，您可以尝试下最新版本，刚我使用3.2.1没有可以正常显示。
<img width="862" alt="image" src="https://user-images.githubusercontent.com/5753992/232659296-ebb9b6d6-486d-4202-93f2-73f7c13e125f.png">

<img width="635" alt="image" src="https://user-images.githubusercontent.com/5753992/232659365-8e67bf6b-d31f-41a5-8a15-4ad10a134d63.png">

**Comment by karrley** [comment]
> 
使用这个就不好使了
.registerWriteHandler(new LongestMatchColumnWidthStyleStrategy())

**Comment by tmlx1990** [comment]
> > 
> 
> 使用这个就不好使了 .registerWriteHandler(new LongestMatchColumnWidthStyleStrategy())

能提供下完整的代码吗？ 
我测试是使用最简单的方式写的。
<img width="833" alt="image" src="https://user-images.githubusercontent.com/5753992/232665875-ae139424-0fc3-4308-abda-1d3596a01134.png">
