### ISSUE TITLE
您好，我想咨询下，最新版本，是否同时支持动态表头和行的自定义合并

### ISSUE THREAD

**Issue by muyifeiyang** [alibaba/easyexcel#3119]
# 问题描述
您好，我想咨询下，最新版本，是否同时支持动态表头和行的自定义合并

**Comment by muyifeiyang** [comment]
表格中的某些列可能会存在一对多情况

**Comment by gongxuanzhang** [comment]
表头如下https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E5%A4%8D%E6%9D%82%E5%A4%B4%E5%86%99%E5%85%A5

合并单元格
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E5%90%88%E5%B9%B6%E5%8D%95%E5%85%83%E6%A0%BC

如果你需要把表头和数据合并，需要自定以拦截器实现  因为概念上表头和数据是两种东西，如果你要合并  就已经超越概念了

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
