### ISSUE TITLE
大佬，读excel数据大的时候，如果我用main测试方式循环很快？用框架测试接口访问就读取特别慢？为啥啊？

### ISSUE THREAD

**Issue by seaguil** [alibaba/easyexcel#312]

**Comment by seaguil** [comment]
4千行数据，用main方法读取循环9秒结束，用接口访问90秒，我都排查不出啥问题了，难道是我框架的问题？我是springboot+通用mapper的，这一定不影响吧，愁死我了

**Comment by fish7790714** [comment]
先贴代码 这样说查询不出问题的

**Comment by seaguil** [comment]
![image](https://user-images.githubusercontent.com/38853650/56416413-5a9e9d80-62c3-11e9-84f5-ae6f884778d2.png)
这个是测试代码，不到4千行，监听类里面循环只用了9秒左右
![image](https://user-images.githubusercontent.com/38853650/56416529-b6692680-62c3-11e9-87d5-6286446ce92b.png)
同样的监听类，我在service调用，他就执行的特别慢。我哭死心都有了
![image](https://user-images.githubusercontent.com/38853650/56416674-30011480-62c4-11e9-93d1-06c207712d31.png)

**Comment by seaguil** [comment]
我在测试和main方法里面运行都是很快的，但是一在项目框架里面调用就很慢，同一个监听类，处理通用的业务，执行速度不一样，我真的就懵逼了，笑死~

**Comment by fish7790714** [comment]
listener 也发下吧 循环次数 27W 什么意思？问题应该是 在listener 。 你插入数据库用了一条条插入。然后所有时间耗费在网络上面

**Comment by seaguil** [comment]
这是监听类
package com.zcf.universe.common.excel;

import com.alibaba.excel.context.AnalysisContext;
import com.alibaba.excel.event.AnalysisEventListener;
import com.zcf.universe.common.utils.DateUtils;
import com.zcf.universe.mapper.JrkMapper;
import org.apache.poi.hssf.usermodel.HSSFDateUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.util.StringUtils;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

/**
 * 净入库excel 解析
 */
public class TestListener extends AnalysisEventListener {

    private static final Logger logger = LoggerFactory.getLogger(TestListener.class);
    //监听类是无法通过@Autowired注入的，需要通过构造注入
/*    private JrkMapper jrkMapper;

    public TestListener(JrkMapper jrkMapper) {
        super();
        this.jrkMapper = jrkMapper;
    }*/

    //所属文件id
    public Long fileId;
    //文件名称
    public String fileName;
    //表头模板数据
    String[] title = {};
    //结果集
    private List<Object> data = new ArrayList<Object>();

    //结果集数量
    public Integer addSize;

    //插入数量
    public Integer addCount;

    @Override
    public void invoke(Object object, AnalysisContext context) {
        logger.info("当前行数据为：" + object);
        data.add(object);
        try {
            //拿到表头
            if (data.size() == 1) {
                title = handleData(object);
            } else {
                //数据从1开始便利循环
                String currentData[] = handleData(object);
                String excelTitle = "";
                for (int i = 0; i < title.length; i++) {
                    if (StringUtils.isEmpty(title[i])) {
                        continue;
                    }
                    //处理业务
                    excelTitle = title[i].trim();
                    System.out.println(data.size() + " 行 数据为：" + currentData[i]);
                }
                //存入数据库
                 /*
                jrk.setCreateTime(new Date());
                int count = jrkMapper.insert(jrk);
                if (count > 0) {
                    logger.info("当前数据：{}插入数据库信息成功", object);
                }*/
            }
        } catch (Exception o) {
            o.printStackTrace();
            logger.error("JrkExcelListener类-》解析错误:{}", o.getMessage());
        }
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
        doSomething();
    }

    public void doSomething() {
        //根据文件id查询插入成功数量，和data数据对比
        logger.info("解析文件：{}結束", fileName);
        addSize = (data.size() - 1);
        logger.info("解析总条数为：{}", addSize);
        //addCount = jrkMapper.findAddCount(fileId);
        //logger.info("插入数据库总条数为：{}", addCount);
    }

    /**
     * 处理数据，object返回string 数组
     *
     * @param object
     * @return
     */
    public String[] handleData(Object object) {
        try {
            List<String> list = (List) object;
            for (int i = 0; i < list.size(); i++) {
                System.out.println(i + ": " + list.get(i));
            }
            String[] array = {};
            if (title.length == 0) {
                //第一次
                array = new String[list.size()];
            } else {
                array = new String[title.length];
            }
            String[] data = list.toArray(array);
            System.out.println("转换过数组：" + Arrays.toString(data));
            return data;
        } catch (Exception e) {
            logger.error("JrkExcelListener类-》Object数据转换错误:{}", e.getMessage());
            e.printStackTrace();
        }
        return null;
    }

    /**
     * 处理日期
     *
     * @param value
     * @return
     * @throws Exception
     */
    public Date handleDate(String value) throws Exception {
        Date date = null;
        //3种excel格式处理2018-01-01、2018-01-01 12:00：12、2018/1/1
        if (!StringUtils.isEmpty(value)) {
            if (value.indexOf("-") > 0) {
                if (value.length() > 10) {
                    date = DateUtils.dateParse(value, DateUtils.HOUR_PATTERN);
                } else {
                    date = DateUtils.dateParse(value, DateUtils.DATE_PATTERN);
                }
            } else {
                date = HSSFDateUtil.getJavaDate(new Double(value));
            }
        }
        return date;
    }
}

如下这是测试调用类
package com.zcf.universe.common.excel;

import com.alibaba.excel.EasyExcelFactory;
import com.alibaba.excel.metadata.Sheet;
import com.zcf.universe.common.utils.FileUtil;
import com.zcf.universe.service.JrkService;
import com.zcf.universe.vo.out.AnalysisVo;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.io.InputStream;

public class Read {
    private static final Logger logger = LoggerFactory.getLogger(JrkService.class);

    /**
     * 模拟api请求测试
     *
     * @param file
     * @param fileName
     * @param fileId
     * @param headLineMun
     * @return
     */
    public static AnalysisVo analysisExcel(MultipartFile file, String fileName, Long fileId, Integer headLineMun) {
        Long start = System.currentTimeMillis();
        InputStream inputStream = null;
        try {
            //方面为了测试，从本地获取excel
            inputStream = FileUtil.getResourcesFileInputStream("净入库（大数据）.xlsx");
            TestListener listener = new TestListener();
            //赋值刚上传的文件id
            listener.fileId = fileId;
            listener.fileName = fileName;
            //从传入表头行数开始解析
            EasyExcelFactory.readBySax(inputStream, new Sheet(1, headLineMun), listener);
            AnalysisVo vo = new AnalysisVo();
            vo.setFileName(fileName);
            vo.setAddSize(listener.addSize);
            vo.setAddCount(listener.addCount);
            Long end = System.currentTimeMillis();
            logger.info("执行excel时间：" + ((end - start) / 1000) + "秒");
            return vo;
        } catch (Exception o) {
            o.printStackTrace();
            return null;
        } finally {
            try {
                if (inputStream != null) {
                    inputStream.close();
                }
            } catch (IOException e) {
                logger.error("方法：analysisExcel流关闭异常:{}" + e.getMessage());
            }
        }
    }

    public static void main(String[] args) {
        analysisExcel(null, "净入库（大数据）", 118L, 2);
    }
}

如下是main方式调用时间
![image](https://user-images.githubusercontent.com/38853650/56417757-7d32b580-62c7-11e9-9989-fe57dae558a4.png)
接下来是接口调用
![image](https://user-images.githubusercontent.com/38853650/56418179-c6373980-62c8-11e9-90b2-76627280c013.png)
我这个只是监听里面写了个循环，还没到数据库插入操作，main 方法调用和接口调用时间差别太大。我真的是懵逼了，大佬

**Comment by fish7790714** [comment]
jrkMapper.insert(jrk) 这行代码删了 试试 。

**Comment by seaguil** [comment]
> jrkMapper.insert(jrk) 这行代码删了 试试 。

我这里已经注释了，大佬

**Comment by seaguil** [comment]
> > jrkMapper.insert(jrk) 这行代码删了 试试 。
> 
> 我这里已经注释了，大佬

我现在就是排除数据库插入的问题，就是同一个监听类执行固定循环，我就看看，排除其他因素之外，main方法调用和接口调用的区别，现在就卡在这里了，2个调用方式执行速度相差10倍，我懵逼了。。。。。

**Comment by fish7790714** [comment]
invoke 第一行 最后一行 输出下日志 看下 是不是老子花时间了

**Comment by fish7790714** [comment]
invoke 第一行 最后一行 输出下日志 看下 是不是这里花时间了

**Comment by seaguil** [comment]
![image](https://user-images.githubusercontent.com/38853650/56418738-6d68a080-62ca-11e9-8a5b-54f82c6d8537.png)
main方法测试，基本间隔都是1毫秒

- -- -  - - -

接口调用都是20hm
![image](https://user-images.githubusercontent.com/38853650/56418845-c1738500-62ca-11e9-99be-492baa8e0caf.png)

大佬我真的，，，，难受了一笔啊

**Comment by seaguil** [comment]
> invoke 第一行 最后一行 输出下日志 看下 是不是这里花时间了

我从来没有遇到过这样的问题出现，我一直以为其他地方处理数据，或者插入数据库影响了时间，但是经过层层测试，其他都没有干扰，我现在但就是调用方式不同，导致了这个问题时间差这么大。。。。

**Comment by fish7790714** [comment]
这个不是很简单了啊 你多加点输出 就行了啊。看下 哪个东西在20里面占大头了就行了啊

**Comment by seaguil** [comment]
> 这个不是很简单了啊 你多加点输出 就行了啊。看下 哪个东西在20里面占大头了就行了啊

那我是main 方法调用会很快呢？这个是根本问题的，我先按照你的说法先看看哪里执行了20hm比例重吧

**Comment by seaguil** [comment]
![image](https://user-images.githubusercontent.com/38853650/56419638-81fa6800-62cd-11e9-9844-8ac6de737082.png)
是处理object 转数组的时间长，占了很大比重
![image](https://user-images.githubusercontent.com/38853650/56419708-c71e9a00-62cd-11e9-8b56-e997983b9d1a.png)

但是我用main方法执行，循环占用的时间多，我蒙蔽了，我要自闭了大佬，哭哭哭哭~

**Comment by seaguil** [comment]
> > 这个不是很简单了啊 你多加点输出 就行了啊。看下 哪个东西在20里面占大头了就行了啊
> 
> 那我是main 方法调用会很快呢？这个是根本问题的，我先按照你的说法先看看哪里执行了20hm比例重吧

按照你的方法，用接口调用时候，处理object数据变数组时间长，用main方法调用，循环时间长，大佬我该怎么办 ，哭哭哭

**Comment by seaguil** [comment]
> > > 这个不是很简单了啊 你多加点输出 就行了啊。看下 哪个东西在20里面占大头了就行了啊
> > 
> > 
> > 那我是main 方法调用会很快呢？这个是根本问题的，我先按照你的说法先看看哪里执行了20hm比例重吧
> 
> 按照你的方法，用接口调用时候，处理object数据变数组时间长，用main方法调用，循环时间长，大佬我该怎么办 ，哭哭哭
    /**
     * 处理数据，object返回string 数组
     *
     * @param object
     * @return
     */
    public String[] handleData(Object object) {
        try {
            List<String> list = (List) object;
            for (int i = 0; i < list.size(); i++) {
                System.out.println(i + ": " + list.get(i));
            }
            String[] array = {};
            if (title.length == 0) {
                //第一次表头长度
                array = new String[list.size()];
            } else {
                array = new String[title.length];
            }
            String[] data = list.toArray(array);
            //System.out.println("转换过数组：" + Arrays.toString(data));
            return data;
        } catch (Exception e) {
            logger.error("》Object数据转换错误:{}", e.getMessage());
            e.printStackTrace();
        }
        return null;
    }
我这个处理objec方法还分调用方式的吗，我就笑哭了

**Comment by seaguil** [comment]
大佬，我期待等你的完美解答，我真是遇到这坑过不去了，小生在这里谢谢你了，祝你有个愉快的周末，谢谢你

**Comment by fish7790714** [comment]
我感觉你对这个框架 有点误解。写法 不是特别好,主要是也是原版的demo没写好，数据转换，处理头根本不是你要考虑的事情。
1. 读取的时候加入 headLineMun 传1 代表 忽略第一条头
```java

   EasyExcelFactory.readBySax(inputStream, new Sheet(2, 1, ReadModel.class), excelListener);
```

2. 使用泛型 在 AnalysisEventListener传入泛型 ReadModel，然后 invoke方法返回的就是ReadModel 了
```java
public class ExcelListener extends AnalysisEventListener<ReadModel> {

    private List<Object> data = new ArrayList<Object>();

    @Override
    public void invoke(ReadModel object, AnalysisContext context) {
        System.out.println(context.getCurrentSheet());
        data.add(object);
        if (data.size() >= 100) {
            doSomething();
            data = new ArrayList<Object>();
        }
    }

}
```

**Comment by seaguil** [comment]
> 我感觉你对这个框架 有点误解。写法 不是特别好,主要是也是原版的demo没写好，数据转换，处理头根本不是你要考虑的事情。
> 
> 1. 读取的时候加入 headLineMun 传1 代表 忽略第一条头
> 
> ```java
>    EasyExcelFactory.readBySax(inputStream, new Sheet(2, 1, ReadModel.class), excelListener);
> ```
> 
> 1. 使用泛型 在 AnalysisEventListener传入泛型 ReadModel，然后 invoke方法返回的就是ReadModel 了
> 
> ```java
> public class ExcelListener extends AnalysisEventListener<ReadModel> {
> 
>     private List<Object> data = new ArrayList<Object>();
> 
>     @Override
>     public void invoke(ReadModel object, AnalysisContext context) {
>         System.out.println(context.getCurrentSheet());
>         data.add(object);
>         if (data.size() >= 100) {
>             doSomething();
>             data = new ArrayList<Object>();
>         }
>     }
> 
> }
> ```

你好，回答1，为啥我要处理头部，因为我的业务需要根据头部的表头做判断处理，导入的excel不是很规范的，顺序不一样的，而且表头不是都在固定的某一行的（政府项目~~哭）。
回答2，为啥我不用Model ，也是因为业务需求没有明确的规范制度，所以我只能拿到每一行的数据对象做对应的业务处理。
以上交流了这么多，在你的帮助下我也 已经排查出解析慢的原因了（就是处理List<object>数据慢），但是我还是解决不了根本的问题，
或者，大佬有没有推荐List<object>数据转 String [] 数组比较高效的方法。
最后，我还是无法理解，通用的监听业务类，在接口调用和main方法调用的执行效率差太多。

**Comment by seaguil** [comment]
> 我感觉你对这个框架 有点误解。写法 不是特别好,主要是也是原版的demo没写好，数据转换，处理头根本不是你要考虑的事情。
> 
> 1. 读取的时候加入 headLineMun 传1 代表 忽略第一条头
> 
> ```java
>    EasyExcelFactory.readBySax(inputStream, new Sheet(2, 1, ReadModel.class), excelListener);
> ```
> 
> 1. 使用泛型 在 AnalysisEventListener传入泛型 ReadModel，然后 invoke方法返回的就是ReadModel 了
> 
> ```java
> public class ExcelListener extends AnalysisEventListener<ReadModel> {
> 
>     private List<Object> data = new ArrayList<Object>();
> 
>     @Override
>     public void invoke(ReadModel object, AnalysisContext context) {
>         System.out.println(context.getCurrentSheet());
>         data.add(object);
>         if (data.size() >= 100) {
>             doSomething();
>             data = new ArrayList<Object>();
>         }
>     }
> 
> }
> ```

希望大佬，能结合我以上的问题，给我个建议或者其他的执行方案。小生在这里多谢了。

**Comment by fish7790714** [comment]
你在 ```java String[] data = list.toArray(array);``` 这行代码 上面下面 输出国日志了？这个效率肯定很高的。你看下size ,

**Comment by seaguil** [comment]
> 你在 `java String[] data = list.toArray(array);` 这行代码 上面下面 输出国日志了？这个效率肯定很高的。你看下size ,
首先在这里还是谢谢了，根据你的要求我又在size前后打印输出时间、转数组前后打印时间，结果执行效率果然很高，在我不经意之间发现有一行多余代码，我简直不敢相信！！！！！！！！
System.out.println(i + ": " + list.get(i));
就是它，我以前只是听过少用System.out输出的警告，但是不怎么在意，今天我是彻底了解她竟然这么影响性能，还有系统配置的logger日志多多少少也会影响性能，我把带有System.out函数和logger输出全部去掉之后，和main方法执行后的效率时间一样的了，logger也会占用很高的系统资源和性能。
现在4k行数据不到10秒左右还能接受。看看在数据库插入时候再做一些相关优化操作。
![image](https://user-images.githubusercontent.com/38853650/56546884-39cd9500-65ae-11e9-8d33-d062fa8325a7.png)
希望有其他小伙伴遇到我相同问题，大佬可以帮忙及时定位解决，哈哈哈哈~3Q

**Comment by fish7790714** [comment]
日志输出是性能影响很大 但是你这么大估计是你硬盘有问题……

**Comment by seaguil** [comment]
> 日志输出是性能影响很大 但是你这么大估计是你硬盘有问题……

硬不硬盘的我不知道，反正去掉System.out和logger之后，很快了。
![image](https://user-images.githubusercontent.com/38853650/56630919-baab9000-6685-11e9-8cc6-1c72b69105b8.png)
开发环境为了方便测试，输出到控制台来看信息的，等发布之后直接异步到文件，也就不存在logger输出问题了，哈哈哈，因为这输出问题让我老懵逼了，这次真真正正长记性了
