### ISSUE TITLE
多个list是否支持？

### ISSUE THREAD

**Issue by liangrj914** [alibaba/easyexcel#3122]
类似于下面这种格式，list里面包含表头
![image](https://user-images.githubusercontent.com/101916802/233231729-019b780c-a5b9-4098-95e0-f78ce57ce5b0.png)

**Comment by gongxuanzhang** [comment]
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E4%BD%BF%E7%94%A8table%E5%8E%BB%E5%86%99%E5%85%A5
参考这个文档

**Comment by liangrj914** [comment]
填充模版的方式也支持这种方式吗

**Comment by gongxuanzhang** [comment]
暂时不支持，建议使用write方式
