### ISSUE TITLE
模板{}转义问题

### ISSUE THREAD

**Issue by Wu-Z-J** [alibaba/easyexcel#3125]
# 异常代码
```java
// 设置强制公式计算
ExcelWriter writer = EasyExcel.write(outputFile).withTemplate(templateFile).build();
Workbook workbook = writer.writeContext().writeWorkbookHolder().getWorkbook();
workbook.setForceFormulaRecalculation(true);
ExcelWriterSheetBuilder excelWriterSheetBuilder = new ExcelWriterSheetBuilder(writer);
// 填充数据
excelWriterSheetBuilder.doFill(list, FillConfig.builder().build());
writer.finish();
```
# 问题描述
这是我导入Excel的模板。
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/75168110/233290228-5aa47df6-d47b-474a-b3ec-b7a955f590e3.png">
导出模板之后，\{和\}并没有转化为{}，而是继续显示\{\}。
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/75168110/233290339-28e99aee-b8b8-4a7a-975a-9a7526c13a66.png">

**Comment by gongxuanzhang** [comment]
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/fill
把转义字符去掉

**Comment by Edwin-Xu** [comment]
本身就有转义字符，导出后不会还原吗 
![image](https://github.com/alibaba/easyexcel/assets/38159112/61b853aa-dc76-4559-b448-c65890745697)

**Comment by Edwin-Xu** [comment]
![image](https://github.com/alibaba/easyexcel/assets/38159112/32a9ca1c-02c2-4f11-83b7-58f341b4c522)

**Comment by Edwin-Xu** [comment]
模板，填充的值本身是 {} 格式 ，也有问题
![image](https://github.com/alibaba/easyexcel/assets/38159112/2b4df6df-28b2-4df1-9c13-0bd36122b043)

**Comment by Edwin-Xu** [comment]
会多空出来一行
