### ISSUE TITLE
如何使用拦截器修改表头的字体样式

### ISSUE THREAD

**Issue by anglehome** [alibaba/easyexcel#3134]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
  @Override
            public void afterCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Cell cell, Head head, Integer integer, Boolean aBoolean) {
                FontProperty fontProperty = new FontProperty();
                fontProperty.setFontHeightInPoints((short)18); // 调整字体大小
                head.setHeadFontProperty(fontProperty);
                head.setContentFontProperty(fontProperty);
            }
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述
这几天在处理复杂表格，发现无论对拦截器里的head对象如何操作，都无法修改表格的表头字体样式，请问这里应该如何才能修改表头字体样式

**Comment by gongxuanzhang** [comment]
参考自定义样式
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E4%BB%A3%E7%A0%81-11

注意
<img width="868" alt="image" src="https://user-images.githubusercontent.com/48286053/233814157-6a1db367-12ae-4fc6-b5c0-af76ff4c960f.png">

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
