### ISSUE TITLE
列为长整型，导出后变成科学计数法，无法再导入

### ISSUE THREAD

**Issue by jeesun** [alibaba/easyexcel#314]
因为列是长整型，导出后变成科学计数法，无法再导入，会报如下错误
```
com.alibaba.excel.exception.ExcelGenerateException: java.lang.NumberFormatException: For input string: "1.0E9"
```
原本是1000000000，变成科学记数法1.E9了。

**Comment by jeesun** [comment]
我把WorkBookUtil.java第67行代码`cell.setCellValue(Double.parseDouble(cellValue.toString()));`改成`cell.setCellValue(cellValue.toString());`解决了该问题。

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。使用`NumberFormat`注解或者自定义转换器都可以

**Comment by gaochuanneu** [comment]
使用2.0.3 如果导出 类型为长整型或者string,导出后excel点击进某个数据框内再出来,数据就会发生变化 依旧有丢位情况,比如7495396815497821会变成7495396815497820
