### ISSUE TITLE
关于相同副标题合并的问题

### ISSUE THREAD

**Issue by xunComeon** [alibaba/easyexcel#3140]
现在的需求是：不同的主标题，相同的副标题，副标题能否不进行合并效果
有什么方式可以实现导出是如下这种效果
![image](https://user-images.githubusercontent.com/60594799/233906245-e79bfa90-57aa-4c06-b2c4-779407955a65.png)
而不是这个效果
![image](https://user-images.githubusercontent.com/60594799/233906282-2e757529-c335-4334-b6fb-34e2058fc873.png)

**Comment by gongxuanzhang** [comment]
EasyExcel.write(file).automaticMergeHead(Boolean.FALSE)

设置automaticMergeHead 为false即可

**Comment by xunComeon** [comment]
![image](https://user-images.githubusercontent.com/60594799/233932164-03b1ddfc-bd24-4045-9d24-f12c51c4f66e.png)
设置automaticMergeHead 为false后所有的列都合并了啊，有可以指定哪几列不合并，哪几列合并的吗，就图中这个效果

**Comment by gongxuanzhang** [comment]
没有，自己 用拦截器实现吧

> ![image](https://user-images.githubusercontent.com/60594799/233932164-03b1ddfc-bd24-4045-9d24-f12c51c4f66e.png) 设置automaticMergeHead 为false后所有的列都合并了啊，有可以指定哪几列不合并，哪几列合并的吗，就图中这个效果

**Comment by xunComeon** [comment]
好的，谢谢了啊
