### ISSUE TITLE
求解：easyexcel读取多个sheet，48多w条数据的excel，耗时很长。

### ISSUE THREAD

**Issue by Y-Stone** [alibaba/easyexcel#3147]
# 异常代码
```java
  @Test
    public void testReadBigDataExcel2() {
        File targetFile = new File("C:\\Users\\Administrator\\Desktop\\能链2月.xlsx");
        long begin = System.currentTimeMillis();
        List<ReceiptBillDataExcel> list1 = new ArrayList<>();
        List<ReceiptBillDataExcel> list2 = new ArrayList<>();
        ExcelReader excelReader = EasyExcel.read(targetFile).build();
        long finalBegin1 = begin;
        ReadSheet readSheet = EasyExcel.readSheet(0).head(ReceiptBillDataExcel.class).registerReadListener(new AnalysisEventListener<ReceiptBillDataExcel>() {


            @Override
            public void invokeHeadMap(Map<Integer, String> headMap, AnalysisContext context) {
            }

            @Override
            public void invoke(ReceiptBillDataExcel data, AnalysisContext context) {
                list1.add(data);
            }

            @Override
            public void doAfterAllAnalysed(AnalysisContext context) {
                Integer approximateTotalRowNumber = context.readSheetHolder().getApproximateTotalRowNumber();
                System.out.println("解析excel完成" + approximateTotalRowNumber + "条,耗时" + (System.currentTimeMillis() - finalBegin1) + "ms");
            }

        }).build();

        begin = System.currentTimeMillis();
        long finalBegin = begin;
        ReadSheet readSheet2 = EasyExcel.readSheet(1).head(ReceiptBillDataExcel.class).registerReadListener(new AnalysisEventListener<ReceiptBillDataExcel>() {


            @Override
            public void invokeHeadMap(Map<Integer, String> headMap, AnalysisContext context) {
            }

            @Override
            public void invoke(ReceiptBillDataExcel data, AnalysisContext context) {
                list2.add(data);
            }

            @Override
            public void doAfterAllAnalysed(AnalysisContext context) {
                Integer approximateTotalRowNumber = context.readSheetHolder().getApproximateTotalRowNumber();
                System.out.println("解析excel完成" + approximateTotalRowNumber + "条,耗时" + (System.currentTimeMillis() - finalBegin) + "ms");
            }

        }).build();

        // 只读取第二个sheet
        excelReader.read(readSheet2);
        // 两个sheet一起读
        //excelReader.read(readSheet, readSheet2);
        excelReader.finish();
    }
```
# 异常提示
同一个excel文件，读取相同数量、数据相近（48w左右）的不同sheet，耗时翻了很多倍。
解析excel完成486635条,耗时10034ms
解析excel完成485926条,耗时213841ms
# 问题描述
有一个excel，里面有两个sheet页，每个sheet页都有48w条数据，每行共有5列。第一个sheet读取耗时10s，第二个sheet读取至少4分钟。甚至我只读取excel的第二个sheet，耗时也很长。

**Comment by Y-Stone** [comment]
EasyExcel版本：2.2.5

**Comment by zhuangjiaju** [comment]
最新有加速



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月26日(周三) 晚上7:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [alibaba/easyexcel] easyexcel读取48多w条数据excel时间很长 (Issue #3147)




 
异常代码
   @Test     public void testReadBigDataExcel2() {         File targetFile = new File("C:\\Users\\Administrator\\Desktop\\能链2月.xlsx");         long begin = System.currentTimeMillis();         List<ReceiptBillDataExcel&gt; list1 = new ArrayList<&gt;();         List<ReceiptBillDataExcel&gt; list2 = new ArrayList<&gt;();         ExcelReader excelReader = EasyExcel.read(targetFile).build();         long finalBegin1 = begin;         ReadSheet readSheet = EasyExcel.readSheet(0).head(ReceiptBillDataExcel.class).registerReadListener(new AnalysisEventListener<ReceiptBillDataExcel&gt;() {             @Override             public void invokeHeadMap(Map<Integer, String&gt; headMap, AnalysisContext context) {             }             @Override             public void invoke(ReceiptBillDataExcel data, AnalysisContext context) {                 list1.add(data);             }             @Override             public void doAfterAllAnalysed(AnalysisContext context) {                 Integer approximateTotalRowNumber = context.readSheetHolder().getApproximateTotalRowNumber();                 System.out.println("解析excel完成" + approximateTotalRowNumber + "条,耗时" + (System.currentTimeMillis() - finalBegin1) + "ms");             }         }).build();         begin = System.currentTimeMillis();         long finalBegin = begin;         ReadSheet readSheet2 = EasyExcel.readSheet(1).head(ReceiptBillDataExcel.class).registerReadListener(new AnalysisEventListener<ReceiptBillDataExcel&gt;() {             @Override             public void invokeHeadMap(Map<Integer, String&gt; headMap, AnalysisContext context) {             }             @Override             public void invoke(ReceiptBillDataExcel data, AnalysisContext context) {                 list2.add(data);             }             @Override             public void doAfterAllAnalysed(AnalysisContext context) {                 Integer approximateTotalRowNumber = context.readSheetHolder().getApproximateTotalRowNumber();                 System.out.println("解析excel完成" + approximateTotalRowNumber + "条,耗时" + (System.currentTimeMillis() - finalBegin) + "ms");             }         }).build();         // 只读取第二个sheet         excelReader.read(readSheet2);         // 两个sheet一起读         //excelReader.read(readSheet, readSheet2);         excelReader.finish();     }
 
异常提示
 
同一个excel文件，读取相同数量、数据相近（48w左右）的不同sheet，耗时翻了很多倍。
 解析excel完成486635条,耗时10034ms
 解析excel完成485926条,耗时213841ms
 
问题描述
 
有一个excel，里面有两个sheet页，每个sheet页都有48w条数据，每行共有5列。第一个sheet读取耗时10s，第二个sheet读取至少4分钟。甚至我只读取excel的第二个sheet，耗时也很长。

**Comment by Y-Stone** [comment]
> 最新有加速
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年4月26日(周三) 晚上7:13 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [alibaba/easyexcel] easyexcel读取48多w条数据excel时间很长 (Issue #3147) 异常代码 @test public void testReadBigDataExcel2() { File targetFile = new File("C:\\Users\\Administrator\\Desktop\\能链2月.xlsx"); long begin = System.currentTimeMillis(); List<ReceiptBillDataExcel&gt; list1 = new ArrayList<&gt;(); List<ReceiptBillDataExcel&gt; list2 = new ArrayList<&gt;(); ExcelReader excelReader = EasyExcel.read(targetFile).build(); long finalBegin1 = begin; ReadSheet readSheet = EasyExcel.readSheet(0).head(ReceiptBillDataExcel.class).registerReadListener(new AnalysisEventListener<ReceiptBillDataExcel&gt;() { @OverRide public void invokeHeadMap(Map<Integer, String&gt; headMap, AnalysisContext context) { } @OverRide public void invoke(ReceiptBillDataExcel data, AnalysisContext context) { list1.add(data); } @OverRide public void doAfterAllAnalysed(AnalysisContext context) { Integer approximateTotalRowNumber = context.readSheetHolder().getApproximateTotalRowNumber(); System.out.println("解析excel完成" + approximateTotalRowNumber + "条,耗时" + (System.currentTimeMillis() - finalBegin1) + "ms"); } }).build(); begin = System.currentTimeMillis(); long finalBegin = begin; ReadSheet readSheet2 = EasyExcel.readSheet(1).head(ReceiptBillDataExcel.class).registerReadListener(new AnalysisEventListener<ReceiptBillDataExcel&gt;() { @OverRide public void invokeHeadMap(Map<Integer, String&gt; headMap, AnalysisContext context) { } @OverRide public void invoke(ReceiptBillDataExcel data, AnalysisContext context) { list2.add(data); } @OverRide public void doAfterAllAnalysed(AnalysisContext context) { Integer approximateTotalRowNumber = context.readSheetHolder().getApproximateTotalRowNumber(); System.out.println("解析excel完成" + approximateTotalRowNumber + "条,耗时" + (System.currentTimeMillis() - finalBegin) + "ms"); } }).build(); // 只读取第二个sheet excelReader.read(readSheet2); // 两个sheet一起读 //excelReader.read(readSheet, readSheet2); excelReader.finish(); } 异常提示 同一个excel文件，读取相同数量、数据相近（48w左右）的不同sheet，耗时翻了很多倍。 解析excel完成486635条,耗时10034ms 解析excel完成485926条,耗时213841ms 问题描述 有一个excel，里面有两个sheet页，每个sheet页都有48w条数据，每行共有5列。第一个sheet读取耗时10s，第二个sheet读取至少4分钟。甚至我只读取excel的第二个sheet，耗时也很长。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

什么加速？
