### ISSUE TITLE
实体属性为Integer，导出后变成浮点型，无法再导入

### ISSUE THREAD

**Issue by jeesun** [alibaba/easyexcel#315]
比如Integer类型的属性age值为18，导出后，再读取，变成了18.0，无法映射属性，报如下的错误
```
com.alibaba.excel.exception.ExcelGenerateException: java.lang.NumberFormatException: For input string: "18.0"
```

**Comment by jeesun** [comment]
我把WorkBookUtil.java第67行代码`cell.setCellValue(Double.parseDouble(cellValue.toString()));`改成`cell.setCellValue(cellValue.toString());`解决了该问题。

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。使用NumberFormat注解或者自定义转换器都可以
