### ISSUE TITLE
求解：怎么把不同类型的数据 统一转换为String

### ISSUE THREAD

**Issue by hjg0325** [alibaba/easyexcel#3150]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述

**Comment by gongxuanzhang** [comment]
听不懂

**Comment by hjg0325** [comment]
我只是想根据行列 把数据读取出来  但是每个sheet中的数据都不同 ，  想问问 怎么通过代码把数据读到缓存中

**Comment by hjg0325** [comment]
> 听不懂

每个sheet中列的数量都不同，并且数据类型都不一样  所有想将数据统一转成String

**Comment by gongxuanzhang** [comment]
直接读不就行了吗  你有什么要问的。
你现在写的代码是什么  达到了不满意的效果

**Comment by gongxuanzhang** [comment]
这不就是基本功能吗，看文档去

**Comment by hjg0325** [comment]
> 这不就是基本功能吗，看文档去

用了文档上的方式  表格第一行没读出来

**Comment by gongxuanzhang** [comment]
你可以贴上代码和excel吗？
没人是你肚子里的蛔虫能通过你几句话就能还原你的上下文解决你的问题


https://github.com/my-handbook/How-To-Taise-Questions-To-The-Open-Source-Community
