### ISSUE TITLE
建议添加导出多张图片的构造函数

### ISSUE THREAD

**Issue by huanxinbo** [alibaba/easyexcel#3152]
# 建议描述
    public WriteCellData(byte[] image) {
        super();
        if (image == null) {
            throw new IllegalArgumentException("Image can not be null");
        }
        setType(CellDataTypeEnum.EMPTY);
        this.imageDataList = ListUtils.newArrayList();
        ImageData imageData = new ImageData();
        imageData.setImage(image);
        imageDataList.add(imageData);
    }
建议添加List<byte[]> image 的构造函数

**Comment by gongxuanzhang** [comment]
暂不考虑

**Comment by gongxuanzhang** [comment]
暂不考虑
