### ISSUE TITLE
求解：图片导出行高设置

### ISSUE THREAD

**Issue by Qianjunjie** [alibaba/easyexcel#3153]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述
导出的时候有些行有图片，有些行没有，有图片的行想设置的高点，@ContentRowHeight会设置所有的行一样高。有没有办法在导出图片的时候设置图片所在行的高度。

**Comment by gongxuanzhang** [comment]
你可以在CellWritehandler中自定义这些行为

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
