### ISSUE TITLE
如何将图片嵌入进excel的cell表格里面

### ISSUE THREAD

**Issue by Thereyouare** [alibaba/easyexcel#3155]
我这里有一个需求，需要从excel读取个人信息，个人信息里面有一个头像，是嵌入在单元格里面的，如何把它读取出来。
![image](https://user-images.githubusercontent.com/54898368/235087287-84604d41-bcf3-41d6-9fde-6ad3a893584c.png)
我想从上方的单元格里面讲图片的信息读取出来。后续的业务还有生成用户的二维码信息，也是上方的效果。请问该如何实现呢。

**Comment by gongxuanzhang** [comment]
目前不支持从excel中读取，你只能使用POI进行读取.

**Comment by Thereyouare** [comment]
非常感谢，我去POI再去看看
