### ISSUE TITLE
实体类上能不能加注解，而不只是属性上

### ISSUE THREAD

**Issue by jeesun** [alibaba/easyexcel#316]
一般属性注解是这样的，`@ExcelProperty(value = "id", index = 0)`
但如果想在头部增加一行表头，必须这样写`@ExcelProperty(value = {"用户信息汇总", "id"}, index = 0)`
而且每个ExcelProperty注解都要加`"用户信息汇总"`，有点不友好。

**Comment by zhuangjiaju** [comment]
非常感谢您的意见。后续我们会考虑这个情况
