### ISSUE TITLE
导出少量数据等待时间过长

### ISSUE THREAD

**Issue by lkcjjf** [alibaba/easyexcel#3160]
使用的是若依框架 easyexcel 是 2.2.11 导出数据的时候发现 addContent 里的方法耗时很多 1000条数据需要一分钟 查询数据用了 900ms 这是框架的问题吗 还是有别的解决方案呢

**Comment by gongxuanzhang** [comment]
查询是数据库的职责，和excel没关系的

**Comment by lkcjjf** [comment]
> 

对呀 我的意思是已经查出来了然后在生成excel的时候add那个方法比较慢 这是什么原因呢

**Comment by gongxuanzhang** [comment]
这个得上代码看，这么说有点抽象

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
