### ISSUE TITLE
找不到类

### ISSUE THREAD

**Issue by g2plus** [alibaba/easyexcel#3165]
com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoSuchMethodError: org.apache.xmlbeans.XmlOptions.put(Ljava/lang/Object;)V

**Comment by gongxuanzhang** [comment]
https://easyexcel.opensource.alibaba.com/qa/#%E5%87%BA%E7%8E%B0-nosuchmethodexception-classnotfoundexception-noclassdeffounderror-%E7%AD%89%E5%85%BC%E5%AE%B9%E6%80%A7%E9%97%AE%E9%A2%98
