### ISSUE TITLE
填充方式  动态合并单元格

### ISSUE THREAD

**Issue by xiaofeiji0730** [alibaba/easyexcel#3166]
填充方式能支持合并单元格吗，类似这样的效果
![image](https://user-images.githubusercontent.com/38942029/236149823-683d5ac4-5723-4376-9ee2-a6cae37f88fe.png)

**Comment by dardaplanet** [comment]
需要自定义合并规则

**Comment by xiaofeiji0730** [comment]
怎么自定义，有文档示例吗

**Comment by dardaplanet** [comment]
自定义合并单元格的策略,.可以参考官方默认给出的两种合并策略,OnceAbsoluteMergeStrategy和LoopMergeStrategy.
