### ISSUE TITLE
使用.xlsx模板写入数据，创建ExcelWriter抛出“No valid entries or contents found, this is not a valid OOXML (Office Open XML) file”异常，已确认模板文件未加密

### ISSUE THREAD

**Issue by mendaimon** [alibaba/easyexcel#3171]
ByteArrayOutputStream out = new ByteArrayOutputStream();
/ExcelWriter excelWriter = EasyExcel.write(out).withTemplate(filepath).excelType(ExcelTypeEnum.XLSX).build();

**Comment by gongxuanzhang** [comment]
你的文件是xlsx吗。
上传可以复现的文件和代码

**Comment by mendaimon** [comment]
[确认是xlsx文件，执行到第三行时就抛出题中异常了，原始代码如下（文件目录地址为maven项目下resources目录中名为"template"的目录）：
InputStream templateInputStream = getClass().getClassLoader().getResourceAsStream("template/holiday_template.xlsx");
ByteArrayOutputStream out = new ByteArrayOutputStream();
ExcelWriter excelWriter = EasyExcel.write(out).withTemplate(filepath).excelType(ExcelTypeEnum.XLSX).build();
[holiday_template.xlsx](https://github.com/alibaba/easyexcel/files/11403573/holiday_template.xlsx)

**Comment by gongxuanzhang** [comment]
我执行如下代码完全没有问题，你确定你的资源位置是对的吗。你换成fileinputstream试试。
你说第三行抛异常，但是你的描述没有行号

```java
InputStream templateInputStream = new FileInputStream("/Users/gongxuanzhang/Downloads/holiday_template.xlsx");
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        ExcelWriter excelWriter = EasyExcel.write(out).withTemplate(templateInputStream).excelType(ExcelTypeEnum.XLSX).build();
```

**Comment by mendaimon** [comment]
和文件位置好似没关系，，不过还是非常感谢耐心解答，pom文件添加如下图插件配置解决了：
![image](https://user-images.githubusercontent.com/29232459/236390383-cd96273b-bea1-4e9b-8a93-658509b49a7f.png)
已能写入文件，只是不知为何，模板红圈处原本时三行，写入文件之后变成了四行：
![image](https://user-images.githubusercontent.com/29232459/236390562-483b0164-51ab-454f-958e-c6e658769324.png)

**Comment by gongxuanzhang** [comment]
你是循环写入的  两行数据  空行两个
