### ISSUE TITLE
write方法写入时传的类名必须是子类类名吗，用父类类名可以处理子类属性吗

### ISSUE THREAD

**Issue by sulianheng** [alibaba/easyexcel#3187]
write方法写入时传的类名必须是子类类名吗，用父类类名可以处理子类属性吗

比如 EasyExcel.write(file, ExportData.class)  如果ExportData是父类，但是实际传入的是子类，可以按子类的属性处理吗。
目前我测试的情况没法按照子类处理表头

**Comment by gongxuanzhang** [comment]
目前不支持
