### ISSUE TITLE
如何动态显示列的数据

### ISSUE THREAD

**Issue by 15292137182** [alibaba/easyexcel#319]
假设我有一个字段是status，但我想动态显示status的中文名称，而不是对应的数字，请问该如何操作

**Comment by Idiot-Alex** [comment]
继承 BaseRowModel ，属性上加注解，如下图
![image](https://user-images.githubusercontent.com/16541166/56548614-19eca000-65b3-11e9-910e-df0cb321002c.png)

**Comment by 15292137182** [comment]
这个我知道,我要的效果不是这样的 我要的是 假设说我的数据中有一个字段是状态 就是 1 ,2 之类的 ,但是我想在下载的excel中显示 1:正常 2:失败

**Comment by heiyu106** [comment]
可以在Bean添加一个冗余字段statusStr字段，在查询SQL中将值对应的中文名直接转换好后返回，可通过码表直接关联查询对应状态值的中文名，或者在SQL中使用 CASE WHEN status=1 THEN ‘ 正常’ AS statusStr

**Comment by Muscleape** [comment]
> 假设我有一个字段是status，但我想动态显示status的中文名称，而不是对应的数字，请问该如何操作

我在自己fork的仓库里实现了键值转换导出，可以参考，如果有问题请指出，谢谢！
https://github.com/Muscleape/easyexcel

**Comment by Muscleape** [comment]
> 可以在Bean添加一个冗余字段statusStr字段，在查询SQL中将值对应的中文名直接转换好后返回，可通过码表直接关联查询对应状态值的中文名，或者在SQL中使用 CASE WHEN status=1 THEN ‘ 正常’ AS statusStr

我在自己fork的仓库里实现了键值转换导出，可以参考，如果有问题请指出，谢谢！
https://github.com/Muscleape/easyexcel

**Comment by 15292137182** [comment]
我这边已经通过注解的方式实现了 也是类似于键值做的

**Comment by Muscleape** [comment]
> 我这边已经通过注解的方式实现了 也是类似于键值做的

实现方式方不方便放出来看看，学习一下啊

**Comment by 15292137182** [comment]
![image](https://user-images.githubusercontent.com/24935555/56858302-543ab080-69aa-11e9-92a2-f896dd7bd7d2.png)
在实体上面再加一个注解就可以了

**Comment by Muscleape** [comment]
> ![image](https://user-images.githubusercontent.com/24935555/56858302-543ab080-69aa-11e9-92a2-f896dd7bd7d2.png)
> 在实体上面再加一个注解就可以了

奥，这样的。我是扩展了一下原有的注解，用JSON类型字符串

**Comment by 15292137182** [comment]
我没有去动他原有的注解,我是自己去解析自己的注解

**Comment by cityagent** [comment]
> 我没有去动他原有的注解，我是自己去解析自己的注解

我在VO类加了这个注解，但是并没有效果呢

**Comment by cityagent** [comment]
![image](https://user-images.githubusercontent.com/33981649/61843306-bcc3fb80-aecd-11e9-9c2f-64cabf1cb1d2.png)

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。 新版本支持自定义转换器
