### ISSUE TITLE
includeColumnIndexes 使用index不生效

### ISSUE THREAD

**Issue by JemyXiao** [alibaba/easyexcel#3191]
实体类使用index includeColumnIndexes 有空行，缓存order之后生效，但是会自动缩进到第一列

ExcelWriter writer = ExportUtils
        .exportCommonBuilder(file)
        .head(QuotePayOutExportEntity.class)
        .excelType(ExcelTypeEnum.XLSX)
        .includeColumnIndexes(deleteColumnIndexes)
        .registerWriteHandler(new EasyExcelMergeStrategy(list.size(),0))
        .registerWriteHandler(new EasyExcelMergeStrategy(list.size(),1))
        .build();

**Comment by JemyXiao** [comment]
@zhuangjiaju 可以帮看下怎么解决吗？

**Comment by gongxuanzhang** [comment]
上完整的代码 不要传封装之后的代码
说出你期望的导出内容和当前的导出内容

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
