### ISSUE TITLE
执行com.alibaba.easyexcel.test.demo.read.ReadTest#simpleRead，报ClassCastException

### ISSUE THREAD

**Issue by wuyiliang1** [alibaba/easyexcel#3200]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
branch：master
version：3.3.1
执行com.alibaba.easyexcel.test.demo.read.ReadTest#simpleRead，报ClassCastException
![image](https://github.com/alibaba/easyexcel/assets/106386822/35d9aed4-c135-4cdd-aa93-2ace4bcdf55d)

# 触发Bug的代码
![image](https://github.com/alibaba/easyexcel/assets/106386822/7df2f6b2-3a18-4a83-a2f7-34b023f25149)
读取excel的时候，这里实际上是ReadHolder，无法cast为WriteHolder
# 提示的异常或者没有达到的效果
excludeColumnFieldNames，excludeColumnIndexes，includeColumnFieldNames，includeColumnIndexes四个属性实际上没有用到，报错的地方应该增加WriteHolder的判断

**Comment by gongxuanzhang** [comment]
感谢issue  尽快修复
