### ISSUE TITLE
使用'OnceAbsoluteMergeStrategy'合并单元格，导出Excel打开之后报错

### ISSUE THREAD

**Issue by AwenJackson** [alibaba/easyexcel#3208]
`代码如下：

            EasyExcel.write(filePath)
                    .excelType(ExcelTypeEnum.XLSX)
                    .registerWriteHandler(new OnceAbsoluteMergeStrategy(0,0,0,8))
                    .sheet()
                    .sheetName("Sheet1")
                    .head(headTable)
                    .doWrite(dataList);`
主要是为了合并Excel表格中第一行第一列到第8列，虽然导出Excel的确是成功了，但是在打开Excel的时候，报错如下
![image](https://github.com/alibaba/easyexcel/assets/95326431/4069c605-4f2e-4e94-b494-47dbb5cf4706)
![image](https://github.com/alibaba/easyexcel/assets/95326431/8a28305e-c9e8-49eb-b6bc-7876f62d0776)

请问该怎么解决这个问题？ @gongxuanzhang

**Comment by gongxuanzhang** [comment]
有其他的逻辑吗   

https://easyexcel.opensource.alibaba.com/qa/write#%E5%AF%BC%E5%87%BA%E7%9A%84excel%E6%8F%90%E7%A4%BA%E9%9C%80%E8%A6%81%E4%BF%AE%E5%A4%8D

**Comment by AwenJackson** [comment]
没有其他的逻辑了

**Comment by gongxuanzhang** [comment]
我觉得你这个需求不需要手动合并，只需要把头设置好就行了

**Comment by AwenJackson** [comment]
我看了一下，EasyExcel有一个默认的合并策略，如果相邻单元格的数据相同，那么就会自动合并 @gongxuanzhang

**Comment by gongxuanzhang** [comment]
> 

表头是这样的 所以你可以直接设置表头必须要手动合并

**Comment by ly-yueyue** [comment]
我也遇到这个问题了。。表头自定义内容太多不能用自动合并，然后这样写启动还修复好烦

**Comment by ly-yueyue** [comment]
> 我也遇到这个问题了。。表头自定义内容太多不能用自动合并，然后这样写启动还修复好烦

啊哈哈，问题解决了，automaticMergeHead属性设置成false就行
