### ISSUE TITLE
导出时,实体类属性被复写后,指定的converter无效

### ISSUE THREAD

**Issue by hccpw007** [alibaba/easyexcel#3209]
实体类继承公共父类, 字段可以导出, 表头【提出人】生效, 但是自定义converter无效, 
将字段名换一个，比如【createBy2】，可以正确导出用户名，说明converter没有问题

父类
```
    @Schema(description = "创建者")
    private Long createBy;
```
子类
```
    @Schema(description = "创建者")
    @ExcelProperty(value = "提出人", converter = ExcelUserConverter.class)
    private Long createBy;
```

**Comment by gongxuanzhang** [comment]
无法复现 给份代码

**Comment by gongxuanzhang** [comment]
不知道你是否已经解决了问题，我们将关闭issue  如果仍为解决可以reopen

**Comment by GeeCoder-zyl** [comment]
![image](https://github.com/alibaba/easyexcel/assets/45805482/1f458546-443c-4cb8-90e9-34c9b0eab3f7)
![image](https://github.com/alibaba/easyexcel/assets/45805482/4f1a92b8-c49b-4db2-833a-6517ebd5fffd)
![image](https://github.com/alibaba/easyexcel/assets/45805482/12504088-7c1c-4abd-8fb0-c2f5b8ea2956)
同样的问题我这也出现了，2.2.11版本是没问题的

**Comment by GeeCoder-zyl** [comment]
> 不知道你是否已经解决了问题，我们将关闭issue 如果仍为解决可以reopen

请再看看是否能解决这个问题

**Comment by GeeCoder-zyl** [comment]
出现问题版本3.3.2

**Comment by hccpw007** [comment]
> 不知道你是否已经解决了问题，我们将关闭issue 如果仍为解决可以reopen

我重写了com.alibaba.excel.util.ClassUtils 这个类才解决的, easyexcel获取class的fields的逻辑是有问题的,你可以参考我的代码

<img width="1040" alt="image" src="https://github.com/alibaba/easyexcel/assets/13290294/68eb5f8b-02f6-42b9-a75c-66aabc2b0a46">

**Comment by linsiming** [comment]
我也同意遇到这个问题。 除非使用 registerConverter，否则就是无法读取。
