### ISSUE TITLE
在生成文件时头部字段变成了1列，请问如何变为行并去掉字体样式，谢谢

### ISSUE THREAD

**Issue by wangzxnpu** [alibaba/easyexcel#321]
![image](https://user-images.githubusercontent.com/10628842/56561827-934bb900-65da-11e9-84af-478273218fee.png)

这是创建sheet代码，不理解headLineMun到底什么意思，希望懂的大佬帮忙解释下，多谢！
        sheetOne = new Sheet(1,0);
        sheetOne.setSheetName(newEntryName);
        sheetOne.setHead(Arrays.asList(titleList));
        writer = EasyExcelFactory.getWriter(unCloseableOutputStream, ExcelTypeEnum.XLSX, true);

**Comment by zhuangjiaju** [comment]
这个字段已经被删除，请参照最新的demo
