### ISSUE TITLE
单元测试类CellDataDataTest类中t01ReadAndWrite07()方法生成的excel中CellDataTypeEnum.NUMBER数值类型无效

### ISSUE THREAD

**Issue by joey-happy** [alibaba/easyexcel#3216]
![image](https://github.com/alibaba/easyexcel/assets/16012082/56c3be8e-699a-4c3e-a122-ca5b2a9ff597)
生成的类型是常规 而非数值类型

现在所有办法都试过了 就是不能生成数值类型的 求帮助啊

**Comment by joey-happy** [comment]
江湖救急啊 麻烦帮忙看一下被

**Comment by liruibingniubi** [comment]
很高兴能为你解决问题

**Comment by joey-happy** [comment]
> 很高兴能为你解决问题

有办法吗？

**Comment by joey-happy** [comment]
> 很高兴能为你解决问题

首先非常感谢哈 如果您有办法 如果可以的话 烦请粘贴一下完整代码被

**Comment by liruibingniubi** [comment]
有办法
,你试试

**Comment by joey-happy** [comment]
> 有办法 ,你试试

说具体点儿被？

**Comment by liruibingniubi** [comment]
我找找,稍等

**Comment by liruibingniubi** [comment]
这里是字段类型
    private WriteCellData<String> hyperlink;

这是格式设置
 // 设置公式
        WriteCellData<String> formula = new WriteCellData<>();
        writeCellDemoData.setFormulaData(formula);
        FormulaData formulaData = new FormulaData();
        formula.setFormulaData(formulaData);
        // 将 123456789 中的第一个数字替换成 2
        // 这里只是例子 如果真的涉及到公式 能内存算好尽量内存算好 公式能不用尽量不用
        formulaData.setFormulaValue("REPLACE(123456789,1,1,2)");

**Comment by liruibingniubi** [comment]
这是打个比方
具体你试试

**Comment by joey-happy** [comment]
> 这是打个比方 具体你试试

好的

**Comment by liruibingniubi** [comment]
在吗
我处理好了

**Comment by liruibingniubi** [comment]
![图片](https://github.com/alibaba/easyexcel/assets/105581852/45102693-64e7-41fe-a704-1ac329c684f0)

**Comment by liruibingniubi** [comment]
![图片](https://github.com/alibaba/easyexcel/assets/105581852/3d07bd42-5af6-46f6-8929-5bab87f14fa6)
请使用这个注解             @NumberFormat("0.00_ ")

**Comment by liruibingniubi** [comment]
还在吗,兄弟

**Comment by liruibingniubi** [comment]
很高兴帮助你解决问题,再见!

**Comment by joey-happy** [comment]
> 还在吗,兄弟

昨天有事 早走了 怎么了 还有更好的方法吗？我这个是动态内容 不能用注解

**Comment by joey-happy** [comment]
> 很高兴帮助你解决问题,再见!

多谢您的热心帮助 我看看注解那个源码吧

**Comment by liruibingniubi** [comment]
最后加个_ 就是数值格式

**Comment by joey-happy** [comment]
> 最后加个_ 就是数值格式

好的 我尝试一下 方便加您微信吗？

**Comment by liruibingniubi** [comment]
15533829110

**Comment by joey-happy** [comment]
![image](https://github.com/alibaba/easyexcel/assets/16012082/ccd96d97-7f1b-479f-a131-a487a9e35937)
您看看 这个是easyExcel源码
