### ISSUE TITLE
动态头的方式写入，不支持多次追加写入

### ISSUE THREAD

**Issue by TheMachine1024** [alibaba/easyexcel#3217]
EasyExcel.write(fileName)
            // 这里放入动态头
            .head(head()).sheet("模板")
            // 当然这里数据也可以用 List<List<String>> 去传入
            .doWrite(data());
    }
多次调用会报错
Attempting to write a row[1] in the range [0,1001] that is already written to disk. easyexcel

怎么可以实现多次追加写入，使用动态头，不使用数据对象

**Comment by gongxuanzhang** [comment]
为什么表头要多次追加

**Comment by TheMachine1024** [comment]
您好，来信已收到，我会尽快给您回复。                                                                                            chenyujun

**Comment by TheMachine1024** [comment]
>

**Comment by TheMachine1024** [comment]
不是这个意思，表头只写一次，然后后面的表格数据会分批写入

**Comment by gongxuanzhang** [comment]
数据是需要一次性走完的，可以在过滤器中分段查询

**Comment by TheMachine1024** [comment]
demo:
 /**
     * 动态头，实时生成头写入
     * <p>
     * 思路是这样子的，先创建List<String>头格式的sheet仅仅写入头,然后通过table 不写入头的方式 去写入数据
     *
     * <p>
     * 1. 创建excel对应的实体对象 参照{@link DemoData}
     * <p>
     * 2. 然后写入table即可
     */
    @Test
    public void dynamicHeadWrite() {
        String fileName = TestFileUtil.getPath() + "dynamicHeadWrite" + System.currentTimeMillis() + ".xlsx";
        EasyExcel.write(fileName)
            // 这里放入动态头
            .head(head()).sheet("模板")
            // 当然这里数据也可以用 List<List<String>> 去传入
            .doWrite(data());
    }




是demo中的这种写法，想实现data() 多次写入，

**Comment by gongxuanzhang** [comment]
参考官网的多次写入

https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E9%87%8D%E5%A4%8D%E5%A4%9A%E6%AC%A1%E5%86%99%E5%85%A5%E5%86%99%E5%88%B0%E5%8D%95%E4%B8%AA%E6%88%96%E8%80%85%E5%A4%9A%E4%B8%AAsheet


https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E4%BD%BF%E7%94%A8table%E5%8E%BB%E5%86%99%E5%85%A5

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
