### ISSUE TITLE
读Excel时自定义列转换器，当遇到空单元格不会调用convertToJavaData方法

### ISSUE THREAD

**Issue by suncch** [alibaba/easyexcel#3219]
![微信图片_20230525092531](https://github.com/alibaba/easyexcel/assets/39582483/e8255ed8-1db8-4279-acb3-e84f63b856cb)
![微信图片_20230525092546](https://github.com/alibaba/easyexcel/assets/39582483/c27b5ae5-9c38-4c7d-bb07-6833dcc64b3e)
![微信图片_20230525092948](https://github.com/alibaba/easyexcel/assets/39582483/5c79d0fc-fdec-4235-9242-887a7fc93fe0)
![微信图片_20230525093016](https://github.com/alibaba/easyexcel/assets/39582483/c4e077de-9368-4d47-931c-214c6fe4202e)
指定了两个列来放图片，读图片需要知道这两个列的行号和列号，所以启用了自定义转换器，想在转换的时候读取出来行号和列号，但是放图片的单元格不会有任何文字，这样就不会调用convertToJavaData方法了，请问怎么才能在单元格为空的时候也调用convertToJavaData方法

**Comment by quaintclever** [comment]
我试了下Microsoft Excel 在单元格插入图片，发现图片貌似是悬浮与单元格上的，看上去像是和单元格没有关联，这样的话
相当于你该单元格是空的，跟了下源码，ModelBuildEventListener#buildUserModel 里面 cellDataMap 是没有空单元格数据的，因此没有调用 convert 方法。
既然要解决问题，为什么不在 AnalysisEventListener 里的 invoke 方法判断图片字段是否为空，手动转换呢？或者说存图片url？

**Comment by DoubleC77** [comment]
我都是给模板的图片字段设置为空字符串，然后在

**Comment by DoubleC77** [comment]
我都是模板填充图片时,对应字段给空字符串，图片资源另外传入
.registerWriteHandler(new ImageModifyHandler(‘图片资源’)
