### ISSUE TITLE
读取excel的时候，context.getCurrentSheet().getSheetName()为null

### ISSUE THREAD

**Issue by Zrollan** [alibaba/easyexcel#322]
context.getCurrentSheet()拿到的返回值是：Sheet{headLineMun=0, sheetNo=1, sheetName='null', clazz=class bean.Rule1Modul, head=null, tableStyle=null, columnWidthMap={}}，  sheetName和head都是null

**Comment by zcjm60** [comment]
![image](https://user-images.githubusercontent.com/22487059/56630800-28a38780-6685-11e9-8054-3b7a4195c5de.png) 使用这种方式

**Comment by xiongfeng1015** [comment]
人家要获取当前的sheetname，你这是设置sheetname

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
