### ISSUE TITLE
遇到如下情况，如何多行多列合并，多列（多行id相同情况）都相同才合并，只要有一列不同不合并（多行id相同情况）

### ISSUE THREAD

**Issue by xy12345678zz** [alibaba/easyexcel#3221]
![image](https://github.com/alibaba/easyexcel/assets/30724557/310cdf68-2923-420e-9f45-b2bca5dea2fc)

**Comment by gongxuanzhang** [comment]
你需要在writeHandler中自定义行为

**Comment by xy12345678zz** [comment]
好的，谢谢 我试试

**Comment by a1667834841** [comment]
https://github.com/a1667834841/easyExcel_merge.git
希望能帮助到你

**Comment by xy12345678zz** [comment]
好的，谢谢




xuyang
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 上午10:24
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 遇到如下情况，如何多行多列合并，多列（多行id相同情况）都相同才合并，只要有一列不同不合并（多行id相同情况） (Issue #3221)





 
https://github.com/a1667834841/easyExcel_merge.git
 希望能帮助到你

**Comment by xy12345678zz** [comment]
好的，谢谢。
现在有个问题

版本用的这个



提示找不到CollectionUtils，是有什么依赖问题吗？


xuyang
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月26日(星期五) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 遇到如下情况，如何多行多列合并，多列（多行id相同情况）都相同才合并，只要有一列不同不合并（多行id相同情况） (Issue #3221)





 
你需要在writeHandler中自定义行为
