### ISSUE TITLE
找不到类CollectionUtils

### ISSUE THREAD

**Issue by xy12345678zz** [alibaba/easyexcel#3223]
![image](https://github.com/alibaba/easyexcel/assets/30724557/f7cef10f-f1b5-42e9-a0b4-d9a0979688a3)

**Comment by gongxuanzhang** [comment]
项目版本或者依赖冲突  自行解决

**Comment by Fang57** [comment]
依赖树很干净，没有冲突的依赖  只引入了easyexcel 3.3.0  easyexcel-core 3.3.0  lombok 1.18.12三个依赖   仍然报错找不到CollectionUtils类；debug发现 ClassUtils.declaredFields方法报该问题  easyexcel cannot find local variable CollectionUtils
