### ISSUE TITLE
使用PageReadListener读到的数据都是空

### ISSUE THREAD

**Issue by limengning** [alibaba/easyexcel#3235]
![图片](https://github.com/alibaba/easyexcel/assets/10029844/a3cd259d-62f6-48e8-a1e1-6ae65c7c8d0d)
![图片](https://github.com/alibaba/easyexcel/assets/10029844/ffe8275c-f77c-4f02-b176-68a554a9f93d)
能读取到数据，但是转换泛型后没有数据

**Comment by gongxuanzhang** [comment]
附上代码和excel

**Comment by limengning** [comment]
![图片](https://github.com/alibaba/easyexcel/assets/10029844/3f55ca3a-62f6-4f13-80b1-6e946e7bb2e2)

**Comment by limengning** [comment]
我用的是zulu jdk，跟这个有关系吗？我调试跟到BeanMap的put时，put完成以后，值没有更新进去，依旧是null

**Comment by limengning** [comment]
原因时我lombok.config里默认打开了链式setter了
![图片](https://github.com/alibaba/easyexcel/assets/10029844/1c58f2d8-9571-4409-b3f9-6b853889adb3)
#2374 
DTO改成这样就读到了
···JAVA
@Accessors(chain = false)
@Data
public class ExcelMetricData {
    private Long id;
    private String recordTime;
    private Float value;
}
```

**Comment by limengning** [comment]
虽然解决了，但是能否加一个警告啊，或者文档里给与说明，提醒开发者不能使用链式getter，否则遇到问题真不知道从哪找原因

**Comment by CoderRyou** [comment]
真坑啊这个问题，调了半天找不到问题出在哪里
