### ISSUE TITLE
Model不支持lombok注解

### ISSUE THREAD

**Issue by wangsaner** [alibaba/easyexcel#324]
Model不支持lombok注解，使用lombok后读不到数据

**Comment by jiantouyao5kuai** [comment]
> Model不支持lombok注解，使用lombok后读不到数据

版本问题？我用的easyExcel（1.1.1），lombok（1.16.18），没有问题。

**Comment by jeesun** [comment]
我的没有问题。

**Comment by robinsono** [comment]
lombok 1.18.6  & easyexcel 1.1.2-beta4  没有问题

**Comment by fish7790714** [comment]
贴代码 应该是你代码问题 lombok 和这个插件没任何关系

**Comment by chengliangcode** [comment]
确实是不支持 lombok 的 @Accessors(chain = true) 注解

**Comment by lkplyl** [comment]
我也遇到同样问题，写入excel没有问题，但是读取excel的时候有问题，跟踪代码分析后发现是使用cglib做map给bean赋值时的问题，@ToString注解导致根据class反射出来的对象是字符串，@Getter和@Setter导致无法赋值，我的版本是lombok 1.16.22 & easyexcel 1.1.2-beta5

**Comment by zhuangjiaju** [comment]
新版测试时支持的，请尝试升级到最新版本
