### ISSUE TITLE
大数据导出优化

### ISSUE THREAD

**Issue by zhangjr0575** [alibaba/easyexcel#3245]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 建议描述
在大量数据导出需求下,是否可提供边写边向输出流输出,目前的客户端体验很差劲,客户端等待时间很长后才会开始下载任务

**Comment by gongxuanzhang** [comment]
目前不可以，建议从业务角度解决。

**Comment by zhangjr0575** [comment]
请问后期是否有计划支持呢
