### ISSUE TITLE
获取workbook中sheet的数量

### ISSUE THREAD

**Issue by renyd123** [alibaba/easyexcel#3248]
调用doAfterAllAnalysed的时候，怎么通过参数AnalysisContext context获取到workbook总共有多少个sheet呀。我用context.readWorkbookHolder().getActualSheetDataList()和context.readSheetList()获取到的list都是null

**Comment by DaZuiZui** [comment]
~~~java
   excelReader = EasyExcel.read(filePath).build();
   int count = excelReader.getSheets().size();
~~~

**Comment by renyd123** [comment]
> ```java
>    excelReader = EasyExcel.read(filePath).build();
>    int count = excelReader.getSheets().size();
> ```
> 
> 祝你生活愉快，工作顺利。

这是在官方文档里的办法，我也知道这个。就是想在不增加额外开销的情况下获取到sheet数量。这种方法还是要再读一次EasyExcel的

**Comment by DaZuiZui** [comment]
> 就是想在不增加额外开销的情况下获取到sheet数量。这种方法还是要再读一次EasyExcel的

那么就使用SimpleReadCacheSelector，它是通过EasyExcel的缓存机制来读取的。
~~~java
        ReadSheet rs = EasyExcel.readSheet(0).build();
        SimpleReadCacheSelector srcs = new SimpleReadCacheSelector("ur file path");
        srcs.setCurrentReadSheet(rs);
        return srcs.getReadCache().sheetCount();
~~~
祝您生活愉快，工作顺利

**Comment by renyd123** [comment]
> > 就是想在不增加额外开销的情况下获取到sheet数量。这种方法还是要再读一次EasyExcel的
> 
> 那么就使用SimpleReadCacheSelector，它是通过EasyExcel的缓存机制来读取的。
> 
> ```java
>         ReadSheet rs = EasyExcel.readSheet(0).build();
>         SimpleReadCacheSelector srcs = new SimpleReadCacheSelector("ur file path");
>         srcs.setCurrentReadSheet(rs);
>         return srcs.getReadCache().sheetCount();
> ```
> 
> 祝您生活愉快，工作顺利

好的谢谢
