### ISSUE TITLE
easyExcel导出时 段落如何设置格式

### ISSUE THREAD

**Issue by omenss** [alibaba/easyexcel#3255]
在生成excel文件时 我有一些段落数据  在表格头里的样式居中
![image](https://github.com/alibaba/easyexcel/assets/26828924/70a4c180-6d72-42b0-a4f0-d92f5a0c3211)

请问下在单元格内的段落的格式要如何设置呢 比如：
![image](https://github.com/alibaba/easyexcel/assets/26828924/df1fa937-f350-4c87-a7b0-d67fdb5a9274)

**Comment by omenss** [comment]
比如 第一行第二行是居中的 第三行第四行是居右的 还有一些对齐方式 缩进 换行 可否自定义操作

**Comment by gongxuanzhang** [comment]
这个你需要看POI是如何实现了   这个属于复杂样式。
用poi完成之后在拦截器中加入到表头拦截即可

**Comment by omenss** [comment]
好的 好像自身excel 也没有办法一个单元格  两行文字采用不同的对齐方式
