### ISSUE TITLE
怎么通过内容：图片字符串链接的属性，导出到excel展示图片

### ISSUE THREAD

**Issue by 15155662482** [alibaba/easyexcel#3256]
请问easyexcel怎么将内容是图片URL链接的字符串属性，导出到excel呈图片展示啊。
例如：我有一个类Model:
Class Model{
 ...
String imgUrls;//每个url，逗号隔开
...
}
我知道使用转化器，但是转换器里要指定excel单元格的内容格式，源码中貌似没有跟图片相关的类型啊，求指教

**Comment by gongxuanzhang** [comment]
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E5%9B%BE%E7%89%87%E5%AF%BC%E5%87%BA
文档中的URL导出方法是否是你的需求

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
