### ISSUE TITLE
请问如何实现当导入excel时，如果某行校验不通过，则在原文件该行最后新增一列追加错误信息？

### ISSUE THREAD

**Issue by yuanbing692** [alibaba/easyexcel#3258]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述

**Comment by gongxuanzhang** [comment]
在JavaBean增加一个属性，手动校验之后填充
