### ISSUE TITLE
写文件时报空指针，文件也损坏，打断点查看是context的excelProperty属性为null

### ISSUE THREAD

**Issue by tamlover** [alibaba/easyexcel#326]

**Comment by fuxinlin** [comment]
我照抄示例也碰到了，不知道你这是不是和我一样的情况，我这是少了BaseRowModel子类的Class参数。

修改前：

`Sheet sheet1 = new Sheet(1, 0);`

修改后：

`Sheet sheet1 = new Sheet(1, 0, UserModel.class);`

**Comment by tamlover** [comment]
@fuxinlin 啊，感谢啊老哥！
