### ISSUE TITLE
excel读取完成之后，获取总行数的方法被废弃，但是在替代方法中却没找到

### ISSUE THREAD

**Issue by kxxfydj** [alibaba/easyexcel#3265]
问题：
com.alibaba.excel.context.AnalysisContext#getTotalCount方法已经被废弃，然后让我们去com.alibaba.excel.context.AnalysisContext#readRowHolder()中获取，但是这个对象中没有获取总行数的方法

版本：3.3.2

**Comment by HugoBFHe** [comment]
有没有一种可能，业务需要每一行和总行数做处理
