### ISSUE TITLE
使用导出模板填充数据里面的没命中变量也会清理为空值的问题

### ISSUE THREAD

**Issue by ztl9624** [alibaba/easyexcel#3267]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
 ExcelWriter excelWriter = EasyExcel.write(response.getOutputStream())
                        .withTemplate(Thread.currentThread().getContextClassLoader()
                                .getResourceAsStream(String.format(EXCEL_FILE_PATH,
                                        ReportExportEnum.findByCode(type).getDesc()))).build();
Map<String, Integer> data = param(type, year); //param()是自己这边的获取业务数据转换成map详细就不放出来了
excelWriter.fill(data8, EasyExcel.writerSheet(ReportExportEnum.findByCode("8").getDesc()).build());
                    excelWriter.finish();
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述
![1686726891810](https://github.com/alibaba/easyexcel/assets/52037960/f80f66aa-359f-4f0e-b96a-6c6d0c0fb46c)
上图是我定义的变量，代码会把找到的变量替换数据没有找到的变量变成空值。我的问题是怎么把默认变成空值的这个操作变成默认变成0，感谢大佬们来解答。

**Comment by ztl9624** [comment]
我试过操作器但是没用不知道是不是我写的有问题。网上说是能用操作器但是操作器好像对ExcelWriter excelWriter = EasyExcel.write(response.getOutputStream())
                        .withTemplate(Thread.currentThread().getContextClassLoader()
                                .getResourceAsStream(String.format(EXCEL_FILE_PATH,
                                        ReportExportEnum.findByCode(type).getDesc()))).build();这段操作没什么作用

**Comment by gongxuanzhang** [comment]
可以提供一下模板吗  这边方便复现一下

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
