### ISSUE TITLE
xls格式文件导出oom

### ISSUE THREAD

**Issue by shuqingdadi** [alibaba/easyexcel#3270]
![image](https://github.com/alibaba/easyexcel/assets/25097201/0cd63c2f-3fc5-46fb-87d7-6958728cb22a)
我导出100w行数据，使用的是xls ，数据是分页获取的，数据写到一大半时候内存已经溢出了，2G内存，使用xlsx良好，是否只支持xlsx大数据量的导出

指定过excelType 也是一样

**Comment by gongxuanzhang** [comment]
xls行格式是有要求的 不能超过65536行
建议使用xlsx

**Comment by Tem-529** [comment]
@gongxuanzhang 您好，我在使用easyexcel 3.10版本 进行数据导出时发送了OOM，通过分析hprof文件， Xobj$ElementXobj 和 Xobj$AttrXobj 对象占比分别达到了2.5g和1.3g。导出文件类型为xlsx，数据量在35w左右，jvm最大堆内存为6g。

**Comment by Tem-529** [comment]
@gongxuanzhang 您好，我在使用easyexcel 3.10版本 进行数据导出时发生了OOM，通过分析hprof文件， Xobj$ElementXobj 和 Xobj$AttrXobj 对象占比分别达到了2.5g和1.3g。导出文件类型为xlsx，数据量在35w左右，jvm最大堆内存为6g。请问3.10以上版本有针对导出内存使用进行优化吗？ 目前在不增加内存的情况下，考虑使用两个方案，一个是减少不必要的单元格样式，一个是采用POI SXSSFWorkbook导出
![image](https://github.com/alibaba/easyexcel/assets/63625823/b26db6ce-a662-461b-b654-ff91df9a5ee3)

**Comment by gongxuanzhang** [comment]
> @gongxuanzhang 您好，我在使用easyexcel 3.10版本 进行数据导出时发生了OOM，通过分析hprof文件， Xobj$ElementXobj 和 Xobj$AttrXobj 对象占比分别达到了2.05g和1.8g。导出文件类型为xlsx，数据量在35w左右，jvm最大堆内存为6g。请问3.10以上版本有针对导出内存使用进行优化吗？ 目前在不增加内存的情况下，考虑使用两个方案，一个是减少不必要的单元格样式，一个是采用POI SXSSFWorkbook导出 ![image](https://user-images.githubusercontent.com/63625823/246063635-b26db6ce-a662-461b-b654-ff91df9a5ee3.png)

导出的时候默认就是SXSSFWorkbook
但是如果有很多样式可能会有奇奇怪怪的问题

**Comment by Tem-529** [comment]
> > @gongxuanzhang 您好，我在使用easyexcel 3.10版本 进行数据导出时发生了OOM，通过分析hprof文件， Xobj$ElementXobj 和 Xobj$AttrXobj 对象占比分别达到了2.05g和1.8g。导出文件类型为xlsx，数据量在35w左右，jvm最大堆内存为6g。请问3.10以上版本有针对导出内存使用进行优化吗？ 目前在不增加内存的情况下，考虑使用两个方案，一个是减少不必要的单元格样式，一个是采用POI SXSSFWorkbook导出 ![image](https://user-images.githubusercontent.com/63625823/246063635-b26db6ce-a662-461b-b654-ff91df9a5ee3.png)
> 
> 导出的时候默认就是SXSSFWorkbook 但是如果有很多样式可能会有奇奇怪怪的问题

好的，感谢，在考虑减少一些不必要的样式和单元格格式校验了

**Comment by gongxuanzhang** [comment]
> 

因为格式是固定的，所以poi尽量会选择复用。 如果格式多了就会留下来 可能会就导致释放不掉的情况

**Comment by gongxuanzhang** [comment]
> > > @gongxuanzhang 您好，我在使用easyexcel 3.10版本 进行数据导出时发生了OOM，通过分析hprof文件， Xobj$ElementXobj 和 Xobj$AttrXobj 对象占比分别达到了2.05g和1.8g。导出文件类型为xlsx，数据量在35w左右，jvm最大堆内存为6g。请问3.10以上版本有针对导出内存使用进行优化吗？ 目前在不增加内存的情况下，考虑使用两个方案，一个是减少不必要的单元格样式，一个是采用POI SXSSFWorkbook导出 ![image](https://user-images.githubusercontent.com/63625823/246063635-b26db6ce-a662-461b-b654-ff91df9a5ee3.png)
> > 
> > 
> > 导出的时候默认就是SXSSFWorkbook 但是如果有很多样式可能会有奇奇怪怪的问题
> 
> 好的，感谢，在考虑减少一些不必要的样式和单元格格式校验了

因为格式是固定上限数量的，所以poi尽量会选择复用。 如果格式多了就会留下来 可能会就导致释放不掉的情况

**Comment by shuqingdadi** [comment]
> xls行格式是有要求的 不能超过65536行 建议使用xlsx

你说的这个是单sheet页这么多行把，我这边单sheet 5w，分20个sheet 页

**Comment by Tem-529** [comment]
后面发现头部使用富文本了，为了富文本能正常展示使用了inMemory这个参数，这个参数产生的内存溢出

**Comment by attachmentList** [comment]
> @gongxuanzhang 您好，我在使用easyexcel 3.10版本 进行数据导出时发生了OOM，通过分析hprof文件， Xobj$ElementXobj 和 Xobj$AttrXobj 对象占比分别达到了2.05g和1.8g。导出文件类型为xlsx，数据量在35w左右，jvm最大堆内存为6g。请问3.10以上版本有针对导出内存使用进行优化吗？ 目前在不增加内存的情况下，考虑使用两个方案，一个是减少不必要的单元格样式，一个是采用POI SXSSFWorkbook导出 ![image](https://private-user-images.githubusercontent.com/63625823/246063635-b26db6ce-a662-461b-b654-ff91df9a5ee3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTE2MzcsIm5iZiI6MTczNTExMTMzNywicGF0aCI6Ii82MzYyNTgyMy8yNDYwNjM2MzUtYjI2ZGI2Y2UtYTY2Mi00NjFiLWI2NTQtZmY5MWRmOWE1ZWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA3MjIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMDIwZDJmYjdjMjY3MTgxYzhhOTY4ODJhYjFiMjU2MDI4NmMxOGYwOWEzNTJmY2YyM2FhZDM3MTE1NWVkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J9dnocMNH5QMOlbeIlii8--mtZgQyu1puBfmFWnvCAY)

我也是，导出文件这两个一直占用特别大，堆内存也释放不掉。内存居高不下

**Comment by attachmentList** [comment]
> inMemory

我是给加了水印，必须内存模式，直接溢出了，内存不释放
