### ISSUE TITLE
读取能否返回一个 迭代器 iterator 或者 实现 spring batch 的  itemReader 接口

### ISSUE THREAD

**Issue by qiaohhgz** [alibaba/easyexcel#3272]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java

```
# 异常提示

# 问题描述
读取能否返回一个 迭代器 iterator 或者 实现 spring batch 的 itemReader 接口

**Comment by gongxuanzhang** [comment]
暂不考虑,但你可以在拦截器中自己实现

**Comment by chenzhenjia** [comment]
我实现了一个简单的itemReader，还未经过测试，提供一下思路
https://gist.github.com/chenzhenjia/db411d93f960ca731526850243bd536a#file-easyexcelreader-kt
