### ISSUE TITLE
填充时动态设置单元格格式

### ISSUE THREAD

**Issue by he323219002** [alibaba/easyexcel#3283]
# 问题描述

场景：在模板fill的场景下，比如有一列是价格，如何渲染最低价所在的单元格格式 背景为灰色，字体加粗

**Comment by gongxuanzhang** [comment]
在内存中计算出最低价所在行  然后修改样式
修改样式参考文档
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F
