### ISSUE TITLE
导入问题

### ISSUE THREAD

**Issue by h1078787839** [alibaba/easyexcel#3285]
各位好。我在做导入的时候，有时候导入表格问题导入失败了。但是需要修改这个文件或者删除的时候发现代码在占用这个文件。有什么方法在导入失败或者出现异常的时候释放这个资源。

**Comment by gongxuanzhang** [comment]
导入是读取的意思吗？
读取发生错误也会释放资源的
最好能贴上代码看看是否是使用问题

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
