### ISSUE TITLE
读取第一行数据为null（实际从第二行开始读取）

### ISSUE THREAD

**Issue by Phantom0103** [alibaba/easyexcel#3287]
最近在维护一个古老的系统，不方便升级easyexcel（v2.2.6），发现一个问题。很简单的读取，就一列数据，没有表头，但是断点发现从第2行读取，然后最后还多读取了一行，导致结果就是条数对的，但是最后一个元素是null的。excel内容如下：
<img width="161" alt="企业微信截图_16873391511045" src="https://github.com/alibaba/easyexcel/assets/50362495/0825e90b-a606-4eea-bd98-0c590edbeeeb">

运行时如下：
<img width="594" alt="企业微信截图_16873380749389" src="https://github.com/alibaba/easyexcel/assets/50362495/02c7f5f6-f631-4b69-9d81-5faed2685776">

看的出来是读取的2 3 4 5行数据，listener就比较简单了：
```
public class ExcelListener<T> extends AnalysisEventListener<T> {
    @Override
    public void invoke(T object, AnalysisContext context) {
        //当前行
        // context.getCurrentRowNum()
        if (object != null) {
            datas.add(object);
        }
    }
```

在不升级的情况下，这个问题怎么解决？

**Comment by Phantom0103** [comment]
通过设置```headRowNumber(0)```解决了，但是另外一个问题还存在，就是多读取了末尾的空行，说是要升级版本，只能先在```invoke```里面判断一下。

**Comment by gongxuanzhang** [comment]
你的理解和解决方式都是对的。
excel reader 默认是有表头的
