### ISSUE TITLE
想实现一下就是只锁住一个单元格的某一列数据如何实现？

### ISSUE THREAD

**Issue by shujinghuan2022** [alibaba/easyexcel#3288]
就是在导出excel之后如何能锁住一个sheet页中有内容数据部分的某一列，然后对其他没有数据的单元格可以随意编辑。

**Comment by gongxuanzhang** [comment]
没法实现.. POI应该也不行

**Comment by shujinghuan2022** [comment]
> 没法实现.. POI应该也不行

其实我 想能不能就是找到cell的属性是在哪里吧这个lock设施为true的但是没有找到

**Comment by gongxuanzhang** [comment]
拿到cell的style对象
setLock  
要配合protectSheet使用

**Comment by shujinghuan2022** [comment]
> 拿到cell的style对象 setLock 要配合protectSheet使用

大佬我就是按照你说的这种进行操作的，只能实现对有内容填充部分的单元格实现了锁定与非锁定的效果。没有内容部分的单元格都锁定了，如何实现对没有内容填充的单元格实现不锁定的效果，大佬你有什么方法吗？

**Comment by jacentsao** [comment]
> > 拿到cell的style对象 setLock 要配合protectSheet使用
> 
> 大佬我就是按照你说的这种进行操作的，只能实现对有内容填充部分的单元格实现了锁定与非锁定的效果。没有内容部分的单元格都锁定了，如何实现对没有内容填充的单元格实现不锁定的效果，大佬你有什么方法吗？

最后有解决吗，这个东西真是奇怪，未填充内容的末尾行居然锁定
