### ISSUE TITLE
请问如何让继承ExcelWriteFillExecutor的自定义Executor正常工作

### ISSUE THREAD

**Issue by repins21** [alibaba/easyexcel#3289]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码

使用方式
![image](https://github.com/alibaba/easyexcel/assets/53001537/e06bfe97-3f49-47a1-9c09-3a22ee4ca80c)

修改了doFill方法获取值
![image](https://github.com/alibaba/easyexcel/assets/53001537/dbf2ebd0-5e63-4bb5-8c2a-36d03028a03c)

![image](https://github.com/alibaba/easyexcel/assets/53001537/d5daf584-1a24-4ecf-81e8-22f35c86e547)

![image](https://github.com/alibaba/easyexcel/assets/53001537/556a3cbe-00a8-45bf-bf9e-57bbb06d0b96)

# 异常提示
无
# 问题描述
继承了ExcelWriteFillExecutor，只修改了从 doFill 方法从 dataMap 中取值的方式，其他方法和属性完全从ExcelWriteFillExecutor中复制，填充过程中未报错，debug没发现异常，但是查看输出文件发现并未进行填充，请问和上下文有关吗？

**Comment by xiaotiejuan** [comment]
这个问题现在解决了吗？
