### ISSUE TITLE
表头有办法兼容大小写么？

### ISSUE THREAD

**Issue by lanxikun** [alibaba/easyexcel#3292]
比如我指定了 @ExcelProperty("ICD")
我希望，它既可以识别 大小的 ICD，也可以识别 小写的 icd  或者 大小写混合的 Icd

**Comment by gongxuanzhang** [comment]
兼容大小写是什么意思

**Comment by lanxikun** [comment]
就是想让 @ExcelProperty 忽略大小写，只要 字母相同，不论大小写，它 都可以 识别

**Comment by gongxuanzhang** [comment]
不支持，可以考虑不用实体，使用Map接受
