### ISSUE TITLE
如何填充数组或者List<String> ？

### ISSUE THREAD

**Issue by SGYQ** [alibaba/easyexcel#3304]
如何向Excel模板中填充一个字符串数组，或者一个List<String> ？？Excel模板如何设置？

**Comment by gongxuanzhang** [comment]
数组和集合被视为特殊类型，需要在实体中自定义转换器，即可导出

**Comment by elcnu986** [comment]
> 数组和集合被视为特殊类型，需要在实体中自定义转换器，即可导出

定义一个类，把这个集合放到这个类的属性里？
