### ISSUE TITLE
excel导出时存在缓存bug

### ISSUE THREAD

**Issue by qq664042** [alibaba/easyexcel#3305]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
多次动态导出数据文件为excel时，会出bug;
比如第一次导出，指定
excelWriterBuilder.registerConverter(new LongStringConverter());
excelWriterBuilder.registerConverter(new DoubleStringConverter());
可以正常导出，
第2次导出，没有注册这两个Converter，他还是会使用这两个Converter,导出的文件的数据类型就不对了。

# 触发Bug的代码
```java
第一次导出
ExcelWriterBuilder excelWriterBuilder = EasyExcel.write(outputStream);
excelWriterBuilder.registerConverter(new LongStringConverter());
excelWriterBuilder.registerConverter(new DoubleStringConverter());

第二次导出：
ExcelWriterBuilder excelWriterBuilder = EasyExcel.write(outputStream);

但是实际执行的时候，发现使用第一次的缓存
com.alibaba.excel.util.ClassUtils.CONTENT_CACHE
结果还是相当于注册了LongStringConverter DoubleStringConverter
```

**Comment by gongxuanzhang** [comment]
什么版本的easyexcel。
3.3.2这个问题应该已经解决
