### ISSUE TITLE
对象嵌套数组，怎么填充

### ISSUE THREAD

**Issue by chenyu9390** [alibaba/easyexcel#3307]
有一个对象数组，对象里面又嵌套数组，应该怎么填充excel
![image](https://github.com/alibaba/easyexcel/assets/8199403/997353b2-76ec-45c0-8a0a-3282ecb736ce)
![image](https://github.com/alibaba/easyexcel/assets/8199403/4bc626be-c27e-430a-92f5-4a962601e4ad)
填充模板
![image](https://github.com/alibaba/easyexcel/assets/8199403/cbd8de4b-f79d-45aa-85ed-7c336ee77358)

**Comment by chenhao-ah** [comment]
同问

**Comment by gongxuanzhang** [comment]
如果是模板填充模式，只能再适配一次。
easyexcel暂时不支持多级对象。
在写模式下 如果你的嵌套对象想输入在一列中 
你可以自定义转换器
参考https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E6%97%A5%E6%9C%9F%E6%95%B0%E5%AD%97%E6%88%96%E8%80%85%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%BC%E5%BC%8F%E8%BD%AC%E6%8D%A2
写一个关于List<TemplateTexportData> 的转换方法，
如果你希望把集合中的数据变成多列，建议使用POI或者用map的方式进行write
