### ISSUE TITLE
  com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLStreamReader;

### ISSUE THREAD

**Issue by HaiRunTian** [alibaba/easyexcel#3308]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
      val fileName: String =
            Environment.getExternalStorageDirectory().path + "/simpleWrite" + System.currentTimeMillis() + ".xlsx"
        Log.i("TAG","fileName=" + fileName)
        if (!File(fileName).exists()){
            File(fileName).createNewFile()
        }
        // 这里 需要指定写用哪个class去写，然后写到第一个sheet，名字为模板 然后文件流会自动关闭
        // 如果这里想使用03 则 传入excelType参数即可
        EasyExcel.write(fileName, DemoData::class.java)
            .sheet(1,"11")
            .doWrite { data() }
        
    }

Android 使用3.3.2版本，导出数据异常，i请问呢这是什么问题呢

**Comment by frankggyy** [comment]
android 3.3.2对应JDK 6，你引入的easyexcel是哪个版本？
请参考[easyexcel版本选择](https://easyexcel.opensource.alibaba.com/qa/#%E5%85%B3%E4%BA%8E%E7%89%88%E6%9C%AC%E9%80%89%E6%8B%A9)

**Comment by HaiRunTian** [comment]
邮件已经收到，谢谢
