### ISSUE TITLE
因为使用了mybatis-Plus 实体类已经有继承了 不想在写一个modle

### ISSUE THREAD

**Issue by sonictuzi** [alibaba/easyexcel#331]

**Comment by sonictuzi** [comment]
还有 注解写出的时候如何 从long 转换成data 格式呢

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
