### ISSUE TITLE
Excel读取一个sheet复制到新的sheet，只读sheet不读数据可以实现吗

### ISSUE THREAD

**Issue by a13269756843** [alibaba/easyexcel#3313]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述

**Comment by a13269756843** [comment]
复制一个sheet到新的excel，不用管里面的数据  只复制sheet到指定的sheetNo

**Comment by gongxuanzhang** [comment]
不可以实现  只能一个一个来
