### ISSUE TITLE
文档中-重复多次写入(写到单个或者多个Sheet)这里，例子没有ExcelWriter.finish语句

### ISSUE THREAD

**Issue by CCblibo** [alibaba/easyexcel#3315]
不finish会导致ExcelWrite一直没结束，直接就生成excel导致文件损坏。

**Comment by gongxuanzhang** [comment]
try-with-source中会自动调用close方法 close中有finish.
请仔细看例子

**Comment by CCblibo** [comment]
受教

**Comment by LSL1618** [comment]
如果不用try-with-source的写法，建议加上`excelWriter.finish();`
