### ISSUE TITLE
CSV文件解析-某一条数据内部分字段值为null

### ISSUE THREAD

**Issue by NiYueLiuFeng** [alibaba/easyexcel#3316]
easyexcel版本:3.1.1

解析的文件大小-超过100万行数据。

两次偶然出现，CSV文件解析，某一条数据内部分字段值为null，其他字段值正常的情况。

尝试重复解析后，能正常获取所有字段（单元格）的值。
所以该问题无法复现。

在项目中使用了easyexcel，为确保稳定解析。请问该如何避免这个问题喔？

**Comment by gongxuanzhang** [comment]
csv本质上是一个逗号分割的数据文件，不存在null的说法。
只要是逗号分割的都是可以解析的，但是如果csv数据本身有问题可能需要处理一下

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
