### ISSUE TITLE
easyexcel 2.2.10版本forceNewRow(Boolean.TRUE)覆盖原有数据

### ISSUE THREAD

**Issue by superzhangquansong** [alibaba/easyexcel#3318]
public static void main(String[] args) throws Exception {
        // 模板注意 用{} 来表示你要用的变量 如果本来就有"{","}" 特殊字符 用"\{","\}"代替
        String templateFile = "/Users/super_song/Downloads/IntlContractTemplate.xlsx";
        String targetFileName = "/Users/super_song/Downloads/testNew.xlsx";
        // 创建一个工作簿对象
        ExcelWriter workBook = EasyExcel.write(targetFileName).withTemplate(templateFile).build();
        // 创建工作表对象
        WriteSheet sheet = EasyExcel.writerSheet().build();
        FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.TRUE).build();
        // 准备数据
        List<FillData> students = initFillData();
        // 多组数据填充
        workBook.fill(students, fillConfig, sheet);
        // 关闭流 ！！！
        workBook.finish();
    }
我的Excel主要分成三部分，头部是固定的内容，中间是动态插入数据的区域，底部是固定的内容。三部分都存在样式。
现在遇到的问题是我能成功插入数据，但是插入的数据会破坏底部的样式已经会覆盖底部的内容。

**Comment by frankggyy** [comment]
FillConfig需要设置`direction = WriteDirectionEnum.VERTICAL`，`forceNewRow(Boolean.TRUE)`才能生效。
```java
FillConfig fillConfig = FillConfig.builder()
    .setDirection(WriteDirectionEnum.VERTICAL)
    .forceNewRow(Boolean.TRUE)
    .build()

// or
// FillConfig fillConfig = FillConfig.builder()
//    .forceNewRow(Boolean.TRUE)
//    .build()
//    .init()
```

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
