### ISSUE TITLE
关于0读取为_x0030_

### ISSUE THREAD

**Issue by SunIsEnergy** [alibaba/easyexcel#3322]
# 问题描述
将excel单元格中0101000000914读取为_x0030_101000000914。
同样:990902100731读取为_x0039_90902100731。
猜测是编码问题导致。

备注:POI测试读取正常

**Comment by SunIsEnergy** [comment]
![20230711_103105](https://github.com/alibaba/easyexcel/assets/107131949/efaf75bb-bd1c-4f13-9469-b34775c16e8d)
![20230711_103221](https://github.com/alibaba/easyexcel/assets/107131949/515208b2-a06d-4a92-ab8b-d3b12f7be599)

**Comment by SunIsEnergy** [comment]
![20230711_103221](https://github.com/alibaba/easyexcel/assets/107131949/53e78427-2468-45d8-8539-286ff170dc52)

**Comment by gongxuanzhang** [comment]
你这个是CSV吗

**Comment by SunIsEnergy** [comment]
.xlsx呢

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
