### ISSUE TITLE
the log of ReadTest.simpleRead do not work

### ISSUE THREAD

**Issue by taoyect** [alibaba/easyexcel#3324]
# 触发场景描述
com.alibaba.easyexcel.test.demo.read.ReadTest#simpleRead
# 触发Bug的代码
```java
   log.info("读取到一条数据{}", JSON.toJSONString(demoData));
```
# 提示的异常或者没有达到的效果
通过 System.out.println(log); 发现输出的是 org.slf4j.helpers.NOPLogger(NOP)，手动换了pom的日志相关的dependency能够正常输出日志。

**Comment by frankggyy** [comment]
reviewed and merged.
thanks for your contribution @axing199112
