### ISSUE TITLE
根据模板导出数据，日期单元格样式异常

### ISSUE THREAD

**Issue by YorushikaTopFans** [alibaba/easyexcel#3326]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
**版本**：3.3.2
**根据模板导出数据的模版如下：**
* 这是异常的日期单元格的样式：
![image](https://github.com/alibaba/easyexcel/assets/26869783/a9a3c672-9895-4fb4-9824-201691e3c8ad)

* 这是列表中的日期单元格的样式（和上图单元格的样式设置一模一样）：
![image](https://github.com/alibaba/easyexcel/assets/26869783/4015b730-5dd5-4df7-8e7b-c5607b30b788)

* 模版类中的日期注解（也是一模一样的）：
![image](https://github.com/alibaba/easyexcel/assets/26869783/a0e97b99-89f1-44cb-9b37-c8dccb6fa5b6)

* 导出之后的异常日期样式（单元格中设置好的样式全部被清空了）：
![image](https://github.com/alibaba/easyexcel/assets/26869783/75e5d1ec-8e6e-49c0-bec0-564135f1d298)

* 但列表中的日期样式是正常的：
![image](https://github.com/alibaba/easyexcel/assets/26869783/d7ea84f1-0996-47bd-8298-280a31503ce5)

# 触发Bug的代码
```java
  // com.alibaba.excel.write.executor.ExcelWriteFillExecutor.java
  // com.alibaba.excel.write.executor.ExcelWriteFillExecutor#doFill(List<AnalysisCell> analysisCellList, Object oneRowData, FillConfig fillConfig,Integer relativeRowIndex)
  // 第232行：列表类型的 doFill() 会多执行一次这段代码去重新设置样式
  // Restyle
  if (fillConfig.getAutoStyle()) {
      Optional.ofNullable(collectionFieldStyleCache.get(currentUniqueDataFlag))
          .map(collectionFieldStyleMap -> collectionFieldStyleMap.get(analysisCell))
          .ifPresent(cellData::setOriginCellStyle);
  }
```
# 提示的异常或者没有达到的效果
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。

**Comment by frankggyy** [comment]
请尝试设置写入样式，参考代码如下：
```java
import java.util.Date;

import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.annotation.format.DateTimeFormat;
import com.alibaba.excel.annotation.write.style.ContentStyle;
import com.alibaba.excel.annotation.write.style.HeadFontStyle;
import com.alibaba.excel.annotation.write.style.HeadStyle;
import com.alibaba.excel.enums.poi.HorizontalAlignmentEnum;
import com.alibaba.excel.enums.poi.VerticalAlignmentEnum;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@EqualsAndHashCode
@HeadStyle
@HeadFontStyle
public class StyleData {
    @ExcelProperty("字符串")
    private String string;
    @ExcelProperty("字符串1")
    private String string1;

    @DateTimeFormat("yyyy/MM/dd")
    @ContentStyle(verticalAlignment = VerticalAlignmentEnum.CENTER, horizontalAlignment = HorizontalAlignmentEnum.CENTER)
    private Date birthDay;
}
```

**Comment by CodeStudying** [comment]
请问这个有什么解决办法吗
