### ISSUE TITLE
使用模板填充列表时,列表中的对象里面有嵌套的对象,这个嵌套的对象属性如何进行模板填充.例如:列表的对象属性可用{.name},那嵌套的对象{.people.name}如何填充

### ISSUE THREAD

**Issue by chenhao-ah** [alibaba/easyexcel#3336]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述

**Comment by hutdonrun** [comment]
求助，一样的问题，我是来一下好像不行

**Comment by ethancat** [comment]
一样的诉求

**Comment by gongxuanzhang** [comment]
目前不支持嵌套对象,在规划一个比较好的解决方案

**Comment by chenhao-ah** [comment]
肝了一天源码,重写ExcelWriteFillExecutor这个类,可以实现

**Comment by luoqingming110** [comment]
一样的问题

**Comment by luoqingming110** [comment]
> 肝了一天源码,重写ExcelWriteFillExecutor这个类,可以实现

源码能发出来吗

**Comment by luoqingming110** [comment]
@chenhao-ah  代码能发出来吗

**Comment by chenhao-ah** [comment]
![image](https://github.com/alibaba/easyexcel/assets/77044797/729149e3-a086-4a50-8d4c-1a1985225bf6)
if (!dataKeySet.contains(variable) && !variable.startsWith("errorDataMap")) {
                            continue;
                        }

                        Object value = ((Map)dataMap).get(variable);
                        if (value == null) {
                            String[] split = variable.split("\\.");
                            if (split.length > 1) {
                                Object map = ((Map)dataMap).get(split[0]);
                                Map<String, Object> hutoolMap = BeanUtil.beanToMap(map, new String[0]);
                                if (!hutoolMap.isEmpty()) {
                                    value = hutoolMap.get(split[1]);
                                    variable = split[1];
                                }
                            }
                        }

**Comment by chenhao-ah** [comment]
占位符的那个判断可以优化一下,就看你具体需求了
