### ISSUE TITLE
使用Date类型报错与 当数据源是List<JSONObject>时 导出数据为空只有标题

### ISSUE THREAD

**Issue by liuzhe101** [alibaba/easyexcel#3337]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
<img width="1151" alt="image" src="https://github.com/alibaba/easyexcel/assets/61652514/e05bccec-c998-430e-b29b-4dd68a19d81a">

# 触发Bug的代码
```java
问题1:
  @ExcelProperty("DIP生产时间")
    @DateTimeFormat("yyyy-MM-dd HH:ss:mi")
    Date afterFurnaceDate;
    @ExcelProperty("包装时间")
    @DateTimeFormat("yyyy-MM-dd HH:ss:mi")
    Date packingDate;
    @ExcelProperty("上料时间")
    @DateTimeFormat("yyyy-MM-dd HH:ss:mi")
    Date onLineDate;
EasyExcel.write(response.getOutputStream(), clazz).registerWriteHandler(writeHandler).sheet(sheetName).doWrite(dataList);
问题2:
当dateList为List<JSONObject> 导出数据为空  初步定位 赋值是。行map值 获取是。是通过索引下标get
EasyExcel.write(response.getOutputStream(), clazz).registerWriteHandler(writeHandler).sheet(sheetName).doWrite(dataList);
```
# 提示的异常或者没有达到的效果
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。

**Comment by gongxuanzhang** [comment]
clazz要和你的List数据一致

**Comment by gongxuanzhang** [comment]
最好使用文档中的例子 自定义成自己的

**Comment by liuzhe101** [comment]
> 最好使用文档中的例子 自定义成自己的

当是JSONObejct时。clazz使用JSONObject.class?

**Comment by liuzhe101** [comment]
> 最好使用文档中的例子 自定义成自己的

还有第一个问题呢，当是Date类型 ，导出就报错

**Comment by gongxuanzhang** [comment]
> > 最好使用文档中的例子 自定义成自己的
> 
> 当是JSONObejct时。clazz使用JSONObject.class?

JSONObject 和map的使用方式一样 ，尽量使用文档中的 head指定
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E4%B8%8D%E5%88%9B%E5%BB%BA%E5%AF%B9%E8%B1%A1%E7%9A%84%E5%86%99

但是不推荐， 你拿到jsonobject很容易转换成对应实体 

报错问题需要你提供一些能复现的代码 ，从图中看甚至可能是版本冲突
