### ISSUE TITLE
合并单元格后，计数不是1的问题

### ISSUE THREAD

**Issue by xzxiaoshan** [alibaba/easyexcel#3338]
![image](https://github.com/alibaba/easyexcel/assets/16459864/ed0c305d-1b27-4814-99b4-8d9da356a0ea)

# 触发Bug的代码
```java
  # 使用的代码是参考官网的示例
  registerWriteHandler(loopMergeStrategy)
```

**Comment by gongxuanzhang** [comment]
这是期待的效果，你拆分单元格之后仍然可以变成合并之前的小单元格内容。

**Comment by guanpeijia** [comment]
> 这是期待的效果，你拆分单元格之后仍然可以变成合并之前的小单元格内容。
既然合并，大部分场景还是希望计数为1吧？而且这个合并导出，修改Excel的数据，只能修改第一个小单元格的数据，并不能将合并单元格里面的所有小单元格内容改变
