### ISSUE TITLE
AnalysisEventListener监听器中不能使用@Resource或者Autowired吗？为啥报空指针异常

### ISSUE THREAD

**Issue by 630533753** [alibaba/easyexcel#3341]
@Autowired
   private UserService userService;
![image](https://github.com/alibaba/easyexcel/assets/128342324/b7dc2e87-bc2f-4efe-a67e-4396cda1c0a3)
![image](https://github.com/alibaba/easyexcel/assets/128342324/c7b61b57-704c-4e23-b515-f2cd36e6d66e)
![image](https://github.com/alibaba/easyexcel/assets/128342324/a8c46b2b-09f5-44e0-96e2-6ab6041b1f67)

**Comment by frankggyy** [comment]
目前暂未实现与Springboot的集成，easyexcel不在spring容器中管理。后续版本会提供与Springboot的集成。
