### ISSUE TITLE
readBySax Sax读取文件如何返回Excel数据

### ISSUE THREAD

**Issue by pussyboots** [alibaba/easyexcel#335]
您好:
```
 ExcelListener excelListener = new ExcelListener();
 EasyExcelFactory.readBySax(inputStream, new Sheet(1, 2, UserLikeModel.class), excelListener);
```

在监听器中处理数据--引入不了接口service  service 为null,就无法调用存数据入库

easyexcel 版本 1.1.2-beta5

![image](https://user-images.githubusercontent.com/20161534/56806960-0580ff80-6860-11e9-82df-9a9b07f7b211.png)

谢谢

**Comment by Xia-Bin** [comment]
package cn.com.polygon.excel.util;

import javax.annotation.PostConstruct;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import cn.com.polygon.service.price.commodity.CommodityService;

/** 
 * @Description: listen 类中不能注入server：能通过这个工具类，加载server 类；
 * @author Larray.
 * @date 2019年5月5日 下午2:48:17 
 * @ClassName: InJectServiceUtil
 *  
 */
@Component
public class InJectServiceUtil {
    @Autowired
    public CommodityService commodityService;
    
    @PostConstruct
    public void init() {
	InJectServiceUtil.getInStance().commodityService = this.commodityService;
    }
    
    /**
     *  实现单例 start
     */
    private static class SingletonHolder {
        private static final InJectServiceUtil INSTANCE = new InJectServiceUtil();
    }
    private InJectServiceUtil (){}
    public static final InJectServiceUtil getInStance() {
        return SingletonHolder.INSTANCE;
    }
    /**
     *  实现单例 end
     */
    public CommodityService getCommodityService(){
        return InJectServiceUtil.getInStance().commodityService;
    }
   

    
}

**Comment by pussyboots** [comment]
ok 谢谢!
