### ISSUE TITLE
百分比单元格式

### ISSUE THREAD

**Issue by usawjq** [alibaba/easyexcel#3352]
如何设置excel单元格格式为 百分比，小数位数为2
目前文档中提供的NumberFormat("#.##%") 在excel中显示的是自定义格式
如果出现0.00%这种会展示成 .%
求问设置格式为百分比格式，小数位数为2，期望在excel中展示0.00% （百分比格式） 求问如何设置

![KMK%C8AXU 86JF JF_ZMG9A](https://github.com/alibaba/easyexcel/assets/31095758/9346a37a-589f-43b0-bf5c-fe6555018bf5)

**Comment by usawjq** [comment]
问题已解决，谢谢

**Comment by biggerdamage** [comment]
> 问题已解决，谢谢

请问咋解决的

**Comment by yikus-tjq** [comment]
怎么解决的？
