### ISSUE TITLE
表示时长的Long型毫秒数转换成 时:分:秒 导出的Excel在非编辑态能求和如何实现

### ISSUE THREAD

**Issue by LuoMv** [alibaba/easyexcel#3355]
# 代码
![image](https://github.com/alibaba/easyexcel/assets/77734886/0011337a-3ee6-4d36-915f-35c2228c7d5e)
![image](https://github.com/alibaba/easyexcel/assets/77734886/0e9bfa97-1c07-4179-b061-8b7cd982ef82)
实现CellWriteHandler重写afterCellDispose，指定该列单元格的格式为46->[h]:mm:ss
![image](https://github.com/alibaba/easyexcel/assets/77734886/333a5e9e-a2cd-4a98-9677-657986ff0026)

# 导出效果
![image](https://github.com/alibaba/easyexcel/assets/77734886/434d2a87-048d-4382-9899-fe9c8ce39e70)
![image](https://github.com/alibaba/easyexcel/assets/77734886/d3721f45-d704-4c7d-9f4b-b847a4f4a786)

# 问题描述
想实现表示时长的Long型毫秒数转换成 时:分:秒 导出的Excel在非编辑态能求和，使用了上述方法导出Excel后该列无法求和，但是双击两个单元格之后可以求和，求个解决方法

**Comment by yuhaowin** [comment]
持续时间的相加和时间的相加是不一样的概念
如：持续 3h + 持续 23h = 持续 26h，
但是3点+23点 = 2点

<img width="630" alt="image" src="https://github.com/alibaba/easyexcel/assets/34699768/11da5f20-7882-4157-887d-1bd41eb099cb">

**Comment by LuoMv** [comment]
> 持续时间的相加和时间的相加是不一样的概念 如：持续 3h + 持续 23h = 持续 26h， 但是3点+23点 = 2点
> 
> <img alt="image" width="630" src="https://user-images.githubusercontent.com/34699768/256274309-11da5f20-7882-4157-887d-1bd41eb099cb.png">

是的，时长和时间不是一个概念，我使用的那种转换方法是错误的。因为这个时长我们需要给用户直接能使用SUM函数进行累加求和，要做成时:分:秒这种格式来表示时长以便于能统计总时长。虽然h:mm:ss表示的是一个时间而非时长的格式，但是我尝试在Excel里面输出这种格式的字符串后指定其格式后求和是可以实现的，就是不知道使用EsayExcel如何在代码中实现。

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
