### ISSUE TITLE
模板{}转义问题,转义符会保留

### ISSUE THREAD

**Issue by java-silence** [alibaba/easyexcel#3356]
单个\\{name\\}会保留原样\\{name\\}, 如果想生成结果为{name}, 可以加个{XXX}占位符. 譬如: \\{name\\}{XXX任意字符}, 结果为{name}

**Comment by gongxuanzhang** [comment]
如果需要特殊转义比较好的方法是在代码里把需要的数据填充，不要在模板上太花哨

**Comment by Farb** [comment]
@gongxuanzhang  我擦，能不能好好看看人家的需求，随便搪塞几句就关了，类似的issue有好几个了，也有提PR的，能不能用点心啊

**Comment by lijileiGood** [comment]
> @gongxuanzhang 我擦，能不能好好看看人家的需求，随便搪塞几句就关了，类似的issue有好几个了，也有提PR的，能不能用点心啊

我想说没说, easyexcel刚开始了解这个项目

**Comment by Farb** [comment]
ExcelWriteFillExecutor.java 这个文件的prepareData这个方法，有问题

**Comment by gongxuanzhang** [comment]
模板是为了满足复杂样式功能需求，数据中完全可以填充，比如说数据脱敏的需求是数据层面的，不是excel模板的功能

> @gongxuanzhang 我擦，能不能好好看看人家的需求，随便搪塞几句就关了，类似的issue有好几个了，也有提PR的，能不能用点心啊

**Comment by java-silence** [comment]
> 模板是为了满足复杂样式功能需求，数据中完全可以填充，比如说数据脱敏的需求是数据层面的，不是excel模板的功能
> 
> > @gongxuanzhang 我擦，能不能好好看看人家的需求，随便搪塞几句就关了，类似的issue有好几个了，也有提PR的，能不能用点心啊

客户提供的模板包含大量的以大括号括起来的默认值, 这种应该属于模板部分.  把这些信息以数据填充,固然能实现, 可代码中包含大量的这种默认的数据, 如果模板修改,还得去修改代码, 是否合理?
