### ISSUE TITLE
如何自定义颜色？

### ISSUE THREAD

**Issue by VectorWen** [alibaba/easyexcel#336]
Poi 有如下的API
```java
XSSFCellStyle cellStyle = workbook.createCellStyle();
style.setFillForegroundColor(new XSSFColor(new Color(0x00, 0xf0, 0)));
```

可以我在TableStyle 无法配置，ExcelWriter 也没有提供方法获取WriteContext，进而无法获取Workbook，所以无法自定义颜色了。

是否有解决方案呢？求解

**Comment by Aronlele** [comment]
他的poi版本太老了

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
