### ISSUE TITLE
一级表头不同二级表头相同,如果二级表头相邻会触发合并操作问题

### ISSUE THREAD

**Issue by Uinie** [alibaba/easyexcel#3362]
![image](https://github.com/alibaba/easyexcel/assets/109409743/b0384a15-719b-463a-a14b-fa6976cac35f)

![image](https://github.com/alibaba/easyexcel/assets/109409743/0f63cf4c-c425-4bfc-a8c6-733b38916dd5)

**Comment by gongxuanzhang** [comment]
可以在导出时设置 automaticMergeHead(false).
```java
  EasyExcel.write(fileName).head(head()).sheet("模板").automaticMergeHead(false).doWrite(dataList());
```

**Comment by Uinie** [comment]
> 可以在导出时设置 automaticMergeHead(false).
> 
> ```java
>   EasyExcel.write(fileName).head(head()).sheet("模板").automaticMergeHead(false).doWrite(dataList());
> ```

使用后一级表头也会不合并

**Comment by gongxuanzhang** [comment]
那只能关闭自动合并然后手动合并表头

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
