### ISSUE TITLE
批注如何设置宽度和高度？

### ISSUE THREAD

**Issue by Naylor55** [alibaba/easyexcel#3364]

**Comment by Naylor55** [comment]
据我观察，批注得宽度默认就是列宽。然后我尝试显式指定列宽，再然后似乎宽度问题解决了。

~~~java 

@Getter
@Setter
@EqualsAndHashCode
public class DemoData {
    @ExcelProperty("字符串标题")
    private String string;

    @ColumnWidth(50)
    @ExcelProperty("日期标题")
    private Date date;

    @ExcelProperty("数字标题")
    private Double doubleData;

    /**
     * 忽略这个字段
     */
    @ExcelIgnore
    private String ignore;
}

~~~

**Comment by gongxuanzhang** [comment]
可以根据文档实现插入批注
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E6%8F%92%E5%85%A5%E6%89%B9%E6%B3%A8

通过拦截器调用原生API即可实现设置样式

**Comment by gongxuanzhang** [comment]
> 可以根据文档实现插入批注 https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E6%8F%92%E5%85%A5%E6%89%B9%E6%B3%A8
> 
> 通过拦截器调用原生API即可实现设置样式

没有默认API 就需要使用POI去实现
