### ISSUE TITLE
各位大佬，我在做自定义表单的过程中，需要进行数据的导入，后台无固定实体，通过easyexcel有什么好的思路，对poi不是很熟悉，求助！！！

### ISSUE THREAD

**Issue by vipMhr20150820** [alibaba/easyexcel#3365]
# 问题描述
## excel 样式截图
![image](https://github.com/alibaba/easyexcel/assets/29145257/69fa71a6-b11d-4292-966b-76420deea2a0)
## 怎么才能将excel的数据解析成以下JSON格式，方面插入mongo数据库
```json
{
	"项目类型": "软件项目",
	"项目编号": "T-KF001",
	"项目名称": "软件项目001",
	"立项日期": "2023-07-01",
	"预计交付日期": "2023-12-01",
	"工期计划": [{
		"计划日期": "2023-08-01",
		"计划内容": "开始开发",
		"参与人员": "张三、王五、李四",
		"是否交付": "否"
	}, {
		"计划日期": "2023-08-01",
		"计划内容": "开始开发",
		"参与人员": "嘻嘻、哈哈",
		"是否交付": "否"
	}],
	"测试动态表单": [{
		"单行文本": "测试动态表单1",
		"单行文本": "测试动态表单1",
		"单行文本": "测试动态表单1",
		"单行文本": "测试动态表单1"
	}, {
		"单行文本": "测试动态表单1",
		"单行文本": "测试动态表单1",
		"单行文本": "测试动态表单1",
		"单行文本": "测试动态表单1"
	}]
}
```

**Comment by gongxuanzhang** [comment]
你可以参考文档进行读取
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/read
如果没有固定实体可以按列号读成Map
然后进行数据组织。
数据组织可以使用stream的collector分组和添加.

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
