### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by coca-cola33** [alibaba/easyexcel#337]
编译时报错：Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\xxxx\.gradle\caches\modules-2\files-2.1\org.apache.xmlbeans\xmlbeans\2.6.0\29e80d2dd51f9dcdef8f9ffaee0d4dc1c9bbfc87\xmlbeans-2.6.0.jar
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: org.apache.xmlbeans.xml.stream.XMLName

**Comment by sas1991** [comment]
implementation 'org.apache.xmlbeans:xmlbeans:3.1.0'

**Comment by fish7790714** [comment]
重新clean编译下 gradle 有时候经常会莫名其妙错误 。
