### ISSUE TITLE
导出设置列隐藏不生效,求助

### ISSUE THREAD

**Issue by wdkGitHub** [alibaba/easyexcel#3376]
使用注解   ` @ContentStyle(hidden = BooleanEnum.TRUE, locked = BooleanEnum.TRUE)` 设置隐藏,不生效,还是我用错了, easyexcel是最新版本

**Comment by yikengboy** [comment]
`@ExcelProperty("需求id") @ColumnWidth(0) private Long id;`
我设置成0 为什么还是会显示这列
