### ISSUE TITLE
请问在导出时，写入excel的拦截器部分，可以获取即将写入excel的数据总行数吗

### ISSUE THREAD

**Issue by Greenjiao** [alibaba/easyexcel#3378]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java

```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述
![2023-08-01_120132](https://github.com/alibaba/easyexcel/assets/80018120/088ba58e-0709-443f-b25f-eb337968868c)
是这样的，我想给导出的excel部分列的所有行都设置自定义下拉框，按demo所写的需要提供一个行范围值，但是我没找到在这个拦截器中如何通过context获取到即将导入的数据条数

**Comment by gongxuanzhang** [comment]
无法获取，但是可以获取目前已经写入的行数。
一种可以获取的方式需要直接把所有数据内容全都读到内存，很占用空间.

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
