### ISSUE TITLE
怎么设置某一列的单元格格式为百分比

### ISSUE THREAD

**Issue by sun10000** [alibaba/easyexcel#3381]
请问，我想实现设置某一列的单元格格式为百分比，没有找到相关的解决方法，这个easyexcel支持吗？

**Comment by gongxuanzhang** [comment]
https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E6%97%A5%E6%9C%9F%E6%95%B0%E5%AD%97%E6%88%96%E8%80%85%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%BC%E5%BC%8F%E8%BD%AC%E6%8D%A2

**Comment by Rancho-7** [comment]
如果是BigDecimal类型的数据如何转为百分比？试了这个注解好像不生效

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
