### ISSUE TITLE
如何导出竖表，目前找到解决办法

### ISSUE THREAD

**Issue by myloveanddog** [alibaba/easyexcel#3387]
![Uploading image.png…]()

想要导出这样格式的数据，表头转换后，但是数据只能放在表头的下方，不能放在右侧，有什么实现办法吗？

**Comment by myloveanddog** [comment]
![image](https://github.com/alibaba/easyexcel/assets/49627669/bcee6ab0-07cc-4810-9d7c-c0ea469b6d7a)

**Comment by gongxuanzhang** [comment]
尝试用模板填充的方式

参考https://easyexcel.opensource.alibaba.com/docs/current/quickstart/fill#%E6%A8%AA%E5%90%91%E7%9A%84%E5%A1%AB%E5%85%85

**Comment by myloveanddog** [comment]
我的表头和数据都是动态的，模板有点不太合适，横向和纵向的数据都要支持导出，目前就是纵向数据，使用的头是             List<List<String>>格式， 数据是 List<List<Object>>格式，这种也可以用模板吗

**Comment by gongxuanzhang** [comment]
全动态的话直接自己把数据改成横向吧。。 感觉还更容易一点

**Comment by myloveanddog** [comment]
横向是可以实现的，需求要两种方式都实现，如果实现不了就只有砍掉纵向了

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
