### ISSUE TITLE
纵向填充遇到合并单元格，合并单元格会丢失数据，想问一下这个怎么解决

### ISSUE THREAD

**Issue by takeMeFlyToAir** [alibaba/easyexcel#3389]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
 代码就是普通的纵向填充代码
```
# 异常提示
无异常
# 问题描述
可以看到因为有合并单元格的情况，name2和name4丢失了，这个怎么解决呢
导出模版
![image](https://github.com/alibaba/easyexcel/assets/18323001/f9095fef-f85f-405f-806f-610494ff305c)
实际导出数据
![image](https://github.com/alibaba/easyexcel/assets/18323001/43255aed-5739-4aed-a2b1-a88182c5893a)

**Comment by gongxuanzhang** [comment]
关闭自动合并单元格的功能 
```java
EasyExcel.write(fileName).withTemplate(templateFileName).automaticMergeHead(false)
```

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
