### ISSUE TITLE
自动设置列宽

### ISSUE THREAD

**Issue by a464989624** [alibaba/easyexcel#339]
sheet1.setAutoWidth(true);  设置了这个没什么用，是还有哪里需要设置吗

**Comment by gendseo** [comment]
可能需要改变字体和大小

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。里面有个不完善的解决方案。如果您有更好的方案，可以根据上面的方案自定义拦截去处理。然后别忘记提一个PR，共享给大家。
