### ISSUE TITLE
处理20万数据进行数据导出分为32个sheet到一个文件里，本地代码跑起来好好的 一放生产环境就报Can not close IO

### ISSUE THREAD

**Issue by AeRocky** [alibaba/easyexcel#3391]
public static <T> void exportSheet(HttpServletResponse response, String fileName, List<String> sheetName, List<List<T>> list, Class<T> clazz) {
		response.setContentType("application/vnd.ms-excel");
		response.setCharacterEncoding(Charsets.UTF_8.name());
		ServletOutputStream outputStream = null;
		ExcelWriter excelWriter = null;
		try {
			fileName = URLEncoder.encode(fileName, Charsets.UTF_8.name());
			response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx");
			outputStream = response.getOutputStream();
			excelWriter = EasyExcel.write(outputStream, clazz).build();

			int i = 0;
			int k = 0;
			for (List<T> c : list) {
				WriteSheet writeSheet = EasyExcel.writerSheet(i++, sheetName.get(k++)).head(clazz).build();
				excelWriter.write(c, writeSheet);
			}
			excelWriter.finish();
			outputStream.flush();
		} catch (UnsupportedEncodingException e) {
			throw new RuntimeException(e);
		} catch (IOException e) {
			throw new RuntimeException(e);
		} finally {
			if (outputStream != null) {
				try {
					outputStream.close();
				} catch (IOException e) {
					throw new RuntimeException(e);
				}
			}
		}
	}
``

**Comment by Sean-214** [comment]
excelWriter.finish(); 调这个方法时输出流应该已经关闭了。

**Comment by AeRocky** [comment]
大佬那应该怎么解决呢 @Sean-214

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
