### ISSUE TITLE
模板导出如何添加公式并执行

### ISSUE THREAD

**Issue by zbw6384** [alibaba/easyexcel#3393]
导出文件模板的时候，如果给模板中添加公式，不同的模板，导出不同的计算公式如何实现，有没有文档代码可以查看。

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
