### ISSUE TITLE
如何处理有些固定列，然后再有些动态不固定列？

### ISSUE THREAD

**Issue by yfgcq** [alibaba/easyexcel#3394]
# 问题描述
如何处理有些固定列，然后再有些动态不固定列？
就是一对多的数据需要导出，多是不固定数据

**Comment by gongxuanzhang** [comment]
用拦截器的方式会很麻烦，建议把你的"一" 拆成多个属性列 重新建实体

**Comment by yfgcq** [comment]
> 用拦截器的方式会很麻烦，建议把你的"一" 拆成多个属性列 重新建实体

支持这种List方式不？
    Class ExcelData{
        @ExcelProperty("问题列表")
        private List<Question> questionList;

    }

    Class Question{
        @ExcelProperty("问题id")
        private String name;
        @ExcelProperty("问题名称")
        private String name;
    }

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
