### ISSUE TITLE
导入bean对象的时候,如果是string类型希望删除string类型首尾的空格

### ISSUE THREAD

**Issue by zkoalas** [alibaba/easyexcel#340]

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。

**Comment by BiYanzhao** [comment]
请问现在是默认会删除string类型首尾的空格吗，有没有可以保留空格的版本呢？
