### ISSUE TITLE
合并多个单元格

### ISSUE THREAD

**Issue by MovingBrick-er** [alibaba/easyexcel#3405]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   ![image](https://github.com/alibaba/easyexcel/assets/76142107/7bc2a920-a76a-4c0f-856b-e1baf01a3904)
```
# 异常提示
# 问题描述
我需要合并多个表头的第一个，并且这些单元格都不是连续的，用@OnceAbsoluteMerge注解貌似只能定义一个把？有没有什么办法设置多个列进行单元格合并

**Comment by aBlindBoy** [comment]
编码的方式，注册多个OnceAbsoluteMerge来处理

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
