### ISSUE TITLE
无法导入原始数据的问题

### ISSUE THREAD

**Issue by jiaoxrgit** [alibaba/easyexcel#3408]
# 问题描述
首先我的监听使用的是Map来接收数据，不是使用的实体类。
其次 excel里面的原始数据是153.1124，excel的单元格格式为数字 不保留小数 所以显示的是153
最后 在执行导入时候 通过debug看到 easy获取到的数据是153。
问题 如何能获取到153.1124数据。
已经在议题中找到类似解答 是要变为bigdecimal格式 。在转变为bigdecimal后仍然存在该问题。
求助在不改变接受对象的情况下如何解决该问题。

# excel数据
![微信截图_20230815094319](https://github.com/alibaba/easyexcel/assets/18240091/380f7b45-294b-4549-a221-287050e3c9f9)
# 代码
![code](https://github.com/alibaba/easyexcel/assets/18240091/9b93acf9-3420-498c-95d5-6ab3db82a666)

**Comment by AngusTripleH** [comment]
看起来excel保存的就不是小数，被格式化成整数了，原始数据能在excel展示小数吗

**Comment by jiaoxrgit** [comment]
> 看起来excel保存的就不是小数，被格式化成整数了，原始数据能在excel展示小数吗

excel保存的是小数，只是但单元格格式是整数。

**Comment by AngusTripleH** [comment]
原始数据用poi的读取吧，cell.getNumericCellValue()这个方法能读取到原始数据

**Comment by jiaoxrgit** [comment]
> 原始数据用poi的读取吧，cell.getNumericCellValue()这个方法能读取到原始数据


那easyexcel如何改造一下用poi读取呢。因为项目需要读大量数据 用easyexcel快一点。

**Comment by Sean-214** [comment]
文档：https://easyexcel.opensource.alibaba.com/docs/current/api/#readworkbook
ReadWorkbook的readDefaultReturn默认为STRING:会返回一个Map<Integer,String>的数组，返回值就是你在excel里面不点击单元格看到的内容，改成ACTUAL_DATA或READ_CELL_DATA试试
```
EasyExcel.read(...).readDefaultReturn(ReadDefaultReturnEnum.READ_CELL_DATA)
```

**Comment by jiaoxrgit** [comment]
> 文档：https://easyexcel.opensource.alibaba.com/docs/current/api/#readworkbook
> 
> ReadWorkbook的readDefaultReturn默认为STRING:会返回一个Map<Integer,String>的数组，返回值就是你在excel里面不点击单元格看到的内容，改成ACTUAL_DATA或READ_CELL_DATA试试
> 
> ```
> 
> EasyExcel.read(...).readDefaultReturn(ReadDefaultReturnEnum.READ_CELL_DATA)
> 
> ```

感谢大佬解惑，成功解决问题。
