### ISSUE TITLE
存在合并单元格的行，无法自适应行高

### ISSUE THREAD

**Issue by Ijiran** [alibaba/easyexcel#3412]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码

无法通过自适应行高，来给存在合并单元格的行进行自适应。

请问有什么解决方案吗？

# 异常提示

# 问题描述

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。

**Comment by swallow777** [comment]
解决了么？
