### ISSUE TITLE
锁定其他单元格，导出图片无法点开放大

### ISSUE THREAD

**Issue by JDay0318** [alibaba/easyexcel#3413]
public class CellHandler implements CellWriteHandler {

    private CellStyle cellStyle;

    @Override
    public int order() {
        return Integer.MAX_VALUE;
    }

    @Override
    public void beforeCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Row row, Head head, Integer columnIndex, Integer relativeRowIndex, Boolean isHead) {
        cellStyle = writeSheetHolder.getSheet().getWorkbook().createCellStyle();
        writeSheetHolder.getSheet().protectSheet("123456");
    }
}

    @Override
    public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, List<WriteCellData<?>> cellDataList, Cell cell, Head head, Integer relativeRowIndex, Boolean isHead)
    {
        if(cell.getColumnIndex()==1 || cell.getColumnIndex()==0){
            cellStyle.setLocked(true);
        }else{
            cellStyle.setLocked(false);
        }
}
**这样设置导出带图片的单元格时，图片无法点开**如下图所示
![image](https://github.com/alibaba/easyexcel/assets/129704164/62878eee-5800-44cc-9d81-08749df12067)

不锁定的话，图片是可以操作的，可以点开，如下
![image](https://github.com/alibaba/easyexcel/assets/129704164/577ffe5c-21cb-448b-8bda-ed2bc98d63eb)
有没有办法解决使用锁定图片无法点击的问题~

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
