### ISSUE TITLE
导出long类型数据精度缺失

### ISSUE THREAD

**Issue by on-create** [alibaba/easyexcel#3421]
# 异常代码
```java
public class ExportData {
    @NumberFormat(value = "#")
    private Long projectId;
    ...
}
```
# 异常提示
# 问题描述
预期导出结果：1689481454674870279
实际导出结果：1689481454674870000
版本：3.0.1

**Comment by Sean-214** [comment]
我是将 Long 类型以 String 导入到 Excel 解决的，`EasyExcel...registerConverter(new LongStringConverter())`。导入的时候会自动识别不需要配置。

**Comment by chehongwei-git** [comment]
excel  数字类型超过 15 位会丢失精度，可以转换为 String 导出

```java
@Data
public class ExportData {
    @ExcelProperty(converter = LongStringConverter.class)
    private Long projectId;
}

```
