### ISSUE TITLE
模型写入excel导出报错，ExcelBuilderImpl.addJavaObjectToExcel

### ISSUE THREAD

**Issue by seaguil** [alibaba/easyexcel#343]
![image](https://user-images.githubusercontent.com/38853650/57187487-32997600-6f22-11e9-9292-f6aec19721ee.png)
![image](https://user-images.githubusercontent.com/38853650/57187492-4513af80-6f22-11e9-96da-2e877ff2baf1.png)
list通过调试是有数据的，但是其中有数据有可能为null,下面是报错信息
![image](https://user-images.githubusercontent.com/38853650/57187505-7ab89880-6f22-11e9-978b-f5469eb474c6.png)

**Comment by Yee2** [comment]
哥们 你是怎么解决的 我也同样遇到这个问题。

**Comment by JimmyLincole** [comment]
> 哥们 你是怎么解决的 我也同样遇到这个问题。

@Yee2 
 
```java
// 模型上打有表头的注解，需要指定 model 的 class

// 或者
Sheet sheet2 = new Sheet(2, 3, WriteModel.class);

// 或者
sheet2.setClazz(WriteModel.class);

// 或者
Table table2 = new Table(2);
table2.setClazz(WriteModel.class);

```
