### ISSUE TITLE
Excel填充数据时，如何在所有数据都写入表格之后触发操作？

### ISSUE THREAD

**Issue by SGYQ** [alibaba/easyexcel#3433]
EasyExcel 3.2.0 版本，填充；
我想在所有数据都写入模板之后，进行某些操作，比如修改样式、加粗框线等，应该实现哪个接口？
之前是实现WorkbookWriteHandler，重写public void afterWorkbookDispose(WriteWorkbookHolder writeWorkbookHolder)方法，但是效果不行

**Comment by VinaChiong** [comment]
> 

试试设置 builder.inMemory(true)
估计是因为默认用了 SXSSF API 的 SXSSFWorkbook，有个 DEFAULT_WINDOW_SIZE，默认值是100。

**Comment by SGYQ** [comment]
@Override
public void afterWorkbookDispose(WriteWorkbookHolder writeWorkbookHolder) {
    Workbook workbook = writeWorkbookHolder.getWorkbook();
    Sheet sheet = workbook.getSheetAt(0);
    CellStyle cellStyle = workbook.createCellStyle();
    cellStyle.setBorderBottom(BorderStyle.THICK);

    Integer lastRowIndex = rowIndexList.get(rowIndexList.size() - 1);
    Row row = sheet.getRow(lastRowIndex);
    for (int i = firstColumnIndex; i < lastColumnIndex; i++) {
        Cell cell = row.getCell(i);
        cell.setCellStyle(cellStyle);
    }
}
发现获取的Row是空的 ，null
