### ISSUE TITLE
合并单元格时导出后, excel内合计数值不对, 不是真的合并单元格, 怎么解决

### ISSUE THREAD

**Issue by wqf0305** [alibaba/easyexcel#3437]
如图
![image](https://github.com/alibaba/easyexcel/assets/56428076/f7d43ced-b27e-4ea3-b9f1-c03a5f3f2a1e)

**Comment by zhangguixing** [comment]
我尝试重写 WorkbookWriteHandler的afterWorkbookDispose(WriteWorkbookHolder writeWorkbookHolder)进行解决，但是结果并没有达到预期

从sheet中可以获取数据行数只拿到了最后100行数据，我的总行数为120行，前20行数据未能处理，代码如下

   @Override
    public void afterWorkbookDispose(WriteWorkbookHolder writeWorkbookHolder) {
        Iterator<Sheet> sheetIterator = writeWorkbookHolder.getWorkbook().sheetIterator();
        while (sheetIterator.hasNext()) {
            Sheet sheet = sheetIterator.next();
            List<CellRangeAddress> mergedRegions = sheet.getMergedRegions();
            if (CollectionUtils.isEmpty(mergedRegions)) {
                continue;
            }
            for (CellRangeAddress mergedRegion : mergedRegions) {
                for (int ri = mergedRegion.getFirstRow(); ri <= mergedRegion.getLastRow(); ri++) {
                    Row row = sheet.getRow(ri);
                    for (int ci = mergedRegion.getFirstColumn(); ci <= mergedRegion.getLastColumn(); ci++) {
                        // 保留左上角单元格值
                        if (ri == mergedRegion.getFirstRow() && ci == mergedRegion.getFirstColumn()) {
                            continue;
                        }
                        row.getCell(ci).setCellValue((String) null);
                    }
                }
            }
        }
    }

求解答

**Comment by zhangguixing** [comment]
查看源码中有段逻辑 

 ```
if(_randomAccessWindowSize >= 0 && _rows.size() > _randomAccessWindowSize) {
      try {
          flushRows(_randomAccessWindowSize);
      } catch (IOException ioe) {
          throw new RuntimeException(ioe);
      }
  }
```

其中_randomAccessWindowSize默认值为100，前20行会被flush到磁盘

由于场景数据量少我通过SXSSFSheet#setRandomAccessWindowSize方法重新设定了长度，暂时解决了问题

```
public class ExcelSheetWriteHandler implements SheetWriteHandler {

    @Override
    public void afterSheetCreate(WriteWorkbookHolder writeWorkbookHolder, WriteSheetHolder writeSheetHolder) {
        // 解除只可访问100行限制 所有数据不刷盘，都可访问
        ((SXSSFSheet) writeSheetHolder.getSheet()).setRandomAccessWindowSize(-1);
    }
}
```

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
