### ISSUE TITLE
模板导出时如何删除模板行

### ISSUE THREAD

**Issue by zhang-jie8** [alibaba/easyexcel#3443]
ExcelWriter excelWriter = EasyExcel.write(response.getOutputStream()). withTemplate(templateFileName).build()) 
excelWriter 和writeSheet似乎无法修改excel内的数据，如何获取excel的sheet修改模板

**Comment by gongxuanzhang** [comment]
模板被视为是静态文件，不应该被修改，如果模板不支持你的需求应该重建。
我猜测你这个可能是个XY问题，请提供原始需求

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
