### ISSUE TITLE
Can not find 'Converter' support class Date

### ISSUE THREAD

**Issue by Kriszttttt** [alibaba/easyexcel#3449]
使用原生jdbc查询SQL，并导出结果成excle，sql中有个字段在数据库中是date类型，代码报错Can not find 'Converter' support class Date，使用register注册了TimestampConverter，可以正常转换数据库dateTime类型，但是date类型不行，该怎么解决这个问题
<img width="828" alt="image" src="https://github.com/alibaba/easyexcel/assets/114504439/338ec870-c50f-4a63-9c4b-c57b72176034">

    private void exportToExcel2(List<List<String>> head, List<List<Object>> data, HttpServletResponse servletResponse) {
        try {
            // 注册 Timestamp 类型的转换器
            EasyExcel.write(getOutputStream("1", servletResponse))
                    .registerConverter(new TimestampConverter()) // 注册自定义转换器
                    .registerWriteHandler(new CustomCellWriteWeightConfig())
                    .registerWriteHandler(new CustomCellWriteHeightConfig())
                    .registerWriteHandler(setExcelStyle())
                    .sheet()
                    .head(head)
                    .doWrite(data);
        } catch (Exception e) {
            log.error("", e);
        }
    }

    
    public class TimestampConverter implements Converter<Timestamp>{

	@Override
    public Class<Timestamp> supportJavaTypeKey() {
        return Timestamp.class;
    }

    @Override
    public CellDataTypeEnum supportExcelTypeKey() {
        return CellDataTypeEnum.STRING;
    }

	@Override
	public WriteCellData<String> convertToExcelData(Timestamp timestamp, ExcelContentProperty contentProperty,
			GlobalConfiguration globalConfiguration) throws Exception {
		return new WriteCellData<String>(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(timestamp));
	}
}

**Comment by likepepper** [comment]
怎么解决的

**Comment by mazhewei** [comment]
3.3.4版本遇到了同样的问题，经过排查后发现是Date类不匹配导致的，留个备注供参考。
我本地使用的是达梦数据库，数据库字段设置为Date(13)。
核心点在于，达梦数据库驱动返回的java类型为`java.sql.Date`而不是`java.util.Date`，而easyexcel自带的转换器仅支持的是`java.util.Date`的，故会报错误：`Can not find 'Converter' support class Date`。

自行添加自定义转换器：（用的hutool转换，可以自己换成其他工具类）
```java
import cn.hutool.core.date.DatePattern;
import cn.hutool.core.date.DateUtil;
import com.alibaba.excel.converters.Converter;
import com.alibaba.excel.enums.CellDataTypeEnum;
import com.alibaba.excel.metadata.GlobalConfiguration;
import com.alibaba.excel.metadata.data.ReadCellData;
import com.alibaba.excel.metadata.data.WriteCellData;
import com.alibaba.excel.metadata.property.ExcelContentProperty;

import java.sql.Date;

public class SQLDateConverter implements Converter<Date> {
    @Override
    public Class<?> supportJavaTypeKey() {
        return Date.class;
    }

    @Override
    public CellDataTypeEnum supportExcelTypeKey() {
        return CellDataTypeEnum.STRING;
    }

    @Override
    public WriteCellData<?> convertToExcelData(Date value, ExcelContentProperty contentProperty,
                                               GlobalConfiguration globalConfiguration) {
        return new WriteCellData<>(
                DateUtil.format(new java.util.Date(value.getTime()), DatePattern.NORM_DATE_FORMATTER)
        );
    }

    @Override
    public Date convertToJavaData(ReadCellData<?> cellData, ExcelContentProperty contentProperty, GlobalConfiguration globalConfiguration) {
        return Date.valueOf(cellData.getStringValue());
    }
}
```

另外，达梦数据库的timestamp类型也是特殊的，也需要自行添加转换器：
```java
import cn.hutool.core.date.DatePattern;
import cn.hutool.core.date.LocalDateTimeUtil;
import com.alibaba.excel.converters.Converter;
import com.alibaba.excel.enums.CellDataTypeEnum;
import com.alibaba.excel.metadata.GlobalConfiguration;
import com.alibaba.excel.metadata.data.ReadCellData;
import com.alibaba.excel.metadata.data.WriteCellData;
import com.alibaba.excel.metadata.property.ExcelContentProperty;
import dm.jdbc.driver.DmdbTimestamp;

public class DmdbTimestampConverter implements Converter<DmdbTimestamp> {
    @Override
    public Class<?> supportJavaTypeKey() {
        return DmdbTimestamp.class;
    }

    @Override
    public CellDataTypeEnum supportExcelTypeKey() {
        return CellDataTypeEnum.STRING;
    }

    @Override
    public WriteCellData<?> convertToExcelData(DmdbTimestamp value, ExcelContentProperty contentProperty,
                                               GlobalConfiguration globalConfiguration) {
        return new WriteCellData<>(
                LocalDateTimeUtil.format(value.toLocalDateTime(), DatePattern.NORM_DATETIME_FORMATTER)
        );
    }

    @Override
    public DmdbTimestamp convertToJavaData(ReadCellData<?> cellData, ExcelContentProperty contentProperty, GlobalConfiguration globalConfiguration) {
        return DmdbTimestamp.valueOf(cellData.getStringValue());
    }
}
```

使用下面的代码注册自定义转换器：
```java
ExcelWriterBuilder excelWriterBuilder = EasyExcel.write(outputStream);
// 注册自定义转换器
excelWriterBuilder.registerConverter(new DmdbTimestampConverter());
excelWriterBuilder.registerConverter(new SQLDateConverter());
```

**Comment by RubyXun** [comment]
> 3.3.4版本遇到了同样的问题，经过排查后发现是Date类不匹配导致的，留个备注供参考。 我本地使用的是达梦数据库，数据库字段设置为Date(13)。 核心点在于，达梦数据库驱动返回的java类型为`java.sql.Date`而不是`java.util.Date`，而easyexcel自带的转换器仅支持的是`java.util.Date`的，故会报错误：`Can not find 'Converter' support class Date`。
> 
> 自行添加自定义转换器：（用的hutool转换，可以自己换成其他工具类）
> 
> import cn.hutool.core.date.DatePattern;
> import cn.hutool.core.date.DateUtil;
> import com.alibaba.excel.converters.Converter;
> import com.alibaba.excel.enums.CellDataTypeEnum;
> import com.alibaba.excel.metadata.GlobalConfiguration;
> import com.alibaba.excel.metadata.data.ReadCellData;
> import com.alibaba.excel.metadata.data.WriteCellData;
> import com.alibaba.excel.metadata.property.ExcelContentProperty;
> 
> import java.sql.Date;
> 
> public class SQLDateConverter implements Converter<Date> {
>     @Override
>     public Class<?> supportJavaTypeKey() {
>         return Date.class;
>     }
> 
>     @Override
>     public CellDataTypeEnum supportExcelTypeKey() {
>         return CellDataTypeEnum.STRING;
>     }
> 
>     @Override
>     public WriteCellData<?> convertToExcelData(Date value, ExcelContentProperty contentProperty,
>                                                GlobalConfiguration globalConfiguration) {
>         return new WriteCellData<>(
>                 DateUtil.format(new java.util.Date(value.getTime()), DatePattern.NORM_DATE_FORMATTER)
>         );
>     }
> 
>     @Override
>     public Date convertToJavaData(ReadCellData<?> cellData, ExcelContentProperty contentProperty, GlobalConfiguration globalConfiguration) {
>         return Date.valueOf(cellData.getStringValue());
>     }
> }
> 另外，达梦数据库的timestamp类型也是特殊的，也需要自行添加转换器：
> 
> import cn.hutool.core.date.DatePattern;
> import cn.hutool.core.date.LocalDateTimeUtil;
> import com.alibaba.excel.converters.Converter;
> import com.alibaba.excel.enums.CellDataTypeEnum;
> import com.alibaba.excel.metadata.GlobalConfiguration;
> import com.alibaba.excel.metadata.data.ReadCellData;
> import com.alibaba.excel.metadata.data.WriteCellData;
> import com.alibaba.excel.metadata.property.ExcelContentProperty;
> import dm.jdbc.driver.DmdbTimestamp;
> 
> public class DmdbTimestampConverter implements Converter<DmdbTimestamp> {
>     @Override
>     public Class<?> supportJavaTypeKey() {
>         return DmdbTimestamp.class;
>     }
> 
>     @Override
>     public CellDataTypeEnum supportExcelTypeKey() {
>         return CellDataTypeEnum.STRING;
>     }
> 
>     @Override
>     public WriteCellData<?> convertToExcelData(DmdbTimestamp value, ExcelContentProperty contentProperty,
>                                                GlobalConfiguration globalConfiguration) {
>         return new WriteCellData<>(
>                 LocalDateTimeUtil.format(value.toLocalDateTime(), DatePattern.NORM_DATETIME_FORMATTER)
>         );
>     }
> 
>     @Override
>     public DmdbTimestamp convertToJavaData(ReadCellData<?> cellData, ExcelContentProperty contentProperty, GlobalConfiguration globalConfiguration) {
>         return DmdbTimestamp.valueOf(cellData.getStringValue());
>     }
> }
> 使用下面的代码注册自定义转换器：
> 
> ExcelWriterBuilder excelWriterBuilder = EasyExcel.write(outputStream);
> // 注册自定义转换器
> excelWriterBuilder.registerConverter(new DmdbTimestampConverter());
> excelWriterBuilder.registerConverter(new SQLDateConverter());

特此感谢 SQLDateConverter 解决了我的问题
