### ISSUE TITLE
是不是停止维护了，最近的提交都是去年12月份了？

### ISSUE THREAD

**Issue by jeesun** [alibaba/easyexcel#345]
？？

**Comment by Ryoui** [comment]
同问，issues里这么多问题，好像没解决

**Comment by snaigle** [comment]
是不是维护人离职了？阿里的好多项目都是这样突然就没人管了

**Comment by Wilson-He** [comment]
同问

**Comment by ZhenxingXiao** [comment]
有把它部署到生产环境的吗？要是不维护了不敢用啊

**Comment by Walkinwindy** [comment]
我暂时还没用过，具体情况不清楚，不过我的生产环境用的是easypoi。




------------------ 原始邮件 ------------------
发件人: "Albert Xiao"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 上午10:27
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 是不是停止维护了，最近的提交都是去年12月份了？ (#345)




有把它部署到生产环境的吗？要是不维护了不敢用啊

**Comment by ZhenxingXiao** [comment]
> 我暂时还没用过，具体情况不清楚，不过我的生产环境用的是easypoi。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Albert Xiao"<notifications@github.com>; 发送时间: 2019年5月20日(星期一) 上午10:27 收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [alibaba/easyexcel] 是不是停止维护了，最近的提交都是去年12月份了？ (#345) 有把它部署到生产环境的吗？要是不维护了不敢用啊 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

感谢告知，我在测试环境测试(不完全为了测试这个)一周多了，目前很稳定

**Comment by zhuangjiaju** [comment]
重新活了
