### ISSUE TITLE
关于easyExcel，如何导出分组。

### ISSUE THREAD

**Issue by FDsecurity123** [alibaba/easyexcel#3452]
复现效果
excel- 选择一行 - 数据 - 创建租
通过这个步骤，就可以在不同excel中实现。目前easyexcel中没有相关dome和api

![f0c86d4a64616be57be61cb9e25fb8e](https://github.com/alibaba/easyexcel/assets/135003385/3ff86125-b255-4b7e-931d-55e2eca73641)
这个是我要达到的效果，从图片中可以看到，左边的+ - 按钮就是excel的分组功能。
我查阅资料直到需要使用poi库，但具体解决方案不清晰。我自己尝试编辑了代码，使用了相对应的hander拦截器。可以分组，但是效果不理想，并且不确定是否兼容easyexcel。烦请帮助解答。

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
