### ISSUE TITLE
我们项目好几个导出表格的数据封装在同一个实体类中，表头不确定

### ISSUE THREAD

**Issue by qinsiyuan123** [alibaba/easyexcel#3459]
我们项目好几个导出表格的数据封装在同一个实体类中，表头不确定。
比如我表一需要用到实体类里的1,2,3属性三个做表头和填充
表二需要2,3,4,三个属性做表头和数据，这样没法确定表头，用注解也没法解决
除了新建实体类外有什么解决办法吗

**Comment by changhai-weinan** [comment]
动态生成表头（也可以是复杂表头）和数据，参考官网：
https://easyexcel.opensource.alibaba.com/docs/2.x/quickstart/write#%E5%8A%A8%E6%80%81%E5%A4%B4%E5%AE%9E%E6%97%B6%E7%94%9F%E6%88%90%E5%A4%B4%E5%86%99%E5%85%A5

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
