### ISSUE TITLE
导出时间不稳定问题

### ISSUE THREAD

**Issue by hyllovedf** [alibaba/easyexcel#3462]
# 异常代码
```java
   ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
   EasyExcel.write(byteArrayOutputStream, Head.class).sheet().doWrite(downloadData);
```
# 问题描述
一个简单的导出功能, 表头只有四个字段, 600多条数据，导出后文件大小22kb， 项目重启后第一次导出的时候耗时较长(4-5s) 后面继续导出就只有几百毫秒。（这里统计的是查出数据后，纯导出时间）
等过一段时间再次导出（具体过了多长时间没有统计出来，过了一晚肯定会慢），首次还是比较慢。首次较慢的问题项目
重启后是必现。
![image](https://github.com/alibaba/easyexcel/assets/49096277/319176c7-eeed-4774-82e8-8dda3fb1c9c6)

**Comment by gongxuanzhang** [comment]
第一次导出是有初始化的过程的，
"过了一晚"这个可能是操作系统缓存页的优化

**Comment by hyllovedf** [comment]
> 第一次导出是有初始化的过程的， "过了一晚"这个可能是操作系统缓存页的优化

有没有办法先去初始化一下呢  防止首次导出的时候耗时长

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
