### ISSUE TITLE
Create workbook failure”.Caused by: org.xml.sax.SAXNotSupportedException: not supported setting property http://xml.org/sax/properties/lexical-handler

### ISSUE THREAD

**Issue by jsonyangqq** [alibaba/easyexcel#3467]
使用easyexcel做文件导出时出现“Create workbook failure” Caused by: org.xml.sax.SAXNotSupportedException: not supported setting property http://xml.org/sax/properties/lexical-handler	
easyexcel版本：implementation("com.alibaba:easyexcel:3.0.5")

**Comment by jsonyangqq** [comment]
Solution：
export to add the following code below.
```
System.setProperty("javax.xml.parsers.SAXParserFactory", "org.apache.xerces.jaxp.SAXParserFactoryImpl");
System.setProperty("javax.xml.parsers.SAXParserFactory", "com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl");
```

**Comment by youlingdada** [comment]
请给出可供复现的代码和数据

**Comment by youlingdada** [comment]
请给出可供复现的代码和必要的数据

**Comment by DaZuiZui** [comment]
Hello, please provide me the key code
I wish you a happy life and smooth work

**Comment by youlingdada** [comment]
I'm not sure if you have resolved the issue? We will temporarily close this issue. If there are still issues, please reopen this issue
