### ISSUE TITLE
是否考虑将poi相关包升级到5.2.3+版本

### ISSUE THREAD

**Issue by rimwoorim** [alibaba/easyexcel#3471]
大佬, 您好!

请问 : 是否考虑将poi相关包升级到5.2.3+版本

以解决 : 在docker容器中, 采用openjdk时会找不到字体的错误

附录 : 
poi的版本更新日志 : https://poi.apache.org/changes.html

![image](https://github.com/alibaba/easyexcel/assets/8778939/eb0e7dd2-a0a4-4093-9fe9-799ef495feef)

**Comment by youlingdada** [comment]
https://easyexcel.opensource.alibaba.com/qa/#%E6%88%91%E5%9C%A8%E6%9C%AC%E5%9C%B0%E5%8F%AF%E4%BB%A5%E5%8F%91%E5%B8%83%E5%88%B0%E7%BA%BF%E4%B8%8A%E7%8E%AF%E5%A2%83%E6%80%8E%E4%B9%88%E4%B8%8D%E5%8F%AF%E4%BB%A5%E4%BA%86 看看这个能解决吗

**Comment by rimwoorim** [comment]
容器中安装字体确实可以解决, 之前我们也是这么处理的

但运维不大想这么做, 原因是 : 这样每次构建镜像时体积更大, 上传镜像仓库耗费的时间更多

所以我才去重新看看有没有别的能处理这个字体的问题方式

然后就恰好看到poi官方解决了这个问题

遂, 提出这个建议

**Comment by youlingdada** [comment]
好的，这个后面在后面版本会升级的

**Comment by luojianjun** [comment]
现在如果把poi 升到5.2.3 解析excel 会抛出异常

**Comment by rimwoorim** [comment]
1. 我这边有下easyexcel的项目, 试着自己调整, 确实有报错的, 确实不能直接升级
2. 我只用于导出, 调整了包版本目前是可以正常是使用的, 也没有字体的那个报错
3. 至于要不要升级, 大佬您做决定, 我就是发现了这个东西, 提出这个建议

**Comment by psxjoy** [comment]
Hi, we have an update to poi-5！
This issue has been completed, I will close this issue.
