### ISSUE TITLE
根据模板导出文件时，如果模板本身包含图片，导出的文件图片为空白

### ISSUE THREAD

**Issue by wweihd** [alibaba/easyexcel#3475]

**Comment by lalala1024** [comment]
老哥你解决了吗

**Comment by wweihd** [comment]
解决了 ---- 回复的原邮件 ***@***.***>发送日期2023年12月16日 20:21 ***@***.***> 抄送人wei ***@***.***>,State ***@***.***>主题Re: [alibaba/easyexcel] 根据模板导出文件时，如果模板本身包含图片，导出的文件图片为空白 (Issue #3475)
老哥你解决了吗

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/alibaba/easyexcel/issues/3475#issuecomment-1858805681",
"url": "https://github.com/alibaba/easyexcel/issues/3475#issuecomment-1858805681",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wweihd** [comment]
有一个设置项，开启内存模式可以正常导出模版中的图片 ---- 回复的原邮件 ***@***.***>发送日期2023年12月16日 20:21 ***@***.***> 抄送人wei ***@***.***>,State ***@***.***>主题Re: [alibaba/easyexcel] 根据模板导出文件时，如果模板本身包含图片，导出的文件图片为空白 (Issue #3475)
老哥你解决了吗

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/alibaba/easyexcel/issues/3475#issuecomment-1858805681",
"url": "https://github.com/alibaba/easyexcel/issues/3475#issuecomment-1858805681",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wweihd** [comment]
但如果文件太大会有内存溢出风险 ---- 回复的原邮件 ***@***.***>发送日期2023年12月16日 20:21 ***@***.***> 抄送人wei ***@***.***>,State ***@***.***>主题Re: [alibaba/easyexcel] 根据模板导出文件时，如果模板本身包含图片，导出的文件图片为空白 (Issue #3475)
老哥你解决了吗

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/alibaba/easyexcel/issues/3475#issuecomment-1858805681",
"url": "https://github.com/alibaba/easyexcel/issues/3475#issuecomment-1858805681",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
