### ISSUE TITLE
如何用Easyexcel或POI接口，「写入指定单元格」或「删除特定行」？

### ISSUE THREAD

**Issue by uncarbon97** [alibaba/easyexcel#3476]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
// 没有异常
```
# 异常提示
没有异常
# 问题描述
![github-issue](https://github.com/alibaba/easyexcel/assets/75737767/7f57556e-eb12-43bf-b79d-c3520db9a129)

由于模板向下输出的行数不确定（但可以知道到哪一行止），所以有2种思路：

1. 置特定行、特定列文本；但通过官网右上角的「写入指定单元格」等关键词未找到方法
2. 蓝框内使用模板替换，然后删除红蓝框中多余的行；但通过官网右上角的「删除」等关键词未找到方法

**Comment by tmlx1990** [comment]
> # 建议先去看文档
> [快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
> 
> # 异常代码
> ```java
> // 没有异常
> ```
> 
> # 异常提示
> 没有异常
> 
> # 问题描述
> ![github-issue](https://user-images.githubusercontent.com/75737767/269891721-7f57556e-eb12-43bf-b79d-c3520db9a129.png)
> 
> 由于模板向下输出的行数不确定（但可以知道到哪一行止），所以有2种思路：
> 
> 1. 置特定行、特定列文本；但通过官网右上角的「写入指定单元格」等关键词未找到方法
> 2. 蓝框内使用模板替换，然后删除红蓝框中多余的行；但通过官网右上角的「删除」等关键词未找到方法

您好，直接在填充后边固定模板就可以了。
程序会自动根据数据增加行的。
<img width="343" alt="image" src="https://github.com/alibaba/easyexcel/assets/5753992/422c0bae-142d-4619-a31b-9e1488d0c53b">
<img width="455" alt="image" src="https://github.com/alibaba/easyexcel/assets/5753992/106a34c4-94a7-434c-b524-5f4fbe9133d3">
<img width="762" alt="image" src="https://github.com/alibaba/easyexcel/assets/5753992/42d92958-5558-45f0-8b12-cac020cc75b4">

**Comment by uncarbon97** [comment]
谢谢！仔细看了一下 原来要点在于「forceNewRow」
试验了一下已经近似达成了需要的效果
