### ISSUE TITLE
官网上的重复写入 是追加写的意思吗?

### ISSUE THREAD

**Issue by ChenYilei2016** [alibaba/easyexcel#3477]
我看github里有一个 issue里有说 easyexcel 不支持追加写 : https://github.com/alibaba/easyexcel/issues/2892

但官网的文档里有一个重复写入 https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#%E9%87%8D%E5%A4%8D%E5%A4%9A%E6%AC%A1%E5%86%99%E5%85%A5%E5%86%99%E5%88%B0%E5%8D%95%E4%B8%AA%E6%88%96%E8%80%85%E5%A4%9A%E4%B8%AAsheet

看起来像是追加写的功能, 想问下 这个重复写入的话 是不是不会读取整个excel的内容 , 会占用较少的内存呢. .

**Comment by ChenYilei2016** [comment]
又发现一个类似的提问  https://github.com/alibaba/easyexcel/issues/3422 , 请求解答下疑惑

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
