### ISSUE TITLE
对于单个枚举的处理可以通过自定义的转换器 如何全局处理？

### ISSUE THREAD

**Issue by kang91226** [alibaba/easyexcel#3480]
对于单个枚举的处理可以通过自定义的转换器 
但是对于有很多都是枚举类型都需要做转换，不想通过注解的方式，有没有办法能够处理所有的枚举类型？所有的枚举都是一样取name属性

**Comment by Crazy-x** [comment]
目前，全局注册和，注册处理器都不支持，我也在等，，，等哪个大佬来个PR

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。

**Comment by Farley-Chen** [comment]
我认为可以使用registerConverter方法进行注册转换器，然后进行简单点封装

案例如下

```java
EasyExcel.write(response.getOutputStream())
            .charset(StandardCharsets.UTF_8)
            .head(WorkOrderDto.class)
            .registerConverter(new LocalDateTimeConverter())
            .sheet()
            .doWrite(dtos);
```
