### ISSUE TITLE
easyexcel的注解，能否用于web api？

### ISSUE THREAD

**Issue by MuChenMuXuan** [alibaba/easyexcel#3482]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)

# 问题描述
对于内部系统，同一个功能，需要后端返回json类型的数据`List<Object>`，同时呢，又需要后端提供excel导出功能。
api和excel导出，都需要对字段进行格式化，如日期格式化、小数点保留n位......，那么，easyexcel中提供的注解，能否运用到web api中？
easyexcel中是否有api，参数是List<Object>，输出是经过注解格式化后的List数据。

这个问题困扰很久，未找到答案，不胜感谢！

**Comment by youlingdada** [comment]
easyapi的注解是自己写的，不是javax规范，未用在其他web框架中使用，无法实现类似的web中的序列化数据的功能
