### ISSUE TITLE
作者设计的逻辑是尽量简单，所以抛弃了poi，那一堆类型 ，统一自动转换。目前没法获取cell的类型

### ISSUE THREAD

**Issue by xietuke** [alibaba/easyexcel#349]
excel 数据日期格式如：2018-11-11 无model模式读取为11/11/18 这种格式，请问怎么解决？

**Comment by fish7790714** [comment]
联系到作者了 内部版本已经解决了。后续等更新吧

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
