### ISSUE TITLE
如何分页读取Excel文件呢？

### ISSUE THREAD

**Issue by geekerstar** [alibaba/easyexcel#3490]
# 问题描述
使用文档中的不创建对象的读，读取一个大的Excel文件，实现类似分页列表一样的分页读取，比如先读取前100行数据，再次请求则读取下100行数据。

**Comment by geekerstar** [comment]
可以通过抛出异常实现：throw new ExcelAnalysisStopException();

**Comment by Alexxiaochen** [comment]
您好，我是刚接触easyexcel，也遇到了和您相似的问题，请问您这里提出的通过抛出异常来实现分页读取的具体细节是什么呢？
