### ISSUE TITLE
映射类中存在list类型或者包含其他类时如何使用注解

### ISSUE THREAD

**Issue by 0wenwu** [alibaba/easyexcel#350]
映射类中存在list类型或者包含其他类时如何使用注解？
```
public class LoanInfo extends BaseRowModel {
    @ExcelProperty(index = 0)
    private List<String> list;
    
    @ExcelProperty(index = 1)
    private TimeBean tb; //其中TimeBean为自定义类
}
```

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。然后自定义转换器即可
