### ISSUE TITLE
填充Excel匯出, 有方法可以1筆資料兩(多)行輸出

### ISSUE THREAD

**Issue by tatalo** [alibaba/easyexcel#3509]
如果使用 excelWriter.fill(new FillWrapper("a", [object]), writeSheet) 方式, 
可否在 excel 中, 多行資料算1筆輸出?

ex: 以下資料為   [{A, A1},{B,B2},{C,C3}}..這樣
EXCEL第1行:   A
EXCEL第2行:   A1
EXCEL第3行:   B
EXCEL第4行:   B2
EXCEL第5行:   C
EXCEL第6行:   C3

**Comment by beangou** [comment]
同样的需求

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
