### ISSUE TITLE
请问文档中提到 3m 的2007excel文档 sax解析只要kb级的内存是怎么做到的

### ISSUE THREAD

**Issue by snaigle** [alibaba/easyexcel#351]

**Comment by snaigle** [comment]
我使用 EasyExcelFactory.readBySax 读取 180m的xlsx文档，还是需要将近6g的jvm内存，否则加载不成功

**Comment by ksharpy** [comment]
183M占用内存4.5G

**Comment by zhuangjiaju** [comment]
> 183M占用内存4.5G

大概多少条数据呀

**Comment by ksharpy** [comment]
3500W条，找了一个别人优化的ExcelUtil包,现在数据量翻倍的情况，内存控制到4G

**Comment by gaochuanneu** [comment]
> 
> 
> 3500W条，找了一个别人优化的ExcelUtil包,现在数据量翻倍的情况，内存控制到4G
大哥,代码共享一下呗

**Comment by zhuangjiaju** [comment]
> 3500W条，找了一个别人优化的ExcelUtil包,现在数据量翻倍的情况，内存控制到4G

作者在重写 1-2个月 183M 争取1G内

**Comment by ksharpy** [comment]
http://5589csxz.wicp.top:10028/?id=9606945&key=522748578927626241

**Comment by ksharpy** [comment]
用上面链接别人的工具包改了一下，把这个ExcelUtil引入，然后在Xlsx2ListData类加入一个变量maxCol，覆盖原本的endRow方法，解决最后一列部分字段为空的问题
public void endRow(int rowNum) {
// Ensure the minimum number of columns
for (int i = currentCol; i < minColumns - 1; i++) {
currRowData.add(defaultValue);
}
if (rowNum == 0) {
maxCol = currRowData.size() > 0 ? currRowData.size() - 1 : 0;
}
for (int i = currentCol; i < maxCol; i++) {
currRowData.add(defaultValue);
}
processRowData(currRowData);
}

**Comment by tblueprint** [comment]
文档提到poi sax模式占用较多。看了代码作者用的还是poi sax。重写在哪块，想取取经

**Comment by lgx211** [comment]
比如加载进来的时候，字体样式等不重要的数据被丢弃了




------------------ 原始邮件 ------------------
发件人: "liyao"<notifications@github.com>; 
发送时间: 2019年7月16日(星期二) 上午9:27
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [alibaba/easyexcel] 请问文档中提到 3m 的2007excel文档 sax解析只要kb级的内存是怎么做到的 (#351)




文档提到poi sax模式占用较多。看了代码作者用的还是poi sax。重写在哪块，想取取经
 
&mdash;

**Comment by tblueprint** [comment]
感谢楼上的回答，已经找到了。poi sax默认实现是XSSFSheetXMLHandler。作者重写了Handler，丢弃了不重要的字体样式等数据。

**Comment by zhuangjiaju** [comment]
新版本已经出了，180M应该是 500M内存就够了，请更新版本
