### ISSUE TITLE
复杂表头如何调整每一行的行高

### ISSUE THREAD

**Issue by wzh530502204** [alibaba/easyexcel#3517]
![1698117193999](https://github.com/alibaba/easyexcel/assets/46470304/30051bcd-6cf3-4bd5-b8e9-f5efcb5ff78d)
如图，列表的表头是行1 、行2、 行3共三行组成的，它们分别需要设置不同的行高 ，请问需要怎么设置，十分感谢！

**Comment by wzh530502204** [comment]
![height](https://github.com/alibaba/easyexcel/assets/46470304/52809860-0162-4248-b78a-08258dd084cb)
重发图片

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
