### ISSUE TITLE
 @ExcelProperty("列名")无法读取数据

### ISSUE THREAD

**Issue by Supers1st** [alibaba/easyexcel#3519]
# 问题描述
在使用3.2.1进行数据读取时，有的类通@ExcelProperty("列名")的方式无法获取结果，有的类却可以，很抽象的一个问题
使用过程也并没有报错，无法读取的通过指定下标的方式也能正确读取值
# 实体以及读取结果如下图
![结果](https://github.com/alibaba/easyexcel/assets/53671131/820ba277-1c79-48b8-b02e-4c1a719099d0)
![无法获取实体类](https://github.com/alibaba/easyexcel/assets/53671131/b12d9071-2985-4c43-b295-d06a4c6134c4)
![正常获取](https://github.com/alibaba/easyexcel/assets/53671131/4d3af2c0-1133-4eb5-9df7-831153d1a6df)
![正常获取结果](https://github.com/alibaba/easyexcel/assets/53671131/f9e5249a-1d0e-4991-a9ec-482993574108)

**Comment by lepark2** [comment]
我也遇到过读出来全为null的情况，后来发现是按列名匹配时不完全正确，你可以尝试debug看下他读出来的列名是否与你的注解列名完全匹配，我之前的遇到的问题是包含换行符，然而有的是\n 有的是\r\n 导致匹配时不一致
框架默认用的equals匹配
建议作者可以增加自定义列名匹配方式

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
