### ISSUE TITLE
任意大的文件如何读取成功的？

### ISSUE THREAD

**Issue by csz** [alibaba/easyexcel#352]
![image](https://user-images.githubusercontent.com/469794/57428350-82e24200-725a-11e9-9350-6c68a51b35af.png)
这个open方法使用inputstream有限制，最终调用的poi-ooxml jar中的FakeZipEntry类有文件大小限制，300多M以上的无法加载，
![image](https://user-images.githubusercontent.com/469794/57428465-1ae02b80-725b-11e9-893c-3075b58f72a8.png)
请问，任意大的excel文件是怎么读取的？谢谢

**Comment by fish7790714** [comment]
您可以参照下test案例，easyexcel读取没有调用poi，不应该会有这个限制

**Comment by ksharpy** [comment]
请问这个问题解决了吗？我有一个300M的EXCEL无法读取

**Comment by lgx211** [comment]
厉害啊，300M。我一个1048576行 * 10列的excel，31M左右，这都可以放一百多万行的数据了啊（行数都达到了单个sheet的峰值了），你那300M的数据，是自己人工填的，这得1000万行左右的数据，平台导出的，这么大的excel导出都能解决，还需要使用这个？还是格式设置的太多，太复杂。
没有必要什么东西都任意大，浪费别人的开发时间。


------------------ 原始邮件 ------------------
发件人: "ksharpy"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 上午10:38
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 任意大的文件如何读取成功的？ (#352)




请问这个问题解决了吗？我有一个300M的EXCEL无法读取

**Comment by ksharpy** [comment]
一个政府系统导出来的数据，在excel里面很难做处理

**Comment by ksharpy** [comment]
> 厉害啊，300M。我一个1048576行 * 10列的excel，31M左右，这都可以放一百多万行的数据了啊（行数都达到了单个sheet的峰值了），你那300M的数据，是自己人工填的，这得1000万行左右的数据，平台导出的，这么大的excel导出都能解决，还需要使用这个？还是格式设置的太多，太复杂。 没有必要什么东西都任意大，浪费别人的开发时间。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "ksharpy"<notifications@github.com>; 发送时间: 2019年6月25日(星期二) 上午10:38 收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [alibaba/easyexcel] 任意大的文件如何读取成功的？ (#352) 请问这个问题解决了吗？我有一个300M的EXCEL无法读取 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

政府系统导出来的数据，我也很无奈

**Comment by zhuangjiaju** [comment]
新版本已经支持超级大的数据了。请使用新版本
