### ISSUE TITLE
我的某个字段是string类型，但他实际表示的是一个数值，导出成excel之后，在Excel里他展示的是文本类型，不能使用office等功能，我想让他导出来就是数字类型。

### ISSUE THREAD

**Issue by wgaofei** [alibaba/easyexcel#3531]
目前使用了  @ContentStyle(dataFormat = 2)这个注解，发现并没有用，而且他还将我的居中样式取消了，变成了居左

**Comment by sstyo** [comment]
插入的时候转换下呗

**Comment by wgaofei** [comment]
> 插入的时候转换下呗

烦就烦在这，有的数据没有值的情况下，得给“-”，还不能给零；要是统一转成bigDecimal，这个“-”值就没办法处理。所以想着问问有没有其他办法的

**Comment by Nnaking** [comment]
![image](https://github.com/alibaba/easyexcel/assets/33016473/0d0130da-cf26-4c31-8d31-81d20c166455)
我也遇到了这个问题，`new FillWrapper("sheet", excelLineDataList)` 中的 `excelLineDataList` 是`List<Map<String, Object>>`；不知道是不是得定义Bo类来精确字段类型，而不是使用Object

**Comment by wgaofei** [comment]
> ![image](https://user-images.githubusercontent.com/33016473/280899499-0d0130da-cf26-4c31-8d31-81d20c166455.png) 我也遇到了这个问题，`new FillWrapper("sheet", excelLineDataList)` 中的 `excelLineDataList` 是`List<Map<String, Object>>`；不知道是不是得定义Bo类来精确字段类型，而不是使用Object

应该是这个问题，如果实体类字段是bigDecimal，导出来之后就默认是数字。但业务总是如此麻烦

**Comment by Nnaking** [comment]
> > ![image](https://user-images.githubusercontent.com/33016473/280899499-0d0130da-cf26-4c31-8d31-81d20c166455.png) 我也遇到了这个问题，`new FillWrapper("sheet", excelLineDataList)` 中的 `excelLineDataList` 是`List<Map<String, Object>>`；不知道是不是得定义Bo类来精确字段类型，而不是使用Object
> 
> 应该是这个问题，如果实体类字段是bigDecimal，导出来之后就默认是数字。但业务总是如此麻烦

是的，得业务层面来多转换一层，就可以避免此问题了。

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
