### ISSUE TITLE
3.3.2读取时间秒缺失

### ISSUE THREAD

**Issue by besehen** [alibaba/easyexcel#3536]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述

# 触发Bug的代码
List<Map<Integer, String>> readAll = EasyExcel.read(filePath).sheet().doReadSync();
```
# 提示的异常或者没有达到的效果
excel时间精确到秒，但是读取出来秒丢失，wps  xlsx
![image](https://github.com/alibaba/easyexcel/assets/22188377/3443f41b-d1fc-46e9-9e58-fec7cd117ae5)
![image](https://github.com/alibaba/easyexcel/assets/22188377/10586599-d12b-46d6-99e3-b752e006b668)

**Comment by hncboy** [comment]
当选中单元格时才会展示完整的日期，默认的格式是 yyyy/m/d h:mm，要想展示秒，可以将单元格时间格式改为 yyyy/m/d h:mm:ss
![image](https://github.com/alibaba/easyexcel/assets/27755574/74252ce5-241d-4ab9-a908-d1477132f9c7)

**Comment by psxjoy** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue.

**Comment by chenmch** [comment]
> 当选中单元格时才会展示完整的日期，默认的格式是 yyyy/m/d h:mm，要想展示秒，可以将单元格时间格式改为 yyyy/m/d h:mm:ss ![image](https://github.com/alibaba/easyexcel/assets/27755574/74252ce5-241d-4ab9-a908-d1477132f9c7)

我也遇到这个问题
