### ISSUE TITLE
多sheet页读取的时候，想要每个sheet读100行就读下一个sheet页

### ISSUE THREAD

**Issue by zerlynn** [alibaba/easyexcel#3537]
我的中断用过几种方式
第一种：
if (preView && dataList.size() >= limitRowSize) {
    throw new ExcelAnalysisException(this.limitRowSize + "行" + this.limitRowSize + "列读取完成");
}
第二种：
重写了hasNext方法，行数大于的时候返回false

以上两种方式均会导致，如果当前sheet页数据超出limit之后会中止读取，没法到下一个sheet读取

**Comment by zhoujun001** [comment]
使用hasNext=false 好像会使得doAfterAllAnalysed方法不会被执行

**Comment by chenzhilin0** [comment]
> 使用hasNext=false 好像会使得doAfterAllAnalysed方法不会被执行

是的，我这样也不行analysisContext.analysisEventProcessor().endSheet(analysisContext); 这样会执行doAfterAllAnalysed，但是后续的sheet页也会停止读取了

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
