### ISSUE TITLE
请问各位大佬，有自动设置列宽的案例吗？还有我现在用AfterWriteHandlerImpl来设置单元格样式，对效率有影响吗？

### ISSUE THREAD

**Issue by aixin743** [alibaba/easyexcel#354]

**Comment by Uetty** [comment]
不知道，我用这个其实是觉得注解方式比较方便

**Comment by aixin743** [comment]
但是用注解，样式都是默认的，而且也没有自动列宽啊。------------------ 原始邮件 ------------------
发件人: "Uetty"<notifications@github.com>
发送时间: 2019年7月22日(星期一) 晚上6:54
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "aixin743"<2314643632@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 请问各位大佬，有自动设置列宽的案例吗？还有我现在用AfterWriteHandlerImpl来设置单元格样式，对效率有影响吗？ (#354)



不知道，我用这个其实是觉得注解方式比较方便
 
&mdash;

**Comment by Uetty** [comment]
我是自己扩充了样式注解
https://github.com/uetty/common-excel
将anno、constant、easyexcel.hssf、model、util包（去掉ExcelProperty注解，这是为后续版本准备的）拷走就能用了
demo包是示例代码，headless为无标题示例，withhead是有标题示例，功能很单一，单个sheet只写一个表的写excel功能。

只是参考的话，看XlsExcelWriter.java代码就行了

**Comment by zhuangjiaju** [comment]
新版本实现了一个，也是和你一样的方式实现的，都是内存，所以效率基本不用担心。
