### ISSUE TITLE
多线程同时进行多表的导出是不支持的吗？

### ISSUE THREAD

**Issue by evelynn996** [alibaba/easyexcel#3550]
之前在使用poi写500W数据到EXCEL的时候，用多线程分多个表导出可以大幅优化导出的时间，从79秒能到47秒。
同时我注意到了EasyExcel不支持单个文件的并发写入、读取。所以我放弃了 多线程 写单个Excel表的多个Sheet ，想试试多个线程，一个线程只负责一个Excel表的写出，结果还是不行，本来应该有3个Excel表，最终只得到一个，而且还是损坏的。
所以，对于百万数据写入Excel的正确使用方式，就是单线程使用 分批查询，多次重复写入，判断一个Sheet达到100W行，则写下一个Shhet吗？

**Comment by hotdogc1017** [comment]
不支持多线程写入#3020

**Comment by evelynn996** [comment]
> 不支持多线程写入#3020

好的，感谢回复
