### ISSUE TITLE
使用正常导出携带公式的excel，读取单元格时有公式的值为null，如果忽略公式去读取值？

### ISSUE THREAD

**Issue by zxf8** [alibaba/easyexcel#3555]
![image](https://github.com/alibaba/easyexcel/assets/47075918/ce706496-93e5-40f9-a438-7128749082b7)
![image](https://github.com/alibaba/easyexcel/assets/47075918/abb527fd-bcb7-4f12-85f5-a91c58269008)
![image](https://github.com/alibaba/easyexcel/assets/47075918/dcd04379-328d-4f93-ac6f-c951b104a03d)

excel读取单元格时有公式的值为null，能否有什么方法读取到值，或者忽略掉公式直接读取单元格值

**Comment by hogwarts0827** [comment]
你用的是什么 版本啊。读取数据为NULL我刚刚也遇到了。然后把版本从3.1.5升级到3.3.2就好了。

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
