### ISSUE TITLE
新建一个List<byte[]>转为CellDate出现错误，莫名空指针？

### ISSUE THREAD

**Issue by JSerJXH** [alibaba/easyexcel#3563]
![image](https://github.com/alibaba/easyexcel/assets/53112870/5974c810-9131-4ace-b312-6ff6bd5470f2)
代码如上，但是却总空指针

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
