### ISSUE TITLE
动态选择导出内容

### ISSUE THREAD

**Issue by zyblove** [alibaba/easyexcel#357]
我们这边遇到一个业务需求，用户自己选择要导出的内容项（单表，单行表头），例如：映射关系中配置了所有的导出项，但是我想动态的选择某几项作为导出内容，有没有解决方案呢？是否可将表头排序的内容从注解中提取出来，使用接口的形式实现，顺便可以动态的配置导出内容？

**Comment by robinsono** [comment]
可以参考源码下测试包中：https://github.com/alibaba/easyexcel/tree/master/src/test/java/com/alibaba/easyexcel/test
可先定位到util/DataUtil.java

**Comment by zyblove** [comment]
好的，谢谢，我看看啊。

**Comment by zhuangjiaju** [comment]
新版本已经支持

**Comment by Ryoui** [comment]
2.0.0-bate4   请问，你是怎样解决的？我的需求和你一样，也是从页面提供的字段选择需要导出的，对象中也是所有的字段都配置了的，现在表头能正常动态生成，但把所有数据都导出了，而且顺序也不对。

**Comment by zyblove** [comment]
> 2.0.0-bate4 请问，你是怎样解决的？我的需求和你一样，也是从页面提供的字段选择需要导出的，对象中也是所有的字段都配置了的，现在表头能正常动态生成，但把所有数据都导出了，而且顺序也不对。

您好，我当时使用了其他的方式解决，您可以查看一下最新版，因为上面的人说新版已经支持了。
