### ISSUE TITLE
可以添加excel文件的自定义属性吗？

### ISSUE THREAD

**Issue by NicooooChan** [alibaba/easyexcel#3573]
可以添加excel文件的自定义属性吗？
![image](https://github.com/alibaba/easyexcel/assets/50325449/a659e26e-a58e-489f-b378-89717eac9a19)

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
