### ISSUE TITLE
模板填充合并单元格数据缺失问题和样式丢失问题？

### ISSUE THREAD

**Issue by ChenPeiChuang** [alibaba/easyexcel#3575]
#### 模板
![image](https://github.com/alibaba/easyexcel/assets/28059540/a7bfed93-5f0d-4e69-82bc-fcae92a6cec1)
#### 数据填充效果
![image](https://github.com/alibaba/easyexcel/assets/28059540/17803a01-2b16-4299-b7eb-7fe6ac0765e6)
#### 代码
excelWriter.fill(new FillWrapper("player2", playerList), writeSheet); // 三行数据

**Comment by 954589528** [comment]
您好请问这个问题有无解决方法？
