### ISSUE TITLE
请问生成excel的时候如何生成一列隐藏的列

### ISSUE THREAD

**Issue by pasake** [alibaba/easyexcel#359]
请问生成excel的时候如何生成一列隐藏的列，类似表单提交的时候隐藏的input

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。然后自定义拦截器。在创建完一行后，设置为隐藏
