### ISSUE TITLE
导出excel时，可以做到一行数据渲染多行excel吗？

### ISSUE THREAD

**Issue by Zmz0289** [alibaba/easyexcel#3593]
![image](https://github.com/alibaba/easyexcel/assets/71144052/59e72f56-b3a1-4b02-b5c6-3dddd1391fd3)

**Comment by LSL1618** [comment]
把行数据多生成一份不就行了，注意防范重复引用的问题。

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
