### ISSUE TITLE
空白行的坑

### ISSUE THREAD

**Issue by caizhixiang** [alibaba/easyexcel#360]
对excel表格的数据直接delete，这一行数据空了，但是easyexcel依然把那些空白行进行解析了，封装对象。这造成两个问题：①：根据行数限制上传excel 不准确、②、对某些字段做非空校验时，因为有空白对象（对象不为null，属性全为null）的存在，做出错误提示

**Comment by bymaxchen** [comment]
遇到这个问题+1

**Comment by luanweijie** [comment]
+1

**Comment by lgx211** [comment]
空白行的问题，不好处理啊，作者底层也是优化POI的sax模式，sax模式对于空白行就没有处理好，要么去解决sax模式的底层，要么你自己的业务代码做出适当的处理。




------------------ 原始邮件 ------------------
发件人: "WeijieLuan"<notifications@github.com>;
发送时间: 2019年6月19日(星期三) 下午4:47
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 空白行的坑 (#360)




+1

**Comment by WangChaolin** [comment]
+1

**Comment by lgx211** [comment]
如果你深入了解excel，那就会知道excel有物理删除和逻辑删除，所谓的空白行问题就是，你的那行是逻辑删除，并没有做物理删除，这个是读一行写入内存一行，主要是避免内存溢出，提高性能，不可能去循环判断该行是否为空，为空就不添加进去。如果不添加空的那一行，那么之后的行号就和内容对应不上了。清楚吗？
你要是有这种需求，要么模板告诉用户操作注意，要么拿到解析的数据后，自己去循环判断。


------------------ 原始邮件 ------------------
发件人: "WangChaolin"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 下午4:26
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "Richard"<2029666191@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 空白行的坑 (#360)




+1

**Comment by Poppy666** [comment]
有没有什么解决办法呀，读取文件的时候会一直读，把excel末尾的空白行全部读入了

**Comment by wwggyy** [comment]
> 如果你深入了解excel，那就会知道excel有物理删除和逻辑删除，所谓的空白行问题就是，你的那行是逻辑删除，并没有做物理删除，这个是读一行写入内存一行，主要是避免内存溢出，提高性能，不可能去循环判断该行是否为空，为空就不添加进去。如果不添加空的那一行，那么之后的行号就和内容对应不上了。清楚吗？ 你要是有这种需求，要么模板告诉用户操作注意，要么拿到解析的数据后，自己去循环判断。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "WangChaolin"<notifications@github.com>; 发送时间: 2019年6月25日(星期二) 下午4:26 收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>; 抄送: "Richard"<2029666191@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [alibaba/easyexcel] 空白行的坑 (#360) +1 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

POI库，可以过滤掉逻辑删除这部分数据。

**Comment by wwggyy** [comment]
POI库，可以过滤掉逻辑删除这部分数据。

**Comment by zhuangjiaju** [comment]
新版本 已经过滤了这些数据。请尝试升级版本

**Comment by SANDUO421** [comment]
> 新版本 已经过滤了这些数据。请尝试升级版本

你好，我poi和easyExcel 都是最新版，目前还有问题

**Comment by 241600489** [comment]
遇到了相同的问题

**Comment by vito16** [comment]
重写`hasNext`方法，判断取出来的数据，如果为空返回`false`就可以了    

```
@Override
public boolean hasNext(AnalysisContext context) {
    Map<Integer, Cell> cellMap =context.readRowHolder().getCellMap();
    return !CollectionUtils.isEmpty(cellMap);
}
```

**Comment by wolf9236** [comment]
不起作用，只有第一行进入了方法判断，

**Comment by xhjzrq** [comment]
还是 有问题啊  2.210 版本 得 空行 还是 读取进来了

**Comment by zhangdongcq** [comment]
下面是判断某行是不是空行的函数。可以判断后选择如何操作。
![image](https://user-images.githubusercontent.com/20893557/145289406-ba179c98-0430-4ade-82ad-eda3306173eb.png)

**Comment by chency-jn** [comment]
解决了吗？

**Comment by pancun9527** [comment]
Map<Integer, Cell> cellMap =analysisContext.readRowHolder().getCellMap();
        boolean atLeastOneCellNotNull = cellMap.values().stream()
                .anyMatch(this::isCellNotNull);
        if (!atLeastOneCellNotNull) {
            // 跳过包含空单元格的行
            return;
        }

/**
     * 判断该单元格的值是否为null
     * @param cell
     * @return
     */
    private boolean isCellNotNull(Cell cell) {
        CellData<Object> cellData = (CellData<Object>) cell;
        Object cellValue = cellData.getData();
        String stringValue = cellData.getStringValue();
        BigDecimal numberValue = cellData.getNumberValue();
        log.info("cellV:{}",cellValue);
        log.info("stringValue:{}",stringValue);
        log.info("numberValue:{}",numberValue);
        return (cellValue!=null&&!"".equals(cellValue))||(StringUtils.isNotBlank(stringValue))||(numberValue!=null);
    }

😄 no thanks

**Comment by pancun9527** [comment]
private static boolean isRowEmpty(Row row) {
        if (row == null || row.getLastCellNum() <= 0) {
            return true;
        }
        for (int cellNum = row.getFirstCellNum(); cellNum <= row.getLastCellNum(); cellNum++) {
            Cell cell = row.getCell(cellNum);
            if (cell != null && cell.getCellType() != CellType.BLANK) {
                //此时非空行
                return false;
            }
        }
        return true;
    }
