### ISSUE TITLE
写excel使用AbstractRowWriteHandler合并单元格后出现问题

### ISSUE THREAD

**Issue by MovingBrick-er** [alibaba/easyexcel#3607]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
![image](https://github.com/alibaba/easyexcel/assets/76142107/0e2cf6e4-cb60-42a6-ba13-2559d1c3134e)

![image](https://github.com/alibaba/easyexcel/assets/76142107/4b41515a-ef7f-4539-8292-c1b57f9a579b)

   
![image](https://github.com/alibaba/easyexcel/assets/76142107/3d52524e-2c33-4103-b29d-978f53a705b2)

```
# 异常提示
![image](https://github.com/alibaba/easyexcel/assets/76142107/c6c0836a-7ecf-4131-b984-81f89336e022)

# 问题描述

**Comment by MovingBrick-er** [comment]
![Snipaste_2023-12-15_11-20-21](https://github.com/alibaba/easyexcel/assets/76142107/c319bf06-9abb-4c74-893a-3ecce02ff35f)
assets/76142107/49cc0028-1706-429f-8161-b715e7797961)

**Comment by MovingBrick-er** [comment]
![image](https://github.com/alibaba/easyexcel/assets/76142107/add04497-5ad5-4a38-bd95-b20f220d3f70)

**Comment by MovingBrick-er** [comment]
![Snipaste_2023-12-15_11-20-48](https://github.com/alibaba/easyexcel/assets/76142107/22facfdf-6f9e-482f-b79d-53de6a10d177)



![Snipaste_2023-12-15_11-21-03](https://github.com/alibaba/easyexcel/assets/76142107/c9fb0065-b6e3-41e6-91dd-5fba8e7d9333)

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
