### ISSUE TITLE
请问使用handler加完下拉值之后，怎么加上出错警告？加上下拉值之后没自动勾选出错警告

### ISSUE THREAD

**Issue by wangcuisun** [alibaba/easyexcel#3613]
![1](https://github.com/alibaba/easyexcel/assets/23044512/9ee7a2f0-81ba-4615-a6d7-4f46792bdf5f)
![2](https://github.com/alibaba/easyexcel/assets/23044512/c890a2f9-d8ee-4a6b-b371-ad1e95aad89d)

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
