### ISSUE TITLE
在一个excel中，有多个表格，每个表格上面有一行说明，可以解析吗？

### ISSUE THREAD

**Issue by sunweilu** [alibaba/easyexcel#3617]
# excel数据格式
![image](https://github.com/alibaba/easyexcel/assets/49406132/618c00c6-da6f-4897-9bed-abfe39e1688b)
# 需求
获取每个表格的数据以及表格上面的档号，因为要根据档号存储，可以实现吗？
# 异常提示

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
