### ISSUE TITLE
怎样才能获取上传的excel表格的总列数呢？

### ISSUE THREAD

**Issue by yigerendehaotianqi** [alibaba/easyexcel#362]
怎样才能获取上传的excel表格的总列数呢？

**Comment by yigerendehaotianqi** [comment]
我真的很需要帮助

**Comment by fish7790714** [comment]
如果数据量不大，
```java
        List<Object> data = EasyExcelFactory.read(inputStream, new Sheet(1, 0));
```
data.size 就是
如果大,
```java
  ExcelListener excelListener = new ExcelListener();
            ExcelReader excelReader = new ExcelReader(inputStream, null, excelListener, false);
```
然后 excelListener 的invoke 方法 去统计+1 最后得到总的列数

**Comment by YancyPeng** [comment]
需要在开始解析前获取列数和sheet数，以此来进行判断是否要开启多个线程，列数和sheet数怎么获取？

**Comment by zhuangjiaju** [comment]
目前不支持多线程

**Comment by FengShaduVIP** [comment]
目前使用2.0.5版本 读取xls文件 获取总列数为null 

`analysisContext.readSheetHolder().getTotal()`
@YancyPeng

**Comment by shushengming** [comment]
`    @Override
    public void invoke(ShWmsOrderFb data, AnalysisContext context) {
    
        if (!getTotal) {
            wmsTotal = context.readSheetHolder().getTotal() - 1;
            getTotal = true;
        }
        
        // 上传进度
        String excelId = ThreadLocalUtil.getExcelId();
        numberFormat.setMaximumFractionDigits(2);
        String format = numberFormat.format(((float) ++totals / wmsTotal) * 100).concat("%");
        LOGGER.info("excelId:{},进度{}", excelId, format);
        redisUtils.set(WMS_UPLOAD_PROGREE_KEY.concat(excelId), format);
        
        list.add(data);
        if (list.size() >= BATCH_COUNT) {
            saveData();
            list.clear();
        }
    }`

**Comment by cryboy007** [comment]
这样子就行了
ExcelReader excelReader  = EasyExcelFactory.read(inputStream).build().read(new ReadSheet(0));
int row = excelReader.analysisContext().readRowHolder().getRowIndex();

**Comment by kaciry0927** [comment]
context.readSheetHolder().getApproximateTotalRowNumber()
这个方法在2.2.10版本中调用不太准确，在数据被右键点击删除行时是正确返回的，但是将行数据使用Delete键删除时，返回的数据不会变化 @zhuangjiaju
