### ISSUE TITLE
单元格样式加载错误问题

### ISSUE THREAD

**Issue by lllzy222** [alibaba/easyexcel#3621]
![微信图片_20231222183440](https://github.com/alibaba/easyexcel/assets/153477673/c34cf5f6-d2cd-44a7-acd3-9595aecce8e5)
![微信图片_20231222183220](https://github.com/alibaba/easyexcel/assets/153477673/1666e6e7-cf7f-4825-b89d-2db0db85f514)
![image](https://github.com/alibaba/easyexcel/assets/153477673/098f1fe7-3d17-4ff3-a4c4-1ae4ee9574c6)

生成Excel时指定了样式，生成后的Excel 选择单元格，可以看到上方样式已经显示了货币，但是单元格里面的内容并没有变化，此时双击单元格选中后，点击其他地方取消选中，单元格里面的内容变成了正常的价格样式， 请问如何修改代码，使他导出后直接显示正常的价格样式呢？  其他单元格数据格式同样存在这个问题

**Comment by haiyex** [comment]
遇到了同样的问题，设置了样式，但是生成的Excel需要双击才能显示成对应的样式

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
