### ISSUE TITLE
多列导出很慢

### ISSUE THREAD

**Issue by PhaerisWakfu** [alibaba/easyexcel#3624]
# 建议先去看文档
看了文档与好多issue好像没有跟我类似的问题
# 建议描述
场景是当导出数据时，一个100行 * 16000列的excel，导出要1-2分钟，有时候甚至会一直阻塞在writer.write(data.getResultList(), sheet)。
我这个需求比较特殊，需要我将数据库中的一维表数据通过代码转成二维表，比如我2个行2个列2个指标，原始数据是6列，8000行，但是我转为二维表后，行列分组去重后，列字段横向遍历有指标个数 * 列字段数据个数，也就是8000 * 2个列，但行纵向遍历可能只有100条。
这种场景是不一定的，有可能行字段数据多也有可能列字段数据多，实验下来是列数过多会比较影响速度，而行数多列数少（也就是大部分人使用的方式）则速度快很多
代码如下  
```java
        //构建workbook writer
        ExcelWriter writer = writerBuilder
                .registerConverter(new TimestampConverter())
                .registerConverter(new DateConverter())
                .registerWriteHandler(new LongestMatchColumnWidthStyleStrategy())
                .build();

        //获取数据
        List<SheetData> sheetData = getSheetData(requestDTO);

        try {
            for (int i = 0; i < sheetData.size(); i++) {
                SheetData data = sheetData.get(i);
                //获取需要冻结几行
                Integer freezeRow = data.getHeaders().stream().findAny().map(List::size).orElse(null);
                //设置样式
                WriteSheet sheet = EasyExcelFactory.writerSheet(i, data.getSheetName())
                        .head(data.getHeaders())
                        .registerWriteHandler(new DynamicFieldFormatCellStyleStrategy(data.getFormat(), freezeRow))
                        .build();
                //写数据生成sheet
                writer.write(data.getResultList(), sheet);
            }
            //导出
            writer.finish();
        } finally {
            //清理资源
            dispose();
        }
```
能否有什么好的办法

**Comment by LSL1618** [comment]
导出时间过长的情况，建议使用异步导出，创建一个导出记录表，每次导出实际上只是生成文件然后保存导出记录，再新增一个查看导出记录的入口，专用于下载导出记录中的文件。

**Comment by PhaerisWakfu** [comment]
> 导出时间过长的情况，建议使用异步导出，创建一个导出记录表，每次导出实际上只是生成文件然后保存导出记录，再新增一个查看导出记录的入口，专用于下载导出记录中的文件。

这个本身就是在异步任务中执行的，需求就是订阅报表截图和下载报表excel，每一个都是独立的任务，就想问下有没有什么办法可以提高速度

**Comment by LSL1618** [comment]
> > 导出时间过长的情况，建议使用异步导出，创建一个导出记录表，每次导出实际上只是生成文件然后保存导出记录，再新增一个查看导出记录的入口，专用于下载导出记录中的文件。
> 
> 这个本身就是在异步任务中执行的，需求就是订阅报表截图和下载报表excel，每一个都是独立的任务，就想问下有没有什么办法可以提高速度

你这个列数太多了，有没有可能是自动列宽策略LongestMatchColumnWidthStyleStrategy导致耗时，或者自定义单元格样式策略频繁创建样式类实例导致耗时。

**Comment by PhaerisWakfu** [comment]
> > > 导出时间过长的情况，建议使用异步导出，创建一个导出记录表，每次导出实际上只是生成文件然后保存导出记录，再新增一个查看导出记录的入口，专用于下载导出记录中的文件。
> > 
> > 
> > 这个本身就是在异步任务中执行的，需求就是订阅报表截图和下载报表excel，每一个都是独立的任务，就想问下有没有什么办法可以提高速度
> 
> 你这个列数太多了，有没有可能是自动列宽策略LongestMatchColumnWidthStyleStrategy导致耗时，或者自定义单元格样式策略频繁创建样式类实例导致耗时。

感谢回复，我测下看看

**Comment by PhaerisWakfu** [comment]
> > > 导出时间过长的情况，建议使用异步导出，创建一个导出记录表，每次导出实际上只是生成文件然后保存导出记录，再新增一个查看导出记录的入口，专用于下载导出记录中的文件。
> > 
> > 
> > 这个本身就是在异步任务中执行的，需求就是订阅报表截图和下载报表excel，每一个都是独立的任务，就想问下有没有什么办法可以提高速度
> 
> 你这个列数太多了，有没有可能是自动列宽策略LongestMatchColumnWidthStyleStrategy导致耗时，或者自定义单元格样式策略频繁创建样式类实例导致耗时。

去掉LongestMatchColumnWidthStyleStrategy，100行 * 16000列速度从108秒降到4秒了，🙏感谢

**Comment by PhaerisWakfu** [comment]
去掉LongestMatchColumnWidthStyleStrategy速度就上去了，这个策略在列多的情况下会特别耗时

**Comment by LSL1618** [comment]
> 去掉LongestMatchColumnWidthStyleStrategy速度就上去了，这个策略在列多的情况下会特别耗时

从108s降到4s，这个时间差距，只能说LongestMatchColumnWidthStyleStrategy的性能太差了，而且列宽还不准确，需要谨慎使用！
