### ISSUE TITLE
多sheet表的自定义拦截器如何在加载数据之后生效？

### ISSUE THREAD

**Issue by lmx0106** [alibaba/easyexcel#3629]
# 异常代码
```java
  WriteSheet writeSheet = EasyExcel.writerSheet(i++,type.getTypeName())
                        .relativeHeadRowIndex(4)
                        .registerWriteHandler(new inventorySheetWriteHandler())
                        .registerWriteHandler(myMergeStrategy)
                        .registerWriteHandler(myMergeStrategy1)
                        .registerWriteHandler(myMergeStrategy2)
                        .build();

                excelWriter.write(inventoryList,writeSheet);
```
# 异常提示
无异常，需求帮助
# 问题描述
因为是先加的拦截器再放入的数据，导致表尾样式设置不了；请求帮助，直接dowrite的话只有一个sheet表

**Comment by LSL1618** [comment]
如果自定义的拦截器是多个sheet共用，试试把registerWriteHandler()移到创建excelWriter那一步。

**Comment by lmx0106** [comment]
拦截器里设置了表尾样式，未填充数据前表尾样式设置不了；

**Comment by LSL1618** [comment]
> 拦截器里设置了表尾样式，未填充数据前表尾样式设置不了；

就是说需要填充完数据之后，再调用拦截器去处理表尾样式。估计需要二次读取才能处理表尾样式。

**Comment by lmx0106** [comment]
如何实现填充完数据再调取拦截器，大佬能发个demo吗？

**Comment by LSL1618** [comment]
> 如何实现填充完数据再调取拦截器，大佬能发个demo吗？

好像也不用二次读取，拦截器接口有好几个方法的，你实现的是哪个方法？

**Comment by lmx0106** [comment]
public class inventorySheetWriteHandler implements SheetWriteHandler {

    @Override
    public void afterSheetCreate(WriteWorkbookHolder writeWorkbookHolder, WriteSheetHolder writeSheetHolder) {
        Workbook workbook = writeWorkbookHolder.getWorkbook();
        Sheet sheet = writeSheetHolder.getSheet();
//        Sheet sheet = workbook.getSheetAt(writeSheetHolder.getSheetNo());
//        Sheet sheet = workbook.getSheetAt(0);

        // 样式设计
        CellStyle cellStyle2 = workbook.createCellStyle();
        cellStyle2.setVerticalAlignment(VerticalAlignment.CENTER);
        cellStyle2.setAlignment(HorizontalAlignment.CENTER);

        Font font2 = workbook.createFont();
        font2.setFontHeight((short) 220);
        font2.setFontName("仿宋体");

        cellStyle2.setFont(font2);

**Comment by LSL1618** [comment]
@lmx0106 你试试实现这个方法`afterCellDispose()`去处理。
