### ISSUE TITLE
模板填充样式丢失问题

### ISSUE THREAD

**Issue by HaceraI** [alibaba/easyexcel#3649]
今天升级了一下easyexcel 版本，升级后发现 模板填充部分样式丢失，fock下来自己本地改改断点调试最终自己使用的项目成功恢复，分享一点信息：

+ 填充样式丢失触发条件：
当前单元格有且仅有一个模板字符串，并且该单元格不属于集合，例如(`missing`字段填充完毕后，会丢失样式)：
![image](https://github.com/alibaba/easyexcel/assets/48341368/7d36e284-070e-42b5-bcdc-cb3e970e1fd3)

+ 我的解决方法
// `ExcelWriteFillExecutor.createCell` 内，如果 单元格类型是 `COMMON`，将样式也放入到 `collectionFieldStyleCache` 内，这样在 doFill 方法内的 Restyle 就能够成功执行.
https://github.com/alibaba/easyexcel/blob/master/easyexcel-core/src/main/java/com/alibaba/excel/write/executor/ExcelWriteFillExecutor.java#L317-L327
![image](https://github.com/alibaba/easyexcel/assets/48341368/242fb380-f657-407f-8374-0964a8503bc0)
![image](https://github.com/alibaba/easyexcel/assets/48341368/eef928e1-e8de-4823-a7ae-273ec6591592)

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。

**Comment by nmaxnsdqrqe8556** [comment]
到现在还没修
