### ISSUE TITLE
空表头如何去除

### ISSUE THREAD

**Issue by hou718945431** [alibaba/easyexcel#365]
我用1.1.2之前的jar导出是没有空表头的，我看1.1.2修复了表头问题  但现在导出就有空表头  求解决

**Comment by fish7790714** [comment]
具体问题 能否描述清楚？代码 +需要的效果

**Comment by hou718945431** [comment]
ExcelWriter writer = EasyExcelFactory.getWriter(out,ExcelTypeEnum.XLSX,false);Sheet sheet1 = new Sheet(1, 0);writer.write1(data, sheet1);writer.finish();这样把data写入到文件中，第一行是空的，1.1.2之后就会出现这样的问题




------------------ 原始邮件 ------------------
发件人: "zhuangjiaju"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 下午5:32
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "旋风小子"<718945431@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 空表头如何去除 (#365)




具体问题 能否描述清楚？代码 +需要的效果

**Comment by fish7790714** [comment]
我感觉作者希望 你必须有头。建议调用 ` sheet1.setHead` 加入头，当然 不加入头 可以使用：
```java
sheet1.setStartRow(-1)
```
从-1行开始，这个这个版本能用，但是不确定下个版本 作者是否会改成 默认不设置头的情况下 默认就从第一行开始

**Comment by hou718945431** [comment]
之前测试用的jar包比较老  然后没问题  上生产之前升级了一下 发现了这个问题 我看git上面很早就有提到过这个问题 但没有人解决




------------------ 原始邮件 ------------------
发件人: "zhuangjiaju"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 下午3:59
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "旋风小子"<718945431@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 空表头如何去除 (#365)




我感觉作者希望 你必须有头。建议调用  sheet1.setHead 加入头，当然 不加入头 可以使用：
 sheet1.setStartRow(-1)
 
从-1行开始，这个这个版本能用，但是不确定下个版本 作者是否会改成 默认不设置头的情况下 默认就从第一行开始

**Comment by fish7790714** [comment]
应该作者比较忙 你这个问题 先别关  我想办法联系下作者

**Comment by hou718945431** [comment]
还有一个问题  就是new sheet(a,b)这个a,b参数设置无效，1.1.2之后。之前没试过




------------------ 原始邮件 ------------------
发件人: "zhuangjiaju"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 下午4:04
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "旋风小子"<718945431@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 空表头如何去除 (#365)




应该作者比较忙 你这个问题 先别关  我想办法联系下作者

**Comment by fish7790714** [comment]
嗯 嗯 到时候 我想办法一起问问

**Comment by zl15145428** [comment]
> 我感觉作者希望你必须有头。建议调用` sheet1.setHead`加入头，当然不加入头可以使用：
> 
> ```java
> sheet1 。setStartRow（- 1）
> ```
> 
> 从-1行开始，这个这个版本能用，但是不确定下个版本作者是否会改成默认不设置头的情况下默认就从第一行开始

非常棒，我用这个办法去掉了表头空白行。

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。设置`needHead`=`false`即可
