### ISSUE TITLE
如何在模板错误的场景下获取到准确行数信息

### ISSUE THREAD

**Issue by OneBella** [alibaba/easyexcel#3658]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述
现在有一种场景是：在读取错误Excel模板的情况下，获取准确的行数信息，要问为啥，已有的其他代码决定的。。。。
当前代码debug会在处理完表头信息后，直接不解析数据了，应该是没和DataModel匹配上异常退出，无法在invoke解析的时候准确累加行数，context.readSheetHolder().getApproximateTotalRowNumber()方法的注释是非精确，请教下有没有其他的办法

**Comment by OneBella** [comment]
忘了doafterall。。。已解决

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
