### ISSUE TITLE
可以在 python 中调用吗？如何调用

### ISSUE THREAD

**Issue by wonb168** [alibaba/easyexcel#3659]
开发语言是 python，导出 excel 慢且费内存，想在 python 中使用这个包

**Comment by murainwood** [comment]
java写，打出个jar，然后写个shell脚本，python调用呗

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
