### ISSUE TITLE
时间格式读取错误,bigdecimal接收不到值

### ISSUE THREAD

**Issue by Nullpointerdxy** [alibaba/easyexcel#366]
javamodel 处理日期格式如下,
![image](https://user-images.githubusercontent.com/30741355/57829703-67d77b00-77e2-11e9-94be-6cbc0381b423.png)
excel中填写的是2019/5/16
实际读取到的是Mon Apr 19 00:00:00 CST 6,读取日期有问题,还有javamodel的bigdecimal属性怎么接收不到值

**Comment by Nullpointerdxy** [comment]
bigdecimal问题解决了 现在就是日期读取不对  我用date接收到的是错误的日期,用string类型接收到5/16/2019,然后MM/dd/yyyy这种格式,解析出来是0019-05-15 10:00:00这样的

**Comment by houguiqiang** [comment]
我现在是000000001234这种类型到不能写入

**Comment by Nullpointerdxy** [comment]
你这个是字符串还是日期?日期的话你选择对应的日期格式,填写完之后,还需要改变单元格格式为常规,这样java代码用date就能接收到

**Comment by houguiqiang** [comment]
我这个是string类型的，eg：0000000000000000000000000000000000010001

**Comment by Nullpointerdxy** [comment]
我字符串写入没问题的呀,你报什么错

**Comment by houguiqiang** [comment]
没报错，
private static void writeData2exl(List<KeyWordVO> list) throws FileNotFoundException, IOException{
		String fileName = "keydatatrs-"+System.currentTimeMillis()+".csv";
		 try (OutputStream out = new FileOutputStream("d:\\"+fileName);) {
	         ExcelWriter writer = new ExcelWriter(out, ExcelTypeEnum.XLSX);
	         Sheet sheet1 = new Sheet(1, 0, KeyWordVO.class);
	         sheet1.setSheetName("sheet1");
	         writer.write(list, sheet1);
	         writer.finish();
	      }
	}
上面读取一个vo list 
下图为结果
![image](https://user-images.githubusercontent.com/1575749/58073561-84eebe00-7bd5-11e9-976c-b896c2ce9952.png)

**Comment by houguiqiang** [comment]
其他字符串都没问题，就类似0000000001这种格式到没有写入excel里面，也没报错。

**Comment by Nullpointerdxy** [comment]
那就不清楚了,我这边字符串都可以的

**Comment by houguiqiang** [comment]
嗯，可以了，我刚刚把属性字段F_NEW 改成f_NEW可以了。
