### ISSUE TITLE
模板填充时在excel里设置单元格格式后，需要双击才能按对应的格式展示

### ISSUE THREAD

**Issue by adrift00** [alibaba/easyexcel#3669]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述
提前在模板文件里设置日期的单元格格式，在java代码里使用Map<String, String>来存储要填充的内容
![1](https://github.com/alibaba/easyexcel/assets/35949066/ab13aaef-c121-4a25-9155-c4cfdbceb517)

填充之后没有按对应格式展示内容：
![2](https://github.com/alibaba/easyexcel/assets/35949066/4ccf8bca-6397-437c-a53e-ee8c1a1b3813)

而双击该单元格后，可以按预先设定的格式展示：
![3](https://github.com/alibaba/easyexcel/assets/35949066/02a1fd13-0570-44b5-bbe6-9a9974cfec87)

**Comment by adrift00** [comment]
![image](https://github.com/alibaba/easyexcel/assets/35949066/ed6a8e91-5fe1-4256-8799-4219ee79c22b)

**Comment by ennian001** [comment]
重新实现WorkbookWriteHandler，这行加上 
// 强制公式计算
workbook.setForceFormulaRecalculation(true);
`public class CustomWorkbookWriteHandler implements WorkbookWriteHandler {

    @Override
    public void afterWorkbookDispose(WorkbookWriteHandlerContext context) {
        Workbook workbook = context.getWriteWorkbookHolder().getCachedWorkbook();
        // 强制公式计算
        workbook.setForceFormulaRecalculation(true);
    }
}`

**Comment by haiyex** [comment]
> 重新实现WorkbookWriteHandler，这行加上 // 强制公式计算 workbook.setForceFormulaRecalculation(true);
> 
> **完整代码** `public class CustomWorkbookWriteHandler implements WorkbookWriteHandler {
> 
> ```
> @Override
> public void afterWorkbookDispose(WorkbookWriteHandlerContext context) {
>     Workbook workbook = context.getWriteWorkbookHolder().getCachedWorkbook();
>     // 强制公式计算
>     workbook.setForceFormulaRecalculation(true);
> }
> ```
> 
> }`

遇到了同样的问题，使用这个方法解决了吗

**Comment by ddddict** [comment]
> > 重新实现WorkbookWriteHandler，这行加上 // 强制公式计算 workbook.setForceFormulaRecalculation(true);
> > **完整代码** `public class CustomWorkbookWriteHandler implements WorkbookWriteHandler {
> > ```
> > @Override
> > public void afterWorkbookDispose(WorkbookWriteHandlerContext context) {
> >     Workbook workbook = context.getWriteWorkbookHolder().getCachedWorkbook();
> >     // 强制公式计算
> >     workbook.setForceFormulaRecalculation(true);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }`
> 
> 遇到了同样的问题，使用这个方法解决了吗

可以, 已解决
