### ISSUE TITLE
异常Attempting to write a row[0] in the range [0,0] that is already written to disk

### ISSUE THREAD

**Issue by huyifei2016** [alibaba/easyexcel#367]
Attempting to write a row[0] in the range [0,0] that is already written to disk

sheet.setRandomAccessWindowSize()是不是这里设置的太小，导致这个异常

**Comment by fish7790714** [comment]
这个是重复 创建row  你代码贴一下 还有 设置setRandomAccessWindowSize目的是啥？

**Comment by evanyangg** [comment]
@huyifei2016 请问你这个bug解决了吗

**Comment by huyifei2016** [comment]
InputStream inputStream = FileUtil.getResourcesFileInputStream("temp.xlsx");
        AfterWriteHandlerImpl afterWriteHandler=new AfterWriteHandlerImpl();
        OutputStream out = new FileOutputStream("temp11.xlsx");
        ExcelWriter writer=EasyExcelFactory.getWriterWithTempAndHandler(inputStream,out, ExcelTypeEnum.XLSX,true,afterWriteHandler);
      //  ExcelWriter writer = EasyExcelFactory.getWriterWithTemp(inputStream,out, ExcelTypeEnum.XLSX,true);
        //写第一个sheet, sheet1  数据全是List<String> 无模型映射关系
        Sheet sheet1 = new Sheet(1, 1);
        sheet1.setSheetName("第一个sheet");
        //heet1.setStartRow(20);
    //    writer.m(createTestListJavaMode(),sheet1);
  //  writer.write1(createTestListJavaMode(),sheet1);
        writer.write(createTestListJavaMode(),sheet1);
        writer.finish();
        out.close();
        inputStream.close();

**Comment by huyifei2016** [comment]
我知道我的问题在哪里谢谢

**Comment by huyifei2016** [comment]
没有设置sheet1.setHead(createTestListStringHead());
