### ISSUE TITLE
模板可否支持公式模板，现在模板只支持数据模板，不支持公式模板

### ISSUE THREAD

**Issue by ennian001** [alibaba/easyexcel#3677]
类似，花钱的Gcexcel
![image](https://github.com/alibaba/easyexcel/assets/36769491/4e519bae-9000-4b3b-ab56-a01a6200b346)

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
