### ISSUE TITLE
数字转人名币大写的复杂函数不能执行

### ISSUE THREAD

**Issue by Wusdragon** [alibaba/easyexcel#3679]
![image](https://github.com/alibaba/easyexcel/assets/116860729/94ea18d9-f4ac-46db-abce-a8b52f0bfa55)

数字转人民币大写函数：=IF(MOD(A1,1)=0,TEXT(INT(A1),"[DBNUM2]")&"元"&"整",TEXT(INT(A1),"[DBNUM2]")&"元"&TEXT(MID(A1,LEN(INT(A1))+2,1),"[DBNUM2]D角")&TEXT(MID(A1,LEN(INT(A1))+3,1),"[DBNUM2]D分"))

使用在内存内进行函数运算的方式，并不能计算出大写形式。需要手动在excel文件内对该表达式触发执行
代码
![image](https://github.com/alibaba/easyexcel/assets/116860729/b73610e9-2303-48d3-bd71-b53b4f8482fc)
结果
![image](https://github.com/alibaba/easyexcel/assets/116860729/87195298-c443-43d7-a821-ac427ed33279)

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
