### ISSUE TITLE
实体字段映射能否根据字段名匹配？

### ISSUE THREAD

**Issue by XHZY1314** [alibaba/easyexcel#3692]
查看文档发现导出数据与表头之间的映射方式是通过@ExcelProperty注解来实现的。
我的项目比较特殊，实体是通过类似lombok的机制生成出来的，不能做到自定义，能否支持通过其他方式匹配映射字段？

**Comment by psxjoy** [comment]
比较简单的方式，是在运行时动态地创建一个映射，将实体类的字段名称映射到 Excel 表头名称。

**Comment by XHZY1314** [comment]
cxv

**Comment by psxjoy** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue.
