### ISSUE TITLE
按照测试案例写了个简单的Demo，没有输出任何内容，数据是没有问题的

### ISSUE THREAD

**Issue by wpeace1212** [alibaba/easyexcel#37]
![image](https://user-images.githubusercontent.com/11496700/42509124-8ecddd02-847d-11e8-9c31-4e0de6a0d0e7.png)
使用的版本
 <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>1.0.1</version>
</dependency>
系统：centos7
你好，test的Demo卡住。麻烦解答下，另外你们这边有对比过StreamingReader的性能

**Comment by jipengfei-jpf** [comment]
1.0.3最近版本
