### ISSUE TITLE
2.2.11 子类@ExcelIgnore未生效

### ISSUE THREAD

**Issue by runoob-beggar** [alibaba/easyexcel#3700]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
@Data
@ExcelIgnoreUnannotated
@HeadStyle(fillForegroundColor = 55)
public abstract class Parent {
    @ExcelProperty(value = "名称", order = 0)
    @ColumnWidth(value = 20)
    @HeadStyle(fillForegroundColor = 21)
    private String name;
}

@EqualsAndHashCode(callSuper = true)
@Data
public class Child extends Parent {
    @ExcelIgnore
    private String name;
}

public static void main(String[] args) throws IOException {
    // ...
    ExcelWriter excelWriter = EasyExcel.write(Files.newOutputStream(new File("aaa.xlsx").toPath()), Child.class).build();
    // ...
}
```
# 异常提示
无
# 问题描述
EasyExcel 2.2.11，子类覆盖父类属性时，@ExcelIgnore未生效（我希望用子类生成excel时，不需要【名称】这一列）

已参考 [子类@ExcelIgnore未生效 · Issue #2764 · alibaba/easyexcel](https://github.com/alibaba/easyexcel/issues/2764) 但是未解决，是否低版本已不支持？或能否有其他方式实现

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
