### ISSUE TITLE
Converter中convertToExcelData方法设置样式不生效

### ISSUE THREAD

**Issue by mizoreyo** [alibaba/easyexcel#3703]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   @Override
    public WriteCellData<?> convertToExcelData(HashMap<String, Object> value, ExcelContentProperty contentProperty,
                                               GlobalConfiguration globalConfiguration) throws Exception {
        Double v = (Double) value.get("value");
        if (v == null) {
            return new WriteCellData<>("");
        } else {
            WriteCellData<Object> cellData = new WriteCellData<>(BigDecimal.valueOf(v));
            if (value.get("highlight") != null && (Boolean) value.get("highlight")) {
                WriteCellStyle style = new WriteCellStyle();
                style.setFillForegroundColor(IndexedColors.RED.getIndex());
                cellData.setWriteCellStyle(style);
            }
            return cellData;
        }
    }
```
# 异常提示
![image](https://github.com/alibaba/easyexcel/assets/61266947/918c052c-9120-4df5-ac7a-ab3e2e2d8b19)
并未显示为红色
# 问题描述
我希望某些数据显示为红色，是否显示为红色与数据处理规则相关，所以我的数据为Map，Map中highlight为true的数据显示为红色，但是我在转换器中设置了样式并没有生效，如果使用拦截器的话会非常的麻烦

**Comment by LSL1618** [comment]
加上这个试试`cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);`

**Comment by mizoreyo** [comment]
> 加上这个试试`cellStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);`

谢谢，有颜色了，但是为什么看上去像是背景颜色，我这里测试的是日期的转换器：
![image](https://github.com/alibaba/easyexcel/assets/61266947/52058bb5-6104-4109-8816-b7732c67e599)
![image](https://github.com/alibaba/easyexcel/assets/61266947/1f0b6506-591a-432e-81c4-248985c09018)

**Comment by LSL1618** [comment]
根据方法名来看`setFillForegroundColor()、setFillBackgroundColor()`设置的是单元格前景色和背景色，
字体颜色需要这样设置：
```
WriteFont font = new WriteFont();
font.setFontHeightInPoints((short) 14);
font.setColor(IndexedColors.RED.getIndex());
font.setFontName("微软雅黑");
cellStyle.setWriteFont(font);
```

**Comment by mizoreyo** [comment]
> 根据方法名来看`setFillForegroundColor()、setFillBackgroundColor()`设置的是单元格前景色和背景色， 字体颜色需要这样设置：
> 
> ```
> WriteFont font = new WriteFont();
> font.setFontHeightInPoints((short) 14);
> font.setColor(IndexedColors.RED.getIndex());
> font.setFontName("微软雅黑");
> cellStyle.setWriteFont(font);
> ```

非常感谢(●'◡'●)
