### ISSUE TITLE
使用fill填充配合CellWriteHandler无法实现针对某个满足条件的单元格设置样式

### ISSUE THREAD

**Issue by a54620456** [alibaba/easyexcel#3704]
我现在使用的版本是3.2.1。
我使用了fill进行填充表格，然后配合CellWriteHandler来实现对我填充的数据。如果该数据包含某个字符串就将当前单元格进行加粗。

目前发现，无法实现这个效果。结果有两个，针对不同的代码实现。要么都不加粗，要么全都加粗。不会针对某个单元格进行单独的处理。

![1709005352292](https://github.com/alibaba/easyexcel/assets/43132650/64899c53-e400-4474-b5ee-3acd276871b8)
这是全部都加粗。
图1中的font.setBold(fales)。实际上是写的true，这里是我自己改错了。与我提交的issue无关
![1709005392525](https://github.com/alibaba/easyexcel/assets/43132650/fc803d4a-4167-4ae4-8f8e-1e951affd5db)
全部不加粗的代码实际是图1中的
cell.getCellStyle().setFont(font); 
改成
CellStyle cellStyle = workbook.createCellStyle();
cellStyle.setFont(font);
cell.setCellStyle(cellStyle);

也许这是一个BUG。

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
