### ISSUE TITLE
升级poi版本

### ISSUE THREAD

**Issue by liuchangfitcloud** [alibaba/easyexcel#3709]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 建议描述
建议升级poi版本到5.2.5

**Comment by psxjoy** [comment]
Hi，we have an update to poi-5！
This issue has been completed, I will close this issue.
