### ISSUE TITLE
这写法会报流关闭异常 Stream closed

### ISSUE THREAD

**Issue by angiely1115** [alibaba/easyexcel#371]
try (InputStream inputStream = new BufferedInputStream(excel.getInputStream())) {
            ExcelReader excelReader = new ExcelReader(inputStream, null, excelListener, false);
            return excelReader;
        } catch (IOException e) {
           
        }

Caused by: java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:336)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at org.apache.poi.util.IOUtils.readFully(IOUtils.java:189)
	at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.<init>(NPOIFSFileSystem.java:298)

**Comment by fish7790714** [comment]
请 把异常复制的全一点 应该是这个工具类没关系

**Comment by angiely1115** [comment]
不好意思，是我这边的ExcelReader对象传入流对象导致的，跟工具类没有关系。抱歉。
但是这样写时没有问题：
try  {
InputStream inputStream = new BufferedInputStream(excel.getInputStream())
ExcelReader excelReader = new ExcelReader(inputStream, null, excelListener, false);
return excelReader;
} catch (IOException e) {

    }finally{
inputStream.close();
}
是jdk的问题么

**Comment by fish7790714** [comment]
try-with-resource 会自动关闭流，你用你报错的代码 .是否这样也会报错？如果报错 把excel对象如何获取的代码也贴出来
```java
try (InputStream inputStream = new BufferedInputStream(excel.getInputStream())) {
} catch (IOException e) {
    }
```

**Comment by angiely1115** [comment]
try (BufferedInputStream bufferedInputStream = new BufferedInputStream(excel.getInputStream())) {
            ExcelReader excelReader = new ExcelReader(bufferedInputStream, null, excelListener, false);
            for (Sheet sheet : excelReader.getSheets()) {
                sheet.setClazz(aClass);
                excelReader.read(sheet);
            }
        } catch (IOException e) {
            
        }
现在这样是没有问题的，之前有一个方法去获取ExcelReader对象这样就有问题

**Comment by angiely1115** [comment]
嗯 是的 多谢！
