### ISSUE TITLE
读excel返回null,总是映射不上数据

### ISSUE THREAD

**Issue by lppoi** [alibaba/easyexcel#3711]
# 异常代码
```java
@Data
@ToString
public class TakeStock {

    @ExcelProperty(index = 0)
    private String code;

    @ExcelProperty(index = 1)
    private Date create_time;

    @ExcelProperty(index = 2)
    private Integer num;

}

List<TakeStock> list=EasyExcel.read(basePath+File.separator+"工作1.xlsx").head(TakeStock.class).sheet().doReadSync();
for (TakeStock data : list) {
     System.out.println(JSON.toJSONString(data));
}
```
# 问题描述
### 依赖
jdk21
easyexcel3.3.3

### Excel
![image](https://github.com/alibaba/easyexcel/assets/64509267/ac370d0d-de2b-48c2-8026-7308fedf64db)

获取的数据总是null
![image](https://github.com/alibaba/easyexcel/assets/64509267/104cb9bc-31c1-4854-9e43-4854b0c3c4e3)

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
