### ISSUE TITLE
使用EasyExcel.read读取EasyExcel.write导出的文件会重复读取

### ISSUE THREAD

**Issue by qingyu910** [alibaba/easyexcel#3714]
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 使用EasyExcel.read读取EasyExcel.write导出的文件会重复读取
最开始是使用3.2.1版本，读取easyexcel刚导出的多sheet文件，发现每个sheet都读取了两遍，读出的数据也是重复的，
当文件被OfficeExcel重新保存后，读取正常且读取数据正常。后面更新到3.3.3版本，仍能复现。
# 触发Bug的代码
```java
// EasyExcel.write
List<List<String>> head = new ArrayList<>();
head.add(CollUtil.newArrayList("title1"));
List<List<String>> data = new ArrayList<>();
data.add(CollUtil.newArrayList("data1"));
EasyExcel.write("D:\\test.xlsx").head(head).sheet("sheet1").doWrite(data);

//EasyExcel.read
log.info(JSON.toJSONString(EasyExcel.read("D:\\test.xlsx").doReadAllSync()));
```
# 提示的异常或者没有达到的效果
写入的log：
```log
21:29:30.020 [main] DEBUG reactor.util.Loggers - Using Slf4j logging framework
21:29:30.026 [main] DEBUG reactor.core.publisher.Hooks - Enabling stacktrace debugging via onOperatorDebug
21:29:30.213 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Begin to Initialization 'WriteContextImpl'
21:29:30.225 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is STRING
21:29:30.297 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - CurrentConfiguration is writeWorkbookHolder
21:29:30.656 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Initialization 'WriteContextImpl' complete
21:29:30.658 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is STRING
21:29:30.661 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - CurrentConfiguration is writeSheetHolder
21:29:30.662 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Can not find sheet:null ,now create it
21:29:30.778 [main] INFO com.alibaba.excel.write.metadata.holder.WriteWorkbookHolder - create new style:com.alibaba.excel.write.metadata.style.WriteCellStyle@984f0a58,null
21:29:30.861 [main] INFO com.alibaba.excel.util.StyleUtil - create new font:com.alibaba.excel.write.metadata.style.WriteFont@e747bd82,null
21:29:30.971 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Finished write.
```
读取的log:
```log
21:30:48.110 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is NONE
21:30:48.156 [main] DEBUG com.alibaba.excel.context.AnalysisContextImpl - Initialization 'AnalysisContextImpl' complete
21:30:48.236 [main] DEBUG com.alibaba.excel.cache.selector.SimpleReadCacheSelector - Use map cache.size:138
21:30:48.526 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is NONE
21:30:48.526 [main] DEBUG com.alibaba.excel.context.AnalysisContextImpl - Began to read：com.alibaba.excel.read.metadata.holder.xlsx.XlsxReadSheetHolder@e4325fe5
21:30:48.594 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is NONE
21:30:48.595 [main] DEBUG com.alibaba.excel.context.AnalysisContextImpl - Began to read：com.alibaba.excel.read.metadata.holder.xlsx.XlsxReadSheetHolder@e65685ba
21:30:48.653 [main] INFO com.***.util - [{0:"data1"},{0:"data1"}]
```

**Comment by ET-stack** [comment]
我去重现了一下，没能重现，我试过3.3.3和3.2.1版本
代码如下
`    // EasyExcel.write
        List<List<String>> head = new ArrayList<>();
        List<String> strings = new ArrayList<>();
        strings.add("title1");
        head.add(strings);
        List<List<String>> data = new ArrayList<>();
        List<String> datas = new ArrayList<>();
        datas.add("data1");
        data.add(datas);
        EasyExcel.write("E:\\test1.xlsx").head(head).sheet("sheet1").doWrite(data);
        log.info(JSON.toJSONString(JSON.toJSONString(EasyExcel.read("E:\\test1.xlsx").doReadAllSync())));`
        
        
        日志如下
`14:15:50.116 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Begin to Initialization 'WriteContextImpl'
14:15:50.116 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is STRING
14:15:50.167 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - CurrentConfiguration is writeWorkbookHolder
14:15:50.452 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Initialization 'WriteContextImpl' complete
14:15:50.452 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is STRING
14:15:50.452 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - CurrentConfiguration is writeSheetHolder
14:15:50.452 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Can not find sheet:null ,now create it
14:15:50.564 [main] INFO com.alibaba.excel.write.metadata.holder.WriteWorkbookHolder - create new style:com.alibaba.excel.write.metadata.style.WriteCellStyle@449430ca,null
14:15:50.578 [main] INFO com.alibaba.excel.util.StyleUtil - create new font:com.alibaba.excel.write.metadata.style.WriteFont@e747bd82,null
14:15:50.709 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Finished write.
14:15:50.709 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is NONE
14:15:50.722 [main] DEBUG com.alibaba.excel.context.AnalysisContextImpl - Initialization 'AnalysisContextImpl' complete
14:15:50.740 [main] DEBUG com.alibaba.excel.cache.selector.SimpleReadCacheSelector - Use map cache.size:138
14:15:50.753 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is NONE
14:15:50.753 [main] DEBUG com.alibaba.excel.context.AnalysisContextImpl - Began to read：com.alibaba.excel.read.metadata.holder.xlsx.XlsxReadSheetHolder@8d733910
14:15:50.885 [main] INFO com.example.business.BusinessExampleApplicationTests - "[{0:\"data1\"}]"

Process finished with exit code 0
`


`

**Comment by ET-stack** [comment]
**我已经在3.2.1和3.3.3版本测试以下代码，均没有重现出打印两次，并且Excel内sheet也是多个**

```
List<List<String>> head = new ArrayList<>();
List<String> strings = new ArrayList<>();
strings.add("title1");
head.add(strings);
List<List<String>> data = new ArrayList<>();
List<String> datas = new ArrayList<>();
datas.add("data1");
data.add(datas);
EasyExcel.write("E:\\test1.xlsx").head(head).sheet("sheet1").doWrite(data);
log.info(JSON.toJSONString(JSON.toJSONString(EasyExcel.read("E:\\test1.xlsx").doReadAllSync())));
```

**所打印日志**

```
14:15:50.116 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Begin to Initialization 'WriteContextImpl'
14:15:50.116 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is STRING
14:15:50.167 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - CurrentConfiguration is writeWorkbookHolder
14:15:50.452 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Initialization 'WriteContextImpl' complete
14:15:50.452 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is STRING
14:15:50.452 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - CurrentConfiguration is writeSheetHolder
14:15:50.452 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Can not find sheet:null ,now create it
14:15:50.564 [main] INFO com.alibaba.excel.write.metadata.holder.WriteWorkbookHolder - create new style:com.alibaba.excel.write.metadata.style.WriteCellStyle@449430ca,null
14:15:50.578 [main] INFO com.alibaba.excel.util.StyleUtil - create new font:com.alibaba.excel.write.metadata.style.WriteFont@e747bd82,null
14:15:50.709 [main] DEBUG com.alibaba.excel.context.WriteContextImpl - Finished write.
14:15:50.709 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is NONE
14:15:50.722 [main] DEBUG com.alibaba.excel.context.AnalysisContextImpl - Initialization 'AnalysisContextImpl' complete
14:15:50.740 [main] DEBUG com.alibaba.excel.cache.selector.SimpleReadCacheSelector - Use map cache.size:138
14:15:50.753 [main] DEBUG com.alibaba.excel.metadata.property.ExcelHeadProperty - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is NONE
14:15:50.753 [main] DEBUG com.alibaba.excel.context.AnalysisContextImpl - Began to read：com.alibaba.excel.read.metadata.holder.xlsx.XlsxReadSheetHolder@8d733910
14:15:50.885 [main] INFO com.example.business.BusinessExampleApplicationTests - "[{0:\"data1\"}]"



```

**Comment by qingyu910** [comment]
好的，感谢回复。
我单独新建了一个纯净的项目，重新测试了发现是确实是正常的。同一个导出的文件，在我当前工作的项目中依然会出现重复读取，在新项目中是正常的，这个我自己排查下吧，谢谢。
