### ISSUE TITLE
maven库中版本StyleUtil类报错

### ISSUE THREAD

**Issue by jeremy7xu** [alibaba/easyexcel#374]
public static CellStyle buildDefaultCellStyle(Workbook workbook) 中的newCellStyle.setVerticalAlignment(VerticalAlignment.CENTER)这一句传入的参数枚举，但是要求的是Short类型？

**Comment by fish7790714** [comment]
是否你自己还引入了 其他poi版本 3.17 版本 入参是枚举

**Comment by jeremy7xu** [comment]
可能使这个原因  我试试

**Comment by jeremy7xu** [comment]
> 是否你自己还引入了 其他poi版本 3.17 版本 入参是枚举

有可能是这个原因

**Comment by fish7790714** [comment]
可以尝试使用 `mvn dependency:tree` 命令查看依赖树 确保 poi版本是3.17

**Comment by jeremy7xu** [comment]
> 可以尝试使用 `mvn dependency:tree` 命令查看依赖树 确保 poi版本是3.17

谢谢
