### ISSUE TITLE
poi-ooxml4.1.2现在有漏洞，需要升级到5.2.1以上，升级后导出报错

### ISSUE THREAD

**Issue by mc243410633** [alibaba/easyexcel#3742]
![2024-03-28_171429](https://github.com/alibaba/easyexcel/assets/26464190/4f26f5d9-215c-4b9c-a638-c91f83956e86)
![2024-03-28_171400](https://github.com/alibaba/easyexcel/assets/26464190/754581f9-25fa-4800-a6bc-293249c8a47f)
![2024-03-28_171346](https://github.com/alibaba/easyexcel/assets/26464190/4c28b435-a35d-491c-8fd3-3061f28e12d2)
![2024-03-28_171331](https://github.com/alibaba/easyexcel/assets/26464190/7dc13ea8-be67-41ff-a44e-25037360532a)

查看了下资料
按照如下文档建议的解决方法还是不生效
![2024-03-28_171537](https://github.com/alibaba/easyexcel/assets/26464190/62c7d583-61cf-42b6-aa0b-26d132e0e9c6)

**Comment by LSL1618** [comment]
我的是这样的，正常使用
```
            <!--easyexcel-->
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>3.3.4</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.poi</groupId>
                        <artifactId>poi</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.poi</groupId>
                        <artifactId>poi-ooxml</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.poi</groupId>
                        <artifactId>poi-ooxml-schemas</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <!--poi 5+ 需要单独引入-->
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>2.22.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>5.2.5</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>5.2.5</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml-schemas</artifactId>
                <version>4.1.2</version>
            </dependency>
```

**Comment by mc243410633** [comment]
感谢



***@***.***
 
发件人： LSL1618
发送时间： 2024-04-12 10:04
收件人： alibaba/easyexcel
抄送： 马小忙; Author
主题： Re: [alibaba/easyexcel] poi-ooxml4.1.2现在有漏洞，需要升级到5.2.1以上，升级后导出报错 (Issue #3742)
我的是这样的，正常使用
            
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>3.3.4</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.poi</groupId>
                        <artifactId>poi</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.poi</groupId>
                        <artifactId>poi-ooxml</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.poi</groupId>
                        <artifactId>poi-ooxml-schemas</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>2.22.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>5.2.5</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-api</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>5.2.5</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml-schemas</artifactId>
                <version>4.1.2</version>
            </dependency>

―

**Comment by psxjoy** [comment]
Hi, we have an update to poi-5！
This issue has been completed, I will close this issue.
