### ISSUE TITLE
Excel to PDF Page Size Issue

### ISSUE THREAD

**Issue by Sarsewar** [alibaba/easyexcel#3747]
Please find attached [Demo_Excel.xlsx](https://github.com/exceljs/exceljs/files/14717537/Demo_Excel.xlsx), which we are currently using to convert to PDF. The conversion process is being conducted directly on DocuSign. However, we've encountered issues regarding page size and scaling, as illustrated in the screenshots below. Despite attempting conversion through other online free platforms specializing in direct XLSX to PDF conversion, we've encountered the same issues. Notably, the same Excel file converts correctly using Microsoft's "Save As" or "Print" functionality.

We have explored various combinations in the worksheet's XML, including adjustments to pageSize, scale, fitToWidth, and fitToHeight, yet none have proven successful. We seek your insights into the possible reasons for these challenges.

fitToPage | fitToWidth | fitToHeight | Scale
-- | -- | -- | --
0 | 0 | 0 | 0
0 | 0 | 0 | 1
0 | 0 | 1 | 0
0 | 0 | 1 | 1
0 | 1 | 1 | 1
0 | 1 | 0 | 1
0 | 1 | 1 | 0
0 | 1 | 0 | 0
1 | 0 | 0 | 0
1 | 0 | 0 | 1
1 | 0 | 1 | 0

![image](https://github.com/exceljs/exceljs/assets/26505197/1a890475-5121-4752-92a8-fabed22168b0)

Your guidance in resolving this matter is greatly appreciated.

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
