### ISSUE TITLE
弱问有没有回调的办法、通过sheet名称定位sheet的办法?

### ISSUE THREAD

**Issue by loooog** [alibaba/easyexcel#375]
如题：
有没有办法遇到某一行就退出终止呢？
能否通过sheet名称定位sheet呢？

**Comment by fish7790714** [comment]
1. 目前我看没有专门的退出终止。抛异常可以处理，但是不建议，建议直接读取到标记数据后，后面的不处理即可，性能影响不大。
2. 看了源码 不支持 只能id 定位

**Comment by loooog** [comment]
嗯，我现在的做法是弄个exit变量，后面的invoke直接返回了，不过总感觉怪怪的

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
