### ISSUE TITLE
导出的Excel，在Excel中点击千分位按钮时，格式会被清除，无法转成千分位格式

### ISSUE THREAD

**Issue by zlsfaith** [alibaba/easyexcel#3752]
FillData中有个字段BigDecimal qty;
模版用的是office 2019 xlsx，easyexcel版本：3.3.4
导出到Excel中可以正常显示，但是在Excel中点击千分位按钮时
1.原先的格式会被清除（office打开）
2.数值无法转成千分位表示形式（office打开）
3.将导出的excel内容复制到新建的excel中，点击千分位按钮可以正常转换（office打开）
4.导出的excel用wps打开，点击千分位按钮也可以正常转换（wps打开）

**Comment by zlsfaith** [comment]
@zhuangjiaju 大佬帮忙看看呀

**Comment by psxjoy** [comment]
@zlsfaith 能提供demo吗？或者该issue已经解决？

**Comment by psxjoy** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue。

**Comment by zlsfaith** [comment]
点击千分位后，单元格的数据格式也会清除
