### ISSUE TITLE
单元格中含有html样式代码导出

### ISSUE THREAD

**Issue by lyon-liang** [alibaba/easyexcel#3757]
# 问题描述
导出的单元格中含有html样式代码,可以转成excel的样式导出吗

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
