### ISSUE TITLE
@ColumnWidth 无效

### ISSUE THREAD

**Issue by Juncheng210** [alibaba/easyexcel#3782]
# 触发场景描述
使用 3.3.4 版本
列名为英文字母时设置列宽无效，使用了“A”、“AA”、“a”等方式@ColumnWidth均未生效
# 触发Bug的代码
```java
    @ExcelProperty("A")
    @ColumnWidth(10)
    private Integer gradeA;
```
# 提示的异常或者没有达到的效果
<img width="173" alt="image" src="https://github.com/alibaba/easyexcel/assets/24565491/174fad16-1583-4d8a-891d-a28d485f63b5">

**Comment by jieyangxchen** [comment]
# 复现

环境：macOS
easyexcel版本：3.3.4 
jdk：8、21
根据代码：
```java
    @ExcelProperty("A")
    @ColumnWidth(10)
    private Integer gradeA;
```
未复现op所说列名为英文字母时设置列宽无效

# 补充
请补充运行环境，以及完整的代码

**Comment by jieyangxchen** [comment]
不知道您是否还存在问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue。
