### ISSUE TITLE
poi-ooxml-schemas 存在漏洞

### ISSUE THREAD

**Issue by Yannis-01** [alibaba/easyexcel#3798]
# 问题描述
社区最新版3.3.4依赖的 poi-ooxml-schemas 存在漏洞且超期, 请问如何解决, 后续是否有替换的计划?

**Comment by LSL1618** [comment]
[https://easyexcel.opensource.alibaba.com/qa/#%E5%85%B3%E4%BA%8E%E7%89%88%E6%9C%AC%E9%80%89%E6%8B%A9](https://easyexcel.opensource.alibaba.com/qa/#%E5%85%B3%E4%BA%8E%E7%89%88%E6%9C%AC%E9%80%89%E6%8B%A9)

**Comment by LSL1618** [comment]
4.1.2已经是最新的了
```
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml-schemas</artifactId>
    <version>4.1.2</version>
</dependency>
```

**Comment by psxjoy** [comment]
easyexcel-3.3.4 版本依赖的 poi-ooxml-schemas已经是最新的4.1.2版本了。
从5.0.X开始，poi-ooxml-schemas 被重命名为 poi-ooxml-full，应该近期不会有升级。

下面是easyexcel-core 中的依赖：
```xml
  <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml-schemas</artifactId>
      <version>4.1.2</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by psxjoy** [comment]
Hi， we have an update to poi-5！
This issue has been completed, I will close this issue.
