### ISSUE TITLE
模板填充时表格样式问题

### ISSUE THREAD

**Issue by xiaoluoluoluo** [alibaba/easyexcel#3806]
# 异常代码
```java
    public void ExportContract(HttpServletResponse response,@RequestParam("file") MultipartFile file) throws IOException {
        String fileName = "contract";
        File tempFile = File.createTempFile("uploaded-file", file.getOriginalFilename());
        file.transferTo(tempFile);
        response.setHeader("Content-disposition", "attachment;filename = " + fileName + ".xlsx");
        System.out.println(getDate());

        try (ExcelWriter excelWriter = EasyExcel.write(response.getOutputStream()).withTemplate(tempFile).registerWriteHandler(new CellHandler()).build()) {
            WriteSheet writeSheet = EasyExcel.writerSheet().build();
            FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.TRUE).build();
            excelWriter.fill(getDate(),writeSheet);
            excelWriter.fill(new FillWrapper("item",getDate().getItems()), fillConfig,writeSheet);
           //用来测试其他备注
            excelWriter.fill(new FillWrapper("it",getDate().getItems()),fillConfig,writeSheet);
        }
}
```
# 异常提示
其他备注模块的格式异常
![微信截图_20240524104127](https://github.com/alibaba/easyexcel/assets/141432852/b33fb938-04ce-4536-bb04-426ca8d1d75b)
希望样式：
![image](https://github.com/alibaba/easyexcel/assets/141432852/c89bc538-4165-47a6-a543-1eecab966f6d)
如何解决

**Comment by psxjoy** [comment]
参考 [WriteCellStyle](https://github.com/alibaba/easyexcel/blob/master/easyexcel-core/src/main/java/com/alibaba/excel/write/metadata/style/WriteCellStyle.java)

**Comment by xiaoluoluoluo** [comment]
> 参考 [WriteCellStyle](https://github.com/alibaba/easyexcel/blob/master/easyexcel-core/src/main/java/com/alibaba/excel/write/metadata/style/WriteCellStyle.java)
![image](https://github.com/alibaba/easyexcel/assets/141432852/8786c216-3d1c-44fa-a226-9d590eb5ca10)
大佬，不是很会用你发的这个，我现在样式会这样，怎么让他们都在一个方框中

**Comment by psxjoy** [comment]
未提供完整数据，临时写个demo做验证，有问题自行修改里面的小逻辑。
example :
1. 自定义拦截器
```java
public class CustomCellWriteHandler implements CellWriteHandler {
    //数据总数
    int total = 0;

    public CustomCellWriteHandler(int total) {
        this.total = total;
    }

    @Override
    public void afterCellDispose(CellWriteHandlerContext context) {
        int rowIndex = context.getRowIndex();
        int columnIndex = context.getColumnIndex();
        //如果是首行,边框-上-左-右增加实线，下边框为NONE
        if (rowIndex == 1) {
            WriteCellData<?> writeCellData = context.getFirstCellData();
            WriteCellStyle customCellStyle = new WriteCellStyle();
            customCellStyle.setBorderTop(BorderStyle.MEDIUM);
            customCellStyle.setBorderBottom(BorderStyle.NONE);
            customCellStyle.setBorderLeft(BorderStyle.MEDIUM);
            customCellStyle.setBorderRight(BorderStyle.MEDIUM);
            WriteCellStyle.merge(customCellStyle, writeCellData.getOrCreateStyle());
            //如果是尾行,边框下-左-右增加实线，上边框为NONE
        } else if (rowIndex == total) {
            WriteCellData<?> writeCellData = context.getFirstCellData();
            WriteCellStyle customCellStyle = new WriteCellStyle();
            customCellStyle.setBorderBottom(BorderStyle.MEDIUM);
            customCellStyle.setBorderTop(BorderStyle.NONE);
            customCellStyle.setBorderLeft(BorderStyle.MEDIUM);
            customCellStyle.setBorderRight(BorderStyle.MEDIUM);
            WriteCellStyle.merge(customCellStyle, writeCellData.getOrCreateStyle());
        } else {
            //中间行保持左右边框实线即可
            WriteCellData<?> writeCellData = context.getFirstCellData();
            WriteCellStyle customCellStyle = new WriteCellStyle();
            customCellStyle.setBorderBottom(BorderStyle.NONE);
            customCellStyle.setBorderTop(BorderStyle.NONE);
            customCellStyle.setBorderLeft(BorderStyle.MEDIUM);
            customCellStyle.setBorderRight(BorderStyle.MEDIUM);
            WriteCellStyle.merge(customCellStyle, writeCellData.getOrCreateStyle());
        }

    }
}
```
2. 写入时注册该拦截器
```JAVA
 WriteSheet writeSheet = EasyExcel.writerSheet(0, "Sheet1")
//注册自定义拦截器，参数为数据量
                .registerWriteHandler(new CustomCellWriteHandler(list.size()))
                .build();
```

**Comment by xiaoluoluoluo** [comment]
> 未提供完整数据，临时写个demo做验证，有问题自行修改里面的小逻辑。 example :
> 
> 1. 自定义拦截器
> 
> ```java
> public class CustomCellWriteHandler implements CellWriteHandler {
>     //数据总数
>     int total = 0;
> 
>     public CustomCellWriteHandler(int total) {
>         this.total = total;
>     }
> 
>     @Override
>     public void afterCellDispose(CellWriteHandlerContext context) {
>         int rowIndex = context.getRowIndex();
>         int columnIndex = context.getColumnIndex();
>         //如果是首行,边框-上-左-右增加实线，下边框为NONE
>         if (rowIndex == 1) {
>             WriteCellData<?> writeCellData = context.getFirstCellData();
>             WriteCellStyle customCellStyle = new WriteCellStyle();
>             customCellStyle.setBorderTop(BorderStyle.MEDIUM);
>             customCellStyle.setBorderBottom(BorderStyle.NONE);
>             customCellStyle.setBorderLeft(BorderStyle.MEDIUM);
>             customCellStyle.setBorderRight(BorderStyle.MEDIUM);
>             WriteCellStyle.merge(customCellStyle, writeCellData.getOrCreateStyle());
>             //如果是尾行,边框下-左-右增加实线，上边框为NONE
>         } else if (rowIndex == total) {
>             WriteCellData<?> writeCellData = context.getFirstCellData();
>             WriteCellStyle customCellStyle = new WriteCellStyle();
>             customCellStyle.setBorderBottom(BorderStyle.MEDIUM);
>             customCellStyle.setBorderTop(BorderStyle.NONE);
>             customCellStyle.setBorderLeft(BorderStyle.MEDIUM);
>             customCellStyle.setBorderRight(BorderStyle.MEDIUM);
>             WriteCellStyle.merge(customCellStyle, writeCellData.getOrCreateStyle());
>         } else {
>             //中间行保持左右边框实线即可
>             WriteCellData<?> writeCellData = context.getFirstCellData();
>             WriteCellStyle customCellStyle = new WriteCellStyle();
>             customCellStyle.setBorderBottom(BorderStyle.NONE);
>             customCellStyle.setBorderTop(BorderStyle.NONE);
>             customCellStyle.setBorderLeft(BorderStyle.MEDIUM);
>             customCellStyle.setBorderRight(BorderStyle.MEDIUM);
>             WriteCellStyle.merge(customCellStyle, writeCellData.getOrCreateStyle());
>         }
> 
>     }
> }
> ```
> 
> 2. 写入时注册该拦截器
> 
> ```java
>  WriteSheet writeSheet = EasyExcel.writerSheet(0, "Sheet1")
> //注册自定义拦截器，参数为数据量
>                 .registerWriteHandler(new CustomCellWriteHandler(list.size()))
>                 .build();
> ```

好的，谢谢大佬
