### ISSUE TITLE
excel 导出日期格式筛选问题 

### ISSUE THREAD

**Issue by of0** [alibaba/easyexcel#3813]
异常提示
easyexcel 2.2.6
使用的数据
![image
](https://user-images.githubusercontent.com/27794583/106219279-05234e80-6214-11eb-8950-7861c457624e.png)

如果您使用过excel的日期排序, 它应该是这样的
![image
](https://user-images.githubusercontent.com/27794583/106219263-ff2d6d80-6213-11eb-8d9b-11065fb4e0c4.png)

但是使用easyexcel 导出之后, excel筛选居然是这样的，只有双击单元格后才正常

![img](https://user-images.githubusercontent.com/27794583/106219404-3a2fa100-6214-11eb-8375-02f45e1b3078.png
)

目前多种尝试, 除非双击单元格, 不然导出的excel日期类型筛选都不是想要的, 请问一下这个有好的解决方案么

**Comment by psxjoy** [comment]
参考 [日期数字或者自定义格式转换](https://easyexcel.opensource.alibaba.com/docs/current/quickstart/write#日期数字或者自定义格式转换)  
Not a bug,change to `help wanted` tag.

**Comment by of0** [comment]
是按照日期格式写的
@DateTimeFormat("yyyy年MM月dd日HH时mm分ss秒")
    @ExcelProperty("日期标题")
    private Date date;

还是导出没有办法按日期筛选

**Comment by psxjoy** [comment]
能提供一个可以运行的demo吗？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: CoderXin ***@***.***>
发送时间: Thursday, May 30, 2024 9:45:30 AM
收件人: alibaba/easyexcel ***@***.***>
抄送: Black Pan ***@***.***>; Comment ***@***.***>
主题: Re: [alibaba/easyexcel] excel 导出日期格式筛选问题 (Issue #3813)


是按照日期格式写的
@DateTimeFormat("yyyy年MM月dd日HH时mm分ss秒")
@ExcelProperty("日期标题")
private Date date;

还是导出没有办法按日期筛选

―

**Comment by of0** [comment]
其实直接用你们的示例就行。


	@Test
	public void test5() {
		
		String fileName = "/Users/zjx/Downloads/converterWrite" + System.currentTimeMillis() + ".xlsx";
		// 这里 需要指定写用哪个class去写，然后写到第一个sheet，名字为模板 然后文件流会自动关闭
		
		List<ConverterData> data = new ArrayList<>();
		data.add(new ConverterData(new Date(1717034452040L)));
		data.add(new ConverterData(new Date(1717854452040L)));
		data.add(new ConverterData(new Date(1717012452040L)));
		data.add(new ConverterData(new Date(1717036652040L)));
		EasyExcel.write(fileName, ConverterData.class).sheet("模板").doWrite(data);
		
	}


@Data
@EqualsAndHashCode
class ConverterData {
	
	/**
	 * 我想写到excel 用年月日的格式
	 */
	@DateTimeFormat("yyyy/MM/dd")
	@ExcelProperty("日期标题")
	private Date date;
	
	public ConverterData(Date date) {
		this.date = date;
	}
	
}

**Comment by of0** [comment]
这段代码运行后生成的 excel 点筛选就是这个效果：
<img width="328" alt="image" src="https://github.com/alibaba/easyexcel/assets/37819737/f36d344f-ece7-4fa6-94db-c6f79e291ccb">
双击单元格以后才能按照日期筛选：
<img width="404" alt="image" src="https://github.com/alibaba/easyexcel/assets/37819737/dce32993-c0cb-478d-b36a-74b1969980be">

**Comment by of0** [comment]
是版本问题吗？我用的是easyexcel 2.2.6

**Comment by psxjoy** [comment]
建议升到最新版，或者 3.1.0+ 版本。
按照升级路径，2.2.x版本已经弃用了
> 不推荐项目新引入此版本，除非是 jdk6，否则不推荐使用，除非超级严重bug，否则不再更新

**Comment by of0** [comment]
确认了，是版本问题，升级到 3.3.1版本好了。
谢谢！

**Comment by psxjoy** [comment]
________________________________
发件人: CoderXin ***@***.***>
发送时间: 2024年5月30日 11:12
收件人: alibaba/easyexcel ***@***.***>
抄送: Black Pan ***@***.***>; Comment ***@***.***>
主题: Re: [alibaba/easyexcel] excel 导出日期格式筛选问题 (Issue #3813)


确认了，是版本问题，升级到 3.3.1版本好了。
谢谢！

―

**Comment by psxjoy** [comment]
It is not a bug, please change it to the `help wanted` tag. @zhuangjiaju

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.
