### ISSUE TITLE
建议将底层依赖的版本进行升级，因为目前使用的版本存在很多安全漏洞

### ISSUE THREAD

**Issue by troyzhxu** [alibaba/easyexcel#3815]
首先感谢作者提供这么好用的框架，但目前底层依赖的版本普遍较低，建议升级：

![image](https://github.com/alibaba/easyexcel/assets/29403889/813cad2d-1a9f-4f2a-8a11-bae2175a198f)

低版本的依赖有很多都存在安全漏洞，例如 `org.apache.poi:poi:4.1.2`：

![1716946867430](https://github.com/alibaba/easyexcel/assets/29403889/ef280d34-ed57-4f1e-a5f7-c3970aee2c1f)

希望作者能进行升级。

**Comment by psxjoy** [comment]
Hi, we have an update to poi-5！
This issue has been completed, I will close this issue.
