### ISSUE TITLE
easyexcel导入多行，读取不到数据

### ISSUE THREAD

**Issue by wuwei0727** [alibaba/easyexcel#3816]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
springboot：2.7.12。
maven：
![PixPin_2024-05-29_14-12-26](https://github.com/alibaba/easyexcel/assets/100761249/06798876-8c05-4be1-86e3-fb757e1cfdf6)

我导入一个多sheet的xlsx表格，里面有多行数据但是只读取了第一个，后面读取不到。
xlxs文件：
[展位模板 (5).xlsx](https://github.com/alibaba/easyexcel/files/15479000/5.xlsx)

# 触发Bug的代码
实体类：
![image](https://github.com/alibaba/easyexcel/assets/100761249/339e147b-d0be-4ccc-8c9d-9acae8a260c1)
```java
代码：
     @PostMapping("import/zhanWei")
    public R<Object> importZhanWei(HttpServletResponse response, @RequestPart(value = "file") MultipartFile file) throws IOException {
        List<ZhanWeiVo> userList = EasyExcel.read(file.getInputStream())
                .head(ZhanWeiVo.class)
                .sheet()
                .doReadSync();
}
```
# 提示的异常或者没有达到的效果
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
![error](https://github.com/alibaba/easyexcel/assets/100761249/40bd3b8c-07a4-485c-a632-4ac123b35293)

**Comment by psxjoy** [comment]
读取到了2行数据，看模板里的数据没问题啊。

如果要读取多个sheet页里面的数据，用`doReadAll()`，参考[读多个sheet](https://easyexcel.opensource.alibaba.com/docs/current/quickstart/read#读多个sheet)

**Comment by wuwei0727** [comment]
我不是读取多个sheet。我是读第一个sheet的数据，都读不完整

**Comment by psxjoy** [comment]
> 模版数据没问题为什么会读不完整？

不完整的数据具体指的是什么？

**Comment by wuwei0727** [comment]
为什么第一行可以读到？而第二行就读不到，后面都读不到，这是为什么？我不是读多个sheet，我只读sheet1的数据都读不到啊

**Comment by psxjoy** [comment]
以官方demo为示例，重写`ReadListener`的`invoke`函数，增加下面的逻辑：
```java
//不忽略空白行
context.readWorkbookHolder().setIgnoreEmptyRow(false);
```
result:
![Snipaste_2024-05-29_16-16-51](https://github.com/alibaba/easyexcel/assets/10711694/5b4ffc49-f905-41ca-952b-4379d15f4a1a)

**Comment by psxjoy** [comment]
It is not a bug, change to the `help wanted` tag. @zhuangjiaju

**Comment by psxjoy** [comment]
看上去已经解决了该问题。@wuwei0727   @zhuangjiaju 麻烦关闭该issue。

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.
