### ISSUE TITLE
多层级表头创建的问题

### ISSUE THREAD

**Issue by StoneStarChan** [alibaba/easyexcel#3818]
```java
   List<List<String>> list = new ArrayList<>();
        List<String> head0 = new ArrayList<>();
        head0.add("string" + System.currentTimeMillis());
        List<String> head1 = new ArrayList<>();
        head1.add("number" + System.currentTimeMillis());
        List<String> head2 = new ArrayList<>();
        head2.add("date" + System.currentTimeMillis());
        list.add(head0);
        list.add(head1);
        list.add(head2);
```
多层级表头通过这种方式添加，使用EasyExcel.write(out)
                    .head(head)
                    .registerWriteHandler(new LongestMatchColumnWidthStyleStrategy())
                    .registerWriteHandler(horizontalCellStyleStrategy);方法不生效。请问是不能这么写吗？

**Comment by psxjoy** [comment]
EasyExcel 的 .head() 方法期望的是一个二维数组或者是实现了 Iterable 接口的对象。你提供的demo，类似于一维数组了。具体的可以参考[该篇文章](https://blog.csdn.net/qq_39084191/article/details/122842113)

**Comment by psxjoy** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue.
