### ISSUE TITLE
数值格式解析错误 负数“(100)”应该解析成-100

### ISSUE THREAD

**Issue by spt110** [alibaba/easyexcel#384]
![image](https://user-images.githubusercontent.com/5217855/58536734-fa850a80-8223-11e9-8e33-1eedfc2a78b0.png)
![image](https://user-images.githubusercontent.com/5217855/58537003-839c4180-8224-11e9-9a61-0e3f26f1a239.png)

**Comment by spt110** [comment]
带括号的负数格式“(100)”，是财务专用的

**Comment by dongjun613** [comment]
这个需要自己做处理，文档里说明了去除了很多东西。只保留最基础的数据读写

**Comment by spt110** [comment]
ok

**Comment by zhuangjiaju** [comment]
这个问题已经在`2.2.0` 里面解决
