### ISSUE TITLE
Excel单元格宽度固定，单元格内容非常多导致一个单元格显示不下所有内容，现有方法可以让单元格内容完全显示吗？多谢！

### ISSUE THREAD

**Issue by AccountGc** [alibaba/easyexcel#3852]
已经搜索过，未找到相关问题 谢谢

**Comment by AccountGc** [comment]
例如：调用某个方法可以检测溢出的数据，并且合并单元格

**Comment by psxjoy** [comment]
xlsx本质上来说是一个xml文件，没办法做这种动态检测。只能说你预估一个值，超过这个长度，固定增加宽度。

**Comment by LSL1618** [comment]
一个是重设单元格列宽，一个是重设单元格行高，根据单元格内容的字符长度，来预估一个宽度或高度。

**Comment by AccountGc** [comment]
> xlsx本质上来说是一个xml文件，没办法做这种动态检测。只能说你预估一个值，超过这个长度，固定增加宽度。

多谢

**Comment by AccountGc** [comment]
> 一个是重设单元格列宽，一个是重设单元格行高，根据单元格内容的字符长度，来预估一个宽度或高度。

多谢
