### ISSUE TITLE
版本3.1.1，EasyExcel导出支持千分位

### ISSUE THREAD

**Issue by YangJingf** [alibaba/easyexcel#3853]
**1、Maven依赖**
```
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>3.1.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>poi-ooxml-schemas</artifactId>
                    <groupId>org.apache.poi</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

2、实体类
```
    @DateTimeFormat("#,##0.00")
    private BigDecimal endNetValue;
```
或者
  ```
  @NumberFormat("#,###.00")
    private BigDecimal endNetValue;
```
都没有千分位效果
![image](https://github.com/alibaba/easyexcel/assets/33126647/92d1bc0d-dee7-492e-a7ff-a8de683c81bd)

**Comment by YangJingf** [comment]
难道是数值的类型要double才可以吗

**Comment by psxjoy** [comment]
跑了一下官方demo，显示是正常。建议升级版本到3.3.4+。

![image](https://github.com/alibaba/easyexcel/assets/10711694/3bdb82b9-7205-4379-8778-6d85ed487239)

**Comment by YangJingf** [comment]
> 跑了一下官方demo，显示是正常。建议升级版本到3.3.4+。
> 
> ![image](https://private-user-images.githubusercontent.com/10711694/342653851-3bdb82b9-7205-4379-8778-6d85ed487239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5OTI4NDMsIm5iZiI6MTcxOTk5MjU0MywicGF0aCI6Ii8xMDcxMTY5NC8zNDI2NTM4NTEtM2JkYjgyYjktNzIwNS00Mzc5LTg3NzgtNmQ4NWVkNDg3MjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDA3NDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YTI1Mzk2MWIzZTVjOWFkMmQyYWQzMTljZTI0YWNhOGRhMGY2ZjdhNzEzZjhkOWIzMGU2MGJhMGE4MmZkZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oxA0onQ05tCqPYe6qMC0ic_y8Fg_5FymvODc77v-A8Y)
已经升级到3.3.4，还是不行
` <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>3.3.4</version>
            <exclusions>
                <exclusion>
                    <artifactId>poi-ooxml-schemas</artifactId>
                    <groupId>org.apache.poi</groupId>
                </exclusion>
            </exclusions>
        </dependency>`

**Comment by YangJingf** [comment]
升级到3.3.4之后还是没效果
xml：
`      <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>3.3.4</version>
            <exclusions>
                <exclusion>
                    <artifactId>poi-ooxml-schemas</artifactId>
                    <groupId>org.apache.poi</groupId>
                </exclusion>
            </exclusions>
        </dependency>`
java实体类：
`   /**
     * 资产账面净值
     */
    @NumberFormat("#,###.00")
    @ExcelProperty(value = "资产账面净值")
    private BigDecimal netBookValue;`

**Comment by sch1446795386** [comment]
自定义一个CellWriteHandler可以实现

**Comment by YangJingf** [comment]
这个问题解决了，主要是通过继承LongestMatchColumnWidthStyleStrategy的方式，也就是自定义CellWriteHandler。
关键代码如下：
` if ((num = cellStyleMap.get(context.getColumnIndex())) != null) {
            DataFormat format = workbook.createDataFormat();
            short dataFormat = format.getFormat(BuiltinFormats.getBuiltinFormat(num));
            thousandthsCellStyle.setDataFormat(dataFormat);
            return thousandthsCellStyle;
        }`

**Comment by YangJingf** [comment]
这个问题解决了，主要是通过继承LongestMatchColumnWidthStyleStrategy的方式，也就是自定义CellWriteHandler。
关键代码如下：
````
   if ((num = cellStyleMap.get(context.getColumnIndex())) != null) {
            DataFormat format = workbook.createDataFormat();
            short dataFormat = format.getFormat(BuiltinFormats.getBuiltinFormat(num));
            thousandthsCellStyle.setDataFormat(dataFormat);
            return thousandthsCellStyle;
        }
````

cellStyleMap是为了精确控制某一列，以及其对应的单元格式值。

**Comment by psxjoy** [comment]
> 这个问题解决了，主要是通过继承LongestMatchColumnWidthStyleStrategy的方式，也就是自定义CellWriteHandler。 关键代码如下：
> 
> ```
>    if ((num = cellStyleMap.get(context.getColumnIndex())) != null) {
>             DataFormat format = workbook.createDataFormat();
>             short dataFormat = format.getFormat(BuiltinFormats.getBuiltinFormat(num));
>             thousandthsCellStyle.setDataFormat(dataFormat);
>             return thousandthsCellStyle;
>         }
> ```
> 
> cellStyleMap是为了精确控制某一列，以及其对应的单元格式值。

Good Job!

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.
