### ISSUE TITLE
导出下载成功后，发生“WPS 表格在试图打开文件时遇到错误”

### ISSUE THREAD

**Issue by zxguan2560** [alibaba/easyexcel#3887]
# 异常提示
前端导出下载成功后，发生“WPS 表格在试图打开文件时遇到错误”问题

# 问题描述
前后端分离项目，后端代码完成后，亲测 Postman 下载并 WPS 打开无问题，但是前端下载之后 WPS 无法正常打开。由于前端公共组件库，且异地沟通不太明确，故而怀疑其他原因导致。

# 问题原因
前端 POST 模拟下载，需要指定 responseType: "blob"，否则就可能出现 WPS 无法打开文件的问题

**Comment by psxjoy** [comment]
业务代码，无法提供有效的帮助。有可能是环境问题、WPS问题、代码问题等。
建议前端提供一个页面，专门给后端下载测试使用。

**Comment by zxguan2560** [comment]
嗯嗯，此处只是帮助大家解决此类问题，谢谢

**Comment by psxjoy** [comment]
很优秀的issue ，谢谢你的反馈和回复。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zxguan2560 ***@***.***>
发送时间: Wednesday, July 17, 2024 12:28:29 AM
收件人: alibaba/easyexcel ***@***.***>
抄送: Black Pan ***@***.***>; Comment ***@***.***>
主题: Re: [alibaba/easyexcel] 导出下载成功后，发生“WPS 表格在试图打开文件时遇到错误” (Issue #3887)


嗯嗯，此处只是帮助大家解决此类问题，谢谢

―

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.
