### ISSUE TITLE
web 导出excel 内容乱码 

### ISSUE THREAD

**Issue by ChengKeJ** [alibaba/easyexcel#389]
锟斤５铮碉５铮碉５铮碉５铮碉５铮碉５铮碉５铮碉５铮碉５铮 之类 乱码
![Uploading image.png…]()

**Comment by ChengKeJ** [comment]
request.setCharacterEncoding("GBK");
                response.setCharacterEncoding("GBK");
                response.setHeader("Content-Type", "application/vnd.ms-excel");
                response.setHeader("Content-Disposition",
                        "attachment;filename=" + URLEncoder.encode(filename + ".xls", "GBK"));
                ServletOutputStream out = response.getOutputStream();
                ExcelWriter writer = new ExcelWriter(out, ExcelTypeEnum.XLS);
                Sheet sheet = new Sheet(1, 0, RandomCheckExcelDateModel.class);
                sheet.setSheetName("randDomCheck");
                writer.write(data, sheet);
                writer.finish();
                out.flush();

**Comment by javaFather** [comment]
问题结局了吗？我也遇到了同样的问题，前端用的ant design pro

**Comment by ChengKeJ** [comment]
代码没有问题 之前 是我导出用的方式有问题   如果用swagger 调用接口导出Excel swagger 会导致excel 乱码 解决方式： 直接在浏览器中 输入导出对应访问url 就可以了！！ swagger 有点坑 在excel 导出这块
