### ISSUE TITLE
4.0.1版本依赖有冲突

### ISSUE THREAD

**Issue by danjiaxin555** [alibaba/easyexcel#3891]
![bb](https://github.com/user-attachments/assets/9e1b077a-ce71-4070-b5bd-4dc664bef918)

**Comment by psxjoy** [comment]
项目导致的jar包冲突，要么直接排除easyexcel中的依赖，要么删除项目中原本的jar包版本。

**Comment by psxjoy** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue。
