### ISSUE TITLE
在Docker中运行的导出Excel文件出现找不到字体的问题

### ISSUE THREAD

**Issue by JessenGan** [alibaba/easyexcel#3899]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
使用的版本：3.3.2
使用Java环境：OpenJDK21
在Docker中运行的导出Excel文件出现找不到字体的问题。不在Docker环境中，能够正常到处。在Docker中也无法安装字体。
不知道在最新版本中是否还有这个问题
# 触发Bug的代码
```java
   
```
# 提示的异常或者没有达到的效果
{"code":400,"success":false,"msg":"下载文件失败Fontconfig head is null, check your fonts or fonts configuration"}

**Comment by psxjoy** [comment]
与easyexcel无关，字体原因，是docker镜像本身的问题。

**Comment by hahaha-zsq** [comment]
是你docker中jdk版本的原因，不要使用slim类型的jdk,使用完整版本的

**Comment by psxjoy** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue。

**Comment by simonHome** [comment]
看了openjdk21 官方包已经没有字体这个配置，所以这个依赖是不是要单独导入进去

**Comment by fkong-bgl** [comment]
Docker 加入即可解决
RUN apk add --no-cache fontconfig ttf-dejavu

**Comment by Rmond** [comment]
> Docker 加入即可解决 RUN apk add --no-cache fontconfig ttf-dejavu

我这边装了也不行，需要其他配置吗
