### ISSUE TITLE
通过浏览器下载easyexcel的时候数据量过大，导致浏览器弹出下载框很慢怎么解决，能不能秒出然后处理数据

### ISSUE THREAD

**Issue by icaomeng** [alibaba/easyexcel#3908]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述

**Comment by psxjoy** [comment]
1. 数据量很大，本身就会耗时量大；
2. 秒出下载框在你的业务中，就意味着生成成功；
3. 浏览器下载框也只是响应你的请求。

因此暂时想不到能满足你的方法。

如果想要秒下载，建议：
1. 数据没有生成完毕，不要显示下载接口；
2. 数据写完后保存到临时文件中，下载直接走临时文件。

**Comment by icaomeng** [comment]
> 1. 数据量很大，本身就会运行量大；
> 2. 秒出下载框在你的业务中，就意味着生成成功；
> 3. 浏览器下载框也只是响应你的请求。
> 
> 因此暂时想不能满足你的方法。
> 
> 如果想要秒下载，建议：
> 
> 1. 数据未生成完毕，不要显示下载接口；
> 2. 数据写完后保存到临时文件中，下载直接走临时文件。

好的谢谢

**Comment by psxjoy** [comment]
> we can close this issue @psxjoy

LGTM

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.
