### ISSUE TITLE
使用Model解析Excel的时候Sheet是否可以考虑添加Model的泛型，还有空白行也被读取但是是个空元素，后续操作操作后出错，能否将空白行转换成空串

### ISSUE THREAD

**Issue by Mr-Zhe** [alibaba/easyexcel#391]
使用Model解析Excel的时候Sheet是否可以考虑添加Model的泛型，还有空白行也被读取但是是个空元素，后续操作操作后出错，能否将空白行转换成空串

**Comment by zhuangjiaju** [comment]
新版本已经修复您说的两个问题 非常感谢您的意见。请升级版本 并安装demo 书写
