### ISSUE TITLE
AnalysisEventListener中 doSomething方法需要调用外部接口怎么办？这样注入不进来

### ISSUE THREAD

**Issue by javaFather** [alibaba/easyexcel#392]
![image](https://user-images.githubusercontent.com/30115843/58942109-b22f9480-87af-11e9-8d03-ffaa051578ad.png)

**Comment by fish7790714** [comment]
listener 不能单例。你这样会崩的。你在调用 sax方法的类上面有 注入方法 ，然后 server作为构造函数的入参，new listenert 把service传进来

**Comment by javaFather** [comment]
按照你的方法已经解决了，谢谢

**Comment by bightZhang** [comment]
构造正解
