### ISSUE TITLE
你好，麻烦问一下读取Excel文件，Excel中有合并单元格 怎么处理？

### ISSUE THREAD

**Issue by webwangbao** [alibaba/easyexcel#393]

**Comment by dawangdedawang5** [comment]
有一个api方法叫merage

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
