### ISSUE TITLE
需要只读第一行就返回，请问如何处理

### ISSUE THREAD

**Issue by feitian124** [alibaba/easyexcel#394]
比如我有一个大文件，我需要分析表头，怎么读取了第一行就返回呢？
ExcelListener ， Reader 里面似乎都没有读一行就返回的方法。。

···
            // 解析每行结果在listener中处理
            ExcelListener listener = new ExcelListener();

            ExcelReader excelReader = new ExcelReader(inputStream, ExcelTypeEnum.XLS, null, listener);
            excelReader.read();
···

**Comment by fish7790714** [comment]
这个比较弱 你试试 Sheet.setStartRow=-1试试

**Comment by feitian124** [comment]
谢谢, 目前我也是抛异常的，感觉不优雅，故有一问。
读取一行，及读取某几行，类似于翻页，算一个比较常见的需求吧。
不知道是否方便实现。

**Comment by javaFather** [comment]
context.getCurrentRowNum()，可以拿到当前的行信息，不知道是不是你想要的

**Comment by javaFather** [comment]
context.getCurrentRowNum()，可以拿到当前的行号，不知道是不是你想要的

**Comment by bightZhang** [comment]
这个功能的确需要！为了判断Excel是不是合法模板导入的，需要读取表头就结束，然而ExcelListener会解析完每一行的。楼上所言极是，用异常是个办法的确不优雅。

**Comment by feitian124** [comment]
> context.getCurrentRowNum()，可以拿到当前的行号，不知道是不是你想要的

拿到行号还不够，需要能提前退出

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。覆盖`hasNext`方法即可

**Comment by YiMing-ING** [comment]
![image](https://user-images.githubusercontent.com/54900100/157153069-c95da084-1e03-4fdf-9d97-c8ac07cb9731.png)
从监听器直接重写方法，感谢楼上老哥

**Comment by louising** [comment]
> 请使用最新版本。[https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel%E3%80%82) 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。覆盖`hasNext`方法即可

覆盖 hasNext()后，解析完第一个 sheet 就退出了，如何让它解析完所有 sheet 的表头？
EasyExcel.read(inputStream, excelHeadListener).doReadAll();
