### ISSUE TITLE
有没有把图片插入excel的操作

### ISSUE THREAD

**Issue by 425131361** [alibaba/easyexcel#395]
业务场景存在把图片插入到excel中，有计划加入吗

**Comment by fish7790714** [comment]
写入 其实就稍封装了poi的代码 要图片建议直接用poi .这个工具的重点是 读取文件 防止oom

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
