### ISSUE TITLE
多sheet读取，每个sheet对应不同model,解决办法？

### ISSUE THREAD

**Issue by maxlange** [alibaba/easyexcel#396]
如题，多个sheet读取，每个sheet对应不同model,需持久化到数据库，研究了两天，越想越复杂，这个说明文档也太简单了，只能针对普通情况，一到复杂情况各种抓瞎，感觉要放弃了

**Comment by fish7790714** [comment]
你创建多个model 然后 多次调用sax方法不就好了？没理解你哪里理解不了

**Comment by maxlange** [comment]
可能我说的不是很清楚，对于这个工具直接上生产我是持保留态度的，结构不怎么严谨，而且说明文档基本上说是没有，对于后期迭代，尤其是更换研发人员之后的情况，是比较复杂的，所以自娱自乐还可以，上生产的话就要考虑风险了，当然这只是我的个人看法，对于好的开源工具我们还是要支持的。期待后期完善

**Comment by fish7790714** [comment]
如果你没有大的excel导入，可以直接用poi。 这个是阿里内部使用的，共享出来而已。稳定性肯定没问题，文档方面可以联系作者完善

**Comment by maxlange** [comment]
很感谢开源工作者的努力，是因为公司的技术leader推荐看下easyExcel，因为我的水平问题，解决不了easyExcel在一些复杂场景的应用，最终决定使用ApachePOI来做。会一直关注EasyExcel的更新，支持

**Comment by fish7790714** [comment]
嗯嗯 对的。easyexcel 兼容性极差，目前对外版本连单元格的格式都没法获取，一个String处理到底。目前只有大文件导入，生产出现oom的情况下，建议使用easyexcel，其他建议使用poi

**Comment by Uetty** [comment]
多次写
