### ISSUE TITLE
嵌套LIST问题

### ISSUE THREAD

**Issue by jzjohn789** [alibaba/easyexcel#3984]
例子
getArrayList.add(new TestEntity("1","2",Arrays.asList("1","2","3")));
比如上面这样，我自己定义了转换器，实体类也对应了
但是，这样的话，嵌套的List没办法每个占用一个格子，而是把对应的格子全面怼进去
就会变成下面这样？
![微信截图_20240910121337](https://github.com/user-attachments/assets/15a274ef-a222-42d7-abdb-16a7d39a395d)

有哪位大佬给点提示，该怎么改?

**Comment by jzjohn789** [comment]
已解决

**Comment by Tomccaatt** [comment]
具体方法是什么？
