### ISSUE TITLE
读取excel能否倒序读取

### ISSUE THREAD

**Issue by baixinbao77** [alibaba/easyexcel#3990]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 建议描述
我的excel文件内容过多，无法支出excel读取完写入数组转换的情况，所以能否支持读取excel时倒序读取，流程处理的情况

**Comment by psxjoy** [comment]
At the moment, this feature is not supported.I think this feature would be highly complex and difficult to control due to the underlying limitations of POI.

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.
