### ISSUE TITLE
我使用模板导出，支持用线程池并发导出多个excel吗

### ISSUE THREAD

**Issue by 17857333693** [alibaba/easyexcel#3992]
如题

**Comment by psxjoy** [comment]
Multithreading is currently not supported. While it generally doesn't cause issues in most cases (I sometimes use it for data processing), I strongly recommend against using it in production environments.

目前不支持。虽然日常使用中，多线程处理在大部分情况下，不会产生问题（我偶尔也会使用多线程处理数据），但是我强烈不建议在正式项目中使用。

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.
