### ISSUE TITLE
文档写错了，不是什么大问题

### ISSUE THREAD

**Issue by GUjhreal** [alibaba/easyexcel#3993]
![3b21747e28f1c58711f5b41c0c2588d](https://github.com/user-attachments/assets/428a0ec8-0980-472b-9908-9878ef270499)

**Comment by psxjoy** [comment]
Thanks for pointing that out. Would you be able to submit a PR for this?

**Comment by psxjoy** [comment]
I will update this info in the next update. Thanks for your suggestion.
