### ISSUE TITLE
正常的跑test出现java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Font.setBold(Z)V 错误

### ISSUE THREAD

**Issue by zhangws0994** [alibaba/easyexcel#40]
java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Font.setBold(Z)V

	at com.alibaba.excel.write.context.GenerateContextImpl.buildDefaultCellStyle(GenerateContextImpl.java:77)

**Comment by zhangws0994** [comment]
刚开始，我是直接在写了个测试类。引用maven运行出现的。我原以为是poi版本问题想把源代码的poi版本放高点在运行试试，但是我运行源代码中的test类是没问题的。再次回到之前写的test竟然可以了。不知道什么原因造成的。

**Comment by AbelKeithsun** [comment]
很容易出现这个错误，我之前没有引用别的 poi 包
