### ISSUE TITLE
如果模型里面属性第一个字母是大写的导致写 excel 数据为空

### ISSUE THREAD

**Issue by adntian** [alibaba/easyexcel#400]
1.1.2-bate5

继承BaseRowModel的 model 中，如果属性第一个字母为大写，在调用write方法之后，输出的 excel中，第一个字母为大写的列均为空值

**Comment by fish7790714** [comment]
这个估计没救 你什么第一个字母要大写？反射会获取不到 boolean  is开头也不行

**Comment by FlickerMi** [comment]
遇到了同样的问题，怎么解决呢？
