### ISSUE TITLE
报错：java.lang.NoSuchMethodError: org.apache.commons.io.input.BoundedInputStream.builder

### ISSUE THREAD

**Issue by CaptainJackH** [alibaba/easyexcel#4005]
使用版本easyexcel-core-3.1.4，apache.commons.io从2.15.1升级到2.16.1后，easyexcel报错

**Comment by psxjoy** [comment]
The issue clearly stems from the version of POI being used. I recommend not upgrading. For more information, you can check [this webpage](https://easyexcel.opensource.alibaba.com/qa/#%E5%85%B3%E4%BA%8E%E7%89%88%E6%9C%AC%E9%80%89%E6%8B%A9) to see the compatibility between POI and EasyExcel.

很明显的是 依赖的poi版本问题。我建议不要手动升级。或者参考 [这个网页](https://easyexcel.opensource.alibaba.com/qa/#%E5%85%B3%E4%BA%8E%E7%89%88%E6%9C%AC%E9%80%89%E6%8B%A9)，查询poi与easyexcel的对应依赖关系。

**Comment by CaptainJackH** [comment]
> The issue clearly stems from the version of POI being used. I recommend not upgrading. For more information, you can check [this webpage](https://easyexcel.opensource.alibaba.com/qa/#%E5%85%B3%E4%BA%8E%E7%89%88%E6%9C%AC%E9%80%89%E6%8B%A9) to see the compatibility between POI and EasyExcel.
> 
> 很明显的是 依赖的poi版本问题。我建议不要手动升级。或者参考 [这个网页](https://easyexcel.opensource.alibaba.com/qa/#%E5%85%B3%E4%BA%8E%E7%89%88%E6%9C%AC%E9%80%89%E6%8B%A9)，查询poi与easyexcel的对应依赖关系。

poi不支持5.3.0吗？我们的父版本升级了poi到5.3.0

**Comment by psxjoy** [comment]
I can't give a precise answer. Major version changes in POI can affect numerous APIs. I recommend adhering to the official guidance, where different versions of EasyExcel correspond to different major versions of POI. If you need to upgrade POI to 5.x, it would be best to also upgrade EasyExcel to the latest version.

我无法给出确切的答案。事实上poi的大版本改动会影响很多api，我建议是按照官网的建议，不同的easyexcel匹配不同大版本的poi。如果强制升级poi到5.x，最好升级easyexcel至最新版本。

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.
