### ISSUE TITLE
如何生成复选框

### ISSUE THREAD

**Issue by xinjirufen** [alibaba/easyexcel#401]
请问下，在Excel中如何生成下图中的复选框？
![TIM截图20190612112940](https://user-images.githubusercontent.com/44968246/59321639-6a57c280-8d05-11e9-9be4-e2f016527fd0.png)

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。

**Comment by FutaoSmile** [comment]
说了跟没说一样
