### ISSUE TITLE
在映射体存在链式调用的时候获取字段值为空

### ISSUE THREAD

**Issue by fatehcds** [alibaba/easyexcel#4013]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
在读取Excel的时候，如果设置的对象存在get/set链式调用会存在无法获取到值的情况，使用lombok将get/set设置成链式调用可以必现此bug

**Comment by psxjoy** [comment]
I think setter methods should focus on the single responsibility of setting properties. We don’t have plans to support this feature at the moment.

我认为 setter 方法应该专注于设置属性的单一职责。 目前暂时没有支持该特性的打算。

**Comment by psxjoy** [comment]
link #3905

**Comment by psxjoy** [comment]
It seems not a bug. I will remove `BUG` tag.
