### ISSUE TITLE
源码构建失败

### ISSUE THREAD

**Issue by marker-wu** [alibaba/easyexcel#4028]
帮忙看下源码构建失败，pom依赖不到
![image](https://github.com/user-attachments/assets/4258bd99-381b-4ffc-9ffa-fef2ecd6e485)

**Comment by psxjoy** [comment]
using `mvn complie -DskipTests=true `.

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by marker-wu** [comment]
> using `mvn complie -DskipTests=true `.

还是报错
![image](https://github.com/user-attachments/assets/ef9c0a32-8973-40c3-8925-deccea5c12d0)

**Comment by psxjoy** [comment]
> > using `mvn complie -DskipTests=true `.
> 
> 还是报错 ![image](https://private-user-images.githubusercontent.com/45256940/382172610-ef9c0a32-8973-40c3-8925-deccea5c12d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MzExMzMsIm5iZiI6MTczMDQzMDgzMywicGF0aCI6Ii80NTI1Njk0MC8zODIxNzI2MTAtZWY5YzBhMzItODk3My00MGMzLTg5MjUtZGVjY2VhNWMxMmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAzMTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMzNkNGEwY2RmMmYxZjgxOGZmMjAwMmM1ZTIzNmVmNDBlZGYyM2U1NTAzZmU0ZGQ0ZWM5Yzc4MzhjYzY1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pJQ2H5M0kBJ_xOuHeOy-F-NnVuPItV4OYVZ1zmBb3C8)

sorry for my typo.
just using `mvn compile -DskipTests=true ` or `mvn compile -DskipTests`

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.
