### ISSUE TITLE
做了列宽的自动适配，但是@ColumnWidth失效了

### ISSUE THREAD

**Issue by cxz0101** [alibaba/easyexcel#4034]
![0fc7f0172df321bec10b07a9cb8e24d](https://github.com/user-attachments/assets/c893b88d-2b91-4af0-894b-c56c8960fdd9)

![10a4b9a6c870bae49d46aa046c15310](https://github.com/user-attachments/assets/7acec75e-dff2-4f22-a3d2-f35aff0ed77f)

就是想要有指定的就按照指定长度 @ColumnWidth来，没有的话，就是自动适应，这个怎么写呢，谢谢

**Comment by psxjoy** [comment]
The "auto-width" feature is still in the experimental phase, so we can't guarantee full compatibility with tables at the moment.

**Comment by cxz0101** [comment]
我拓展了这个代码，代码如下，想问一下，这样可以嘛，测试是没问题的，可以识别@ColumnWidth

public class CustomColumnWidthStrategy extends LongestMatchColumnWidthStyleStrategy {

    private static final int MAX_COLUMN_WIDTH = 255;
    private static final int MIN_COLUMN_WIDTH = 20;

    @Override
    protected void setColumnWidth(WriteSheetHolder writeSheetHolder, List<WriteCellData<?>> cellDataList,
                                  Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {
        // 检查是否有 @ColumnWidth 注解
        ColumnWidth columnWidthAnnotation = head.getField().getAnnotation(ColumnWidth.class);
        if (columnWidthAnnotation != null) {
            // 有注解时直接按注解宽度设置列宽并返回
            int specifiedWidth = columnWidthAnnotation.value();
            writeSheetHolder.getSheet().setColumnWidth(cell.getColumnIndex(), specifiedWidth * 256);
            return;
        }

        // 如果没有注解，则按自动宽度计算逻辑
        Integer columnWidth = dataLength(cellDataList, cell, isHead);
        if (columnWidth != null && columnWidth >= 0) {
            if (columnWidth > MAX_COLUMN_WIDTH) {
                columnWidth = MAX_COLUMN_WIDTH;
            } else if (columnWidth < MIN_COLUMN_WIDTH) {
                // 小于最小宽度时，按比例扩展
                columnWidth *= 2;
            }
            writeSheetHolder.getSheet().setColumnWidth(cell.getColumnIndex(), columnWidth * 256);
        }
    }

    private Integer dataLength(List<WriteCellData<?>> cellDataList, Cell cell, Boolean isHead) {
        if (isHead) {
            return cell.getStringCellValue().getBytes().length;
        } else {
            WriteCellData<?> cellData = (WriteCellData)cellDataList.get(0);
            CellDataTypeEnum type = cellData.getType();
            if (type == null) {
                return -1;
            } else {
                switch (type) {
                    case STRING:
                        return cellData.getStringValue().getBytes().length;
                    case BOOLEAN:
                        return cellData.getBooleanValue().toString().getBytes().length;
                    case NUMBER:
                        return cellData.getNumberValue().toString().getBytes().length;
                    default:
                        return -1;
                }
            }
        }
    }
}

**Comment by psxjoy** [comment]
> 我拓展了这个代码，代码如下，想问一下，这样可以嘛，测试是没问题的，可以识别@ColumnWidth
> 
> public class CustomColumnWidthStrategy extends LongestMatchColumnWidthStyleStrategy {
> 
> ```
> private static final int MAX_COLUMN_WIDTH = 255;
> private static final int MIN_COLUMN_WIDTH = 20;
> 
> @Override
> protected void setColumnWidth(WriteSheetHolder writeSheetHolder, List<WriteCellData<?>> cellDataList,
>                               Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {
>     // 检查是否有 @ColumnWidth 注解
>     ColumnWidth columnWidthAnnotation = head.getField().getAnnotation(ColumnWidth.class);
>     if (columnWidthAnnotation != null) {
>         // 有注解时直接按注解宽度设置列宽并返回
>         int specifiedWidth = columnWidthAnnotation.value();
>         writeSheetHolder.getSheet().setColumnWidth(cell.getColumnIndex(), specifiedWidth * 256);
>         return;
>     }
> 
>     // 如果没有注解，则按自动宽度计算逻辑
>     Integer columnWidth = dataLength(cellDataList, cell, isHead);
>     if (columnWidth != null && columnWidth >= 0) {
>         if (columnWidth > MAX_COLUMN_WIDTH) {
>             columnWidth = MAX_COLUMN_WIDTH;
>         } else if (columnWidth < MIN_COLUMN_WIDTH) {
>             // 小于最小宽度时，按比例扩展
>             columnWidth *= 2;
>         }
>         writeSheetHolder.getSheet().setColumnWidth(cell.getColumnIndex(), columnWidth * 256);
>     }
> }
> 
> private Integer dataLength(List<WriteCellData<?>> cellDataList, Cell cell, Boolean isHead) {
>     if (isHead) {
>         return cell.getStringCellValue().getBytes().length;
>     } else {
>         WriteCellData<?> cellData = (WriteCellData)cellDataList.get(0);
>         CellDataTypeEnum type = cellData.getType();
>         if (type == null) {
>             return -1;
>         } else {
>             switch (type) {
>                 case STRING:
>                     return cellData.getStringValue().getBytes().length;
>                 case BOOLEAN:
>                     return cellData.getBooleanValue().toString().getBytes().length;
>                 case NUMBER:
>                     return cellData.getNumberValue().toString().getBytes().length;
>                 default:
>                     return -1;
>             }
>         }
>     }
> }
> ```
> 
> }

Nice try. I don’t think there’s anything wrong with it, but make sure it aligns with the requirements of your business logic.

**Comment by cxz0101** [comment]
好的，谢谢啦

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by cxz0101** [comment]
你好，我这边看到评论已经删除了，请问一下是有更好的解决方案吗，谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/easyexcel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月28日(星期一) 晚上11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] ***@***.***失效了 (Issue #4034)





 
maybe this solution will solve your problem click

**Comment by psxjoy** [comment]
That reply was not a real reply, but a link to an advertisement with a misleading nature. So I deleted it

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: cxz ***@***.***>
发送时间: Tuesday, October 29, 2024 5:43:42 PM
收件人: alibaba/easyexcel ***@***.***>
抄送: psxjoy ***@***.***>; Assign ***@***.***>
主题: Re: [alibaba/easyexcel] ***@***.***失效了 (Issue #4034)


你好，我这边看到评论已经删除了，请问一下是有更好的解决方案吗，谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "alibaba/easyexcel" ***@***.***&gt;;
发送时间:&nbsp;2024年10月28日(星期一) 晚上11:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] ***@***.***失效了 (Issue #4034)






maybe this solution will solve your problem click

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

―

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.
