### ISSUE TITLE
请问如何知道浏览器上传的excel的行数

### ISSUE THREAD

**Issue by putekid** [alibaba/easyexcel#404]

**Comment by fish7790714** [comment]
`ExcelListener` 里卖弄data的size

**Comment by putekid** [comment]
> 
> 
> `ExcelListener` 里卖弄data的size

不是在读之前要根据行数来选择调用哪个方法吗？读之前怎么获取行数呢？

**Comment by fish7790714** [comment]
不用 都用 `ExcelListener`即可。1000以内的方法 也是 使用的他自己的 `ExcelListener`然后统一返回了而已。1000就是让你感觉写法简单一点
