### ISSUE TITLE
自定义多行表头，变成多列

### ISSUE THREAD

**Issue by cx282441** [alibaba/easyexcel#4049]
# 异常代码
```java
   // 将数据写入到输出流中 演示代码
        ExcelWriterBuilder writerBuilder = EasyExcel.write(rsp.getOutputStream())
            .head(data);
        writerBuilder.sheet("Sheet1").doWrite(ListUtil.empty());
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述
使用 Version 4.0.3 自定义多行head 数据结构List<List<String>>
<img width="999" alt="image" src="https://github.com/user-attachments/assets/9328e845-cc75-43c3-9926-7be4e5a4944d">
导出的excel文件表头变成了竖行，如何解决
<img width="779" alt="image" src="https://github.com/user-attachments/assets/343e6190-e8ee-4390-969d-0ff289d52562">

正常表头
<img width="566" alt="image" src="https://github.com/user-attachments/assets/8724175f-6916-4306-8b03-d0b0919d7ae9">

**Comment by LSL1618** [comment]
你可能对表头参数`List<List<String>> head`的数据结构理解错了，应该这样装载表头数据：
```
head.add(Arrays.asList("第1行第1列表头", "第2行第1列表头"));
head.add(Arrays.asList("第1行第2列表头", "第2行第2列表头"));
head.add(Arrays.asList("第1行第3列表头", "第2行第3列表头"));
head.add(Arrays.asList("第1行第4列表头", "第2行第4列表头"));
head.add(Arrays.asList("第1行第5列表头", "第2行第5列表头"));
```
而你传的表头数据却是这样的：
```
head.add(Arrays.asList("", "", "", "", "", "1", "2", "3", "4", "5"));
head.add(Arrays.asList("总序号", "部门ID", "班组", "工号", "姓名", "项目经理", "人力资源", "普通员工", "可办运", "ABCD")));
```

**Comment by cx282441** [comment]
@LSL1618 感谢回复，简洁明了。
