### ISSUE TITLE
请问这个支持设置某一列为下拉选择吗？

### ISSUE THREAD

**Issue by putekid** [alibaba/easyexcel#405]
请问如何设置某一列为下拉选择的呢？

**Comment by fish7790714** [comment]
这个工具的核心时读excel 不OOM ，如果要写的话 建议直接用poi。这个写只是简单的封装用了poi的接口

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。

**Comment by Sdky** [comment]
> 这个已经在最新版本修复，请使用最新版本。[https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel%E3%80%82) 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。

请问应该怎么设置整列为下拉选择呢？我只看到设置起始、结束行号的
`        CellRangeAddressList cellRangeAddressList = new CellRangeAddressList(1, 1048576 - 1, 0, 0);
        DataValidationHelper helper = context.getWriteSheetHolder().getSheet().getDataValidationHelper();
        DataValidationConstraint constraint = helper.createExplicitListConstraint(new String[] {"测试1", "测试2"});
        DataValidation dataValidation = helper.createValidation(constraint, cellRangeAddressList);
        context.getWriteSheetHolder().getSheet().addValidationData(dataValidation);
`
