### ISSUE TITLE
依赖错误

### ISSUE THREAD

**Issue by jjjcv** [alibaba/easyexcel#4054]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 建议描述
希望在文档中添加maven指示，单独引入easyexcel依赖无法运行，必须引入poi。。。。
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>4.1.2</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>4.0.3</version>
        </dependency>

**Comment by gongxuanzhang** [comment]
完全不需要，请检查自己使用方法
