### ISSUE TITLE
读Excel反序列化为model的时候，能根据ExcelProperty（value = "公司名称"）来匹配值么

### ISSUE THREAD

**Issue by liuhui8278** [alibaba/easyexcel#406]
excel的头部顺序不固定，想按照中文头来自动反序列化
  @ExcelProperty(value = "公司名称")  这么写反序列化的值无法复制，非要用index么？ 请问无序的表头该如何反序列化

**Comment by fish7790714** [comment]
木的。这个是用来 value 是用write的。

**Comment by liuhui8278** [comment]
我觉得可以根据这个中文来匹配读取字段的复制？

**Comment by liuhui8278** [comment]
我们自己用poi原生api来读取的时候，都是根据中文头来匹配的，是否可以考虑也支持一下？

**Comment by fish7790714** [comment]
这个要联系作者了 我就多看了几遍源码而已

**Comment by liuhui8278** [comment]
> 这个要联系作者了 我就多看了几遍源码而已

作者现在还维护么？怎么联系？

**Comment by fish7790714** [comment]
据说 内部升级过 也不确定 是否支持这个

**Comment by fish7790714** [comment]
你可以直接PR试试吧

**Comment by liuhui8278** [comment]
> 据说 内部升级过 也不确定 是否支持这个

这个不根据中文名匹配自动反序列化就很鸡肋了，如何保证excel头部顺序 不变？都是用户上传的啊

**Comment by fish7790714** [comment]
> > 据说 内部升级过 也不确定 是否支持这个
> 
> 这个不根据中文名匹配自动反序列化就很鸡肋了，如何保证excel头部顺序 不变？都是用户上传的啊

你可以直接提交pull  requests

**Comment by andysd** [comment]
我这边大部分需求都是无序表头， 几十个字段如果表头稍微调整以下顺序，程序就要重新修改

**Comment by zhuangjiaju** [comment]
新版本支持。请升级版本
