### ISSUE TITLE
为什么我调用write0写出来的文件打不开（最新版本）

### ISSUE THREAD

**Issue by wanglforever** [alibaba/easyexcel#407]
public static void main(String[] args) {
        try {
            OutputStream out = new FileOutputStream("C:\\Users\\ASUS\\Desktop\\bbb.xlsx");
            ExcelWriter writer = EasyExcelFactory.getWriter(out,ExcelTypeEnum.XLSX,false);
            Sheet sheet = new Sheet(1,0);
            List<List<String>> result = new ArrayList<>();
            for (int i=0 ; i<100 ;i++){
                List<String> list = new ArrayList<>();
                list.add("aa" + i);
                list.add("bb" + i);
                list.add("cc" + i);
                result.add(list);
            }
            writer.write0(result,sheet);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }

**Comment by fish7790714** [comment]
```java
  public ExcelWriter write0(List<List<String>> data, Sheet sheet) {
        excelBuilder.addContent(data, sheet);
        return this;
    }
```

write0 入参是 `List<List<String>> data` 。然后建议 用wirte

**Comment by wanglforever** [comment]
/** @deprecated */
    @Deprecated
    public ExcelWriter write(List data) {
        return this.objectClass != null ? this.write(data, new Sheet(1, 0, this.objectClass)) : this.write0(data, new Sheet(1, 0, this.objectClass));
    }
这个write方法已经废弃了，而且我的入参确实是List<List<String>>呀

**Comment by fish7790714** [comment]
用这个
```java
    /**
     * Write data to a sheet
     * @param data Data to be written
     * @param sheet Write to this sheet
     * @return this current writer
     */
    public ExcelWriter write(List<? extends BaseRowModel> data, Sheet sheet) {
        excelBuilder.addContent(data, sheet);
        return this;
    }

```

**Comment by wanglforever** [comment]
谢谢，这个是可以用，但是没有解决我的问题，就是为什么用write0方法不行呢？

**Comment by wanglforever** [comment]
找到原因了。。。没有调用finish方法
