### ISSUE TITLE
列数和sheet数怎么获取？

### ISSUE THREAD

**Issue by YancyPeng** [alibaba/easyexcel#408]
需要在开始解析前获取列数和sheet数，以此来进行判断是否要开启多个线程，请问列数和sheet数有没有办法获取？

**Comment by fish7790714** [comment]
easy的思路是读一条 给你一条。所以不会放在内存里面，这样可以避免OOM。所以无法获取列数，建议直接开多线程就行。多线程不是针对某一次导入的，而是全局的。一直开几个线程问题不大

**Comment by zhuangjiaju** [comment]
请升级到最新版本。根据 `excelExecutor.sheetList` 能获取sheet数量。列的数量 你直接 用`Map<Integer,String>` 去接 size 就是列的数量。

**Comment by leslie010203** [comment]
列的名称怎么获取呢

**Comment by leslie010203** [comment]
第一列
