### ISSUE TITLE
压缩功能

### ISSUE THREAD

**Issue by guofeiwu** [alibaba/easyexcel#412]
可以集成多个Excel压缩为一个压缩包吗？

**Comment by BlueSkyChina** [comment]
从对象职责来说，是不是应该考虑在外部应用系统中来考虑，将多个文件进行压缩处理？

**Comment by fish7790714** [comment]
这个功能 不会去做。java自在有zip功能。超出了excel的范围

**Comment by lgx211** [comment]
我也觉得作者不会去做这个功能




------------------ 原始邮件 ------------------
发件人: "zhuangjiaju"<notifications@github.com>; 
发送时间: 2019年6月25日(星期二) 中午11:09
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: Re: [alibaba/easyexcel] 压缩功能 (#412)




这个功能 不会去做。java自在有zip功能。超出了excel的范围
 
&mdash;

**Comment by guofeiwu** [comment]
好的，好的，小菜鸡知道了，谢谢大家的指点。
