### ISSUE TITLE
能不能提供下对于单元格设置格式的方法，不然很难去设置单元格的格式问题

### ISSUE THREAD

**Issue by MentosL** [alibaba/easyexcel#413]

**Comment by fish7790714** [comment]
这个 在联系作者 会想办法加入格式

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
