### ISSUE TITLE
如何根据sheetName来读取Excel中的sheet，而非sheetIndex？

### ISSUE THREAD

**Issue by chuanwu** [alibaba/easyexcel#414]

**Comment by fish7790714** [comment]
```java 

        try (InputStream inputStream =  new BufferedInputStream(FileUtil.getResourcesFileInputStream("2007.xlsx"))) {
            ExcelListener excelListener = new ExcelListener();
            ExcelReader excelReader = new ExcelReader(inputStream, null, excelListener, false);
            List<Sheet> sheets = excelReader.getSheets();
            System.out.println("llll****" + sheets);
            System.out.println();
            for (Sheet sheet : sheets) {
                // 这里有名称
                sheet.getSheetName();
               
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
```

**Comment by chuanwu** [comment]
> ```java
>         try (InputStream inputStream =  new BufferedInputStream(FileUtil.getResourcesFileInputStream("2007.xlsx"))) {
>             ExcelListener excelListener = new ExcelListener();
>             ExcelReader excelReader = new ExcelReader(inputStream, null, excelListener, false);
>             List<Sheet> sheets = excelReader.getSheets();
>             System.out.println("llll****" + sheets);
>             System.out.println();
>             for (Sheet sheet : sheets) {
>                 // 这里有名称
>                 sheet.getSheetName();
>                
>             }
> 
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
> ```

谢谢你的答复。
我更希望库中直接提供该方法。自己遍历sheet来根据名字判定，不太优雅。

anyway，谢谢你。

**Comment by fish7790714** [comment]
嗯 嗯 包括根据sheetName 和rowName 已经想办法在和作者沟通了 目前肯定不支持

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
