### ISSUE TITLE
【建议】sheetNo这个参数建议加上文档。

### ISSUE THREAD

**Issue by chuanwu** [alibaba/easyexcel#416]
一般潜意识，我们认为sheet的序号是从0开始，举个例子，一个excel包含三个sheet，则第一个sheet，序号应该为0，第二个sheet，序号为1，第三个sheet，序号为2。
但是现在代码的实现是，传入0，则返回所有sheet中的数据。
这个设计个人觉得不太合理。
希望作者能考虑一下。

**Comment by lgx211** [comment]
那那些确实想获得全部sheet的呢？他要传什么参数？作者这种做法，明显是他深思熟虑的，你取第几个sheet就传第几，想取得全部的就传0这个特殊数字。这种做法是最大程度的兼顾了所有人的需求，不要用你单独的业务来衡量。




------------------ 原始邮件 ------------------
发件人: "孙传武"<notifications@github.com>;
发送时间: 2019年6月19日(星期三) 下午4:42
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [alibaba/easyexcel] 【建议】sheetNo这个参数建议加上文档。 (#416)




一般潜意识，我们认为sheet的序号是从0开始，举个例子，一个excel包含三个sheet，则第一个sheet，序号应该为0，第二个sheet，序号为1，第三个sheet，序号为3。
 但是现在代码的实现是，传入0，则返回所有sheet中的数据。
 这个设计个人觉得不太合理。
 希望作者能考虑一下。

**Comment by chuanwu** [comment]
看我的标题哦。如果我的建议不合理的话，最好在文档上标注一下哈～
还有，从0开始计数，这个并不是我个人单独的业务哦。

**Comment by chuanwu** [comment]
> 那那些确实想获得全部sheet的呢？他要传什么参数？作者这种做法，明显是他深思熟虑的，你取第几个sheet就传第几，想取得全部的就传0这个特殊数字。这种做法是最大程度的兼顾了所有人的需求，不要用你单独的业务来衡量。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "孙传武"<notifications@github.com>; 发送时间: 2019年6月19日(星期三) 下午4:42 收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [alibaba/easyexcel] 【建议】sheetNo这个参数建议加上文档。 (#416) 一般潜意识，我们认为sheet的序号是从0开始，举个例子，一个excel包含三个sheet，则第一个sheet，序号应该为0，第二个sheet，序号为1，第三个sheet，序号为3。 但是现在代码的实现是，传入0，则返回所有sheet中的数据。 这个设计个人觉得不太合理。 希望作者能考虑一下。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

忘at了。

**Comment by MissThee** [comment]
sheet序号从0开始确实是poi用户的共通认知了。。。

**Comment by lgx211** [comment]
真的是，你就改个0为1，就解决了的事情。那那些想拿全部值的呢，单个sheet的峰值也就一百来万行，别人要是有千万级别的日志数据，别人写什么获取呢？作者又要单独写法方法去调用。从程序计数来看，确实是从0开始，你是个程序员，大家都知道了。但是很多场景里面，是1代表开始计数，0这个特殊的就代表全部的含义。能别为这种事情叨扰人家作者吗？




------------------ 原始邮件 ------------------
发件人: "MT"<notifications@github.com>; 
发送时间: 2019年6月25日(星期二) 下午4:51
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>; 
抄送: "Richard"<2029666191@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [alibaba/easyexcel] 【建议】sheetNo这个参数建议加上文档。 (#416)




sheet序号从0开始确实是poi用户的共通认知了。。。
 
&mdash;

**Comment by MissThee** [comment]
@lgx211 
1. 首先0不能获取所有，别人用什么获取呢？
  可以用-1或者其他负数获取，当然这样也不太好；可以额外增加一个原方法或xxxAll()的无参方法，专门获取。这种逻辑实现起来应该不难，不是个全世界无解的问题
2. 很多场景里面，是1代表开始计数
  懒得吐槽了。 为什么建议0？首先，作者说过这里一部分是对poi接口的二次封装，既然是二次封装，就应该尽量和原有接口的规则相同，让使用者不会混乱，如果poi全是1开始做sheet序号的接口，鬼才会提出这个建议；其次，java里集合类的开始下标是0
3. 能别为这种事情叨扰人家作者吗？
  作为一个程序员，自己的开源项目有人提出并非扯淡般的建议，应该算是个好事儿。

**Comment by zhuangjiaju** [comment]
请在参照最新版本 已经改为0  非常感谢您的意见。
