### ISSUE TITLE
spingboot/resources/excel.xlsx

### ISSUE THREAD

**Issue by luanweijie** [alibaba/easyexcel#419]
spingboot/resources/excel.xlsx模板，根据模板导出文件，导出后，文件格式损坏，遇到么？
查了很多说是maven打包导致的

**Comment by fish7790714** [comment]
尝试 用demo的模板 试试可以不

**Comment by harvies** [comment]
你的excel被maven编译了，导致文件损坏，排除编译即可


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>xlsx</nonFilteredFileExtension>
                        <nonFilteredFileExtension>xls</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>

**Comment by luanweijie** [comment]
实际上，用inputstream可以解决此问题，谢谢，已解决
