### ISSUE TITLE
读取 Excel 的速度会越来越慢

### ISSUE THREAD

**Issue by HowieYuan** [alibaba/easyexcel#42]
读取一个有 10W+ 数据的 Excel 文件，前 5000 条很快，之后速度逐渐变慢，读到几万条的时候速度已经非常非常慢，没办法处理数据量大的文件

**Comment by jipengfei-jpf** [comment]
数据解析完需要处理掉，不要尝试经占用内存，后面内存增加会FULL gc。没100条处理一次，如果还有问题，微信找我发我文件看一下

**Comment by jipengfei-jpf** [comment]
由于1.0.*版本核心考虑的是怎么解决读excel内存溢出问题，自己重写了读excel的POI的底层，写仍旧使用POI。可以从根本解决OOM问题。但是由于自己对excel的格式认识不全面，有很多坑产生了很多BUG。最新版本以POI为底层。最新版：1.1.2-beat1，虽然不能完全解决OOM但可以解决大部分的OOM问题，完全解决OOM版本会等稳定后再开放，敬请理解。目前稳定版本1.1.2-beat1
