### ISSUE TITLE
如果优雅的进行表头合并呢？

### ISSUE THREAD

**Issue by tyfwe** [alibaba/easyexcel#426]
jar版本:  1.1.2-beta5
如图：
![image](https://user-images.githubusercontent.com/22927037/60232901-a297fd00-98d0-11e9-86b0-19b7c68dd0b1.png)
有什么写法可以避免这种情况呢

**Comment by BestRoach** [comment]
测试代码中好像已经有了很多样的合并情况，感觉你这个倒像是合并策略选择的不对引起的。

**Comment by gnng** [comment]
老哥，解决了吗？

**Comment by zhuangjiaju** [comment]
这个真的无法解决。这里只能实现 看到相同后合并。或者全部不合并。如果您有好的方案，可以修改 `com.alibaba.excel.write.property.ExcelWriteHeadProperty#headCellRangeList` 并提交PR

**Comment by dujunjunjason** [comment]
@zhuangjiaju ，是否可以考虑使用html中table的rowspan和colspan来设置如何合并呢，我12年用poi做过类似的，设置poi自动合并标题中的行列
