### ISSUE TITLE
何时来一个正式版？

### ISSUE THREAD

**Issue by 66254264** [alibaba/easyexcel#436]

**Comment by 66254264** [comment]
release

**Comment by BestRoach** [comment]
不知道这个项目还有没有持续的发布计划，用1.1.1的话就没有merge了，而且数据类型的支持也不完整。很是困扰。希望可以早点出一个1.1.2的正式版。

**Comment by Ryoui** [comment]
长时间没更新，多半凉了，转poi了

**Comment by zhuangjiaju** [comment]
最多一个月 会出2.0 性能大幅提升 100M+ 读取 300M内存 就能读取

**Comment by 66254264** [comment]
> 最多一个月 会出2.0 性能大幅提升 100M+ 读取 300M内存 就能读取

你怎么知道一个月会出2.0？

**Comment by zhuangjiaju** [comment]
一个月内升级正式版。目前主要收集问题
