### ISSUE TITLE
poi.xml是否重复引入dependency(org.apache.poi:poi:3.17)?

### ISSUE THREAD

**Issue by tanbo091** [alibaba/easyexcel#437]
android 会因为重复引入无法使用。

pom.xml是否重复引入 dependency (org.apache.poi:poi:3.17)?
org.apache.poi 现在已经 4.1.0 ，能否更新一下？

还是说因为poi 3.17 中有引入 org.apache.xmlbeans : xmlbeans 导致的重复问题？

**Comment by zhuangjiaju** [comment]
已经更新 请使用最新版本
