### ISSUE TITLE
读取含多个sheet的excel，不能读取

### ISSUE THREAD

**Issue by cikeJonas** [alibaba/easyexcel#44]
当一个2007+ excel存在多个sheet，且只有第一个有具体数据，其他都为空时，读取不到数据。

**Comment by maojiudada** [comment]
第二个直接报空指针异常了

**Comment by jipengfei-jpf** [comment]
InputStream inputStream = FileUtil.getResourcesFileInputStream("2007.xlsx");
        ExcelListener excelListener = new ExcelListener();
        ExcelReader excelReader = EasyExcelFactory.getReader(inputStream,excelListener);
        List<Sheet> sheets = excelReader.getSheets();
        System.out.println("llll****"+sheets);
        System.out.println();
        for (Sheet sheet:sheets) {
            if(sheet.getSheetNo() ==1) {
                excelReader.read(sheet);
            }else if(sheet.getSheetNo() ==2){
                sheet.setHeadLineMun(1);
                sheet.setClazz(JavaModel.class);
                excelReader.read(sheet);
            }else if(sheet.getSheetNo() ==3){
                sheet.setHeadLineMun(1);
                sheet.setClazz(JavaModel2.class);
                excelReader.read(sheet);
            }
        }
最新版1.1.2-beat1
