### ISSUE TITLE
无模板模式下, listener.invoke方法中, excel数据如果是不带时分秒的时间类型,如何判断?

### ISSUE THREAD

**Issue by yiwangai1983** [alibaba/easyexcel#441]
版本<1.1.2-beta5>

带时分秒的日期格式可以用正则匹配, 如果是不带时分秒的日期如何确定呢? 现在不能确定这是一个整数,还是一个不带时分秒的日期.

建议如果是日期,统一格式化.其他类型不管. 或者已经有了更好的解决方案.

盼复.

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel  。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
