### ISSUE TITLE
导出Excel时如何冻结表头？

### ISSUE THREAD

**Issue by chuyuanlinzi** [alibaba/easyexcel#443]
导出Excel时如何冻结表头？

**Comment by Uetty** [comment]
注册一个WriteHandler 可以实现。我是因为样式需求多，外面又封装了一层。
https://github.com/Uetty/common-excel/blob/master/src/main/java/com/uetty/common/excel/easyexcel/hssf/XlsExcelWriter.java
代码定位如下
![image](https://user-images.githubusercontent.com/14183559/61628309-83647380-acb4-11e9-86f0-80e622e033ab.png)
