### ISSUE TITLE
在openjdk 上面使用提示缺少java.awt. x11font

### ISSUE THREAD

**Issue by gisdaodao** [alibaba/easyexcel#445]
设置headless=true 无效，在openjdk 环境下面,SUSE LINUX

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
