### ISSUE TITLE
解析大文件占用内存过多

### ISSUE THREAD

**Issue by mycoolgame** [alibaba/easyexcel#446]
大家解析的文件都是多大的，我使用1.1.2解析90个sheet页，100m左右的excel，需要使用内存2.6G。难道大家没有遇见类似的情况吗？

**Comment by ksharpy** [comment]
有遇到，183M的EXCEL使用内存4.5G

**Comment by mycoolgame** [comment]
> 有遇到，183M的EXCEL使用内存4.5G

你怎么弄了

**Comment by ksharpy** [comment]
http://5589csxz.wicp.top:10028/?id=9606945&key=522748578927626241
用别人的工具包改了一下，把这个ExcelUtil引入，然后在Xlsx2ListData类加入一个变量maxCol，覆盖原本的endRow方法，解决最后一列部分字段为空的问题
[public void endRow(int rowNum) {
            // Ensure the minimum number of columns
            for (int i = currentCol; i < minColumns - 1; i++) {
                currRowData.add(defaultValue);
            }
            if (rowNum == 0) {
                maxCol = currRowData.size() > 0 ? currRowData.size() - 1 : 0;
            }
            for (int i = currentCol; i < maxCol; i++) {
                currRowData.add(defaultValue);
            }
            processRowData(currRowData);
        }](url)

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel  。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。

**Comment by zhuangjiaju** [comment]
新版本重点就是为了解决内存占用的问题
