### ISSUE TITLE
你好 请问如何读取合并单元格的数据？

### ISSUE THREAD

**Issue by kylincode** [alibaba/easyexcel#447]

**Comment by 453055141** [comment]
我也想知道

**Comment by ainmind** [comment]
您好，我也遇到合并单元格的数据读取

**Comment by 453055141** [comment]
> 您好，我也遇到合并单元格的数据读取

我是这么做的，因为合并的单元格读取的是合并第一行数据，后面的读取都是null，所以我判断如果合并的几列都是null,就表示是合并的单元格，虽然这样判断不够严谨，但我不知道更好的办法了，你如果找到了麻烦告诉我，谢谢

**Comment by zhuangjiaju** [comment]
对 合并单元格 就第一格有数据 后面数据都为空

**Comment by 453055141** [comment]
> 对 合并单元格 就第一格有数据 后面数据都为空

你是怎么处理的呢？

**Comment by ainmind** [comment]
> > 您好，我也遇到合并单元格的数据读取
> 
> 我是这么做的，因为合并的单元格读取的是合并第一行数据，后面的读取都是null，所以我判断如果合并的几列都是null,就表示是合并的单元格，虽然这样判断不够严谨，但我不知道更好的办法了，你如果找到了麻烦告诉我，谢谢

谢谢，我也是这么想的

**Comment by zhuangjiaju** [comment]
> > 对 合并单元格 就第一格有数据 后面数据都为空
> 
> 你是怎么处理的呢？

你要知道那几格合并了？应该知道第一格数据就行了吧。你的应用场景是啥

**Comment by 453055141** [comment]
> > > 对 合并单元格 就第一格有数据 后面数据都为空
> > 
> > 
> > 你是怎么处理的呢？
> 
> 你要知道那几格合并了？应该知道第一格数据就行了吧。你的应用场景是啥

我并不知道哪几行会合并，你可以看我回答另一个人的问题，我是那样去做的，如果有更好的方法请告知

**Comment by zhuangjiaju** [comment]
> > > > 对 合并单元格 就第一格有数据 后面数据都为空
> > > 
> > > 
> > > 你是怎么处理的呢？
> > 
> > 
> > 你要知道那几格合并了？应该知道第一格数据就行了吧。你的应用场景是啥
> 
> 我并不知道哪几行会合并，你可以看我回答另一个人的问题，我是那样去做的，如果有更好的方法请告知

这个是异步解析的。所以没法知道那几行合并了。但是可以做成 ，全部数据解析完成了，然后再通知你那几行合并了

**Comment by 453055141** [comment]
> > > > > 对 合并单元格 就第一格有数据 后面数据都为空
> > > > 
> > > > 
> > > > 你是怎么处理的呢？
> > > 
> > > 
> > > 你要知道那几格合并了？应该知道第一格数据就行了吧。你的应用场景是啥
> > 
> > 
> > 我并不知道哪几行会合并，你可以看我回答另一个人的问题，我是那样去做的，如果有更好的方法请告知
> 
> 这个是异步解析的。所以没法知道那几行合并了。但是可以做成 ，全部数据解析完成了，然后再通知你那几行合并了。关键你的应用场景是啥？

对导入的数据做校验，然后过滤入库。怎么告诉我哪几行是合并行呢?有什么API去判断吗？

**Comment by zhuangjiaju** [comment]
> > > > > > 对 合并单元格 就第一格有数据 后面数据都为空
> > > > > 
> > > > > 
> > > > > 你是怎么处理的呢？
> > > > 
> > > > 
> > > > 你要知道那几格合并了？应该知道第一格数据就行了吧。你的应用场景是啥
> > > 
> > > 
> > > 我并不知道哪几行会合并，你可以看我回答另一个人的问题，我是那样去做的，如果有更好的方法请告知
> > 
> > 
> > 这个是异步解析的。所以没法知道那几行合并了。但是可以做成 ，全部数据解析完成了，然后再通知你那几行合并了。关键你的应用场景是啥？
> 
> 对导入的数据做校验，然后过滤入库。怎么告诉我哪几行是合并行呢?有什么API去判断吗？

目前木有…… 可以加入 在所有数据解析完成后。解析合并

**Comment by 453055141** [comment]
我写的很死板，就是根据合并的不能为空的几列去判断，如果合并的这几列都没有值，则99.9%的概率是合并行。因为easyexcel读取合并行的时候，只能取到合并第一行值，后面几行是没有值的，所以可以利用是否全部为空来判断是不是合并行，并且在读取有值的行时，需要在循环外定义一个对象来存放这一合并行的值，后面根据判断是合并行的话，利用在循环外定义的对象赋值给后面的合并行。




------------------ 原始邮件 ------------------
发件人: "Jiaju Zhuang"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 晚上9:20
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "大坏蛋，emmm"<453055141@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 你好 请问如何读取合并单元格的数据？ (#447)




Closed #447.

**Comment by jingminghao** [comment]
不喝

> 我写的很死板，就是根据合并的不能为空的几列去判断，如果合并的这几列都没有值，则99.9%的概率是合并行。因为easyexcel读取合并行的时候，只能取到合并第一行值，后面几行是没有值的，所以可以利用是否全部为空来判断是不是合并行，并且在读取有值的行时，需要在循环外定义一个对象来存放这一合并行的值，后面根据判断是合并行的话，利用在循环外定义的对象赋值给后面的合并行。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Jiaju Zhuang"<notifications@github.com>; 发送时间: 2019年9月5日(星期四) 晚上9:20 收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>; 抄送: "大坏蛋，emmm"<453055141@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [alibaba/easyexcel] 你好 请问如何读取合并单元格的数据？ (#447) Closed #447. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

你的方式不合理，如果以导出的excel作修改，拿着修改的excel导入，会出现合并的第一行是修改的数据，其他还是旧数据。
