### ISSUE TITLE
excel中以货币类型格式的数字，目前不能直接读取成BigDecimal,能否将“,”移除

### ISSUE THREAD

**Issue by DongXiaoxie** [alibaba/easyexcel#448]
<img width="490" alt="大数字" src="https://user-images.githubusercontent.com/24628889/61111435-24387f00-a4bc-11e9-9d1d-332a58de16d9.png">

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel  。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
