### ISSUE TITLE
希望后面能添加对csv文件导出的功能

### ISSUE THREAD

**Issue by chenyu9390** [alibaba/easyexcel#450]
希望后面能添加对csv文件导出的功能

**Comment by Uetty** [comment]
csv文件，其实不需要这个工具，用文本编辑器打开csv文件，会发现每一行用逗号分割而已，很简单

**Comment by huanghe2015** [comment]
CSV就是逗号分隔的文本文件，自己一个小时就能撸一个出来的。

**Comment by zhuangjiaju** [comment]
非常感谢您的意见。我们内部讨论了下。会在后续支持，但是优先级比较低。
