### ISSUE TITLE
你好，请问支持斜线表头吗？

### ISSUE THREAD

**Issue by evanyangg** [alibaba/easyexcel#452]
![image](https://user-images.githubusercontent.com/22952321/61353268-f3808d00-a8a1-11e9-94cb-18dc08e8e6c1.png)
想这样的斜线表头，请问支持吗

**Comment by Uetty** [comment]
看了源码，应该不支持

**Comment by zhuangjiaju** [comment]
使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md#customHandlerWrite 自定义拦截器。然后使用poi的接口去处理

**Comment by Uetty** [comment]
easyexcel默认设计自动合并单元格，poi如果有这个功能的话可以在handler中手动判断第几格，使用poi的来实现


 
---原始邮件---
发件人: "Jiaju Zhuang"<notifications@github.com&gt;
发送时间: 2019年8月28日(星期三) 晚上8:08
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Uetty"<vincent_field@foxmail.com&gt;;
主题: Re: [alibaba/easyexcel] 你好，请问支持斜线表头吗？ (#452)



使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md#customHandlerWrite 自定义拦截器。然后使用poi的接口去处理
