### ISSUE TITLE
新增统计行

### ISSUE THREAD

**Issue by CosmosNi** [alibaba/easyexcel#455]
你好，新版本里可以加入统计行吗？
目前，我在ExcelProperty加入里统计字段。
同时为每个线程创建本地map，将每个需要统计的field加入到本地map中，在addJavaObjectToExcel中判断字段是否需要统计总和，需要的在本地map中累加值。等全部遍历完后，新增一行统计行

**Comment by zhuangjiaju** [comment]
升级到最新版本。然后使用 `ReadSheetHolder#getTotal` 但是只要注意这个值不一定正确。想要知道正确的值 ，必须一行行读 然后累加
