### ISSUE TITLE
能否提供excel的从多少行开始，某列有哪些类型的方法

### ISSUE THREAD

**Issue by ylh23y** [alibaba/easyexcel#456]

**Comment by ylh23y** [comment]
存到数据库方便确认列的类型

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel  。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。设置`headRowNumber`即可。需要知道类型 可以用 CellData作为成员变量去接收
