### ISSUE TITLE
导出excel 强制自动换行

### ISSUE THREAD

**Issue by caohangbo** [alibaba/easyexcel#460]
导出excel 的时候，设置了excel 内容超出单元格时会自动换行，数据量过大会导致导出的excel打不开，请问这个怎么取消

**Comment by tzou24** [comment]
同问，导出 Excel 一行数据需要换多行，请教一下如何实现？

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel  。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。自定义`style`应该能实现。实在不行自定义拦截器

**Comment by TheFlase** [comment]
> 同问，导出 Excel 一行数据需要换多行，请教一下如何实现？

后来解决了吗

**Comment by ConnoonWoo** [comment]
> > 同问，导出 Excel 一行数据需要换多行，请教一下如何实现？
> 
> 后来解决了吗

WriteCellStyle中有个Wraped属性就是控制自动换行的,可以看看HorizontalCellStyleStrategy源码，可以对head和content分别设置
WriteCellStyle cellStyle = new WriteCellStyle();
cellStyle.setWrapped(true);
HorizontalCellStyleStrategy strategy = new HorizontalCellStyleStrategy();
strategy.setContentWriteCellStyleList(Collections.singletonList(cellStyle));
EasyExcel.registerWriteHandler(strategy);
