### ISSUE TITLE
StyleUtil.buildDefaultCellStyle 方法修改建议

### ISSUE THREAD

**Issue by chenshouzhang** [alibaba/easyexcel#461]
我个人为该方法com.alibaba.excel.util.StyleUtil.buildDefaultCellStyle(Workbook workbook)应该再加上setBorderRight(BorderStyle.THIN);和setBorderTop(BorderStyle.THIN);设置

**Comment by zhuangjiaju** [comment]
非感觉您的意见。这个已经在新版加入了
