### ISSUE TITLE
导出小数位数问问题

### ISSUE THREAD

**Issue by zhangyenull** [alibaba/easyexcel#465]
bigdecimal 两位小数怎么解决，

**Comment by zhuangjiaju** [comment]
请参照 手册书写 。`@NumberFormat` 注解

**Comment by williamHappy** [comment]
`@NumberFormat("#.##")` 
模板填充
BigDecimal类型，写入数据未保留两位小数，未生效

**Comment by paranoiddemon** [comment]
> `@NumberFormat("#.##")`
> 模板填充
> BigDecimal类型，写入数据未保留两位小数，未生效

请问解决了吗
