### ISSUE TITLE
导入的excel中为时间，后端用yyyy/mm/dd接收，用户不填写时间报错应该怎么去处理呢

### ISSUE THREAD

**Issue by ghsy2233** [alibaba/easyexcel#469]

**Comment by zsf513** [comment]
这应该是你自己的业务处理，和easyexcel应该没有关系吧。

**Comment by ghsy2233** [comment]
描述有点不对，用户没有按照所规定的格式填写时间，而是填写了中文上去，工具包抛出的异常

**Comment by zhangsen540445123** [comment]
如果实体类里定义的是Date类型，在读取到数据后封装之前做下类型校验，如果不是日期类型，响应前台错误信息

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
然后自定义转换器 可以解决。或者实现 `AnalysisEventListener`的`onException` 在抛异常的时候 也继续处理
