### ISSUE TITLE
导入excel小数位最多仅允许10位,需要怎么解决

### ISSUE THREAD

**Issue by dingxiaowei773** [alibaba/easyexcel#470]

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。如果还是不行 请尝试使用自定义转换器 。quickstart里面有
