### ISSUE TITLE
readBySax自动flush问题

### ISSUE THREAD

**Issue by mimajiushi** [alibaba/easyexcel#471]
调用完readBySax后输入流就被清空了，导致无法通过循环读多个sheet

**Comment by zw1one** [comment]
我也遇到了你这个问题，读取多个sheet可以参考项目中的这个测试代码
```
com.alibaba.easyexcel.test.ReadTest.saxReadSheetsV2007();
```

**Comment by mimajiushi** [comment]
> 我也遇到了你这个问题，读取多个sheet可以参考项目中的这个测试代码
> 
> ```
> com.alibaba.easyexcel.test.ReadTest.saxReadSheetsV2007();
> ```

谢谢，看到了，问题解决了
