### ISSUE TITLE
导出列表最后一列缺少右边框

### ISSUE THREAD

**Issue by Zxhhhh** [alibaba/easyexcel#473]
大神的组件很赞，性能也不错，就是导出XLSX表格的最后一列会没有右边框，使的每个导出都要加上WriteHandler检查最后一行修改单元格样式，有点消耗性能

**Comment by xdcrazyboy** [comment]
我也遇到了这个问题，很尴尬

**Comment by zhuangjiaju** [comment]
这个已经在新版本修复，非常感谢宝贵的意见
