### ISSUE TITLE
导入导出数据涉及数据字典

### ISSUE THREAD

**Issue by karakiel** [alibaba/easyexcel#474]
导入导出数据涉及数据字典的有什么好的处理方式吗

**Comment by liuliu2018** [comment]
内部可以提供接口。你实现接口返回数据字典。

**Comment by karakiel** [comment]
> 内部可以提供接口。你实现接口返回数据字典。

是不是需要修改源码？

**Comment by zhuangjiaju** [comment]
使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 然后自定义 `Converter`去转换
