### ISSUE TITLE
当excel条数超过2000的时候无法识别当前文件为excel

### ISSUE THREAD

**Issue by masterchengsheng** [alibaba/easyexcel#476]
>1.1.2-beta5 版本   
``` ExcelTypeEnum typeEnum = ExcelTypeEnum.valueOf(file.getInputStream());````
 无法识别当前文件的类型 返回的是null

**Comment by masterchengsheng** [comment]
public static ExcelTypeEnum valueOf(InputStream inputStream){
        try {
            if (!inputStream.markSupported()) {
                return null;
            }
            FileMagic fileMagic =  FileMagic.valueOf(inputStream);
            if(FileMagic.OLE2.equals(fileMagic)){
                return XLS;
            }
            if(FileMagic.OOXML.equals(fileMagic)){
                return XLSX;
            }
            return null;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

**Comment by zhuangjiaju** [comment]
您可以尝试使用最新版本再试下这个问题。理论上老版本也不存在这个问题。如果还存在，建议您把数据混淆下，并提供xlsx
