### ISSUE TITLE
listener模式中，为什么考虑用数组接受行数据?

### ISSUE THREAD

**Issue by LeasonX** [alibaba/easyexcel#479]
如图，默认初始化数组容量为20，150%扩容，最后将数组转成ArrayList，如果只有一列数据的excel，至少也要占用20个数组容量，为什么不直接用LinkedList来实现呢？
![企业微信截图_15650632391227](https://user-images.githubusercontent.com/15868922/62509979-f71f8800-b83f-11e9-96e9-93ba88b87d87.png)
![企业微信截图_15650632648088](https://user-images.githubusercontent.com/15868922/62509992-0272b380-b840-11e9-9bb2-312c4fbe9001.png)
![企业微信截图_15650632758185](https://user-images.githubusercontent.com/15868922/62510000-08689480-b840-11e9-8f6f-9b40ec2923c5.png)

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
