### ISSUE TITLE
怎么给指定的单元格设值呢？

### ISSUE THREAD

**Issue by tkggft** [alibaba/easyexcel#484]

**Comment by BradyWZH** [comment]
+1  我也想知道

**Comment by zhuangjiaju** [comment]
自己实现拦截器 SheetWriteHandler 后可以获取到sheet 然后设置值即可

**Comment by swallow777** [comment]
> 自己实现拦截器 SheetWriteHandler 后可以获取到sheet 然后设置值即可

自己实现拦截器 SheetWriteHandler 后， 是不是就会影响.doWrite()，导致数据行下移？
