### ISSUE TITLE
Maven的上的版本是1.1.1 导入是有问题的，现在是1.1.2-beta4没问题，但是1.1.2正式版啥时候发布

### ISSUE THREAD

**Issue by haopangang** [alibaba/easyexcel#486]

**Comment by auguso** [comment]
确实有这样的问题，1.1.1导入报NoClassDefFoundError: org/apache/poi/poifs/filesystem/FileMagic，暂时换成了1.1.2beta版本

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
正式版会在1个月内发布
