### ISSUE TITLE
导出带百分比的数据,非字符串数据

### ISSUE THREAD

**Issue by jmying** [alibaba/easyexcel#489]
rt

**Comment by zhuangjiaju** [comment]
如果想把数字导入到excel变成文本的百分比，最新版本并参照demo书写。如果是想excel也是数字，就要自定义拦截器了，参照写入的 自定义拦截器

**Comment by HusenHuang** [comment]
请问有例子提供么。

**Comment by HusenHuang** [comment]
这边没使用注解，是通过Map去写入excel的，想excel中带%的，能够通过excel求平均数等
