### ISSUE TITLE
这种方式可以正确的判断excel版本吗？

### ISSUE THREAD

**Issue by OlnyBigRoc** [alibaba/easyexcel#490]
/**
     * 描述：根据文件版本自适应上传文件的版本
     */
    public static Workbook getWorkbook(InputStream inStr)
            throws Exception {
        Workbook wb;
        if (FileMagic.valueOf(inStr) == FileMagic.OLE2) {
            // 2003-
            wb = new HSSFWorkbook(inStr);
        } else if (FileMagic.valueOf(inStr) == FileMagic.OOXML) {
            // 2007+
            wb = new XSSFWorkbook(inStr);
        } else {
            throw new Exception("解析的文件格式有误！");
        }
        return wb;
    }

**Comment by OlnyBigRoc** [comment]
测试通过了 ，可是正确识别，总觉得用后缀问题会多一些

**Comment by marionlxy** [comment]
从3.10升级到3.17，这一块是不是已经自动识别呢
