### ISSUE TITLE
读取excel，映射没有生效

### ISSUE THREAD

**Issue by peiht** [alibaba/easyexcel#491]
代码如下：

Sheet sheet = new Sheet(2,1,DuoClubExcelModel.class);

 List<Object> read = EasyExcelFactory.read(inputStream, sheet);

读取的read中 object全是list，并非是model实体

**Comment by peiht** [comment]
引得包的问题

**Comment by Lnybb** [comment]
请问楼主怎么解决的啊？1.1.2-beta5 版本

**Comment by peiht** [comment]
> 请问楼主怎么解决的啊？1.1.2-beta5 版本
我新建了个工程，然后用这个包试了一下，是可以正确读取的，然后maven clean了一下原工程就可以 了。
