### ISSUE TITLE
多线程导出excel

### ISSUE THREAD

**Issue by nanase-takesi** [alibaba/easyexcel#492]
<img width="723" alt="image" src="https://user-images.githubusercontent.com/38271786/63168555-0b952900-c067-11e9-9974-2827370438ac.png">
鞥

**Comment by nanase-takesi** [comment]
多线程导出excel，发现无法导出完整的excel，文件打不开
![Uploading image.png…]()

**Comment by zhuangjiaju** [comment]
这个短期内肯定不会支持。没法知道您的数据要创建在第几行，一没法并发。唯一办法就是先创建好一堆，然后再慢慢的写入，但是性能也不会提升很高。

**Comment by pjf000** [comment]
> 这个短期内肯定不会支持。没法知道您的数据要创建在第几行，一没法并发。唯一办法就是先创建好一堆，然后再慢慢的写入，但是性能也不会提升很高。

我的需求是这样的：用户下载文件10s（有时sql执行比较久）内有响应则直接输出到浏览器，否则暂存到服务器指定目录，以便用户直接下载。于是用了futureTask.get() 方法，结果文件打不开。
