### ISSUE TITLE
只写@ExcelProperty(value = "XXX")不能读取么？

### ISSUE THREAD

**Issue by qq742464260** [alibaba/easyexcel#494]
只写@ExcelProperty(value = "XXX")不能读取么？业务需求对应的index可能会变，能不能只对应value的列呢

**Comment by qq742464260** [comment]
自己弄了个反射解决了，没去改源码，希望作者把这个问题解决了，好像反映这个问题的人还是蛮多的。

**Comment by Cao-Bin** [comment]
> 自己弄了个反射解决了，没去改源码，希望作者把这个问题解决了，好像反映这个问题的人还是蛮多的。

反射代码能简单提供下吗

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。

**Comment by qq742464260** [comment]
> > 自己弄了个反射解决了，没去改源码，希望作者把这个问题解决了，好像反映这个问题的人还是蛮多的。
> 
> 反射代码能简单提供下吗

兄弟，不好意思。刚上来，才看到。。。不过作者说已经修复了，哈哈，还是用作者的吧

**Comment by qq742464260** [comment]
> 这个已经在最新版本修复，请使用最新版本。[https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。](https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel%E3%80%82) 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。

好的，感谢。

**Comment by Cao-Bin** [comment]
ok
