### ISSUE TITLE
如何避免把空行当作数据读进来

### ISSUE THREAD

**Issue by diaowenyang** [alibaba/easyexcel#499]
作者您好：
  我在用easyexcel处理数据的时候，发现有时候会把空行读进来，当作用户填写的数据。请问这个问题应该怎么处理。谢谢！感谢您对开源世界的贡献。

**Comment by zhuangjiaju** [comment]
我查看最新版本 ，空行会自动忽略的，请尝试最新版本。如果还有问题，请提供问题文件
