### ISSUE TITLE
ExcelProperty注解能否支持多语言国际化？

### ISSUE THREAD

**Issue by yjmyzz** [alibaba/easyexcel#502]
有一些国际化的业务场景 ，比如 Student这个类，里面有name这个字段， 在中文站点上导出时，希望excel里的表头是”学生姓名“，在英文站点上导出时，表头是"Name"

另外对于日期型字段， 中文环境下一般会用yyyy-mm-dd(即：年-月-日)格式输出，但在英文环境下，一般会用mm/dd/yyyy（即：月/日/年）格式

所以，ExcelProperty注解可否扩展一下，加一些property，类似：

  @ExcelProperty(value = "生日", index = 2,i18nFormat = {"en-us|MM/dd/yyyy,zh-cn|yyyy-MM-dd"})
  private Date birthday;

  @ExcelProperty(value = "姓名", index = 1,i18nTitles = {"en-us|name,zh-HK|學生姓名"})
  private String name;

即：如果有多语言需求，在额外的i18nFormat ， i18nTitles 里写明每种语言对应的表头和转换格式

**Comment by huanghe2015** [comment]
这个是业务逻辑的事情，和本工具无关。

**Comment by zhuangjiaju** [comment]
非常感谢您的意见，我们内部讨论了下，近期版本不会支持国际化。如果国际化，可以用多个class来指定

**Comment by qq540814390** [comment]
我做了国际化扩展，可以参考下 https://blog.csdn.net/qq_28452049/article/details/106600268

**Comment by Harrdy2018** [comment]
> 我做了国际化扩展，可以参考下 https://blog.csdn.net/qq_28452049/article/details/106600268
你用EasyExcel做国家化的时候有碰到。Excel能下载下来，但是 打开的时候报错 "文件格式和扩展名不匹配。文件可能已损坏或不安全"

**Comment by Harrdy2018** [comment]
@qq540814390 你用EasyExcel做国家化的时候有碰到。Excel能下载下来，但是 打开的时候报错 "文件格式和扩展名不匹配。文件可能已损坏或不安全"

**Comment by qq540814390** [comment]
我没有遇到，检查一下你windows环境的Excel是不是有问题，EasyExcel后续版本好像更新了国际化功能，你也可以升级一下jar包试试。

**Comment by lingjunyang** [comment]
国际化，可以用多个class来指定。cv还是挺快的，但是希望可以适配一下！！
