### ISSUE TITLE
String格式手机号读取变成了Number格式

### ISSUE THREAD

**Issue by lx3xun** [alibaba/easyexcel#503]
在 2.0.0-beta1中，声明的数据类型为String, 打算接收手机号，但真正读取的时候确是以NUMBER来处理的，导致手机号变成了科学计数法的格式

String类型：
![image](https://user-images.githubusercontent.com/6147862/63735447-6d009780-c8b2-11e9-9370-8f84f9f29d5a.png)

读取确是Number
![image](https://user-images.githubusercontent.com/6147862/63735768-658dbe00-c8b3-11e9-9713-28b11c553798.png)

**Comment by zhuangjiaju** [comment]
使用 NumberFormat 。格式化数据。目前不支持读取excel中的样式 来格式数据，后续会支持
