### ISSUE TITLE
三级表头还是存在将单元格合并的问题

### ISSUE THREAD

**Issue by jianhh** [alibaba/easyexcel#504]
版本：1.1.2-beta5
系统：window7
描述：三级表头存在将第三级相同名称的单元格合并。
![image](https://user-images.githubusercontent.com/12593175/63757054-09935b80-c8ec-11e9-9adf-a4f0cc32d25a.png)

**Comment by jianhh** [comment]
先自己改了下，在value值加标识后缀，标识不合并，合并的时候判断。
![image](https://user-images.githubusercontent.com/12593175/63832362-38b8d400-c9a3-11e9-8885-47c8026dd7bf.png)
![image](https://user-images.githubusercontent.com/12593175/63832376-41110f00-c9a3-11e9-8189-1a0e08c77862.png)
先应付着先，后期修复了再看。

**Comment by jianhh** [comment]
我这边是主要是三级表头不需要合并，而且是动态表头，所以为了方便：
![image](https://user-images.githubusercontent.com/12593175/63832694-ee842280-c9a3-11e9-9b13-a6a535a4fbfc.png)

**Comment by zhuangjiaju** [comment]
如果不需要合并 请加入个空格之类的方式去解决。
