### ISSUE TITLE
xls上传问题

### ISSUE THREAD

**Issue by ws121736** [alibaba/easyexcel#505]
解析xls格式  AnalysisContext 对象不能获取总行数

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。但是由于异步解析，总行数可能不一定完全正确。需要完全正确的需要自己写监听器，并且读完所有数据去累加
