### ISSUE TITLE
v2.0版本WriteHandler重复执行问题

### ISSUE THREAD

**Issue by Bin-mario** [alibaba/easyexcel#506]
com/alibaba/excel/write/metadata/holder/AbstractWriteHolder.java:331

> 
   for (WriteHandler writeHandler : cleanUpHandlerList) {
            if (writeHandler instanceof CellWriteHandler) {
                result.get(CellWriteHandler.class).add(writeHandler);
            }
            if (writeHandler instanceof RowWriteHandler) {
                result.get(RowWriteHandler.class).add(writeHandler);
            }
            if (writeHandler instanceof SheetWriteHandler) {    //1
                result.get(SheetWriteHandler.class).add(writeHandler);
            }
            if (writeHandler instanceof SheetWriteHandler) {
                result.get(SheetWriteHandler.class).add(writeHandler); //2  1和2 是重复代码
            }
            if (writeHandler instanceof WorkbookWriteHandler) {
                result.get(WorkbookWriteHandler.class).add(writeHandler);
            }
            result.get(WriteHandler.class).add(writeHandler); //3此处会导致cleanUpHanderList 里面的Handler被放置两次
        }

**Comment by zhuangjiaju** [comment]
OK。非常感谢。这个问题会导致 `SheetWriteHandler`会执行多次。已经修复。其中3 改成在增加parent的`WriteHandler`的时候 直接去获取`result.get(WriteHandler.class)`

**Comment by Bin-mario** [comment]
> OK。非常感谢。这个问题会导致 `SheetWriteHandler`会执行多次。已经修复。其中3 改成在增加parent的`WriteHandler`的时候 直接去获取`result.get(WriteHandler.class)`

感谢及时修复，1和2 只需删除一处就可以了，3 处是否删除，看此处是否需要一个WriteHandler基类 存放所有的handler
