### ISSUE TITLE
1.1.2beta4 这个版本的converter不见了？

### ISSUE THREAD

**Issue by JasonTang0606** [alibaba/easyexcel#508]
1.1.2beta4 这个版本的converter不见了？
需要用到自定义converter，但是发现连jar包里面没有converter这个目录  😨

**Comment by JasonTang0606** [comment]
现在最新版是2.0了，我 试试

**Comment by zhuangjiaju** [comment]
请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
