### ISSUE TITLE
单元格内容包含:<>符号时，读取结果混乱

### ISSUE THREAD

**Issue by msqp** [alibaba/easyexcel#52]
![_001](https://user-images.githubusercontent.com/31834292/44244727-f42f2000-a207-11e8-98c6-32e75199e52b.png)
![_002](https://user-images.githubusercontent.com/31834292/44244742-08731d00-a208-11e8-8098-1e71f05d2f02.png)
单元格内容包含:<>时，读取结果混乱

**Comment by jipengfei-jpf** [comment]
由于1.0.*版本核心考虑的是怎么解决读excel内存溢出问题，自己重写了读excel的POI的底层，写仍旧使用POI。可以从根本解决OOM问题。但是由于自己对excel的格式认识不全面，有很多坑产生了很多BUG。最新版本以POI为底层。最新版：1.1.2-beat1，虽然不能完全解决OOM但可以解决大部分的OOM问题，完全解决OOM版本会等稳定后再开放。目前依赖POI版本1.1.2-beat1
