### ISSUE TITLE
通过模板导出时传入list<list<object>>数据，导出的数据少了最后一列

### ISSUE THREAD

**Issue by dieeman** [alibaba/easyexcel#526]

**Comment by zhuangjiaju** [comment]
请提供源代码

**Comment by dieeman** [comment]
private void addBasicTypeToExcel(List<Object> oneRowData, Row row, int relativeRowIndex) {
        if (CollectionUtils.isEmpty(oneRowData)) {
            return;
        }
        Map<Integer, Head> headMap = context.currentWriteHolder().excelWriteHeadProperty().getHeadMap();
        int dataIndex = 0;
        int cellIndex = 0;
        for (Map.Entry<Integer, Head> entry : headMap.entrySet()) {
            if (dataIndex >= oneRowData.size()) {
                return;
            }
            cellIndex = entry.getKey();
            Head head = entry.getValue();
            doAddBasicTypeToExcel(oneRowData, head, row, relativeRowIndex, dataIndex++, cellIndex);
        }
        // Finish
        if (dataIndex >= oneRowData.size()) {
            return;
        }
        if (cellIndex != 0) {
            cellIndex++;
        }
        for (int i = 0; i < oneRowData.size() - dataIndex; i++) {//此处减去dataindex后遍历次数减少无法全部遍历出oneRowData中的数据
            doAddBasicTypeToExcel(oneRowData, null, row, relativeRowIndex, dataIndex++, cellIndex++);
        }
    }

**Comment by dieeman** [comment]
还有当oneRowData.get（i）为null时，获取不到oneRowData.get（i）的class，会报空指针

**Comment by zhuangjiaju** [comment]
> 还有当oneRowData.get（i）为null时，获取不到oneRowData.get（i）的class，会报空指针

这个请提供测试数据

**Comment by zhuangjiaju** [comment]
已经在2.0.0-beat4 修复 非常感谢您的意见
