### ISSUE TITLE
如何添加超链接？

### ISSUE THREAD

**Issue by hahaduo** [alibaba/easyexcel#53]
如题，如何给某个cell添加超链接？
poi是可以的，如下代码所示：
`cell = row.createCell(colNumber)。
cell.setCellType(HSSFCell.CELL_TYPE_FORMULA);
cell.setCellFormula("HYPERLINK(\"" + "Http://www.google.ca"+ "\",\"" + "Google Canada"+ "\")");
或cell.setCellFormula("HYPERLINK(\"[workbook.xls]'sheet2'!A1\",\"homepage\")"); //HYPERLINK("#明细!A1","homepage")`
我查看了一下源代码，好像没有把这个功能带过来，也就是没有实现。

**Comment by jipengfei-jpf** [comment]
下个版本会支持

**Comment by foresx** [comment]
现在是不是暂时还没支持超链接？
