### ISSUE TITLE
10万+的数据一次性导出会造成服务器内存一直占用，怎么处理

### ISSUE THREAD

**Issue by LockieZou** [alibaba/easyexcel#531]

**Comment by zhuangjiaju** [comment]
请提供源代码。参照 快速使用 去书写。并升级到beta3。 如果内存还没释放 请检查 是否内存占用的 非easyexcel的对象。

**Comment by LockieZou** [comment]
/**
     * 导出单个sheet
     * @param response
     * @param dataList
     * @param sheet
     * @param fileName
     * @throws UnsupportedEncodingException
     */
    public static void writeExcelOneSheet(HttpServletResponse response, List<? extends BaseRowModel> dataList, Sheet sheet, String fileName) {
        if (CollectionUtils.isEmpty(dataList)) {
            return;
        }
        // 如果sheet为空，则使用默认的
        if (null == sheet) {
            sheet = initSheet;
        }

        ServletOutputStream out = null;
        try {
            String value = "attachment; filename=" + new String(
                    (fileName + new SimpleDateFormat("yyyyMMdd").format(new Date()) + ExcelTypeEnum.XLSX.getValue()).getBytes("gb2312"), "ISO8859-1");
            response.setContentType("multipart/form-data");
            response.setCharacterEncoding("utf-8");
            response.setContentType("application/vnd.ms-excel;charset=utf-8");
            response.setHeader("Content-disposition", value);
            out = response.getOutputStream();
            ExcelWriter writer = EasyExcelFactory.getWriter(out, ExcelTypeEnum.XLSX, true);
            // 设置属性类
            sheet.setClazz(dataList.get(0).getClass());
            writer.write(dataList, sheet);
            writer.finish();
            out.flush();
            out.close();
        } catch (IOException e) {
            logger.error("导出失败，失败原因：{}", e);
        }
    }

**Comment by allenwtl** [comment]
你是怎么解决了
