### ISSUE TITLE
新版不支持写多个sheet了吗？如果可以，要怎么做，给个demo？

### ISSUE THREAD

**Issue by 029ye** [alibaba/easyexcel#534]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示
**建议描述**

**Comment by Ryoui** [comment]
可以有个方法，不过我搞忘了。如果你还有以前的方法，会提示过时了，然后点进去，你就会看见用哪个替换过时的

**Comment by zhuangjiaju** [comment]
参照 简单的写，方法2 即可。new 2次 writesheet
