### ISSUE TITLE
自动列宽无效

### ISSUE THREAD

**Issue by czbphoto** [alibaba/easyexcel#539]
<version>1.1.2-beta5</version> 版本   sheet.setAutoWidth(true);设置自动列宽导出excel没有效果

**Comment by zhuangjiaju** [comment]
您好 1.1.2-beta 自动列宽未做实现。所以未生效。升级到最新版有个可以实现的，但是也不是完美实现，如果有完美的方案 可以一起探讨。建议升级到最新版本 并安装手册操作
