### ISSUE TITLE
无法通过获取sheet页的方式，得到指定sheet页下的数据

### ISSUE THREAD

**Issue by ututuut** [alibaba/easyexcel#543]
**触发场景描述**
版本：<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>2.0.0-beta1</version>
        </dependency>
**触发Bug的代码**
按照demo里的代码可以获取指定sheet下的数据
 List<Object> datas = EasyExcel.read(fileName).sheet(0).doReadSync(); // 可以获取指定sheet下的数据
下面这种获取不到
       ExcelReader excelReader =  EasyExcel.read(fileName).build();
List<Sheets> sheets = excelReader.getSheets();
// sheets为空
        Map<String,List<Map<Integer,Object>>> datas = new LinkedHashMap();
        for(Sheet sheet:sheets){
            List<Object> sheetData = EasyExcel.read(fileName).sheet(sheet.getSheetName()).doReadSync();
        }
        ReadSheet readSheet1 = EasyExcel.readSheet(0).build();
        ReadSheet readSheet2 = EasyExcel.readSheet(1).build();
        excelReader.read(readSheet1);
        excelReader.read(readSheet2);
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
请参照文档 书写。你需要加入监听器
