### ISSUE TITLE
可不可以不用指定用哪个类去读？

### ISSUE THREAD

**Issue by asp1111** [alibaba/easyexcel#545]
**建议描述**
我想要写一个通用的导出EXCEL的方法，但是easyexcel要求一定要建一个类似model类的类，这就意味着我每加一个报表就需要添加一个类，如果只是需要表头信息，是不是可以换一种形式，比如json之类的

**Comment by zhuangjiaju** [comment]
write入参 支持 List<List<Obejct>>
