### ISSUE TITLE
AnalysisEventListener 继承类里面，@Autowired注入类报空指针异常

### ISSUE THREAD

**Issue by xiangshang190823** [alibaba/easyexcel#546]
![image](https://user-images.githubusercontent.com/21261032/64269809-1e679300-cf6d-11e9-9299-29b85ce6386f.png)

![image](https://user-images.githubusercontent.com/21261032/64269841-2d4e4580-cf6d-11e9-80e5-47a1331dcdab.png)
![image](https://user-images.githubusercontent.com/21261032/64269870-3b9c6180-cf6d-11e9-91eb-43f385a83321.png)
![image](https://user-images.githubusercontent.com/21261032/64269920-4c4cd780-cf6d-11e9-9add-1894439256e0.png)

**Comment by zhuangjiaju** [comment]
这个是spring基础。new的对象不归spring管理 所以不能注入。你加个构造方法 传入需要的对象

**Comment by xiangshang190823** [comment]
谢谢大佬指点




------------------ 原始邮件 ------------------
发件人: "Jiaju Zhuang"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 晚上8:46
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "小魔头"<1041975591@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/easyexcel] AnalysisEventListener 继承类里面，@Autowired注入类报空指针异常 (#546)




这个是spring基础。new的对象不归spring管理 所以不能注入。你加个构造方法 传入需要的对象
