### ISSUE TITLE
请问，poi3.9适配easyexcel版本是哪一个

### ISSUE THREAD

**Issue by tys87198312** [alibaba/easyexcel#555]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示
**建议描述**

**Comment by zhuangjiaju** [comment]
请使用最新版

**Comment by ZhuTail** [comment]
项目中本来是用了poi的3.9版本，今天试着引入了easyexcel2.26的依赖，使用demo，https://github.com/alibaba/easyexcel/blob/master/src/test/java/com/alibaba/easyexcel/test/demo/web/WebTest.java，抛出 `Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/poi/util/TempFileCreationStrategy`的异常，是不是easyexcel只能使用3.17的poi呢，有没有什么方法做到兼容呢？
