### ISSUE TITLE
根据模板写入 方法 存在head多出一行的问题  是我使用的有问题吗

### ISSUE THREAD

**Issue by shenqicheng100** [alibaba/easyexcel#563]
**异常代码**
```
    @Test
    public void templateWrite() {
        String templateFileName = "E:/" + "demo.xlsx";
        String fileName = "E:/" + "templateWrite" + System.currentTimeMillis() + ".xlsx";
        // 这里 需要指定写用哪个class去读，然后写到第一个sheet，名字为模板 然后文件流会自动关闭
        EasyExcel.write(fileName, DemoData.class).withTemplate(templateFileName).sheet().doWrite(data());
    }
```
**问题描述**

demo.xlsx
![TIM图片20190909152615](https://user-images.githubusercontent.com/34977303/64511127-39902500-d316-11e9-8756-be3a551e453c.png)

导出的excel
![5](https://user-images.githubusercontent.com/34977303/64511312-9ee41600-d316-11e9-9535-1fadfe8dee76.png)

实体对象
![6](https://user-images.githubusercontent.com/34977303/64511347-b4594000-d316-11e9-9f8d-02aece91aac0.png)

**Comment by shenqicheng100** [comment]
**问题解决 这样写没问题**
```
    @Test
    public void templateWrite() {
        String templateFileName = "E:/" + "demo.xlsx";
        String fileName = "E:/" + "templateWrite" + System.currentTimeMillis() + ".xlsx";
        // 这里 需要指定写用哪个class去读，然后写到第一个sheet，名字为模板 然后文件流会自动关闭
        EasyExcel.write(fileName, DemoData.class).withTemplate(templateFileName).sheet().doWrite(data());
    }
```

**Comment by whpat126** [comment]
> 
> 
> **问题解决 这样写没问题**
> 
> ```
>     @Test
>     public void templateWrite() {
>         String templateFileName = "E:/" + "demo.xlsx";
>         String fileName = "E:/" + "templateWrite" + System.currentTimeMillis() + ".xlsx";
>         // 这里 需要指定写用哪个class去读，然后写到第一个sheet，名字为模板 然后文件流会自动关闭
>         EasyExcel.write(fileName, DemoData.class).withTemplate(templateFileName).sheet().doWrite(data());
>     }
> ```

看着没做啥改动？就可以了？

**Comment by shenqicheng100** [comment]
@whpat126 尴尬没有复制上  已经改了评论 加了 .needHead(false)

**Comment by shenqicheng100** [comment]
@whpat126  抱歉啊

**Comment by whpat126** [comment]
@shenqicheng100 学习了
