### ISSUE TITLE
org.apache.poi.ss.usermodel.Workbook.close()V

### ISSUE THREAD

**Issue by hlzha** [alibaba/easyexcel#565]
**异常代码**
执行这一段代码就报错 老版本writer.write(page.getList(), sheet); 
在老版本执行可以的，换成你新版本写法还是一样的报错
```java
   这里写你的代码
ServletOutputStream out = response.getOutputStream(); response.setContentType("multipart/form-data"); response.setCharacterEncoding("utf-8"); response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx"); ExcelWriter writer = EasyExcelFactory.getWriter(out); // 设置SHEET Sheet sheet = new Sheet(1, 1, AgentCostmanage.class, "表1", null); writer.write(page.getList(), sheet); writer.finish(); out.flush();
```
**异常提示**
Caused by: java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Workbook.close()V
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:350)
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by hlzha** [comment]
<dependency> 	<groupId>com.alibaba</groupId> 	<artifactId>easyexcel</artifactId> 	<version>2.0.0-beta5</version> </dependency>
如果和poi 3.17版本执行是可以的

换成poi 4.0.1就报那个错

检查了项目没有发现poi版本冲突的问题

**Comment by zhuangjiaju** [comment]
这个应该是版本冲突的问题。请检查下 Workbook 有没有colose方法

**Comment by hlzha** [comment]
是的，接口有这个方法，下面的类也有，很奇怪，用3.17就可以，我就纳闷了
