### ISSUE TITLE
导出会将Model类中final static字段也作为表头输出

### ISSUE THREAD

**Issue by liaow** [alibaba/easyexcel#567]
**触发场景描述**
导出会将Model类中final static字段也作为表头输出
![image](https://user-images.githubusercontent.com/3170158/64592279-38c2c600-d3de-11e9-8226-7323bb18caf9.png)

**触发Bug的代码**
在测试Model中增加`private final static String TITLE = "主标题";`
```java
@Data
public class ComplexHeadData {
    private final static String TITLE = "主标题";
    @ExcelProperty({TITLE, "字符串标题"})
    private String string;
    @ExcelProperty({TITLE, "日期标题"})
    private Date date;
    @ExcelProperty({TITLE, "数字标题"})
    private Double doubleData;
}
```
执行测试方法 WriteTest.complexHeadWrite

**提示的异常或者没有达到的效果**
无异常，需要过滤final static类型字段（属性）

**Comment by liaow** [comment]
虽然可以用@ExcelIgnore注解忽略，但是通常情况下开发者容易误认为该类型字段（属性）就应该默认被忽略掉。是否修改源码默认忽略呢

**Comment by zhuangjiaju** [comment]
这个想法不错 下个 或者下下个版本会改。这个版本应该不会改。这个版本尽量先发布稳定版再说

**Comment by joffreychen** [comment]
怎么忽视model一些字段不导出，或者说能不能自由选择model中的导出字段呢

**Comment by liaow** [comment]
> 怎么忽视model一些字段不导出，或者说能不能自由选择model中的导出字段呢

静态的代码可以在model属性上使用@ExcelIgnore

**Comment by joffreychen** [comment]
> > 怎么忽视model一些字段不导出，或者说能不能自由选择model中的导出字段呢
> 
> 静态的代码可以在model属性上使用@ExcelIgnore

谢谢大佬的指导，@ExcelIgnore解决了我的问题

**Comment by zhuangjiaju** [comment]
已经在 最新版本修复
