### ISSUE TITLE
导出数据含有蓝色背景列

### ISSUE THREAD

**Issue by VectorWen** [alibaba/easyexcel#569]
![image](https://user-images.githubusercontent.com/6134525/64597919-56e1f380-d3e9-11e9-9582-39a9dadeab07.png)

当数据超过11列，之后的列表的内容背景全部变为了蓝色，查了很久还是无法处理。

**Comment by zhuangjiaju** [comment]
提供导出代码 理论上来说不会出现这种问题。

**Comment by VectorWen** [comment]
sorry ，我的错，测试背景色的代码忘记删除了，导致的这种问题。
