### ISSUE TITLE
@HeadRowHeight在动态表头时无效

### ISSUE THREAD

**Issue by layou1989** [alibaba/easyexcel#572]
使用了动态表头，发现设置的@HeadRowHeight无效

@HeadRowHeight(50)
@ContentRowHeight(20)
@Data
public class UserExportVO {
}

EasyExcel.write(response.getOutputStream()).head(headers) .sheet(sheetName).table().head(clazz).needHead(false).doWrite(data);

**Comment by zhuangjiaju** [comment]
这个设计就是这样子的。如果是动态表头 ，请使用 `SimpleRowHeightStyleStrategy` 和 `SimpleColumnWidthStyleStrategy` 或者自定义策略。`@HeadRowHeight` 也是实现了这两个策略而已。

**Comment by layou1989** [comment]
got it

**Comment by layou1989** [comment]
> 这个设计就是这样子的。如果是动态表头 ，请使用 `SimpleRowHeightStyleStrategy` 和 `SimpleColumnWidthStyleStrategy` 或者自定义策略。`@HeadRowHeight` 也是实现了这两个策略而已。

got it
