### ISSUE TITLE
建议增加注解对字段只读只写读写属性

### ISSUE THREAD

**Issue by getpro** [alibaba/easyexcel#573]
有些字段只需要在写入的时候用到，有些是读的时候用到，目前只能忽略，没办法针对指定字段进行读写控制

**Comment by zhuangjiaju** [comment]
非常感谢您的意见。因为大部分需求只有单独的读或者写，或者读写都需要忽略。所以暂时性不考虑读写分开。目前第三方工具 比如json 也不会说读写分开的。有其他好的想法 欢迎再次提出来

**Comment by wenchaomartin** [comment]
即便是某些字段不支持 只读， 也可以提供  cell  单元格的disabled editor .方法
