### ISSUE TITLE
请问下，为什么读完文件后，文件的修改日期会变？

### ISSUE THREAD

**Issue by BradyWZH** [alibaba/easyexcel#574]
**异常代码**
使用的读代码如下：
```java
   EasyExcel.read(filePath, listener).sheet(0).doRead()
```
**异常提示**
使用完全正常，文件大小的字节数也完全一样，就是很好奇，为什么明明是读文件，但是文件的修改时间会变；此处修改时间指的是  windows 文件夹中 修改日期  这一列
**建议描述**

**Comment by jilliss** [comment]
我测试了下  并没有发现这个问题呀，不管是xls还是xlsx 格式的文件
PS. 我是直接用的 测试代码 
`com.alibaba.easyexcel.test.demo.read.ReadTest `
### 环境
`Windows 10`
### JDK 版本
`openjdk-7`

**Comment by sjmingdna** [comment]
谢谢您的回答，后来发现是Excel的问题，Excel会自动转换，在前面加一个英文的单引号就好了




------------------ 原始邮件 ------------------
发件人: "zared"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 下午2:05
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 请问下，为什么读完文件后，文件的修改日期会变？ (#574)




我测试了下  并没有发现这个问题呀，不管是xls还是xlsx 格式的文件
 PS. 我是直接用的 测试代码
 com.alibaba.easyexcel.test.demo.read.ReadTest 
 
环境
 
Windows 10
 
JDK 版本
 
openjdk-7

**Comment by zhuangjiaju** [comment]
这个是个Bug 已经在 2.0.5里面修复，非常感谢您的意见。
