### ISSUE TITLE
解析 xlsx时 ，AnalysisEventListener类的 invoke（）方法中 空行空格过滤掉了吗？

### ISSUE THREAD

**Issue by likunping77** [alibaba/easyexcel#581]
public class ExcelListener extends AnalysisEventListener  {

 public void invoke(Object object, AnalysisContext context) {
        System.out.println("当前行：" + context.getCurrentRowNum());
        System.out.println(object);
        // 发现ojbect里 本来我一行有40列， 其中只有24列有数据 ， 但是ojbect 集合里size只有24,怎样才能实现把空行也当作object的一列？ 需求：ojbect  size=40
    }

｝

**Comment by jiangdashuai** [comment]
easy excel中有没有check空行的方法，就是一行数据都是空的字符串，我导入时他也算一条数据，我就没法计算导入了多少条，现在我想在读的时候就不读进来，请问一下有这个check吗？

**Comment by tuean** [comment]
+1

**Comment by zhuangjiaju** [comment]
轻尝试升级到2.0.5 然后设置 ignoreEmptyRow 为false ，如果还有问题 请提供 源代码和excel
