### ISSUE TITLE
Excel中为数字类型，Model中字段为String类型，会转成科学计数法

### ISSUE THREAD

**Issue by liuhui8278** [alibaba/easyexcel#583]
excel获取对应的值的时候是否可以根据Model中声明的类型取转换？ 这样就算是字符串类型，也不会因为excel中是数字类型而被转化成科学计数法了
用你的NumberFormat 或者 Convert重写，岂不是每个String类型都的加上，这样太麻烦了。因为每个String类型里面都可能填的有光数字的

**Comment by zhuangjiaju** [comment]
已经在最新版本修复，请使用最新版本
