### ISSUE TITLE
怎么设置列为下拉框并设置下拉框数据呢

### ISSUE THREAD

**Issue by lianghongshuai** [alibaba/easyexcel#584]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by majianguo202** [comment]
> **异常代码**
> 
> ```java
>    这里写你的代码
> ```
> 
> **异常提示**
> 请提供完整的异常提示,记住是全部异常！
> **建议描述**


下载最新代码，查找这个关键字CustomSheetWriteHandler, 这个实例就是增加列下拉框的

**Comment by Zeng-Qe** [comment]
大约第一次体验到git的好用
