### ISSUE TITLE
poi 4已经不支持jdk7，建议修改properties中jdk.version为1.8

### ISSUE THREAD

**Issue by liaow** [alibaba/easyexcel#587]
**建议描述**
依赖版本为4.0.1，但是官方changelog中明确指出从4.0.0开始已经移除了jdk7的支持。实际使用中也确实会因为不支持jdk7而报错。
![image](https://user-images.githubusercontent.com/3170158/65003560-9e0d3e80-d92b-11e9-9ad7-ea4843d8bc16.png)

**Comment by zhuangjiaju** [comment]
非常感谢您的意见。我们内部讨论了下 决定降级到poi 3.17 兼容jdk6 尽量提高兼容性

**Comment by rookiy** [comment]
依赖低版本的poi有bug，在com.alibaba.excel.analysis.v07.handlers.CellTagHandler 里拿不到正确的单元格类型，升级poi版本可解决
