### ISSUE TITLE
Converter<xxx>实现类中的convertToJavaData()方法中怎么拿到查数据库的信息？

### ISSUE THREAD

**Issue by wsm1217395196** [alibaba/easyexcel#588]
@ExcelProperty(value = "父级域", converter = CustomLongConverter.class)，CustomLongConverter类中要注入service bean去查数据库信息，重写的convertToJavaData()的方法要用到查数据库的信息，这个要怎么弄呢？或者有其他解决方法吗？

**Comment by zhuangjiaju** [comment]
CustomLongConverter 可以定义一个静态变量。然后 在启动完成的时候 初始化这个值，后续new 出来的对象都会有和这个 参数
