### ISSUE TITLE
当.xlsx文件的字符串数据上百万时,是不是还是有可能出现oom?

### ISSUE THREAD

**Issue by xuljzz** [alibaba/easyexcel#59]
.xlsx文件的字符串数据都存储在sharedStrings.xml中,sheetxxx.xml存储的都是索引,看源码都是将sharedStrings.xml中的所有数据都存储在内存中,如果字符串数据量很大的时候,是不是也会出现oom?

**Comment by jipengfei-jpf** [comment]
由于1.0.*版本核心考虑的是怎么解决读excel内存溢出问题，自己重写了读excel的POI的底层，写仍旧使用POI。可以从根本解决OOM问题。但是由于自己对excel的格式认识不全面，有很多坑产生了很多BUG。最新版本以POI为底层。最新版：1.1.2-beat1，虽然不能完全解决OOM但可以解决大部分的OOM问题，完全解决OOM版本会等稳定后再开放，敬请理解。目前依赖POI版本1.1.2-beat1
