### ISSUE TITLE
导出一个excel 文件,三个sheet ,每个sheet对应不同的java模型,要怎么写?

### ISSUE THREAD

**Issue by Limbozombie** [alibaba/easyexcel#593]
导出一个excel 文件,三个sheet ,每个sheet对应不同的java模型,要怎么写? 给的案例中好像只能指定一个java模型

**Comment by cschenzz** [comment]
我也正需要实现这功能，现在解决了吗？

**Comment by Limbozombie** [comment]
> 我也正需要实现这功能，现在解决了吗？

已解决
![image](https://user-images.githubusercontent.com/35883214/65126055-2f160f80-da29-11e9-873b-eb5d1bc04147.png)
 

new ExcelHandler() 是我自己定义的拦截器,主要用来处理业务数据转换
