### ISSUE TITLE
设置了模板的情况下，默认加了一行头，如果在设置头，那样前面就会多出一空行

### ISSUE THREAD

**Issue by shenglong0314** [alibaba/easyexcel#598]
public int getNewRowIndexAndStartDoWrite() {
        // 'getLastRowNum' doesn't matter if it has one or zero,is's zero
        int newRowIndex = 0;
        switch (writeLastRowType) {
            case TEMPLATE_EMPTY:
                if (parentWriteWorkbookHolder.getExcelType() == ExcelTypeEnum.XLSX) {
                    if (parentWriteWorkbookHolder.getTemplateLastRowMap().containsKey(sheetNo)) {
                        newRowIndex = parentWriteWorkbookHolder.getTemplateLastRowMap().get(sheetNo);
                    }
                } else {
                    newRowIndex = sheet.getLastRowNum();
                }

                 newRowIndex++;//这里默认加了一行，导至我加入title后前面总是空一行
                break;
            case HAS_DATA:
                newRowIndex = sheet.getLastRowNum();
                newRowIndex++;
                break;
            default:
                break;
        }
        writeLastRowType = WriteLastRowType.HAS_DATA;
        return newRowIndex;
    }

**Comment by zhuangjiaju** [comment]
请提供代码和模板 。模板是否为空？

**Comment by layou1989** [comment]
> 请提供代码和模板 。模板是否为空？

模板为空会出现这个问题???

**Comment by layou1989** [comment]
遇到同样的问题，模板为空,代码
    @Test
    public void testTemplateEasyExcel() {
        EasyExcel.write("C:\\Users\\Administrator\\Desktop\\test2.xlsx", DemoData.class).withTemplate("C:\\Users\\Administrator\\Desktop\\test1.xlsx").
                sheet("测试").doWrite(data());
    }
，还有个问题，如何修改模板中的sheet名称，直接用sheet()方法无效？望指导

**Comment by shenglong0314** [comment]
模板
结果






代码
@Test
public void templateWrite() {
    String templateFileName = TestFileUtil.getPath() + "demo" + File.separator + "demo.xlsx";
    String fileName ="d:/aa.xlsx";
    // 这里 需要指定写用哪个class去读，然后写到第一个sheet，名字为模板 然后文件流会自动关闭
    EasyExcel.write(fileName, DemoData.class).withTemplate(templateFileName).sheet().doWrite(data());
}











------------------ 原始邮件 ------------------
发件人: "layou1989"<notifications@github.com>;
发送时间: 2019年10月12日(星期六) 中午1:36
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "87049333"<87049333@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/easyexcel] 设置了模板的情况下，默认加了一行头，如果在设置头，那样前面就会多出一空行 (#598)



 
请提供代码和模板 。模板是否为空？
  
模板为空会出现这个问题???

**Comment by zhuangjiaju** [comment]
不支持空模板，如果用了模板至少有一行数据。
