### ISSUE TITLE
@ExcelProperty 注解能否添加对函数支持

### ISSUE THREAD

**Issue by xxccll** [alibaba/easyexcel#603]
**建议描述**

## 版本 1.1.2-beta1
现有的数据类里面有部分字段不是基本类型,业务逻辑是通过自定义函数来从这些字段获取需要的值,其实在生成 Excel 的时候也是同样的原理,但是现在 `@ExcelProperty` 不支持函数注解,请问有没有什么解决办法

**Comment by zhuangjiaju** [comment]
建议升级版本 然后又 自定义拦截器去处理
