### ISSUE TITLE
对于Listener中抛出异常的处理

### ISSUE THREAD

**Issue by nonfou** [alibaba/easyexcel#608]
**建议描述**

**在listener中抛出异常后， 全局异常拦截器中会拦截到 "Listener error" 异常提示返回给页面，**

**自定义抛出的异常可以给用户一定的提示，但会被覆盖.**

**希望可以去掉图中抛出"Listener error"的包装, 可以抛出有效信息给页面**
![image](https://user-images.githubusercontent.com/20853378/65225886-7cad7d80-daf8-11e9-9a91-54f8972d410d.png)

**Comment by zhuangjiaju** [comment]
这个可以 ，后面会把真正的异常信息放到message里面

**Comment by Muscleape** [comment]
> 这个可以 ，后面会把真正的异常信息放到message里面

现在有什么可替代的方案吗？检验数据的结果响应给页面

**Comment by zhuangjiaju** [comment]
已经加入 参照 https://alibaba-easyexcel.github.io/  `数据转换等异常处理`

**Comment by nonfou** [comment]
灰常感谢 ：）
