### ISSUE TITLE
写excel 时poi依赖问题导致的失败 , 异常信息丢失

### ISSUE THREAD

**Issue by pwypwy** [alibaba/easyexcel#610]
**触发场景描述**
写excel 时 且poi依赖异常
**触发Bug的代码**
```java
       public ByteArrayOutputStream convertToOutputStream(Class<T> clazz,List<T> data) { 
        
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream(); 
        EasyExcel.write(outputStream,clazz).sheet().doWrite(data);
         
        return outputStream;  
    }
```
**提示的异常或者没有达到的效果**
ExcelBuilderImpl   addContent 方法 第98行
异常信息被catch住且执行finish() 方法  导致原异常信息:
java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.CellStyle.setVerticalAlignment(Lorg/apache/poi/ss/usermodel/VerticalAlignment;)
丢失 且抛出异常信息为:
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO

**Comment by zhuangjiaju** [comment]
异常是异常栈，第二层异常就是真正的异常。你可以把所有异常都贴出来。理论上不会丢失异常，只是外面包了一层。

**Comment by zhuangjiaju** [comment]
您好 我这里先关闭问题。如果还有问题 ，请打开问题
