### ISSUE TITLE
请问写操作支持CSV导出吗

### ISSUE THREAD

**Issue by JesseZhen** [alibaba/easyexcel#611]
用的demo里面的下面代码
EasyExcel.write(fileName, DemoData.class).sheet("模板").doWrite(data());
fileName为xxx.csv，打开文件提示“文件格式和拓展名不匹配”，请问支持指定格式(xls/xlsx/csv)的导出吗？

**Comment by zhuangjiaju** [comment]
目前仅仅支持xlsx xls 请参照demo书写
