### ISSUE TITLE
建议在代码中增加防止CSV注入的特性

### ISSUE THREAD

**Issue by Cuihongwen** [alibaba/easyexcel#614]
安全相关
现在本人是通过重写ExcelBuild类并覆盖加载来实现的，很繁琐。
希望能合入相关特性，毕竟CSV注入是很普遍的问题了
https://www.owasp.org/index.php/CSV_Injection

**Comment by zhuangjiaju** [comment]
您好 我这边没有去执行公式的代码。您这边是怎么处理的？能否提供下代码？或者说 提供一个可以触发的excel

**Comment by zhuangjiaju** [comment]
真的没看懂问题，如果有好的想法可以提供下pr 。我暂时先关闭问题
