### ISSUE TITLE
文件名filename 如果是中文，下载后名称不对，名称变成了一个下划线   ____.xlsx

### ISSUE THREAD

**Issue by linjpg** [alibaba/easyexcel#619]
response.setContentType("application/vnd.ms-excel");
        response.setCharacterEncoding("utf-8");
        response.setHeader("Content-disposition", "attachment;filename=下载.xlsx");
        EasyExcel.write(response.getOutputStream(), DownloadData.class).sheet("模板").doWrite(data());

**Comment by nonfou** [comment]
```
String fileName="下载.xlsx";
response.setHeader("Content-disposition", "attachment;filename=" + URLEncoder.encode(fileName, StandardCharsets.UTF_8.name()));
```
