### ISSUE TITLE
easyexcel生成的excel无法居中

### ISSUE THREAD

**Issue by liu165** [alibaba/easyexcel#622]
**触发场景描述**
生成excel后，生成的excel无法居中
**触发Bug的代码**
```java
![image](https://user-images.githubusercontent.com/38496424/65404657-09fc1500-de0c-11e9-8fd7-9a39144a46c1.png)


```
**提示的异常或者没有达到的效果**
无法居中

**Comment by liu165** [comment]
![TIM截图20190923141309](https://user-images.githubusercontent.com/38496424/65404766-77a84100-de0c-11e9-8abf-a52a87ca5f0d.png)

**Comment by liu165** [comment]
请大佬解决一下

**Comment by zhuangjiaju** [comment]
请使用自定义样式
