### ISSUE TITLE
新版是 删除 多sheet写入了吗

### ISSUE THREAD

**Issue by lianghongshuai** [alibaba/easyexcel#626]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by lianghongshuai** [comment]
读取excel的监听器中的获取行号的方法也没有用了，现在怎么获取行号呢？

**Comment by zhuangjiaju** [comment]
参照简单的写里面的demo2 可以创建多个writesheet 然后写入过多个。获取行号的 点进去有建议使用的方法。
