### ISSUE TITLE
嵌套集合的动态列、动态列的合并单元格

### ISSUE THREAD

**Issue by lianghongshuai** [alibaba/easyexcel#629]
public class SurveyDataExcel {

 
    private String projectName;

    private String subProjectName;

    private String taskName;

    private List<SurveyDataVo> surveyDataVoList;

}

如果这是我的要导出的数据，前三个字段对应后面的集合， 其中SurveyDataVo 中也有一个字段是集合，这样复杂的集合嵌套有什么好的解决方案吗？ 
还有就是：
        LoopMergeStrategy loopMergeStrategy = new LoopMergeStrategy(2, 0);
       CellRangeAddressList cellRangeAddressList = new CellRangeAddressList(1, 2, 0, 0);
合并单元格和设置下拉框都是根据下标指定的，那么动态处理上面那种嵌套数据有什么好的解决方案吗？

**Comment by zhuangjiaju** [comment]
建议把 SurveyDataExcel 里面的字段移动到 SurveyDataVo里面。搞成平级对象，然后再合并
