### ISSUE TITLE
大数据量比如20万的Excel读取之后要写库，事务要怎么控制呢？

### ISSUE THREAD

**Issue by ljm653467080** [alibaba/easyexcel#63]
大神，读取大文件的excel没问题了，对读取到的数据要做写库操作，多线程r任务FutureTask异步处理？事务该怎么控制呢，失败要支持回滚，作者有什么优秀的解决方案吗？阿里内部应该有这样的场景吧。

**Comment by zljgit** [comment]
20w行一个事务！

**Comment by jipengfei-jpf** [comment]
最终一致性通过消息回调
