### ISSUE TITLE
Could not open the specified zip entry source stream

### ISSUE THREAD

**Issue by shanmie** [alibaba/easyexcel#632]
**触发场景描述**
如果excel 数据很大 就会报异常  Could not open the specified zip entry source stream
**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
有没有调用finish?如果有 clean 然后 统一poi版本 。

**Comment by zhuangjiaju** [comment]
请问是否已经解决了问题？如果未解决 请重新打开问题

**Comment by qianhuaipeng** [comment]
> 请问是否已经解决了问题？如果未解决 请重新打开问题

你看是不是maven编译的时候把xlsx文件也编译了，可以看这一篇https://www.cnblogs.com/changfanchangle/p/8808963.html

**Comment by daarone** [comment]
遇到同样的问题，导入的数据过大时报异常，是否已经解决了？

**Comment by dandelionflying** [comment]
是否已解决？我也遇到了这个报错

**Comment by waveBoom** [comment]
> > 请问是否已经解决了问题？如果未解决 请重新打开问题
> 
> 你看是不是maven编译的时候把xlsx文件也编译了，可以看这一篇https://www.cnblogs.com/changfanchangle/p/8808963.html

这个可能有用 建议筛查
