### ISSUE TITLE
建议使用注解的方式将头名称与类反射注入

### ISSUE THREAD

**Issue by shrchang** [alibaba/easyexcel#634]
**建议描述**
返回的类根据head name自动注入对应属性且可以忽略未找到的头属性的内容

**Comment by zhuangjiaju** [comment]
能否描述详细一点 你想要实现什么功能 推荐用什么来实现

**Comment by zhuangjiaju** [comment]
您好 您的问题是否已经解决？如果未解决 请描述详细后重新打开问题
