### ISSUE TITLE
使用Model读Excel模型时，注解ExcelProperty设置value值无效

### ISSUE THREAD

**Issue by PhilosophyBuns** [alibaba/easyexcel#64]
是我使用方式不对吗
在对象类型转换的时候，仅仅用了ExcelProperty中的index属性获得列对象
类名：com.alibaba.excel.metadata.ExcelHeadProperty
![image](https://user-images.githubusercontent.com/28674017/45290265-c648ad00-b521-11e8-81bc-e41969e7f036.png)
在excelColumnPropertyMap1 初始化的时候也并没针对ExcelProperty的value值进行重新设置index.
顺便吐槽一下变量的命名错了
类名：com.alibaba.excel.metadata.ExcelHeadProperty
![image](https://user-images.githubusercontent.com/28674017/45290451-335c4280-b522-11e8-9283-2e921cdae452.png)

使用版本1.0.4

**Comment by wangchl0932** [comment]
还以为我看错了呢，也发现了这个问题

**Comment by boycezeng** [comment]
也有这个问题

**Comment by DarrenGu** [comment]
我也遇到了，继承的时候出现的，无法赋值

**Comment by Ryoui** [comment]
我也遇到了，因为我的excel是自动的，不能确定index,所以用的value结果也不行，我还以为用错了1.1.12

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel

**Comment by sicosola** [comment]
转换model 的BeanMap.create(resultModel).putAll(map)，把值都给转换没了。
