### ISSUE TITLE
导入时如果异常突然终止导入，文件就无法再导入了

### ISSUE THREAD

**Issue by wenfer** [alibaba/easyexcel#642]
感觉像是再导入时，IO没有正常关闭的话，会损坏文件

**Comment by wenfer** [comment]
![image](https://user-images.githubusercontent.com/16834499/65677369-0d013a80-e084-11e9-847f-3dc67604efbd.png)

**Comment by wenfer** [comment]
![image](https://user-images.githubusercontent.com/16834499/65677614-839e3800-e084-11e9-9bf4-70260cb7de26.png)

**Comment by zhuangjiaju** [comment]
看下你导入的代码 是否调用了finish?

**Comment by zhuangjiaju** [comment]
请问是否已经解决了问题？如果未解决问题 请重新打开问题
