### ISSUE TITLE
导出的excel,点击数字类型格子里,数据会变科学计数法,并且丢位

### ISSUE THREAD

**Issue by gaochuanneu** [alibaba/easyexcel#646]
使用版本2.0.3 如果导出 类型为长整型或者string,导出后excel点击进某个数据框内再出来,数据就会发生变化 依旧有丢位情况,比如7495396815497821会变成7495396815497820

**Comment by zhuangjiaju** [comment]
这个在2.0.4里面修复

**Comment by zhuangjiaju** [comment]
请参照：https://www.yuque.com/easyexcel/faq/evmtmu
