### ISSUE TITLE
RichTextString无效

### ISSUE THREAD

**Issue by layou1989** [alibaba/easyexcel#649]
在CellWriteHandler的afterCellCreat()方法中，设置新建了RichTextString并设置了字体，但是为生效

`@Override
public void afterCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, CellData cellData, Cell cell, Head head, int relativeRowIndex, boolean isHead) {
        Font redFont = writeSheetHolder.getSheet().getWorkbook().createFont();
        if(redFont instanceof XSSFFont) {
            XSSFRichTextString richString = new XSSFRichTextString("21213");
            richString.applyFont(0, 1, redFont);
            cell.setCellValue(richString);

        }
}`

**Comment by zhuangjiaju** [comment]
如果自定义样式的话 请参照demo。这个需要使用poi的写法，请确认 写法是否有问题?

**Comment by layou1989** [comment]
> 如果自定义样式的话 请参照demo。这个需要使用poi的写法，请确认 写法是否有问题?

`
@Test
    public void testRichTextString() throws IOException {
        XSSFWorkbook wb = new XSSFWorkbook();
        XSSFSheet sheet = wb.createSheet();
        XSSFRow row = sheet.createRow(0);
        XSSFCell cell = row.createCell(0);
        XSSFFont fontRed = wb.createFont();
        fontRed.setColor(Font.COLOR_RED);
        XSSFRichTextString richString = new XSSFRichTextString("表头必填*");
        richString.applyFont(richString.length() - 1, richString.length(), fontRed);
        cell.setCellValue(richString);
        FileOutputStream fos = new FileOutputStream("C:\\Users\\Administrator\\Desktop\\test1.xlsx");
        wb.write(fos);
        fos.close();
    }
`

`
@Test
    public void testRichTextStringEasyExcel() {
        EasyExcel.write("C:\\Users\\Administrator\\Desktop\\test2.xlsx", DemoData.class).
                registerWriteHandler(new CellWriteHandler() {
                    @Override
                    public void beforeCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Row row, Head head, int relativeRowIndex, boolean isHead) {

                    }

                    @Override
                    public void afterCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, CellData cellData, Cell cell, Head head, int relativeRowIndex, boolean isHead) {
                        if(isHead) {
                            Font fontRed = writeSheetHolder.getSheet().getWorkbook().createFont();
                            XSSFRichTextString richString = new XSSFRichTextString(cell.getStringCellValue());
                            richString.applyFont(richString.length() - 1, richString.length(), fontRed);
                            cell.setCellValue(richString);
                        }

                    }
                }).
                sheet("模板").doWrite(data());
    }
`

用poi的写法是生效的
![image](https://user-images.githubusercontent.com/7498703/65824549-ab1c1d00-e29d-11e9-917b-dab4116d2656.png)
但是easyexcel是不生效的，
![image](https://user-images.githubusercontent.com/7498703/65824558-c129dd80-e29d-11e9-9c12-c67a2afa7a0c.png)
是不是有其他的配置

**Comment by layou1989** [comment]
是不是被表头样式给覆盖了??

**Comment by zhuangjiaju** [comment]
你可以自定义表头样式。然后设置表头样式为null，试试。

**Comment by layou1989** [comment]
> 你可以自定义表头样式。然后设置表头样式为null，试试。

`
@Test
    public void testRichTextStringEasyExcel() {
        HorizontalCellStyleStrategy strategy = new HorizontalCellStyleStrategy(null, new WriteCellStyle());

        EasyExcel.write("C:\\Users\\Administrator\\Desktop\\test2.xlsx", DemoData.class).
                registerWriteHandler(strategy).
                registerWriteHandler(new CellWriteHandler() {
                    @Override
                    public void beforeCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Row row, Head head, int relativeRowIndex, boolean isHead) {

                    }

                    @Override
                    public void afterCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, CellData cellData, Cell cell, Head head, int relativeRowIndex, boolean isHead) {
                        if(isHead) {
                            Font fontRed = writeSheetHolder.getSheet().getWorkbook().createFont();
                            XSSFRichTextString richString = new XSSFRichTextString(cell.getStringCellValue());
                            richString.applyFont(richString.length() - 1, richString.length(), fontRed);
                            cell.setCellValue(richString);
                        }

                    }
                }).
                sheet("模板").doWrite(data());
    }
`
一样未生效
![image](https://user-images.githubusercontent.com/7498703/66361037-dbf00680-e9af-11e9-83ee-9d8baca4e176.png)

**Comment by zhuangjiaju** [comment]
知道原因了 我们写用的是sxssf 模式 该模式不支持 richtextString，下个版本会可以自义定模式。但是xssf数据会全部在内存。这个问题 建议 用模板解决。

**Comment by layou1989** [comment]
> 知道原因了 我们写用的是sxssf 模式 该模式不支持 richtextString，下个版本会可以自义定模式。但是xssf数据会全部在内存。这个问题 建议 用模板解决。
麻烦了

**Comment by zhuangjiaju** [comment]
还有一个方案就是 升级到`2.1.0-beta3`以上，然后设置`InMemory` 为true，就可以使用了。但是这样都会在内存处理，大批量导出文件勿用。

**Comment by layou1989** [comment]
> 还有一个方案就是 升级到`2.1.0-beta3`以上，然后设置`InMemory` 为true，就可以使用了。但是这样都会在内存处理，大批量导出文件勿用。

感谢耐心指导，刚试了下，没问题了，主要是用这个来做导入模板的生成，没有大文件

**Comment by Mings1998** [comment]
> > 知道原因了 我们写用的是sxssf 模式 该模式不支持 richtextString，下个版本会可以自义定模式。但是xssf数据会全部在内存。这个问题 建议 用模板解决。
> > 麻烦了

请问下现在这个功能支持了吗？目前我们公司也有类似的需求

**Comment by shenxianlu** [comment]
> 还有一个方案就是 升级到`2.1.0-beta3`以上，然后设置`InMemory` 为true，就可以使用了。但是这样都会在内存处理，大批量导出文件勿用。

2.1.0-beta3 是什么
