### ISSUE TITLE
EasyExcle第一次因为格式导入报错，再次导入即使格式是对了也会导入失败，报同样的错误

### ISSUE THREAD

**Issue by SANDUO421** [alibaba/easyexcel#653]
**需求**
1、数据库设计：id，name，age；其中id为主键，不能为空
2、导入excle 数据（id手动输入）
**产生的情况**
1、当excel没有空行的时候导入成功
2、当excel有空行的时候导入失败，接下来不重启系统，即使再次导入正确的没有空行的文件，依然回报同样的错误
**触发Bug的代码**
```java
   public void invoke(Person data, AnalysisContext context) {
        log.info("解析到一条数据:{}", JSON.toJSONString(data));
       //不添加该处判断，会因为读入的空对象，导致存储失败
        if (data != null && data.getId() != null) {
            list.add(data);
        }
        if (list.size() >= BATCH_COUNT) {
           //简单的数据库批量存储
            saveData();
            list.clear();
        }
    }

```
**希望达到的效果**
1、希望不会读取空的对象；
2、即使因为格式导入失败，但只要格式对，不重启服务器接口导入功能正常

**Comment by zhuangjiaju** [comment]
请确认是否使用了2.0.5的最新版本。然后 贴下异常。触发Bug 的代码 贴全一点，必须要的话上传excel，至少能让我看懂是什么问题？

**Comment by zhuangjiaju** [comment]
您好 不知道您的问题是否已经解决 如果未解决 请重新打开问题 我这里暂时关闭问题
