### ISSUE TITLE
Excel头上会多一列 this$0

### ISSUE THREAD

**Issue by MyouchSky** [alibaba/easyexcel#655]
使用简单Excel写 ,  生成的excel 头为：  字符串标题 | this$0。 多了一列this$0。
使用easyexcel版本为2.0.3。使用1.1.1没有这个问题

代码如下:
    @Data
    public class DemoData {
        @ExcelProperty("字符串标题")
        private String string;
    }
    public void simpleWrite() {
        String file = "D://";
        // 写法2
        String fileName = file + "simpleWrite" + System.currentTimeMillis() + ".xlsx";
        // 这里 需要指定写用哪个class去读
        ExcelWriter excelWriter = EasyExcel.write(fileName, DemoData.class).build();
        WriteSheet writeSheet = EasyExcel.writerSheet("模板").build();
        excelWriter.write(new ArrayList(), writeSheet);
        /// 千万别忘记finish 会帮忙关闭流
        excelWriter.finish();
    }

**Comment by zhuangjiaju** [comment]
这个应该是 你用了什么测试工具的原因。直接跑应该没问题。这个也是个Bug 会在下个版本修复。
