### ISSUE TITLE
数字类型数据读取实体String字段接收数据转换成double

### ISSUE THREAD

**Issue by xietuke** [alibaba/easyexcel#659]
数字类型数据读取实体String字段接收数据转换成double

**Comment by zhuangjiaju** [comment]
请说明问题就行。比如excel里面是什么值，我用string去接收，但是接收到什么值，但是我想要什么值。并提供源代码

**Comment by zhuangjiaju** [comment]
请问是否解决了问题？如果还没解决  描述详细后重新打开问题
