### ISSUE TITLE
如何自定义表中的数据样式呢？

### ISSUE THREAD

**Issue by coder-lzh** [alibaba/easyexcel#66]
比如说，我导入的100条数据，99条成功，1条因为数据验证问题失败，我需要返回一个错误的excel。里面特殊标注一下这一行数据。比如字体颜色红色，放上去有提示。这个如何解决啊？？？

**Comment by pluto-tu** [comment]
导入完成后重新创建一个excel到出，设置下错误那列的颜色为红色，这个是可以实现的。
放下去有提示这个需要研究下。

**Comment by coder-lzh** [comment]
感谢回复，还想请教一下，这个框架对比如说设置单元格背景为红色这种功能封装了么？如果封装了，在哪可以找到这类的相关的api呢？我见官网的demo中只有简单的上传和下载。没有其他更多的例子。如果没有封装，那用poi的那一套可以实现么？

**Comment by S-Beacon** [comment]
单元格如何按列设置单元格样式呢？非注解的模式，貌似数据部分默认是统一的样式。

**Comment by Maijh97** [comment]
同上， @pluto-tu 请问一下，导入完成后重新创建一个excel导出？是自己手动实现的吗？还是框架有封装好的方法

**Comment by Shangyangyang** [comment]
> 同上， @pluto-tu 请问一下，导入完成后重新创建一个excel导出？是自己手动实现的吗？还是框架有封装好的方法

我们公司都是自己实现功能，

**Comment by pluto-tu** [comment]
@Maijh97  @Shangyangyang  我目前的做法比较笨 导入完成后 失败的按原excel格式导出数据

**Comment by superliuliuliu** [comment]
> 数据验证问题

请问一下 怎样对单元格中数据做校验啊

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写

**Comment by snail10241024** [comment]
如何根据内容设置单元格样式？我是通过实现CellWriteHandler，重写afterCellDataConverted方法设置的样式，但是报错：You can define up to 64000 style in a .xlsx Workbook
