### ISSUE TITLE
请问，导入的时候excel中间存在空行怎么处理

### ISSUE THREAD

**Issue by tys87198312** [alibaba/easyexcel#661]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by sjmingdna** [comment]
你好，不是代码的问题，是Excel自身需要在这种格式的数据前加一个英文的单引号，不然会转义




------------------ 原始邮件 ------------------
发件人: "tys87198312"<notifications@github.com>;
发送时间: 2019年9月30日(星期一) 下午3:37
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [alibaba/easyexcel] 请问，导入的时候excel中间存在空行怎么处理 (#661)




异常代码
    这里写你的代码
 
异常提示
 请提供完整的异常提示,记住是全部异常！
 建议描述

**Comment by zhuangjiaju** [comment]
请升级到2.0.5 版本 默认会忽略空行
