### ISSUE TITLE
您好，行中的空数据的问题，行中的空数据会被抓自动略过，导致实际列数和读取列数不一致

### ISSUE THREAD

**Issue by ailuoli666** [alibaba/easyexcel#663]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
请升级到最新版本。然后使用参数`ignoreEmptyRow`  设置false 会读取到空行

**Comment by forvicky** [comment]
> 请升级到最新版本。然后使用参数`ignoreEmptyRow` 设置false 会读取到空行

ignoreEmptyRow参数无效

**Comment by zhuangjiaju** [comment]
> > 请升级到最新版本。然后使用参数`ignoreEmptyRow` 设置false 会读取到空行
> 
> ignoreEmptyRow参数无效

请提供详细案例 你想要干嘛 用了什么代码 结果咋么样 你想要怎么样

**Comment by zhuangjiaju** [comment]
不知道您是否已经解决了问题 如果还是未解决 请详细描述后 重新打开此问题。
