### ISSUE TITLE
读取Excel时 超链接数据为空

### ISSUE THREAD

**Issue by Strong-Gavin** [alibaba/easyexcel#666]
**建议描述**
建议增加读取超链接数据的功能，目前读取Excel时，如果某一列是超链接，那么这一列读取为空

**Comment by sjmingdna** [comment]
谢谢




------------------ 原始邮件 ------------------
发件人: "Gavin"<notifications@github.com>;
发送时间: 2019年10月7日(星期一) 上午9:47
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [alibaba/easyexcel] 读取Excel时 超链接数据为空 (#666)




建议描述
 建议增加读取超链接数据的功能，目前读取Excel时，如果某一列是超链接，那么这一列读取为空

**Comment by zhuangjiaju** [comment]
这个需要提供详细的数据。我虽然读不到超链接的信息 但是能读到 引用超链接的数据。你提供下文件？

**Comment by zhuangjiaju** [comment]
您好 是否已经解决问题了？如果还未解决 请重新打开问题
