### ISSUE TITLE
导出excel自定义表头格式

### ISSUE THREAD

**Issue by zhourui136** [alibaba/easyexcel#669]
**建议描述**
现在2.0.5版本还不可以自定义设置表头格式的，2.1.0-beta1倒是新增了handle实现，但是2.1.0-beta1是还在完善吗，一直没有发布该版本

**Comment by zhuangjiaju** [comment]
请解释下自定义表头的意思 谢谢。

**Comment by zhourui136** [comment]
> 请解释下自定义表头格式的意思 谢谢。

自定义表头样式，比如表头多行，第一行橙色背景，第二行表头红色背景，表头字体颜色设置成白色，现在2.0.5版本可以解决表头背景样式，但是表头字体不能设置成白色的，现在2.0.5导出来的是橙色表头背景，黑色默认表头字体

**Comment by zhuangjiaju** [comment]
两个表头的样式不一样 就要参照自定义样式了。理论上也可以实现。
