### ISSUE TITLE
怎么样在数据写完的时候添加自定义的一行？

### ISSUE THREAD

**Issue by felixzhang09** [alibaba/easyexcel#670]
![image](https://user-images.githubusercontent.com/29116883/66362676-4015c900-e9b6-11e9-8730-9b9f02e26d89.png)
如图所示，怎么样在数据写完的时候添加自定义的一行？

**Comment by felixzhang09** [comment]
![image](https://user-images.githubusercontent.com/29116883/66362738-75bab200-e9b6-11e9-8c5a-7a43bc9eef5f.png)
代码写法

**Comment by zhuangjiaju** [comment]
参照下 写入`table` ，然后不用头。`table`类似于一个子的小表格的概念。
