### ISSUE TITLE
如何实现边读取数据边下载？

### ISSUE THREAD

**Issue by linxiaoyang** [alibaba/easyexcel#673]
数据量庞大时，如果将全部的数据加载、拼接到内存中，然后统一输出成excel下载，很有可能造成两个问题，第一内存爆掉，第二web服务器超时，如果支持边查询少量数据，边下载，这样就可避免上面两个问题，不知道目前easyexcel有没有类似的解决方案，恳请回复，谢谢

**Comment by zhuangjiaju** [comment]
直接参照`demo` 书写即可，数据分批读取。

**Comment by linxiaoyang** [comment]
实例中的方法repeatedWrite的解决方案，采用的是分批读取，数据还是在应用系统的内存中，本质上还是将所有的数据都汇总完毕后，调用finish方法，将数据写入outputstream中，还是不能解决我上面提到的两个问题啊
