### ISSUE TITLE
如何创建Excel文档摘要信息

### ISSUE THREAD

**Issue by 3479785008** [alibaba/easyexcel#676]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
easyexcel是封装了poi。所以至少升级到`2.1.0-beta3`，然后设置`InMemory` 参数为true，然后通过自定义拦截器的方式加入备注。但是这样所有的数据都会在内存处理，大量导出的时候容易OOM。如果不是每个字段都要，建议使用`填充Excel`。
