### ISSUE TITLE
可以指定导出的列吗？

### ISSUE THREAD

**Issue by JesseZhen** [alibaba/easyexcel#677]
现在使用的时候，在POJO上添加注解@ExcelProperty，在导出的时候会将所有注解的列导出。
请问可以在导出的时候指定导出哪些列吗？
需求场景是同一个POJO需要导出不同的字段

**Comment by zhuangjiaju** [comment]
目前不支持。需要创建多个POJO。看到一个同学要反射实现过，但是不推荐
