### ISSUE TITLE
我捣鼓三天了，都搞不懂你这到底怎么用的？不能写清楚吗？像我们这样的小白就懵逼了

### ISSUE THREAD

**Issue by smfx1314** [alibaba/easyexcel#68]

**Comment by zhangsxnaive** [comment]
我觉得如果只是会用，那永远都是小白.....作者开放源代码，没有义务去教你怎么用，你自己可以看代码去研究怎么用

**Comment by hbprotoss** [comment]
伸手党真的是越来越过分了

**Comment by pluto-tu** [comment]
作者已经写得非常详细了，导入导出 例子都给出了。

**Comment by jipengfei-jpf** [comment]
https://github.com/alibaba/easyexcel  最新版1.1.2-beat1使用更加简单。可以拉测试代码在本地跑一下
