### ISSUE TITLE
在Listener的onException方法中怎样获取当前抛异常单元格的head名称

### ISSUE THREAD

**Issue by a466350665** [alibaba/easyexcel#680]
在Listener的onException方法中怎样获取当前抛异常单元格的head名称
![image](https://user-images.githubusercontent.com/19278040/66536634-32944680-eb50-11e9-83a9-f2c6bd2e90f5.png)

**Comment by zhuangjiaju** [comment]
这个目前不支持 会在下个版本支持

**Comment by zhuangjiaju** [comment]
参照 https://alibaba-easyexcel.github.io/  `数据转换等异常处理`
