### ISSUE TITLE
新人求解。。。表头7列，但是实际每行中数据有可能为空，读取时不对应，怎么设置参数读取为空的单元格？

### ISSUE THREAD

**Issue by lazybird23** [alibaba/easyexcel#681]
打印的输出：
数据：[name_A, age_A, gender_A, hobby_A, department_A, leader_A, money_A]
出自1个sheet表,名称: test1
第3行数据
数据：[name_A1, 1.0, 女, B1, 101291.1]
出自1个sheet表,名称: test1
第4行数据
数据：[name_A2, 2.0, 女, B2, 101292.1]
出自1个sheet表,名称: test1

代码：
 public void invoke(List<String> object, AnalysisContext context) {
                    System.out.println("出自"+(context.readSheetHolder().getSheetNo()+1)+"个sheet表,名称: "+
                            context.readSheetHolder().getSheetName());
                    System.out.println("第"+context.readRowHolder().getRowIndex()+"行数据");
                    List<String> datas = (List<String>) context.readRowHolder().getCurrentRowAnalysisResult();
                    System.out.println("数据："+datas.toString());
                }

**Comment by zhuangjiaju** [comment]
建议用对象或者 map 去接收 用map的话话可以用index判断。下个版本会修复这个问题 会有个null的数据

**Comment by linsmalldragon** [comment]
2.2.7还有这个问题

**Comment by linsmalldragon** [comment]
请问在哪个版本已修复
