### ISSUE TITLE
EasyExcel.read(filePath).sheet(sheetName) 无法根据sheet name读取

### ISSUE THREAD

**Issue by lazybird23** [alibaba/easyexcel#682]
EasyExcel.read(filePath).sheet(sheetName).doReadSync()

**Comment by qigecanghai** [comment]
是现在没有这个功能么

**Comment by zhuangjiaju** [comment]
能否提供详细代码。还是你用的是03版，03版目前不支持。07版没问题

**Comment by lazybird23** [comment]
> 能否提供详细代码。还是你用的是03版，03版目前不支持。07版没问题

额。。。确实使用的是03版本不行，07可以

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复
