### ISSUE TITLE
如何遍历获取所有的sheetName，通过判断sheetName获取sheet的位置下标

### ISSUE THREAD

**Issue by object360** [alibaba/easyexcel#683]
需要通过判断sheetname来读取哪几个工作薄的数据，通过什么方法可以获取所有sheetName和位置下标

**Comment by qigecanghai** [comment]
同问  ，如何根据sheet名读取excel

**Comment by qigecanghai** [comment]
这样写好像可以
```
        SyncReadListener listener = new SyncReadListener();
        ExcelReader excelReader = EasyExcel.read(fileName, ExcelIm.class, listener).build();
        ReadSheet sheet = EasyExcel.readSheet(sheetName).build();
        excelReader.read(sheet);
        List<Object> lists = listener.getList();
```

**Comment by lazybird23** [comment]
> 这样写好像可以
> 
> ```
>         SyncReadListener listener = new SyncReadListener();
>         ExcelReader excelReader = EasyExcel.read(fileName, ExcelIm.class, listener).build();
>         ReadSheet sheet = EasyExcel.readSheet(sheetName).build();
>         excelReader.read(sheet);
>         List<Object> lists = listener.getList();
> ```
好像的。。。大多都不靠谱

**Comment by zhuangjiaju** [comment]
```java
   ExcelReader excelReader = EasyExcel.read(fileName, DemoData.class, listtener).build();
        excelReader.excelExecutor().sheetList()
```
这个可以获取 但是需要注意03版的话 这么 会读取整个excel 。

**Comment by MaxwellAlen** [comment]
@zhuangjiaju 我用这个方法获取所有sheet页的时候，只获取到了第一页，可能是咋回事啊
