### ISSUE TITLE
构建Excel对象疑问

### ISSUE THREAD

**Issue by qigecanghai** [alibaba/easyexcel#684]
使用`@ExcelProperty`构建对象时,此注解属性指定的是对应excel哪一列。如何指定对应哪一行呢？
```
    //单位类型    （比如这个type怎么对应excel第一行数据，而不是第一列）
    private String type;
```
默认是以一行作为对象，请问如何以Excel一列作为一个对象进行构建？

**Comment by zhuangjiaju** [comment]
您好 目前不支持 横向的读取。建议用map 接收 然后自己去拼接。
