### ISSUE TITLE
在android中引用该库时，报Program type already present: org.apache.xmlbeans.xml.stream.Location异常

### ISSUE THREAD

**Issue by zhangliangbo** [alibaba/easyexcel#685]
**触发场景描述**
在android中引用该库，运行代码时。
**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
目前easyexcel 不支持安卓。您可以调试下 或者异常贴全一点。如果能有好的解决方案 也可以提交pr.

**Comment by zhuangjiaju** [comment]
我暂时先关闭问题 如果您有好的方法了，可以提交个PR 或者 加群直接沟通。这里沟通效率低。
