### ISSUE TITLE
poi版本自动降级为3.9（非冲突？）

### ISSUE THREAD

**Issue by iiiLFC** [alibaba/easyexcel#686]
项目里使用了1.1.2-beta5版本， 内置依赖poi肉眼可见3.17 ，实际加载依赖是3.9。第一反应依赖冲突了或者其他依赖的内部引用。网上也看到了几个一模一样的问题，用了dependency：tree -dverbose 【poi：jar：3.9：compile（version managed from 3.17）】或是mavenhelper查看依赖的确只有easyexcel使用了poi，并且我删除easyexcel依赖，清空本地仓库，重新reimport并没有去下载poi依赖（证明非依赖冲突？），实在无解，望指教

**Comment by iiiLFC** [comment]
公司电脑无法在gh提交，无法截图粘贴代码 望海涵

**Comment by iiiLFC** [comment]
dependencyManagement 版本管理中心并没有对poi有单独配置 只管理了easyexcel

**Comment by zhuangjiaju** [comment]
可以尝试  自己外部 再次引入poi 这样强行指定版本。
