### ISSUE TITLE
使用模板实体导入时怎样实现添加了@ExcelProperty注解的属性才和与excel文件数据对应，否则自动忽略

### ISSUE THREAD

**Issue by wyldusername** [alibaba/easyexcel#687]
<img width="430" alt="90bd43a891704e7d6e815858d783b66" src="https://user-images.githubusercontent.com/42833098/66700669-bfdcc400-ed25-11e9-9246-452e013d62b2.png">

**Comment by zhuangjiaju** [comment]
使用 `@ExcelIgnore` 注解 目前不支持自动忽略
