### ISSUE TITLE
使用了lombok.experimental.Accessors注解后，指定列方式读取为空

### ISSUE THREAD

**Issue by BryantWangGitHub** [alibaba/easyexcel#689]
@Accessors(chain = true)
指定列模式读取，模板类上只要使用了该注解，就会导致ReadListener读取时invoke获得的读取对象各属性都为空。
去掉注解后就可以正常使用，另外这个注解不影响导出。

版本：2.0.5

**Comment by zhuangjiaju** [comment]
这个需要排查下 目前用的是 cglib 来返回对象的。

**Comment by zhuangjiaju** [comment]
这个暂时性 不解决。cglib 不支持 有返回值的get set ，后续考虑自己修改cglib的代码
