### ISSUE TITLE
ExcelAnalysisException: File type error, io must be available markSupported, you can do like this <code> new BufferedInputStream(new   )>

### ISSUE THREAD

**Issue by IssacGan** [alibaba/easyexcel#690]
**异常代码**
```java
  简单上传功能，同事的机器上能运行（相同的代码，相同的上传文件），我的报这个异常
```
**异常提示**
com.alibaba.excel.exception.excelAnalysisException:File type error , io must be markSupported, you can do like this<code> new BufferedInputStream( new FileInputStream(\"/xxxxx\"))</code>"
**建议描述**

**Comment by zhuangjiaju** [comment]
请尝试升级版本 或者  new BufferedInputStream 包裹这个传入的stream流
