### ISSUE TITLE
数字变成科学计数法及数字自动带上“.0”

### ISSUE THREAD

**Issue by Lang-Zh** [alibaba/easyexcel#697]
导入数字 变成科学计数法及数字自动带上“.0”

**Comment by zhuangjiaju** [comment]
是否使用了 最新的`2.0.5` 版本。如果是的话 请加上注解`@NumberFomart(#)` 。

**Comment by Lang-Zh** [comment]
请问&nbsp; 如果是没有映射实体类 而是Map&nbsp; 要怎么处理？










------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiaju Zhuang"<notifications@github.com&gt;; 
发送时间: 2019年10月15日(星期二) 晚上10:18
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com&gt;; 
抄送: "深秋&amp;#x1F340;"<1102076808@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/easyexcel] 数字变成科学计数法及数字自动带上“.0” (#697)




是否使用了 最新的2.0.5 版本。如果是的话 请加上注解@NumberFomart(#) 。
