### ISSUE TITLE
导入excel时间格式数据转换异常

### ISSUE THREAD

**Issue by SSHinata** [alibaba/easyexcel#698]
**描述**
excel时间格式为yyyy/mm/dd，导入读取数据获得的是mm/dd/yy，
描述年的数据缺失前两位。

例：2019/01/01和1919/01/01读入的数据都为1/1/19。

无法精确转换日期时间。

**Comment by zhuangjiaju** [comment]
请尝试使用 `Date`去接收。如果必须用String 请 用 `@DataFomart`注解
