### ISSUE TITLE
大牛好，我有一个问题。读取excel，会读取表格中的空行，这中问题，是不是需要业务逻辑中处理，还是我操作方式不对

### ISSUE THREAD

**Issue by DxfGit** [alibaba/easyexcel#709]
版本

<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>easyexcel</artifactId>
    <version>2.0.5</version>
</dependency>

读取代码如下
public void invoke(TmkClueReadTemplate data, AnalysisContext analysisContext) {
        Loggers.INFO_LOGGER.info("解析到一条数据:{}", JSONObject.toJSONString(data));
        list.add(data);
}

**Comment by zhuangjiaju** [comment]
请提供日志。data是 null?还是空对象？

**Comment by DxfGit** [comment]
日志打印：
[2019-10-17 19:53:10.161] [http-nio-8080-exec-5] [INFO ] info-logger - 解析到一条数据:{}
[2019-10-17 19:53:10.161] [http-nio-8080-exec-5] [INFO ] info-logger - 解析到一条数据:{}
[2019-10-17 19:53:10.161] [http-nio-8080-exec-5] [INFO ] info-logger - 解析到一条数据:{}
[2019-10-17 19:53:10.161] [http-nio-8080-exec-5] [INFO ] info-logger - 解析到一条数据:{}
[2019-10-17 19:53:10.161] [http-nio-8080-exec-5] [INFO ] info-logger - 解析到一条数据:{}

解析到的对象
TmkClueReadTemplate(tmkName=null, tmkMobile=null, 
tmkAddTime=null, handTime=null, productName=null, handUserName=null, 
handUserMobile=null, parentSource=null, childSource=null, assistantName=null, 
tmkIs2MinTalk=null, tmkIsEffectConnect=null, salesman2MinTalk=null, salesmanEffectConnect=null, 
isStudentReply=null, clueWechat=null, clueName=null, clueMobile=null, school=null, major=null, 
graduateDate=null, email=null, remark=null, intentionCity=null, intentionIndustry=null, gradeXueli=null, 
gradeXuexiaoGuonei=null, gradeXuexiaaoGuowai=null, gradeYixiangchengshi=null, 
gradeYixianghangye=null, gradeGongzuojingyan=null, gradeGuoji=null, gradeLiaojiefuwu=null)

**Comment by zhuangjiaju** [comment]
是否就是群里说的 单元格内有公式？这个目前没法解决，建议删除公式或者自己判断空

**Comment by DxfGit** [comment]
好滴，多谢大佬耐心解答，目前我通过自己判空已经解决，多谢，多谢
