### ISSUE TITLE
easyexcel 能设置单元格内容居中和自动适应宽度吗

### ISSUE THREAD

**Issue by lidenger** [alibaba/easyexcel#71]
public class TableStyle {
    private IndexedColors tableHeadBackGroundColor;
    private Font tableHeadFont;
    private Font tableContentFont;
    private IndexedColors tableContentBackGroundColor;

tablestyle 没有找到，特此请教

**Comment by yswang0927** [comment]
你可以使用  jxls (http://jxls.sourceforge.net/)

**Comment by lidenger** [comment]
> 你可以使用jxls（http://jxls.sourceforge.net/）

个人认为居中和自适应宽度通常都会用到，不能说没有就看别的框架，您是不是不喜欢easyexcel,

**Comment by lidenger** [comment]
> 你可以使用jxls（http://jxls.sourceforge.net/）

它能做到不OOM吗？它有easyexcel操作方便简单吗，个人认为居中和自适应宽度经常使用，作者应该早就想到了，
`@Target({ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
@Inherited
public @interface ExcelProperty {
    String[] value() default {""};

    int index() default 99999;

    String format() default "";
}
`
format是不是就可以设置

**Comment by aionbo** [comment]
请问下单元格自适应的这个问题解决了吗？

**Comment by chenshun00** [comment]
@aionbo @lidenger #101

**Comment by narutoform** [comment]
这个问题解决了吗？

**Comment by zhuangjiaju** [comment]
目前没有非常好的自适应方法。可以参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 有个相对能用的。当然有更好的自适应方法，可以基于上面的方案自定义
