### ISSUE TITLE
OnceAbsoluteMergeStrategy在合并单元格的坐标范围内只有一个单元格时，poi报错最少有两个单元格，建议加判断避免报错

### ISSUE THREAD

**Issue by guoyang924** [alibaba/easyexcel#717]
**建议描述**
protected void merge(Sheet sheet, Cell cell, Head head, int relativeRowIndex) {
        if (cell.getRowIndex() == this.firstRowIndex && cell.getColumnIndex() == this.firstColumnIndex) {
            CellRangeAddress cellRangeAddress = new CellRangeAddress(this.firstRowIndex, this.lastRowIndex, this.firstColumnIndex, this.lastColumnIndex);
//建议加判断
            if(firstRowIndex==lastRowIndex &&firstColumnIndex==lastColumnIndex){
                return;
            }
            sheet.addMergedRegion(cellRangeAddress);
        }
    }

**Comment by zhuangjiaju** [comment]
这个另外一方面 理解。你要合并一个单元格 肯定是要报错。肯定是代码写的出乎你的意料了，才会出现合并一个单元格的。所以应该报错。如果不报错，你以为是正确的，结果出来了却是错的。这个应该也是poI 会选择报错 而不是忽略的原因，
