### ISSUE TITLE
获取解析的数据为null的问题

### ISSUE THREAD

**Issue by krupp** [alibaba/easyexcel#718]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
问好！按照例子写了代码后，运行读取本地文件的时候，发现在Listener中invoke中得到的数据全是null是什么原因呢。同样在源码中运行测试类就可以获取到数据。烦请解答一下。多谢
**建议描述**

**Comment by krupp** [comment]
补充，使用Map类型接收可以获取到值，使用自定义的数据类型接收不到数据。

**Comment by zhuangjiaju** [comment]
请加入getset
