### ISSUE TITLE
能满足根据传入表头列表，自动筛选写入数据的功能吗？

### ISSUE THREAD

**Issue by vito16** [alibaba/easyexcel#720]
过滤+排序  
比如完整数据如下：

| id  | name | age |
| ------------- | ------------- | ------------- |
| 1  | 张三 | 43 |
| 2 | 李四 | 29 |  

现在传入一个附加参数
```
{id,age}
```
输出表格就应该是

| id  | age |
| ------------- | ------------- |
| 1   | 43 |
| 2  | 29 |    

如果传入的参数是:
```
{age,name}
```
输出的Excel就应该是：    

| age  | name |
| ------------- | ------------- |
| 43  | 张三 | 
| 49 | 李四 |

**Comment by zhuangjiaju** [comment]
目前不支持。需要自己提前删选好数据，并导入。或者你定义不同的class,实际生成会根据不同的class的字段来删选
