### ISSUE TITLE
导出时，如何设置列隐藏？

### ISSUE THREAD

**Issue by youerduoDog** [alibaba/easyexcel#721]

**Comment by huangxin19990101** [comment]
`


    @Override
    public void beforeCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Row row,
                                 Head head, int relativeRowIndex, boolean isHead) {
    }

    @Override
    public void afterCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, CellData cellData,
                                Cell cell, Head head, int relativeRowIndex, boolean isHead) {
        // 这里可以对cell进行任何操作
        LOGGER.info("第{}行，第{}列写入完成。", cell.getRowIndex(), cell.getColumnIndex());

        //隐藏id列
        writeSheetHolder.getSheet().setColumnHidden(0, true);

        //居中
        CellUtil.setAlignment(cell, HorizontalAlignment.CENTER);
        CellUtil.setVerticalAlignment(cell, VerticalAlignment.CENTER);
    }


`

**Comment by huangxin19990101** [comment]
> `
> 
> ```
> @Override
> public void beforeCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, Row row,
>                              Head head, int relativeRowIndex, boolean isHead) {
> }
> 
> @Override
> public void afterCellCreate(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder, CellData cellData,
>                             Cell cell, Head head, int relativeRowIndex, boolean isHead) {
>     // 这里可以对cell进行任何操作
>     LOGGER.info("第{}行，第{}列写入完成。", cell.getRowIndex(), cell.getColumnIndex());
> 
>     //隐藏id列
>     writeSheetHolder.getSheet().setColumnHidden(0, true);
> 
>     //居中
>     CellUtil.setAlignment(cell, HorizontalAlignment.CENTER);
>     CellUtil.setVerticalAlignment(cell, VerticalAlignment.CENTER);
> }
> ```
> 
> `

实现CellWriteHandler接口, 并调用.registerWriteHandler(new InventoryTallyExcelCellWriteHandler())注册

**Comment by ZombieSouls** [comment]
@ContentStyle(hidden = BooleanEnum.TRUE) 为什么不起作用？
private String id;

**Comment by yikengboy** [comment]
`@ExcelProperty("需求id")
    @ColumnWidth(0)
    private Long id;` 
我设置成0 为什么还是会显示这列

**Comment by Loongphy** [comment]
使用 `@ExcelIgnore`，如：
```
@ExcelIgnore
private String data;
```

**Comment by YangJingf** [comment]
这种就是完全没有了，不是隐藏了。列隐藏还可以通过取消隐藏打开，这种是这个列直接没有了
