### ISSUE TITLE
读取全部sheet,到第二个sheet会抛出转换类型的异常

### ISSUE THREAD

**Issue by dardaplanet** [alibaba/easyexcel#727]
` ExcelListener excelListener = new ExcelListener();
EasyExcel.read(inputStream,TbTraineequestion.class,excelListener).doReadAll();`
错误提示
![image](https://user-images.githubusercontent.com/32916396/67266415-cb2cae00-f4e2-11e9-92bc-737712eedd21.png)
字符串的类型为什么会转Integer,自己没有自定义converter

**Comment by zhuangjiaju** [comment]
这个问题 你TbTraineequestion 这个class必须和sheet1 2的数据都对上。你的问题是 那个字段 对应到 TbTraineequestion里面变成integer里。你必须指定index 或者 指定表头名。如果sheet1 2数据不一致，需要分开读。
