### ISSUE TITLE
设置单元格内容格式setDataFormat不生效的问题

### ISSUE THREAD

**Issue by msl1024bit** [alibaba/easyexcel#728]
大佬，我在用WriteCellStyle去设置内容的单元格格式，里面有个dataFormat的属性。在set的时候，这个属性的传值是什么？是BuiltinFormats里的_formats数组的每个格式的index吗？能举个例子吗？比如我要设置个自定义格式"@"来作为文本占位符，在_formats数组里是最后一个，index也就是49，但是我setDataFormat((short)49)，没有效果是怎么回事？期待大佬回复~

**Comment by Limbozombie** [comment]
![image](https://user-images.githubusercontent.com/35883214/70674073-c05ef000-1cbf-11ea-9b80-b23121a9d974.png)
看源码

**Comment by zhuangjiaju** [comment]
参照https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.numberingformat?view=openxml-2.8.1 
49是常规 所以不起作用，具体什么你在这个里面找

**Comment by zhangfan1110** [comment]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/68902616/125597673-73760bac-3cff-4f65-aeb6-168b75ea1f53.png">
常规是(short)0
//设置单元格类型为常规
WriteCellStyle contentCellStyle = new WriteCellStyle();
contentCellStyle.setDataFormat((short) 0);
