### ISSUE TITLE
今天在使用咱们的框架后发现在简析中文的时候会带上拼音

### ISSUE THREAD

**Issue by xietieyun** [alibaba/easyexcel#730]
今天在使用咱们的框架后发现在简析中文的时候会带上拼音
这是简析excel中一段中文后，后面会带上拼音：
具有抗氧化性强、不易结垢、耐高温、抗高压等特点ju'youkangyang'huaxingqiangbuyijie'gounaigao'wenkanggao'yadengte'dian

**Comment by zhuangjiaju** [comment]
这个问题 暂时不解决。请重新保存excel ,这个是mac 特殊版本处理的问题。实际上他有这个数据的，只是看不到。
