### ISSUE TITLE
excel单元格是数字保留两位小数，如果按照String处理后丢失精度

### ISSUE THREAD

**Issue by WhatisAnt** [alibaba/easyexcel#731]
excel单元格是数字保留两位小数，如果javabean 对应的列定义为String后丢失精度
例如单元格中的是9632.03,解析后变成9632.0300000000007，这是为什么？

**Comment by zhuangjiaju** [comment]
里面存储的 就是这个 建议加上@NumberFormat 后续会解决 读出来 和excel显示完全一致的问题
