### ISSUE TITLE
如何动态维护字段的列数

### ISSUE THREAD

**Issue by CuiKai721** [alibaba/easyexcel#733]
求教如何动态维护字段的列数

当excel有很多列时,在Model前面几列添加字段后,需要依次修改后续字段列数,有什么动态设置的方法吗?

**Comment by CuiKai721** [comment]
即想要BaseRowModel中的@ExcelProperty注解的index属性可以依次递增

**Comment by dardaplanet** [comment]
可以通过@ExcelProperty的value动态匹配,官方不建议index和value混着用,可参考@ExcelProperty的使用

**Comment by zhuangjiaju** [comment]
这个需要升级到 `2.0.5`版本，然后不设置index 即可
