### ISSUE TITLE
升级2.1.0-beta2后使用SimpleRowHeightStyleStrategy设置表头高度无效

### ISSUE THREAD

**Issue by layou1989** [alibaba/easyexcel#735]
@Test
    public void testHeight() {
        SimpleRowHeightStyleStrategy rowHeightStyleStrategy = new SimpleRowHeightStyleStrategy((short)150, (short)120);
        EasyExcel.write("C:\\Users\\Administrator\\Desktop\\test2.xlsx", DemoData.class).
                registerWriteHandler(rowHeightStyleStrategy)
                .sheet("测试").doWrite(data());
    }

升级了2.1.0-beta2后，使用SimpleRowHeightStyleStrategy 设置表头的高度，但是并未生效，内容高度生效了

![image](https://user-images.githubusercontent.com/7498703/67353685-bfde8e80-f585-11e9-80d2-f768c72ace9a.png)

**Comment by zhuangjiaju** [comment]
这个是个bug,已经在2.1.0-beta3修复

**Comment by layou1989** [comment]
> 这个是个bug,已经在2.1.0-beta3修复

got it

**Comment by FunctionD** [comment]
实测2.0.1的head高度设置有效，.registerWriteHandler()的顺序不对所以不生效
