### ISSUE TITLE
exceleasy2.0，读取XLSX时，getPartsByContentType方法报异常

### ISSUE THREAD

**Issue by Liesport758** [alibaba/easyexcel#740]
**触发场景描述**
版本2.0.0
**触发Bug的代码**
![image](https://user-images.githubusercontent.com/10843358/67378201-7e67d680-f5b9-11e9-8e29-b57ce715c472.png)

![image](https://user-images.githubusercontent.com/10843358/67377233-f0d7b700-f5b7-11e9-8541-f275c7426293.png)

很奇怪的问题，在本地好好的，线上就报这个错误，再导入一次就好了
```java
   
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
请至少升级到'2.0.5'版本 ，api 接口没有变化。2.0.0 存在小概率漏读数据的问题。
