### ISSUE TITLE
2.1.0-beta2，表格填充，默认为cell.getStringCellValue()，遇到数字会报Cannot get a STRING value from a NUMERIC cell

### ISSUE THREAD

**Issue by yaoshengxuan** [alibaba/easyexcel#741]
**触发场景描述**
模板表格中有数字，会报Cannot get a STRING value from a NUMERIC cell
**触发Bug的代码**
private List<AnalysisCell> readTemplateData(Map<Integer, List<AnalysisCell>> analysisCache) {
        Integer sheetNo = writeContext.writeSheetHolder().getSheetNo();
        List<AnalysisCell> analysisCellList = analysisCache.get(sheetNo);
        if (analysisCellList != null) {
            return analysisCellList;
        }
        Sheet sheet = writeContext.writeSheetHolder().getCachedSheet();
        analysisCellList = new ArrayList<AnalysisCell>();
        List<AnalysisCell> collectionAnalysisCellList = new ArrayList<AnalysisCell>();
        for (int i = 0; i <= sheet.getLastRowNum(); i++) {
            Row row = sheet.getRow(i);
            if (row == null) {
                continue;
            }
            for (int j = 0; j < row.getLastCellNum(); j++) {
                Cell cell = row.getCell(j);
                if (cell == null) {
                    continue;
                }
                boolean needFill =
                    prepareData(cell.getStringCellValue(), analysisCellList, collectionAnalysisCellList, i, j);
                // Prevent empty data from not being replaced
                if (needFill) {
                    cell.setCellValue(StringUtils.EMPTY);
                }
            }
        }
        templateAnalysisCache.put(sheetNo, analysisCellList);
        templateCollectionAnalysisCache.put(sheetNo, collectionAnalysisCellList);
        return analysisCache.get(sheetNo);
    }
```java
   prepareData(cell.getStringCellValue(), analysisCellList, collectionAnalysisCellList, i, j);
这一句不能先判断Cell.getCellType,再去根据不同getStringCellValue或者getNumericCellValue去获取Cell的Value吗？
```
**提示的异常或者没有达到的效果**
java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell

**Comment by zhuangjiaju** [comment]
是个bug 模板中有数字就会有问题。晚上发布 `2.1.0-beat3`修复这个bug
