### ISSUE TITLE
导出excel，能不能设置单元格为文本格式，否则出现身份证号码太长变为科学计数，字段为String也认为是数字

### ISSUE THREAD

**Issue by notsayyu** [alibaba/easyexcel#746]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
你用2.0.5 你用string 到excel 肯定是string。如果数字想转string 请参照自定义转换器，可以指定为数字转字符串。

**Comment by notsayyu** [comment]
用的2.1.0-beta1，实体字段是String，导出后会出现这个问题，请问是版本问题还是我漏掉了什么呢？

**Comment by notsayyu** [comment]
![image](https://user-images.githubusercontent.com/33818727/67388572-7dd83b80-f5cb-11e9-9a5e-947d9640bce5.png)
![image](https://user-images.githubusercontent.com/33818727/67388666-ad874380-f5cb-11e9-989b-aad5483cbf06.png)

**Comment by notsayyu** [comment]
![image](https://user-images.githubusercontent.com/33818727/67389342-03a8b680-f5cd-11e9-9f37-ada155725127.png)
使用的版本是2.1.0-beta1，导出后是文本，点击编辑之后会变为数字，请问这个可以代码设置为文本格式么

**Comment by zhuangjiaju** [comment]
自定义样式 设置dataformat为 48试试 应该可以
