### ISSUE TITLE
1、如何从指定的行开始读和写？2、读取的时候做数据转换，注解无法转换成BigDecimal，是否先转换成其他数字格式，再转成BigDecimal？

### ISSUE THREAD

**Issue by youerduoDog** [alibaba/easyexcel#752]

**Comment by disilence** [comment]
`EasyExcel.read(fileInputStream).sheet().headRowNumber(-1).doReadSync();`
我用这种方式从第一行开始读。默认headRowNumber应该是0，导致从第二行开始读。修改为-1之后直接从第一行开始读。如果想要从其他行读，把设置为该行的行数-1即可。

**Comment by dardaplanet** [comment]
第二个问题建议使用注解方式解决,如果使用registerConverter会进行全局设置

**Comment by zhuangjiaju** [comment]
> 1.从指定行开始读取参照com.alibaba.excel.read.builder.ExcelReaderBuilder#headRowNumber,默认值为1,表示有一行头,从第二行开始读取数据
> `EasyExcel.read(inputstream).sheet().headRowNumber(指定行).doRead()`
> 2.读取的时候数据进行转换参照com.alibaba.excel.read.builder.ExcelReaderBuilder#registerConverter或在实体类中使用注解@ExcelProperty的convert自定义转换,string转decimal可参见com.alibaba.excel.converters.bigdecimal.BigDecimalStringConverter
> `EasyExcel.read(inputstream).sheet().registerConverter(BigDecimalStringConverter)`或对应实体类中field添加@ExcelProperty(converter=BigDecimalStringConverter)

优秀
