### ISSUE TITLE
onException 方法中的异常信息无法抛出到前端

### ISSUE THREAD

**Issue by nonfou** [alibaba/easyexcel#757]
**描述**
`拿到的异常信息并不是我想要的`

![图片](https://user-images.githubusercontent.com/20853378/67540568-5f338b00-f718-11e9-98dc-f7ea352159a5.png)

![图片](https://user-images.githubusercontent.com/20853378/67540556-52169c00-f718-11e9-8b03-f17a0ba214b3.png)

**拿到的结果**

![图片](https://user-images.githubusercontent.com/20853378/67540601-7c685980-f718-11e9-94ed-6f2a24007c29.png)

**期望结果**

> 
{"code":50000,"message":"数据转换异常","success":false}

**建议描述**

按照文档上的异常处理后，拿不到主动抛出的异常提示信息
请问要怎么处理达到我的预期

**Comment by zhuangjiaju** [comment]
升级到最新版 2.1.0-beta4 或者 e.getCause()

**Comment by nonfou** [comment]
感谢 :)
