### ISSUE TITLE
如何在导出的excel表头上面一行，添加一行动态数据？？？

### ISSUE THREAD

**Issue by seaguil** [alibaba/easyexcel#761]
查询到后端数据导出excel提供下载，业务需要把前端查询条件加载表头的第一列之中，现在的表头是固定只能键值对方式存在第一行的，有啥解决的方法吗
![image](https://user-images.githubusercontent.com/38853650/67554057-2d82ea00-f741-11e9-8af1-5efac6990982.png)

- - - -- - - - -- - - -- -- - -- - - -- - --    
![image](https://user-images.githubusercontent.com/38853650/67553764-800fd680-f740-11e9-89a8-05f35ef6806a.png)

**Comment by zhuangjiaju** [comment]
参照table demo

**Comment by YanFangZhou** [comment]
哈哈，正准备找这种问题解决方法的时候，发现有前辈之前提过了

**Comment by taosehngyijiushi** [comment]
解决方法是什么呢

**Comment by andyphone** [comment]
"参照table demo"的意思是看文档这里-- "使用table去写入"
