### ISSUE TITLE
根据参数导出指定列同时设置导出列的顺序

### ISSUE THREAD

**Issue by fungoddd** [alibaba/easyexcel#762]
**建议描述**
可否在根据参数来导出指定列的同时,根据参数的传入顺序(集合的顺序)或传入索引顺序(动态参数),来对导出的excel中的列的顺序进行排序
如 name,age,sex 三个属性,实体类中设置索引为0,1,2导出的列从左到右侧顺序肯定也是name,age,sex
此时如果只根据参数导出age,name,则导出的列的顺序从左至右为age,name.或传入该导出列排序的索引

**Comment by zhuangjiaju** [comment]
理论上来说就是你说的情况

**Comment by zhuangjiaju** [comment]
有Bug 下个版本修复

**Comment by zhuangjiaju** [comment]
非常感谢您的意见 已经在`2.1.1`修复
