### ISSUE TITLE
web重复多次写入无效

### ISSUE THREAD

**Issue by qingjiaorose157** [alibaba/easyexcel#769]
**异常代码**
ExcelWriter writer = EasyExcel.write(response.getOutputStream(), DownloadData.class).build();
        WriteSheet sheet = EasyExcel.writerSheet("模板").build();
        for (int i = 0; i < 10; i++) {
            writer.write(data(), sheet);//这里只有第一次生效
        }
        writer.finish();
```
**异常提示**
重复多次写入，只有第一次生效
**建议描述**
在/test/demo/web里面添加重复多次写入的demo。

**Comment by zhuangjiaju** [comment]
这个 建议直接把github的项目下下来 直接跑。不可能只有一次生效。

**Comment by yanhuasanyue1015gmail** [comment]
也遇到这个问题   只有第一次生效
