### ISSUE TITLE
读取excel问题

### ISSUE THREAD

**Issue by dzjfromChina** [alibaba/easyexcel#77]
我用了读取excel的例子发现我sheet1里面的数据再控制台输出的时候被标注为sheet2，sheet2里面的数据被标注了sheet1

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
