### ISSUE TITLE
日期类型只支持Date，不支持LocalDate和LocalDateTime

### ISSUE THREAD

**Issue by yangbinsoft** [alibaba/easyexcel#770]
**触发场景描述**
在导出excel的时候   EasyExcel.write(fileName, c).sheet(sheetName).doWrite(data);
**触发Bug的代码**
```java

    @ApiModelProperty(value = "下次跟进时间")
    @ExcelProperty("下次跟进时间")
    private LocalDateTime nextFollowUpTime;

```
**提示的异常或者没有达到的效果**

com.alibaba.excel.exception.ExcelDataConvertException: Can not find 'Converter' support class LocalDateTime.

**Comment by zhuangjiaju** [comment]
LocalDateTime 属于jdk8.所以暂时不支持。这个需要自己自定义转换器。目前不支持 后期会考虑。

**Comment by yangbinsoft** [comment]
谢谢，我已经自定义转换器了，可以导出LocalDateTime 了

**Comment by gaohanghang** [comment]
希望能够支持java8，目前我是参考这篇文章写得转换器

https://juejin.im/post/5db3aba7518825645656bea4

**Comment by ricardo0624** [comment]
感觉有些无语,框架本来就是简化劳动的,java8已经多少年了,都2020了,可以预见用了easyExcel的人,多少人写了多少个LocalDateConverter,LocalDateTimeConverter,为什么不能支持呢?为什么呢?呢?
