### ISSUE TITLE
excel模板中指定表头信息,将数据写入模板中时如何能根据列号将数据写入指定列

### ISSUE THREAD

**Issue by Limbozombie** [alibaba/easyexcel#773]
比如 模板中 表头为  A B C D
我的数据为 [ [ B1,C1 ], [ B2, C2] ]

导出为
A |    B    |  C    | D
    |    B1 |  C1  |
    |   B2  |  C2  |

**Comment by Limbozombie** [comment]
好像可以使用填充来实现 ( doFill )

**Comment by zhuangjiaju** [comment]
只能fill

**Comment by gem-groups** [comment]
fill在哪个版本有呢？我看2.0及以上都没有fill了。

**Comment by Limbozombie** [comment]
> fill在哪个版本有呢？我看2.0及以上都没有fill了。

我用的2.1.0-beta4 ,应该是2.1.x版本新增的
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>easyexcel</artifactId>
			<version>2.1.0-beta4</version>
		</dependency>
