### ISSUE TITLE
关于通过对象读取发生数据转换异常的优化

### ISSUE THREAD

**Issue by zengguangping** [alibaba/easyexcel#781]
**建议描述**

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>2.1.0-beta1</version>
        </dependency>

1. 表格数据  
![image](https://user-images.githubusercontent.com/48940784/67936107-1d1db400-fc06-11e9-8726-5d282328a02b.png)  

2.异常返回的行数为2  列数也为2   实际表格为C3格
因为可能需要给用户看处理日志，这里需要我们去做处理进行转换

3.而且异常信息可能需要给用户查看以中文展示，能否通过异常直接获取异常的数据内容，而不需要再进行解析
所以希望你们能做一下优化从而我们使用都不需要做额外的处理
![image](https://user-images.githubusercontent.com/48940784/67936508-e2684b80-fc06-11e9-8152-c6dd6e444587.png)
![image](https://user-images.githubusercontent.com/48940784/67936770-573b8580-fc07-11e9-9139-9f5caa0c0799.png)

**Comment by zhuangjiaju** [comment]
提示信息还需要自己拼接，后续会加入异常单元格的值

**Comment by zhuangjiaju** [comment]
已经在最新版加入了单元格的内容，行号，列号还需要自己转换。
