### ISSUE TITLE
使用fill填充后，excel的公式无法自动计算

### ISSUE THREAD

**Issue by gem-groups** [alibaba/easyexcel#782]
![image](https://user-images.githubusercontent.com/50982354/67938188-fc575d80-fc09-11e9-8c3d-a3cf0879dd82.png)
fill之后：
![image](https://user-images.githubusercontent.com/50982354/67938256-1a24c280-fc0a-11e9-96af-5e8c7e6d0ccc.png)

**Comment by zhuangjiaju** [comment]
由于数据不在内存，目前没法解决您的问题。您可以尝试 自己计算完成，或者`inMemory` 参数，然后自定义拦截，使用poI的写法去处理。
