### ISSUE TITLE
最新版本2.1.0-beta4读取全部sheet会重复读数据？

### ISSUE THREAD

**Issue by jackyzheng123** [alibaba/easyexcel#786]
```java
   // 读取全部sheet 最新版本2.1.0-beta4
   EasyExcel.read(fileName, clazz, listener).doReadAll();
```

**建议描述**
发现用最新版本2.1.0-beta4读取全部sheet，有些数据会重复读

**Comment by zhuangjiaju** [comment]
请详细描述您的问题，并提供代码。以及日志，最好也提供excel.

**Comment by jackyzheng123** [comment]
解决了，是我自己的bug，大于3000阀值余量的没清掉。谢谢

public class MainTest {

    private static final Logger log = LoggerFactory.getLogger(MainTest.class);

    private static final String FILE = "C:/Users/zhengjiaxing/Desktop/test.xlsx";

    public static void main (String[] args){
        Stopwatch stopwatch = Stopwatch.createStarted();
        List<JimiCartonImportDto> tempList = Lists.newCopyOnWriteArrayList();
        AnalysisEventListener<JimiCartonImportDto> listener = EasyExcelUtils.getListener(list -> {
            // 保存数据
            tempList.addAll(list);
        }, 3000);

        EasyExcel.read(FILE, JimiCartonImportDto.class, listener).doReadAll();
        log.info("总导入数据tempList：{}条, 耗时{}秒", tempList.size(), stopwatch.elapsed(TimeUnit.SECONDS));
        log.info("total:" + EasyExcelUtils.count.get());
        EasyExcelUtils.count.set(0);
    }
}


// EasyExcelUtils工具类
public static <T> AnalysisEventListener<T> getListener(Consumer<List<T>> consumer, int threshold) {
        return new AnalysisEventListener<T>() {

            private List<T> list = new LinkedList<T>();

            @Override
            public void invoke(T t, AnalysisContext analysisContext) {
                LOGGER.info("解析到一条数据:{}", JSON.toJSONString(t));
                if (t != null) {
                    count.incrementAndGet();
                    list.add(t);
                }
                if (list.size() == threshold) {
                    consumer.accept(list);
                    list.clear();
                }
            }

            @Override
            public void doAfterAllAnalysed(AnalysisContext analysisContext) {
                if (list.size() > 0) {
                    consumer.accept(list);
                    list.clear(); // 余量要清掉
                }
                LOGGER.info("所有数据解析完成！");
            }
        };
    }
