### ISSUE TITLE
关于针对大文件的excel的编辑功能

### ISSUE THREAD

**Issue by ulyn** [alibaba/easyexcel#793]
**建议描述**
经常的，我们会对导入的excel文件逐条处理，发现有异常时，希望能在该行加上错误信息一列以及样式高亮。
easyexcel有读有写，如果能将编辑的能力开放出来，能力又进一步提升

**Comment by zhuangjiaju** [comment]
非常感激您的意见。短时间内不会支持。因为读 是自己写的。而写只是封装了poi ，所以兼容非常困难，后续可能考虑。但是短期内不会支持。
