### ISSUE TITLE
关于带有公式的特殊文本解析，也就是上标、下标，sub、sup 这些特殊情况的解析问题。

### ISSUE THREAD

**Issue by iqeq00** [alibaba/easyexcel#795]
**建议描述**
最近项目里面大量用到 easyexcel，但有一个需求，确实是开始没有想到的情况。
在进行 xls 读取导入操作的时候，遇到了一个特殊的数据格式。
![QQ截图20191104160627](https://user-images.githubusercontent.com/1817828/68106671-4fd4ee80-ff1d-11e9-9450-5d30b05f7bef.jpg)
就是 xls 里面包含公式的这种特殊形式，是包含上标、下标这种格式的。

在通过相关资料查询后，发现这种情况，在 poi 是处理了的。通过判断，动态增加 sub、sup 这些标签来完成。 [https://www.jianshu.com/p/9106c8472d3b](url)

但是，通过测试，目前 easyexcel 好像是直接忽略掉了这些 tag，读取出来的数据是：

解析到一条数据:{"gname":"王家河沙溪庙组（J2s）与新田沟组（J2xt）接触界线","type":"地方性标准剖面","lat":"104.170055555546","lng":"29.508333333331102","feature":"位于荣县来牟镇大桊树村，东经104°10′12.23″，北纬29°30′30.02″。为王家河沙溪庙组（J2s）与新田沟组（J2xt）接触界线，接触面及岩性清楚。界线北西侧为沙溪庙组（J2s），岩性为黄灰色块状粗砂岩，单层厚约15m，出露厚约15-20m，发育少量平行层理和交错层理，纹层厚约1-4cm，砂岩表面受风化作用影响，较光滑，同时发育1组纵向节理，把砂岩绝壁裂解为几个岩柱，形似总统山，中部被人为挖掘出几个岩穴，如人脸，推测为放棺材或佛像地。界线南东侧为新田沟组（J2xt），岩性为暗黄色、灰黑色粉砂岩、紫红色泥岩，暗黄色粉砂岩发育水平层理，纹层厚约2-7cm，出露厚约45cm，局部被风化，较破碎；灰黑色粉砂岩出露厚约22cm，与暗黄色粉砂岩呈渐变关系；紫红色泥岩出露厚约50cm以上，强风化，表面较破碎。接触面弱波状起伏，接触面产状：231°∠6°。周边都为绝壁，绝壁下种植大量茶树，风景十分优美。}

不知道在未来的版本，能否考虑支持这种特殊模式的格式解析，或者是可以扩展一个方式，让开发者动态传入解析 poi 的规则。

望关注，谢谢。

**Comment by zhuangjiaju** [comment]
这个后续会处理。但是会比较慢。

**Comment by zhuangjiaju** [comment]
发现需求量很小，暂时不兼容
