### ISSUE TITLE
2.0.5版本，xlsx文件，小数点类型数据会丢失精度

### ISSUE THREAD

**Issue by tomtigger** [alibaba/easyexcel#802]
2.0.5版本，xlsx文件，小数点类型数据会丢失精度，比如 1.1 解析得到的数据是 1.1000000000000001，同样的数据 xls 文件没有问题。
[template.zip](https://github.com/alibaba/easyexcel/files/3812210/template.zip)

**Comment by zhuangjiaju** [comment]
这个目前没法处理，建议用@NumberFormat 来解决。后续会解决。
