### ISSUE TITLE
你好，能否增加.csv文件格式的导入导出解析

### ISSUE THREAD

**Issue by yuanlihonggit** [alibaba/easyexcel#803]
.csv文件为文本格式，所以上传的数据都是string，不用担心其他格式转换的问题，相对来说格式上不用担心string转date，及证件号码导入excel中出现的科学计数法等显示问题

该种类型文件还是很常用的，麻烦采纳

**Comment by zhuangjiaju** [comment]
目前还有问题要处理。后续会考虑csv，但是会比较慢。
