### ISSUE TITLE
导出列顺序动态自定义

### ISSUE THREAD

**Issue by mrjasonjiang** [alibaba/easyexcel#809]
我在使用中有导出指定列，且列的顺序需要自定义的问题
请问在工具的封装中有吗
我在文档中没有发现对应的实现

**Comment by mrjasonjiang** [comment]
看了源码，经过几番摸索，通过实现RowWriteHandler
修改
```
ExcelWriteHeadProperty excelWriteHeadProperty = writeSheetHolder.excelWriteHeadProperty();
Map<Integer, ExcelContentProperty> contentPropertyMap=excelWriteHeadProperty.getContentPropertyMap();
```
修改cotentPropertyMap达到改变导出顺序的需求
****
但是还是希望能提供相应的实现ヽ(°◇° )ノ

**Comment by zhuangjiaju** [comment]
导出列 根据class的顺序 或者 class里面 `ExcelProperty`来指定。或者根据传入头 的顺序。
