### ISSUE TITLE
读取excel 解析结果不对

### ISSUE THREAD

**Issue by xionggaogao123** [alibaba/easyexcel#81]
读取excel 时，数据全乱了

**Comment by wangwengeek** [comment]
private void initSharedStringsTable() throws IOException, ParserConfigurationException, SAXException {

        InputStream inputStream = new FileInputStream(this.sharedStringXMLFilePath);
        //this.sharedStringsTable = new SharedStringsTable();
        //this.sharedStringsTable.readFrom(inputStream);

        XmlParserFactory.parse(inputStream, new DefaultHandler() {
            //int lastElementPosition = -1;
            //
            //int lastHandledElementPosition = -1;

            String beforeQName = "";

            String currentQName = "";

            boolean flag = false;
            @Override
            public void startElement(String uri, String localName, String qName, Attributes attributes) {
                //if (hasSkippedEmptySharedString()) {
                //    sharedStringList.add("");
                //}
                //if ("t".equals(qName)) {
                //    lastElementPosition++;
                //}
                if ("si".equals(qName) || "t".equals(qName)) {
                    beforeQName = currentQName;
                    currentQName = qName;
                    if ("t".equals(currentQName)&& "si".equals(beforeQName)){
                        if (flag == true){
                            sharedStringList.add(null);
                        }
                        flag = true;
                    }
                }
            }
            //@Override
            //public void endElement (String uri, String localName, String qName)
            //    throws SAXException
            //{
            //    if ("si".equals(qName) || "t".equals(qName)) {
            //        beforeQName = qName;
            //        currentQName = "";
            //    }
            //}

            //private boolean hasSkippedEmptySharedString() {
            //    return lastElementPosition > lastHandledElementPosition;
            //}

            @Override
            public void characters(char[] ch, int start, int length) {
                if ("t".equals(currentQName) && ("t".equals(beforeQName))) {
                    String pre = sharedStringList.get(sharedStringList.size() - 1);
                    String str = pre + new String(ch, start, length);
                    sharedStringList.remove(sharedStringList.size() - 1);
                    sharedStringList.add(str);
                    flag = false;
                }else  if ("t".equals(currentQName) && ("si".equals(beforeQName))){
                    sharedStringList.add(new String(ch, start, length));
                    flag = false;
                }
                // lastHandledElementPosition++;


            }

        });
        inputStream.close();
    }

**Comment by jipengfei-jpf** [comment]
由于1.0.*版本核心考虑的是怎么解决读excel内存溢出问题，自己重写了读excel的POI的底层，写仍旧使用POI。可以从根本解决OOM问题。但是由于自己对excel的格式认识不全面，有很多坑产生了很多BUG。最新版本以POI为底层。最新版：1.1.2-beat1，虽然不能完全解决OOM但可以解决大部分的OOM问题，完全解决OOM版本会等稳定后再开放，敬请理解。目前稳定版本1.1.2-beat1
