### ISSUE TITLE
Writing excel boolean field issue 

### ISSUE THREAD

**Issue by busrauman** [alibaba/easyexcel#812]
**I can not write the boolean field to the excel cell. Field is always empty**

**触发Bug的代码**
```java
@ExcelProperty(converter = BooleanNumberConverter.class)
  private Boolean isActive ;
```

**I change poi version from 3.17 to 4.1.1  because I got the exception when I implement the library spring boot project ( exception was Class Not found org.apache.poi.ss.usermodel.IndexedColors)
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
You do not need to specify `converter`。
```java
    EasyExcel.write(fileName, DemoData.class).sheet("模板").doWrite(data());
```
Just make sure 'data()' returns a value.

**Comment by busrauman** [comment]
I'm sure data() returns value to me. I can see other field in the file.
```java
     EasyExcel.write(fileName, Data.class).sheet("busra").doWrite(data());
     
    //my method 
    private static List<Data> data() {
        List<Data> list = new ArrayList();
        for (int i = 0; i < 200000; i++) {
             Data data = new Data();
             data.setName("busra " + i);
             data.setNumber(5.2 * i);
             data.setDesc("text");
             data.setActive(Boolean.TRUE);
             list.add(data);
        }
        return list;
    }
```

**Comment by pdkst** [comment]
Is "active" and "isActive" the same field?

**Comment by busrauman** [comment]
Yes They are same.

**Comment by pdkst** [comment]
> Yes They are same.
> setActive() is a setter method for isActive field.
> 
> I also tried to set default value in my Data class but nothing change.
> **I'm using jdk 11 and I tried with jdk 8**

I'm sure this is a bug because a boolean field starts with "is".
But it's better not to use a boolean field that starts with "is".
