### ISSUE TITLE
整数变成浮点数

### ISSUE THREAD

**Issue by baifenbai** [alibaba/easyexcel#814]
数字例如 1 解析后变成浮点数1.0，怎么解决这个问题。如何让数字识别为文本字符串？

**Comment by zhuangjiaju** [comment]
使用`@NumberFormat`注解 或者 将excel 设置为文本。这是个bug,后续会兼容。

**Comment by baifenbai** [comment]
收到，十分感谢。使用Numberformat解决了问题。但Excel单元格格式数字改为文本没有解决这个问题。



---原始邮件---
发件人: "Jiaju Zhuang"<notifications@github.com&gt;
发送时间: 2019年11月7日(星期四) 晚上6:41
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送: "baifenbai"<1579150763@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [alibaba/easyexcel] 整数变成浮点数 (#814)



Closed #814.
