### ISSUE TITLE
没有maven的依赖吗？

### ISSUE THREAD

**Issue by Xanthuim** [alibaba/easyexcel#816]
**建议描述**
加个maven的依赖吧，还是说自己去找。。

**Comment by pdkst** [comment]
maven中央仓库有：
```https://mvnrepository.com/artifact/com.alibaba/easyexcel```

**Comment by zhuangjiaju** [comment]
在主页 有个`maven central` 的tag ，点进去就有。一般开源项目都是这个流程。
