### ISSUE TITLE
数据导出时，怎么让excel文件列宽自适应数据长度？

### ISSUE THREAD

**Issue by wyldusername** [alibaba/easyexcel#818]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by pdkst** [comment]
先按照官方教程试试看：[自动列宽](https://alibaba-easyexcel.github.io/quickstart/write.html#%E8%87%AA%E5%8A%A8%E5%88%97%E5%AE%BD-%E4%B8%8D%E5%A4%AA%E7%B2%BE%E7%A1%AE)

**Comment by zhuangjiaju** [comment]
目前 没有很好的办法。你可以按照楼上demo试试
