### ISSUE TITLE
并发写excel报错,A part with the name '/xl/worksheets/sheet1.xml' already exists

### ISSUE THREAD

**Issue by zuochangqin** [alibaba/easyexcel#82]
下面是我的代码:
@Test
	public void testThread() throws FileNotFoundException, InterruptedException {
		ExecutorService executorService = new ThreadPoolExecutor(5, 10, 1, TimeUnit.HOURS, new LinkedBlockingQueue());
		int MAXROW = 5000;
		Integer size = 100000;
		Integer sheetNum = 1;
		//计算需要生产的sheet数量
		if (size > MAXROW) {
			int less = size % MAXROW;
			if (less > 0) {
				sheetNum = size / MAXROW + 1;
			} else {
				sheetNum = size / MAXROW;
			}
		}
		OutputStream os = new FileOutputStream("/Users/ic/77.xlsx");
		ExcelWriter writer = new ExcelWriter(os, ExcelTypeEnum.XLSX);
		CountDownLatch doneSignal = new CountDownLatch(sheetNum);//计数
		for (int i = 0; i < sheetNum; i++) {
			//开始id
			int startIdx = i * MAXROW;
			//结束id
			int endIdx = (i + 1) * MAXROW - 1;
			//如果为最后一个sheet
			if (i == sheetNum - 1) {
				endIdx = size - 1;
			}
			PoiWriter poi = new PoiWriter(doneSignal, writer, startIdx,
					endIdx, i);
			executorService.submit(poi);
		}
		doneSignal.await();//等待所有sheet页创建完成
		writer.finish();
	}

public class PoiWriter implements Runnable {

	private final CountDownLatch doneSignal;

	private ExcelWriter writer;

	private int start;

	private int end;

	private int index;

	public PoiWriter(CountDownLatch doneSignal, ExcelWriter writer, int start,
	                 int end,int index) {
		this.doneSignal = doneSignal;
		this.writer = writer;
		this.start = start;
		this.end = end;
		this.index = index;
	}

	public void run() {
		try {
			Sheet sheet = new Sheet(index + 1, 0);
			sheet.setSheetName(String.valueOf(index + 1));
			List<List<String>> dataList = new ArrayList<List<String>>();
			createTitleRow(dataList);
			createRows(dataList);
			writer.write0(dataList, sheet);
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			doneSignal.countDown();
		}
	}

	/**
	 * 创建标题栏
	 *
	 * @param dataList
	 */
	private void createTitleRow(List<List<String>> dataList) {
		List<String> titleList = new ArrayList<String>();
		for (int i = 0; i < 10; i++) {
			String title = i + "标题";
			titleList.add(title);
		}
		dataList.add(titleList);
	}

	/**
	 * 填行数据
	 *
	 * @param dataList
	 */
	private void createRows(List<List<String>> dataList) {
		for (int i = start; i <= end; i++) {
			List<String> rowList = new ArrayList<String>();
			for (int j = 0; j < 10; j++) {
				String value = i+""+j;
				rowList.add(value);
			}
			dataList.add(rowList);
		}
	}

}
并发写excel报错:
org.apache.poi.openxml4j.exceptions.PartAlreadyExistsException: A part with the name '/xl/worksheets/sheet1.xml' already exists : Packages shall not contain equivalent part names and package implementers shall neither create nor recognize packages with equivalent part names. [M1.12]
	at org.apache.poi.openxml4j.opc.OPCPackage.createPart(OPCPackage.java:889)
	at org.apache.poi.openxml4j.opc.OPCPackage.createPart(OPCPackage.java:853)
	at org.apache.poi.POIXMLDocumentPart.createRelationship(POIXMLDocumentPart.java:558)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:858)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:677)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:83)

**Comment by ming-jock** [comment]
这个应该是sheet重名了

**Comment by jipengfei-jpf** [comment]
easyexcel不能并发写
