### ISSUE TITLE
建议：写Sheet的时候，增加参数判断是否需要合并head的cell

### ISSUE THREAD

**Issue by lixingxing16888** [alibaba/easyexcel#822]
版本: 2.1.1
类: WriteContextImpl.java 
方法: initHead(ExcelWriteHeadProperty excelWriteHeadProperty)
代码片段:
`// Combined head
 addMergedRegionToCurrentSheet(excelWriteHeadProperty, newRowIndex);`

当前实现，是强制合并相同内容的临近cell了，有些时候可能不需要合并。
建议增加参数判断是否需要开启合并head cell。
thx!

**Comment by zhuangjiaju** [comment]
可以 这个以前有人提过 忘记了。建议目前 可以稍微加个字符区别。

**Comment by disilence** [comment]
可以指定坐标进行合并的

**Comment by weiwensangsang** [comment]
```
 EasyExcel.write(fileName, DemoData.class).sheet("模板").doWriteNomerge(data());

 EasyExcel.write(fileName, DemoData.class).sheet("模板").doWrite(data(), false);
```
这两种方式都能通过增加参数实现，且不影响doWrite(data()）的正常调用。
请问对于这个问题来说哪种更好呢？

**Comment by pdkst** [comment]
> ```
>  EasyExcel.write(fileName, DemoData.class).sheet("模板").doWriteNomerge(data());
> 
>  EasyExcel.write(fileName, DemoData.class).sheet("模板").doWrite(data(), false);
> ```
> 
> 这两种方式都能通过增加参数实现，且不影响doWrite(data()）的正常调用。
> 请问对于这个问题来说哪种更好呢？
> @zhuangjiaju

我喜欢这种的
```java
EasyExcel.write(fileName, DemoData.class).sheet("模板").mergeHead(false).doWrite(data());
```

**Comment by zhuangjiaju** [comment]
已经在`2.1.3`上面加入参数`automaticMergeHead`
