### ISSUE TITLE
读Excel时, Model使用了lombok.experimental.Accessors注解会导致读不到值

### ISSUE THREAD

**Issue by MaoQiankun97** [alibaba/easyexcel#836]
**触发场景描述**
在com.alibaba.easyexcel.test.demo.read.ReadTest#simpleRead方法中将DemoData类加上@Accessors(chain = true)注解，其他不变，会导致读取到的对象中值为null
![image](https://user-images.githubusercontent.com/24428913/68746785-4857c880-0634-11ea-9464-ae250ba3c4f0.png)
![image](https://user-images.githubusercontent.com/24428913/68747072-c74d0100-0634-11ea-9e1b-67f7ebdc1091.png)

**Comment by zhuangjiaju** [comment]
这个后续会考虑解决。需要改cglib比较麻烦，建议先删除。
