### ISSUE TITLE
建议: ignoreEmptyRow(false)不要忽略空行(从未操作过的空行)

### ISSUE THREAD

**Issue by lixingxing16888** [alibaba/easyexcel#837]
**建议描述**
ignoreEmptyRow(false) 可以不忽略空行 (这个应该是有操作过的空行)
但是有些空行，依然过滤的掉了，这个猜测是从未操作的行

**Comment by lixingxing16888** [comment]
AnalysisEventListener.invoke 参数 AnalysisContext context，打印当前行号，是跳过了一些行的(猜测是未操作过的行)

**Comment by zhuangjiaju** [comment]
这个是这样子的 有些行excel里面根本没有写，所以不会回调。这个只能针对有返回数据，但是为空的。

**Comment by lixingxing16888** [comment]
“有些行excel里面根本没有写”
如果我想获取这行，有什么办法处理吗？

**Comment by lixingxing16888** [comment]
还是只能 在 Listerner.invoke 里面自己判断一下是否有丢失的行数，然后模拟一个空行？

**Comment by AlbertZhang1993** [comment]
> 

解决了不
