### ISSUE TITLE
missing value in result file

### ISSUE THREAD

**Issue by avp90** [alibaba/easyexcel#838]
Hello,

i copied your simpleFill method in my scala project to test the implementation, but the result file contains only the template. The Value "张三" and 5.2 is missing.

```scala
  class FillData(name: String, number: Double)

  def simpleFill(template: File, resultFile: File): File = {
    val fillData = new FillData("张三", 5.2)
    EasyExcelFactory
      .write(resultFile)
      .withTemplate(template)
      .sheet(0)
      .doFill(fillData)
    resultFile
  }
```

**Comment by pdkst** [comment]
FillData requires getter and setter methods，I am not sure if it is generated

**Comment by avp90** [comment]
It seam that the getter and setter methods was missing.
