### ISSUE TITLE
写数据时写入指定sheet后其他sheet丢失

### ISSUE THREAD

**Issue by memorate** [alibaba/easyexcel#839]
**触发场景描述**
　写数据时写入指定sheet后其他sheet丢失
<br/>
**触发Bug的代码**
```java
        ExcelWriter writer = EasyExcel.write(inFileName).build();
        WriteSheet sheet = EasyExcel.writerSheet(8, "sheet9").head(Relation.class).build();
        writer.write(relationList, sheet);
        writer.finish();
```
**提示的异常或者没有达到的效果**
<br/>
　Excel中共有10个sheet，我只向第9个sheet中写入数据后，其他9个sheet数据丢失。  
___
　写入前
![10](https://user-images.githubusercontent.com/45744410/68822371-b8fdf400-06cb-11ea-883c-4c7131254864.png)
___
　写入后
![20](https://user-images.githubusercontent.com/45744410/68822378-bbf8e480-06cb-11ea-9b70-e6e808200e2c.png)

**Comment by pdkst** [comment]
excel写入并不会考虑之前的数据情况，如果想要保留数据应该使用API
```
com.alibaba.excel.write.builder.ExcelWriterBuilder#withTemplate(java.lang.String)
com.alibaba.excel.write.builder.ExcelWriterBuilder#withTemplate(java.io.File)
com.alibaba.excel.write.builder.ExcelWriterBuilder#withTemplate(java.io.InputStream)
```
数据量较小时可以直接将数据加载到内存里覆盖原来的文件，数据量大的情况还是生成额外的文件比较好

**Comment by memorate** [comment]
> withTemplate

```java
      ExcelWriterBuilder excelWriterBuilder = new ExcelWriterBuilder();
      excelWriterBuilder.autoCloseStream(true);
      excelWriterBuilder.withTemplate(inFileName).sheet(8, "sheet9").head(Relation.class).doWrite(relationList);
 ```
这个ExcelWriterBuilder怎么关闭  0.0  
![1111](https://user-images.githubusercontent.com/45744410/68830537-ec01b100-06e6-11ea-8e6a-a02ccb2c966e.png)

**Comment by pdkst** [comment]
你没有指定输出文件
```java
EasyExcel.write(fileName, DemoData.class).withTemplate(templateFileName).sheet().doWrite(data());
```
参考[官方demo](https://alibaba-easyexcel.github.io/quickstart/write.html#%E6%A0%B9%E6%8D%AE%E6%A8%A1%E6%9D%BF%E5%86%99%E5%85%A5)

**Comment by memorate** [comment]
**感谢！！**  
<br/>
但还是不行， fileName文件是写成功了，但是里面其他sheet仍然丢失了，templateFileName里未写入数据。  
算了，我还是写到一个新的文件里吧。 

**建议将“写入指定sheet，其他sheet可不更改”作为一个feature投入任务池**
