### ISSUE TITLE
导出的时候希望能支持一对多的导出

### ISSUE THREAD

**Issue by zmj-hub** [alibaba/easyexcel#842]
**建议描述**
导出的时候希望可以支持一对多的导出，即导出的的实体类里面有List，希望可以在导出的Excel中可以实现一对多，然后前面重复部分为空后面一对多（list）部分显示出来，希望可以解决这个问题

**Comment by zhuangjiaju** [comment]
非常感谢您的意见。这个比较复杂，所以短期内不会实现。后续会考虑。暂时先关闭问题。

**Comment by cxwangxixi** [comment]
这种对象嵌套导出，其实可以考虑提供，做报表的很常见
