### ISSUE TITLE
希望doWrite方法能支持List<Map> 数据类型

### ISSUE THREAD

**Issue by hjnjmjkj** [alibaba/easyexcel#844]
**建议描述**
希望doWrite方法能支持List<Map> 数据类型

目前的代码需要将dubbo泛化调用返回的的List<Map>转换为List<Class>
List exportList = new ArrayList(((List) data).size());
for (Object map : (List<Object>)data) {
    if (map instanceof Map) {
        Object object = dataClass.newInstance();
        BeanUtils.copyProperties(object, map);
        exportList.add(object);
     }
}
EasyExcel.write(servletResponse.getOutputStream(), dataClass).sheet(dataClass.getName()).doWrite(exportList);

我是通过dubbo泛化调用获得的数据 dubbo将List<Class> 转换为了List<Map>了， 我们通过dubbo的泛化调用实现了网关，将http请求转换为excel下载流。

**Comment by pdkst** [comment]
虽然不支持map，但是支持list，可以试试这个代码
```java
//过滤掉不是map的、为null的list
List<List> exportList = (((List<Map>) data).stream().map(Map::values).collect(Collectors.toList()));
EasyExcel.write(servletResponse.getOutputStream(), dataClass).sheet(dataClass.getName()).doWrite(exportList);
```

jdk7和以下
```
        //过滤掉不是map的、为null的list
        List<List> exportList = new ArrayList<>();
        for (Map map : (((List<Map>) data) ){
            if(map != null){
                exportList.add(map);
            }
        }
        EasyExcel.write(servletResponse.getOutputStream(), dataClass).sheet(dataClass.getName()).doWrite(exportList);
```

**Comment by zhuangjiaju** [comment]
考虑很久 map 需要配合head使用 暂时不支持。map 很容易无序
