### ISSUE TITLE
导出Excel表时上一个字段数据过长而下一个字段数据为空时 则数据会覆盖空值的单元格上

### ISSUE THREAD

**Issue by hlfatter** [alibaba/easyexcel#845]
![image](https://user-images.githubusercontent.com/43473741/68914623-1e201b00-079a-11ea-9b9e-2b14ecd8ed1d.png)

**Comment by pdkst** [comment]
这个是excel的特性，单元格格式选择 水平对齐—填充，就不会出现溢出现象
代码实现参考[官方demo-自定义样式](https://alibaba-easyexcel.github.io/quickstart/write.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)
增加一行这样的样式即可
`contentWriteCellStyle.setHorizontalAlignment(HorizontalAlignment.FILL);`

**Comment by hlfatter** [comment]
好的 已经解决 谢谢

**Comment by hlfatter** [comment]
![image](https://user-images.githubusercontent.com/43473741/68920409-15d2da80-07b0-11ea-9136-1175388890dd.png)
但是这样设置会导致过短的字段会自动填充以至于对齐啊

**Comment by pdkst** [comment]
单元格长度过短的话可以试试官方[demo-列宽、行高](https://alibaba-easyexcel.github.io/quickstart/write.html#%E5%88%97%E5%AE%BD%E3%80%81%E8%A1%8C%E9%AB%98)
`    @ColumnWidth`
如果希望它自适应宽度可以采用[官方demo-自动列宽](https://alibaba-easyexcel.github.io/quickstart/write.html#%E8%87%AA%E5%8A%A8%E5%88%97%E5%AE%BD-%E4%B8%8D%E5%A4%AA%E7%B2%BE%E7%A1%AE)

**Comment by hlfatter** [comment]
是我在设置单元格格式选择 水平对齐—填充这个样式zhi'h之后会出现下面这个现象
![image](https://user-images.githubusercontent.com/43473741/68921168-c5a94780-07b2-11ea-914b-c47bfc978e52.png)

**Comment by pdkst** [comment]
填充只适合全都是比较长的列，如果只是一些比较长的就不要这样设置了，
溢出也只会出现在下一个列没有内容的情况，所以，不影响业务的情况下，多写一个空格就可以（邪道）

**Comment by hlfatter** [comment]
You are such a small ghost.
