### ISSUE TITLE
实体类字段第一个字母小写第二个字母大写，取不到值，如pDate

### ISSUE THREAD

**Issue by dongloveying0706** [alibaba/easyexcel#846]
**触发场景描述**
经测试，属性字段名称，大写字母前必须有2位以上的小写字母，不然实体字段的值一直为null
**触发Bug的代码**
```java
    @ExcelProperty(value = "航班日期", index = 0)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
   private Date pDate;
```
**提示的异常或者没有达到的效果**
pDate的值永远为null

**Comment by zhang7249** [comment]
按照阿里代码规范，变量名见名知意，一个单词的场景不多吧

**Comment by pdkst** [comment]
定义：
```java
    @ExcelProperty
    private String sActive;
```
设置数据的地方
`data.setSActive("sActive");`
读取的地方：
![image](https://user-images.githubusercontent.com/8915631/68926466-8f72c480-07c0-11ea-9456-ca2dd69dd805.png)
先暂时避免这样的字段

**Comment by dongloveying0706** [comment]
好的，谢谢啦！
