### ISSUE TITLE
多表头如何读取？

### ISSUE THREAD

**Issue by fuzhixuan** [alibaba/easyexcel#851]
实体类如下：
![image](https://user-images.githubusercontent.com/24598917/68933657-14b1a580-07d0-11ea-91de-a5c20b76d46e.png)
读取的excel：
![image](https://user-images.githubusercontent.com/24598917/68933793-65c19980-07d0-11ea-9df5-747909b20c34.png)
执行+结果：
![image](https://user-images.githubusercontent.com/24598917/68933688-28f5a280-07d0-11ea-8f5a-df87c7e87e8b.png)

为啥表头值映射到实体类中了呢？

**Comment by pdkst** [comment]
关键的读取的代码没有贴……我把我能成功读取的代码给你参考看看
```java
@Data
public class MultipleData {
    @ExcelProperty({"基本信息", "a", "姓名"})
    private String name;
    @ExcelProperty({"基本信息", "b", "年龄"})
    private Integer age;
    @ExcelProperty(value = {"手机号","手机号","手机号"}, index = 2)
    private String phone;
}
```
监听器
```java
@Slf4j
public class MultipleDataListener extends AnalysisEventListener<MultipleData> {
    @Override
    public void invoke(MultipleData multipleData, AnalysisContext analysisContext) {
        log.info("data = {}", multipleData);
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext analysisContext) {

    }
}
```
测试类
```java
    @Test
    public void testMultiple() throws IOException {
        final ClassPathResource resource = new ClassPathResource("excel/multiple.xlsx");
        EasyExcel.read(resource.getInputStream(), MultipleData.class, new MultipleDataListener()).doReadAll();
    }
```
@Data是lombok的注解
![image](https://user-images.githubusercontent.com/8915631/68942374-6e6f9b00-07e3-11ea-90d0-0e63165fcdcb.png)
![image](https://user-images.githubusercontent.com/8915631/68942396-7cbdb700-07e3-11ea-93cc-d8f6001d44b8.png)

**Comment by fuzhixuan** [comment]
OK，可以用了，我用的是别人封装的方法，有问题

**Comment by hxnlyw** [comment]
![image](https://user-images.githubusercontent.com/30015066/118639870-f2f10e80-b80a-11eb-8d5f-86f10b9d380e.png)
这种表格能读取吗
