### ISSUE TITLE
导出$jacocoData

### ISSUE THREAD

**Issue by Code-Xiaoda** [alibaba/easyexcel#852]
在使用jacoco的测试环境进行excel导出，会自动多出表头为$jacocoData的一列

**Comment by pdkst** [comment]
应该是测试类被jacoco代理了，动态添加了$jacocoData字段
对于这样的，easyexcel有个注解`@ExcelIgnoreUnannotated`，放到bean上面之后，只会导出被`@ExcelProperty`注解修饰的属性，这样应该就不会导出多余的字段，
**不过，导出的属性需要全部都被`@ExcelProperty`注解修饰**

**Comment by zhuangjiaju** [comment]
尝试升级到 2.1.3以上版本
