### ISSUE TITLE
一个excel多个不同数据模型的sheet 

### ISSUE THREAD

**Issue by cherishYX** [alibaba/easyexcel#860]
**建议描述**
EasyExcel.write(fileName, DemoData.class).sheet("模板").doWrite(data());

功能:  实现1个excel多个不同数据模型的sheet 

增加这种类似的实现
EasyExcel.write(fileName, DemoData.class).sheet("模板").data(data())
               .write(fileName, DemoData2.class).sheet("模板2").data(data2())
               .dowrite();

以下代码可实现上述功能, 但是设置项太多 , head等信息都需要单个去设置. 
注解 @ExcelProperty解析不出来, 而且填充的每行数据中如果有null的时候, 会跳过cell ,用后面的列填充
`public static void createExcel(OutputStream out, List<ExportExcelInfo> excelOutDto){
        Assert.isTrue(!CollectionUtils.isEmpty(excelOutDto),"导出信息为空");
        ExcelWriter writer = EasyExcel.write(out).build();
        excelOutDto.forEach(dto -> {
            writer.write(dto.getDatas(),dto.getSheet());
        });
        writer.finish();
    }`

**Comment by zhuangjiaju** [comment]
这个有考虑过，但是后来为了少写个`finish`，放弃了这种方案。因为 我不知道你什么时候finish。
