### ISSUE TITLE
用easyexcel导出时怎么合并单元格呢

### ISSUE THREAD

**Issue by Winelfeng** [alibaba/easyexcel#862]
如题

**Comment by pdkst** [comment]
参考[官方demo-合并单元格](https://alibaba-easyexcel.github.io/quickstart/write.html#%E5%90%88%E5%B9%B6%E5%8D%95%E5%85%83%E6%A0%BC)

**Comment by 418545106** [comment]
请问我怎么做复杂的单元格合并的，列入第一例前三行合并，第二列前五行合并，第二列6-16行又合并这样的

**Comment by pdkst** [comment]
> 请问我怎么做复杂的单元格合并的，列入第一例前三行合并，第二列前五行合并，第二列6-16行又合并这样的

请对照`LoopMergeStrategy`源代码自定义实现一个就好了，官方也是这么推荐的
