### ISSUE TITLE
在安卓中使用时，导入包始终编译失败

### ISSUE THREAD

**Issue by code1136** [alibaba/easyexcel#863]
com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/apache/xmlbeans/xml/stream/Location.class

**Comment by pdkst** [comment]
jar包冲突了，冲突的类来自于
```xml
    <dependency>
      <groupId>org.apache.xmlbeans</groupId>
      <artifactId>xmlbeans</artifactId>
      <version>2.6.0</version>
    </dependency>
```
这个依赖由
```xml
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>3.17</version>
        </dependency>
```
传递，检查下相关的依赖项排除掉其中一个就好了

**Comment by code1136** [comment]
好的，已经解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pdkst"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月19日(星期二) 晚上7:44
收件人:&nbsp;"alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送:&nbsp;"188120554"<188120554@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 在安卓中使用时，导入包始终编译失败 (#863)




jar包冲突了，冲突的类来自于
     <dependency&gt;       <groupId&gt;org.apache.xmlbeans</groupId&gt;       <artifactId&gt;xmlbeans</artifactId&gt;       <version&gt;2.6.0</version&gt;     </dependency&gt;
 
这个依赖由
         <dependency&gt;             <groupId&gt;org.apache.poi</groupId&gt;             <artifactId&gt;poi-ooxml</artifactId&gt;             <version&gt;3.17</version&gt;         </dependency&gt;
 
传递，检查下相关的依赖项排除掉其中一个就好了
