### ISSUE TITLE
请问如何一行一行的写入

### ISSUE THREAD

**Issue by tomuGo** [alibaba/easyexcel#864]
我想导出这样子的，所以想一行一行的写入

![image](https://user-images.githubusercontent.com/24789356/69145652-1ac5c000-0b09-11ea-803a-4eba11b6c117.png)

**Comment by pdkst** [comment]
你可以试试用table写，研究看看[官方demo-使用table去写入](https://alibaba-easyexcel.github.io/quickstart/write.html#%E4%BD%BF%E7%94%A8table%E5%8E%BB%E5%86%99%E5%85%A5)

**Comment by zhuangjiaju** [comment]
你的那个条形码 比较复杂。可以尝试楼上说的table.或者使用其他开源组件jxls
