### ISSUE TITLE
事务问题，如何保证整个文件写入或都不写入数据库

### ISSUE THREAD

**Issue by jjbb** [alibaba/easyexcel#866]
如果文件在读取过程中，某条记录校验失败抛出异常，已经写入数据库的记录如何回滚呢？

**Comment by pdkst** [comment]
抛出自定义的异常即可，这个异常会被包装成为`ExcelAnalysisException`抛出
然后给整个读取的方法开启事务，如果使用spring事务，至少设置
`    @Transactional(rollbackFor = ExcelAnalysisException.class)`
或者
    @Transactional(rollbackFor = RuntimeException.class)

**Comment by jjbb** [comment]
好的谢谢额
