### ISSUE TITLE
通过指定excel模板写入时，如果模板的格式是xls后缀，会提示：Create workbook failure

### ISSUE THREAD

**Issue by object360** [alibaba/easyexcel#867]
**触发场景描述**
通过指定excel模板写入数据
**触发Bug的代码**
```java
   `String templateFileName = "F:\\Test\\1.xlsx";
        String fileName = "F:\\Test\\根据模板写入.xls";
        // 这里 需要指定写用哪个class去读，然后写到第一个sheet，名字为模板 然后文件流会自动关闭
        EasyExcel.write(fileName, IndexData.class).needHead(Boolean.FALSE).withTemplate(templateFileName).sheet().doWrite(IndexData.data());`
```
**提示的异常或者没有达到的效果**
会提示 com.alibaba.excel.exception.ExcelGenerateException:Create workboook failure
。。。。。。。
The supplied data appears to be in the OLE2 Format....

**Comment by zhuangjiaju** [comment]
统一poi版本 3.17 或者 4.0.1

**Comment by Limbozombie** [comment]
> 统一poi版本 3.17 或者 4.0.1

那么怎么统一呢

**Comment by Limbozombie** [comment]
![4a26fc9cb354c141e208d81b570d975](https://user-images.githubusercontent.com/35883214/70906445-5d63b500-2041-11ea-9488-1bfd02619b12.png)

改用被标记为过期的方法解决了,不知道会不会出现其他问题

**Comment by Limbozombie** [comment]
![401dc0bedbef8a838aaeaa6e0e50aee](https://user-images.githubusercontent.com/35883214/70907164-255d7180-2043-11ea-80a3-73fbcd5fb314.png)
加了个参数,默认 xlsx  
尴尬.jpg
