### ISSUE TITLE
将数据写入Excel报NullPointerException

### ISSUE THREAD

**Issue by cdxubo** [alibaba/easyexcel#868]
日志开头提示如下:
c.a.e.m.property.ExcelHeadProperty ：  The table has no header set and all annotations will not be read.If you want to use annotations, please use set head class in ExcelWriterBuilder/ExcelWriterSheetBuilder/ExcelWriterTableBuilder

我的版本是2.0..5

**Comment by cdxubo** [comment]
ExcelWriter writer = new ExcelWriter(out, ExcelTypeEnum.XLSX);   writer.write(list, sheet1);   应该是执行这两行报错  writer和list、sheet1均不为空

**Comment by pdkst** [comment]
请使用`EasyExcel`来构建`ExcelWriter `

**Comment by ldfengl4j** [comment]
同问，同样出现此问题，windows电脑调试没问题，上传到linux上出现此异常

**Comment by zhuangjiaju** [comment]
就是 没有头class而已，问题不大。升级到`2.1.3`已经修复了。
