### ISSUE TITLE
关于数据校验

### ISSUE THREAD

**Issue by jjbb** [alibaba/easyexcel#875]
有没有整合数据校验？如和hibernate validator的整合，还是只能自己在listener中进行每行的校验？

**Comment by pdkst** [comment]
我不确定普通方法使用`@Valid`注解会不会生效，如果你试了，也请告诉我一下
手动调用的话，貌似入口是`javax.validation.Validation`，也要添加`hibernate-validator`的依赖

**Comment by zhuangjiaju** [comment]
在下个大版本户考虑支持。目前自己加个 `hibernate-validator`校验即可。

**Comment by jjbb** [comment]
目前自己加了hibernate-validator，正在使用

**Comment by jy05568536** [comment]
> 目前自己加了hibernate-validator，正在使用

求教，在easyexcel中怎么使用hibernate-validator

**Comment by jjbb** [comment]
> > 目前自己加了hibernate-validator，正在使用
> 
> 求教，在easyexcel中怎么使用hibernate-validator


跟普通使用的方法一样，添加依赖包，然后在解析到的方法invoke回调中进行校验

**Comment by jy05568536** [comment]
> > > 目前自己加了hibernate-validator，正在使用
> > 
> > 
> > 求教，在easyexcel中怎么使用hibernate-validator
> 
> 跟普通使用的方法一样，添加依赖包，然后在解析到的方法invoke回调中进行校验

加注解@Valid 吗，我试了不行啊
