### ISSUE TITLE
请问在导出过长字段时有方法能自动换行吗

### ISSUE THREAD

**Issue by 418545106** [alibaba/easyexcel#876]
![image](https://user-images.githubusercontent.com/29942834/69313984-fa634600-0c6d-11ea-848b-1323428941e1.png)
请问导出时候有这种过长内容的字段，请问有什么方法能设置自动换行吗

**Comment by pdkst** [comment]
这其实是自定义样式的问题，请参考[官方demo-自定义样式](https://alibaba-easyexcel.github.io/quickstart/write.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)
显示多行的话，请添加`contentWriteCellStyle.setWrapped(Boolean.TRUE);`

**Comment by 418545106** [comment]
在请问一下，如果我想要表头每列都展示不同的颜色的话这个改怎么写，demo中所有表头都是同一个颜色

**Comment by pdkst** [comment]
> 在请问一下，如果我想要表头每列都展示不同的颜色的话这个改怎么写，demo中所有表头都是同一个颜色

参考[官方demo-自定义拦截器](https://alibaba-easyexcel.github.io/quickstart/write.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8B%A6%E6%88%AA%E5%99%A8%EF%BC%88%E4%B8%8A%E9%9D%A2%E5%87%A0%E7%82%B9%E9%83%BD%E4%B8%8D%E7%AC%A6%E5%90%88%E4%BD%86%E6%98%AF%E8%A6%81%E5%AF%B9%E5%8D%95%E5%85%83%E6%A0%BC%E8%BF%9B%E8%A1%8C%E6%93%8D%E4%BD%9C%E7%9A%84%E5%8F%82%E7%85%A7%E8%BF%99%E4%B8%AA%EF%BC%89)，要注意excel有样式上限，需要复用样式

或者采用预先设置好的模板[官方demo-复杂填充](https://alibaba-easyexcel.github.io/quickstart/fill.html#%E5%A4%8D%E6%9D%82%E7%9A%84%E5%A1%AB%E5%85%85)

**Comment by zhuangjiaju** [comment]
这个这哪是只能按照楼上的解决，后续考虑出注解。应该在下个大版本。
