### ISSUE TITLE
导出excel时内容为空但想保留表头，如下图所示，应如何处理

### ISSUE THREAD

**Issue by dimdark** [alibaba/easyexcel#878]
导出excel时内容为空但想保留表头，想要的效果如下图所示：

![image](https://user-images.githubusercontent.com/25684983/69340761-2baa3900-0ca3-11ea-9be6-4cb30e84ffc8.png)
应如何处理
我采用以下代码主要内容如下，发现没有生效，导出的excel文件格式有问题
```java
ExcelWriter excelWriter = EasyExcel.write(response.getOutputStream(), ExportWhiteListInfo.class).autoCloseStream(Boolean.FALSE).build();
// ExportWhiteListInfo为vo对象
WriteSheet writeSheet = EasyExcel.writerSheet(0, "白名单").head(ExportWhiteListInfo.class).build();
excelWriter.write(null, writeSheet);
```
应该如何正确处理，查阅了文档，没发现相关的例子，请帮助一下。

**Comment by pdkst** [comment]
`excelWriter.write(null, writeSheet);`
替换成这个
`excelWriter.write(Collections.emptyList(), writeSheet);`
试试

**Comment by dimdark** [comment]
可以了，感谢
我自己debug了也发现了，如果是data不是null会执行 `initSheet`方法，这个方法内也调用了`initHead`来初始化表头，总之，谢谢。
