### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by happynewdate** [alibaba/easyexcel#879]
**建议描述**
大佬，导出excel的有没有动态表头和列的，而且表头还是复杂表头的呢？

**Comment by pdkst** [comment]
表头也是数据，如果不行的话，把表头作为数据输出也是可行的，不过实现难度比较高，也比较复杂
如果过于自由的话，直接使用POI实现比较好，
或者先在内存里用POI写个表头，再通过easyExcel的`withTemplate(stream)`引进来，写剩下的数据这种实现方式，
哪种比较方便采用哪种

**Comment by happynewdate** [comment]
谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pdkst"<notifications@github.com&gt;; 
发送时间: 2019年11月22日(星期五) 上午10:41
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com&gt;; 
抄送: "十&amp;#xE23;緬&amp;#xE23;埋&amp;#xE23;伏"<986740084@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/easyexcel] 求助 (#879)




表头也是数据，如果不行的话，把表头作为数据输出也是可行的，不过实现难度比较高，也比较复杂
 如果过于自由的话，直接使用POI实现比较好，
 或者先在内存里用POI写个表头，再通过easyExcel的withTemplate(stream)引进来，写剩下的数据这种实现方式，
 哪种比较方便采用哪种

**Comment by happynewdate** [comment]
我回头试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "pdkst"<notifications@github.com&gt;; 
发送时间: 2019年11月22日(星期五) 上午10:41
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com&gt;; 
抄送: "十&amp;#xE23;緬&amp;#xE23;埋&amp;#xE23;伏"<986740084@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/easyexcel] 求助 (#879)




表头也是数据，如果不行的话，把表头作为数据输出也是可行的，不过实现难度比较高，也比较复杂
 如果过于自由的话，直接使用POI实现比较好，
 或者先在内存里用POI写个表头，再通过easyExcel的withTemplate(stream)引进来，写剩下的数据这种实现方式，
 哪种比较方便采用哪种
