### ISSUE TITLE
EhCache依赖是必须的吗？

### ISSUE THREAD

**Issue by liunancun** [alibaba/easyexcel#883]
我们项目原来依赖了ehcache的2.0版本，引入easyexcel后里面有个ehcache的3.0版本，导致版本冲突了

**Comment by pdkst** [comment]
excel的`EhCache`是主动依赖的，主要用来解决07版excel超大文件的读取
可以尝试排除掉一个看看，这类依赖api一般变动很小，能够兼容

**Comment by zhuangjiaju** [comment]
写的没必要，读的话20M内也没必要。
