### ISSUE TITLE
在导入时，如何处理对象嵌套问题

### ISSUE THREAD

**Issue by FisterV** [alibaba/easyexcel#889]
类似与订单与订单详情一对多关系的导入，我使用@ExcelProperty指定对象中嵌套的list对象，会报类型转换异常 convert STRING to java.lang.list
有没有类似easypoi这种的处理方式
` @Data
		@ExcelTarget("totalBean")
		public class TotalBean {
			@ExcelEntity(id="order")
			private OrderBean orderBean;
			@ExcelCollection(name = "订单明细",orderNum="5")
			private List<OrderDetailBean> detailBeans;
		}
`

**Comment by zhuangjiaju** [comment]
目前不支持嵌套对象。要实现可以参照定义转换器的demo.但是也不能实现一对多，只能一对一。
