### ISSUE TITLE
读取excel是否可以返回一个错误对象,显示给前端

### ISSUE THREAD

**Issue by haohub** [alibaba/easyexcel#891]
![image](https://user-images.githubusercontent.com/24990182/69518454-9654c080-0f92-11ea-9514-3d4dc5e80b1e.png)

**Comment by pdkst** [comment]
listener发生异常会抛出`ExcelAnalysisException`，在调用类中try-catch，或者在spring中的`ControllerAdvice`、`ExceptionHandler`中捕获并处理
