### ISSUE TITLE
导出的时候excel怎么设置下拉菜单

### ISSUE THREAD

**Issue by dongloveying0706** [alibaba/easyexcel#892]
下载Excel模板的时候指定某一列数据为下拉菜单

**Comment by dongloveying0706** [comment]
![image](https://user-images.githubusercontent.com/12047017/69527281-efc6ea80-0fa6-11ea-9b04-da3585f539b3.png)

**Comment by pdkst** [comment]
数据约束请参考[官方demo-自定义拦截器](https://alibaba-easyexcel.github.io/quickstart/write.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8B%A6%E6%88%AA%E5%99%A8%EF%BC%88%E4%B8%8A%E9%9D%A2%E5%87%A0%E7%82%B9%E9%83%BD%E4%B8%8D%E7%AC%A6%E5%90%88%E4%BD%86%E6%98%AF%E8%A6%81%E5%AF%B9%E5%8D%95%E5%85%83%E6%A0%BC%E8%BF%9B%E8%A1%8C%E6%93%8D%E4%BD%9C%E7%9A%84%E5%8F%82%E7%85%A7%E8%BF%99%E4%B8%AA%EF%BC%89)

**Comment by dongloveying0706** [comment]
好的，谢谢啦

**Comment by dongloveying0706** [comment]
完美解决
