### ISSUE TITLE
excel 如何导出货币格式的数字，自定义的converter未生效。

### ISSUE THREAD

**Issue by 908216809** [alibaba/easyexcel#893]
@Override
    public CellData convertToExcelData(BigDecimal value, ExcelContentProperty contentProperty, GlobalConfiguration globalConfiguration){
        CellData cd = new CellData(value);
        if(null != value)
            cd.setData(StrUtils.getMoneyRoundTwoDecimalStr(value.doubleValue()));
        return cd;
    }

**Comment by dongjun613** [comment]
该字段上有加@ExcelProperty(converter="XXXConverter.class")吗？

**Comment by 908216809** [comment]
我们采用的是动态列，没有模板对象，因为每次导出的数据列和顺序也是不固定的。

**Comment by 908216809** [comment]
问题已解决，实现CellWriteHandler接口并注册handler可以解决问题，但实现方式比较丑陋，传入的数据无法指定类型，目前通过空格识别金额字段，并将格式化好的数据反格式化成double。
@Override
    public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder,
                                 List<CellData> cellDataList, Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {
        if (!isHead && !cellDataList.isEmpty()) {
            CellData cellData = cellDataList.get(0);
            //金额数据设置
            if(null != cellData.getStringValue() && cellData.getStringValue().startsWith(" ")) {
                String value = cellData.getStringValue().trim();
                value = value.replace(",", "");
                if(StrUtils.isDoubleNumeric(value)){
                    CellStyle mcs = getMoneyCellStyle(cell);
                    cell.setCellStyle(mcs);
                    cell.setCellType(CellType.NUMERIC);
                    cell.setCellValue(Double.parseDouble(value));
                }
            }
        }
    }

    //金额转换
    private CellStyle getMoneyCellStyle(Cell cell){
        if(null == moneyCellStyle) {
            moneyCellStyle = cell.getSheet().getWorkbook().createCellStyle();
            DataFormat df = cell.getSheet().getWorkbook().createDataFormat(); // 此处设置数据格式
            moneyCellStyle.setDataFormat(df.getFormat("#,##0.00"));//数据格式只显示整数
            moneyCellStyle.setBorderTop(BorderStyle.THIN);
            moneyCellStyle.setBorderLeft(BorderStyle.THIN);
            moneyCellStyle.setBorderRight(BorderStyle.THIN);
            moneyCellStyle.setBorderBottom(BorderStyle.THIN);
        }
        return moneyCellStyle;
    }

**Comment by 908216809** [comment]
问题已解决，实现CellWriteHandler接口并注册handler可以解决问题，但实现方式比较丑陋，传入的数据无法指定类型，目前通过空格识别金额字段，并将格式化好的数据反格式化成double。

@override
public void afterCellDispose(WriteSheetHolder writeSheetHolder, WriteTableHolder writeTableHolder,
List cellDataList, Cell cell, Head head, Integer relativeRowIndex, Boolean isHead) {
if (!isHead && !cellDataList.isEmpty()) {
CellData cellData = cellDataList.get(0);
//金额数据设置
if(null != cellData.getStringValue() && cellData.getStringValue().startsWith("&nbsp;")) {
String value = cellData.getStringValue().trim();
value = value.replace("&nbsp;", "");
value = value.replace(",", "");
if(StrUtils.isDoubleNumeric(value)){
CellStyle mcs = getMoneyCellStyle(cell);
cell.setCellStyle(mcs);
cell.setCellType(CellType.NUMERIC);
cell.setCellValue(Double.parseDouble(value));
}
}
}
}

//金额转换
private CellStyle getMoneyCellStyle(Cell cell){
    if(null == moneyCellStyle) {
        moneyCellStyle = cell.getSheet().getWorkbook().createCellStyle();
        DataFormat df = cell.getSheet().getWorkbook().createDataFormat(); // 此处设置数据格式
        moneyCellStyle.setDataFormat(df.getFormat("#,##0.00"));//数据格式只显示整数
        moneyCellStyle.setBorderTop(BorderStyle.THIN);
        moneyCellStyle.setBorderLeft(BorderStyle.THIN);
        moneyCellStyle.setBorderRight(BorderStyle.THIN);
        moneyCellStyle.setBorderBottom(BorderStyle.THIN);
    }
    return moneyCellStyle;
}
