### ISSUE TITLE
在导入时不定义实体对象能否读取到表头数据？

### ISSUE THREAD

**Issue by hlfatter** [alibaba/easyexcel#895]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by pdkst** [comment]
默认应该跳过了一行表头

`EasyExcel.read(fileName, new MapDataListener()).sheet().headRowNumber(0).doRead();`

**Comment by hlfatter** [comment]
![image](https://user-images.githubusercontent.com/43473741/69704923-73abde80-112f-11ea-9792-ecc56aa5a33d.png)
我这样写读取的是Excel表头以及所有的内容数据


![image](https://user-images.githubusercontent.com/43473741/69705221-0f3d4f00-1130-11ea-8982-7cd4ad97975b.png)
这样写呢 拿到的没有表头（excel内容）的数据  这是什么原因呢

**Comment by pdkst** [comment]
> ![image](https://user-images.githubusercontent.com/43473741/69704923-73abde80-112f-11ea-9792-ecc56aa5a33d.png)
> 我这样写读取的是Excel表头以及所有的内容数据
> 
> ![image](https://user-images.githubusercontent.com/43473741/69705221-0f3d4f00-1130-11ea-8982-7cd4ad97975b.png)
> 这样写呢 拿到的没有表头（excel内容）的数据 这是什么原因呢

`headRowNumber()`会标注表头占的行数，应该是默认有一行表头，如果设置为0则表示没有表头（表头占行数为0）

**Comment by hlfatter** [comment]
多谢讲解！
