### ISSUE TITLE
在写入的时候，能否以追加的方式，不覆盖原有的数据？

### ISSUE THREAD

**Issue by cliff-ck** [alibaba/easyexcel#896]
对已有数据的excel进行写操作，能不能用append的方式，直接把list创建的行附加到已有excel里面？

**Comment by pdkst** [comment]
保留原先的数据有两个方式，一个是时[官方demo-根据模板写入](https://alibaba-easyexcel.github.io/quickstart/write.html#%E6%A0%B9%E6%8D%AE%E6%A8%A1%E6%9D%BF%E5%86%99%E5%85%A5)

另外一个是填充的方式实现[官方demo-填充](https://alibaba-easyexcel.github.io/quickstart/fill.html)
看哪种适合业务逻辑选用
