### ISSUE TITLE
在实现web下载的时候 如何自定义返回数据

### ISSUE THREAD

**Issue by HundredsOfProfessors** [alibaba/easyexcel#897]
比如在下载生成excel的时候 同时返回一个json数据结构体
{
  code:"".
 message:""
}

**Comment by pdkst** [comment]
你可以考虑返回一个文件路径，然后前端拿着这个路径来获取流
Duplicate of #891

**Comment by zhuangjiaju** [comment]
这个你需要把流 序列化，然后再返回。或者参照楼上的，返回路径。

**Comment by HundredsOfProfessors** [comment]
好的 谢谢
