### ISSUE TITLE
excel有两个sheet，我用java反射可以获取第一个sheet的内容，但是无法获取第2个sheet的内容

### ISSUE THREAD

**Issue by tkggft** [alibaba/easyexcel#898]
**异常代码**
 /**
     * 如果没有模板对应的sheet则调用这个
     */
    public static SXSSFSheet getSxssSheet(ExcelWriter writer, int sheetIndex) {
        try {
            Field field = writer.getClass().getDeclaredField("excelBuilder");
            field.setAccessible(true);
            ExcelBuilderImpl impl = (ExcelBuilderImpl) field.get(writer);
            Field field1 = impl.getClass().getDeclaredField("context");
            field1.setAccessible(true);
            WriteContext context = (WriteContext) field1.get(impl);
            Workbook workbook = context.getWorkbook();
            SXSSFSheet sheet1 = (SXSSFSheet) workbook.getSheetAt(sheetIndex);
            return sheet1;
        } catch (Exception e) {
            throw new BizException("内部错误");
        }
    }

/**
     * 如果是拿模板对应的sheet调用这个
     */
    public static XSSFSheet getXssfSheet(ExcelWriter writer, int sheetIndex) {

        try {
            SXSSFSheet sheet1 = getSxssSheet(writer, sheetIndex);
            Field sh = sheet1.getClass().getDeclaredField("_sh");
            sh.setAccessible(true);
            XSSFSheet xssfSheet = (XSSFSheet) sh.get(sheet1);
            return xssfSheet;
        } catch (Exception e) {
            throw new BizException("内部错误");
        }
    }

  * @param writer
     * @param planName
     * @param sheetIndex
     * @param rownum
     */
    public static void setPremisesSheetStyle(ExcelWriter writer, String planName, int sheetIndex, int rownum) {
        SXSSFSheet sxssSheet = EasyExcelUtil.getSxssSheet(writer, sheetIndex);
        SXSSFRow row = sxssSheet.getRow(rownum);
        if (null != row) {
            for (int i = 0; i < row.getLastCellNum(); i++) {
                SXSSFCell oldCell = row.getCell(i);
                SXSSFCell newCell = row.createCell(i);
                newCell.setCellValue(oldCell.getStringCellValue());
                if (StringUtils.isNotBlank(planName)) {
                    if (i == 1) {
                        newCell.setCellValue(planName);
                    }
                }
                //设置样式
                SXSSFWorkbook workbook = sxssSheet.getWorkbook();
                CellStyle cellStyle = workbook.createCellStyle();
                //自动换行
                cellStyle.setWrapText(false);
                // 水平对齐方式
                cellStyle.setAlignment(HorizontalAlignment.CENTER);
                // 垂直对齐方式
                cellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
                Font font = workbook.createFont();
                font.setBold(true);
                // 字体
                font.setFontName(ExcelConfig.FONT_FAMILY);
                //字体大小
                font.setFontHeightInPoints((short) 12);
                cellStyle.setFont(font);
                newCell.setCellStyle(cellStyle);
            }
        }

    }
```
**异常提示**
 SXSSFRow row = sxssSheet.getRow(rownum);
这个row是空，获取不到第2个sheet的第一行表头内容，我想给表头设置样式
**建议描述**

**Comment by pdkst** [comment]
我觉得用反射去读，不如直接用POI去读更快一点……
设置样式请参照[官方demo-自定义样式](https://alibaba-easyexcel.github.io/quickstart/write.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

**Comment by tkggft** [comment]
我现在自定义实现了WriteHandler接口来设置的样式，代码里面也是用到了POI实现，修改样式可以用反射、也可以用POI、还可以用官方最新版本的样式，几种都可以，因为只是对表头设置样式，性能可以忽略不计，还是很快的，代码如下：
public class PointWriterHandler implements WriteHandler {
    @Override
    public void sheet(int i, Sheet sheet) {

    }

    @Override
    public void row(int i, Row row) {

    }

    @Override
    public void cell(int i, Cell cell) {
        Sheet sheet = cell.getSheet();
        Workbook workbook = sheet.getWorkbook();
        //获取点位sheet
        Sheet sheet1 = workbook.getSheet("点位");
        if (sheet1 == null) {
            sheet1 = workbook.getSheet("点位(未去重)");
        }
        if (sheet1 != null) {
            //对第一行设置样式
            if (cell.getRowIndex() == 0) {
                cell.setCellStyle(getCellStyle(cell));
            }
        }
    }

    private CellStyle getCellStyle(Cell cell) {
        //设置样式
        Workbook workbook = cell.getSheet().getWorkbook();
        CellStyle cellStyle = workbook.createCellStyle();
        //自动换行
        cellStyle.setWrapText(false);
        // 水平对齐方式
        cellStyle.setAlignment(HorizontalAlignment.CENTER);
        // 垂直对齐方式
        cellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
        Font font = workbook.createFont();
        font.setBold(true);
        // 字体
        font.setFontName(ExcelConfig.FONT_FAMILY);
        //字体大小
        font.setFontHeightInPoints((short) 12);
        cellStyle.setFont(font);
        return cellStyle;
    }
