### ISSUE TITLE
注解加了日期 ,导出来格式不行

### ISSUE THREAD

**Issue by Caiguang** [alibaba/easyexcel#9]
@ExcelProperty(value = "处理时间", index = 13,format = "yyyy-MM-dd HH:mm:ss")

**Comment by Caiguang** [comment]
Wed Mar 07   15:58:30 CST 2018  导出来格式还是这样
--

**Comment by Caiguang** [comment]
数字都是文本的格式写入的，导致会计在拉一列的时候，无法计算总和，平均数

**Comment by CaixiLi** [comment]
数字都是文本的格式写入的，导致会计在拉一列的时候，无法计算总和，平均数 

这个没有办法转成数值格式的吗？

**Comment by jipengfei-jpf** [comment]
升级已处理
