### ISSUE TITLE
设置表头样式demo

### ISSUE THREAD

**Issue by tkggft** [alibaba/easyexcel#900]
public class PointWriterHandler implements WriteHandler {
    @Override
    public void sheet(int i, Sheet sheet) {

    }

    @Override
    public void row(int i, Row row) {

    }

    @Override
    public void cell(int i, Cell cell) {
        Sheet sheet = cell.getSheet();
        Workbook workbook = sheet.getWorkbook();
        //获取点位sheet
        Sheet sheet1 = workbook.getSheet("点位");
        if (sheet1 != null) {
            //对第一行设置样式
            if (cell.getRowIndex() == 0) {
                cell.setCellStyle(getCellStyle(cell));
            }
        }
    }

    private CellStyle getCellStyle(Cell cell) {
        //设置样式
        Workbook workbook = cell.getSheet().getWorkbook();
        CellStyle cellStyle = workbook.createCellStyle();
        //自动换行
        cellStyle.setWrapText(false);
        // 水平对齐方式
        cellStyle.setAlignment(HorizontalAlignment.CENTER);
        // 垂直对齐方式
        cellStyle.setVerticalAlignment(VerticalAlignment.CENTER);
        Font font = workbook.createFont();
        font.setBold(true);
        // 字体
        font.setFontName(ExcelConfig.FONT_FAMILY);
        //字体大小
        font.setFontHeightInPoints((short) 12);
        cellStyle.setFont(font);
        return cellStyle;
    }
}

调用：
 public static byte[] writePublishPointsWithTemplate(List<PremisesModel> premisesModels, List<PremisesPointModel> pointModelList, InputStream inputStream, String planName) {
        byte[] bytes = null;
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            ExcelWriter writer = EasyExcelFactory.getWriterWithTempAndHandler(inputStream, out, ExcelTypeEnum.XLSX, true, new PointWriterHandler());

            Sheet sheet1 = new Sheet(1, 0, PremisesModel.class, "项目", null);
            sheet1.setStartRow(2);
            writer.write(premisesModels, sheet1);

            Sheet sheet2 = new Sheet(2, 0, PremisesPointModel.class, "点位", null);
            writer.write(pointModelList, sheet2);

            writer.finish();
            bytes = out.toByteArray();
        } catch (Exception e) {
            logger.error("上刊点位导出异常", e);
        }
        return bytes;
    }

**Comment by pdkst** [comment]
样式设置请参照[官方demo-自定义样式](https://alibaba-easyexcel.github.io/quickstart/write.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

**Comment by tkggft** [comment]
明白了，我用的版本不是最新版本，还是用的1.1.2-beta5版本，这个版本我上面的代码也可以实现样式设置；到时候用最新版本后就按照管方demo-自定义样式来实现；
