### ISSUE TITLE
现在我有个客户想要.csv格式。请问我导出csv格式文件编码为ansi ,打开编码有问题。请问我要如何设置写入时编码格式为utf-8

### ISSUE THREAD

**Issue by fullSecKil** [alibaba/easyexcel#902]
EasyExcel.write(fileContent.get("file").toString(), fileContent.get("dealClass").getClass()).registerWriteHandler(getCellStyleStrategy()).sheet(fileContent.get("sheetName").toString()).doWrite(content);
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
目前不支持csv，后续会考虑支持
