### ISSUE TITLE
名称管理器

### ISSUE THREAD

**Issue by superxbh** [alibaba/easyexcel#907]
**建议描述**
名称管理器如何写入

**Comment by superxbh** [comment]
名称管理器如何写入

**Comment by pdkst** [comment]
目前的话，可以采用 [官方demo-自定义拦截器](https://alibaba-easyexcel.github.io/quickstart/write.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8B%A6%E6%88%AA%E5%99%A8%EF%BC%88%E4%B8%8A%E9%9D%A2%E5%87%A0%E7%82%B9%E9%83%BD%E4%B8%8D%E7%AC%A6%E5%90%88%E4%BD%86%E6%98%AF%E8%A6%81%E5%AF%B9%E5%8D%95%E5%85%83%E6%A0%BC%E8%BF%9B%E8%A1%8C%E6%93%8D%E4%BD%9C%E7%9A%84%E5%8F%82%E7%85%A7%E8%BF%99%E4%B8%AA%EF%BC%89)采用POI方式写入，或者[官方demo-填充](https://alibaba-easyexcel.github.io/quickstart/fill.html)先写好名称管理器再填写数据
