### ISSUE TITLE
easyexcle（或者poi） 导出数据有没有多线程的模式？？？

### ISSUE THREAD

**Issue by 17173YeYu** [alibaba/easyexcel#912]
easyexcle（或者poi） 导出数据有没有多线程的模式？？？
自己创建多个线程，将数据拆分，导出多个临时的excle，再临时的excle合并，这种模式是否真的能提升性能？存在什么问题。 可以帮忙解答一下么。

**Comment by pdkst** [comment]
没有，不能，多次读写可能会造成性能下降……，
导出这种问题，性能主要集中在数据库查询数据上，
导出其实并不会占用太多额外的性能……，
如果真的需要不同读取方案，我觉得将需求拆分成多个文件可能更适合

**Comment by 17173YeYu** [comment]
好的，谢谢哈

**Comment by zhuangjiaju** [comment]
目前 easyexcel肯定不支持。poi 单个sheet肯定也不支持，多个不确定以 你也可以研究下。但是一般 单线程够了，不会慢

**Comment by 17173YeYu** [comment]
好的，谢谢



---原始邮件---
发件人: "Jiaju Zhuang"<notifications@github.com&gt;
发送时间: 2019年11月29日(星期五) 晚上7:58
收件人: "alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送: "17173YeYu"<951520363@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [alibaba/easyexcel] easyexcle（或者poi） 导出数据有没有多线程的模式？？？ (#912)



目前 easyexcel肯定不支持。poi 单个sheet肯定也不支持，多个不确定以 你也可以研究下。但是一般 单线程够了，不会慢
