### ISSUE TITLE
读取Excel时会有历史缓存是什么原因？

### ISSUE THREAD

**Issue by bihumanbu** [alibaba/easyexcel#915]
导入修改后的Excel时，每次读取的时候上一条记录不会被清掉
![image](https://user-images.githubusercontent.com/43693693/69846648-a8df3a80-12af-11ea-96d5-fdf9901ed885.png)

**Comment by zhuangjiaju** [comment]
建议 把excel  移动到 固定的d盘 之类的，别放到resource ，问题应该和easyexcel没关系。
