### ISSUE TITLE
怎么获取XSSFWorkbook

### ISSUE THREAD

**Issue by zhaop33** [alibaba/easyexcel#916]
EasyExcel有提供接口获取XSSFWorkbook对象吗，找了半天找不见啊

**Comment by pdkst** [comment]
普通读取写入不需要这个对象，自定义的话可以通过各种cell、handler获取到sheetHandler进而获取到这个对象

**Comment by zhaop33** [comment]
可以详细点吗，

**Comment by pdkst** [comment]
参考官方代码就可以了，各种handler大都能拿到workbook，[官方教程](https://alibaba-easyexcel.github.io/quickstart/write.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8B%A6%E6%88%AA%E5%99%A8%EF%BC%88%E4%B8%8A%E9%9D%A2%E5%87%A0%E7%82%B9%E9%83%BD%E4%B8%8D%E7%AC%A6%E5%90%88%E4%BD%86%E6%98%AF%E8%A6%81%E5%AF%B9%E5%8D%95%E5%85%83%E6%A0%BC%E8%BF%9B%E8%A1%8C%E6%93%8D%E4%BD%9C%E7%9A%84%E5%8F%82%E7%85%A7%E8%BF%99%E4%B8%AA%EF%BC%89)
```
public class CustomSheetWriteHandler implements SheetWriteHandler {

    private static final Logger LOGGER = LoggerFactory.getLogger(CustomSheetWriteHandler.class);

    @Override
    public void beforeSheetCreate(WriteWorkbookHolder writeWorkbookHolder, WriteSheetHolder writeSheetHolder) {

    }

    @Override
    public void afterSheetCreate(WriteWorkbookHolder writeWorkbookHolder, WriteSheetHolder writeSheetHolder) {
        LOGGER.info("第{}个Sheet写入成功。", writeSheetHolder.getSheetNo());
        Workbook workbook = writeWorkbookHolder.getWorkbook();
        if (workbook instanceof XSSFWorkbook) {
            //TODO 
        }
    }
}
```

**Comment by zhaop33** [comment]
这里是写的时候获取的，如果我要读的时候获取呢？我看了handler都是write才有的

**Comment by pdkst** [comment]
> 这里是写的时候获取的，如果我要读的时候获取呢？我看了handler都是write才有的

读取应该是poi的sax解析的，好像没有创建workbook，如果需要workbook我觉得可能需要换用poi读取

**Comment by zhuangjiaju** [comment]
读的时候 没这个东西 以为没有调用poI的东西，自己写的。

**Comment by zhaop33** [comment]
噢噢，谢谢
