### ISSUE TITLE
实体对象导入导出时，如果set方法返回值不为void，则无法赋值

### ISSUE THREAD

**Issue by zhaop33** [alibaba/easyexcel#917]
**触发场景描述**
实体对象导入导出时，如果set方法返回值不为void，则无法赋值
**触发Bug的代码**
```java
   BeanMap.create(resultModel).putAll(map);
```
**提示的异常或者没有达到的效果**
跟踪是cglib的putAll方法没有将值放进去

**Comment by pdkst** [comment]
遵循java规范，使用正常的getter、setter比较好，如果是lombok，使用builder替代chain

**Comment by zhuangjiaju** [comment]
这个目前没法解决，后续会考虑。需要重写cglib 比较麻烦。

**Comment by mm-zx** [comment]
现在很多数据库工具在逆向后 会加上 Lombok 的@Accessors(chain = true)，建议在文档中告知用户先去掉注释
