### ISSUE TITLE
自定义报表 head不固定 应该咋整啊 new sheet()的入参中有一个入参 BaseRowModel 这个咋整

### ISSUE THREAD

**Issue by RobertDav** [alibaba/easyexcel#919]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by pdkst** [comment]
参考[官方demo-动态生成](https://alibaba-easyexcel.github.io/quickstart/write.html#%E5%8A%A8%E6%80%81%E5%A4%B4%EF%BC%8C%E5%AE%9E%E6%97%B6%E7%94%9F%E6%88%90%E5%A4%B4%E5%86%99%E5%85%A5)

**Comment by zhuangjiaju** [comment]
参照楼上就行
