### ISSUE TITLE
可不可以在文件读取部分插入数据库环节失败就停止整个读写

### ISSUE THREAD

**Issue by zhugekuangyi** [alibaba/easyexcel#921]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by pdkst** [comment]
不要拦截listener里的异常就可以了，invoke方法抛出的异常会被包装成`ExcelAnalysisException`让外部异常捕获捕获到就可以了，捕获到就可以回滚事务，如果想要即使出错也要继续执行则需要在invoke中手动捕获异常
`public class DemoDataListener extends AnalysisEventListener<DemoData> {`

**Comment by zhuangjiaju** [comment]
监听器 有个`hasNext` 返回false就不会读了。
