### ISSUE TITLE
使用填充excel功能填充数据后公式无法生效

### ISSUE THREAD

**Issue by weibn** [alibaba/easyexcel#922]
我的模板中有些单元格的数据是通过excel公式计算的，但使用excel填充功能后公式没有正确生效，需要双击该填充内容后才生效。我查询到poi似乎是通过
`workBook.setForceFormulaRecalculation(true);`
刷新公式使其生效，不知道现版本的easyExcel是否有类似api？

**Comment by zhuangjiaju** [comment]
这个目前支持 设置 inmemoy=true  然后再通过拦截器设置这个。但是这个有问题就是操作都在内存了，要注意OOM。POI也一样 必须 在内存 这个才有效。

**Comment by weibn** [comment]
> 这个目前支持 设置 inmemoy=true 然后再通过拦截器设置这个。但是这个有问题就是操作都在内存了，要注意OOM。POI也一样 必须 在内存 这个才有效。
这个inmemory在哪里设置，我找遍了文档没找到-  - 。。还有拦截器好像只看到写excel的时候有，并且操作的也不是workBook 。 原谅我java入门没多久，不太懂

**Comment by weibn** [comment]
WriteWorkbookHolder 
如果是这个的话，inmemory可以设置，但似乎在里面没找到类似刷新公式的方法

**Comment by weibn** [comment]
> 这个目前支持 设置 inmemoy=true 然后再通过拦截器设置这个。但是这个有问题就是操作都在内存了，要注意OOM。POI也一样 必须 在内存 这个才有效。


找到了非常感谢！
