### ISSUE TITLE
xls文件导入时，字符型数字总是变成数值型，导致数据异常

### ISSUE THREAD

**Issue by xudan180** [alibaba/easyexcel#928]
**触发场景描述**

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**

**Comment by zhuangjiaju** [comment]
贴全异常。

**Comment by xudan180** [comment]
比如我导入用户信息
![image](https://user-images.githubusercontent.com/33273972/70014001-6f127a80-15b4-11ea-8a63-25f07b4d1961.png)
实际后台接收到的
![image](https://user-images.githubusercontent.com/33273972/70014249-2dce9a80-15b5-11ea-9c55-64b14846b41e.png)

**Comment by likanglong555** [comment]
我也遇到类似的问题。没有异常，就是后台接受的数据对不上

**Comment by ZheBigFish** [comment]
+1，xlsx格式的就不会

**Comment by zhuangjiaju** [comment]
这个问题已经在最新版本解决。参照：https://www.yuque.com/easyexcel/faq/evmtmu
