### ISSUE TITLE
CellDataTypeEnum咨询

### ISSUE THREAD

**Issue by feifei498536** [alibaba/easyexcel#931]
CellDataTypeEnum
    STRING,
    DIRECT_STRING,
    NUMBER,
    BOOLEAN,
    EMPTY,
    ERROR,
    IMAGE;
上述类型代表单元格的哪个类型呢.
如果一个属性字段加了自定义转换器,该属性对应单元格是空,为何不走该转换器....

**Comment by zhuangjiaju** [comment]
空的话 目前直接会跳过。具体意思看注释。
