### ISSUE TITLE
com.alibaba.excel.exception.ExcelAnalysisException: java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected

### ISSUE THREAD

**Issue by lin-jim** [alibaba/easyexcel#932]
easyexcel最新版，poi4.1.0，读取excel报错：com.alibaba.excel.exception.ExcelAnalysisException: java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected

**Comment by lin-jim** [comment]
poi版本问题，不过之前是可以的，poi换成3.17

**Comment by yinjinxiong** [comment]
的确换成3.17就可以了，2.2.6的easyExcel 依赖的是3.17
