### ISSUE TITLE
使用泛型去接受数据，一直接收不到

### ISSUE THREAD

**Issue by HusenHuang** [alibaba/easyexcel#936]
import com.alibaba.excel.context.AnalysisContext;
import com.alibaba.excel.event.AnalysisEventListener;

import com.alibaba.fastjson.JSON;
import com.candao.log4dc.logger.Logger;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * @author Ray lei
 * @date 2019/11/25 22:39
 * @Description 监听器
 */
public class ExcelDataListener<T> extends AnalysisEventListener<T> {

    private List<T> result = new ArrayList<>();

    private Map<Integer, String> header = new HashMap<>();

    @Override
    public void invoke(T t, AnalysisContext analysisContext) {
        Logger.info("解析到一条数据:{}", t);
        result.add(t);
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext analysisContext) {
        Logger.info("解析一共解析{}条数据",result.size());
        Logger.info("所有数据解析完成！");
    }

    public List<T> getResult() {
        return result;
    }

    public Map<Integer, String> getHeader() {
        return header;
    }

    /**
     * 这里会一行行的返回头
     * @param headMap
     * @param context
     */
    @Override
    public void invokeHeadMap(Map<Integer, String> headMap, AnalysisContext context) {
        this.header = headMap;
        Logger.info("解析到一条头数据:{}", JSON.toJSONString(headMap));
    }

    @Override
    public void onException(Exception exception, AnalysisContext context) throws Exception {
        Logger.error("解析数据异常!!!", exception);
        super.onException(exception, context);
    }
}

**Comment by pdkst** [comment]
`public class ExcelDataListener extends AnalysisEventListener<这里指定接收的数据泛型> {`

**Comment by HusenHuang** [comment]
public class ExcelDataListener<T> extends AnalysisEventListener<T> {
这样也不行的

**Comment by HusenHuang** [comment]
里面是有泛型的 但是贴代码到github被忽略了

**Comment by HusenHuang** [comment]
![image](https://user-images.githubusercontent.com/26651752/70110362-b0288e80-1689-11ea-9da7-773a270563a1.png)
![image](https://user-images.githubusercontent.com/26651752/70110373-b7e83300-1689-11ea-950a-d6eadc60a372.png)
这样都读取不到

**Comment by HusenHuang** [comment]
![image](https://user-images.githubusercontent.com/26651752/70110448-f54cc080-1689-11ea-8b0e-e6f4f507d5aa.png)

**Comment by pdkst** [comment]
`AnalysisEventListener`只是指定接收数据的类型，也就是invoke方法的类型，你还需要指定Excel的实体类型

`EasyExcel.read(fileName, DataDemo.class, new DemoDataListener<DataDemo>()).sheet().doRead();`

这边的实体类不可以省

**Comment by HusenHuang** [comment]
我这边调试了一下
![image](https://user-images.githubusercontent.com/26651752/70116878-efada580-169e-11ea-9c88-1658e10e1bcd.png)
这里赋值bujin不进去

**Comment by HusenHuang** [comment]
![image](https://user-images.githubusercontent.com/26651752/70116918-0a801a00-169f-11ea-9396-713b706715c6.png)
这里时泛型传进去的，没办法指定

**Comment by HusenHuang** [comment]
![image](https://user-images.githubusercontent.com/26651752/70117027-50d57900-169f-11ea-9424-c406fd780414.png)
这里已经能拿到数据了。

**Comment by HusenHuang** [comment]
![image](https://user-images.githubusercontent.com/26651752/70117230-de18cd80-169f-11ea-8931-b43c7125c8e0.png)
找到原因了，实体类贴了@Accessors(chain = true)这个导致的

**Comment by pdkst** [comment]
> ![image](https://user-images.githubusercontent.com/26651752/70117230-de18cd80-169f-11ea-8931-b43c7125c8e0.png)
> 找到原因了，实体类贴了@accessors(chain = true)这个导致的

好吧，easyExcel对模型的映射依赖getter setter，所以如果getter setter不正常就没办法的

**Comment by HusenHuang** [comment]
谢谢你。

**Comment by ccubec** [comment]
你代码怎么写的  能分享一下么 传到github看一下?
