### ISSUE TITLE
导入的数据日期格式化问题

### ISSUE THREAD

**Issue by JunHong1995** [alibaba/easyexcel#94]
导入的BaseRowModel中，添加了注解如下所示：

```java
    @ExcelProperty(value = "制造日期", format="yyyy-MM-dd HH:mm:ss" ,index = 16)
    private String makeDate;
```

在导入的excel数据中，makeDate的值为：“2017/12/12”。

导入以后，并没有进行格式化，还是“201712/12”，希望得到类似：**2017-12-12 00:00:00**这样的结果，请问下作者，如何才能做到？

**Comment by haopangang** [comment]
我试过，yyyy-MM-dd可以格式化的。但是只要一点击又变成了 yyyy/MM/dd。这应该是Excel的问题。
