### ISSUE TITLE
能不能出一个完整的API手册

### ISSUE THREAD

**Issue by hyllovedf** [alibaba/easyexcel#942]
**建议描述**
有没有一个完整的API手册啊，比如设置单元格样式时，都不清楚每个方法是干嘛的

**Comment by zhuangjiaju** [comment]
这个源码有。我也是课后写的，目前比较忙，后续有时间了考虑加入。

**Comment by hyllovedf** [comment]
辛苦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jiaju Zhuang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月12日(星期四) 晚上6:27
收件人:&nbsp;"alibaba/easyexcel"<easyexcel@noreply.github.com&gt;;
抄送:&nbsp;"来自1993。"<1353996141@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/easyexcel] 能不能出一个完整的API手册 (#942)




这个源码有。我也是课后写的，目前比较忙，后续有时间了考虑加入。
