### ISSUE TITLE
读取excel数字类型的字段精度损失 

### ISSUE THREAD

**Issue by tkqengineer** [alibaba/easyexcel#943]
**触发场景描述**
读取带有数字类型的excel
**触发Bug的代码**
![image](https://user-images.githubusercontent.com/29010438/70196163-cfcfbd80-1742-11ea-9c36-ea8b1511cca3.png)

**提示的异常或者没有达到的效果**
![image](https://user-images.githubusercontent.com/29010438/70196195-ed9d2280-1742-11ea-9400-6eb40de30aa9.png)

**Comment by zhuangjiaju** [comment]
这个是bug,文档有写怎么解决。

**Comment by lliangbin** [comment]
@zhuangjiaju 哪里的文档讲有解决方案？

**Comment by Jasyl0519** [comment]
这个怎么解决？
