### ISSUE TITLE
如何向空行添加数据

### ISSUE THREAD

**Issue by zxk175** [alibaba/easyexcel#944]
![image](https://user-images.githubusercontent.com/10259995/70208119-aecd9380-1767-11ea-8b7a-6788c20af58d.png)

这是写入代码
![image](https://user-images.githubusercontent.com/10259995/70208209-e0def580-1767-11ea-8ad8-123cfff9b5df.png)

版本2.1.3

**Comment by pdkst** [comment]
先写入需要写入空行的数据就可以了

**Comment by zxk175** [comment]
> 先写入需要写入空行的数据就可以了

已经解决了

![image](https://user-images.githubusercontent.com/10259995/70297102-9cb32a00-1827-11ea-9135-ff5ec5da7b0f.png)
