### ISSUE TITLE
有没有使用模板导出功能呢？

### ISSUE THREAD

**Issue by jiang-jian-jian** [alibaba/easyexcel#945]
使用定制好的模板，再往模板里填充数据，最后生成excel文档。
类似freemarker、velocity模板导出excel的功能。
有些复杂的表格，使用模板的话会很方便。

**Comment by pdkst** [comment]
参考[官方demo-填充](https://alibaba-easyexcel.github.io/quickstart/fill.html)

**Comment by jiang-jian-jian** [comment]
类似这样的模板也可以实现吗？
![image](https://user-images.githubusercontent.com/38133323/70248368-bd429c00-17b5-11ea-8af4-085ac171276f.png)

**Comment by jiang-jian-jian** [comment]
> 参考[官方demo-填充](https://alibaba-easyexcel.github.io/quickstart/fill.html)

类似这样的模板也可以实现吗？

![image](https://user-images.githubusercontent.com/38133323/70248683-380bb700-17b6-11ea-9b98-920ddf011576.png)

**Comment by pdkst** [comment]
> > 参考[官方demo-填充](https://alibaba-easyexcel.github.io/quickstart/fill.html)
> 
> 看了demo,似乎如下图这样的模板实现不了？
> 
> ![image](https://user-images.githubusercontent.com/38133323/70248683-380bb700-17b6-11ea-9b98-920ddf011576.png)

这种还是推荐使用普通行写入+合并单元格比较快一些

**Comment by zhuangjiaju** [comment]
建议使用table 填充或者 用第三方开源项目：jxls
