### ISSUE TITLE
使用apache poi写3000合并列，消耗19分钟

### ISSUE THREAD

**Issue by zhouzach** [alibaba/easyexcel#951]
easyexecel支持分组的map数据结构吗？
目前使用的是Apache poi，实现的逻辑是这样的：
1.先从数据库取出数据，List<Object[]> dataList
Object[] 包含date字段，city字段，指标1，指标2

2. dataList根据date字段分组，得到rowMap，
dataList根据city字段分组，得到colMap

3.
3.1根据rowMap得到keySet：dates数组写第一列；
3.2根据colMap得到keySet：city数组，从第2列开始写数据的列头，因为每个city有两个指标数据，所以city列头是合并单元格；
3.3写完city列头，写指标列头（每个city下面都有相同的两个指标，比如count,prices）
3.4遍历city数组，通过colMap，rowMap，获取到city的某个date的两个指标，写数据

4.数据量：
2行：2019-11-10，2019-11-11
3000个城市，3000个合并列
平均耗时19分钟

Workbook使用的是SXSSFWorkbook
合并列使用的是
sheet.addMergedRegionUnsafe(region);

能否给一些优化建议，谢谢

**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by zhuangjiaju** [comment]
这个目前我也没遇到过。建议去poi stackoverfolw咨询。
