### ISSUE TITLE
CellData无法识别是哪一行、哪一列的数据

### ISSUE THREAD

**Issue by huangxfchn** [alibaba/easyexcel#954]
**建议描述**
建议在 `com.alibaba.excel.metadata.CellData` 添加`rowIndex`、`columnIndex`属性，分别区分这个cell是哪一行、哪一列的数据

**Comment by zhuangjiaju** [comment]
我研究下

**Comment by 791182746** [comment]
您好！目前没有此属性的情况下，如何获取columnIndex值？

**Comment by huangxfchn** [comment]
> 您好！目前没有此属性的情况下，如何获取columnIndex值？

没办法获取

**Comment by huangxfchn** [comment]
啥时候能支持呢，ping……

**Comment by zhuangjiaju** [comment]
最新版本已经在 CellData添加 ，非常感谢您的意见。

**Comment by huangxfchn** [comment]
好的，多谢大佬

**Comment by huangxfchn** [comment]
> 最新版本已经在 CellData添加 ，非常感谢您的意见。

具体怎样使用呢，能否在Excel对应的 pojo 中获取到该值
