### ISSUE TITLE
建议excel读取处理前置

### ISSUE THREAD

**Issue by tlyw** [alibaba/easyexcel#958]
**建议描述**
希望EasyExcel读取Excel调用可以再简单些(集合处理前置)..

// Java 8：

EasyExcel.read(fileName, DemoData.class, pageSize, pageList -> LOGGER.info("读取到数据:{}", JSON.toJSONString(pageList))).sheet().doRead();

// Java 7：

EasyExcel.read(fileName, DemoData.class, pageSize, new EasyExcelConsumer<List<T>>() {
        @Override
        public void accept(List<T> pageList) {
            LOGGER.info("读取到数据:{}", JSON.toJSONString(pageList));
        }
 }).sheet().doRead();

public class ReadTest {
    private static final Logger LOGGER = LoggerFactory.getLogger(ReadTest.class);
    @Test
    public void easyRead() {
        String fileName = TestFileUtil.getPath() + "demo" + File.separator + "demo.xlsx";
        // 这里 需要指定读用哪个class去读，然后读取第一个sheet 文件流会自动关闭
        int pageSize = 10;
        // Java 8：EasyExcel.read(fileName, DemoData.class, pageSize, pageList -> LOGGER.info("读取到数据:{}", JSON.toJSONString(pageList))).sheet().doRead();
        // Java 7
        EasyExcel.read(fileName, DemoData.class, pageSize, new EasyExcelConsumer<List<T>>() {
            @Override
            public void accept(List<T> pageList) {
                LOGGER.info("读取到数据:{}", JSON.toJSONString(pageList));
            }
        }).sheet().doRead();
    }
}

EasyExcelFactory.java
  /**
     * Build excel the read and batch consumer list
     *
     * @param pathName
     *            File path to read.
     * @param head
     *            Annotate the class for configuration information.
     * @param pageSize
     *            Batch count.
     * @param consumer
     *            Consumer Batch List
     * @return Excel reader builder.
     * 
     * @author www@yiynx.cn
     */
    public static <T> ExcelReaderBuilder read(String pathName, Class head, Integer pageSize, EasyExcelConsumer<List<T>> consumer) {
        return EasyExcel.read(pathName, head, new EasyExcelDataConsumerListener<>(pageSize, consumer));
    }

    /**
     * Build excel the read and batch consumer list
     *
     * @param inputStream
     *            Input stream to read.
     * @param head
     *            Annotate the class for configuration information.
     * @param pageSize
     *            Batch count.
     * @param consumer
     *            Consumer Batch List
     * @return Excel reader builder.
     * 
     * @author www@yiynx.cn
     */
    public static <T> ExcelReaderBuilder read(InputStream inputStream, Class head, Integer pageSize, EasyExcelConsumer<List<T>> consumer) {
        return EasyExcel.read(inputStream, head, new EasyExcelDataConsumerListener<>(pageSize, consumer));
    }

EasyExcelConsumer.java

package com.alibaba.excel.support;
public interface EasyExcelConsumer<T> {
    void accept(T t);
}

EasyExcelDataConsumerListener.java

package com.alibaba.excel.read.listener;

import java.util.ArrayList;
import java.util.List;

import com.alibaba.excel.context.AnalysisContext;
import com.alibaba.excel.event.AnalysisEventListener;
import com.alibaba.excel.support.EasyExcelConsumer;

/**
 * ConsumerEasyExcelDataListener
 * @author www@yiynx.cn
 *
 * @param <T> the type of the input to the operation
 * @see <a href="https://github.com/alibaba/easyexcel/blob/master/src/test/java/com/alibaba/easyexcel/test/demo/read/DemoDataListener.java">DemoDataListener</a>
 * @since 1.7
 */
public class EasyExcelDataConsumerListener<T> extends AnalysisEventListener<T> {
    private int pageSize = Integer.MAX_VALUE - 1; // default int max
    private List<T> list = new ArrayList<T>();
    private EasyExcelConsumer<List<T>> consumer;
    
    private EasyExcelDataConsumerListener() {
    }
    
    /**
     * ConsumerEasyExcelDataListener
     * @param pageSize
     * @param consumer
     */
    public EasyExcelDataConsumerListener(Integer pageSize, EasyExcelConsumer<List<T>> consumer) {
        this.pageSize = pageSize - 1;
        this.consumer = consumer;
    }
    
    /**
     * ConsumerEasyExcelDataListener
     * @param consumer
     */
    public EasyExcelDataConsumerListener(EasyExcelConsumer<List<T>> consumer) {
        this.consumer = consumer;
    }
    
    @Override
    public void invoke(T data, AnalysisContext context) {
        list.add(data);
        if (list.size() > pageSize) {
            consumer.accept(list);
            list.clear();
        }
    }
    
    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
        consumer.accept(list);
        list.clear();
    }

}

[EasyExcel读取简化(处理前置)](https://gitee.com/tanbei/codes/zx2lcw3n19udpsbe6mrqg97)

**Comment by littleantfly** [comment]
希望ExcelProperty中的converter 类型支持配置Spring Bean。因为有些数据需要通过bean来做出数据处理。

**Comment by zhuangjiaju** [comment]
这个升级到1.8 后会考虑。
