### ISSUE TITLE
能不能做个android版本的

### ISSUE THREAD

**Issue by akingyin1987** [alibaba/easyexcel#961]
**建议描述**

**Comment by zhuangjiaju** [comment]
这个以前很多人用过，但是没人知道有没有成功。主要我也不会安卓。需要一个人研究下。

**Comment by DocHuangys** [comment]
Android上用，前提太多jar包的冲突和依赖问题了；android 也没awt/font/FontRenderContext ，目前卡在这儿了，期待出个Android版本

**Comment by xuexixuexijpg** [comment]
> Android上用，前提太多jar包的冲突和依赖问题了；android 也没awt/font/FontRenderContext ，目前卡在这儿了，期待出个Android版本

我捣鼓了两天也卡在这了...
