### ISSUE TITLE
可以增加合并excel文件的功能

### ISSUE THREAD

**Issue by xjl456852** [alibaba/easyexcel#968]
**建议描述**
加入我有很多数据需要导出为excel文件,可能有200万条数据,我会通过多个不同的机器去执行生成excel文件任务,最后会生成大于2个文件的excel文件,我最终需要将多个文件合并到一起,最后生成两个excel文件,因为一个excel最多可以保存100零几万数据.计划每个excel保存100万数据.
easyexcel可以增加这个合并的操作.将多个零散的文件合并起来,利于管理.
谢谢

**Comment by zhuangjiaju** [comment]
这个需要自己书写。边读边写。
