### ISSUE TITLE
mac 下使用easyexcel 写入excel出现部分中文乱码

### ISSUE THREAD

**Issue by zhengyingj** [alibaba/easyexcel#97]

**Comment by zhengyingj** [comment]
使用mac 并使用easyexcel进行写入excel操作，出现部分中文乱码问题，
mac os版本：10.14
java版本：1.8
![image](https://user-images.githubusercontent.com/24710198/47332760-eb007a80-d6b2-11e8-855e-7a9238942b1f.png)

**Comment by jipengfei-jpf** [comment]
看下自己些时候的编码
