### ISSUE TITLE
@ExcelProperty works case sensitivity.

### ISSUE THREAD

**Issue by busrauman** [alibaba/easyexcel#974]
**异常代码**
```java
     @ExcelProperty(value = "Barkod")
     private String barcode;
```
**异常提示**
Is there any way to get excel headers without checking case sensitivity, for example, my column heading is "Barkod" that I've reported above, but I want a valid title without case sensitivity.
Because "Barkod", "barkod", "BarkoD" and so on. All combinations are the same and valid for the title.
**建议描述**
Thank you for your time

**Comment by zhuangjiaju** [comment]
This is not currently supported.Let's talk to the other members and add configuration variables.
