### ISSUE TITLE
关于写出Exce咨询l

### ISSUE THREAD

**Issue by feifei498536** [alibaba/easyexcel#978]
**代码**
 @Override
    public CellData convertToExcelData(Integer val, ExcelContentProperty excelContentProperty,GlobalConfiguration globalConfiguration){
        String fieldName = excelContentProperty.getHead().getFieldName();
        Class<?> declaringClass = excelContentProperty.getField().getDeclaringClass();
        Object bean=null;
        try {
            bean = declaringClass.newInstance();
        }catch (Exception e){
        }
        String dicName = DicExcelUtils.getDicName(fieldName, val,bean);
        return new CellData(CellDataTypeEnum.STRING,dicName); 
    }
   这里写你的代码
```
**异常提示**
如果我输出的单元格名称如果字段为空null 会报错.  我想写出单元格空如果解决
**建议描述**

**Comment by pdkst** [comment]
试试空字符串

**Comment by zhuangjiaju** [comment]
不应该 。请提供详细代码。为null 应该就是空单元格。

**Comment by zhuangjiaju** [comment]
目前是否已经解决，如果未解决请重新打开代码
