### ISSUE TITLE
com.alibaba.excel.exception.ExcelDataConvertException: Can not find 'Converter' support class LocalDateTime.

### ISSUE THREAD

**Issue by eric-chao** [alibaba/easyexcel#980]
**触发场景描述**

**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**
com.alibaba.excel.exception.ExcelDataConvertException: Can not find 'Converter' support class LocalDateTime.
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.doConvert(AbstractExcelWriteExecutor.java:108)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.convert(AbstractExcelWriteExecutor.java:93)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.converterAndSet(AbstractExcelWriteExecutor.java:39)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addJavaObjectToExcel(ExcelWriteAddExecutor.java:137)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addOneRowOfDataToExcel(ExcelWriteAddExecutor.java:65)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.add(ExcelWriteAddExecutor.java:51)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:61)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)

**Comment by eric-chao** [comment]
public class LocalDateTimeConverter implements Converter<LocalDateTime> {

	/**
	 * 不使用{@code @LocalDateTimeFormat}注解指定日期格式时,默认会使用该格式.
	 */
	private static final String DEFAULT_PATTERN = "yyyy-MM-dd HH:mm:ss";

	@Override
	public Class supportJavaTypeKey() {
		return LocalDateTime.class;
	}

	@Override
	public CellDataTypeEnum supportExcelTypeKey() {
		return CellDataTypeEnum.STRING;
	}

	/**
	 * 这里读的时候会调用
	 *
	 * @param cellData            excel数据 (NotNull)
	 * @param contentProperty     excel属性 (Nullable)
	 * @param globalConfiguration 全局配置 (NotNull)
	 * @return 读取到内存中的数据
	 */
	@Override
	public LocalDateTime convertToJavaData(CellData cellData, ExcelContentProperty contentProperty, GlobalConfiguration globalConfiguration) {
		LocalDateTimeFormat annotation = contentProperty.getField().getAnnotation(LocalDateTimeFormat.class);
		return LocalDateTime.parse(cellData.getStringValue(),
				DateTimeFormatter.ofPattern(Objects.nonNull(annotation) ? annotation.value() : DEFAULT_PATTERN));
	}


	/**
	 * 写的时候会调用
	 *
	 * @param value               java value (NotNull)
	 * @param contentProperty     excel属性 (Nullable)
	 * @param globalConfiguration 全局配置 (NotNull)
	 * @return 写出到excel文件的数据
	 */
	@Override
	public CellData convertToExcelData(LocalDateTime value, ExcelContentProperty contentProperty, GlobalConfiguration globalConfiguration) {
		LocalDateTimeFormat annotation = contentProperty.getField().getAnnotation(LocalDateTimeFormat.class);
		return new CellData(value.format(DateTimeFormatter.ofPattern(Objects.nonNull(annotation) ? annotation.value() : DEFAULT_PATTERN)));
	}
}

**Comment by eric-chao** [comment]
@Target({ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface LocalDateTimeFormat {
	/**
	 * 指定LocalDateTime转化的日期格式
	 * 例如 : "yyyy-MM-dd HH:mm:ss",导入导出都会将LocalDateTime转化为对应格式字符串
	 *
	 * @return 日期格式
	 */
	String value();
}

**Comment by eric-chao** [comment]
@ExcelProperty(value = "审核时间", converter = LocalDateTimeConverter.class)
	@LocalDateTimeFormat("yyyy-MM-dd HH:mm:ss")
	private LocalDateTime auditTime;

**Comment by zhuangjiaju** [comment]
你目前已经解决了么？

**Comment by geekerstar** [comment]
太棒了，大佬

**Comment by 1725636955** [comment]
最新版方法改变了

**Comment by Vetich** [comment]
> ```
> @ExcelProperty(value = "审核时间", converter = LocalDateTimeConverter.class)
> @LocalDateTimeFormat("yyyy-MM-dd HH:mm:ss")
> private LocalDateTime auditTime;
> ```

貌似还是有BUG 实际运行OK的？

**Comment by BruceAn1978** [comment]
使用converter指定class后，运行时仍然会报找不到LocalDateTime的转换器错误！！！

有人能够运行成功吗？

**Comment by xuzhitudev** [comment]
有错误的话尝试修改一下就可以了，新版本只是参数改了一下，原理一致
