### ISSUE TITLE
对于行列都很多的数据比如500x500这种，怎么写他的模型？

### ISSUE THREAD

**Issue by ShupengHu** [alibaba/easyexcel#981]
DemoData 里面的java读写模型都是按列来的，一列对应一个ExcelProperty. 那么碰到几百行几百列的数据，不可能给列都创建一个ExcelProperty。 有没有自动生成模型的方法？

现在官方给的例子都是带模型读写的，我百度以前不带模型读写的代码都会出现方法被弃用了。作者大哥能不能给我这个新手一个不用模型读写的EasyExcel的代码例子？

**Comment by pdkst** [comment]
参考[官方demo-动态头，实时生成头写入](https://alibaba-easyexcel.github.io/quickstart/write.html#%E5%8A%A8%E6%80%81%E5%A4%B4%EF%BC%8C%E5%AE%9E%E6%97%B6%E7%94%9F%E6%88%90%E5%A4%B4%E5%86%99%E5%85%A5)
