### ISSUE TITLE
表头不在第一行怎么读

### ISSUE THREAD

**Issue by gitzhangliang** [alibaba/easyexcel#982]
![360截图18141223293756](https://user-images.githubusercontent.com/30276946/70895505-08687480-202a-11ea-9398-08d1e84c879b.png)

**Comment by gitzhangliang** [comment]
![360截图18141223293756](https://user-images.githubusercontent.com/30276946/70895571-2930ca00-202a-11ea-8ed3-8c9a77e123d5.png)

**Comment by pdkst** [comment]
参考这个API`com.alibaba.excel.read.builder.ExcelReaderBuilder#headRowNumber`
