### ISSUE TITLE
2.1.4 读取所有格式相同的sheet 重复保存

### ISSUE THREAD

**Issue by forgetmeagain** [alibaba/easyexcel#985]
**触发场景描述**
读取所有格式相同的sheet重复保存
**触发Bug的代码**
// 按demo上面来写的
 String fileName = TestFileUtil.getPath() + "demo" + File.separator + "demo.xlsx";
    // 读取全部sheet
    // 这里需要注意 DemoDataListener的doAfterAllAnalysed 会在每个sheet读取完毕后调用一次。然后所有sheet都会往同一个DemoDataListener里面写
    EasyExcel.read(fileName, DemoData.class, new DemoDataListener()).doReadAll();
**提示的异常或者没有达到的效果**
sheet1  :   1,2
sheet2  :   3,4
最终保存在数据库 : 1,2,1,2,3,4

**Comment by pdkst** [comment]
`doAfterAllAnalysed()`只会调用一次，但是`DemoDataListener`只有一个对象，所以应该是调用结束你没有清除`DemoDataListener`中的list

**Comment by forgetmeagain** [comment]
哦哦 这样的啊
