### ISSUE TITLE
关于自定义颜色怎么使用RGB值的问题？

### ISSUE THREAD

**Issue by xgs0921** [alibaba/easyexcel#986]
经过调试发现：cell.getSheet().getWorkbook() 返回的是 SXSSFWorkbook 实现类.

poi中可以通过         HSSFPalette palette = wb.getCustomPalette();
        palette.setColorAtIndex(IndexedColors.RED.getIndex(), (byte) 231, (byte) 0, (byte) 18);
但是基于workbook 是 HSSFWorkbook 实现类。
想请教下怎么弄？

**Comment by xgs0921** [comment]
解决方式：
SXSSFWorkbook workbook = (SXSSFWorkbook) cell.getSheet().getWorkbook();
            XSSFColor myColor = new XSSFColor(new java.awt.Color(231, 0, 18));

**Comment by wesley5201314** [comment]
XSSFColor myColor = new XSSFColor(new java.awt.Color(231, 0, 18)); 使用该方法自定义RGB颜色之后，获取index一直都是0，这个请问你是怎么解决的。谢谢

**Comment by laokewang** [comment]
估计是不支持这种方式
