### ISSUE TITLE
关于图片写入的疑问运行t05WriteImage07

### ISSUE THREAD

**Issue by munan56** [alibaba/easyexcel#987]
在这个单元测试中提供了写入图片的功能，但是写入之后的**图片不在单元格中，改变单元格的大小，图片不会随着单元格改变**，原生的poi是可以固定在单元格内的，我觉的是一个bug

**Comment by zhuangjiaju** [comment]
这个需要研究下

**Comment by zhuangjiaju** [comment]
参照楼上

**Comment by munan56** [comment]
啊是easyexcel选择了不要移动在写excel的时候。
https://github.com/alibaba/easyexcel/blob/master/src/main/java/com/alibaba/excel/write/executor/AbstractExcelWriteExecutor.java#L144

anchor.setAnchorType(ClientAnchor.AnchorType.DONT_MOVE_AND_RESIZE);

**Comment by wenly2014** [comment]
> 啊是easyexcel选择了不要移动在写excel的时候。
> https://github.com/alibaba/easyexcel/blob/master/src/main/java/com/alibaba/excel/write/executor/AbstractExcelWriteExecutor.java#L144
> 
> anchor.setAnchorType(ClientAnchor.AnchorType.DONT_MOVE_AND_RESIZE);

这个怎么能改一下呢

**Comment by munan56** [comment]
> > 啊是easyexcel选择了不要移动在写excel的时候。
> > https://github.com/alibaba/easyexcel/blob/master/src/main/java/com/alibaba/excel/write/executor/AbstractExcelWriteExecutor.java#L144
> > anchor.setAnchorType(ClientAnchor.AnchorType.DONT_MOVE_AND_RESIZE);
> 
> 这个怎么能改一下呢

需要的话，可以修改一下AnchorType 的值
