### ISSUE TITLE
异步读取excel内容 应该如何进行校验内容并且退出呢

### ISSUE THREAD

**Issue by CocoMars** [alibaba/easyexcel#995]
**使用疑问**
当我异步使用监听器进行读取excel内容的时候 
我应该如何判断相关内容不满足我的规则条件下
退出当前读取呢

**Comment by pdkst** [comment]
easyExcel是同步的

**Comment by zhuangjiaju** [comment]
监听器有个`hasNext`方法 您返回false 就可以。
