### ISSUE TITLE
感谢easyexcel让excel操作变得更简单。不知道有没有计划封装word文档的操作

### ISSUE THREAD

**Issue by YellowWinterSun** [alibaba/easyexcel#998]
**建议描述**
这是我之前工作中，遇到比较复杂的word打印的需求。跟普通的那种简单的占位符替换的word打印不一样，在网上找不到比较好的源码，所以后来我自己再对Apache POI进行一层封装，以更好的满足更多的word打印需求。

最近看到easyexcel，使用和学习后觉得作者很优秀。不知道作者有没有兴趣，再做一个easyword之类的，对doc，docx文档的打印进行封装。

这是我之前封装的工具Git： https://github.com/YellowWinterSun/poiWordUtil
这是我对这套工具编写的csdn：https://blog.csdn.net/qq_29765371/article/details/84790086

当时研究了很久，发现POI对excel的支持已经挺不错了。但是对word的支持非常繁琐。
本人目前还在不断进修自己的java水平，这套工具的封装也只是在POI的基础上封装，暂时能力不足以研读POI底层和改源码以让POI在操作word上更加行如流水。希望能倚靠在巨人的肩膀，让自己更上一层楼

**Comment by cwt9562** [comment]
+1

**Comment by zhuangjiaju** [comment]
非常感谢您的意见，目前不会去开发。也希望您的工具越做越好。
