### ISSUE TITLE
如何获取表头字段就退出读操作，而不全部一行行读完？

### ISSUE THREAD

**Issue by JanLiao** [alibaba/easyexcel#999]
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by pdkst** [comment]
继承`AnalysisEventListener<T>`然后重写`hasNext()`

**Comment by louising** [comment]
> 继承`AnalysisEventListener<T>`然后重写`hasNext()`
这样会在读取到第一个Sheet后就退出，如果有多个sheet怎么办？

如果调用多次，会多次打开文件流，关闭文件流。
